### ISSUE TITLE
The symmetry analysis step can not determine the correct point group

### ISSUE THREAD

**Issue by gawcista** [deepmodeling/abacus-develop#1001]
## Describe the Bug
The symmetry analysis step can not determine the correct point group, especially for 2d materials. Some operations are missing.
Here are two examples:

Example 1: monolayer SnS (space group No.31 Pmn2_1, point group mm2 or C_2v)
ABACUS gives:  `POINT GROUP = C_1h`  (or C_s, m)
Example 1: monolayer SnS2 (space group No.164 P-3m1, point group -3m or D3d)
ABACUS gives:  `POINT GROUP = C_3v`  (or 3m)

VASP can give the correct result, which can be found in the attached OUTCAR files.

## To Reproduce
The input files and output log for vasp and abacus can be found here:
[symmetry_test.zip](https://github.com/deepmodeling/abacus-develop/files/8847111/symmetry_test.zip)

## Additional Context
Symmetry analysis is very important especially for topological materials. I hope ABACUS could fix this and add supports to symmetrize the forces and stress during relaxing steps.

**Comment by dyzheng** [comment]
In Example2(SnS2), you have switched position of Sn and S in STRU for ABACUS, so the structure is different with which VASP calculated.

**Comment by dyzheng** [comment]
In Example1(SnS), point group analysis is C_1h both in ABACUS and VASP, the C_2v result is combining with point group and space group. I am sorry that ABACUS only can analyze point group, but the consequence of ABACUS is correct. 
(There is the part of output of VASP)
![5d9b0b31207b3345ddf8a1ecd4243e7](https://user-images.githubusercontent.com/49852742/172316189-e1f06dcb-407b-4d2d-99b9-d17c4dd6086e.jpg)

**Comment by gawcista** [comment]
> In Example2(SnS2), you have switched position of Sn and S in STRU for ABACUS, so the structure is different with which VASP calculated.

Sorry it's my fault. There seems no problem in example 2

I wrote a code to perform transformation between STRU and vasp POSCAR files. At lease this issue helps me find a bug in my script :)

**Comment by gawcista** [comment]
> In Example1(SnS), point group analysis is C_1h both in ABACUS and VASP, the C_2v result is combining with point group and space group. I am sorry that ABACUS only can analyze point group, but the consequence of ABACUS is correct. (There is the part of output of VASP) ![5d9b0b31207b3345ddf8a1ecd4243e7](https://user-images.githubusercontent.com/49852742/172316189-e1f06dcb-407b-4d2d-99b9-d17c4dd6086e.jpg)

If the translation is ignored, the nonsymmorphic symmetries can not be included.
I think C_2v should be the correct explaination in this system. The  2-fold screw is very important in its electronic structure, which protects degeneracies. This is important. So will you add this support in future?
Besides, I noticed a typo in the log file 
![sym](https://user-images.githubusercontent.com/20947418/172327509-4512a34e-d481-4a23-8715-62e05c7c0c33.png)
The relavent code can be found in `source/module_symmetry/symmetry.cpp`

**Comment by dyzheng** [comment]
> If the translation is ignored, the nonsymmorphic symmetries can not be included. I think C_2v should be the correct explaination in this system. The 2-fold screw is very important in its electronic structure, which protects degeneracies. This is important. So will you add this support in future? Besides, I noticed a typo in the log file ![sym](https://user-images.githubusercontent.com/20947418/172327509-4512a34e-d481-4a23-8715-62e05c7c0c33.png) The relavent code can be found in `source/module_symmetry/symmetry.cpp`

Thanks for the typo feedback! 
The lack of space group analysis maybe influent the degeneracies, but one can set high enough accuracy to avoid this problem.
Adding space group analysis is definitely very important for ABACUS, but still need a voluntee to achieve that.
