### ISSUE TITLE
Stres_nl needs efficiency optimization

### ISSUE THREAD

**Issue by Chentao168** [deepmodeling/abacus-develop#1012]
## Describe Current Status and Possible Solution
Currently, in ABACUS Sto_MD, the time of pressure calculation accounts for 45%, which is 11% in QE and 18% in ABACUS PW_MD.

### Sto_MD in ABACUS
   Sto_Stress_PW       cal_stress          +188.36        22        +8.6      +45.      %
   Sto_Stress_Func     stres_nl            +188.14        11        +17.      +45.      %
### PW_MD in ABACUS
   Stress_PW           cal_stress          +26.31         11        +2.4      +7.1      %
   Stress_Func         stres_nl            +26.071        11        +2.4      +7.1      %
   Stress              cal_becp            +2.7919        22        +0.13     +0.76     %
   Stress              reduce_complex_double_pool+0.24733       22        +0.011    +0.067    %
   Stress              get_vkb1            +0.32168       132       +0.0024   +0.087    %
   Stress              dbecp_noevc         +0.6285        132       +0.0048   +0.17     %
   Stress              get_dbecp           +16.349        132       +0.12     +4.4      %
   Stress              get_final_step      +0.17084       132       +0.0013   +0.046    %
### PW_MD in QE
   no-stress/scf.out:     PWSCF        :   1m 3.42s CPU   1m 7.33s WALL
   stress/scf.out:     PWSCF        :   1m12.42s CPU   1m15.89s WALL

**Comment by dyzheng** [comment]
Can you upload your INPUT files?
Which version did you tested?

**Comment by dyzheng** [comment]
Please compare source/src_pw/sto_stress_pw.cpp:line317-339 with source/src_pw/stress_func_nl.cpp:line125-173 @Qianruipku
