### ISSUE TITLE
The calculation of the FORCE/STRESS in ABACUS is slower than QE 

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#1014]
I have run the Si16/Si64 system by ABACUS and QE, the time-cost of STRESS/FORCE by ABACUS is obviously larger than these by QE,

Result of Si16:
|MODULE|QE(s)|MODULE|ABACUS(s)|
|:----:|:----:|:----:|:----:|
|total time|10.79|total time|9.396|
|forces|0.14|Forces::cal_force_nl|0.38983|
|stress|0.31|Stress_PW::cal_stress|0.67537|

Result of Si64:
|MODULE|QE(s)|MODULE|ABACUS(s)|
|:----:|:----:|:----:|:----:|
|total time|633.93|total time|515.71|
|forces|2.95|Forces::cal_force_nl|23.533|
|stress|18.06|Stress_PW::cal_stress|31.108|

[si16.input.zip](https://github.com/deepmodeling/abacus-develop/files/8895741/si16.input.zip)
[si64.input.zip](https://github.com/deepmodeling/abacus-develop/files/8895742/si64.input.zip)

**Comment by dyzheng** [comment]
Reset parameters in case Si16: ecutwfc = 100Ry, kpoints = 4*4*4:
before optimized:
`
   Forces              cal_force_nl        12.493         1         12        2.3       %
   Stress_PW           cal_stress          19.116         1         19        3.5       %
`
 after #1015 :
`
   Forces              cal_force_nl        5.8774         1         5.9       1.1       %
   Stress_PW           cal_stress          11.012         1         11        2.1       %
`
This part still can be optimized in the future.
