### ISSUE TITLE
`diago_parallel_test` failed to run

### ISSUE THREAD

**Issue by caic99** [deepmodeling/abacus-develop#1024]
See https://github.com/deepmodeling/abacus-develop/runs/6875391462?check_suite_focus=true#step:5:3416 .
> 60: Test command: /bin/bash "diago_parallel_test.sh"
./hsolver_diago (No such file or directory)

**Comment by pxlxingliang** [comment]
UT "`hsolver_diago`" is not compiled, it is commented out in (https://github.com/deepmodeling/abacus-develop/blob/develop/source/src_pdiag/test/CMakeLists.txt) /source/src_pdiag/test/CMakeLists.txt . 
So UT "hsolver_diago" is not needed now? I am not sure.  If no, `diago_parallel_test` should also be deleted.
@dyzheng , do you know?
