### ISSUE TITLE
Invalid abacus_manual.pdf

### ISSUE THREAD

**Issue by xiaolixl** [deepmodeling/abacus-develop#103]
**Describe the bug**
The user manual abacus_manual.pdf file is not valid and cannot be opened.

**To Reproduce**
1. Go to 'ABACUS.develop' folder
2. GO to "documents" folder
2. Click on 'abacus_manual.pdf' or download the pdf by right-clicking -->save link as

**Expected behavior**
A pdf file that can be opened and readable.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: e.g. windows 10
 - Browser: Edge
 - Version: not clear

**Smartphone (please complete the following information):**
 - Version [e.g]

**Additional context**

**Comment by dyzheng** [comment]
You can try this path to get manual file for ABACUS:
http://abacus.ustc.edu.cn/uploadfile/abacus_manual_v2.1.0.pdf

**Comment by dyzheng** [comment]
solved.
