### ISSUE TITLE
How to run ABACUS after compilation？

### ISSUE THREAD

**Issue by haozhihan** [deepmodeling/abacus-develop#1035]
After I finish compiling the entire ABACUS software and prepare the INPUT file needed to run the software, I don't know how to run the software. This part seems to be missing from the documentation.

**Comment by caic99** [comment]
Hi @haozhihan ,
After putting all required input files under one folder, you can run command `mpirun -np 4 abacus` to perform calculation. You can replace '4' with your desired number of process, typically the result of `nproc`. 
This [example](https://github.com/deepmodeling/abacus-develop/tree/develop/examples/01a_Si_diamond_pw_scf) demonstrates a minimum case for ABACUS to run.
