### ISSUE TITLE
README.md is a bit confusing

### ISSUE THREAD

**Issue by haozhihan** [deepmodeling/abacus-develop#1036]
1. There are two sections in [README.md](https://github.com/deepmodeling/abacus-develop#table-of-contents) named Features, which focus on different content. 
2. There is some confusion about the relationship between [Functionalities](https://github.com/deepmodeling/abacus-develop#functionalities) and [Examples](https://github.com/deepmodeling/abacus-develop#examples). The content links contained in Functionalities point to the contents of Examples.
3. The link contained in [Examples](https://github.com/deepmodeling/abacus-develop#examples) `here` is not working.

**Comment by caic99** [comment]
Related: #514
