### ISSUE TITLE
Stress results inconsistency between ABACUS and QE

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#1041]
## Describe the Bug
The energy is exactly the same in one same calculation in ABACUS and QE: -553.64834923 Ry,
however,
the stress results are very different between ABACUS and QE.

## To Reproduce
1. cat issue/abacus_input/running_scf.log
2. cat issue/qe_input/scf.out

[issue.tar.gz](https://github.com/deepmodeling/abacus-develop/files/8988941/issue.tar.gz)

<img width="637" alt="ABACUS_stress" src="https://user-images.githubusercontent.com/18049272/175868076-940c900a-42a3-4b54-8a60-7562326967a0.png">
<img width="1083" alt="QE_stress" src="https://user-images.githubusercontent.com/18049272/175868085-da1994f6-dd99-4a45-8495-694061c131ad.png">

**Comment by dyzheng** [comment]
Thanks for your report, I will answer for that after tested this case.
