### ISSUE TITLE
Supporting for new GenELPA in ABACUS cmake tools

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#1042]
## Background

https://github.com/pplab/GenELPA

> GenELPA is a tool for solving generalized eigenvalues using ELPA as a computational core.

> [ELPA](https://elpa.mpcdf.mpg.de/index.html) is a high-performance and highly scalable direct eigensolvers solver, and is used in a variety of first-principles computing softwares. The program is developed at the Max Planck Institute, and is written in FORTRAN with a C interface.

> Since the first version was released in 2011, ELPA has used two APIs, a traditional interface used in 2016.05.004 and earlier versions, and a new interface that uses a handle to pass computational configuration parameters used in 2016.11.001 and later versions. With the new interface, ELPA adds functions for solving generalized eigenvalues directly and support for GPUs.

> We have previously made an extension to GenELPA for solving generalized eigenvalues, which provides functions for solving generalized eigenvalues directly as well as step-by-step solving and enhanced robustness in solving various matrices. The program is able to work stably in [ABACUS](https://abacus.ustc.edu.cn/).

> The new interface of ELPA already supports direct solving of generalized eigenvalues, but we found the following problems in the process of using it.

> 1. less stable calculations when solving certain matrices.

> 2. unnecessary screen output in some cases (version 2021.05.002).

We need compiling support for this GenELPA lib for ABACUS program.

**Comment by caic99** [comment]
Hi @dyzheng ,
I'm not sure if GenELPA is only a interface to ELPA, or it can be used without ELPA?
And, what is the required lib name?
Besides, does ABACUS support it now?

**Comment by dyzheng** [comment]
> Hi @dyzheng , I'm not sure if GenELPA is only a interface to ELPA, or it can be used without ELPA? And, what is the required lib name? Besides, does ABACUS support it now?

@caic99 
1. In my opinion, GenELPA is only a interface to ELPA, we should compile ELPA first and compile GenELPA next.
2. Another method to use this interface is move the GenELPA code to ABACUS.
3. Now, only ABACUS branch https://github.com/pplab/abacus-develop/tree/newelpa support it, I plan to merge the code to HSolver and add a new derived class for "DiagH" and named "DiagoGenELPA" to support both DiagoELPA and DiagoGenELPA in ABACUSv2.3.x.

**Comment by dyzheng** [comment]
Tests for GenELPA is lacking now, so the method should only be a optional method for users, we can use a macro "__GENELPA" to choose the using for GenELPA+ELPA or ELPA only.

**Comment by dyzheng** [comment]
This interface GenELPA is expected to solve problem in Issue #798
