### ISSUE TITLE
running of ABACUS that complied with GNU is much slower than that with intel  

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#1043]
I have complied ABACUS with GNU and intel oneapi, respectively,  and then run examples/performance/P000_si16_pw with `mpirun -np 2 abacus`. The time cost of repeated 4 times running are as below:

||GNU(s)|intel(s)|
|:----:|:----:|:----:|
|1|335|216|
|2|333|215|
|3|328|213|
|4|332|212|

The mainly difference is the h_psi/vloc/recip2real process, which is related to the FFT, 
![image](https://user-images.githubusercontent.com/91927439/175897147-41b4f111-5ea9-4fa9-9b6e-2ed1b76a9c41.png)

**Comment by dyzheng** [comment]
How many differences between FFTW3 in GNU and FFTW3 in oneAPI-mkl? @caic99

**Comment by caic99** [comment]
> How many differences between FFTW3 in GNU and FFTW3 in oneAPI-mkl? @caic99

The FFTW3 in oneAPI-MKL is a interface to it, which means the implementation might be significantly different. The MKL implementation is supported by Intel engineers, while the original FFTW3 is an open-source project. The performance result meets the expectation - MKL should be faster. (Personally, I don't know how fast can it be until today.)

> These wrappers enable using Intel® oneAPI Math Kernel Library Fourier transforms to improve the performance of programs that use FFTW without changing the program source code.  [Ref](https://www.intel.com/content/www/us/en/develop/documentation/onemkl-linux-developer-guide/top/appendix-b-support-for-third-party-interfaces/fftw-interface-support.html)

**Comment by pxlxingliang** [comment]
I also test calculations with LCAO basis, but this time the GNU complied ABACUS is a little faster than intel.
Run examples/performance/P100_si16_lcao, and time cost of repeated 4 times running are as below:
||GNU(s)|intel(s)|
|:----:|:----:|:----:|
|1|153|173|
|2|152|175|
|3|164|171|
|4|151|176|

The mainly difference is the `cal_gint` process
![image](https://user-images.githubusercontent.com/91927439/176068393-4c4d7766-427e-44f1-960b-dbf01c99f9ee.png)

**Comment by caic99** [comment]
The compiling of ABACUS is still using the `-O2` optimization level flag. Future works on different [build types](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html) is possible.

**Comment by caic99** [comment]
This issue might related to the inappropriate linking of MKL, and @baixiaokuang is investigating on it.

**Comment by caic99** [comment]
Hi @pxlxingliang ,
#1492 introduced a remarkable improvement on the parallel organism of grid interal module. Would you try again running these cases?

**Comment by pxlxingliang** [comment]
> Hi @pxlxingliang ,
> #1492 introduced a remarkable improvement on the parallel organism of grid interal module. Would you try again running these cases?

The timing of cal_gint is indeed faster than previous version, but the ABACUS complied by intel is still much slower than that complied by gnu. 

gnu:
<img width="643" alt="image" src="https://user-images.githubusercontent.com/91927439/204440935-1679f796-0e93-4601-972f-cd39b886a9da.png">

intel:
<img width="643" alt="image" src="https://user-images.githubusercontent.com/91927439/204441013-485857e1-bee9-4b20-86da-642349aaef84.png">

**Comment by caic99** [comment]
@pxlxingliang I'm trying to reproduce this result. It cost 107s with gcc compiler, and 110s with Intel compiler. Please note that  "Release" build type should be used for a better performance. I think this difference is acceptable.

**Comment by pxlxingliang** [comment]
> 

@caic99 I complied the ABACUS with command "cmake -B build && cmake --build build -j8", what does "Release" build mean? Should I set some additional compling options？

**Comment by caic99** [comment]
> @caic99 I complied the ABACUS with command "cmake -B build && cmake --build build -j8", what does "Release" build mean? Should I set some additional compling options？

@pxlxingliang Plz set `cmake -B build -DCMAKE_BUILD_TYPE=Release`. I will add docs on this option soon.

**Comment by pxlxingliang** [comment]
> > @caic99 I complied the ABACUS with command "cmake -B build && cmake --build build -j8", what does "Release" build mean? Should I set some additional compling options？
> 
> @pxlxingliang Plz set `cmake -B build -DCMAKE_BUILD_TYPE=Release`. I will add docs on this option soon.

@caic99  I re-complied ABACUS by following your sugguestion, but it can not be faster, the job still takes 132s. Can you complie with GNU in your machine, and then run the job? I want to know how long it takes on your machine.

**Comment by caic99** [comment]
> @pxlxingliang I'm trying to reproduce this result. It cost 107s with gcc compiler, and 110s with Intel compiler. Please note that "Release" build type should be used for a better performance. I think this difference is acceptable.

@pxlxingliang here

**Comment by pxlxingliang** [comment]
@caic99 I complied with GNU and also set  "-DCMAKE_BUILD_TYPE=Release", but the time consuming for that job is 107s. It seems has no obvious difference. In your machine, how long will it take, if not set CMAKE_BUILD_TYPE?

**Comment by caic99** [comment]
> @caic99 I complied with GNU and also set "-DCMAKE_BUILD_TYPE=Release", but the time consuming for that job is 107s. It seems has no obvious difference. 

The difference between setting different build types is notable when using Intel compiler. 

> In your machine, how long will it take, if not set CMAKE_BUILD_TYPE?

300 second.

**Comment by pxlxingliang** [comment]
@caic99 I can not reproduce the difference. Is the intel docker image updated recently? The docker image I used is a month ago.

**Comment by caic99** [comment]
> @caic99 I can not reproduce the difference. 

@pxlxingliang You mean the build type cannot affect the computing time with Intel compiler?

> Is the intel docker image updated recently? The docker image I used is a month ago.

No, the environemnt is consistent.

**Comment by pxlxingliang** [comment]
@caic99 
Previous results may affected by the setting of OMP_NUM_THREADS, which is not awared by me.
I have re-tested P000 by latest ABACUS develop version, the time cost in intel env is still less than that by GNU. Interesting, whether to set OMP_NUM_THREDS = 1 will affect the time for both intel and gnu.


|command|gnu|intel|
|:---:|:---:|:---:|
|mpirun -np 2 abacus|143.24|96.058|
|OMP_NUM_THREADS=1 mpirun -np 2 abacus|97.884|76.89|

**Comment by pxlxingliang** [comment]
I also run the P000 by Bohrium, the image is "registry.dp.tech/deepmodeling/abacus-intel:latest" and "registry.dp.tech/deepmodeling/abacus-gnu:latest" respectively.  The time cost is:


|command|gnu|intel|
|:---:|:---:|:---:|
|mpirun -np 4 abacus|19007.00|66.43|
|OMP_NUM_THREADS=1 mpirun -np 4 abacus|75.59|52.90|

The detail of the timing of jobs with command "OMP_NUM_THREADS=1 mpirun -np 4 abacus" is:
![image](https://user-images.githubusercontent.com/91927439/223920462-0e86c74b-7525-45fe-9785-4bbba8c1eefc.png)
The left one is for intel, and the right one is for gnu.

**Comment by caic99** [comment]
@pxlxingliang I think this result is acceptable. In our expectation, Intel compiler often gerenates codes with higher efficiency.
