### ISSUE TITLE
SCF converge is failed with broyden 

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#1049]
In this case, I do the scf calculation, and from step 13, the energy is nearly no change, and the mixed density seems also no update

![image](https://user-images.githubusercontent.com/91927439/176145103-3798368d-931b-4b30-b387-f6720c0e072c.png)

[example.zip](https://github.com/deepmodeling/abacus-develop/files/8999574/example.zip)

**Comment by caic99** [comment]
Duplicated in #530 .
