### ISSUE TITLE
 ABACUS output bug

### ISSUE THREAD

**Issue by sgyang345** [deepmodeling/abacus-develop#1075]
##  ABACUS output bug
out_wfc_lcao set 1, but ABACUS can not output wave functions coefficients.

## INPUT
#Parameters (5.LCAO)
out_wfc_lcao        1 #ouput LCAO wave functions

## To Reproduce
1. run ABACUS with  nscf

## Environment
- OS: CentOS Linux release 7.9.2009 (Core)

**Comment by dyzheng** [comment]
Thank you for your reporting, I have fixed this bug.
