### ISSUE TITLE
Documentation request for v2.3.0

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#1087]
I have several questions for using ABACUSv2.3.0:

- [x]  1. How can I calculate BSSE for molecular formation energy?
- [ ]  2. How can I calculate SOC effect?
- [x]  3. How can I print PDOS or PBANDS or wavefunction in real space?
- [ ]  4. How can I calculate DFT+U effect?
- [x]  5. How can I print Hamiltonian matrix in real space?
- [x]  6. How can I use FIRE method if I only want to do relax calculation?

**Comment by caic99** [comment]
@dyzheng SOC example
@wenfei-li DFT+U
Thanks!
