### ISSUE TITLE
ABACUS LCAO calculate berryphase issue

### ISSUE THREAD

**Issue by sgyang345** [deepmodeling/abacus-develop#1094]
## Describe the Bug
Berryphase errors are reported for LCAO calculations using ABACUS 2.3.0, but no errors are reported with 2.2.3 or earlier versions.
![2022-07-14_20-57](https://user-images.githubusercontent.com/68679106/178987741-23872dda-4821-414b-88d7-b1de0c56f8a6.png)

## To Reproduce
1. run ABACUS-2.3.0 with berryphase of  ABACUS's example (PbTiO3)

## Environment
- OS: CentOS Linux release 7.9.2009 (Core)

**Comment by dyzheng** [comment]
Thanks for your report, I will fixed this bug.
