### ISSUE TITLE
hybrid functional calculation with exx_separate_loop=0 does not work

### ISSUE THREAD

**Issue by ouqi0711** [deepmodeling/abacus-develop#1106]
## Describe the issue
When running hybrid functional with exx_separate_loop=0, the program will be terminated after the init SCF cycle (i.e., non-hybrid SCF calculation).

## Expected behavior
The job should run successfully until the SCF converges, as it did in former versions (v2.1-). 

## To Reproduce
This is the input file:

[test_sic.zip](https://github.com/deepmodeling/abacus-develop/files/9148508/test_sic.zip)
This is the current on-screen output:
Wed Jul 20 17:27:50 2022
MAKE THE DIR         : OUT.ABACUS/
dft_functional readin is: pbe0
dft_functional in pseudopot file is: PBE
In Pseudopot_upf::read_pseudo_header : dft_functional from INPUT does not match that in pseudopot file
Please make sure this is what you need
dft_functional readin is: pbe0
dft_functional in pseudopot file is: PBE
In Pseudopot_upf::read_pseudo_header : dft_functional from INPUT does not match that in pseudopot file
Please make sure this is what you need
 UNIFORM GRID DIM     : 40 * 40 * 40
 UNIFORM GRID DIM(BIG): 20 * 20 * 20
 DONE(0.0197612  SEC) : SETUP UNITCELL
 DONE(0.020428   SEC) : INIT K-POINTS
 ---------------------------------------------------------
 Self-consistent calculations for electrons
 ---------------------------------------------------------
 SPIN    KPOINTS         PROCESSORS  NBASE       
 1       36              2           26          
 ---------------------------------------------------------
 Use Systematically Improvable Atomic bases
 ---------------------------------------------------------
 ELEMENT ORBITALS        NBASE       NATOM       XC          
 Si      2s2p1d-8au      13          1           
 C       2s2p1d-8au      13          1           
 ---------------------------------------------------------
 Initial plane wave basis and FFT box
 ---------------------------------------------------------
 DONE(0.0250896  SEC) : INIT PLANEWAVE
 DONE(0.0269687  SEC) : INIT CHARGE
 START POTENTIAL      : atomic
 DONE(0.0620499  SEC) : INIT POTENTIAL
 -------------------------------------------
 SELF-CONSISTENT : 
 -------------------------------------------
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
 GE1    -2.613604e+02  0.000000e+00   2.764e-01  1.360e+00  
 GE2    -2.622291e+02  -8.686823e-01  7.604e-02  1.367e+00  
 GE3    -2.622311e+02  -2.017363e-03  4.277e-02  1.357e+00  
 GE4    -2.622320e+02  -8.289866e-04  2.102e-03  1.365e+00  
 GE5    -2.622320e+02  -5.843390e-06  7.184e-04  1.354e+00  
 GE6    -2.622320e+02  -1.423338e-06  1.320e-04  1.385e+00  
 GE7    -2.622320e+02  -2.861743e-08  1.315e-05  1.398e+00  
 GE8    -2.622320e+02  8.658054e-09   1.558e-05  1.341e+00  
 GE9    -2.622320e+02  -5.499221e-09  3.178e-07  1.345e+00  
 GE10   -2.622320e+02  -1.938320e-10  1.487e-07  1.373e+00  
 GE11   -2.622320e+02  -3.830719e-10  3.445e-08  1.359e+00  
abacus: /root/abacus-develop/source/module_base/complexmatrix.cpp:145: ModuleBase::ComplexMatrix ModuleBase::operator+(const ModuleBase::ComplexMatrix &, const ModuleBase::ComplexMatrix &): Assertion `m1.nr == m2.nr' failed.
abacus: /root/abacus-develop/source/module_base/complexmatrix.cpp:145: ModuleBase::ComplexMatrix ModuleBase::operator+(const ModuleBase::ComplexMatrix &, const ModuleBase::ComplexMatrix &): Assertion `m1.nr == m2.nr' failed.

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 1147284 RUNNING AT iZ8vb3owvtboyaqprkftd1Z
=   KILLED BY SIGNAL: 6 (Aborted)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 1 PID 1147285 RUNNING AT iZ8vb3owvtboyaqprkftd1Z
=   KILLED BY SIGNAL: 6 (Aborted)
===================================================================================

**Comment by wenfei-li** [comment]
Has this issue been addressed? I can take a look at it if needed.

**Comment by wenfei-li** [comment]
It seems this issue has been resolved.
