### ISSUE TITLE
The ready-for-use docker images does not work

### ISSUE THREAD

**Issue by Fadelis98** [deepmodeling/abacus-develop#1117]
## Describe the Bug

when running the docker image I get the following message:

[99f4cb284bbf:00007] PMIX ERROR: ERROR in file ../../../src/runtime/pmix_progress_threads.c at line 269
[99f4cb284bbf:00007] PMIX ERROR: ERROR in file ../../../src/runtime/pmix_progress_threads.c at line 393
\--------------------------------------------------------------------------
It looks like pmix_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during pmix_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
PMIX developer):

  pmix_progress_thread_start failed
  --> Returned value -1 instead of PMIX_SUCCESS
\--------------------------------------------------------------------------

[99f4cb284bbf:00007] PMIX ERROR: ERROR in file ../../../src/server/pmix_server.c at line 629

I have cloned the src to my home path ,so the command I used is:
`sudo docker run -v ~/abacus-develop/tests/integrate:/workspace -w /workspace/101_PW
_15_f_pseudopots -it 99a`
where 99a is the image ID for abacus.

## To Reproduce

Both the Latest version and 2.3.0 have the problem, earlier versions haven't been tested yet.
1. `docker pull ghcr.io/deepmodeling/abacus:2.3.1`
2. `docker run -v ~/abacus-develop/tests/integrate:/workspace -w /workspace/101_PW
_15_f_pseudopots -it <the docker image name/id>`

## Environment
- OS: CenOS 7.0
- Docker: Docker version 20.10.12, build e91ed57

**Comment by caic99** [comment]
Hi @Fadelis98 ,
I'm running with command:
```bash
docker run -v ~/abacus-develop/tests/integrate:/workspace -w /workspace/101_PW_15_f_pseudopots ghcr.io/deepmodeling/abacus:2.3.1
```
but the program runs well. The problem might lies elsewhere regarding the collaboration between docker and OpenMPI.

**Comment by Fadelis98** [comment]
Thanks for checking it, I'm still trying to solve the problem

> Hi @Fadelis98 , I'm running with command:
> 
> ```shell
> docker run -v ~/abacus-develop/tests/integrate:/workspace -w /workspace/101_PW_15_f_pseudopots ghcr.io/deepmodeling/abacus:2.3.1
> ```
> 
> but the program runs well. The problem might lies elsewhere regarding the collaboration between docker and OpenMPI.

**Comment by Fadelis98** [comment]
some updates, may helpful for you developers @caic99 
I have tried changing my MPI environment to fix this problem. Now I have installed Intel oneapi base toolkit and HPC toolkit on my system, **and then got new error**.
First, I run the default command:
`~% sudo docker run -v ~/abacus-develop/tests/integrate:/workspace -w /workspace/101_PW_15_f_pseudopots ghcr.io/deepmodeling/abacus:latest`

It first comes with warning:
`WARNING: Total thread number on this node mismatches with hardware availability. This may cause poor performance.`
`Info: Local MPI proc number: 112,OpenMP thread number: 56,Total thread number: 6272,Local thread limit: 112`

Then i see the `abacus`  welcome message and execution information, followed by VERY LONG error messages:
![image](https://user-images.githubusercontent.com/43640976/182559214-2be1be42-fca4-49fd-b411-717a5a617823.png)
The error messages are duplicated:
![image](https://user-images.githubusercontent.com/43640976/182559347-86debff1-8ad5-4059-8b61-74dc8e8a4f09.png)

To investigate this, i tried to run abacus with different mpirun commands:

`~% sudo docker run -v ~/abacus-develop/tests/integrate:/workspace -w /workspace/101_PW_15_f_pseudopots -it ghcr.io/deepmodeling/abacus:latest bash`
`root@1f2481ae3a44:/workspace/101_PW_15_f_pseudopots# mpirun -np 64 abacus`
The result is :
`WARNING: Total thread number on this node mismatches with hardware availability. This may cause poor performance.`
`Info: Local MPI proc number: 32,OpenMP thread number: 56,Total thread number: 1792,Local thread limit: 112`
The OpenMP created abnormal num of threads. Since my machine has 2*56 cores, It seems that the OpenMP didn't recognized my environment correctly, and **`abacus` went wrong when too much threads are created.**

I tried to limit the number of threads: `mpirun -np 2 abacus`
warning still exist:
`WARNING: Total thread number on this node mismatches with hardware availability. This may cause poor performance.`
`Info: Local MPI proc number: 2,OpenMP thread number: 2,Total thread number: 4,Local thread limit: 112`
and this time OpenMP created too little threads, but abacus runs well.
![image](https://user-images.githubusercontent.com/43640976/182562296-a492f9c6-2296-480d-8e7e-e744eab7f61c.png)

It seems that the docker image is not compatible with PCs with multi cpus, or maybe one certain mpi version is needed?

**Comment by caic99** [comment]
Hi @Fadelis98 ,
To avoid thread oversubscribbing, you may want to set an environment variable to limit OpenMP threads, like 
`OMP_NUM_THREADS=1 mpirun -np 4 abacus`. Would you try again with this command.

> It seems that the docker image is not compatible with PCs with multi cpus

Do you mean your machine has 2 CPU sockets on one board? Docker has a really poor support regarding MPI, especially MPI running between nodes(in this case, singularity is a better approach), and perhaps this is your case. Personally I don't have too much experience on multi-socket motherboards running MPI programs in docker. If you are experienced in containers(and have enough time), you can try using singularity.
The docker image for ABACUS is aimed for a rapid experience to get your hands on, but not for massive production cases. I'm very happy to hear from you that the image works for basic cases; however, I would suggest you compiling ABACUS from source file and running in bare-metal(i.e. not in docker) to avoid potential issues like this and gain a better performace. Would you refer to our [installation guide](https://github.com/deepmodeling/abacus-develop/blob/develop/docs/install.md) for compiling ABACUS.
Thanks for your feedback!
