### ISSUE TITLE
Diagonal parallel test fails to detect failures

### ISSUE THREAD

**Issue by caic99** [deepmodeling/abacus-develop#1125]
### Describe the bug

In the [DiagoDavRealSystemTest](https://github.com/deepmodeling/abacus-develop/runs/7555374655?check_suite_focus=true#step:5:2729), the program received a segfault, but the test still passed.

**Comment by pxlxingliang** [comment]
Thanks for your finding. The command `mpirun -np $i ./HSolver_dav` in the bash script is running error. I will fix it by adding an exit in the script when the execute of the command is abnormal.
