### ISSUE TITLE
Docs contain undocumented but used keywords

### ISSUE THREAD

**Issue by caic99** [deepmodeling/abacus-develop#1141]
@dyzheng There are still some keywords which I can not find
<img width="392" alt="nlHWmuFMMv" src="https://user-images.githubusercontent.com/78061359/182554268-ad6abd3d-9b29-41fd-b910-db53b884b385.png">

_Originally posted by @caic99 in https://github.com/deepmodeling/abacus-develop/issues/1140#issuecomment-1203609178_

**Comment by caic99** [comment]
@pxlxingliang Would you check the status of this issue?

**Comment by pxlxingliang** [comment]
Except for 'md_t', links of other keywords are worked.
'md_t' is deleted in #1230

**Comment by caic99** [comment]
Fixed by #1230.
