### ISSUE TITLE
Errors in TDDFT code

### ISSUE THREAD

**Issue by caic99** [deepmodeling/abacus-develop#1154]
https://github.com/deepmodeling/abacus-develop/blob/0cdc725b9057ca729f487f800029ad2fae058759/source/module_esolver/esolver_ks_lcao_tddft.cpp#L390

& has lower precedence than >=; >= will be evaluated first. I think this '&' should be replaced with "&&".

**Comment by dyzheng** [comment]
@lyb9812

**Comment by lyb9812** [comment]
#1161
