### ISSUE TITLE
The calculation terminates abnormally for ABACUS 2.3.2 PW

### ISSUE THREAD

**Issue by sgyang345** [deepmodeling/abacus-develop#1162]
### Describe the bug

If one try to do the nscf calculation of PW with ABACUS 2.3.2, the program will terminates abnormally, it is shown in the following figure.

### Expected behavior

Termination of the program：
![2022-08-09_15-37](https://user-images.githubusercontent.com/68679106/183592006-f901a6d7-0f50-435b-81a2-2a48b4b51679.png)

### To Reproduce

1. Clone the source coda from “https://github.com/deepmodeling/abacus-develop/tree/v2.3.2”
2. The options of make with Makefile.vars and Makefile.vars are as follows.
3. build ABACUS with Intel 2020 and so on.
4. run ABACUS with Intel 2020 mpirun
[Makefile.zip](https://github.com/deepmodeling/abacus-develop/files/9288342/Makefile.zip)

### Environment

OS: Ubuntu 18.04.6 LTS
Compiler: icc version 19.1.3.304 (gcc version 7.5.0 compatibility)

**Comment by wenfei-li** [comment]
@dyzheng are you planning to look at this? If not I'll take a look.
possibly related to your reconstruction work ...

**Comment by dyzheng** [comment]
> @dyzheng are you planning to look at this? If not I'll take a look. possibly related to your reconstruction work ...

Maybe you are right, but I have tried this case but cannot reproduct the same error, maybe we should construct the same environment first.

**Comment by wenfei-li** [comment]
> > @dyzheng are you planning to look at this? If not I'll take a look. possibly related to your reconstruction work ...
> 
> Maybe you are right, but I have tried this case but cannot reproduct the same error, maybe we should construct the same environment first.

Sure. I'll have a try

**Comment by dyzheng** [comment]
> > > @dyzheng are you planning to look at this? If not I'll take a look. possibly related to your reconstruction work ...
> > 
> > 
> > Maybe you are right, but I have tried this case but cannot reproduct the same error, maybe we should construct the same environment first.
> 
> Sure. I'll have a try

Thanks a lot! This is his test case.
[nscf_test.zip](https://github.com/deepmodeling/abacus-develop/files/9289156/nscf_test.zip)

**Comment by wenfei-li** [comment]
this issue has been solved. it is related to pw_seed
