### ISSUE TITLE
The convergence of SCF in AIMD is too slow 

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#1164]
### Describe the bug

The AIMD are performed on a serial of Al structures, and the number of step for the convergence of SCF are too large. Some AIMD step even need more than 10 steps to converge SCF.

<img width="427" alt="image" src="https://user-images.githubusercontent.com/91927439/183794136-fc820b03-9620-44c0-8866-d237429357d0.png">
<img width="428" alt="image" src="https://user-images.githubusercontent.com/91927439/183794124-95034899-481c-4d08-8bec-6ec6c56ea530.png">

I catch one of the structure, and run the same jobs with QE. In QE, except for the first AIMD step whose SCF convergence step number is 10, the SCF convergence step number of latter AIMD steps are only about 1-3. 
[al.zip](https://github.com/deepmodeling/abacus-develop/files/9295891/al.zip)

### Expected behavior

The convergence of SCF in AIMD should be faster

### To Reproduce

None

### Environment

None

### Additional Context

None

**Comment by YuLiu98** [comment]
There are some errors in INPUT parameters:
1. MD time step is specified by `md_dt` instead of `md_tfreq`, which is used in Nose Hoover Chain.
2. If not specified, atomic velocities in QE is set to zero, and cannot be controlled by `tempw`, which is used in nvt. Thus, `md_tfirst` in ABACUS  should be set to zero to be consistent with QE.

After correcting these two points, the convergence of SCF in AIMD is the same with QE.

**Comment by pxlxingliang** [comment]
@YuLiu98 Yes, there have some misunderstand of the key word. 
The previous jobs actually have the md step of a default value that is 1 fs, and a modified md_tfreq of 0.1 whose default value is 0.025. The md_type is set to be 0, which means a NVE job, so md_tfreq has no impact.

The previous results are also abnormal for the NVE job with md step of 1fs.

**Comment by pxlxingliang** [comment]
@YuLiu98 When I set the md_tfirst to be 0, the convergence of SCF is indeed fast, but when temperature is higher, such as 50 and 100 K, the convergence is bad. But in QE, the convergence are seems good whatever the temperature is 50 or 100 K (ion_temperature = 'initial').

step number of the convergence of SCF
|temperature(K)|abacus|qe|
|:----:|:----:|:----:|
|0|13/1/3/3/3/3|11/3/3/3/3/3|
|50|11/6/11/16/11/10|11/6/4/4/3/4|
|100|9/6/11/11/11/6|11/6/5/5/5/5|

[al.zip](https://github.com/deepmodeling/abacus-develop/files/9305798/al.zip)
