### ISSUE TITLE
BFGS cell optimization fail in abacus but not in qe with the same parameters in a specific example

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#1166]
### Describe the bug

BFGS cell optimization fail in abacus but not in qe with the same parameters in a specific example.

### Expected behavior

Expect success in abacus as well.

### Additional Context

[abacus.tar.gz](https://github.com/deepmodeling/abacus-develop/files/9297334/abacus.tar.gz)
[qe.tar.gz](https://github.com/deepmodeling/abacus-develop/files/9297335/qe.tar.gz)

**Comment by wenfei-li** [comment]
A new cg method has been implemented. A new bfgs relaxation scheme might be done some time in the future, but not now.

**Comment by mohanchen** [comment]
agree
