### ISSUE TITLE
Why is TDDFT done as MD?

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#1171]
### Describe Current Status and Possible Solution

It seems we are now running TDDFT by faking a MD run, the INPUT for running TDDFT is something like this:

```
calculation             md
tddft                   1

md_type         0
md_dt                   0.05
```

which is pretty confusing and can be misleading for users.

Furthermore, a bigger problem for this treatment of TDDFT is that we will not be able to run MD along with TDDFT.

From the aspect of code structure, TDDFT is done on a fixed configuration, therefore it should be put in the electronic structure layer, not on the outer layer which involves motion of atoms/cells (which includes MD & relaxation).
That way we also don't need to worry about preserving wavefunctions across MD steps ...

**Comment by lyb9812** [comment]
Yes, the input is confusing now . I will change "calculation" to "tddft" and hide "tddft","md_type".  TDDFT use the last step's wavefunctions to calculate this step's wavefunctions , so I need to preserve wavefunctions. For motion of atoms, TDDFT uses the code of MD NVE.

**Comment by wenfei-li** [comment]
> Yes, the input is confusing now . I will change "calculation" to "tddft" and hide "tddft","md_type". TDDFT use the last step's wavefunctions to calculate this step's wavefunctions , so I need to preserve wavefunctions. For motion of atoms, TDDFT uses the code of MD NVE.

Is it possible to do TDDFT in the same electronic step as DFT? Just like for hybrid functionals, we first do a SCF with PBE, then update EXX and run another SCF. I think with a similar treatment, it will be possible to do TDDFT right after DFT, using the function do_after_converge.

**Comment by wenfei-li** [comment]
ok got it
