### ISSUE TITLE
Fault when number of cores are larger than z fft grids.

### ISSUE THREAD

**Issue by Qianruipku** [deepmodeling/abacus-develop#1181]
### Describe the bug

[Htest.tar.gz](https://github.com/deepmodeling/abacus-develop/files/9386200/Htest.tar.gz)
if we use mpirun -np 16 abacus, error occurs:
![image](https://user-images.githubusercontent.com/76200646/185727795-2b514301-f1cf-4df2-b8d3-ff3802ce4d46.png)
However previous commit 7b86acbeb842e4dc52f8d03f5f573bfe3541b406 is OK:
![image](https://user-images.githubusercontent.com/76200646/185727842-0db2e3c7-4f0c-4178-9a21-ba81e2da3f61.png)

**Comment by Qianruipku** [comment]
Two things we need to do:
1. fix it
2. add integral tests.

**Comment by Qianruipku** [comment]
@dyzheng 
veff_pw.cpp
![image](https://user-images.githubusercontent.com/76200646/185727892-6b48b85f-2eb0-4324-8b72-81abe79cfee0.png)
segmental  fault comes from it
this->veff[0](current_spin, 0).c= null;
double* current_veff = &(this->veff[0](current_spin, 0).c[0]) 
Besides it, probably, there are some other problems.

**Comment by dyzheng** [comment]
> @dyzheng veff_pw.cpp ![image](https://user-images.githubusercontent.com/76200646/185727892-6b48b85f-2eb0-4324-8b72-81abe79cfee0.png) segmental fault comes from it this->veff[0](current_spin, 0).c= null; double* current_veff = &(this->veff[0](current_spin, 0).c[0]) Besides it, probably, there are some other problems.

Thanks for your report, I will solve it.

**Comment by Qianruipku** [comment]
Besides, we have these problems when running Autotest.sh with 36 cores: 
![image](https://user-images.githubusercontent.com/76200646/185732939-6fcd7225-db12-4ec3-a7cf-da5f46fb54a5.png)
Problems in SDFT can be ignored since random numbers are different.
