### ISSUE TITLE
Feature lists in docs should be updated

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#1191]
### Describe Current Status and Possible Solution

- [ ] Feature of Implicit Solvation model method is lack in documentation
- [ ] Feature of Stochastic PW has improved some functions, such as DOS, which are lack in documentation 
- [ ] Feature of SOC is lack in documentation
- [ ] Feature of DFT+U is lack in documentation

**Comment by caic99** [comment]
Hi @dyzheng ,
Would you assign corresponding code owner for each term?
Thanks.

**Comment by wenfei-li** [comment]
check #514 for more
