### ISSUE TITLE
memory leak in tddft case

### ISSUE THREAD

**Issue by lyb9812** [deepmodeling/abacus-develop#1197]
### Describe the bug

For a large system (64Si+Au), the program break off after running 5400 steps. (It needs to take about three days for 16 cores)

### To Reproduce

Run the case in attachment.

### Environment

Ubuntu 20.04.1 OneAPI 2021.3.0

### Additional Context

[64SiAu.tar.gz](https://github.com/deepmodeling/abacus-develop/files/9477233/64SiAu.tar.gz)

**Comment by caic99** [comment]
Hi @lyb9812 ,
Does "the program break off" means it encountered an OOM error?
I have fixed #1388 . Would you mind try again using latest codes?

**Comment by caic99** [comment]
@lyb9812 I'm trying to reproduce with the input file you provided, and there is a error :` THE PARAMETER NAME 'tddft' IS NOT USED!`.

**Comment by lyb9812** [comment]
> @lyb9812 I'm trying to reproduce with the input file you provided, and there is a error :` THE PARAMETER NAME 'tddft' IS NOT USED!`.

Ok, I will retry it . The input file is changed from "tddft 1" to "esolver_type tddft".
