### ISSUE TITLE
SCF gets stuck in some parallel schemes

### ISSUE THREAD

**Issue by Chentao168** [deepmodeling/abacus-develop#1198]
### Describe the bug

Each node has 96 cores in Beijing Super Cloud Computing Center.
If I use 1 node 90 cores or 2 nodes 192 cores, it will work fine; but if I use 2 nodes 120 cores it will get stuck.

### To Reproduce

The source code: ABACUS v2.3.4
My calculation case: [25wk12.46-bug.zip](https://github.com/deepmodeling/abacus-develop/files/9477634/25wk12.46-bug.zip)

### Environment

OS: Beijing Super Cloud Computing Center
Compiler: Intel 2022.1

**Comment by dyzheng** [comment]
1. Please check your STRU, atoms is too close with others.

**Comment by dyzheng** [comment]
2. I found the spending time in 90 cores is smaller than which in 192 cores, it is not reasonable. you can do a simple test that "2 nodes, one of them use 90 cores, another use 1 core", compare it with 90 cores result.

**Comment by dyzheng** [comment]
> 1. Please check your STRU, atoms is too close with others.

Firstly, do you convert STRU from POSCAR? STRU for ABACUS has units Bohr but POSCAR for VASP use units Angstrom.@Chentao168

**Comment by Chentao168** [comment]
The STRU comes from MD simulations, so there will be atoms close to each other, which should not affect the results.
