### ISSUE TITLE
Temperature-dependent XC-functionals are needed

### ISSUE THREAD

**Issue by Chentao168** [deepmodeling/abacus-develop#1209]
### Background

To describe warm dense matter, we need to use temperature-dependent XC-functionals.

### Describe the solution you'd like

Use libxc in https://www.tddft.org/programs/libxc/functionals/ id=318 and 259.

**Comment by wenfei-li** [comment]
The way to do this is by setting dft_functional keyword in INPUT to LDA_XC_CORRKSDT+LDA_XC_KSDT. Please let me know if that works for you.

**Comment by wenfei-li** [comment]
Please also check out the description of 'dft_functional' INPUT parameter in our online documentation: https://github.com/deepmodeling/abacus-develop/blob/develop/docs/input-main.md#dft_functional
