### ISSUE TITLE
link error when build with cmake

### ISSUE THREAD

**Issue by Fadelis98** [deepmodeling/abacus-develop#1216]
### Describe the bug

follow the install guide, when cmake --build error occurs:

![image](https://user-images.githubusercontent.com/43640976/189059235-dbd36091-aaed-4d84-9b86-cd0cc806e666.png)

### To Reproduce

use the latest release of abacus and use cmake to configure it

### Environment

OS: CenOS7
compiler:　GNU C++14 (GCC) version 9.3.1 20200408 (Red Hat 9.3.1-2) (x86_64-redhat-linux)，GMP version 6.0.0, MPFR version 3.1.1, MPC version 1.0.1, isl version isl-0.16.1-GMP
Dependencies: Intel Oneapi toolkit with mkl

In CMakeOutput.log, we can see the information

![image](https://user-images.githubusercontent.com/43640976/189061457-fbd45025-66ac-454a-afaf-452da4b08b8c.png)
![image](https://user-images.githubusercontent.com/43640976/189061863-4dd93b9d-58c0-4395-99ab-d4782002cc33.png)

**Comment by caic99** [comment]
Hi @Fadelis98 ,
If you are using Intel oneAPI toolkit with MKL, it is suggested to use Intel C++ compilers and Intel MPI as well.

**Comment by Fadelis98** [comment]
> Hi @Fadelis98 , If you are using Intel oneAPI toolkit with MKL, it is suggested to use Intel C++ compilers and Intel MPI as well.

it works now, thanks!
By the way, after i successfully installed, can I remove the source code dir now?

**Comment by caic99** [comment]
> it works now, thanks! 

Anytime!

> By the way, after i successfully installed, can I remove the source code dir now?

Sure. You can keep the executable and remove source codes. And don't forget to use the `mpirun` from Intel MPI.
