### ISSUE TITLE
error when building with USE_CUSOLVER_LCAO

### ISSUE THREAD

**Issue by Fadelis98** [deepmodeling/abacus-develop#1220]
### Describe the bug

I use intel oneapi toolchain(including compliers ,mpi and MKL) to build abacus, and the gcc version on the server is 9.3.

I've successfully compiled and run abacus with USE_CUDA enabled and with no gpu support respectively, but failed to build with USE_CUSOLVER_LCAO

![image](https://user-images.githubusercontent.com/43640976/189306805-29ec8c37-268b-4ff0-aa69-fc4a3f762afa.png)

### To Reproduce

download v2.3.5 src and compile with cmake, select the support for USE_CUSOLVER_LCAO

### Environment

OS: CentOS7
compiler: intel oneapi compliers 2022+gcc9.3
dependencies: intel MKL + ELPA2021.11.02

**Comment by caic99** [comment]
Hi @Fadelis98 ,
GPU support is currently not available since we are facilitating the process of refactoring. This feature will be added back as soon as the compatibility with the refactored framework is made.

**Comment by caic99** [comment]
Duplicated: #737
