### ISSUE TITLE
Some INPUT parameters are missing in docs/input-main.md

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#1229]
### Describe Current Status and Possible Solution

Below INPUT parameters are missing in the docs/input-main.md:

bx, by, bz, comp_center, comp_chg, comp_dim, comp_l, comp_q, deepks_bandgap, deepks_out_unittest, dft_plus_dmft, dftu_type, diago_cg_prec, double_counting, force_thr_ev2, lspinorb, noncolin, smearing_sigma_temp, soc_lambda, symmetry_prec, td_val_elec_01, td_val_elec_02, td_val_elec_03, test_skip_ewald, vdw_cn_thr, vdw_cn_thr_unit, vh_in_h, vion_in_h, wannier_card, yukawa_lambda

### Additional Context

no

**Comment by pxlxingliang** [comment]
Below keywords are actually not used by ABACUS:
diago_cg_prec,  relax,

**Comment by pxlxingliang** [comment]
bx, by, bz, force_thr_ev2, smearing_sigma_temp, symmetry_prec have beed added in #1256

**Comment by wenfei-li** [comment]
it seems comp_center, comp_chg, comp_dim, comp_l, comp_q are not used anymore ?

**Comment by pxlxingliang** [comment]
> it seems comp_center, comp_chg, comp_dim, comp_l, comp_q are not used anymore ?

Oh, these parameters may have been removed few days ago.
