### ISSUE TITLE
nscf calculation starting from wavefunction (LCAO) only not supported yet

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#1235]
### Describe the bug

Current Status:
Given wfc file, but no chg file, nscf calculation in lcao will start from atomic charge density. The final eigen energies are wrong due to wrong Hamiltonian.

### Expected behavior

Given wfc file and occupation, if the sum of all occupation equals total number of electrons, calculate rho from wfc, and then perform nscf.

**Comment by hongriTianqi** [comment]
This Issue becomes stale as it can only be solved after lcao refactoring. Can we open the choice of "Close as not planned" option to treat stale issues like this one? @mohanchen @dyzheng @baixiaokuang @caic99

**Comment by caic99** [comment]
> This Issue becomes stale as it can only be solved after lcao refactoring. Can we open the choice of "Close as not planned" option to treat stale issues like this one? @mohanchen @dyzheng @baixiaokuang @caic99

Hi @hongriTianqi ,
I think it would be better using the "later" flag rather than simply closing this issue. "Close as not planned" should be used only if this issue would not / can not being fixed.

**Comment by hongriTianqi** [comment]
Hi @caic99 Thanks for your advice!

**Comment by hongriTianqi** [comment]
- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team and stakeholders on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by mohanchen** [comment]
Assign to me, I will try to solve it.

**Comment by WHUweiqingzhou** [comment]
you can set
`out_wfc_lcao 1` to output Psi
and perform a NSCF calculation by setting `init_wfc  file`
