### ISSUE TITLE
extra outputs for each frame in md calculation

### ISSUE THREAD

**Issue by Fadelis98** [deepmodeling/abacus-develop#1237]
### Background

The latest version of abacus support saving the H matrix and S matrix in scf calculation. However, if we set out_mat_hs2=1 when running a md, because it always write the information to the same path in the same name, the file is override in each md step rather than save the H/S matrix of each frame, which is not expected. 

### Describe the solution you'd like

when running a md, save the files related to each frame to a new subdir.

**Comment by wenfei-li** [comment]
> ### Describe the solution you'd like
> when running a md, save the files related to each frame to a new subdir.

Hi, just to make sure, it seems you are using ABACUS for DeepH training, so it would be more convenient for you if we write the files with the same name, but put in different directories. Is that the case?
