### ISSUE TITLE
Document development

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#124]
Hello everyone, we implement new document of ABACUS in README.md and doc/ on reconstruction branch, please try and leave your suggests about:
1, Not convenient;
2, Lack of some features;
3, Details wrong.

**Comment by caic99** [comment]
@maki49 Would you please add a more detailed usage and example of `doxygen` for us.

**Comment by mohanchen** [comment]
We will have a new issue on this topic.
