### ISSUE TITLE
Segfault in gamma_only LCAO calculation when out_mat_hs2==1

### ISSUE THREAD

**Issue by YuLiu98** [deepmodeling/abacus-develop#1257]
### Describe the bug

There is a segfault in gamma_only LCAO calculation when out_mat_hs2==1.

**Comment by wenfei-li** [comment]
If I understand it correctly, there will be no hs2 for gamma only calculations, since it outputs H(R) and S(R) in the sparse matrix format, which is irrelevant for gamma only calculations.

**Comment by YuLiu98** [comment]
> If I understand it correctly, there will be no hs2 for gamma only calculations, since it outputs H(R) and S(R) in the sparse matrix format, which is irrelevant for gamma only calculations.

Yes, you are right. But in this case, abacus should provide users with some detailed information and exit normally, instead of exiting with a segfault.

**Comment by wenfei-li** [comment]
> > If I understand it correctly, there will be no hs2 for gamma only calculations, since it outputs H(R) and S(R) in the sparse matrix format, which is irrelevant for gamma only calculations.
> 
> Yes, you are right. But in this case, abacus should provide users with some detailed information and exit normally, instead of exiting with a segfault.

I agree. Let me update the code.
