### ISSUE TITLE
The orbital index of HSR matrix

### ISSUE THREAD

**Issue by Fadelis98** [deepmodeling/abacus-develop#1261]
### Details

Hello, I'm trying to use the HSR matrix in my work, but I didn't find some document that explained the out put files`*.csr` files.

Now I guessed out that each four lines expressed a single H(R) where the 3 int numbers in the first line represents R and the last number is the non-zero elements of the matrix.

However the order of orbitals, i.e. which line/cloumn represents which orbital, cannot be inferred from the file itself, and I didn't find the related document or code comments in the src.

**Comment by wenfei-li** [comment]
I'm wondering if this is still relevant?

**Comment by Fadelis98** [comment]
> I'm wondering if this is still relevant?

I've inferred from the source code, but a detailed document for it may still helpful for others

**Comment by mohanchen** [comment]
We provide information in http://abacus.deepmodeling.com/en/latest/advanced/pp_orb.html#basis-set
