### ISSUE TITLE
No output of STRU_ION_D and STRU_ION#_D for only-cell-relaxed cell-relax calculation

### ISSUE THREAD

**Issue by ZhouXY-PKU** [deepmodeling/abacus-develop#1276]
### Describe the bug

There are no output of ```STRU_ION_D``` file while setting direct coordinates of all atoms freezed in input-```STRU``` file in cell-relax calculation even if ```out_stru``` is set to be 1, though cell is surely relaxed according to ```running_cell-relax.log ```.

It may be because of output of ```STRU_ION_D ``` file is only included in ```Ions_Move_Methods``` (IMM) in ```module_relaxation/ions_move_methods(.cpp/.h)``` but may not be called while  direct coordinates of all atoms is set to be freezed (though cell can be relaxed) in input-```STRU``` file.

### Expected behavior

Output final structure file ```STRU_ION_D``` for any setting of ```relax``` and ```self-relax``` calculation and output step structure file ```STRU_ION#_D``` as long as ```out_stru``` is set to be 1.

### To Reproduce

Just run ABACUS-2.3.5 with 
1. ```calculation  (cell-)relax``` in  ```INPUT``` file
2. ```Direct ```
 ```...``` 
```x y z m 0 0 0 ```
```...```
 for all atoms in ```STRU``` file

**Comment by dyzheng** [comment]
Thanks for your report! Output of structures during cell-relax is definitly necessary, I will try to fix it.

**Comment by ZhouXY-PKU** [comment]
Thank you very much! There are still some problems when out_stru is not set to be 1, but can be solved by referring to the output way in ions_move_methods.cpp.
