### ISSUE TITLE
Relaxation on lattice constants

### ISSUE THREAD

**Issue by Liu-RX** [deepmodeling/abacus-develop#1373]
### Describe Current Status and Possible Solution

ABACUS has two kinds of relaxation for now, `relax` and `cell-relax`. For `relax`, atomic positions are relaxed. For `cell-relax`, both atomic positions and cell vectors are relaxed. 
Usually, in search of the lattice constants of a certain crystal, we have to choose `cell-relax` to enable change on cell parameters. But it seems that `cell-relax` does not have much limitation on cell vectors. For example, when relaxing a BCC lattice, the lattice vectors should be always (a, 0, 0), (0, a, 0), (0, 0, a) with only one degree of freedom. But `cell-relax` would allow changes on all 9 directions, which leads to unnatural results like (a, 2e-7, 1.1.e-5) instead of (a, 0, 0). I was trying to find out the lattice constants of graphite when I came into something like this.
Therefore, it might be helpful if ABACUS could support some limitations on cell parameters, to enable the relaxation of crystal of certain kinds.

**Comment by hongriTianqi** [comment]
Have you tried to set `fixed_axes` in `INPUT`? For your specific example of BCC lattice, setting `fixed_axes` to `volume` might help.

**Comment by wenfei-li** [comment]
I checked QE. They use the parameter cell_dofree to control how cell relaxation is performed. If set to 'ibrav', then
'all axis and angles are moved, but the lattice remains consistent with the initial ibrav choice'.
I think we should consider implementing the same stuff in ABACUS.

As for your current problem, if the system is not too large, you might try explicitly drawing the curve of energy v.s. lattice constant to find the minimum ...
