### ISSUE TITLE
Cell volume changes when `fixed_axes` is set to `volume`

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#1375]
### Describe the bug

The explanation of `fixed_axes` = `volume` in the documentation is `volume : relaxation with fixed volume`. But the cell volume indeed changes in one trial.

### Expected behavior

The meaning of `volume` is different with QE: `the volume changes, keeping all angles fixed (i.e. only celldm(1) changes)`. So, what should `volume` really mean?

### To Reproduce

Just run the example in `abacus/examples/relax/pw_al` by adding `fixed_axes volume`. To reproduce quickly, in addition set `a = 4.2, b=4.2, c=4.3` and k-points to `1 1 1`.

**Comment by wenfei-li** [comment]
in QE their variable is called cell_dofree which indicates the degrees of freedom that CAN change
in ABACUS we are using fixed_axes which indicates the degrees of freedome that CANNOT change
so "fixed_axes = volume" is "cell_dofree = shape"
and vice versa.

I'll look into the problem with our implementation of fixed-volume relaxation
