### ISSUE TITLE
symmetry: abacus cannot find fcc primitive cell from its conventional cell

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#1387]
### Background

ABACUS now tells it's a `simple cubic cell` when meets a `face-centered cubic` cell.

### Describe the solution you'd like

ABACUS should know it's a `simple cubic cell` when meets a `face-centered cubic` cell.

### Additional Context

To reproduce:
The `STRU` file:
```
ATOMIC_SPECIES
Al 26.982 Al.PD04.PBE.UPF

LATTICE_CONSTANT
1.8897261254578281

LATTICE_VECTORS
4.04 0.0 0.0
0.0 4.04 0.0
0.0 0.0 4.04

ATOMIC_POSITIONS
Direct
Al
0.0
4
0.0 0.0 0.0
0.5 0.5 0.0
0.5 0.0 0.5
0.0 0.5 0.5
```
The `INPUT` file:
```
INPUT_PARAMETERS
ntype               1
calculation         scf
ecutwfc             50
basis_type          pw
symmetry                1
smearing_method         gauss
```

**Comment by caic99** [comment]
@pxlxingliang Would you provide the codes that have been commented out?
@dyzheng Would you contact Pengfei Li with more details on it.

**Comment by pxlxingliang** [comment]
It seems that function `pricell()` in symmetry.cpp is used to find the primitive lattice, but it is commented out now.
![image](https://user-images.githubusercontent.com/91927439/195790208-b5eae751-364c-4836-8026-b382415807f2.png)

@dyzheng Pls help check why this function is not used now?
