### ISSUE TITLE
Memory leak when using PBE XC of Libxc

### ISSUE THREAD

**Issue by sunliang98** [deepmodeling/abacus-develop#1389]
### Describe the bug

There is slow memory leak when PBE XC of Libxc is used.

### To Reproduce

Run the attached KSDFT MD example,  and the memory usage will increase slowly.
[example.zip](https://github.com/deepmodeling/abacus-develop/files/9764264/example.zip)

### Environment

OS: Ubuntu 16.04
Complier: intel oneAPI 2021
Dependencies: intel MKL, Libxc-5.2.3

**Comment by caic99** [comment]
@sunliang98 Can you analyze the leak status using address sanitizer?
Besides, what if not using PBE from libxc?

**Comment by Qianruipku** [comment]
Only PBE of libxc has a problem.

**Comment by Qianruipku** [comment]
![image](https://user-images.githubusercontent.com/76200646/195799429-2ed5799e-99b2-477e-a7bf-d1c404c2522e.png)

**Comment by Qianruipku** [comment]
There are two possible reasons.
1. Wrong use of xc_func_init.
2. libxc has memory leaks.

**Comment by Qianruipku** [comment]
Besides, case 116_PW_scan_Si2 has the same memory leak.

**Comment by caic99** [comment]
Would you check again after this fix? @sunliang98 @Qianruipku

**Comment by sunliang98** [comment]
There are no memory leaks in above case now.
