### ISSUE TITLE
Some PW-CG diag parameters should be output to the users

### ISSUE THREAD

**Issue by maki49** [deepmodeling/abacus-develop#1399]
### Describe Current Status and Possible Solution

(Maybe “Documentation” tag should be added to this issue. )
In PW calculation with CG (both SCF and NSCF), users should know the values of these parameters to get the infomation about convergence in each step, but now they are not output neither on screen nor in OUT.suffix/running_(n)scf.log: 
- pw_diag_thr
- avg_iter
- notconv

The first is an input parameter which changes with SCF step; the last two are parameters of function `Diago_CG::Diag` in src_pw/diago_cg.h.

**Comment by dyzheng** [comment]
#1520 and #1543 have solved this issue.
