### ISSUE TITLE
Installation about building with deepks

### ISSUE THREAD

**Issue by scott-5** [deepmodeling/abacus-develop#1400]
### Details

According [Advanced Installation Options](http://abacus.deepmodeling.com/en/latest/advanced/install.html), as it mention, I use libtorch with cxx11 ABI supporting CPU. But it goes wrong:
_abacus-develop/libtorch/lib/libtorch_cpu.so: undefined reference to 'powf@GLIBC_2.27'
abacus-develop/libtorch/lib/libtorch_cpu.so: undefined reference to 'expf@GLIBC_2.27'
abacus-develop/libtorch/lib/libtorch_cpu.so: undefined reference to 'logf@GLIBC_2.27'
abacus-develop/libtorch/lib/libtorch_cpu.so: undefined reference to 'log2f@GLIBC_2.27'
abacus-develop/libtorch/lib/libtorch_cpu.so: undefined reference to 'lgammaf@GLIBC_2.23'
abacus-develop/libtorch/lib/libtorch_cpu.so: undefined reference to 'exp2f@GLIBC_2.27'
abacus-develop/libtorch/lib/libtorch_cpu.so: undefined reference to 'lgamma@GLIBC_2.23'_
1. It may mean my GLIBC version is too old (ldd --version, 2.17), so how can I install abacus building with deepks except updating my glibc version? Or can you provide libtorch compiling at lower version GLIBC
2. I try using libtorch with pre-cxx11 for installing, it works though I not tested if binary could executes an example yet. I wanna know whether installing for libtorch with pre-cxx11.
3. Another suggestion: keys`LIBXC_DIR` should be `Libxc_DIR` in [Advanced Installation Options](http://abacus.deepmodeling.com/en/latest/advanced/install.html), and version is less than 5.1.7 in [guide](https://github.com/deepmodeling/abacus-develop/wiki/Building-and-Running-ABACUS).

**Comment by caic99** [comment]
Hi @scott-5 ,

> 1. It may mean my GLIBC version is too old (ldd --version, 2.17), so how can I install abacus building with deepks except updating my glibc version? Or can you provide libtorch compiling at lower version GLIBC

You might request help from the PyTorch community. Personally, I don't have much experience on it. Sorry about that.

> 2. I try using libtorch with pre-cxx11 for installing, it works though I not tested if binary could executes an example yet. I wanna know whether installing for libtorch with pre-cxx11.

It should matches with your cxx library version.

> 3. Another suggestion: keys`LIBXC_DIR` should be `Libxc_DIR` in [Advanced Installation Options](http://abacus.deepmodeling.com/en/latest/advanced/install.html), and version is less than 5.1.7 in [guide](https://github.com/deepmodeling/abacus-develop/wiki/Building-and-Running-ABACUS).

Thanks! We will submit a patch for the key, and refurbish documents regarding requirements.

**Comment by scott-5** [comment]
> 

Thanks, I have solved it finally by compiling libtorch from sources on our machine.

**Comment by caic99** [comment]
@scott-5 Good to hear that! Feel free to reach us if you have any questions.
