### ISSUE TITLE
a mistake in the doc

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#1402]
### Describe the bug

In the doc, it is said that  **There are only two choices now: 1 or 2, meaning non spin or collinear spin.**
 Here is the link:http://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#nspin

but there are some cases where the nspin would be set to 4. 
Here is the link:http://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#out-mat-hs

**Comment by dyzheng** [comment]
Parameter "nspin" is often set to 1(non-polarized)  or 2(collinear polarized).
But for case of noncollinear polarized, nspin will be auto set to 4 but no need to specify in INPUT by users.
http://abacus.deepmodeling.com/en/latest/advanced/scf/spin.html#noncollinear-spin-polarized-calculations

**Comment by Satinelamp** [comment]
Maybe it is better to make it clear in the doc, so I create a pull request.
