### ISSUE TITLE
error on the parallel computing

### ISSUE THREAD

**Issue by caohao001** [deepmodeling/abacus-develop#1413]
### Describe the bug

Dear developers, 
The error (**psi_norm <= 0.0**) is occured when I followed the example P009_32H2O_pw(The INPUT file and STRU file are not changed). The 2018_intel_MPI + MKL is used to compile on the Centos system (HPC). The version of EPLA is 2021. The run command is: mpirun -np 12 abacus > log.  The log file is presented below.
Thanks.

ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
 m = 3
j = 0 lagrange norm = 4.62493e+21
j = 1 lagrange norm = 7.66347e+20
j = 2 lagrange norm = 5.43346e+16
j = 3 lagrange norm = 8.86966e+38
 in DiagoCG, psi norm = -5.36155e+21
 If you use GNU compiler, it may due to the zdotc is unavailable.
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 psi_norm <= 0.0
 CHECK IN FILE : OUT.autotest/warning.log
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by dyzheng** [comment]
I have retested P009_32H2O_pw case in two machine with Intel-oneAPI. 
One of them run normally, and another program exception interrupted.
It seems that stability of PW base is doubtful, and I will check that.

**Comment by Liu-RX** [comment]
I ran the case on Ubuntu 20.04 with ABACUS 3.0.0 compiled with intel-oneAPI 2021.3.0. The elpa version is also 2021. I tested serial run and mpirun with 2 and 4 cores, and did not came into the bug. It might be a bug with different version of compiler or operating system?

**Comment by caic99** [comment]
I can repeat this bug on `103_PW_15_CF_CS_S1_smallg`, using 4 OpenMP threads. ABACUS is compiled with gcc with `-O0` flag.

**Comment by pxlxingliang** [comment]
By using the latest develop codes, I can not repeat the bug with ABACUS applied GNU or intel docker images.
