### ISSUE TITLE
Misusing of GlobalC::hm in working code.

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#1420]
### Describe Current Status and Possible Solution

"GlobalC::hm" is a global class which is obsolete now.
When I try to delete this global class, I found that several code still used this class.

1. https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_esolver/esolver_ks_pw.cpp#L88
```
GlobalC::hm.hpw.allocate(GlobalC::wf.npwx, GlobalV::NPOL, GlobalC::ppcell.nkb, GlobalC::rhopw->nrxx);
```
@Qianruipku can you solve this code coupling?

2. https://github.com/deepmodeling/abacus-develop/blob/develop/source/src_pw/sto_iter.cpp#L401
```
if(GlobalC::kv.nks > 1) GlobalC::hm.hpw.init_k(ik);
```
@Qianruipku I think HamiltPW::updateHk(ik) can replace it. 

3. https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_hsolver/diago_lapack.cpp#L43
```
GlobalC::hm.diagH_LAPACK(GlobalV::NLOCAL, GlobalV::NBANDS, Htmp, Stmp, GlobalV::NLOCAL, en, hvec);
```
This is a public function just place in old class, function diagH_LAPACK() should move to diago_lapack.h file.

4. https://github.com/deepmodeling/abacus-develop/blob/develop/source/src_pw/wavefunc.cpp
Several lines used GlobalC::hm, which can be deleted now. @dyzheng

**Comment by mohanchen** [comment]
FYI, Haozhi may be involved in the diagH_LAPACK part.
