### ISSUE TITLE
abacus_pw.exe link error without -o2

### ISSUE THREAD

**Issue by baixiaokuang** [deepmodeling/abacus-develop#1421]
### Describe the bug

![120221020-173022](https://user-images.githubusercontent.com/17631388/196912337-e32f3042-92ac-4f5a-be27-e50b3f574854.jpg)

### To Reproduce

cmake -DBUILD_TESTING=1 -DCMAKE_BUILD_TYPE=Debug

### Environment

OS: Ubuntu 22.04
Compiler: gcc 11.2
Dependencies: OpenBLAS, ELPA

**Comment by caic99** [comment]
Fixed by #1397 .
