### ISSUE TITLE
The relationship between screen output and running*log is unclear

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#1430]
### Describe Current Status and Possible Solution

In our screen output, there is a section which reads and contains information on how many atoms there are of each type:
![image](https://user-images.githubusercontent.com/38569667/197458357-34cca5e9-c7e1-42b5-a448-1f142c0b60ff.png)

However, such information is never presented in such tabulated form in running*log, but printed separately for each element:
![image](https://user-images.githubusercontent.com/38569667/197458592-f2d5850d-370d-4a8f-9799-fcc1d7dbfe92.png)

The relationship between screen output and running*log is unclear. Maybe it would be better to make the former a subset of the latter, such that whenever we want to find one piece of information, we can be sure that it is in the latter.

Besides, as shown above, there are natom repeats of 'start magnetization = FALSE', which is pretty annoying when we have a large number of atoms. It seems all atoms of the same elements share the same start magnetization. If so, we should only indicate start magnetization once for each element.
![image](https://user-images.githubusercontent.com/38569667/197459722-25a6e3ae-7b5d-403a-8587-a9d67c47171f.png)
(Let me know if I'm wrong.)

**Comment by mohanchen** [comment]
You are correct. However, I am not sure whether it is practical to make the screen output as a subset of the running.log. I agree this should be done, but maybe the format has to be a little different.

**Comment by dyzheng** [comment]
I will optimize this screen in two weeks.

**Comment by mohanchen** [comment]
Two weeks have passed, the issue will close. However, if this is still an issue in future, we can of course discuss it again.
