### ISSUE TITLE
A question about ABACUS+DeePKS documentation

### ISSUE THREAD

**Issue by mohanchen** [deepmodeling/abacus-develop#1449]
### Details

Could not find the documents about manually changing model.pth to model.ptg in ABACUS+DeePKS calculations.

**Comment by ouqi0711** [comment]
Thanks for pointing this out! This part is indeed missed in current DeePKS documentation. The quick answer is to run the following script:

```
import torch
import torch.nn as nn
from torch.nn import functional as F
from deepks.model import CorrNet
mp = CorrNet.load("model.pth")
mp.compile_save("model.ptg")
```

This part has been added to the DeePKS documentation. See https://deepks-kit.readthedocs.io/en/latest/important-outputs-explanation.html.
