### ISSUE TITLE
SCF does not converge in some parallel schemes

### ISSUE THREAD

**Issue by Chentao168** [deepmodeling/abacus-develop#1460]
### Describe the bug

Each node has 96 cores in Beijing Super Cloud Computing Center.
If I use 1 node 64 cores or 1 node 96 cores, it will work fine; but if I use 2 nodes 192 cores or 4 nodes 384 cores, it will not converge.

### To Reproduce

The source code: ABACUS v3.0.1
My calculation case: abacus-3.0.1/abacus-develop-develop/tests/performance/P003_si128_pw
[P003_si128_pw.zip](https://github.com/deepmodeling/abacus-develop/files/9908134/P003_si128_pw.zip)

### Environment

OS: Beijing Super Cloud Computing Center
Compiler: Intel 2022.1

**Comment by pxlxingliang** [comment]
The latest ABACUS v3.0.5 do not have this bug.
I have run the example with 6 nodes 192 cores and 12 nodes 384 cores, both jobs are normal converged.

[test.zip](https://github.com/deepmodeling/abacus-develop/files/10266749/test.zip)

**Comment by caic99** [comment]
@Chentao168 Would you test again on the latest ABACUS codes?

**Comment by Chentao168** [comment]
I have tested again on ABACUS v3.0.5. I used 4 nodes 384 cores, it  could converge.
