### ISSUE TITLE
ABACUS need the feature to set the difference between number of electrons in up and down spin component

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#1473]
### Background

In some calculations, we need to set the difference between number of electrons in up and down spin component, which is like "NUPDOWN" in VASP.

### Describe the solution you'd like

The difference of the number of electrons in the up and down spin component will be kept fixed to the specified value.

### Additional Context

no

**Comment by caic99** [comment]
@dyzheng will take charge.

**Comment by dyzheng** [comment]
#1549 solved this issue.
