### ISSUE TITLE
SCAN XC functional with plane wave basis is far too slower than pw.x

### ISSUE THREAD

**Issue by Liu-RX** [deepmodeling/abacus-develop#1482]
### Describe Current Status and Possible Solution

I tested two systems, diamond and BaTiO3 with SCAN functional and pw basis, and found out that the speed of abacus is one to two orders of magnitude slower than QE. For diamond, each CG iteration in ABACUS takes 1~2 minutes while each CG in qe only takes less than 5 seconds. For BTO, similar thing happens as well.
The Follows are input parameters of diamond for ABACUS and QE:
ABACUS:
INPUT:
INPUT_PARAMETERS
calculation scf
ntype 1
ecutwfc 260.000000
#scf_nmax 1
basis_type pw
dft_functional scan
#gamma_only 1
mixing_type pulay
mixing_beta 0.400000
smearing_method fixed
smearing_sigma 0.0100000
cal_force 1

KPT:
K_POINTS
0
Gamma
14 14 14 0 0 0

STRU:
ATOMIC_SPECIES
C 12 /public1/home/sc80483/5_liurenxi/5_ABACUS_SCAN/SG15_ONCV_v1.0_upf/C_ONCV_PBE-1.0.upf

LATTICE_CONSTANT
6.80301356

LATTICE_VECTORS
0.5 0.5 0.000000
0.5 0.000000 0.5
0.000000 0.5 0.5

NUMERICAL_ORBITAL
/public1/home/sc80483/5_liurenxi/5_ABACUS_SCAN/to_lrx/Orb_TZDP_E100_Full/C/C_gga_10au_100Ry_3s3p2d.orb

ATOMIC_POSITIONS
Cartesian    # Cartesian(Unit is LATTICE_CONSTANT)
C
0.0
2
0.000000 0.000000 0.000000
0.250000 0.250000 0.250000

QE:
&CONTROL
  title = “diamond-scan",
  calculation = 'scf',
  !restart_mode = "restart"
  prefix = "diamond-scan",
  pseudo_dir = '/public1/home/sc80483/5_liurenxi/5_ABACUS_SCAN/SG15_ONCV_v1.0_upf',
  outdir = './SimulationFiles/',
  nstep = 1,
  dt = 2.067055274D0,    !0.1fs
  !verbosity = 'high',
  wf_collect = .true.,
  tstress = .true.,
  tprnfor = .true.,
  etot_conv_thr = 1.D-4,
/
&SYSTEM
  ibrav       = 0,
  nat         = 2,
  ntyp        = 1,
  ecutwfc     = 260.00,
  occupations = 'fixed',
  !smearing    = 'fermi-dirac',
  !degauss     = 0.0190005, ! 3000 K
  !nbnd        = 290, ! number of electrons in sys is 512
  input_dft   = 'scan',
/
&ELECTRONS
  electron_maxstep = 80,
  mixing_beta      = 0.5,
  diagonalization = 'cg',
/
ATOMIC_SPECIES
C  12    C_ONCV_PBE-1.0.upf

CELL_PARAMETERS {bohr}
3.40150678 3.40150678 0
3.40150678 0 3.40150678
0 3.40150678 3.40150678

ATOMIC_POSITIONS {crystal}
C 0 0 0
C 0.5 0.5 0.5

K_POINTS {automatic}
14 14 14 0 0 0

**Comment by wenfei-li** [comment]
Turns out it is because in ABACUS, symmetry is off by default, which causes the number of k points used to be 10 times that of QE.

**Comment by caic99** [comment]
> Turns out it is because in ABACUS, symmetry is off by default, which causes the number of k points used to be 10 times that of QE.

@wenfei-li How about we set symmetry to on by default? @dyzheng @mohanchen What do you think?
