### ISSUE TITLE
Should we remove update_input ?

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#1506]
### Describe Current Status and Possible Solution

We have a 'update_input' class which presumably is used to update some parameters during a long MD run, without restarting the run. Is this a good practice?

**Comment by caic99** [comment]
@mohanchen thinks it's OK to remove it.

**Comment by hongriTianqi** [comment]
I can't find the definition of the class `Update_input`. @wenfei-li @mohanchen

**Comment by hongriTianqi** [comment]
Update_input has been removed. @wenfei-li @mohanchen
