### ISSUE TITLE
problem running LCAO calculation with diago_proc>0 and more than 1 MPI thread

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#153]
## Describe the Bug
When running LCAO calculation with diago_proc > 0 and more than 1 mpi thread, the run halts after the following in running_scf.log:
```
 SETUP THE DIVISION OF H/S MATRIX
 divide the H&S matrix using 2D block algorithms.
                                     nb2d = 1
```

## To Reproduce
1. Clone the latest code from reconstruction branch
2. Compile the code with the following flags in Makefile.vars:

```
FORTRAN       = ifort
CPLUSPLUS      = icpc
CPLUSPLUS_MPI = mpiicpc
LAPACK_DIR    = $(MKLROOT)
FFTW_DIR   = $(your_path_to_fftw3)
BOOST_DIR  = $(your_path_to_boost)
ELPA_DIR = $(your_path_to_elpa)
CEREAL_DIR = $(your_path_to_cereal)
```

3. Copy the example 02a_Si_diamond_lcao_scf/ and add one line in the INPUT file : diago_proc= 1 (or any positive integer less than the number of number of MPI threads)
4. Run the code with more than one MPI thread, for example, mpirun -n 2 ABACUS.mpi

## Environment
- OS: CentOS 7(Core)
- Compiler: Intel Parallel Studio XE 2018
- Optional Dependencies: Intel MKL; FFTW-3.3.4; boost_1_66_0; elpa-2016.05.004

**Comment by mohanchen** [comment]
Thanks for reporting the problem! I will look into it within a couple of days.
