### ISSUE TITLE
Error in relax calculation

### ISSUE THREAD

**Issue by sunml99** [deepmodeling/abacus-develop#1534]
### Describe the bug

In the attached case, an error "Can't find even an electron!" occurs during the relaxation and the calculation is terminated
. It shows "charge before normalized = -nan" in warning.log.
![image](https://user-images.githubusercontent.com/91242172/202656900-0b61bb23-64a4-4955-93fd-fc367ea70f8a.png)
![image](https://user-images.githubusercontent.com/91242172/202657116-4d332d83-d226-4c0d-8c35-c88f6a242617.png)

Then I did an SCF calculation using the configuration of the last ionic step but did not meet any error. 

### To Reproduce

[Pt_slab_H3O.zip](https://github.com/deepmodeling/abacus-develop/files/10039579/Pt_slab_H3O.zip)

**Comment by pxlxingliang** [comment]
Hi @sunml99 , the attached system is so large, and the error is occurred at the relax process of step 23, it is really difficult to repeat. Have you ever suffered similar bug in your other calculations?

**Comment by sunml99** [comment]
> Hi @sunml99 , the attached system is so large, and the error is occurred at the relax process of step 23, it is really difficult to repeat. Have you ever suffered similar bug in your other calculations?

This bug also occurred in other relaxations of adding and subtracting different charges, but the corresponding systems are all similar. I also encountered this bug in an SCF calculation, but I was not able to successfully reproduce it.

**Comment by Qianruipku** [comment]
It maybe fixed after PR #2242

**Comment by pxlxingliang** [comment]
@sunml99, does this bug still exist after PR #2242 merged?

**Comment by sunml99** [comment]
It looks like the bug is solved. I repeated the system that had bugs before, and there were no more errors.
