### ISSUE TITLE
Bug of PW stress calculation when npool>1

### ISSUE THREAD

**Issue by YuLiu98** [deepmodeling/abacus-develop#155]
## Describe the Bug
When running PW calculation, stress is wrong if npool>1

## To Reproduce
1. Clone the latest code from reconstruction branch
2. Compile the code with Intel compiler
3. calculate stress of fcc Al with npool=1
4. calculate stress of fcc Al with npool>1 (such as 8)

## Environment
- OS: ubuntu 16.04
- Compiler: Intel Parallel Studio XE 2017
- Optional Dependencies: Intel MKL; FFTW-3.3.8; boost_1_70_0; elpa-2016.05.004

**Comment by dyzheng** [comment]
The npool setup has not been fully tested in stress code. 
This bug will be fixed as soon as possible.

**Comment by dyzheng** [comment]
#204
