### ISSUE TITLE
Intel OneAPI based Container

### ISSUE THREAD

**Issue by tansongchen** [deepmodeling/abacus-develop#156]
## Describe Current Status and Possible Solution

Recently I made a patch to ELPA 2016.05.004, enabling it to be compiled with Intel OneAPI (icpc, mpiicpc). Therefore we can make a Intel OneAPI based container. The patch is extremely simple: just delete five lines (7055 ~ 7059) at `/ltmain.sh`. I attach the patched archive here.

[elpa-2016.05.004.zip](https://github.com/deepmodeling/abacus-develop/files/6788475/elpa-2016.05.004.zip)

**Comment by mohanchen** [comment]
We have used the new version of ELPA.
