### ISSUE TITLE
Non-Convergence of 8-Si Case with 8*8*8 K-points

### ISSUE THREAD

**Issue by maki49** [deepmodeling/abacus-develop#1573]
### Describe the bug

This case converged with 4\*4\*4 k-points but not converged in 100 steps with 8\*8\*8 k-points. It seems strange.
[nonconv_8Si.zip](https://github.com/deepmodeling/abacus-develop/files/10109660/nonconv_8Si.zip)

**Comment by dyzheng** [comment]
I recommand you to test k-sample from 2*2*2 to 10*10*10？
Please set with symmetry as "1", "-1", "0", respectively.
I have tested 10*10*10, 8*8*8, 6*6*6, the consequence is strange that different symmetry setting leads to different results and some of them can not get convergent.

**Comment by dyzheng** [comment]
I recommand you to test k-sample from 2*2*2 to 10*10*10？
Please set with symmetry as "1", "-1", "0", respectively.
I have tested 10*10*10, 8*8*8, 6*6*6, the consequence is strange that different symmetry setting leads to different results and some of them can not get convergent.

**Comment by pxlxingliang** [comment]
Hi, @maki49 
Si is semi-conductor, I recommand you to use gaussian smearing in the calculation.
I have set smearing_method to gauss and smearing_sigma to 0.002, and test the KPOINTs with 4 4 4, 6 6 6, 8 8 8, 10 10 10, all of them are converged with less than 15 steps

**Comment by maki49** [comment]
@pxlxingliang Thanks. 
This case is not diamond-structure. No such problem in diamond-structure. 
For this case, gauss smearing works.
