### ISSUE TITLE
Examples of using rt-TDDFT in the periodic system

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#1588]
### Background

the rt-TDDFT method is often used in the molecular system, which works well. But in the periodic system for example, when an H2O molecule is absorbed on the surface of TiO2, it could be very tricky to excite electrons so the hot electron could end up in the molecular orbital of H2O. I notice that the examples of rt-TDDFT shipped with ABACUS are about the molecular system, maybe an example about the periodic system would be useful.

### Describe the solution you'd like

An example of using rt-TDDFT in the scenario of an H2O molecule is absorbed on the surface of TiO2

**Comment by mohanchen** [comment]
We are working on the rt-TDDFT
