### ISSUE TITLE
Unit testing for K_Vectors::renew() 

### ISSUE THREAD

**Issue by ruiyiQM** [deepmodeling/abacus-develop#1591]
### Describe Current Status and Possible Solution

 I will add a unit test for the function of `void K_Vectors::renew(): else if (nkstot > 0)` in klist.cpp of src_pw.

**Comment by hongriTianqi** [comment]
Thanks for your contribution. The PRs are suggested to link with the issue.

**Comment by hongriTianqi** [comment]
> ### Describe Current Status and Possible Solution
> The current focus will be mainly based on files (klist.cpp, occupy.cpp, read_atoms.cpp, unit cell.cpp). Unit testing will be added.
> 
> ### Additional Context
> _No response_

@ruiyiQM The title of this ISSUE implies so many things to do. One PR corresponds to one Issue. After a PR is accepted, the corresponding Issue will be closed. So you should mention only one unit from the unittest requirement list in one Issue. For example, the title of this Issue could be: I will add a unittest for the function of `void K_Vectors::renew(): else if (nkstot > 0)` in klist.cpp of src_pw.

**Comment by ruiyiQM** [comment]
> > ### Describe Current Status and Possible Solution
> > The current focus will be mainly based on files (klist.cpp, occupy.cpp, read_atoms.cpp, unit cell.cpp). Unit testing will be added.
> > ### Additional Context
> > _No response_
> 
> @ruiyiQM The title of this ISSUE implies so many things to do. One PR corresponds to one Issue. After a PR is accepted, the corresponding Issue will be closed. So you should mention only one unit from the unittest requirement list in one Issue. For example, the title of this Issue could be: I will add a unittest for the function of `void K_Vectors::renew(): else if (nkstot > 0)` in klist.cpp of src_pw.

@hongriTianqi  Thanks for your reply. It is modified now.
