### ISSUE TITLE
Constrained DFT function is needed

### ISSUE THREAD

**Issue by mohanchen** [deepmodeling/abacus-develop#1601]
### Background

the constrained DFT function is needed

### Describe the solution you'd like

need actual tests to prove the constrained DFT is correct

**Comment by dyzheng** [comment]
In #1530 , there is a method of constrained DFT has been developed. 
Using parameters of ["ocp"](http://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#ocp) and ["ocp_set"](http://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#ocp-set) can enable this feature.

**Comment by dyzheng** [comment]
This feature is not only works for TDDFT feature, but also for Kohn-Sham DFT with LCAO or PW base.

It works well in LCAO but its behavior in PW base is strange, It should be tested for PW base later.

**Comment by dyzheng** [comment]
This feature is not only works for TDDFT feature, but also for Kohn-Sham DFT with LCAO or PW base.

It works well in LCAO but its behavior in PW base is strange, It should be tested for PW base later.

**Comment by dyzheng** [comment]
https://github.com/abacusmodeling/abacus-develop/issues/242 is related to this issue.

**Comment by dyzheng** [comment]
The function is worked now, but it is still needed to optimized in future.
