### ISSUE TITLE
Code for generating LCAO orbitals is incorrect

### ISSUE THREAD

**Issue by mohanchen** [deepmodeling/abacus-develop#1604]
### Describe the bug

currently, the code to generate overlaps for further generation of atomic orbitals is incorrect, something related to the ecut used in determning the energy cutoff of spherical Bessel functions

**Comment by dyzheng** [comment]
I'm willing to help for this.
 
This bug should be discussed with @wenfei-li and @PeizeLin .

**Comment by dyzheng** [comment]
It has been solved.
