### ISSUE TITLE
OpenMP development team needs to have clear job assignments

### ISSUE THREAD

**Issue by mohanchen** [deepmodeling/abacus-develop#1607]
### Details

The openMP codes of ABACUS are now developed simultaneously in USTC and by Jiexin Liang, they need to know each other's works and plans.

**Comment by caic99** [comment]
@mohanchen Sun Jinwen from USTC is currently working on non-local pseudopotential, mainly in `LCAO_gen_fixedH.cpp`. He has reviewed changes from Liang Jiexin, and not seeing conflicts between them and his modifications.
