### ISSUE TITLE
Some code files can be cut into smaller files

### ISSUE THREAD

**Issue by mohanchen** [deepmodeling/abacus-develop#1609]
### Background

Some code lines are large in some specific code files, for example, these files in src_pw may be considered to be cut into smaller files.
   506 charge_pulay.cpp
   533 energy.cpp
   551 wavefunc.cpp
   591 stress_func_nl.cpp
   627 sto_iter.cpp
   737 VNL_in_pw.cpp
   740 wf_atomic.cpp
   981 occupy.cpp
  1125 charge.cpp
  1227 forces.cpp
  1279 klist.cpp
these files in src_lcao
   671 wavefunc_in_pw.cpp
   746 LCAO_hamilt.cpp
   892 LCAO_matrix.cpp
   948 LCAO_gen_fixedH.cpp
   960 FORCE_STRESS.cpp
  1006 dftu_relax.cpp
  1014 FORCE_k.cpp
  1031 LCAO_evolve.cpp
  1688 dftu.cpp

### Describe the solution you'd like

let's find some helpers

**Comment by dyzheng** [comment]
This issue has not been solved until now.

**Comment by mohanchen** [comment]
we will make a new plan, I will close it now.
