### ISSUE TITLE
Current genelpa does not support elpa 2022

### ISSUE THREAD

**Issue by caic99** [deepmodeling/abacus-develop#1616]
In elpa 2022.05.001, the interface has changed from `elpa_eigenvectors_all_host_arrays_d` to `elpa_eigenvectors_a_h_a_d`. `ELPA_2STAGE_COMOLEX_INTEL_GPU` in `elpa_new.cpp` is renamed to `ELPA_2STAGE_COMOLEX_INTEL_GPU_SYCL`. Corresponding compatibility changes in `genelpa.cpp` should be made.

**Comment by mohanchen** [comment]
@caic99 talk to Shen Yu and find a solution?

**Comment by caic99** [comment]
> @caic99 talk to Shen Yu and find a solution?

@mohanchen OK, @dyzheng will update with Prof. Shen in feishu group.

**Comment by caic99** [comment]
In elpa 2022.11, they have implemented the C++ polymorphism interface. Maybe we can use it directly.
