### ISSUE TITLE
Fail to build abacus-3.0.4

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#1618]
### Details

I tried to use Intel OneAPI and ELPA, Cereal, LibXC to compile abacus-3.0.4, and everything worked fine until I tried `cmake --build build -j40` to build abacus.
There are some errors from the point of finishing 20% building process:
```
[ 20%] Building CXX object source/module_gint/CMakeFiles/gint.dir/gint_vl.cpp.o
In file included from /home/lifei/software/abacus-develop-3.0.4/source/module_vdw/vdw.cpp(2):
/home/lifei/software/abacus-develop-3.0.4/source/module_vdw/vdw.h(14): error: namespace "std" has no member "unique_ptr"
  std::unique_ptr<T> make_unique(Args &&... args) {
       ^

In file included from /home/lifei/software/abacus-develop-3.0.4/source/module_vdw/vdw.cpp(2):
/home/lifei/software/abacus-develop-3.0.4/source/module_vdw/vdw.h(41): warning #12: parsing restarts here after previous syntax error
      double energy_ = 0;
                        ^
```
Here is the configuration command 
`cmake -DCMAKE_CXX_COMPILER=mpiicpc -B build -DCMAKE_INSTALL_PREFIX=~/software/abacus_install -DELPA_DIR=~/software/elpa_install -DCEREAL_INCLUDE_DIR=~/software/cereal-1.3.2/include -DLibxc_DIR=~/software/libxc_install`

It looks like an error related `vdw`, I know this feature is still under development, but I am not sure how to solve this error. 
My questions are:
1. Is this a bug?
2. If not, how could I manage to compile ABACUS?
The log for building abacus is attached.
[buildLog.txt](https://github.com/deepmodeling/abacus-develop/files/10147045/buildLog.txt)

**Comment by caic99** [comment]
Hi @Satinelamp ,
Thank you for using ABACUS. What is the version of `gcc` you are using? Intel compilers also use GCC headers and libraries. Please make sure you have GCC >=5 . You can read [our docs](https://abacus.deepmodeling.com/en/latest/quick_start/easy_install.html#prerequisites) for details.

**Comment by Satinelamp** [comment]
Thanks a lot for the help. I indeed didn't change the GCC version.

**Comment by Satinelamp** [comment]
Also, there is an extra note for newbies, if the user doesn't have root privilege, it is better to specify the path of ELPA during configuration.
![Snipaste_2022-12-04_11-37-17](https://user-images.githubusercontent.com/62006565/205473073-cd01b6be-c1cd-4006-a956-f05a6f0b7d7f.png)
