### ISSUE TITLE
Support for INPUT option 'out_mat_hs2' in MD

### ISSUE THREAD

**Issue by Enderwitherzjdl** [deepmodeling/abacus-develop#1623]
### Background

I hope to get Hamiltonian matrix $H$ and overlap matrix $S$ used for DeepH training directly in MD process, to avoid repeated calculation.

### Describe the solution you'd like

I hope that the solution is that MD supports the output of Hamiltonian $H$ and overlap $S$ matrices, with a specified $n$ in INPUT file meaning to output the matrices every $n$ steps. It is suggested to output the matrices in different files or folders.

**Comment by wenfei-li** [comment]
We already have the feature to print H and S to a different file for each step; I guess what we need is just another parameter which controls the interval of printing
