### ISSUE TITLE
Could not compile ABACUS with new EXX implementation using Clang compiler

### ISSUE THREAD

**Issue by xinyangd** [deepmodeling/abacus-develop#1649]
### Describe the bug

When compiling ABACUS using Clang compiler, the new EXX implementation would cause compilation errors. I have fixed some template related ones in this commit: https://github.com/xinyangd/abacus-develop/commit/fa4460be2737c17baf3c2e4b29c45fb23db7b22e.
The remaining errors are related with class Local_Orbital_Charge and class Energy.

Error message:
In file included from /Users/dongxy/code/AISI/abacus-develop/source/module_orbital/ORB_control.cpp:5:
In file included from /Users/dongxy/code/AISI/abacus-develop/source/module_orbital/../src_io/wf_local.h:8:
In file included from /Users/dongxy/code/AISI/abacus-develop/source/src_lcao/local_orbital_charge.h:12:
In file included from /Users/dongxy/code/AISI/abacus-develop/source/src_lcao/LCAO_hamilt.h:52:
In file included from /Users/dongxy/code/AISI/abacus-develop/source/src_lcao/LCAO_hamilt.hpp:12:
In file included from /Users/dongxy/code/AISI/abacus-develop/source/module_ri/RI_2D_Comm.h:53:
In file included from /Users/dongxy/code/AISI/abacus-develop/source/module_ri/RI_2D_Comm.hpp:10:
In file included from /Users/dongxy/code/AISI/abacus-develop/source/module_ri/RI_Util.h:48:
In file included from /Users/dongxy/code/AISI/abacus-develop/source/module_ri/RI_Util.hpp:10:
In file included from /Users/dongxy/code/AISI/abacus-develop/source/src_pw/global.h:313:
In file included from /Users/dongxy/code/AISI/abacus-develop/source/module_cell/../src_pw/../src_lcao/global_fp.h:15:
In file included from /Users/dongxy/code/AISI/abacus-develop/source/module_ri/Exx_LRI.h:66:
/Users/dongxy/code/AISI/abacus-develop/source/module_ri/Exx_LRI.hpp:169:42: error: member access into incomplete type 'const Local_Orbital_Charge'
                ? RI_2D_Comm::split_m2D_ktoR<Tdata>(loc.dm_gamma, pv)
                                                       ^
/Users/dongxy/code/AISI/abacus-develop/source/module_cell/../src_pw/energy.h:17:15: note: forward declaration of 'Local_Orbital_Charge'
        friend class Local_Orbital_Charge;
                     ^
In file included from /Users/dongxy/code/AISI/abacus-develop/source/module_orbital/ORB_control.cpp:5:
In file included from /Users/dongxy/code/AISI/abacus-develop/source/module_orbital/../src_io/wf_local.h:8:
In file included from /Users/dongxy/code/AISI/abacus-develop/source/src_lcao/local_orbital_charge.h:12:
In file included from /Users/dongxy/code/AISI/abacus-develop/source/src_lcao/LCAO_hamilt.h:52:
In file included from /Users/dongxy/code/AISI/abacus-develop/source/src_lcao/LCAO_hamilt.hpp:12:
In file included from /Users/dongxy/code/AISI/abacus-develop/source/module_ri/RI_2D_Comm.h:53:
In file included from /Users/dongxy/code/AISI/abacus-develop/source/module_ri/RI_2D_Comm.hpp:10:
In file included from /Users/dongxy/code/AISI/abacus-develop/source/module_ri/RI_Util.h:48:
In file included from /Users/dongxy/code/AISI/abacus-develop/source/module_ri/RI_Util.hpp:10:
In file included from /Users/dongxy/code/AISI/abacus-develop/source/src_pw/global.h:313:
In file included from /Users/dongxy/code/AISI/abacus-develop/source/module_cell/../src_pw/../src_lcao/global_fp.h:15:
In file included from /Users/dongxy/code/AISI/abacus-develop/source/module_ri/Exx_LRI.h:66:
/Users/dongxy/code/AISI/abacus-develop/source/module_ri/Exx_LRI.hpp:170:42: error: member access into incomplete type 'const Local_Orbital_Charge'
                : RI_2D_Comm::split_m2D_ktoR<Tdata>(loc.dm_k, pv);
                                                       ^
/Users/dongxy/code/AISI/abacus-develop/source/module_cell/../src_pw/energy.h:17:15: note: forward declaration of 'Local_Orbital_Charge'
        friend class Local_Orbital_Charge;
                     ^

**Comment by caic99** [comment]
@xinyangd I'm trying to reproduce this issue on the latest develop branch. However, there are some other errors generated.

```
abacus-develop/source/module_ri/LRI_CV_Tools.hpp:48:20: error: out-of-line definition of 'exist' does not match any declaration in namespace 'LRI_CV_Tools'
bool LRI_CV_Tools::exist(const RI::Tensor<Tdata> &V)

abacus-develop/source/module_ri/LRI_CV.hpp:308:33: error: use 'template' keyword to treat 'cal_overlap_matrix' as a dependent template name
```

**Comment by xinyangd** [comment]
[caic99](https://github.com/caic99) This is the template related problem I have fixed in the commit mentioned above, which is not in the develop branch yet. If you want to reproduce this problem, please go to this branch: https://github.com/xinyangd/abacus-develop/tree/dev_LibRI-compile. If we need to debug this together I can also create a new branch under the deepmodeling repo.
