### ISSUE TITLE
`ELPA_LIBRARY` used by `cmake` is not mentioned in the official website

### ISSUE THREAD

**Issue by 1041176461** [deepmodeling/abacus-develop#1669]
### Describe the bug

![image](https://user-images.githubusercontent.com/40336950/207005986-026c6cc4-7eea-43e8-938b-690ffb5d2d14.png)

**Comment by caic99** [comment]
@1041176461 Please set `ELPA_DIR` following the docs. `ELPA_LIBRARY` is an internal variable.
