### ISSUE TITLE
 `share/cmake/Libxc` is wrong directory for libxc-6.0.0

### ISSUE THREAD

**Issue by 1041176461** [deepmodeling/abacus-develop#1670]
### Describe the bug

 `${Libxc_DIR}/share/cmake/Libxc)` in 'CMakeLists.txt' is a wrong directory for libxc 6.0.0, because it is corrected to `lib64/cmake/Libxc` in this version

**Comment by 1041176461** [comment]
And why ABACUS limit the version of the libxc to 5.1.7? ABACUS v2.3.5 does't have this limit
![image](https://user-images.githubusercontent.com/40336950/207210242-b1599547-6a4f-474d-ba93-235189ac604b.png)

**Comment by caic99** [comment]
> And why ABACUS limit the version of the libxc to 5.1.7? ABACUS v2.3.5 does't have this limit ![image](https://user-images.githubusercontent.com/40336950/207210242-b1599547-6a4f-474d-ba93-235189ac604b.png)

New functionals are introduced in 5.1.7 .

**Comment by caic99** [comment]
> `${Libxc_DIR}/share/cmake/Libxc)` in 'CMakeLists.txt' is a wrong directory for libxc 6.0.0, because it is corrected to `lib64/cmake/Libxc` in this version

Reproduced. The path is slightly different. On my platform it is `lib/cmake/Libxc`. Don't know why they change this.
