### ISSUE TITLE
Rank mismatch error when install environment Scalapack

### ISSUE THREAD

**Issue by KCJ2000** [deepmodeling/abacus-develop#1671]
### Describe Current Status and Possible Solution

When you install the Scalapack ,the step 'make lib' will break and return 
"Warning: Rank mismatch in argument ‘mu‘ at (1) (rank-1 and scalar) [-Wargument-mismatch]". 
That's because this code link different kinds of variables together.This operation is allowed in the last vision of Fortran. But it's not allowed in the latest vision. 

------------------------------------------------------------------------------------------------------
To solve this problem,we should add "-fallow-argument-mismatch" to turn an error to a warning.
The following is an example, where pzlarzc.f is the file with problem.
There are several problem files, so you should change the file name and run it several times.

cd SRC && mpif90 -c -fPIC -fallow-argument-mismatch pzlarzc.f && cd .. && make lib

### Additional Context

https://blog.csdn.net/ZJ315296441/article/details/119082156

**Comment by caic99** [comment]
Hi @KCJ2000 ,
Which Fortran compiler and codes did you use?

**Comment by KCJ2000** [comment]
I can use the command 'gfortran -v' to check the version of Fortran compiler. The information is following.


         Using built-in specs.
         COLLECT_GCC=gfortran
         COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
         OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
         OFFLOAD_TARGET_DEFAULT=1
         Target: x86_64-linux-gnu
         Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.3.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-       languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id   --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release       --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
         Thread model: posix
         Supported LTO compression algorithms: zlib zstd
         gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04)


The Fortran compiler is automatically installed by Ubuntu.This is a new machine. And if we use fortran77 , there will not be any errors. The detail is in the link.

**Comment by caic99** [comment]
@KCJ2000 Thanks. And which codes did you try to compile?

**Comment by KCJ2000** [comment]
The code provided by your website.
http://abacus.deepmodeling.com/en/latest/quick_start/easy_install.html

**Comment by dyzheng** [comment]
Have you solved this Issue ? @KCJ2000

**Comment by KCJ2000** [comment]
yes. The solution has been mentioned above.
