### ISSUE TITLE
The serial version of PW can be compiled for ABACUS 3.0.0, but not 3.0.4

### ISSUE THREAD

**Issue by Qianruipku** [deepmodeling/abacus-develop#1676]
### Describe the bug

In version 3.0.0, serial version of PW can be compiled with make:
make pw CC=icpc
However, it failed in version 3.0.4

### Expected behavior

The serial version and parallel versions of PW should be easily compiled.

**Comment by dyzheng** [comment]
Has this Issue solved? @Qianruipku

**Comment by Qianruipku** [comment]
Yes, it can be closed.
