### ISSUE TITLE
Interface: "running*log" cannot be read by the ASE interface

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#1685]
### Describe the bug

JYY: I find "running*log" of the development version of the ABACUS on the branch develop of the deepmodeling/abacus-develop. have been modified which leads to an AttributeError when I use the interface to read this file. This error means the interface cannot obtain information from "running*log" according to specific keys, such as 'SELF-CONSISTENT' in old 'running_scf.log'. I think that changing  format of the "running*log" frequently will have a big impact on interface (e.g. ase-abacus, phonopy, NOMAD...) compatibility and ABACUS should decide on a fixed format as soon as possible.
https://gitlab.com/1041176461/ase-abacus/-/issues/7

**Comment by hongriTianqi** [comment]
Reopened due to failure of parsing running_relax.log in ASE-ABACUS codes.

**Comment by 1041176461** [comment]
Here is my 'running_relax.log' obtained from commit [28c3d9](28c3d9f64364b553bedc0ece80dc9e22f2f0dba3) 
[running_relax.log](https://github.com/deepmodeling/abacus-develop/files/10242117/running_relax.log)

**Comment by wenfei-li** [comment]
i need to know what keywords are used for the interface exactly

**Comment by wenfei-li** [comment]
I talked with Yuyang, and it appears that best way to resolve this issue is by modifying the ASE interface

**Comment by wenfei-li** [comment]
This issue has been solved by #1704 and corresponding change in ASE interface
