### ISSUE TITLE
Printing smearing contribution to energy in output files is needed

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#1779]
### Background

Smearing is always a promising method for helping SCF reach convergence. However once smearing method changes electronic distribution, the electronic energy will change correspondingly. Therefore outputting an evaluation on smearing, or smearing contribution to electronic energy is necessary and, this feature has been seen in Quantum ESPRESSO as far as I know.

### Describe the solution you'd like

For example in Quantum ESPRESSO, if smearing is enabled, in output file there will be lines about smearing contributions:
!    total energy              =   -1069.18596533 Ry
     estimated scf accuracy    <       0.00000048 Ry
     smearing contrib. (-TS)   =      -0.00056663 Ry
     internal energy E=F+TS    =   -1069.18539869 Ry

     The total energy is F=E-TS. E is the sum of the following terms:
     one-electron contribution =    -115.29972537 Ry
     hartree contribution      =      77.66961906 Ry
     xc contribution           =    -134.01089995 Ry
     ewald contribution        =    -159.49905222 Ry
     DFT-D3 Dispersion         =      -0.06695656 Ry
     one-center paw contrib.   =    -737.97838365 Ry
      -> PAW hartree energy AE =       0.00000000 Ry
      -> PAW hartree energy PS =       0.00000000 Ry
      -> PAW xc energy AE      =       0.00000000 Ry
      -> PAW xc energy PS      =       0.00000000 Ry
      -> total E_H with PAW    =      77.66961906 Ry
      -> total E_XC with PAW   =    -134.01089995 Ry

While presently in ABACUS, this part is absent:
(example/scf/lcao_Cu)
       Energy                       Rydberg                            eV
   E_KohnSham                -84.0118716467                -1143.04015404
     E_Harris                -84.0118716467                -1143.04015404
       E_band                +8.84704015623                 +120.37015656
   E_one_elec                -7.19361162035                -97.8741072357
    E_Hartree                  +16.84173759                +229.143595445
         E_xc                -13.4484937248                -182.976144174
      E_Ewald                -80.2105591012                -1091.32064354
      E_demet            -0.000944790338568              -0.0128545320199
      E_descf                            +0                            +0
        E_exx                            +0                            +0
      E_Fermi                +1.08844192032                +14.8090120584

Many thanks, :)
Yike

**Comment by dyzheng** [comment]
Thank for your suggestion, I will try to add this information in our output file.

**Comment by Qianruipku** [comment]
As far as I know, E_demet in ABACUS represents -TS item?
