### ISSUE TITLE
The stress and force are wrong in dft_plus_u calculation

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#1806]
### Describe the bug

In the attached example, the STRESS and FORCE are extremely large. While the results without dft_plus_uare much normal.

with dft_plus_u
![image](https://user-images.githubusercontent.com/91927439/212635969-805b8347-9492-446c-acb5-0f265bdc5afe.png)

without dft_plus_u
![image](https://user-images.githubusercontent.com/91927439/212636842-1e5ff792-2a1e-4f36-8c40-51e7aa9beee1.png)

[u.zip](https://github.com/deepmodeling/abacus-develop/files/10424026/u.zip)

**Comment by wenfei-li** [comment]
I checked and the problem is that the final converged state has very weird band energies and total energy. The problem is not with the DFTU force and stress code, and we need to check the SCF algorithm.

**Comment by wenfei-li** [comment]
See https://github.com/deepmodeling/abacus-develop/issues/1860
