### ISSUE TITLE
Update version number on release

### ISSUE THREAD

**Issue by caic99** [deepmodeling/abacus-develop#1815]
### Background

Currently ABACUS writes version number in source code. This requires additional effort when releasing a new version.

### Describe the solution you'd like

Maybe we should find a way to automatically configure the version info.

**Comment by dyzheng** [comment]
v3.2.0 is comming soon, how is the progress?

**Comment by dyzheng** [comment]
I update version number by PR, will we have automatic workflow for this issue.
