### ISSUE TITLE
In PR #1826, error occured in UT but not in integrate tests, which also covered related code.

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#1828]
### Details

In PR #1826 , I moved src_pw/kernel/ from src_pw to module_hamilt_pw/hamilt_pwdft/kernel/, I found E2E tests in tests/integrate were passed, but UT of "cal_dbecp_noevc_nl_op_cpu" was not passed. 
I tested this UT in my local environment(intel-oneAPI), and same error occured in UT of "cal_dbecp_noevc_nl_op_cpu".
I ignored this UT in my PR #1826 for bypassing this bug, anyone can help for this problem?

**Comment by denghuilu** [comment]
#1883

**Comment by denghuilu** [comment]
Fixed by PR #1883 .
