### ISSUE TITLE
Abnormal bandgap after nscf calculation of Si

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#1829]
### Describe the bug

set `out_bandgap` in INPUT_nscf in the example of Colombo-ABACUS/ABACUS/Si_LCAO/band_structure, the output bandage is 0.00576 eV, which is obviously wrong.

### Expected behavior

Output the correct bandgap of Si.

**Comment by caic99** [comment]
Hi @ouqi0711 , did your PR fix this issue? If so, don't forget to close it :-)
