### ISSUE TITLE
Segmentation fault error when do dft_plus_u force calculation

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#1830]
### Describe the bug

For the attached example, I try to do the calculation of dft_plus_u, when the SCF is finished, ABACUS throw the "Segmentation fault" error, which seems is running the force calculation.
![image](https://user-images.githubusercontent.com/91927439/215311316-d3dcade2-f084-4701-881a-3e30d8ed735f.png)
[plus.zip](https://github.com/deepmodeling/abacus-develop/files/10529254/plus.zip)

**Comment by pxlxingliang** [comment]
By printing out a signal in some key lines, I can locate the bug is occurred at function `folding_matrix_k()` that called in function DFTU::cal_force_k() at source/module_dftu/dftu_force.cpp.

**Comment by caic99** [comment]
@pxlxingliang @wenfei-li FYI
https://abacus.deepmodeling.com/en/latest/CONTRIBUTING.html#debugging-the-codes
