### ISSUE TITLE
MP-sampled k-points with shift are inconsistent with VASP and QE

### ISSUE THREAD

**Issue by maki49** [deepmodeling/abacus-develop#1850]
### Describe the bug

When `MP` and non-zero shift is set in `KPT` file: 
ABACUS(MP): kpoints moved `shift*(kdirect2-kdirect1)*1/2` from (0 0 0)

> in `KPT`:
> ```
> K_POINTS
> 0
> MP
> 2 1 1 0.5 0 0
> ```
> in `OUT.ABACUS/kpoints`:
> ```\                                   nkstot = 2
>       KPT             DirectX             DirectY             DirectZ
>         1              -0.125                 0                   0
>         2               0.375                 0                   0
> ```

QE(automatic) and VASP(MP): kpoints moved `shift*(kdirect2-kdirect1)` from (0 0 0)
- VASP
> in `KPOINTS`:
> ```
> Automatic generation
> 0
> MP
>  2 1 1
>  0.5 0 0
> ```
> in `OUTCAR`:
> ```
>  k-points in units of 2pi/SCALE and weight: Automatic generation                    
>    0.00000000  0.00000000  0.00000000       0.500
>   -0.00000000  0.17605634  0.17605634       0.500
>  
>  k-points in reciprocal lattice and weights: Automatic generation                    
>    0.00000000  0.00000000  0.00000000       0.500
>    0.50000000  0.00000000 -0.00000000       0.500
> ```

- QE
> in `input`:
> ```
> K_POINTS automatic
> 2 1 1 0.5 0 0
> ```
> ```
>      number of k points=     2  Gaussian smearing, width (Ry)=  0.0020
>                        cart. coord. in units 2pi/alat
>         k(    1) = (   0.0000000   0.0000000   0.0000000), wk =   0.5000000
>         k(    2) = (   0.0000000   0.1760563   0.1760563), wk =   0.5000000
> ```
> 

### Expected behavior

The coordinates of kpoints should be consistent with VASP and QE. 
in this case, the direct coordinates should be:
```
0 0 0
0.5 0 0
```

### To Reproduce

Unzip this file:
[1Fe_MP_shift.zip](https://github.com/deepmodeling/abacus-develop/files/10607882/1Fe_MP_shift.zip)
and run: 
- ABACUS: `mpirun -np 1 abacus`
- VASP: `mpirun -np 1 vasp_std`
- QE: `pw.x -i input`

### Environment

Ubuntu 16.04, OneAPI 2021.3.0, MKL, cmake

**Comment by dyzheng** [comment]
In ABACUS, formula of generating MP grids is different with QE :
```
double K_Vectors::Monkhorst_Pack_formula( const int &k_type, const double &offset,
                                      const int& n, const int &dim)
{
    double coordinate;
    if (k_type==1) coordinate = (offset + 2.0 * (double)n - (double)dim - 1.0) / (2.0 * (double)dim); //MP case
    else coordinate = (offset + (double)n - 1.0) / (double)dim; //gamma case
    return coordinate;
}
```
which in QE:
```
           xkg(1,n) = dble(i-1)/nk1 + dble(k1)/2/nk1 //k1 for offset, nk1 for dim, i for n, xkg for coordinate
```

**Comment by maki49** [comment]
Shall we change it to the same as VASP and QE ？ or is there any special consideration for ABACUS ?

**Comment by dyzheng** [comment]
![image](https://user-images.githubusercontent.com/49852742/218956468-abb7f3cc-a8ca-4fc3-baa1-71919bd92f2d.png)
@maki49 @mohanchen the offset in QE must be 0 or 1, but in ABACUS, double offset [0,1] is surpported.

**Comment by dyzheng** [comment]
> ![image](https://user-images.githubusercontent.com/49852742/218956468-abb7f3cc-a8ca-4fc3-baa1-71919bd92f2d.png) @maki49 @mohanchen the offset in QE must be 0 or 1, but in ABACUS, double offset [0,1] is surpported.

It is same in VASP, offset only can be 0 and 1, 0.5 is same setting as 0.
