### ISSUE TITLE
Constrained magnetization for noncolinear spin

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#1851]
### Background

This is for collaboration with DeepH. We might consider implement non-collinear spin-constrained DFT which is available in both SIESTA and OpenMX.

### Describe the solution you'd like

Details of the method might be found in the following two references:

[Cuadrado_2018_J._Phys._Mater._1_015010.pdf](https://github.com/deepmodeling/abacus-develop/files/10637277/Cuadrado_2018_J._Phys._Mater._1_015010.pdf)

[Cai, Z., & Xu, B. (2022). First-principles Study of Non-collinear Spin Fluctuations Using Self-adaptive Spin-constrained Method. arXiv 2208.04551.pdf](https://github.com/deepmodeling/abacus-develop/files/10637278/Cai.Z.Xu.B.2022.First-principles.Study.of.Non-collinear.Spin.Fluctuations.Using.Self-adaptive.Spin-constrained.Method.arXiv.2208.04551.pdf)

**Comment by dyzheng** [comment]
I will consider these methods, thank you!

**Comment by wenfei-li** [comment]
Redundant with a more recent issue (https://github.com/deepmodeling/abacus-develop/issues/2488), and I'll close this one

**Comment by hongriTianqi** [comment]
@wenfei-li I have added this issue to a new project named "spin constrained dft"

**Comment by hongriTianqi** [comment]
- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team and stakeholders on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by hongriTianqi** [comment]
@wenfei-li We have implemented the DeltaSpin method to constrain atomic magnetic moments in nonlinear and soc calculation. Documentation are provided at: http://abacus.deepmodeling.com/en/latest/advanced/scf/spin.html. Examples are provided in abacus-develop/examples/noncollinear. Please have a test and feedback to us if you meet any problems.
