### ISSUE TITLE
The following characters (≤ 150) in the same line will be neglected.

### ISSUE THREAD

**Issue by Shen-Zhen-Xiong** [deepmodeling/abacus-develop#1859]
### Details

In DOCS( https://abacus.deepmodeling.com/en/latest/quick_start/input.html ):The following characters (≤ 150) in the same line will be neglected. maybe  (>= 150) ?

**Comment by dyzheng** [comment]
Thanks for your report!

**Comment by dyzheng** [comment]
@Shen-Zhen-Xiong can you try to submit a PR to fix this issue ?
