### ISSUE TITLE
GPU version failed to run with more than 2 process on sample input

### ISSUE THREAD

**Issue by lcclcc233** [deepmodeling/abacus-develop#1864]
### Describe the bug

I downloaded the latest vesion and complied it with -DUSE_CUDA=1, then I tried the sample INPUT[https://github.com/deepmodeling/abacus-develop/tree/develop/examples/gpu/si16_pw](url). 
I got the expected answer with 1 and 2 process, but it crashed on 3 or more process.
I then tried the cpu version and got the expected answer (though much slower).
Here is my command:
```
export OMP_NUM_THREADS=10
mpirun -np 3 abacus
```
And here is the result:_（I slightly change the format)_

> No protocol specified
> WARNING: Total thread number on this node mismatches with hardware availability. This may cause poor performance.
> Info: Local MPI proc number: 3,OpenMP thread number: 10,Total thread number: 30,Local thread limit: 56
> 
> ABACUS v3.1                                            
> Atomic-orbital Based Ab-initio Computation at UStc                    
> Website: http://abacus.ustc.edu.cn/                             
> Documentation: https://abacus.deepmodeling.com/                       
> Repository: https://github.com/abacusmodeling/abacus-develop       
> https://github.com/deepmodeling/abacus-develop
> 
> Tue Feb  7 18:01:24 2023
> MAKE THE DIR         : OUT.autotest/
> cuBLAS Assert: CUBLAS_STATUS_NOT_INITIALIZED /home/lcc/abacus-develop/source/module_hsolver/kernels/cuda/math_kernel_op.cu 26
> cuBLAS Assert: CUBLAS_STATUS_NOT_INITIALIZED /home/lcc/abacus-develop/source/module_hsolver/kernels/cuda/math_kernel_op.cu 26
> 
> mpirun detected that one or more processes exited with non-zero status, thus causing
> the job to be terminated. The first process to do so was:
> Process name: [[23029,1],2]
> Exit code:    1
> Primary job  terminated normally, but 1 process returned

### To Reproduce

My way to download and complie.
```
git clone https://github.com/deepmodeling/abacus-develop.git
cd abacus-develop
mkdir build
cd build
/snap/bin/cmake -DCMAKE_BUILD_TYPE=Release -DELPA_DIR=/home/ldh/softwares/elpa_21.05.002 -DLAPACK_DIR=/home/ldh/softwares/OpenBLAS/ -DSCALAPACK_DIR=/home/ldh/softwares/OpenBLAS/lib -DBUILD_TESTING=ON -DUSE_CUDA=ON -DCMAKE_CUDA_COMPILER=/usr/local/cuda-11.7/bin/nvcc -DENABLE_LCAO=ON -DLibxc_DIR=/home/ldh/softwares/libxc-5.1.7 -G "CodeBlocks - Unix Makefiles" ..
cd ..
cmake --build build -j9
cmake --install build
```

**Comment by denghuilu** [comment]
It is caused by misuse of GPU memory, not a bug of ABACUS. I checked the GPU environment and found that there is a TensorFlow program running on the same GPU device, which occupies almost all the device memory. As a result, the memory of the ABACUS device is insufficient and an error is reported.
