### ISSUE TITLE
vl_in_h = 0 is broken

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#1873]
### Describe the bug

vl_in_h is used to control whether vlocal term is included in the hamiltonian. This keyword is intended to be used for debugging. In normal calculations vl_in_h is set to 1. Now running abacus with vl_in_h = 0 will result in segfault.

**Comment by mohanchen** [comment]
Tests needed!

**Comment by hongriTianqi** [comment]
I have tested vl_in_h=1, no seg fault happens in ABACUS v3.2, so this issue will be closed.
