### ISSUE TITLE
SCF calculation of GaAs using SCAN functional and lattice constant larger than 5.86 A, with slight disturbance cannot converge

### ISSUE THREAD

**Issue by Liu-RX** [deepmodeling/abacus-develop#1877]
I was doing pressure finite-difference test using SCAN functional on GaAs when I came through this problem. Lattice constant of fully relaxed GaAs lattice with SCAN functional is 5.66 A. When the lattice constant goes to greater than or equal to 5.86 A, the perfect lattice with diamond geometry could still reach convergence. However, when I change x to 0.15%, the SCF would fail to converge. The problem appears for both PW and LCAO basis.

**Comment by wenfei-li** [comment]
This appears to be the result of band gap getting smaller for larger lattice constants. I tried switching from fixed occupation to gaussian smearing, and SCF converged.

**Comment by Liu-RX** [comment]
The solution does work! But I checked the band gap of the perfect lattice and found out that the band gap is similar to perturbed case. And the perfect case could converge with fixed occupation. It seems that there is still trouble with SCAN SCF convergence.

**Comment by wenfei-li** [comment]
> The solution does work! But I checked the band gap of the perfect lattice and found out that the band gap is similar to perturbed case. And the perfect case could converge with fixed occupation. It seems that there is still trouble with SCAN SCF convergence.

I think it might have something to do with the initial electronic configuration. Let me take a look at it.
