### ISSUE TITLE
The C interface cannot be used to compile ABACUS with DeePMD-kit.

### ISSUE THREAD

**Issue by YuLiu98** [deepmodeling/abacus-develop#1893]
### Describe the bug

I tested the **C interface** of DeePMD-kit recently. However, I found that the `tensorflow_cc` dynamic library must be linked during ABACUS compilation.

Here is the detailed error log: 
[log.txt](https://github.com/deepmodeling/abacus-develop/files/10728338/log.txt)

**Comment by njzjz** [comment]
The log shows that it has been linked, but is not found in the search path. It may be okay to just correct the search path.
```
ld: warning: libtensorflow_framework.so.2, needed by /home/ldh/deepmd-kit/deepmd_root/lib/libdeepmd_cc.so, not found (try using -rpath or -rpath-link)
```
