### ISSUE TITLE
Different PBE energies on rotated structure

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#1898]
### Describe the bug

There are two systems related by a simple rotation. When carrying out PBE calculations on the two systems, the energy of the rotated system (-1.459241e+05) is lower than that of the original system (-1.459145e+05) by about 10 eV.
The two systems are attached.
[abacus_rotated.zip](https://github.com/deepmodeling/abacus-develop/files/10740917/abacus_rotated.zip)
[abacus_original.zip](https://github.com/deepmodeling/abacus-develop/files/10740920/abacus_original.zip)

**Comment by dyzheng** [comment]
I will test this issue.

**Comment by dyzheng** [comment]
![image](https://user-images.githubusercontent.com/49852742/219379003-7de704f4-671b-4ee2-8cb2-a8614c83fe94.png)

**Comment by wenfei-li** [comment]
solved
