### ISSUE TITLE
nscf calculation error

### ISSUE THREAD

**Issue by zjdai** [deepmodeling/abacus-develop#1902]
### Describe the bug

- calculation material MnBiTe with nspin =4 
- band stru is different with vasp result by abacus
- abacus version 3.1.2 
- the scf result is correct because the band stru is agree with vasp result using pyatb software by output the HS matrix.

### Expected behavior

[MnBiTe.zip](https://github.com/deepmodeling/abacus-develop/files/10756335/MnBiTe.zip)

**Comment by dyzheng** [comment]
I have tested, BANDS1.txt from nscf and istate.info from scf is same. 
Can you compare with two files above in your consequence?

**Comment by dyzheng** [comment]
Second electronic step difference

**Comment by LiuXiaohui123321** [comment]
Is the error reported here related to the compilation environment? And is there a more detailed and specific description of this error? For example, in which compilation environment the error will or will not occur. @dyzheng @zjdai

**Comment by dyzheng** [comment]
Two compilation environment are correct:
- https://github.com/deepmodeling/abacus-develop/blob/develop/Dockerfile.gnu
    - This image is available for testing: "registry.dp.tech/deepmodeling/abacus-gnu:latest"
- https://github.com/deepmodeling/abacus-develop/blob/develop/Dockerfile.intel
    - This image is available for testing: "registry.dp.tech/deepmodeling/abacus-intel:latest"
