### ISSUE TITLE
Problems encountered in cell-relax. 

### ISSUE THREAD

**Issue by HongSPang** [deepmodeling/abacus-develop#1905]
### Describe the bug

It seems that ABACUS is unable to do cell-relax with more than one node. Performing in single node with multiple cores is fine. Yet it falls to start calculating when submitting the job on more than one node.

### Expected behavior
[example.zip](https://github.com/deepmodeling/abacus-develop/files/10782859/example.zip)

_No response_

**Comment by dyzheng** [comment]
I retested and result is correct.
