### ISSUE TITLE
relax bug for magnetic material

### ISSUE THREAD

**Issue by zjdai** [deepmodeling/abacus-develop#1913]
### Describe the bug

- abacus version developer-3.1.2
- FeCl2 structure  is a 2D aterial
- The optimization of the first ionization step is correct，but the magnetizaiton of the first step of the second ionization step is wrong

### Expected behavior

[FeCl.zip](https://github.com/deepmodeling/abacus-develop/files/10765135/FeCl.zip)

**Comment by dyzheng** [comment]
It looks not wrong, you can set parameter "relax_scale_force" a small value (0.1) to avoid huge Cl atom movement in second configuration.

**Comment by dyzheng** [comment]
Set maximum of atomic movement.
