### ISSUE TITLE
Magnetic calculation 

### ISSUE THREAD

**Issue by Shen-Zhen-Xiong** [deepmodeling/abacus-develop#1914]
### Background

Recently, when using ABACUS to calculate magnetic materials, I found that there are not many functions currently supported.  Local orbital magnetic moment output, self-consistent calculation of fixed specific magnetic atom direction， these descriptions of the properties of magnetic systems are very important.

### Describe the solution you'd like

1. Only the calculation of LCAO+nspin=2 can be input into the charge analysis mulliken.txt file to view the local orbital magnetic moment of the relevant atoms; Can the muliken.txt file be output in the calculation of pw (and lcao)+nspin=2 (and 4)? In this way, the local orbital magnetic moment can also be seen in the spin-orbit coupling calculation and non-collinear calculation.

2. In the calculation of magnetic system, another point is more important. I need to fix the magnetic moment of each spin atom to a specific direction. For example, in the Fe atom system of the 229 space group, I want to fix the spin magnetic moment of  Fe1 (coordinates: (0.0, 0.0, 0.0))  to S1 (2.0, 0.0, 0.0), and the spin magnetic moment of  Fe2 atom (coordinates: (0.5, 0.5, 0.5))  to  S2 (0.0, 1.2, 2.3), and then carry out self-consistent calculation to output the system energy.

**Comment by dyzheng** [comment]
Problem 1: output atomic charge with LCAO and nspin=4 will be implemented by me.
