### ISSUE TITLE
Abacus Run Time Question

### ISSUE THREAD

**Issue by iduygnay** [deepmodeling/abacus-develop#1915]
### Details

Hi, I just find that different versions will lead to different total CPU time and different memory requirements in the abacus. But I'm not sure whether this is caused by myself (like something wrong with the installation) or by the abacus. Here I offer the INPUT, KPT, and STRU files. 
In this case, I calculated it by ABACUS 2.3.0 and 3.1. For 2.3.0, it only used 32 cores and 3 hours, but for 3.1, it spent more than one day only calculating 2 electron steps. (See the figures below)
Also, for 2.3.0, it can be calculated by 16 cores, however, for 3.1, it says that out of memory. 
[0.zip](https://github.com/deepmodeling/abacus-develop/files/10776927/0.zip)
![image](https://user-images.githubusercontent.com/109792836/219950101-2a5d7b9b-0408-4737-89d7-7f8be2267070.png)
![image](https://user-images.githubusercontent.com/109792836/219950121-033abd2d-6ce7-4585-ab57-305886e21217.png)

Looking forward to your response.

**Comment by caic99** [comment]
Hi @iduygnay ,
Would you check [the instructions on running ABACUS](https://abacus.deepmodeling.com/en/latest/quick_start/easy_install.html#run)? More specifically, please make sure the env var `OMP_NUM_THREADS` is set.

**Comment by caic99** [comment]
@iduygnay I'm trying to reproduce this, but it seems that the orbital file is not provided.

**Comment by iduygnay** [comment]
[Uploading SG15_PBE.zip…]()
[Uploading SG15_Orbits.zip…]()
Please find attached the files of pseudopotential and orbit files

**Comment by iduygnay** [comment]
I used conda install

**Comment by caic99** [comment]
> I used conda install

Hi @iduygnay ,
would you refer to Q1 on https://abacus.deepmodeling.com/en/latest/community/faq.html#failed-jobs , and try again. These steps are always required, no matter what installation method are taken.

**Comment by caic99** [comment]
> Uploading SG15_PBE.zip… Uploading SG15_Orbits.zip… Please find attached the files of pseudopotential and orbit files

@iduygnay These files seem to be not available 🤣 Next time close the webpage after the process finished

**Comment by iduygnay** [comment]
Thank you so much! I think I found what's wrong with my cases.
