### ISSUE TITLE
Output error for HS matrixa in spin=2 system

### ISSUE THREAD

**Issue by zjdai** [deepmodeling/abacus-develop#1918]
### Describe the bug

- abacus version 3.1.2 
- test system Co3Sn2S2 for spin=2 system
- correct for output HS matrixa in spin=4 system

### Expected behavior

[CoSnS.zip](https://github.com/deepmodeling/abacus-develop/files/10779171/CoSnS.zip)

**Comment by zjdai** [comment]
the output function is correct in abacus developer version 2.2.1

**Comment by dyzheng** [comment]
#2135
