### ISSUE TITLE
Improvement of electric field in tddft

### ISSUE THREAD

**Issue by lyb9812** [deepmodeling/abacus-develop#1935]
### Describe the bug

Code of electric field in tddft need improvements.
1. The energy and force of electric field in tddft is lacked
2. In write_dipole.cpp, if ions' positions are fixed, ionic dipole is not necessary for calculation of absorption spectrum.

**Comment by dyzheng** [comment]
Does this issue completed?

**Comment by lyb9812** [comment]
> Does this issue completed?

Not yet.
