### ISSUE TITLE
 In the gpu environment,  Unable to run the official example si16_pw

### ISSUE THREAD

**Issue by zhengzzhiy** [deepmodeling/abacus-develop#1937]
### Details

After installing the CUDA,, executing "cmake - B build - DUSE_CUDA=1", I can't run the official example si16_pw given in directory /abacus-develop/examples/gpu. 

The warning information is:device  warning : INPUT device setting does not match the request!
Other informations are:
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 INPUT device setting does not match the request!
 CHECK IN FILE : OUT.autotest/warning.log
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  |CLASS_NAME---------|NAME---------------|TIME(Sec)-----|CALLS----|AVG------|PER%-------
 ----------------------------------------------------------------------------------------
 See output information in : OUT.autotest/
--------------------------------------------------------------------------
mpirun has exited due to process rank 17 with PID 0 on
node zzy-Precision-7920-Tower exiting improperly. There are three reasons this could occur:

1. this process did not call "init" before exiting, but others in
the job did. This can cause a job to hang indefinitely while it waits
for all processes to call "init". By rule, if one process calls "init",
then ALL processes must call "init" prior to termination.

2. this process called "init", but exited without calling "finalize".
By rule, all processes that call "init" MUST call "finalize" prior to
exiting or it will be considered an "abnormal termination"

3. this process called "MPI_Abort" or "orte_abort" and the mca parameter
orte_create_session_dirs is set to false. In this case, the run-time cannot
detect that the abort call was an abnormal termination. Hence, the only
error message you will receive is this one.

This may have caused other processes in the application to be
terminated by signals sent by mpirun (as reported here).

You can avoid this message by specifying -quiet on the mpirun command line.
-------------------------------------------------------------------------

**Comment by caic99** [comment]
Hi @zhengzzhiy ,
Thank you for trying the GPU-supported ABACUS!
There are many cases causing the computation fall back to CPU. Would you please refer to [the codes](https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_psi/kernels/device.cpp#L557-L577) handling exceptions, and check if your input is compatible with our implementation.
And, would you use `nvidia-smi` to check if your GPU driver and CUDA environment is all set.

@denghuilu @haozhihan plz take a look on this issue, thanks!

**Comment by zhengzzhiy** [comment]
Thank you @caic99
Yes, I have used nvidia-smi and nvcc -V to check if my GPU driver and CUDA environment is all set.
I run the official examples si16_pw, and the input file are:
```
INPUT_PARAMETERS
#Parameters (1.General)
suffix			autotest
calculation		scf
#nbands			8
symmetry		1
device			gpu

#Parameters (2.Iteration)
ecutwfc			60
scf_thr			1e-8
scf_nmax		100
cal_force 		1
cal_stress 		1
#Parameters (3.Basis)
basis_type		pw

#Parameters (4.Smearing)
smearing_method		gauss
smearing_sigma		0.002

#Parameters (5.Mixing)
mixing_type		pulay
mixing_beta		0.3
```
The GPU information are:
```
nvidia-smi
Thu Feb 23 09:20:15 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 4000     Off  | 00000000:73:00.0  On |                  N/A |
| 30%   23C    P8    22W / 125W |    450MiB /  8192MiB |     13%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2467      G   /usr/lib/xorg/Xorg                126MiB |
|    0   N/A  N/A      2638      G   /usr/bin/gnome-shell               80MiB |
|    0   N/A  N/A      3658      G   ...6/usr/lib/firefox/firefox      215MiB |
+-----------------------------------------------------------------------------+
```
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Jan__6_16:45:21_PST_2023
Cuda compilation tools, release 12.0, V12.0.140
Build cuda_12.0.r12.0/compiler.32267302_0

After all these have been done, it still doesn't work.

**Comment by denghuilu** [comment]
@zhengzzhiy, please refer to PR #1957 for more debugging information.
