### ISSUE TITLE
TDDFT branch segfault

### ISSUE THREAD

**Issue by ESROAMER** [deepmodeling/abacus-develop#1949]
### Describe the bug

I was doing some tddft calculation with abacus-develop under the new tddft branch. All of them Interupt like this:
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 141248 RUNNING AT cu03
=   EXIT CODE: 11
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
I also ran an example under example/md, it works fine, so maybe there is some problem with my pesudo or orbital files?

### To Reproduce

I packed all of my input files up,  you may reproduce with them.
[CH4.zip](https://github.com/deepmodeling/abacus-develop/files/10821875/CH4.zip)

**Comment by caic99** [comment]
@lyb9812 This is a segfault error. Would check it using address sanitizer.
Please also take a look on [this error](https://github.com/deepmodeling/abacus-develop/actions/runs/4156612271/jobs/7190517662#step:5:1360).

**Comment by lyb9812** [comment]
> @lyb9812 This is a segfault error. Would check it using address sanitizer.
> Please also take a look on [this error](https://github.com/deepmodeling/abacus-develop/actions/runs/4156612271/jobs/7190517662#step:5:1360).

I cannot reproduce your error on my workstation. And the report is not detailed for me to locate the error now. What's your opinion?
