### ISSUE TITLE
Can ABACUS protect structure symmetry during relaxation ?

### ISSUE THREAD

**Issue by maki49** [deepmodeling/abacus-develop#1978]
### Details

When `calculation=relax` and `symmetry=1` are set, will the stucture symmetry  (point/space group) be protected? 

If yes, how?（Is it guaranteed by `force_symmetry`? ）

**Comment by dyzheng** [comment]
It suppose to be yes, force_symmetry will guarantee it, if you find any case not, you can report the case.

**Comment by dyzheng** [comment]
hello, have you find some cases that structure symmetry changed during relaxation?
