### ISSUE TITLE
Output eigenvalues, eigenvectors and density matrix of Kohn-Sham equation  

### ISSUE THREAD

**Issue by willyywt** [deepmodeling/abacus-develop#2006]
### Details

I am currently developing [ELSI](https://wordpress.elsi-interchange.org/) which is a collection of various Kohn-Sham equation solvers. In abacus the input `out_mat_hs` can be used to output the Hamiltonian and Overlap Matrices. But I would like to compare the eigenvalues, eigenvectors and density matrix results from abacus and ELSI. Is there any way to output such result from abacus?

**Comment by sunliang98** [comment]
The eigenvalues, eigenvectors, and density matrix can be output by turning on `out_wfc_lcao`, `out_band`, and `out_dm`, respectively. Detailed descriptions can be found at [here](http://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html).

**Comment by willyywt** [comment]
I see, thank you
