### ISSUE TITLE
Element consistency check should be made between pseudopotential files and LCAO orbital files

### ISSUE THREAD

**Issue by ouqi0711** [deepmodeling/abacus-develop#2018]
### Background

In an LCAO calculation, UPF files and orbital files are provided independently. **No warning/error message would be given if the element type of the UPF and the orbital file were different**. In other words, if the user provided the wrong UPF/orbital file, she/he would still get a normally-finished job (w/ definitely wrong results).

### Describe the solution you'd like

A consistency check of the element type should be made between UPF and orbital files.

**Comment by Zhuxuegang2022** [comment]
I will try to solve it

**Comment by hongriTianqi** [comment]
- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by hongriTianqi** [comment]
@ouqi0711 This issue has been solved by @Zhuxuegang2022. You may have a test.
