### ISSUE TITLE
Some issues regarding several input variables

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#203]
First of all, we will need some short explanation or (preferably) some documentation on the input variables regarding:
**DFT+U
Hybrid functional
Spectrum
TDDFT**

Secondly, there are a few variables that seems are either not implemented yet or already obsolete:

**mlwf_flag
diago_cg_prec
restart_mode
restart_save
restart_load
input_error
mdoutputpath**

Also, the variable **lmaxmax** sets an upper bound for l channels in atomic orbital basis set, is there a particular reason for doing so?

**Comment by wenfei-li** [comment]
latname is implemented, to be tested and documented soon

**Comment by mohanchen** [comment]
Great, I will give some feedbacks asap.

**Comment by dyzheng** [comment]
move this Issue to #502
