### ISSUE TITLE
memory problem of pzhegvx_()

### ISSUE THREAD

**Issue by lyb9812** [deepmodeling/abacus-develop#2032]
### Describe the bug

We do unit test for pzhegvx, pzgetri, pzgetrf, pzgeadd , and find that memory problem only exists in pzhegvx. In code of siesta, there are two methods to solve eigenvalue (related parameter : Diag.AllInOne ). The first method is using pzhegvx and the second method divides the problem into four steps (using four scalapack functions). And the second method is the default one now. So maybe we also need to abandon pzhegvx.

reference of the second method :(https://cndaqiang.github.io/2019/08/04/HC_SCE/)

**Comment by Qianruipku** [comment]
pzhegvx() indeed has some bugs. However we can control our input parameters to avoid it.
RWORK must have a space of at least sizeof(double)*3.
VU and Vl must be a variable but not NULL.
