### ISSUE TITLE
Bug (double free or corruption (!prev)) in realx of pw at 2500 kbar

### ISSUE THREAD

**Issue by Chentao168** [deepmodeling/abacus-develop#2054]
### Describe the bug

When I relaxed HCP Sn at 2500 kbar, ABACUS met the bug (double free or corruption (!prev)). More information can be seen in the zip file.

### To Reproduce

[2023-03-12-bug_err.zip](https://github.com/deepmodeling/abacus-develop/files/10950252/2023-03-12-bug_err.zip)

### Environment

ABACUS 3.1.4 at intel oneapi 2021

**Comment by dyzheng** [comment]
@Chentao168 Please set "relax_scale_force              0.1" for this case.

**Comment by Chentao168** [comment]
在3.2版本重新测试这个例子，发现设置relax_scale_force 0.1，可以正常跑，但是不设置的话会出现报错“Can't find even an electron!”，跟 https://github.com/deepmodeling/abacus-develop/issues/1534 这个issue完全一致，但我这个例子可以很容易复现，希望能帮助定位bug。

I try to repeat this example in version 3.2 and find that setting relax_scale_force 0.1 can run normally. But if not set, there will be an error message 'Can't find even an electron!' This is completely same as the issue https://github.com/deepmodeling/abacus-develop/issues/1534, but my example can be easily replicated. I hope it can help locate the bug.

![image](https://user-images.githubusercontent.com/76426373/231086589-dae4e7e4-a43c-4058-9833-386870d630bc.png)

**Comment by dyzheng** [comment]
It is not a bug, maybe there should be a restriction that atom positions and lattice vectors can not change too much in one step of Relaxation.

**Comment by Qianruipku** [comment]
When the volume of the cell changes rapidly, maybe a "Warning" or "Warning_quit" can be added. And tell the user to reduce the relax_scale_force parameter.

**Comment by Chentao168** [comment]
我使用修改过的代码重新做了测试，已经可以正常relax了。但是在第二步结束后屏幕输出出现了
```
 x = 2.316e+01
 table_interval = 1.000e-02
 iq=2315 table_length = 1424

 Not enough space allocated for radial FFT: try restarting with a larger cell_factor
```
 直到进行第三步SCF，它一共重复了36360次！可能需要解决一下这个输出问题。@Qianruipku @YuLiu98 

I retested using the modified code and can now relax normally. But after the second step, the screen output appears
```
 x = 2.316e+01
 table_interval = 1.000e-02
 iq=2315 table_length = 1424

 Not enough space allocated for radial FFT: try restarting with a larger cell_factor
```
It repeated a total of 36360 times until the third step of SCF. It may be necessary to address this output issue.

![cde0184a-bf6e-41fd-8c74-47fdbab8fdf6](https://user-images.githubusercontent.com/76426373/233656349-e2d75fae-fc4f-46cc-b6d2-b75b8c4f4957.jpeg)
