### ISSUE TITLE
input checks

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#207]
**Is your feature request related to a problem? Please describe.**

The input check is not very comprehensive. Sometimes the user will not be notified of problematic input, and the calculation will proceed to give wrong results.
For example, if there are two types of elements in the system, while in INPUT, ntype is supplied as 1, then the program will proceed after reading information regarding the first element from STRU file, without notifying the user that ntype is wrong.
Also, it is possible to run the calculation without supplying lattice vectors in STRU file. It seems that a simple cubic lattice will be assumed in this case, and the user is not notified about this either.

**Describe the solution you'd like**
To implement more checks when reading input.
Regarding the ntype problem, maybe we could end the atoms session from STRU file with some special character, and keep reading till that special character. In this way, if there are more elements in the STRU file than specified by ntype parameter, we can raise an error message.
Regarding the lattice vector problem, I can try to add a simple check there.

**Additional context**
It would be nice to know if anyone has some other input checks in mind, so that we could start to improve them.

**Comment by mohanchen** [comment]
Excellent! We should definitely fix these issues.

**Comment by dyzheng** [comment]
[#290 ](url)

**Comment by dyzheng** [comment]
Another important input check is the error input in INPUT file should be reported.
Such as charge_extrap parameter, if key word is "second_order", there should be a report for this input key word error for user.

**Comment by wenfei-li** [comment]
We are planning to do this later during the refactor of ucell class.

**Comment by dyzheng** [comment]
The problem mentioned in this Issue has been solved, and we will check input lists carefully in future.
