### ISSUE TITLE
[Self-consistent convergence problem]

### ISSUE THREAD

**Issue by Shen-Zhen-Xiong** [deepmodeling/abacus-develop#2083]
### Details

The electronic self-consistence of a system containing about 20 A vacuum layer is calculated. It is found that the system charge density is still difficult to converge to 1e-06 and oscillates repeatedly around 4e-05 by using the pulay charge mixing method, reducing the mixing parameter beta to 0.01 and increasing the mixing dimension to 30, but at this time the system energy difference has converged to 1e-10 What's the matter, please? There are preliminary guesses as follows:

1. At present, the interface system is not easy to converge and needs to optimize the algorithm;

2. The energy threshold can be increased to judge the convergence condition. When the energy difference is less than 1e-10 (or other), the self-consistent end can also be determined;

3. Reduce the charge density convergence standard to 4e-05, but it cannot guarantee that every energy convergence is very good.

The attachment is my calculation input parameters and log.
（appendix：  https://bbs.abacus-dft.com/forum.php?mod=viewthread&tid=20&extra=）

**Comment by dyzheng** [comment]
![image](https://user-images.githubusercontent.com/49852742/225265531-0da995e7-f2bc-472a-a423-ef15dde7b06b.png)
