### ISSUE TITLE
Wrong results when out_mat_hs=1 and spin!=1

### ISSUE THREAD

**Issue by lyb9812** [deepmodeling/abacus-develop#2111]
### Describe the bug

If I set out_mat_hs =1 and spin=2, the total energy is different from  the result of out_mat_hs=0 and spin=2 a lot.

### To Reproduce

For Example，304_NO_GO_FM. Comment "if (hsolver::HSolverLCAO::out_mat_hs)" in hsolver_lcao.cpp .

**Comment by dyzheng** [comment]
Can you show some detail? 
I tested case 304_NO_GO_FM and don't find the difference between out_mat_hs=0 and out_mat_hs=1 .

**Comment by lyb9812** [comment]
> Can you show some detail?
> I tested case 304_NO_GO_FM and don't find the difference between out_mat_hs=0 and out_mat_hs=1 .

You need to comment code "if (hsolver::HSolverLCAO::out_mat_hs)" in hsolver_lcao.cpp.

**Comment by dyzheng** [comment]
> > Can you show some detail?
> > I tested case 304_NO_GO_FM and don't find the difference between out_mat_hs=0 and out_mat_hs=1 .
> 
> You need to comment code "if (hsolver::HSolverLCAO::out_mat_hs)" in hsolver_lcao.cpp.

I tried and result is same :
```
 GE1    -4.99e-05 2.55e-02  -1.959401e+02  0.000000e+00   4.179e-01  1.011e-01  
 GE2    -1.95e-05 6.96e-03  -1.960493e+02  -1.091775e-01  1.094e-01  5.659e-02  
 GE3    -7.10e-06 2.56e-03  -1.960550e+02  -5.713281e-03  3.042e-02  5.828e-02  
 GE4    -2.64e-06 9.31e-04  -1.960553e+02  -2.883582e-04  8.782e-03  5.851e-02  
 GE5    -9.73e-07 3.34e-04  -1.960553e+02  -4.033030e-06  2.574e-03  6.160e-02  
 GE6    -3.57e-07 1.20e-04  -1.960553e+02  4.276661e-06   7.592e-04  5.687e-02  
 GE7    -1.31e-07 4.28e-05  -1.960553e+02  1.600496e-06   2.250e-04  5.960e-02  
 GE8    -4.79e-08 1.53e-05  -1.960553e+02  4.805185e-07   6.723e-05  5.849e-02  
 GE9    -1.75e-08 5.47e-06  -1.960553e+02  1.389916e-07   2.028e-05  5.819e-02  
 GE10   -6.39e-09 1.96e-06  -1.960553e+02  4.028976e-08   6.189e-06  5.674e-02  
 GE11   -2.33e-09 7.01e-07  -1.960553e+02  1.180239e-08   1.908e-06  6.174e-02  
 GE12   -8.52e-10 2.51e-07  -1.960553e+02  3.492746e-09   5.957e-07  5.698e-02  
 GE13   -3.11e-10 9.00e-08  -1.960553e+02  1.042246e-09   1.883e-07  6.369e-02  
 GE14   -1.13e-10 3.22e-08  -1.960553e+02  3.129347e-10   6.046e-08  5.564e-02  
 GE15   -4.12e-11 1.16e-08  -1.960553e+02  9.474081e-11   1.974e-08  5.703e-02  
 GE16   -1.50e-11 4.15e-09  -1.960553e+02  2.789054e-11   6.550e-09  6.028e-02 
```

Can you show the error result?

**Comment by lyb9812** [comment]
> > > Can you show some detail?
> > > I tested case 304_NO_GO_FM and don't find the difference between out_mat_hs=0 and out_mat_hs=1 .
> > 
> > 
> > You need to comment code "if (hsolver::HSolverLCAO::out_mat_hs)" in hsolver_lcao.cpp.
> 
> I tried and result is same :
> 
> ```
>  GE1    -4.99e-05 2.55e-02  -1.959401e+02  0.000000e+00   4.179e-01  1.011e-01  
>  GE2    -1.95e-05 6.96e-03  -1.960493e+02  -1.091775e-01  1.094e-01  5.659e-02  
>  GE3    -7.10e-06 2.56e-03  -1.960550e+02  -5.713281e-03  3.042e-02  5.828e-02  
>  GE4    -2.64e-06 9.31e-04  -1.960553e+02  -2.883582e-04  8.782e-03  5.851e-02  
>  GE5    -9.73e-07 3.34e-04  -1.960553e+02  -4.033030e-06  2.574e-03  6.160e-02  
>  GE6    -3.57e-07 1.20e-04  -1.960553e+02  4.276661e-06   7.592e-04  5.687e-02  
>  GE7    -1.31e-07 4.28e-05  -1.960553e+02  1.600496e-06   2.250e-04  5.960e-02  
>  GE8    -4.79e-08 1.53e-05  -1.960553e+02  4.805185e-07   6.723e-05  5.849e-02  
>  GE9    -1.75e-08 5.47e-06  -1.960553e+02  1.389916e-07   2.028e-05  5.819e-02  
>  GE10   -6.39e-09 1.96e-06  -1.960553e+02  4.028976e-08   6.189e-06  5.674e-02  
>  GE11   -2.33e-09 7.01e-07  -1.960553e+02  1.180239e-08   1.908e-06  6.174e-02  
>  GE12   -8.52e-10 2.51e-07  -1.960553e+02  3.492746e-09   5.957e-07  5.698e-02  
>  GE13   -3.11e-10 9.00e-08  -1.960553e+02  1.042246e-09   1.883e-07  6.369e-02  
>  GE14   -1.13e-10 3.22e-08  -1.960553e+02  3.129347e-10   6.046e-08  5.564e-02  
>  GE15   -4.12e-11 1.16e-08  -1.960553e+02  9.474081e-11   1.974e-08  5.703e-02  
>  GE16   -1.50e-11 4.15e-09  -1.960553e+02  2.789054e-11   6.550e-09  6.028e-02 
> ```
> 
> Can you show the error result?

Comment "if " and "out_mat_hs=0" and the result is the following one.
ITER   TMAG      AMAG      ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
 GE1    -7.93e+00 7.93e+00  -7.205824e+02  0.000000e+00   1.258e+00  1.581e-01  
 GE2    -7.10e+00 7.10e+00  -1.236814e+03  -5.162318e+02  2.906e-01  1.033e-01  
 GE3    -7.15e+00 7.15e+00  -1.206276e+03  3.053874e+01   9.986e-02  1.800e-01  
 GE4    -7.10e+00 7.10e+00  -1.185784e+03  2.049172e+01   2.953e-02  1.390e-01  
 GE5    -7.08e+00 7.08e+00  -1.174531e+03  1.125238e+01   8.750e-03  1.064e-01  
 GE6    -7.08e+00 7.08e+00  -1.169821e+03  4.710097e+00   2.600e-03  1.069e-01  
 GE7    -7.08e+00 7.08e+00  -1.168073e+03  1.748042e+00   7.665e-04  1.064e-01  
 GE8    -7.08e+00 7.08e+00  -1.167476e+03  5.972679e-01   2.348e-04  1.058e-01  
 GE9    -7.08e+00 7.08e+00  -1.167284e+03  1.924941e-01   7.732e-05  1.045e-01  
 GE10   -7.08e+00 7.08e+00  -1.167224e+03  5.953876e-02   2.484e-05  1.136e-01  
 GE11   -7.08e+00 7.08e+00  -1.167206e+03  1.787948e-02   7.946e-06  1.089e-01  
 GE12   -7.08e+00 7.08e+00  -1.167201e+03  5.253132e-03   2.525e-06  1.166e-01  
 GE13   -7.08e+00 7.08e+00  -1.167199e+03  1.517868e-03   7.931e-07  1.463e-01  
 GE14   -7.08e+00 7.08e+00  -1.167199e+03  4.328650e-04   2.469e-07  1.099e-01  
 GE15   -7.08e+00 7.08e+00  -1.167199e+03  1.221440e-04   7.632e-08  1.073e-01  
 GE16   -7.08e+00 7.08e+00  -1.167199e+03  3.416775e-05   2.347e-08  1.085e-01  
 GE17   -7.08e+00 7.08e+00  -1.167199e+03  9.487713e-06   7.185e-09  1.046e-01

It is due to the problem of memory probably. This is similar to issue #1968 .

**Comment by dyzheng** [comment]
Another problem is data-0-H is same as data-1-H, I will solve it.

**Comment by dyzheng** [comment]
I didn't see any memory problem in case 304_NO_GO_FM using "ENABLE_ASAN=1".

**Comment by lyb9812** [comment]
> I didn't see any memory problem in case 304_NO_GO_FM using "ENABLE_ASAN=1".

There exists memory problem using valgrind according to LiuQianrui.
