### ISSUE TITLE
A proper threshold of  distance is needed  when calculating asynchronous overlap matrix

### ISSUE THREAD

**Issue by lyb9812** [deepmodeling/abacus-develop#2112]
### Describe the bug

To provide asynchronous overlap matrix, I find that a proper threshold of  distance is needed. The value of tiny2(e-10) in snap_psipsi() need to be set larger to avoid divergency on this occasion. Because the distance of the same atom is vdt, which is a very small number but larger than e-10. And I am not sure about the proper value of tiny2 now.

**Comment by dyzheng** [comment]
Maybe when distance small than 1e-10, asynchronous overlap matrix element is same as synchronous one.
You should test it, I don't think it belongs to "bug" tag
