### ISSUE TITLE
Please provide information on the new input variable md_prec_level

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#2163]
### Describe Current Status and Possible Solution

I have noticed the following lines in esolver:

```
        if(GlobalV::CALCULATION == "md" && istep)
        {
            // different precision level for vc-md
            if(GlobalC::ucell.cell_parameter_updated && GlobalV::md_prec_level == 2)
            {
                this->init_after_vc(INPUT, GlobalC::ucell);
            }
            else
            {
                this->CE.update_all_dis(GlobalC::ucell);
                this->CE.extrapolate_charge(this->pelec->charge);
                if(GlobalC::ucell.cell_parameter_updated && GlobalV::md_prec_level == 0)
                {
                    Variable_Cell::init_after_vc();
                }
            }
        }
```

The new input variable md_prec_level has not been explained in the documentation.
Besides, it does not seem to be a good practice to have two method 'init_after_vc' which has overlapping functionalities but are places in different classes. It would be better if this part can be reorganized.

**Comment by YuLiu98** [comment]
The detail of the new para `md_prec_level` can be found here: https://github.com/deepmodeling/abacus-develop/blob/develop/docs/advanced/input_files/input-main.md#md_prec_level
