### ISSUE TITLE
out_pot, out_element_info and out_proj_band keywords are not well-explained in full list of input parameter

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#2166]
### Background

As described in title, out_pot, out_proj_band and out_element_info  may be better explained. 
Specifically, as already explained in description of  out_pot, the term ‘local potential’ may be somewhat ambiguous, is it something about ELF the electron localization function? 
For parameter 'out_proj_band', although there is a worked example, it may be better to explain the projection operation, say what is the basis on which band structure is projected. 
While for out_element_info, the description may seem to be left incompleted...

Hope it would help ABACUS become better :)

### Describe the solution you'd like

Improve description of parameters in online manual (https://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.htm) asap.

**Comment by mohanchen** [comment]
This has been resolved, thanks.
