### ISSUE TITLE
Extremely slow in rho_symmetry 

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#2168]
### Describe the bug

In case tests/performance/P103_si128_lcao, I found it is extremely slow in rho_symmetry function.
Container of ABACUS-intel:latest:
```
Driver              driver_line         372.63         1         3.7e+02   1e+02     %
Symmetry            rho_symmetry        240.8          9         27        65        %
```
consequence with setting "symmetry 0"
```
Driver              driver_line         130.77         1         1.3e+02   1e+02     %
```

Container of ABACUS-gnu:latest : 
```
Driver              driver_line         1664.9         1         1.7e+03   1e+02     %
Symmetry            rho_symmetry        1392.1         9         1.5e+02   84        %
```

### Expected behavior

Please solve the problem, the efficiency of rho_symmetry is too slow!

### To Reproduce

OMP_NUM_THREADS=1 mpirun -np 4 ~/abacus-develop/build/abacus

**Comment by dyzheng** [comment]
I can repeat this result in bohrium.

**Comment by maki49** [comment]
I added some `timer::tick`s in rhog_symmetry and tested on my workstation. 
![image](https://user-images.githubusercontent.com/33978601/228616875-d37bfd4f-01cd-4565-a8b6-3ea62ba6383f.png)
The specialty of this configuration is a supercell built by **64 primitive cells**. 
Codes between ticker `rhog_symmetry-supercell`: https://github.com/deepmodeling/abacus-develop/blob/40690817860f7c2d9177efd4587f837552a1ca03/source/module_cell/module_symmetry/symmetry.cpp#L1414-L1419

( I'm just giving some details of the problem, maybe someone have good idea to solve this? )

Or else, maybe `rhog_symmetry` is not needed to be called in **every** electronic step?（Escpecially for LCAO and impure point group, which has to use reciprocal-space rhogsymmetry that introduce cut-off errors by FFT. ）

**Comment by dyzheng** [comment]
> I added some `timer::tick`s in rhog_symmetry and tested on my workstation. ![image](https://user-images.githubusercontent.com/33978601/228616875-d37bfd4f-01cd-4565-a8b6-3ea62ba6383f.png) The specialty of this configuration is a supercell built by **64 primitive cells**. Codes between ticker `rhog_symmetry-supercell`:
> 
> https://github.com/deepmodeling/abacus-develop/blob/40690817860f7c2d9177efd4587f837552a1ca03/source/module_cell/module_symmetry/symmetry.cpp#L1414-L1419
> 
> ( I'm just giving some details of the problem, maybe someone have good idea to solve this? )
> 
> Or else, maybe `rhog_symmetry` is not needed to be called in **every** electronic step?（Escpecially for LCAO and impure point group, which has to use reciprocal-space rhogsymmetry that introduce cut-off errors by FFT. ）

Please move lines 1414 to 1419 in front of line 1361 (for loop of i j k), using a temporary vector to save the sin and cos values.

**Comment by dyzheng** [comment]
@maki49 The rotation part should be optimized too, you can seperate the function rotate() such as:
1. matrix3 g should be in front of loop i,j,k;
2. calculation of index i should be in front of loop j,k;
3. calculation of index j should be in front of loop k;
4. calculation of index k and others should keep in the function rotate() and change this function to inline function .

**Comment by maki49** [comment]
> Please move lines 1414 to 1419 in front of line 1361 (for loop of i j k), using a temporary vector to save the sin and cos values.

`tmp_gdirect_double` (and so `arg`) changes after each rotation, so I cannot move these lines before  the loop of  `isym`. 

I optimized something that I can find out in PR #2171 .

**Comment by dyzheng** [comment]
I have tested the case "tests/performance/P103_si128_lcao", time of rhog_symmetry optimized from 2511.4 s to 596.36 s , this is a significant improvement. 
However, it is still in O(N^3) and be the dominate cost of this case (~80%).

**Comment by dyzheng** [comment]
> > Please move lines 1414 to 1419 in front of line 1361 (for loop of i j k), using a temporary vector to save the sin and cos values.
> 
> `tmp_gdirect_double` (and so `arg`) changes after each rotation, so I cannot move these lines before the loop of `isym`.
> 
> I optimized something that I can find out in PR #2171 .

The only shifty variable is "rhogtot" in this function, you can try to save a planning of how to deal with the incoming "rhogtot", the memory cost of the planning would be large, but I think it is worth to do it @maki49 .

**Comment by dyzheng** [comment]
Another problem of this function is OpenMP is not considered.

**Comment by wenfei-li** [comment]
I'm wondering if this issue has been solved?

**Comment by dyzheng** [comment]
Yes，performance now can be accepted.

**Comment by dyzheng** [comment]
rhog_symmetry still need to optimized, mentioned in #2611

**Comment by hongriTianqi** [comment]
- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by dyzheng** [comment]
This Issue is outdated, performance of rho_symmetry is not a bottleneck now.
