### ISSUE TITLE
md_type and md_thermostat two parameters of md may need to be improved

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#2170]
### Background

commonly it is suggested to set ensemble and thermostat/barostat for MD separately. However presently the way to control ensemble and thermostat in abacus is somewhat entangled.

### Describe the solution you'd like

 A more reasonable choice may be:
**keyword**: md_type
options: -1: FIRE (for relax); 0: NVE; 1: NVT; 2: NPT (Nose-Hoover style); 3: Langevin dynamics (NVT); 4: MSST
_(ps.: I am not sure if the option-2 exactly means Nose-Hoover thermostat and barostat. If so, it is better to move it to option list of keyword md_thermostat. I also notice that there is another parameter names md_pmode, while if set it as 0, NVT ensemble is activated. There's something redundant.)_
**keyword**: md_thermostat
options: 'anderson', 'berendsen', 'rescaling', 'rescale_v' and 'nose-hoover'

**Comment by dyzheng** [comment]
@YuLiu98 can you help for this issue？
