### ISSUE TITLE
Number of thread impacts on convergence when nspin=2

### ISSUE THREAD

**Issue by AroundPeking** [deepmodeling/abacus-develop#2184]
### Describe the bug

I use the lastest version of ABACUS to test the system of single C atom, nspin=2. Find that SCF convergence can be reached when thread=4, while not reached when thread=8.  
- thread=4, converge at GE98
- thread=8, not converge
The input files of single C atom and two output files of ABACUS 3.2 are followed.
[single_C.zip](https://github.com/deepmodeling/abacus-develop/files/11144664/single_C.zip)

Another version of ABACUS (3.1, commit ee0f651bec67de97b7754d38786e995c9ca56b33) shows the same issue.
- thread=1, converge at GE17
- thread=8, not converge

Early, system of diamond showed the same issue, fixed already. And now I test it, finding SCF converged at GE10 using both single and multi- thread. But when nspin=2 there still existed this issue. It seems the more threads, the harder SCF converge.

**Comment by dyzheng** [comment]
I will test it, thanks for your report.

**Comment by dyzheng** [comment]
Your test case is not insulator with initial magnetism and atomic charge, while is insulator with converged charge density, "smearing_method" can not be "fixed", I tested 
```
smearing_method gauss
smearing_sigma    1e-4
#using default mixing_beta
```
results of OMP-4-threads:
```
 GE18   2.00e+00  2.00e+00  -1.472695e+02  -4.772085e-10  1.186e-08  5.031e+00  
 GE19   2.00e+00  2.00e+00  -1.472695e+02  4.017784e-10   7.767e-10  4.789e+00  
```
and result of OMP-8-threads:
```
 GE16   2.00e+00  2.00e+00  -1.472695e+02  2.281030e-10   1.727e-09  6.611e+00  
 GE17   2.00e+00  2.00e+00  -1.472695e+02  -3.357498e-10  8.395e-10  6.112e+00  
```
and result of OMP-1-thread:
```
 GE33   2.00e+00  2.00e+00  -1.472695e+02  -1.853971e-10  1.177e-09  1.624e+01  
 GE34   2.00e+00  2.00e+00  -1.472695e+02  1.215196e-10   7.611e-10  1.422e+01  
```
the convergence results are same but convergent paths are different, I will check this problem.

**Comment by dyzheng** [comment]
Bandgap curve in iteration is 
![image](https://user-images.githubusercontent.com/49852742/230010863-9363c1d5-ea36-4087-b5d8-55985db97669.png)

**Comment by AroundPeking** [comment]
Yeah, after changing smearing from "fixed" to "gauss" and "1E-4", I can get converged SCF calculation. 

However, it leads to fractional occupation for single C atom, which gives wrong E_cRPA in LibRPA. Theoretically speaking, lowering smearing_sigma will improve this situation, however, leads to not convergence for SCF in fact. I have tested "1E-5" and "1E-6", both of which leads to not convergence.

**Comment by dyzheng** [comment]
> Yeah, after changing smearing from "fixed" to "gauss" and "1E-4", I can get converged SCF calculation.
> 
> However, it leads to fractional occupation for single C atom, which gives wrong E_cRPA in LibRPA. Theoretically speaking, lowering smearing_sigma will improve this situation, however, leads to not convergence for SCF in fact. I have tested "1E-5" and "1E-6", both of which leads to not convergence.

For this problem, I suggest you to try this two-step calculation:
```
smearing_method gauss
smearing_sigma 1e-4
out_chg               1
```
do ABACUS calculation with this setting first.
```
smearing_method fixed
init_chg                file
```
do ABACUS calculation with this setting next, it will start from good charge density and avoid the convergence problem.

**Comment by AroundPeking** [comment]
Thanks! The two-step method can avoid fractional occupation and get convergent results, in spite of slower calculation, i.e. GE45.

I am trying to optimize 2d orbital, using DZP+2d for orbital file. I don't know whether the SCF convergence can maintain when 2d orbital changes, using the same init_chg through the whole process.
