### ISSUE TITLE
The default value of scf_thr parameter may need improvement

### ISSUE THREAD

**Issue by mohanchen** [deepmodeling/abacus-develop#2190]
### Describe Current Status and Possible Solution

For LCAO calculations, the default setting of scf_thr is 1.0e-9, which is not reasonable, it typically causes too many iterations.

**Comment by caic99** [comment]
#484 Related issue?

**Comment by sunliang98** [comment]
> #484 Related issue?

Yes, maybe we can close https://github.com/deepmodeling/abacus-develop/issues/484, since parameter `dr2` has been replaced by `scf_thr`.

**Comment by mohanchen** [comment]
done
