### ISSUE TITLE
Requests for the bash script for submiting tasks on shuguang DCU platform.

### ISSUE THREAD

**Issue by floatingCatty** [deepmodeling/abacus-develop#2199]
### Details

Hello, I want to submit some jobs parallel across nodes on the Shuguang DCU platform, but I don't know where the root directory of the abacus is installed and what specific setting is required when writing the scripts. If there is any template of the abacus task on Shuguang, that will be a great help.

Thanks!

**Comment by flshbc** [comment]
Hi, @floatingCatty. 

### Restrictions 
For what I can tell currently:
- Sugon Platform does not support preinstallation and template job submission on cluster regions with DCU resource available.(for example, Kunshan & Wuzhen) 
- Hefei region offers template job submission of ABACUS, but it seems that only the CPU version of ABACUS is supported.
- DCU version of ABACUS will have a single-pass compilation with Singularity tool on Sugon Platform, which I haven't tested.

### Solution
- Here I have completed a user guide of compilation and job submission of ABACUS on Sugon DCU Platform written in Chinese, including specific setting of compilation & job submission.Process in this guide has been tested with ABACUS3.2.0 on Sugon cluster region Wuzhen. Refer to this guide and hopefully you will be able to compile and submit jobs on Sugon Platform.
- [ABACUS在曙光DCU集群上的编译与使用.pdf](https://github.com/deepmodeling/abacus-develop/files/11171617/ABACUS.DCU.pdf)


### Next Steps
- Hopefully this guide can be accessible on the website of Tutorial of ABACUS in Chinese days later. If so I will soon add the website here.
- Looking forward to the optimization of compilation of ABACUS with DCU, which will make it easier for us to utilize DCU platform.
