### ISSUE TITLE
about cell relaxation and out_stru

### ISSUE THREAD

**Issue by floatingCatty** [deepmodeling/abacus-develop#2200]
### Describe the bug

I find that when doing relaxation with cell-relax mode and open out_stru, the output STRU number does not match the number of optimization steps. This causes problems in the DPGEN autotest since it read the latest ION steps based on searching the log file's latest step. Also, the log of cell-relax seems has changed its form when recording the steps, the former note is "istep", but now is "STEP OF RELAXATION", I will raise this issue in DPGEN also to align both side.

### Expected behavior

Fix this bug, to produce the same amount of structure as optimization steps.

### To Reproduce

INPUT_PARAMETERS
suffix ABACUS
calculation cell-relax
ntype 2
symmetry 1
dft_functional pbe
ecutwfc 100
scf_thr 1e-8
scf_nmax 100
cal_force 1
cal_stress 1
basis_type lcao
smearing_method gauss
smearing_sigma 0.01
mixing_type pulay
mixing_beta 0.3
relax_new 1
fixed_axes c
out_stru 1
relax_nmax 1000
force_thr 1e-4
stress_thr 1e-3
relax_scale_force 0.2

### Environment

abacus 3.1.0

**Comment by floatingCatty** [comment]
Scripts of reading ion-step config is modified in DPGEN's devel branch.

**Comment by dyzheng** [comment]
@pxlxingliang @YuLiu98 can you help for this issue?
