### ISSUE TITLE
[NSPIN=4 ,gamma only can not run]

### ISSUE THREAD

**Issue by Shen-Zhen-Xiong** [deepmodeling/abacus-develop#2204]
### Details

I run a nspin=4 scf calculation with gamma_only = 1, there are no output after long time, I guess that abacus do not support. Maybe we need to output alarm information to tell user?
[4_nspin4.tar.gz](https://github.com/deepmodeling/abacus-develop/files/11170768/4_nspin4.tar.gz)

**Comment by wenfei-li** [comment]
indeed nspin = 4 is not supposed to be used along with gamma point; I'll update
