### ISSUE TITLE
Test: 604_NO_deepks_ut_H2O_multik does not work

### ISSUE THREAD

**Issue by Liu-RX** [deepmodeling/abacus-develop#2207]
### Describe the bug

The INPUT file in 604_NO_deepks_ut_H2O_multik test folder has only one line. It seems that the test is not complete.

**Comment by hongriTianqi** [comment]
@Liu-RX This test is not run by the abacus executable, but run by a special executable called test_deepks, which is complied under the directory of module_hamilt_lcao/module_deepks/test. It can be run successfully by using test_deepks.
