### ISSUE TITLE
Error when compialing most recent version of ABACUS

### ISSUE THREAD

**Issue by WeibinChu** [deepmodeling/abacus-develop#2209]
### Details

Dear the developer team, I am trying to build ABACUS with hybrid functional.

The compilation environment: cmake/3.22.0 mpi/oneAPI/2022.2 intel/oneAPI/2022.2 cereal-1.3.2 libxc 6.1 elpa-2021.05.002 LibRI LibComm 

Error:
~/src/ABACUS/abacus-develop_deepmodeling-develop/source/module_base/gather_math_lib_info.cpp(30): error: namespace "std" has no member "defaultfloat"
      GlobalV::ofs_info << std::defaultfloat << "zgemm " << *transa << " " << *transb << " " << *m << " " << *n << " "
                                ^

~/src/ABACUS/abacus-develop_deepmodeling-develop/source/module_base/gather_math_lib_info.cpp(73): error: namespace "std" has no member "defaultfloat"
      GlobalV::ofs_info << std::defaultfloat << "zhegvx " << *itype << " " << *jobz << " " << *range << " " << *uplo
                                ^

compilation aborted for /~/src/ABACUS/abacus-develop_deepmodeling-develop/source/module_base/gather_math_lib_info.cpp (code 2)

Both oneAPI 2021 and 2022 have this issue,

**Comment by maki49** [comment]
What's your version of gcc and g++ ? 
(Mine are all 11.3.0 now, with no such error)

**Comment by caic99** [comment]
Hi @WeibinChu ,
Please read the [docs](https://abacus.deepmodeling.com/en/latest/quick_start/easy_install.html#prerequisites) and check it your version of gcc satisfies the requirement.

**Comment by mohanchen** [comment]
The code has been rewritten. The issue does not exist now.
