### ISSUE TITLE
output "ETOT DIFF" in log when using cg algorithm to do structure relaxation.

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#2210]
### Background

When I use `relax_method=bfgs` to do structure relaxation, abacus would output `ETOT DIFF` after each ionic step, but when I use `relax_method=cg`, abacus won't output `ETOT DIFF`.

### Describe the solution you'd like

abacus should output the same information when doing structure relaxation.

**Comment by mohanchen** [comment]
BFGS output:
 GE10   -2.074756e+02  -6.786896e-08  2.217e-06  1.917e-01
 GE11   -2.074756e+02  -2.185081e-10  3.166e-06  1.853e-01
 GE12   -2.074756e+02  1.489026e-10   4.070e-09  1.674e-01
 ETOT DIFF (eV)       : 0.000e+00
 LARGEST GRAD (eV/A)  : 3.749e-01
 BFGS TRUST (Bohr)    : 5.000e-01

New cg output:
 GE10   -2.074756e+02  -6.786896e-08  2.217e-06  1.842e-01
 GE11   -2.074756e+02  -2.185081e-10  3.166e-06  1.864e-01
 GE12   -2.074756e+02  1.489026e-10   4.070e-09  1.701e-01
 LARGEST GRAD (eV/A)  : 3.749e-01

old cg output:
 GE10   -2.074756e+02  -6.786896e-08  2.217e-06  1.752e-01
 GE11   -2.074756e+02  -2.185081e-10  3.166e-06  1.812e-01
 GE12   -2.074756e+02  1.489026e-10   4.070e-09  1.698e-01
 ETOT DIFF (eV)       : 0.000e+00
 LARGEST GRAD (eV/A)  : 3.749e-01

**Comment by mohanchen** [comment]
Indeed, we need to fix this
