### ISSUE TITLE
Performance between OpenMP and MPI parallel calculation

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#2215]
### Details

[scf_TaAs-slab.zip](https://github.com/deepmodeling/abacus-develop/files/11185116/scf_TaAs-slab.zip)
In case of https://github.com/abacusmodeling/abacus-develop/issues/254 , I tested two methods for running ABACUS:
1. OMP_NUM_THREADS=1 mpirun -np 8 abacus > log1
2. OMP_NUM_THREADS=8 mpirun -np 1 abacus > log

The performance of method 2 is better than method 1.
<img width="434" alt="image" src="https://user-images.githubusercontent.com/49852742/230764928-9d9467be-9d23-437a-94d1-7a3b56f5ca51.png">

I recommand users using method 2 (OpenMP multi-threads calculation) for cases which has many k-points.

**Comment by Satinelamp** [comment]
can't reproduce the result. 
I tried the two methods; each electronic step's time is about the same.
![image](https://user-images.githubusercontent.com/62006565/230793010-ea29be26-213b-4719-b900-349ae1b0d1b9.png)

**Comment by dyzheng** [comment]
@Satinelamp Hello, how many threads or processes did you use? 
Can you compare the value of key "cal_dk_k" and "elpa_solve" for these two methods?

**Comment by Satinelamp** [comment]
I use 8 cores.
Here is `cal_dk_k` and `elpa_solver`. But abacus didn't get convergence in both cases:
![image](https://user-images.githubusercontent.com/62006565/230840877-699799d3-eb01-4103-931b-dffb7c4ce67b.png)

Here is the log file:
[log.zip](https://github.com/deepmodeling/abacus-develop/files/11188226/log.zip)

**Comment by dyzheng** [comment]
@Satinelamp It looks your ELPA with openmp version shows much poorer performance than MPI version.
In my test, time of elpa_solve with openmp is slightly slower than MPI version.
I suggest you use MPI version for this case and keep the longest direction along z-axis.

**Comment by Satinelamp** [comment]
I am actually using the input files you provided, does this mean my installation is incorrect?

**Comment by dyzheng** [comment]
@Alcanderian Hello, do you know the expectation of performance difference of ELPA MPI and OMP parallel computing?

**Comment by Alcanderian** [comment]
> @Alcanderian Hello, do you know the expectation of performance difference of ELPA MPI and OMP parallel computing?

The performance of MPI and OMP seem to correlate with the atomic number and atomic type combineation. In general, the more atoms there are, the closer the performance will be.

Here are some references performance (cost time in second)  of `elpa_slove`:
|  Case |  OpenMP 16 Core  |  MPI 16 Core   |
| :------------ | :------------ | :------------ | 
| I3Pb1C1N2H5   |  22  | 34.9  |
| I12Pb4C4N8H2O    |   53   |   83   |
|  Li88Ge20   |   264   |   304   |
|   C60H80O60  |   17   |   19   |
|  As4Ca4Mg2   |    65  |    102  |
|  Ti15   |   145   |   326   |
|  Li128C75H100O75     |     421   |     438    |
|   Au1Mg63   |    250 |    371    |


In this case I have a brief test and found I may reproduce the result

MPI
```
ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)
 GE1    -1.941219e+05  0.000000e+00   4.014e-02  6.705e+01
 GE2    -1.941183e+05  3.570431e+00   3.940e-02  6.459e+01
 GE3    -1.940965e+05  2.184725e+01   3.943e-02  6.464e+01
```
OpenMP
```
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)
 GE1    -1.941219e+05  0.000000e+00   4.014e-02  4.450e+01
 GE2    -1.941183e+05  3.570431e+00   3.940e-02  4.228e+01
 GE3    -1.940965e+05  2.184725e+01   3.943e-02  4.238e+01
```

So it seems that we should take a look at the hardware and software environment

@Satinelamp Are you using AMD CPU?

**Comment by Satinelamp** [comment]
@Alcanderian , I am using Intel CPU.:


Here is the CPU info
@mu01 ~]$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    1
Core(s) per socket:    16
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 106
Model name:            Intel(R) Xeon(R) Silver 4314 CPU @ 2.40GHz
Stepping:              6
CPU MHz:               3400.000
CPU max MHz:           3400.0000
CPU min MHz:           800.0000
BogoMIPS:              4800.00
Virtualization:        VT-x
L1d cache:             48K
L1i cache:             32K
L2 cache:              1280K
L3 cache:              24576K
NUMA node0 CPU(s):     0-15
NUMA node1 CPU(s):     16-31
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 intel_pt mba tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local ibpb ibrs stibp dtherm ida arat pln pts avx512vbmi pku ospke avx512_vpopcntdq spec_ctrl intel_stibp arch_capabilities

**Comment by Alcanderian** [comment]
@Satinelamp My CPU is https://www.intel.com/content/www/us/en/products/sku/198017/intel-core-i910980xe-extreme-edition-processor-24-75m-cache-3-00-ghz/specifications.html

That might have nothing to do with the hardware platform

**Comment by QuantumMisaka** [comment]
@dyzheng Hello!
Did you try using OMP_NUM_THREADS=4 in all tasks?
In my test, OMP_NUM_THREADS=4 to get a MPI-OMP mixed calculation always has the best performance
regardless of Intel-8358 or AMD-7b12
