### ISSUE TITLE
Run symmetry "ERROR: PRICELL: NCELL != NTRANS"

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#2219]
### Describe the bug

I use intel docker image "registry.dp.tech/deepmodeling/abacus-intel:latest" to run the below example, and get the error:
`ERROR: PRICELL: NCELL != NTRANS !`

[000.zip](https://github.com/deepmodeling/abacus-develop/files/11189006/000.zip)

### Environment

docker image : registry.dp.tech/deepmodeling/abacus-intel:latest

**Comment by maki49** [comment]
I think it may be the image's fault. 
I simply add an output here (between line 1048 and 1049): 
`if (i == 2) std::cout << "rotpos[ia * 3 + 1]=" << rotpos[ia * 3 + 1] << std::endl;`
, then the bug disappeared.
https://github.com/deepmodeling/abacus-develop/blob/12e6ab012c096438f94c117a07851565de1ce586/source/module_cell/module_symmetry/symmetry.cpp#L1048-L1049

**Comment by Satinelamp** [comment]
I use the latest `develop` version on my laptop, your input file works fine.

**Comment by dyzheng** [comment]
In my test, auto optimization of compiler will lead to different behaviors, that 
1. -O3 and -O2 lead to error.
2. -O1 and -O0 lead to correct results.
