### ISSUE TITLE
memory issue when running tddft with large system

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#2222]
### Describe the bug

I try to run tddft with a cluster system (about 600 atoms), there is an error about `Segmentation fault` in the second ionic step.

![image](https://user-images.githubusercontent.com/62006565/230964806-0bf8599e-a502-440c-84e9-f3ec3c363e74.png)

I have checked the memory during the simulation, it seems there is enough memory unused.

![image](https://user-images.githubusercontent.com/62006565/230965403-35d5254c-9643-4abe-9d99-57417a66ce46.png)
![image](https://user-images.githubusercontent.com/62006565/230965493-2368628f-c6f6-42ac-89bf-af202f744977.png)

Here are the input and log files.
[input-files.zip](https://github.com/deepmodeling/abacus-develop/files/11192738/input-files.zip)

**Comment by Satinelamp** [comment]
This problem might be the same as https://github.com/deepmodeling/abacus-develop/issues/2232, and is caused by lack of memory. I will try to test this case in other hardware.

**Comment by lyb9812** [comment]
There is no memory leak in this case after testing. It is probably out of memory because the system is too large for md. We will optimize the code of md later to support such case.
