### ISSUE TITLE
Convergence problem when calculating energy of armchair edge of 2D-SiO2

### ISSUE THREAD

**Issue by Skyinner** [deepmodeling/abacus-develop#2230]
### Details

I am trying to calculate the edge energy of armchair edge of 96-atoms 2D-SiO2 with LACO basis. I have tried many combination of "mixing_beta" (0.01, 0.05, 0.1), "mixing_ndim" (8, 10) and "mixing_gg0" (0, 1.5), however, the convergence can not happened  even with 600 scf steps.
I want to know that whether some structures can not ben calculated by the LACO basis?

<img width="250" alt="截屏2023-04-11 18 55 47" src="https://user-images.githubusercontent.com/50408763/231140384-52bb0ee6-414f-4faf-87fc-5b44c18f1822.png">

[INPUT.txt](https://github.com/deepmodeling/abacus-develop/files/11199586/INPUT.txt)
[KPT.txt](https://github.com/deepmodeling/abacus-develop/files/11199588/KPT.txt)
[STRU.txt](https://github.com/deepmodeling/abacus-develop/files/11199589/STRU.txt)
[o-job_0.2865394.log](https://github.com/deepmodeling/abacus-develop/files/11199592/o-job_0.2865394.log)
[o-job_0.2905878.log](https://github.com/deepmodeling/abacus-develop/files/11199593/o-job_0.2905878.log)
[o-job_0.2906794.log](https://github.com/deepmodeling/abacus-develop/files/11199594/o-job_0.2906794.log)

**Comment by Satinelamp** [comment]
you could try to use gaussian smearing method by setting `smearing_method`
https://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#smearing-method

in my experience, if you don't set smearing method for semiconductor, the convergence might be hard.

**Comment by Skyinner** [comment]
> 

I have set the smearing method like below:
```
smearing_method fd
smearing_sigma_temp 600
```

Does gaussian smearing method and fd smearing method has such large difference?
By the way, I have calculated the perfect lattice of 2D-SiO2, the convergence problem does not exist.

**Comment by Skyinner** [comment]
> you could try to use gaussian smearing method by setting `smearing_method` https://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#smearing-method
> 
> in my experience, if you don't set smearing method for semiconductor, the convergence might be hard.

I have set the smearing method like below:

```
smearing_method fd
smearing_sigma_temp 600
```

Do Gaussian smearing method and FD smearing method have such a large difference?
By the way, I have calculated the perfect lattice of 2D-SiO2, the convergence problem does not exist.

**Comment by Satinelamp** [comment]
·fd· and `gaussian` shouldn't make a big difference, there is another possibility that your structure is not reasonable, you should try to relax your structure first.

**Comment by Satinelamp** [comment]
did you solve the problem?
