### ISSUE TITLE
nspin=2 cause abaucs crash 

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#2232]
### Describe the bug

I build a model which contains only one Fe atom in a box. 
Here is `INPUT`
```
INPUT_PARAMETERS
suffix 			Au30
ntype 			1
pseudo_dir 		.
orbital_dir 		.
ecutwfc 		100 
scf_thr 		1e-5 
basis_type 		lcao
calculation 		scf
nspin			2 # this parameter cause abacus crash

gamma_only		1
scf_nmax		100

#mixing
mixing_type            pulay
mixing_beta            0.3

#smearing
smearing_method        gaussian
smearing_sigma         0.005
```

If I use `nspin=2`, abacus would crash.
```
START CHARGE      : atomic
 DONE(20.8599    SEC) : INIT SCF
 ITER   TMAG      AMAG      ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 22001 RUNNING AT mu01
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================
```

### To Reproduce

I am using the latest develop version
Here is the input and log files.
[Fe single atom.zip](https://github.com/deepmodeling/abacus-develop/files/11214114/Fe.single.atom.zip)

This problem might be related with https://github.com/deepmodeling/abacus-develop/issues/2184

**Comment by Satinelamp** [comment]
I find that if I decrease the lattice length, there won't be any errors.

**Comment by jinxin68** [comment]
![image](https://user-images.githubusercontent.com/102202772/231682426-c7986642-3609-46f2-bdcf-2ea9d9e07748.png)
![image](https://user-images.githubusercontent.com/102202772/231682743-47d452a8-4799-40d5-aa21-8b71379f7eef.png)

I repeated your calculation with 1 CPU, and it requires approximately 100GB of memory. Please ensure that your memory is sufficient. @Satinelamp

**Comment by wenfei-li** [comment]
it's due to memory shortage, not a bug
