### ISSUE TITLE
Perf degradation after #2070

### ISSUE THREAD

**Issue by caic99** [deepmodeling/abacus-develop#2237]
### Describe the bug

We observed that the performance on PW test set was influenced after accepting #2070. 
![img_v2_426e05a7-f17f-4df5-bad8-d73cb27980eg](https://user-images.githubusercontent.com/78061359/231381473-82c137e9-0886-46d5-9fb9-0ffc4b9fb0da.jpg)

@Alcanderian Would you investigating on this issue?

**Comment by Alcanderian** [comment]
Currently I have no idea, the performance of the PW basis has been improved in my local test.
We need some logs and test cases to observe and reproduce it.

**Comment by caic99** [comment]
@Alcanderian These are the test cases we used.
[abacus.zip](https://github.com/deepmodeling/abacus-develop/files/11212107/abacus.zip)

**Comment by Alcanderian** [comment]
> @Alcanderian These are the test cases we used. [abacus.zip](https://github.com/deepmodeling/abacus-develop/files/11212107/abacus.zip)

Testing all these case may take such a long time. Would you give me the log before and after #2070 in your testing system?

**Comment by caic99** [comment]
> Testing all these case may take such a long time. Would you give me the log before and after #2070 in your testing system?

@pxlxingliang Would you take a look, thanks!

**Comment by pxlxingliang** [comment]
At 4-4, the testing was runed by 3 times at 01:15, 11:53 and 13:42, the results are:
```
Some key results of 01:15, 11:53, 13:42
--------------------------------------------------------------------
example            jobType ScfSteps totalTime(s) converge normal_end 
----               ----        ----         ----     ----       ---- 
000_4GaAs          01:15          8        24.40     True       True 
                   11:53          8        22.80     True       True 
                   13:42          8        26.98     True       True 
----               ----        ----         ----     ----       ---- 
001_C2H6O          01:15         10        39.49     True       True 
                   11:53         10        42.73     True       True 
                   13:42         10        43.44     True       True 
----               ----        ----         ----     ----       ---- 
002_4MoS2          01:15         14        72.05     True       True 
                   11:53         14        67.40     True       True 
                   13:42         14        74.07     True       True 
----               ----        ----         ----     ----       ---- 
003_12Pt111        01:15         15       106.95     True       True 
                   11:53         15       111.99     True       True 
                   13:42         15       124.63     True       True 
----               ----        ----         ----     ----       ---- 
004_3BaTiO3        01:15         11       185.54     True       True 
                   11:53         11       173.31     True       True 
                   13:42         11       213.35     True       True 
----               ----        ----         ----     ----       ---- 
005_16Na           01:15          8       449.07     True       True 
                   11:53          8       461.75     True       True 
                   13:42          8       517.70     True       True 
----               ----        ----         ----     ----       ---- 
006_27Fe           01:15         15      1706.00     True       True 
                   11:53         15      1525.00     True       True 
                   13:42         18      2055.60     True       True 
----               ----        ----         ----     ----       ---- 
007_32H2O          01:15         10        47.82     True       True 
                   11:53         10        50.75     True       True 
                   13:42         10        47.78     True       True 
----               ----        ----         ----     ----       ---- 
008_Li27Ni9O54Mn9C 01:15         26      1285.70     True       True 
                   11:53         26      1425.30     True       True 
                   13:42         26      1441.00     True       True 
----               ----        ----         ----     ----       ---- 
009_216Si          01:15         13      4213.10     True       True 
                   11:53         13      4149.50     True       True 
                   13:42         13      4058.50     True       True 
--------------------------------------------------------------------
```
For 006_27Fe, the last run at 13:42 has a larger ScfSteps of 18, and the previous run is 15. 

The detail SCF, compared to the run at 11:53 is:
![image](https://user-images.githubusercontent.com/91927439/233965230-3973a630-b311-4059-b83f-109468656762.png)
As we can see the diagonization are different at the first SCF step.

It seems that the difference only occurred in the nspin=2 calculation, and not found in the other nspin=1 calculations. 

The SCF of 000_4GaAs is:
![image](https://user-images.githubusercontent.com/91927439/233966286-dfaca9a3-5e7a-4045-bf3e-eea78bbab432.png)

@Alcanderian @dyzheng

**Comment by pxlxingliang** [comment]
The results of the last two runs:
[pw.zip](https://github.com/deepmodeling/abacus-develop/files/11309216/pw.zip)

**Comment by haozhihan** [comment]
This issue will be tracked in #2351.
