### ISSUE TITLE
Generation of atomic orbitals and corresponding accuracy-check workflow

### ISSUE THREAD

**Issue by ouqi0711** [deepmodeling/abacus-develop#2243]
### Background

Dr. Shi Liu (Westlake Univ.) plans to train a universal deep potential for a series of perovskite systems (attached) based on DPA. ABACUS is applied as the ab initio data generator (w/ PBEsol functional and LCAO basis set). The first thing we need to make sure is that ABACUS has the corresponding atomic orbitals for all elements involved in their systems.  If the orbital for any required element is missing (such as Ba), we should generate it and publish it after a reliable accuracy-check.  
![20230413140331](https://user-images.githubusercontent.com/15252021/231691011-dc1fc014-238b-420a-8e46-209d099bdcd2.png)

### Describe the solution you'd like

A standard method for the atomic orbital generation is desired, with a standard workflow to check its accuracy.

**Comment by mohanchen** [comment]
I will look into this issue.

**Comment by Satinelamp** [comment]
I am planning to calculate the properties of CeO2 using ABACUS, but there are no corresponding pseudopotential and orbital files.  Is there any chance that you take Ce into consideration? Or maybe share a workflow about how to generate orbital files.

**Comment by dyzheng** [comment]
Numerical Orbitals of Dojo are already generated in https://github.com/abacusmodeling/ABACUS-orbitals/tree/main/Dojo-NC-FR , @Satinelamp you can try this.

**Comment by Satinelamp** [comment]
@dyzheng , I just realized that the `Ce.upf` I found is a `PAW` type of pseudopotential, not a `norm-conserving` type.  It seems generating a `norm-conserving` type of pseudopotential for f-block elements is not trivial, I found D. R. Hamann is developing [Multi-projector ONCVPSP-4.0.1 (beta release)](http://www.mat-simresearch.com), maybe the key issue for rare earth elements is about how to generate reliable pseudopotential.

**Comment by hongriTianqi** [comment]
- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by kirk0830** [comment]
#3419 will solve the other part of this issue, close this issue temporarily.
