### ISSUE TITLE
Parameter md _ type does not apply to strings ?

### ISSUE THREAD

**Issue by scott-5** [deepmodeling/abacus-develop#2245]
### Details

When md_type in INPUT setting to nve or nvt etc., abacus reports errors like that:

```
 Fri Apr 14 11:09:10 2023
 word = md_type
 Fail to read parameters. 
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 Error during readin parameters.
 CHECK IN FILE : warning.log
```
I thought it was my personal problem, but tried the official [example](https://github.com/deepmodeling/abacus-develop/tree/develop/examples/md) and reported the same error.

Of course, if md_type  0 ( nve ensemble ) is used, abacus can be run, but the [document](https://abacus.deepmodeling.com/en/latest/advanced/md.html) does not specify the number corresponding to each ensemble.

**Comment by YuLiu98** [comment]
Hi, please make sure you have compiled the newest code of the develop branch.

**Comment by scott-5** [comment]
> Hi, please make sure you have compiled the newest code of the develop branch.

The version I installed is 3.1.4 by conda. I also try the 3.2.0 version. And it doesn't work as well.

[lcao_gammaonly_Sn64.tar.gz](https://github.com/deepmodeling/abacus-develop/files/11252557/lcao_gammaonly_Sn64.tar.gz)

**Comment by YuLiu98** [comment]
> > Hi, please make sure you have compiled the newest code of the develop branch.
> 
> The version I installed is 3.1.4 by conda. I also try the 3.2.0 version. And it doesn't work as well.
> 
> [lcao_gammaonly_Sn64.tar.gz](https://github.com/deepmodeling/abacus-develop/files/11252557/lcao_gammaonly_Sn64.tar.gz)

The feature is enabled in the 3.2.1 version.

**Comment by scott-5** [comment]
Oh, so it's been updated, thanks! The problem has been solved.
