### ISSUE TITLE
tddft error when simulating one atom in a box

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#2246]
### Describe the bug

I am using Abacus to run tddft simulation, the case is that one Au atom in a box, but abacus crash before starting electronic iteration.
```
INPUT_PARAMETERS
suffix 			Au30
ntype 			1
pseudo_dir 		.
orbital_dir 	.
ecutwfc 		100 
scf_thr 		1e-5 
basis_type 		lcao
calculation 		md
esolver_type		tddft
#gamma_only		1

#mixing
mixing_type            pulay
mixing_beta            0.3
chg_extrap             second-order

#smearing
smearing_method        gaussian
smearing_sigma         0.005


#md
md_type                0
md_nstep               5000
md_dt                  0.01
init_vel		1
```

![image](https://user-images.githubusercontent.com/62006565/232229943-99f1c5cd-6f22-431e-8742-ea05f65bbb0f.png)
starting

### To Reproduce

Here is the input and log files.
[input and log.zip](https://github.com/deepmodeling/abacus-develop/files/11239711/input.and.log.zip)

**Comment by lyb9812** [comment]
md_type is updated in #2206  . You should change 0 to nve.
