### ISSUE TITLE
Relax calculation only perform 1 SCF-cycle and done ?

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#2254]
### Details

When I use ABACUS to calculate surface system, I observed that relax calculation only calculated 1 SCF-cycle and then done, the force is explicitly not converged but the calculation is done.
I'm not sure is a bug or my input file have some problem

The input and output files are appended as follow.
[Pt-CO-OH_ab.tar.gz](https://github.com/deepmodeling/abacus-develop/files/11251138/Pt-CO-OH_ab.tar.gz)

**Comment by Satinelamp** [comment]
It is because you keep all atoms fixed:
0 represents that you fix all atoms, change 0 to 1.
![image](https://user-images.githubusercontent.com/62006565/232750656-5f7af54a-aee4-4e7a-a5a8-0daf6712b1b2.png)
