### ISSUE TITLE
automatically replace the STRU file when continue a MD simulation

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#2264]
### Background

if I run a MD simulation for 10 steps, and stop the jobs, but later I want to continue the MD simulation for another 10 steps. Except add `md_restart=true` in the `INPUT` file, I also need to replace `STRU` file with the `STRU_MD_10` in the OUTPUT directory.

### Describe the solution you'd like

Let abacus update the STRU file automatically in the continued MD job.

**Comment by YuLiu98** [comment]
Hi, this feature is implemented in this PR: https://github.com/deepmodeling/abacus-develop/pull/2236
