### ISSUE TITLE
Installation of ABACUS

### ISSUE THREAD

**Issue by AroundPeking** [deepmodeling/abacus-develop#2268]
### Details

When I did "cmake --build build", it showed
![S()WHM{FSA@4MOJ{ )2D$G](https://user-images.githubusercontent.com/108850865/232981861-98858b2e-d886-4c17-b28f-026a5bd73ab2.png)
Before adding libxc 6.0, I never face this issue.
Here is my CMakeList.txt :
[CMakeLists.txt](https://github.com/deepmodeling/abacus-develop/files/11269281/CMakeLists.txt)

**Comment by caic99** [comment]
Hi @AroundPeking , 
Please try using the latest source code.

**Comment by AroundPeking** [comment]
I clone the latest ABACUS code. This issue still remains.
![Q)91E9RAVYKTPZ6~~X$9(9](https://user-images.githubusercontent.com/108850865/232993893-703eddb1-d50d-4cb3-8f92-e453712f2aa9.png)

Here is info when "cmake -B build":
![NQ`KFTXBF3L$BR$2P6~B~X7](https://user-images.githubusercontent.com/108850865/232993425-73e3ea17-fe74-4191-9b90-cb08a56f12cd.png)

![{%$IVU8LC14)XQ`95O AXJT](https://user-images.githubusercontent.com/108850865/232993450-be11eca1-f461-40fc-9f4a-c13bb6b0a58d.png)

**Comment by caic99** [comment]
@AroundPeking Would you try remove `build` folder and restart from scratch? Thanks.

**Comment by AroundPeking** [comment]
Yeah, I have removed "build" folder. In fact, I clone the latest repo and cmake again.

**Comment by AroundPeking** [comment]
It seems "cannot find libio"? Which software includes libio?

**Comment by caic99** [comment]
@AroundPeking Please provide your commands for configuring.
