### ISSUE TITLE
Error in UnitTest

### ISSUE THREAD

**Issue by PeizeLin** [deepmodeling/abacus-develop#2306]
### Describe the bug

# g++

When compiled with
```shell
cmake -B build \
-DCMAKE_INSTALL_PREFIX=./bin \
-DCMAKE_CXX_COMPILER=g++ \
-DMPI_CXX_COMPILER=mpicxx \
-DELPA_DIR=/share/home/linpz/software/elpa/elpa-2021.11.002_OpenMP \
-DCEREAL_INCLUDE_DIR=/share/home/linpz/software/cereal/cereal-1.3.2 \
-DLibxc_DIR=/share/home/linpz/software/libxc/libxc-6.0.0-cmake \
-DBUILD_TESTING=1 \
-DGTest_DIR=/share/home/linpz/software/gtest/googletest
```
Compilation errors are
[make_err.txt](https://github.com/deepmodeling/abacus-develop/files/11302915/make_err.txt)

# icpc
When compiled with
```shell
cmake -B build \
-DCMAKE_INSTALL_PREFIX=./bin \
-DCMAKE_CXX_COMPILER=icpc \
-DMPI_CXX_COMPILER=mpiicpc \
-DELPA_DIR=/share/home/linpz/software/elpa/elpa-2021.11.002_OpenMP \
-DCEREAL_INCLUDE_DIR=/share/home/linpz/software/cereal/cereal-1.3.2 \
-DLibxc_DIR=/share/home/linpz/software/libxc/libxc-6.0.0-cmake \
-DBUILD_TESTING=1 \
-DGTest_DIR=/share/home/linpz/software/gtest/googletest
```
Compilation is successful. And unittests failed
[ctest_log.txt](https://github.com/deepmodeling/abacus-develop/files/11302916/ctest_log.txt)

### Environment

Linux 3.10.0-1160.el7.x86_64, Red Hat 4.8.5-44
gcc 10.2.0 / icpc 2021.5.0
intelmpi 2021.5
mkl 2021.5
elpa_openmp 2021.11.002
cereal 1.3.2
libxc 6.0.0

**Comment by baixiaokuang** [comment]
You should run ``cmake --install build`` before running UT tests.

**Comment by hongriTianqi** [comment]
Hi @PeizeLin, do you still meet unit test errors? Please let me know. Thanks.

**Comment by hongriTianqi** [comment]
Hi @PeizeLin, this issue will be closed since we haven't received updates from you since May15. If this issue persists, please feel free to reopen this issue again and let us know. Thank you!

**Comment by hongriTianqi** [comment]
Hi @PeizeLin , for your information, I have submitted a new PR #2836 to show how to compile and run unit tests.
