### ISSUE TITLE
Unittest is not OK, but passed, should we add notice info?

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#2317]
### Describe Current Status and Possible Solution

The following test is actually not passed, but reviewers cannot see the info.

<img width="733" alt="截屏2023-04-24 17 25 26" src="https://user-images.githubusercontent.com/18049272/233956456-cd1b8f39-537f-4d1b-abc5-c9ed0ed2e3f7.png">

**Comment by caic99** [comment]
@hongriTianqi The test codes should capture the status of calculation, and use assertions to throw an error.
