### ISSUE TITLE
structural optimization not convergence

### ISSUE THREAD

**Issue by gravityanhui** [deepmodeling/abacus-develop#2323]
### Describe the bug

when I use abacus to do structural optimization, it has difficulties in convergence
![image](https://user-images.githubusercontent.com/131337027/234171818-0245e228-8f97-41fb-b633-1827322c4208.png)
[suanli.tar.gz](https://github.com/deepmodeling/abacus-develop/files/11316336/suanli.tar.gz)

**Comment by mohanchen** [comment]
if you chose LCAO basis, the 'scf_thr' convergence threshold may be too tight, we suggest you change 'scf_thr' to 1.0e-7, which may be sufficiently accurate.

**Comment by mohanchen** [comment]
we recently change the default value of 'scf_thr' to 1.0e-7

**Comment by LiuXiaohui123321** [comment]
When the scf iteration and relax iteration are difficult or not convergent, please try to adjust the input parameters. For your calculation, please adjust the input parameters according to the following way, which has been tested to be effective.

For scf  iteration:
1. Rcut of orbital basis: 6au --> 8au, for example, C_gga_6au_100Ry_2s2p1d.orb --> C_gga_8au_100Ry_2s2p1d.orb, the same as Al and Cl elements
2. smearing_sigma: 0.001 --> 0.01
3. no use of mixing_gg0
4. use of gamma only

Every ionic step just needs about 20 scf iterations to converge
![scf-step](https://github.com/deepmodeling/abacus-develop/assets/25027983/9430b13c-6a7f-4bbd-a313-18a834d365b9)

For relax iteration:
1. relax_method: cg --> cg_bfgs
2. relax_cg_thr: 0.2

The whole relax calculation just needs 64 ionic iterations to converge
![relax-step](https://github.com/deepmodeling/abacus-develop/assets/25027983/a2358986-1d04-4283-a487-5b72acf65957)
