### ISSUE TITLE
When the parameter s is set incorrectly, the user should be alerted that the setting is incorrect

### ISSUE THREAD

**Issue by lauthirteen** [deepmodeling/abacus-develop#2339]
### Describe Current Status and Possible Solution

For the md_type parameter of AIMD,  if I set it to the old version of "2", the following error will be reported. It is not friendly for users to troubleshoot the problem. I suggest output a message in the log file: the md_type parameter is incorrect. 
Error info:
"
 Use Systematically Improvable Atomic bases
 ---------------------------------------------------------
 ELEMENT ORBITALS        NBASE       NATOM       XC          
 Si      3s3p2d-9au      22          32          
 C       3s3p2d-9au      22          32          
 ---------------------------------------------------------
 Initial plane wave basis and FFT box
 ---------------------------------------------------------

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 249 RUNNING AT dp-lbg-1175-6861170
=   KILLED BY SIGNAL: 11 (Segmentation fault)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 1 PID 250 RUNNING AT dp-lbg-1175-6861170
=   KILLED BY SIGNAL: 11 (Segmentation fault)
===================================================================================
"

**Comment by YuLiu98** [comment]
This issue is caused by the compilation of ABACUS with HONG **__NORMAL**, which results in the absence of warning information. So, recompiling ABACUS without **__NORMAL** would solve the problem.
