### ISSUE TITLE
Installation of abacus

### ISSUE THREAD

**Issue by Oceanusity** [deepmodeling/abacus-develop#2363]
### Details

I run cmake command successfully. But when I make the file, I face this problem:
```bash
/abacus-develop/source/module_io/input.h:4:10: fatal error: module_base/vector3.h: No such file or directory
    4 | #include "module_base/vector3.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~
```

Does anyone know how to deal with this situation? Thanks.

**Comment by caic99** [comment]
Hi @Oceanusity ,
Would you provide your full commands and logs for configuration and making.

**Comment by mohanchen** [comment]
No answer, we will reopen if we receive further response.
