### ISSUE TITLE
Some output parameters in the document do not describe the units in the output file

### ISSUE THREAD

**Issue by xuan112358** [deepmodeling/abacus-develop#2422]
### Background

Some output parameters in the document do not describe the units in the output file. Specifically they are:
out_mul
out_chg
out_pot
out_dm
out_band
out_proj_band
out_bandgap
out_mat_hs
out_mat_r
out_mat_hs2
out_mat_t
out_mat_dh
out_element_info
resart_save
dft_plus_dmft（not working any more）
rpa（no descriptions for content of output files）.

### Describe the solution you'd like

Add descriptions about units for these parameters.

**Comment by hongriTianqi** [comment]
- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by jinzx10** [comment]
PR #3020 adds description about the unit to the following entries in doc:
out_chg
out_pot
out_band
out_mat_hs
out_mat_r
out_mat_hs2
out_mat_t
out_mat_dh
out_element_info

For the following keywords, I think the description about unit is either unnecessary or not applicable:
out_mul (population is dimensionless)
out_dm (dimensionless)
out_proj_band (unit is mentiond in the output file)
out_bandgap (values are given in both eV & Ry in the output file)
restart_save (I think the content of the output file is not supposed to be used by the user)

As to dft_plus_dmft & rpa, unfortunately I'm not able to find the relevant information. Maybe we should seek help from the origional developers of those modules or skip this part for now. @hongriTianqi

**Comment by jinzx10** [comment]
Hi @xuan112358 we just update the doc with the above change. Does that solve your issue (so that we might close it)?

**Comment by xuan112358** [comment]
@jinzx10 Thanks！I think the change can solve my issue.
