### ISSUE TITLE
We need the version with binding commit or date

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#2430]
### Background

At present, ABACUS is in the stage of rapid development, and many calculations and tests are carried out using the code of the develop branch. When we get a result, it is difficult to determine the actual codes it runs. 

It is best to output a version number during the calculation, which is bound to the github's commit.

### Describe the solution you'd like

One approach is to add a version file that stores the ABACUS version number and the latest commit number. After each PR is received, github automatically changes the commit number in the version file to the latest and pushes the PR. But this approach will double the number of PR. 

Alternatively, we can bind the date instead of commit. After the first PR is received every day, github can modify the date information in the version file, and push to develop repository.

**Comment by caic99** [comment]
Duplicate #1815
