### ISSUE TITLE
When using LCAO for get_S calculation, the process cannot end normally.

### ISSUE THREAD

**Issue by sgyang345** [deepmodeling/abacus-develop#2439]
### Describe the bug

- abnormal interruption of the program
- run ABACUS with 3.0.0  or 3.2.2
- 2D structure with Lattice constant 173 Å
- number of atoms: 16746

### Expected behavior

- I used top or htop to monitor the memory usage in real time during the running process, and the memory did not overflow.

### To Reproduce

- configure CMake
CXX=mpiicpc cmake -B build -DCMAKE_INSTALL_PREFIX=. -DELPA_DIR=/opt/software/ABACUS/libraries/elpa-2021.05.002 -DCEREAL_INCLUDE_DIR=/opt/software/ABACUS/libraries/cereal-1.3.0 -DFFTW3_DIR=/opt/software/ABACUS/libraries/fftw-3.3.9

### Environment

- CentOS Linux release 7.9.2009 (Core)
- System configuration
Total Mem: 1.0T
Total Swap: 599G 

### Additional Context

[get_S_overlap_abacus3.2.2.zip](https://github.com/deepmodeling/abacus-develop/files/11450682/get_S_overlap_abacus3.2.2.zip)

**Comment by wenfei-li** [comment]
where did you get the orbital files? can you send them to me
I only found W_gga_10au_100Ry_4s2p2d2f1g.orb from the official website, not W_gga_10au_100Ry_4s2p2d2f.orb which you used

**Comment by sgyang345** [comment]
Thank you for your reply. 
The orbital files I used comes from the official, the link is given in my README file, and I uploaded the orbital files I used.

[upf_orb.zip](https://github.com/deepmodeling/abacus-develop/files/11591670/upf_orb.zip)

**Comment by wenfei-li** [comment]
I tried it and it seems to be memory issue. I ran with 8 MPI processes on machines with memories 32G, 64G and 128G, respectively. The jobs failed on the former two machines due to memory limit, but succeded on the 128G machine.
The result is about 6GB so I cannot attach it here. I can send you through email in case you want to have the S matrix.
One more thing: I used an older version of the code (commit 44c694878811954658455c09d55ebee9fc2f342e). Not sure if this is relevant. If you only want to use get_S then I suppose there is no need to use the latest version of ABACUS, and you may stick to an older version. There has been many updates recently and some of them may be causing problems.

**Comment by sgyang345** [comment]
Thank you very much for your help!
I do need this S matrix ( email: 1152368130@qq.com ).

But it doesn 't seem to solve my problem, I want to run this example successfully on my machine. 
As I described at the beginning, I have tried to use the code with version of **2.3.5, 3.0.0, 3.2.2, 3.2.3**, and the memory of my machine is **1TB**, but failed. 

I can 't find the code version you said, could you please send the code to me? And what details do I need to pay attention to when compiling ? 

I usually use cmake to compile with the following parameters :
**"CXX=mpiicpc cmake -B build -DCMAKE_INSTALL_PREFIX=.  -DELPA_DIR=/opt/software/ABACUS/libraries/elpa-2021.05.002   -DCEREAL_INCLUDE_DIR=/opt/software/ABACUS/libraries/cereal-1.3.0   -DFFTW3_DIR=/opt/software/ABACUS/libraries/fftw-3.3.9"**

**Comment by wenfei-li** [comment]
The way for accessing that version is to clone a recent copy of ABACUS repository, and use
`git checkout 44c694878811954658455c09d55ebee9fc2f342e`
then compile normally

I'm not sure what's happening on your machine and I cannot solve environment problems. You may try using a docker image.

**Comment by wenfei-li** [comment]
Btw the file is too large (6G). I cannot find a email server that allows such file size ... Do you know if there's any file server that may be useful?

**Comment by sgyang345** [comment]
Thank you very much!

The file is too large for transfer, so you don't need to send it to me anymore, thanks again. 
(I‘ve got the above example S matrix, the size is about **22G**, which seems to be quite different from your file size, I don't know why.) 

Also, I used the specific version of ABACUS (44c6948) you mentioned and found that the calculation still reported an error as before.

But when I use version 3.0.0 with **fewer threads (24)**, the calculation process ends normally without an error.
I guess that maybe the system becomes very large (more than **10,000 atoms**), the number of threads becomes extremely important, so I am still testing larger systems.

**Comment by wenfei-li** [comment]
good to know. I'll then mark this issue as solved
