### ISSUE TITLE
Desire for DOJO LCAO orbit files

### ISSUE THREAD

**Issue by iduygnay** [deepmodeling/abacus-develop#2449]
### Background

Some calculations SG15 cannot support, although I know how to create the orbit files for DOJO PSP I'm not sure how to check the accuracy of orbit files. 

### Describe the solution you'd like

Hope to have a set of orbit files for DOJO PSP.

**Comment by dyzheng** [comment]
https://github.com/abacusmodeling/ABACUS-orbitals/tree/main/Dojo-NC-FR hello, you can try orbit files in this directory.

**Comment by iduygnay** [comment]
Thank you so much!
