### ISSUE TITLE
Binary output of wave functions' coefficients

### ISSUE THREAD

**Issue by ESROAMER** [deepmodeling/abacus-develop#2455]
### Background

Binary format output are more efficient and precise in post process, especially when doing md calculation, which output the data at each step and thus form a quite large file in the end. I noticed that the program have already provides binary format output for plane wave wavefunction coefficients, but it hasn't provided binary format output for LCAO coefficients yet. It would be appreciated if binary format output of LCAO coefficients can be supported.

### Describe the solution you'd like

Unlike the case of pw basis, the overlap matrix should be provided as well to give a full description of LCAO basis. And it would be better to have some other output in binary representation, of course.

**Comment by hongriTianqi** [comment]
- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by hongriTianqi** [comment]
@ESROAMER This issue has been solved:
out_wfc_lcao = 0: no output
out_wfc_lcao = 1: output text files with .txt file
out_wfc_lcao = 2: output binary files with .dat file
