### ISSUE TITLE
I will add an input parameter to choose the convergence criterion of scf calculation.

### ISSUE THREAD

**Issue by sunliang98** [deepmodeling/abacus-develop#2469]
### Background

Currently, the convergence criterion for SCF calculation is determined according to the basis type. To further optimize the choice of `scf_thr` and `mixing_method`, as mentioned in #484 , an input parameter is needed to select this criterion. 
Once sufficient tests have been conducted, Charge Mixing will be refactored, and this parameter will be updated, too.

### Describe the solution you'd like

Add a input parameter to choose the convergence criterion of scf calculation.

**Comment by maki49** [comment]
fix #2472, and the symmetry-part error in #2474
