### ISSUE TITLE
We need some examples about EXX

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#2473]
### Details

Currently, we do not have any integration testing related to EXX, which is very dangerous. We need a batch of EXX calculation examples, and I will add them to Abacus's daily testing to ensure the stability of EXX related functions

**Comment by PeizeLin** [comment]
[exx_integration_accurate.zip](https://github.com/deepmodeling/abacus-develop/files/11518456/exx_integration_accurate.zip)

**Comment by pxlxingliang** [comment]
@PeizeLin How many cores are suitable for running these examples, and what are the running commands?

**Comment by pxlxingliang** [comment]
These examples have been uploaded to the datasets in abacustest https://launching.mlops.dp.tech/?request=GET%3A%2Fapplications%2Fabacustest%2Fdatasets%2Fdataset3-exx.
