### ISSUE TITLE
Rename E_demet

### ISSUE THREAD

**Issue by Chentao168** [deepmodeling/abacus-develop#2481]
### Describe Current Status and Possible Solution

Now, smearing contribution (-TS) in ABACUS has been named as E_demet. This can be misleading.
In QE，it was named as 'smearing contrib. (-TS)'.
![image](https://github.com/deepmodeling/abacus-develop/assets/76426373/da059598-729a-41ec-89ec-03373099e6b3)
In VASP, it was named as 'entropy T*S    EENTRO'.
![image](https://github.com/deepmodeling/abacus-develop/assets/76426373/369d65d3-b8a0-4dff-8b1e-1812dadd51ad)
I think it's necessary to choose an appropriate name to showcase this energy, or explicitly state its meaning in the document.

**Comment by Satinelamp** [comment]
Maybe a simple annotation should be enough.
just change the following line of code:
```
source/module_elecstate/elecstate_print.cpp:        this->print_format("E_demet", this->f_en.demet); // mohan add 2011-12-02
```
The final solution should be decided by the developers.

Here is a suggestion for annotation:
![image](https://github.com/deepmodeling/abacus-develop/assets/62006565/25e2b008-5a84-46af-b112-8f2d93bff6a3)

**Comment by Chentao168** [comment]
'E_demet' has been renamed as 'E_entropy (-TS)'.
#https://github.com/deepmodeling/abacus-develop/pull/2534
