### ISSUE TITLE
how to configure cmake in vs code to recognize intel oneAPI comiler.

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#2487]
### Details

I try to use `vs code +WSL+intel oneAPI` as my development environment, but it seems the `cmake` extension in vs code couldn't recognize the intel c++ compiler: 
![Snipaste_2023-05-21_14-06-31](https://github.com/deepmodeling/abacus-develop/assets/62006565/e9e682f8-8fd8-4815-a95b-fcc361e20763)

How could I let `cmake` extension recognize the compiler from intel oneAPI?
And is there any tutorial for setting up the development environment?

**Comment by caic99** [comment]
Hi @Satinelamp ,
Use VS code command palette (ctrl-shift-p by default) to find setting "CMake: edit user-local cmake kits", and add the following content:

```json
  {
    "name": "Intel oneAPI",
    "compilers": {
      "C": "/opt/intel/oneapi/compiler/latest/linux/bin/icx",
      "CXX": "/opt/intel/oneapi/compiler/latest/linux/bin/icx"
    },
    "keep": true
  }
```

Additionally, you might wish to set "Cmake: Configure Args" to customize the components.
