### ISSUE TITLE
How to constrain the magnetic orders in soc calculations

### ISSUE THREAD

**Issue by summitmoon** [deepmodeling/abacus-develop#2488]
### Background

Estimating the magnetic ground state with the SOC effect is essential to investigate the magnetic properties in material science.

### Describe the solution you'd like

I want to compare several magnetic order with the consideration of SOC calculations, but I found ABACUS do not support this now.

**Comment by wenfei-li** [comment]
please check if this is what you want : https://github.com/deepmodeling/abacus-develop/issues/1851

**Comment by summitmoon** [comment]
> please check if this is what you want : #1851

Yes, this is the same question.

**Comment by wenfei-li** [comment]
> > please check if this is what you want : #1851
> 
> Yes, this is the same question.

Good to know. I'll close the old issue and leave this one open

**Comment by hongriTianqi** [comment]
- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by hongriTianqi** [comment]
@summitmoon We have implemented the DeltaSpin method to constrain atomic magnetic moments in nonlinear and soc calculation. Documentation are provided at: http://abacus.deepmodeling.com/en/latest/advanced/scf/spin.html. Examples are provided in abacus-develop/examples/noncollinear. Please have a test and feedback to us if you meet any problems.
