### ISSUE TITLE
Should we set the default value of `symmetry`  to 1?

### ISSUE THREAD

**Issue by maki49** [deepmodeling/abacus-develop#2498]
Symmetry analysis can reduce the number of k-points to speed up the calculation. 

If `calculation=md` , the default value of symmetry is 0. 
But if `calculation=relax` there's no such enforcement, should we set it to 0 like `md`?

**Comment by Satinelamp** [comment]
maybe in MD cases, we should not take advantage of symmetry. And in practice, we often set `symmetry=0` in the relaxation process of surface catalysts.
