### ISSUE TITLE
An user-friendly way to support "flexible default value" is needed for some parameters

### ISSUE THREAD

**Issue by maki49** [deepmodeling/abacus-develop#2508]
### Background

Currently, ABACUS set the default value of a parameter twice: 
```
    this->Default();    // before reading all parameters, set a fixed default value
    bool success = this->Read(fn);
    this->Default_2();    // after reading all parameters, force changing the value
```
Such logic cannot support a  "flexible default value" like this: 
- Usually, the default value of *symmetry* is 1.
- If *calculation=nscf/istate/ienvelope*, the default value of `symmetry` should be 0.
- However, if it is set by user to 1, the final value should be 1.

That is, **if read in, set by user; if not read in, set the default value depending on some other parameters.**

### Current Solution

Set a string-type variable to "default", if(=="default”)modify it in `Default_2()`, then use `stod, stoi...` to convert it later. 

### Future Solution

There may be a common and user-friendly (int-is-int, double-is-double) solution rather than using string with stoi/stod. 
Since most of such parameters are exx-related, I will discuss it with @PeizeLin ;-)

**Comment by maki49** [comment]
I have an idea using template, here's a demo: https://github.com/maki49/Flexible_Default

**Comment by hongriTianqi** [comment]
- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by mohanchen** [comment]
We will close this issue since the INPUT module has been refactored.
