### ISSUE TITLE
The 'EXX' part of code in ESolver_KS_LCAO::do_after_converge should be moved to 'module_ri'

### ISSUE THREAD

**Issue by mohanchen** [deepmodeling/abacus-develop#2512]
### Describe Current Status and Possible Solution

Currently, the 'EXX' part of code in ESolver_KS_LCAO::do_after_converge occupies nearly 100 lines, these code lines should be simplified to only a call of EXX-related function. This kind of details should not appear in ESolver.

### Additional Context

Awareness of this kind of reconstruction is important!

**Comment by maki49** [comment]
I will move those code into an interface class and remove `GlobalC::exx_lri_double/complex` as a member of `ESolver_KS_LCAO`.
