### ISSUE TITLE
Split the large output files

### ISSUE THREAD

**Issue by ESROAMER** [deepmodeling/abacus-develop#2520]
### Describe Current Status and Possible Solution

When performing MD calculations, most of the output such as wavefunction coefficients or the Hamiltonian matrix is written to a single large file instead of multiple smaller files, which makes it difficult to view the data. It is really annoying that I have to read in 
a file which is several hundreds MB or larger every time, even if I only need a few lines of them. And I believe that "scrolling down to line 706450 to obtain data for step 6125" is not a user-friendly design.
I hope that the output format of these large files can be reconstructed to resemble the format of STRU files, which would be much easier to read or use.

**Comment by YuLiu98** [comment]
Hello, input parameters `out_app_flag` and `out_interval` may solve your issue.

**Comment by ESROAMER** [comment]
> Hello, input parameters `out_app_flag` and `out_interval` may solve your issue.

Thanks for your reply! I see you did have designed a flag to control the output format. But it didn't work. I tested some simple md examples as you said, and with almost all the other parameters set to default, ABACUS still output these matrices in a single large file no matter parameters out_app_flag and out_interval are set to "true" or "false",“1” or “0”。

**Comment by ESROAMER** [comment]
> Hello, input parameters `out_app_flag` and `out_interval` may solve your issue.

You may check my input parameters below to see if I use them correctly:
```
basis_type      lcao

ecutwfc         70
scf_nmax        100
scf_thr         1e-6

calculation     md
esolver_type    ksdft
md_type         nve
md_nstep        80
md_dt           0.001
md_tfirst       0

out_mat_hs      1
out_wfc_lcao    1
out_app_flag    false
out_interval    5
```

**Comment by mohanchen** [comment]
The MD data should be analyzed via statistical methods, so we design the output file in a way that reading them via scripts should be easy. In contrast, it will be difficult to transfer the data if we generate a file for each MD step, then typically the number of output files will be huge.

**Comment by YuLiu98** [comment]
> > Hello, input parameters `out_app_flag` and `out_interval` may solve your issue.
> 
> Thanks for your reply! I see you did have designed a flag to control the output format. But it didn't work. I tested some simple md examples as you said, and with almost all the other parameters set to default, ABACUS still output these matrices in a single large file no matter parameters out_app_flag and out_interval are set to "true" or "false",“1” or “0”。

You are right, `out_mat_hs` and `out_wfc_lcao` cannot be controlled by `out_app_flag` and `out_interval`. Maybe this feature will be implemented later by @lyb9812.
