### ISSUE TITLE
Installation without setting MPI_CXX_COMPILER

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#2524]
### Details

If I set c++ compiler as MPI compilers by using `cmake -DCMAKE_CXX_COMPILER=mpiicpc`, does it mean I don't have to set `MPI_CXX_COMPILER` explicitly?

**Comment by caic99** [comment]
@Satinelamp Yes, you can give it a try.

**Comment by Satinelamp** [comment]
Honestly, this is what I've done on my cluster. Here is the `cmake` command I use
```
cd abacus-develop
cmake -DCMAKE_CXX_COMPILER=mpiicpc -B build -DCMAKE_INSTALL_PREFIX=~/software/abacus_install -DELPA_DIR=~/software/elpa_install -DCEREAL_INCLUDE_DIR=~/software/cereal/include -DLibxc_DIR=~/software/libxc_install -DENABLE_LIBRI=ON
cmake --build build -j4
cmake --install build
```
With above command, abacus seems work fine, but I am not sure if the performance would be affected. I will try to test it.
