### ISSUE TITLE
all-electron charge density

### ISSUE THREAD

**Issue by June976** [deepmodeling/abacus-develop#2525]
### Details

How to obtain the all-electron charge density (valence+core) from a scf calculation in ABACUS? Does plane wave or numerical atomic basis all work well for this?

**Comment by mohanchen** [comment]
ABACUS currently does not support this function.

**Comment by Satinelamp** [comment]
This might be needed for hefei-namd calculation. It is recommended to use an all-electron wavefunction to do named calculations.

**Comment by June976** [comment]
I see, thanks!
