### ISSUE TITLE
the 'print' function in ESolver_KS_LCAO should be simplified

### ISSUE THREAD

**Issue by mohanchen** [deepmodeling/abacus-develop#2532]
### Describe Current Status and Possible Solution

if print == true, the code prints out charge density, density matrix, as well as kinetic energy density (?).
I consider the codes should be moved to somewhere else. A new interface should be designed.
The code lines lie from line 746 to line 829.

in ESolver_KS_LCAO::afterscf function:
The same things occur from line 837 to 859 (generally, there should be no 'new' and 'delete' in ESolver)
The same things occur from line 861 to line 949.
The same things occur from line 962 to line 1000 (combine out_pot==1 and out_pot==2 into one interface function).
The same things occur from line 1066 to line 1095 (combine out_mat_hsR, out_mat_t, out_mat_dh, and out_mat_r into one interface function).

**Comment by hongriTianqi** [comment]
@mohanchen Most of the issues have been tackled in PR #2562 , accept two:
1)  out_pot==1 and out_pot==2  should be refactored before adding their an interface in ModuleIO; #2567 
2) out_mat_hsR, out_mat_t, out_mat_dh, and out_mat_r lack corresponding CI tests, the interface will be added after adding the tests. https://github.com/deepmodeling/abacus-develop/issues/2574
