### ISSUE TITLE
Default value of "mixing_beta"

### ISSUE THREAD

**Issue by LiuXiaohui123321** [deepmodeling/abacus-develop#2533]
https://github.com/deepmodeling/abacus-develop/blob/4f4bb564ccf40a1c2b477434c9fe48b1fb460056/source/module_io/input.cpp#LL280C6-L280C6

Here the default value of "mixing_beta" is set to -10, which should not be a reasonable value. 
Are there any other considerations for such a default?
@dyzheng @mohanchen

**Comment by mohanchen** [comment]
I agree, it should be improved.

**Comment by Satinelamp** [comment]
`-10` actually is a dummy value for telling the abacus to auto-set `mixing_beta`.
![image](https://github.com/deepmodeling/abacus-develop/assets/62006565/dc465354-ec59-4df1-9872-d86769b17b23)

**Comment by Satinelamp** [comment]
There are two methods in the code of ABACUS to set default value of input parameters

One is like the case of `mixing_beta`, which uses a dummy value.
The other one is the case of `symmetry`, which uses a string of `default` and `std:stoi` method

Here is a discussion about these two methods
https://github.com/deepmodeling/abacus-develop/pull/2503#issuecomment-1560226887
https://github.com/deepmodeling/abacus-develop/issues/2508

**Comment by LiuXiaohui123321** [comment]
> `-10` actually is a dummy value for telling the abacus to auto-set `mixing_beta`. ![image](https://user-images.githubusercontent.com/62006565/241098624-dc465354-ec59-4df1-9872-d86769b17b23.png)

OK! Thank you for your reply.

**Comment by LiuXiaohui123321** [comment]
> There are two methods in the code of ABACUS to set default value of input parameters
> 
> One is like the case of `mixing_beta`, which uses a dummy value. The other one is the case of `symmetry`, which uses a string of `default` and `std:stoi` method
> 
> Here is a discussion about these two methods [#2503 (comment)](https://github.com/deepmodeling/abacus-develop/pull/2503#issuecomment-1560226887) #2508

Got it! Thanks!
