### ISSUE TITLE
The new input module needed

### ISSUE THREAD

**Issue by mohanchen** [deepmodeling/abacus-develop#2549]
### Background

The old module of input needs to be updated due to a large number of parameters are now supported by different developers.

### Describe the solution you'd like

Invent a new input module

**Comment by hongriTianqi** [comment]
This issue has been solved by the merged PR.

**Comment by hongriTianqi** [comment]
We might need to give a brief introduction of the solved problem, for example, what problem we have solved and how to use the new input functions. @baixiaokuang @grysgreat

**Comment by grysgreat** [comment]
This PR adds a series of new input module interfaces, including map for storing parameter types and values, an interface for passing parameters to map, and an interface for reading parameters through a configuration file. A new parameter usage design mode is proposed, which is not connected with abacus parameter module at present. See code comments for detailed usage of the function.

**Comment by hongriTianqi** [comment]
This issue summarized the solved issue, so is a good practice issue.
