### ISSUE TITLE
Tighten the error threshold in CI integration testing

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#2558]
### Describe Current Status and Possible Solution

In the current CI testing, the threshold is relatively high, which results in inaccurate reporting of error messages when numerical errors occur. It is recommended to tighten this judgment threshold.

### Additional Context

In case 601_NO_TDDFT_CO, repeating calculations would lead to different consequence.
![image](https://github.com/deepmodeling/abacus-develop/assets/49852742/e26b7576-9cd5-4a51-80c0-82ede444bcf9)
![image](https://github.com/deepmodeling/abacus-develop/assets/49852742/3504bb2d-e7f5-4b86-acd6-cb3c8da72a3c)

**Comment by dyzheng** [comment]
In case 281_NO_KP_HSE, repeating calculations would lead to different consequence.
![image](https://github.com/deepmodeling/abacus-develop/assets/49852742/48cde559-f4de-44fc-ae3e-9ea7474c441e)
![image](https://github.com/deepmodeling/abacus-develop/assets/49852742/96dc275a-6934-4b19-8044-e12196e17c23)

@maki49 can you look at this case?

**Comment by dyzheng** [comment]
In case 220_NO_KP_MD_MSST, repeating calculations would lead to different consequence.
![image](https://github.com/deepmodeling/abacus-develop/assets/49852742/cfad6c0f-eaa4-48d3-8019-af973cdf54a0)
![image](https://github.com/deepmodeling/abacus-develop/assets/49852742/6200cbd7-289c-40c6-ab5e-9961c30ec980)

Fixed in https://github.com/deepmodeling/abacus-develop/pull/2553 .

**Comment by dyzheng** [comment]
In case 208_NO_KP_CF_RE, repeating calculations would lead to different consequence.
![image](https://github.com/deepmodeling/abacus-develop/assets/49852742/e8f3c8be-9d92-42bf-9921-0d9b3eb07ba9)
![image](https://github.com/deepmodeling/abacus-develop/assets/49852742/eeb4168c-18f2-4e1c-bf88-7c61fa5b7232)

Fixed in #2553 .

**Comment by dyzheng** [comment]
In case 127_PW_15_PK_AF, repeating calculations would lead to different consequence.

![image](https://github.com/deepmodeling/abacus-develop/assets/49852742/75a59455-c9e8-4923-bc7f-0b74d858b144)
![image](https://github.com/deepmodeling/abacus-develop/assets/49852742/e95dd2ba-fa4a-460d-9421-f49b522d670a)

**Comment by YuLiu98** [comment]
> In case 220_NO_KP_MD_MSST, repeating calculations would lead to different consequence. ![image](https://user-images.githubusercontent.com/49852742/241625283-cfad6c0f-eaa4-48d3-8019-af973cdf54a0.png) ![image](https://user-images.githubusercontent.com/49852742/241625515-6200cbd7-289c-40c6-ab5e-9961c30ec980.png)
> 
> @YuLiu98 can you look at this case?

I have updated the result.ref in PR #2553, and the warning is caused by the older code.

**Comment by dyzheng** [comment]
> I have updated the result.ref in PR #2553, and the warning is caused by the older code.

Thanks, 220_NO_KP_MD_MSST and 208_NO_KP_CF_RE are fixed in #2553.

**Comment by hongriTianqi** [comment]
This issue has been splitted.
