### ISSUE TITLE
“start magnetization” information redundancy

### ISSUE THREAD

**Issue by 1041176461** [deepmodeling/abacus-develop#2587]
### Describe Current Status and Possible Solution

I think "start magnetization" information in running*log is redundant,  
![image](https://github.com/deepmodeling/abacus-develop/assets/40336950/5bf719eb-70a6-4fb0-b2a5-d80853df3c3a)
I think the initial magnetic moment can be displayed in the "mag" of the structure information
![image](https://github.com/deepmodeling/abacus-develop/assets/40336950/bfba5aa1-a4bb-400e-b2ba-c7980821d10d)

**Comment by dyzheng** [comment]
I will fix this printing format.
