### ISSUE TITLE
symmetry_prec problem in ABACUS

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#2592]
### Details

When I did calculation of this example by ABACUS 3.2.4

[Fe7C3-I.tar.gz](https://github.com/deepmodeling/abacus-develop/files/11640450/Fe7C3-I.tar.gz)

This error message arised:

```bash
 UNIFORM GRID DIM     : 60 * 144 * 90
 UNIFORM GRID DIM(BIG): 12 * 36 * 30
 DONE(0.727659   SEC) : SETUP UNITCELL
 DONE(0.749955   SEC) : SYMMETRY
Optimized lattice type of reciprocal lattice cannot match the optimized real lattice. 
It is often because the inaccuracy of lattice parameters in STRU.
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 Refine the lattice parameters in STRU or use a different`symmetry_prec`. 
 CHECK IN FILE : OUT.FeCx/warning.log
```

In ABACUS 3.2.4, `symmetry` in `INPUT` set default to 1 rather than 0;
if set `symmetry 0`, calculation can be done in 64core (16core will have another problem)
I also did test in ABACUS 3.2.3, when `symmetry 1`, this error message will also arise

What's the problem? Notice that this structure should be near the minimum, the same structure and the same cell-relax calculation can be easily done in VASP

**Comment by maki49** [comment]
VASP gives the same error message as ABACUS in this case with the default `symmetry_prec=1e-5`.
VASP's output: 
```
|     Inconsistent Bravais lattice types found for crystalline and            |
|     reciprocal lattice:                                                     |
|                                                                             |
|        Crystalline: simple monoclinic                                       |
|        Reciprocal : triclinic                                               |
|                    (instead of simple monoclinic)                           |
|                                                                             |
|     In most cases this is due to inaccuracies in the specification of       |
|     the crytalline lattice vectors.                                         |
|                                                                             |
|     Suggested SOLUTIONS:                                                    |
|      ) Refine the lattice parameters of your structure,                     |
|      ) and/or try changing SYMPREC.   
```

ABACUS' OUT.FeCx/running_cell-relax.log:
```
Error: Bravais lattice type of reciprocal lattice is not compatible with that of real space lattice:
ibrav of real space lattice: 12. Monoclinic P (simple)
ibrav of reciprocal lattice: 14. Triclinic cell
(which should be 13).
```

I tried to set `symmetry_prec 2e-5` in INPUT file and it can run normally.

**Comment by QuantumMisaka** [comment]
@maki49 So the problem lies in the structure itself
But can the default setting `symmetry 1` for ABACUS 3.2.4 have better calculation performance?
in VASP this default is `ISYM 2`

**Comment by maki49** [comment]
> @maki49 So the problem lies in the structure itself But can the default setting `symmetry 1` for ABACUS 3.2.4 have better calculation performance? in VASP this default is `ISYM 2`

In this case the performance is not better, because the result of symmetry analysis is `C_1`, which cannot reduce the number of k-points: 
```
              PURE POINT GROUP OPERATIONS = 1
                   SPACE GROUP OPERATIONS = 1
                              POINT GROUP = C_1
               POINT GROUP IN SPACE GROUP = C_1
```
In calculation of higher symmetric configuration with many k-points, `symmetry 1` will lead to better performance.

**Comment by QuantumMisaka** [comment]
@maki49 Is this symmetry analysis result changed by setting `symmetry_prec 2e-5` or even larger?
This structure should be orthogonal in some way

**Comment by maki49** [comment]
> @maki49 Is this symmetry analysis result changed by setting `symmetry_prec 2e-5` or even larger? This structure should be orthogonal in some way

Yes, ABACUS and VASP give the same results: 
| symmetry_prec | point group in space group |
|:----------------:|:------------------------------:|
| 2e-5, 1e-4| C_1|
| 1e-3| D_2h|

**Comment by QuantumMisaka** [comment]
@maki49 Thanks a lot !
Last question is how can I quickly read this symmetry analysis result (what keywards for `grep` ) in ABACUS and VASP?

**Comment by maki49** [comment]
> @maki49 Thanks a lot ! Last question is how can I quickly read this symmetry analysis result (what keywards for `grep` ) in ABACUS and VASP?

Just grep `group` in OUTCAR and `GROUP` in OUT.suffix/running_calculation.log.
