### ISSUE TITLE
Memory problem in simple cell-relax calculation

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#2593]
### Details

[Fe5C2_cellrelax.tar.gz](https://github.com/deepmodeling/abacus-develop/files/11640472/Fe5C2_cellrelax.tar.gz)

When I do calculation above in 16core, this problem will arise:

```
 ><><><><><><><><><><><><><><><><><><><><><><
 TOTAL-STRESS (KBAR):
 ><><><><><><><><><><><><><><><><><><><><><><
 -1.206e-01     -3.773e-01     -5.186e-02     
 -3.773e-01     1.051e+01      9.533e+00      
 -5.186e-02     9.533e+00      8.961e+00      
 TOTAL-PRESSURE: 6.449e+00 KBAR
 ETOT DIFF (eV)       : -1.145e-05
 LARGEST GRAD (eV/A)  : 1.510e-01
 BFGS TRUST (Bohr)    : 5.054e-05
 -------------------------------------------
 RELAX CELL : 1
 RELAX IONS : 22 (in total: 22)
 -------------------------------------------
 DONE(8.050e+03  SEC) : INIT SCF
 ITER   TMAG      AMAG      ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
[1685690216.747862] [l05c35n1:326464:0]        mm_xpmem.c:136  UCX  ERROR   failed to attach xpmem apid 0x40004fb40 offset 0x1c3713000 length 36864: Cannot allocate memory
[1685690216.747892] [l05c35n1:326464:0]        ucp_rkey.c:476  UCX  ERROR   failed to unpack remote key from remote md[7]: Input/output error
[1685690216.779046] [l05c35n1:326464:0]         pgtable.c:643  UCX  WARN    failed to remove pgtable region0x238fe750 [0x238e6f60..0x1496010]
[1685690351.980904] [l05c35n1:326464:0]          rcache.c:624  UCX  WARN    xpmem_remote_mem: destroying inuse region 0x238fe750 [0x238e6f60..0x1496010] g- rw ref 4294967295 apid 0x40004fb40 attach_addr (nil) rmem 0x7f2ff8014260
```

The same problem will arise in the test below

[Fe7C3-II_cellrelax.tar.gz](https://github.com/deepmodeling/abacus-develop/files/11640478/Fe7C3-II_cellrelax.tar.gz)

I tried using more core like 64core to have more memory resources, but the calculation will stuck without any error message

So what is the problem? Notice that these calculation can be easily done by VASP

**Comment by QuantumMisaka** [comment]
in a full node with 64core (256G mem), this error above will also arised

**Comment by pxlxingliang** [comment]
Hi @QuantumMisaka, is this error reproducible, I ran Fe7C3-II by using Bohrium c32_m64_cpu  with command `OMP_NUM_THREADS=1 mpirun -np 16 abacus`, and everything is normal in more than 60 ION steps.

**Comment by QuantumMisaka** [comment]
> is this error reproducible, I ran Fe7C3-II by using Bohrium c32_m64_cpu with command `OMP_NUM_THREADS=1 mpirun -np 16 abacus`, and everything is normal in more than 60 ION steps.

Hi @pxlxingliang I am trying using `OMP_NUM_THREADS=1`，but I have tried `OMP_NUM_THREADS=4` for lots of times in ABACUS 3.2.3 or 3.2.4 and this problem is reproducible. Besides, this is a nearly converged structure, in VASP the cell-relax calculation can be done within 10 ION steps, so running more than 60 ION steps is not normal itself.

**Comment by QuantumMisaka** [comment]
@pxlxingliang I have tried `OMP_NUM_THREADS=1` on my server in 16core, this error also arise. 
My plaform is Intel Platinum 8358 in Rockylinux 8.7
My installation of abacus is in https://blog.csdn.net/weixin_44471577/article/details/130815345

in AMD EPYC 7b12 server the calculation seems to be OK now

**Comment by pxlxingliang** [comment]
I repeated 5 times by intel/oneapi complied abacus, and all are normal. It seems that it is related to the compilation environment, @caic99 can you take a look?

**Comment by caic99** [comment]
> I repeated 5 times by intel/oneapi complied abacus, and all are normal. It seems that it is related to the compilation environment, @caic99 can you take a look?

@QuantumMisaka This problem might happenes within your MPI communication with infiniband. Please check if IB is configured correctly, and your MPI distribution matches the IB interface.

**Comment by QuantumMisaka** [comment]
The key of this problem may be in the server environment, ABACUS from the same compile method in AMD EPYC 7B12 can finish this calculation in 18 ION steps. but how can I check the information about IB?

**Comment by caic99** [comment]
> The key of this problem may be in the server environment, ABACUS from the same compile method in AMD EPYC 7B12 can finish this calculation in 18 ION steps. but how can I check the information about IB?

@QuantumMisaka Maybe you could contact your system admin.

**Comment by hongriTianqi** [comment]
@QunatumMisaka I think this issue has been solved? If you still have problems, just open this issue again.
