### ISSUE TITLE
Suggestion of redundant information in output files. 

### ISSUE THREAD

**Issue by jingan-181** [deepmodeling/abacus-develop#2596]
### Describe Current Status and Possible Solution

1. When using PW basis set for non-self-consistent calculations, there is some redundant information in the running_nscf.log file, such as the following:
![pw](https://github.com/deepmodeling/abacus-develop/assets/78459531/4f10d4a8-0674-4067-a776-69f9861664c2)

2. Is it necessary to output detailed coordinates about kpoints in the running file? There is already a kpoints file. 
![kpoints](https://github.com/deepmodeling/abacus-develop/assets/78459531/e6052926-23e1-4e72-9f31-535cde27ad8a)

3. When using PW basis set, the final Fermi energy is not outputted, while it is outputted when using LCAO basis set.
![image](https://github.com/deepmodeling/abacus-develop/assets/78459531/572b48d9-f869-4153-ab93-691770132790)
![image](https://github.com/deepmodeling/abacus-develop/assets/78459531/40f508d0-42d8-4837-b4cb-db2fc042772f)

4. There are many numerical parts in the output files that are not formatted properly, which is not very aesthetically pleasing.

**Comment by mohanchen** [comment]
We will fix that except 2.

**Comment by dyzheng** [comment]
3 has been fixed by #2604. 
Others still in progress.

**Comment by dyzheng** [comment]
4 is a good suggestion, I will design a Formatter class for this suggestion in #2606 .

**Comment by hongriTianqi** [comment]
A new formatter has been added by https://github.com/deepmodeling/abacus-develop/pull/2859

**Comment by hongriTianqi** [comment]
This issue is systematically solved by one PR, so is a good practice.
