### ISSUE TITLE
more details required for mixing parameters in manual

### ISSUE THREAD

**Issue by HongSPang** [deepmodeling/abacus-develop#2597]
### Background

Currently there are only few descriptions for mixing parameters

### Describe the solution you'd like

I wish more detailed illustrations for mixing gg0, mixing beta, mixing ndim. Such description could contain these  features for illumination:
1. what parameter should I tune if the scf calculation refuse to converge, especially a vibrating density of state.
2. what is the meaning of these parameters? What would the convergence behave after I tune them?
3.suggestions for scf calculations of hard-convergence systems, for example one could tune up mixing beta for a rough convergence, upon such result, one could tune down mixing beta and tune up mixing gg0 for better results.

**Comment by mohanchen** [comment]
We will prepare a document for how to choose mixing parameters.

**Comment by hongriTianqi** [comment]
- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.
