### ISSUE TITLE
Fractional Occupation and wrong results of the system( H bcc)

### ISSUE THREAD

**Issue by AroundPeking** [deepmodeling/abacus-develop#2600]
### Describe the bug

I test RPA calculation of bcc H structure. Here I give 3 outputs (H.out, LibRPA_H.out, band_out).
[H_bcc.zip](https://github.com/deepmodeling/abacus-develop/files/11645454/H_bcc.zip)

It is found that there exists fractional occupation and wrong E_cRPA, which is even positive and has a imaginary part.

Moreover, I test KPT(111) and KPT(112). It seems right.

**Comment by Srlive1201** [comment]
LibRPA currently cannot handle systems that involve fractional occupation. We plan to improve this in the future.
