### ISSUE TITLE
the atomic structure file STRU_ION_D should be standardized and formatted

### ISSUE THREAD

**Issue by xdzhu** [deepmodeling/abacus-develop#2601]
### the atomic structure output STRU_ION_D should be standardized and formatted

Comparing to the CONTCAR in VASP output files with well-organized and aligned format, the STRU_ION_D of ABACUS is disorderly, not aligned and also inconvenient to column operation.

Please make the STRU_ION_D file **more organized** and format the floating number as **decimal notation** rather than scientific notation.

Example:
VASP CONTCAR
![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/d6f65cb9-199d-4727-ab7e-c78b1c3caeb0)

ABACUS STRU_ION_D
![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/242809a2-dfe7-438a-a2c4-a61593fbed85)

**Comment by mohanchen** [comment]
This is an excellent suggestion! Thanks!

**Comment by dyzheng** [comment]
This Issue is not related with #2606 , you can treat it in your own way. @sunliang98 @YuLiu98

**Comment by YuLiu98** [comment]
> This Issue is not related with #2606 , you can treat it in your own way. @sunliang98 @YuLiu98

I think the Formatter proposed in #2606 can also be used here.

**Comment by hongriTianqi** [comment]
@dyzheng I will solve this issue.

**Comment by kirk0830** [comment]
A small library has been developed to handle with string formatting tasks. Pull request will be submit very soon.

**Comment by hongriTianqi** [comment]
This issue is systematically solved by one PR, so is a good practice.
