### ISSUE TITLE
Tools for optimizing printing format: Formatter

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#2606]
### Describe Current Status and Possible Solution

In current ABACUS code, printing format is specified with different criterion, which lead to result files unaesthetic, I will add a new tool "Formatter" class in module_io, which will have advantages below:
1. **Consistency**: By using a `Formatter` class, you can ensure a consistent output format throughout your application. This is especially useful when you have multiple developers working on the same project or when you want to enforce a specific style guide.

2. **Readability**: A `Formatter` class can abstract away the details of formatting, making the code more readable. When you need to format multiple values in different parts of your code, having a dedicated class can help in making the code cleaner and more maintainable.

3. **Flexibility**: If you ever need to change the output format, a `Formatter` class makes it easy to do so in a centralized location. This is particularly helpful when you want to make global changes to the formatting style or when you need to support multiple output formats.

4. **Reusability**: A well-designed `Formatter` class can be easily reused across different projects, saving time and effort in implementing consistent formatting in new projects.

5. **Extensibility**: Using a `Formatter` class allows you to easily extend the functionality as needed. For example, you can add support for new data types or format options without having to modify the code that uses the class.

### Additional Context

The code preview is listed below:
```
class Formatter {
public:
    Formatter(int width = 0, int precision = 2, char fillChar = ' ', bool fixed = true)
        : width_(width), precision_(precision), fillChar_(fillChar), fixed_(fixed) {}

    template <typename T>
    std::string format(const T& value) {
        std::stringstream ss;
        if (fixed_) {
            ss << std::fixed;
        } else {
            ss << std::scientific;
        }

        // judge plus or minus
        if (std::is_signed<T>::value && value >= 0) {
            ss << " ";
        }

        ss << std::setw(width_) << std::setprecision(precision_) << std::setfill(fillChar_);
        ss << value;
        return ss.str();
    }

private:
    int width_;
    int precision_;
    char fillChar_;
    bool fixed_;
};

```

The code usage would be:
```
    Formatter formatter(20, 2, ' ', false);//false means scientific format, while true would be fixed format
    double d1 = -3.14E30;
    double d2 = 5.15E-15;

    std::cout << "double: " << formatter.format(d1) << std::endl;
    std::cout << "double: " << formatter.format(d2) << std::endl;
```

The result of code above would be :
```
double: -3.14e+30          
double:  5.15e-15
```

**Comment by jinzx10** [comment]
My two cents:
1. There's a IO manipulator "std::showpos" which enables the display of '+' for non-negative numbers and ensures equal width for positive & negative numbers:
https://en.cppreference.com/w/cpp/io/manip/showpos

2. I'm curious about the goal of this Formatter class -- is it supposed to replace the use of printf/fprintf in future ABACUS development, or live alongside? printf/sprintf has a rich set of options and is convenient in many scenarios, e.g.,
```
    std::string title = "Iter        Energy            Ediff       Residual    Time (sec)";
    constexpr char format[] = "%2s%-4i   %+12.8e   %+8.4e   %8.4e   %6.1f\n";

    std::string method = "GE";
    int istep[] = {1,10,100,1000};
    double residual[] = {111, 10, 1, 0.001};
    double energy[] = {-12345.6789, 1111.5, 18.003, -2.001};
    double ediff[] = {-123, 5, 0.02, -0.001};
    double time[] = {0.001, 0.25, 123, 1234};

    std::cout << title << std::endl;
    for (int i = 0; i != 4; ++i) {
        std::printf(format, method.c_str(), istep[i], energy[i], ediff[i], residual[i], time[i]);
    }
```
would generate
```
Iter        Energy            Ediff       Residual    Time (sec)
GE1      -1.23456789e+04   -1.2300e+02   1.1100e+02      0.0
GE10     +1.11150000e+03   +5.0000e+00   1.0000e+01      0.2
GE100    +1.80030000e+01   +2.0000e-02   1.0000e+00    123.0
GE1000   -2.00100000e+00   -1.0000e-03   1.0000e-03   1234.0
```
and modern compilers can perform a brief type safety & format check provided "-Wformat" flag is turned on (this check requires that the format char array be constexpr).

3. About the design of the class, I was wondering, is it going to support formatting multiple objects at once? Both the traditional printf/sprintf ( (like "%2s%-4i   %+12.8e   %+8.4e   %8.4e   %6.1f\n" in the above example) or new std::format introduced in c++20 support the use of a format string to format multiple data.

**Comment by dyzheng** [comment]
This issue only focus on how to uniform output format in "GlobalV::ofs_running" in ABACUS, which will print to file "OUT.suffix/running_scf.txt"

**Comment by hongriTianqi** [comment]
This issue is systematically solved by one PR, so is a good practice.
