### ISSUE TITLE
PR #2503 induced energy derivation from exiting results

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#2608]
### Describe the bug

PR #2503   induced large energy derivation from exiting results, this problem should be fixed.

<img width="791" alt="截屏2023-06-07 16 23 56" src="https://github.com/deepmodeling/abacus-develop/assets/18049272/c237fe4e-dad0-4eb8-90a0-b8731b5bafb6">

<img width="791" alt="截屏2023-06-07 16 23 44" src="https://github.com/deepmodeling/abacus-develop/assets/18049272/bb438c57-377d-4144-8539-19d9d76a5d34">

**Comment by dyzheng** [comment]
We have tested case of "fco" with large ecutwfc and k-points, there is still large difference between "symmetry 0" and "symmetry 1", it maybe a serious bug.

**Comment by dyzheng** [comment]
https://github.com/deepmodeling/abacus-develop/issues/2626

**Comment by Satinelamp** [comment]
Here is another case that might be related to this `symmetry`  issue. https://github.com/deepmodeling/abacus-develop/issues/2649

**Comment by hongriTianqi** [comment]
- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by hongriTianqi** [comment]
<img width="978" alt="截屏2023-11-07 11 13 16" src="https://github.com/deepmodeling/abacus-develop/assets/18049272/8490f2d9-783e-41ec-9682-6c78167e1811">

**Comment by maki49** [comment]
It is fixed in #3081.

**Comment by hongriTianqi** [comment]
It still exits as can be seen in the link: https://github.com/deepmodeling/abacus-develop/actions/runs/7402894412/job/20141697031

**Comment by hongriTianqi** [comment]
![Image](https://github.com/deepmodeling/abacus-develop/assets/18049272/3682d741-88a5-495b-9860-07258d86e22e)

**Comment by maki49** [comment]
#3081 changed the result.ref file of 824_NO_LT_fco but forgot to change the one in 810_PW_LT_fco.
#3412 will fix it.
