### ISSUE TITLE
The Symmetry::rhog_symmetry function is time-consuming when calculating the provided gpu example.

### ISSUE THREAD

**Issue by denghuilu** [deepmodeling/abacus-develop#2611]
### Background

![17155e05-07bd-4be7-ba74-2ca53a5bca5d](https://github.com/deepmodeling/abacus-develop/assets/21070560/73e9a41e-eb36-401d-ab59-804080d6d5c6)
It takes almost 40% of the total time to run this function.

- Benchmark system: [gpu example](https://github.com/deepmodeling/abacus-develop/tree/develop/examples/gpu)
- Hardware: 3090

### Describe the solution you'd like

Provide a GPU implementation of this function while in GPU runtime.

**Comment by hongriTianqi** [comment]
- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.
