### ISSUE TITLE
Any specific reason for these codes?

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#2622]
### Details

In nonlocal_op.cpp, we have something like this:

```
template <typename FPTYPE> 
struct nonlocal_pw_op<FPTYPE, psi::DEVICE_CPU> {
  void operator() (
      const psi::DEVICE_CPU* /*dev*/,
      const int& l1,
      const int& l2,
      const int& l3,
      int& sum,
      int& iat,
      const int& spin,
      const int& nkb,
      const int& deeq_x,
      const int& deeq_y,
      const int& deeq_z,
      const FPTYPE* deeq,
      std::complex<FPTYPE>* ps,
      const std::complex<FPTYPE>* becp)
```

From what I understand, this is basically used as a function. Is there any specific reason why this part of the code cannot be written as a normal function?
Further, it seems that a RealArray is passed in here as a pointer, and a specific element is accessed in the following manner:
`deeq[((spin * deeq_x + iat + ii) * deeq_y + xx) * deeq_z + kk] `
Is there any specific reason why we cannot pass the RealArray in and access it normally such as in the case of VNL_in_pw.cpp?
`this->deeq(is, iat, ih, jh) = this->dvan(it, ih, jh);`

**Comment by denghuilu** [comment]
Hello, the purpose of this operation is to be compatible with heterogeneous computing frameworks like CUDA. Please consider the following definition as an integration of four functions: `nonlocal_pw_op<double, cpu>`,  `nonlocal_pw_op<double, gpu>`, `nonlocal_pw_op<float, cpu>` and `nonlocal_pw_op<float, gpu>`.
```
template <typename FPTYPE, typename Device> 
struct nonlocal_pw_op {
  /// @brief Compute the nonlocal potential of hPsi
  ///
  /// Input Parameters
  /// \param dev : the type of computing device
  /// \param l1 : ucell->atoms[it].na
  /// \param l2 : nbands
  /// \param l3 : ucell->atoms[it].ncpp.nh
  /// \param sum : intermediate value
  /// \param iat : intermediate value
  /// \param spin : current spin
  /// \param nkb : ppcell->nkb, number of kpoints
  /// \param deeq_x : second dimension of deeq
  /// \param deeq_y : third dimension of deeq
  /// \param deeq_z : forth dimension of deeq
  /// \param deeq : ppcell->deeq
  /// \param becp : intermediate array
  ///
  /// Output Parameters
  /// \param ps : output array
  void operator() (
      const Device* dev,
      const int& l1,
      const int& l2,
      const int& l3,
      int& sum,
      int& iat,
      const int& spin,
      const int& nkb,
      const int& deeq_x,
      const int& deeq_y,
      const int& deeq_z,
      const FPTYPE* deeq,
      std::complex<FPTYPE>* ps,
      const std::complex<FPTYPE>* becp);
```
In this way, we can control the precision and the computing device of this function by the provided FPTYPE and Device template parameters. The reason we cannot use RealArray is that it is a data structure defined on the CPU with double precision and cannot be directly used on the GPU or with the single precision setting.

Perhaps in the future, we can simplify the function call arguments by using container tensors.

**Comment by denghuilu** [comment]
Another reason is to eliminate the reliance of ops on the abacus modules. Maintaining their independence is beneficial for unit tests (UTs).

**Comment by wenfei-li** [comment]
It would be better if we can indeed have a container tensor.
