### ISSUE TITLE
Turn off symmetry as default

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#2626]
### Background

Given the amount of symmetry related issues lately, I suggest we turn off symmetry by default until the stability of the new symmetry module is further established.

### Describe the solution you'd like

Set default to 0, just like what we had previously.

### Additional Context

We might consider including Spglib instead of implementing symmetry operations ourselves.

**Comment by dyzheng** [comment]
This issue related to another Issue with context.
