### ISSUE TITLE
Implementing PAW (projector augmented wave)

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#2632]
### Background

ABINIT has a very nice PAW module which can be adopted for carrying out PAW calculations.

### Describe the solution you'd like

I am currently working on it.

**Comment by wenfei-li** [comment]
#2633 the first pr; deals with some basic reading operations and spherical bessel transformation

**Comment by wenfei-li** [comment]
#2694 the second pr; deals with splines and spherical harmonics

**Comment by wenfei-li** [comment]
#2731 the third pr, added paw_atom class

**Comment by wenfei-li** [comment]
#2734 calculates rhoij from wavefunctions

**Comment by wenfei-li** [comment]
https://github.com/deepmodeling/abacus-develop/pull/2815 some subroutines for collecting and passing information to libpaw

**Comment by hongriTianqi** [comment]
- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by wenfei-li** [comment]
I will close this issue with https://github.com/deepmodeling/abacus-develop/pull/3110, which fixes the last bug for multi-k paw. Now PAW works for SCF calculations.
