### ISSUE TITLE
HSE calculation does not terminate properly

### ISSUE THREAD

**Issue by shuo1118** [deepmodeling/abacus-develop#2634]
### Describe the bug

The SCF calculation with the HSE functional does not terminate properly even after reaching the specified convergence criteria.

### Environment

registry.dp.tech/deepmodeling/abacus-intel:latest

### Additional Context

[
[out.zip](https://github.com/deepmodeling/abacus-develop/files/11742729/out.zip)
](url)

**Comment by pxlxingliang** [comment]
Hi @shuo1118, ABACUS will firstly run a normal SCF and then update the part of hybrid functional, and loop these two steps until convergence. The first step is really fast (about 23s per scf step on c64_m128_cpu with command: OMP_NUM_THREADS=32 mpirun -np 1 abacus), while the second step is very slow (more than 10 hours for your 128 atoms system). 
So, this is not a bug, but just running slowly.
