### ISSUE TITLE
any parameters to control parallel performance?

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#2641]
### Details

I try to compare the time to finish one electronic step between VASP and ABACUS, but whether I use LCAO or PW basis, ABACUS is much solwer than VASP, e.g. this issue https://github.com/deepmodeling/abacus-develop/issues/2636
 I am wondering if there is any parameter to control the parallel performance in ABACUS, so I could tune the speed of ABACUS?

**Comment by dyzheng** [comment]
We will update documentation soon.

**Comment by Satinelamp** [comment]
@dyzheng， Thanks a lot for the reply. I am trying to learn how to use ABACUS, Could you tell me a few parameters, so I could do a few tests on my PC?

**Comment by dyzheng** [comment]
For "basis_type==pw", there are some parameter related to performance:
   http://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#kpar (parallel for k-points)
   http://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#ecutwfc (decrease value to accelerate)
   http://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#ks-solver (dav sometimes faster than cg)

**Comment by dyzheng** [comment]
For "basis_type==lcao", there are some parameters related to performance:
1. http://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#nb2d
2. http://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#bx-by-bz
3. set OMP_NUM_THREADS>1 to use OpenMP + MPI to accelerate calculation.
