### ISSUE TITLE
Output STRU_NOW.cif during md calculation

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#2642]
### Background

During the calculation of relax, ABACUS would generate a STRU_NOW.cif file, so we could check the structure. But during the calculation of MD, ABACUS wouldn't generate STRU_NOW.cif.

### Describe the solution you'd like

Ouput STRU_NOW.cif during MD simulation.

**Comment by YuLiu98** [comment]
Actually, the output of extra files will increase the time cost of md calculations, whose steps are much more than those of relaxations, so the effect is obvious. 

If you want to visualize the structures, it is better to transform `OUT.${suffix}/STRU/STRU_MD_${step}` to cif files by [dpdata](https://github.com/deepmodeling/dpdata).
