### ISSUE TITLE
how to execute unit tests on my PC

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#2648]
### Details

I'd like to execute unit tests on my PC after compilation, how should do it?

**Comment by hongriTianqi** [comment]
@Satinelamp @mohanchen 
(1) choose the cmake tool to build with `-D BUILD_TESTING=ON` flag. You can find built testing programs under build/source/<module_name>/test.
(2) run `cmake --install build` before run unit tests to install necessary supporting files for the unit tests.
(3) check all the installed unit tests by using the command `ctest -N` under the build directory.
(4) run a specific test by `ctest -R testname -V`
(5) runt tddft unit tests by `ctest -R tddft -V`

**Comment by Satinelamp** [comment]
@Satinelamp Hi, thanks for your question. As it is often very complex to set up the environment for running and test a large package, we have provided docker environment for users' convenience. Please consult here: https://github.com/deepmodeling/abacus-develop/pkgs/container/abacus-development-kit
