### ISSUE TITLE
About which energy is used by final_etot

### ISSUE THREAD

**Issue by scott-5** [deepmodeling/abacus-develop#2650]
### Background

I found that the recent version 3.2.5 can output E_KS(sigma->0). As we know, if smearing is used, then the output energy contains entropy (even if its effect is sometimes negligible), so we should use E_KS(sigma->0) as final energy. But I found that the keyword 'final etot' still uses E_KohnSham. 

### Describe the solution you'd like

I think it is more appropriate to use E_KS(sigma->0) as final_etot.

**Comment by mohanchen** [comment]
Thanks, we will consider your kind suggestion.

**Comment by Chentao168** [comment]
Thanks. We have checked the output of VASP and QE. Currently, QE does not support output of E_KS(sigma->0), while in VASP, "free energy TOTEN" represents the total energy of the system, which corresponds to E_KohnSham in ABACUS. In DP-GEN, the read total energy of the VASP is also reading this total energy, not E_KS(sigma->0).

**Comment by scott-5** [comment]
Thank you for the reminder. If so, I don't think it needs to be modified. The modification may cause a lot of trouble with energy extraction in other software packages. If someone needs E_KS(sigma->0), just extract by self.
