### ISSUE TITLE
I want to combine sparse matrix related data and functions into one class

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#2652]
### Describe Current Status and Possible Solution

At present, the sparse matrix related data (HR_sparse, SR_sparse ...) are written inside the class LCAO_matrix, while most of their methods are inside the class LCAO_hamilt. This will cause difficulty if we want to use the new HContainer to generate sparse matrix quantities.

**Comment by mohanchen** [comment]
Both of the two classes may be deleted in the future.
