### ISSUE TITLE
Optimizing Parameter Settings for HSE Functional SCF Calculation

### ISSUE THREAD

**Issue by shuo1118** [deepmodeling/abacus-develop#2654]
### Details

I am currently running SCF calculations with HSE functional on a c64_m128_cpu machine type. The system contains 64 hydrogen atoms.  The computation has been running for over 20 hours, yet the second iteration of the SCF process has only executed two steps. I suspect that there might be issues with my parameter settings, leading to this inefficiency.

I am in dire need of your assistance. If possible, I would appreciate it if you could check whether my parameter settings are inappropriate, or offer any other suggestions and methods for enhancing computational efficiency.

Thank you very much for your assistance and guidance.
[out.zip](https://github.com/deepmodeling/abacus-develop/files/11797853/out.zip)

**Comment by pxlxingliang** [comment]
@PeizeLin Could you help check it?

**Comment by PeizeLin** [comment]
Theoretically, the calculation time of exact-exchange is approximately proportional to the ninth power of the orbital radius cutoff.
The hydrogen Rcut used in the  [out.zip](https://github.com/deepmodeling/abacus-develop/files/11797853/out.zip) is 9 a.u., while the default value is 6 a.u. in [ABACUS official website](https://abacus.ustc.edu.cn/pseudo/list.htm). Thus, the calculation time difference is about 38 times.
It is strongly recommended to reduce Rcut as much as possible without causing significant errors.
