### ISSUE TITLE
Cannot continue the AIMD calculation with DPKS

### ISSUE THREAD

**Issue by iduygnay** [deepmodeling/abacus-develop#2661]
### Describe the bug

The issue is when I turn on the md_restart 1 (since it was out of memory before, I had to continue the calculation), it is reported that I cannot find the orbit files for descriptors. 

I am attaching the file of the AIMD example with DPKS. I've tried if I turn off the DPKS, it works. If I turn off the md_restart, it also works. 
[continue.zip](https://github.com/deepmodeling/abacus-develop/files/11815096/continue.zip)

**Comment by YuLiu98** [comment]
I have submitted PR #2670 to fix this issue. 

As a temporary solution, you can add a part to the file `OUT.ABACUS/STRU/STRU_MD_780`, just like `STRU`:
```
NUMERICAL_DESCRIPTOR
jle.orb
```

**Comment by iduygnay** [comment]
I tried to add the numerical descriptor lines in the STRU file but still did not work.

**Comment by iduygnay** [comment]
[new.tar.zip](https://github.com/deepmodeling/abacus-develop/files/11859040/new.tar.zip)
Maybe you can try this

**Comment by YuLiu98** [comment]
> I tried to add the numerical descriptor lines in the STRU file but still did not work.

In the case you provided. you should modify `OUT.ABACUS/STRU/STRU_MD_1695` as follows:

```
ATOMIC_SPECIES
C 12.011 C_ONCV_PBE-1.0.upf upf201
N 14.007 N_ONCV_PBE-1.0.upf upf201
H 1.008 H_ONCV_PBE-1.0.upf upf201
Pb 207.2 Pb_ONCV_PBE-1.0.upf upf201
I 126.904 I_ONCV_PBE-1.0.upf upf201

NUMERICAL_ORBITAL
C_gga_9au_100Ry_2s2p1d.orb
N_gga_9au_100Ry_2s2p1d.orb
H_gga_9au_100Ry_2s1p.orb
Pb_gga_9au_100Ry_2s2p2d1f.orb
I_gga_9au_100Ry_2s2p2d1f.orb

NUMERICAL_DESCRIPTOR
jle.orb

LATTICE_CONSTANT
1.889716

LATTICE_VECTORS
12.724 0 0 #latvec1
0 12.724 0 #latvec2
0 0 12.724 #latvec3
```

Between the part `NUMERICAL_ORBITAL` and `LATTICE_CONSTANT`, please add a part of `NUMERICAL_DESCRIPTOR`, just like the format of `STRU` in your working directory.

**Comment by iduygnay** [comment]
<img width="578" alt="image" src="https://github.com/deepmodeling/abacus-develop/assets/109792836/0384ed72-a016-47c1-b79b-177b1e0ca801">

This is the input STRU file



<img width="673" alt="image" src="https://github.com/deepmodeling/abacus-develop/assets/109792836/2e7c23bc-f35e-45d2-a386-e29a45dcecbf">

This is the output

I think I've done what you mentioned, but it still did not work. 
These files I've sent you before in the new.tar. 
If I did anything wrong just let me know, please. 
Thank you so much!

**Comment by YuLiu98** [comment]
> <img alt="image" width="578" src="https://user-images.githubusercontent.com/109792836/248558885-0384ed72-a016-47c1-b79b-177b1e0ca801.png">
> This is the input STRU file
> 
> <img alt="image" width="673" src="https://user-images.githubusercontent.com/109792836/248558964-2e7c23bc-f35e-45d2-a386-e29a45dcecbf.png">
> This is the output
> 
> I think I've done what you mentioned, but it still did not work. These files I've sent you before in the new.tar. If I did anything wrong just let me know, please. Thank you so much!

You should modify **`OUT.ABACUS/STRU/STRU_MD_1695`** in the new case, which is output latest in the directory `OUT.ABACUS/STRU/`.

And you must **NOT** move the modified file!

**Comment by iduygnay** [comment]
Now it works, sorry for the misunderstanding. 
Thank you so much!
