### ISSUE TITLE
how to backtrace the call stack when debugging

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#2663]
### Details

Is there any function in ABACUS to let me backtrace the call stack? Like `backtrace`？
I‘d like to trace the call stack when the following `if` statement is true.

https://github.com/deepmodeling/abacus-develop/blob/5a4b1b58cebadd7e67100b5249029adce7291697/source/module_elecstate/module_charge/charge.cpp#L181-L185

**Comment by caic99** [comment]
@Satinelamp Please try gdb: mark a breakpoint and run abacus.

**Comment by Satinelamp** [comment]
@caic99 
I found some simple tutorials for using `gdb`, but they are all about debugging a simple script, so I could use the following command to set a breakpoint, but what if I am debugging a large program like `ABACUS`, there are many files and `namespaces`, is there any detailed tutorials of using `gdb` to debug large programs?

Here is the tutorial I found on the internet:
https://blog.csdn.net/u013257767/article/details/126524691
```
设置断点
break n （简写b n）:在第n行处设置断点
（可以带上代码路径和代码名称： b OAGUPDATE.cpp:578）
b fn1 if a＞b：条件断点设置
break func（break缩写为b）：在函数func()的入口处设置断点，如：break cb_button
delete 断点号n：删除第n个断点
disable 断点号n：暂停第n个断点
enable 断点号n：开启第n个断点
clear 行号n：清除第n行的断点
info b （info breakpoints） ：显示当前程序的断点设置情况
delete breakpoints：清除所有断点：
```

I tried to use `break n`, here is the what I got:
```
(gdb) break 10
Breakpoint 1 at 0x4149cc: /usr/include/c++/7/bits/stl_vector.h:10. (54 locations)
(gdb) break 1000
Breakpoint 2 at 0x97be18: file /usr/include/c++/7.5.0/bits/stl_vector.h, line 1000.
(gdb) break 10000
No line 10000 in the current file.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 3 (10000) pending.
(gdb) break 5000
No line 5000 in the current file.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 4 (5000) pending.
(gdb)
```

**Comment by Satinelamp** [comment]
I found that I could use `vs code` to do debugging: 
https://opencoursehub.cs.sfu.ca/bfraser/grav-cms/cmpt433/guides/files/DebuggingGuide.pdf

**Comment by caic99** [comment]
> I found that I could use `vs code` to do debugging: https://opencoursehub.cs.sfu.ca/bfraser/grav-cms/cmpt433/guides/files/DebuggingGuide.pdf

@Satinelamp I would suggest you giving it a try [debugging with VS code](https://code.visualstudio.com/docs/cpp/cpp-debug). This is a more interactive way.
