### ISSUE TITLE
error for test case 201_NO_KP_DJ_CF_CS_GaAs : scalapack solver error!

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#267]
**Describe the bug**
1. example : tests/integral/201_NO_KP_DJ_CF_CS_GaAs
2. error output:
 
    =   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
    =   PID 23602 RUNNING AT 4ef21388ba08
    =   EXIT CODE: 4
    =   CLEANING UP REMAINING PROCESSES
    =   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
    =====================================
    YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Illegal instruction (signal 4)
    This typically refers to a problem with your application.
    Please see the FAQ page for debugging suggestions
3. environment: 
     * GNU in docker
     * branch : deepmodeling/abacus-develop/reconstruction
     * commit: c60615bc9b76d47eba7461d2bf2d6e767b3bcb1e
4. more information:
     *  change "ks_solver" setup in INPUT file:
     *  ks_solver = genelpa: error in any cores;
     *  ks_solver = scalapack_gvx : correct in 1 core, error in multi cores
     *  ks_solver = hpseps: correct in both 1core and multi cores

5. bug track:
     * stop in function: void Pdiag_Double::diago_complex_begin()
     * stop in line: source/src_pdiag/pdiag_double.cpp: 1055
     * stop in function:: pzSolveEigen2()
     * stop in function:: elpa_solve_evp_complex_2stage()
     * this is a interface in Elpa.

**Comment by caic99** [comment]
My reimplement:
Warning: Lapack routine DSTEDC failed, info=       17, Trying DSTEQR!

**Comment by dyzheng** [comment]
> My reimplement:
> Warning: Lapack routine DSTEDC failed, info= 17, Trying DSTEQR!

Did that warning caused this error? using genelpa?

**Comment by caic99** [comment]
## Intel MKL ('17) + GCC 8.3.1

### scalapack_gvx
<=2 processes: not converging (related to another issue)
\>2 processes: terminate called after throwing an instance of 'std::runtime_error'
  what():  info=2. /home/caichun/abacus-develop/source/src_pdiag/pdiag_double.cpp line 1171

> if (MOD(INFO/2,2).NE.0),then eigenvectors corresponding to one or more clusters of eigenvalues could not be reorthogonalized because of insufficient workspace. The indices of the clusters are stored in the array ICLUSTR. [more info](https://www.hpc.nec/documents/sdk/SDK_NLC/UsersGuide/man/pzhegvx.html
)


### genelpa
\>2 processes: converged.

### hpseps
Converged.

## Scalapack + GCC 7.5.0

### genelpa
1 process (invoke w/ `abacus`): Converged.
multi processes (invoke w/ `mpirun -n N abacus`): 
N=1:

>  Input  warning : gamma_only_local algorithm is not used.
 AUTO_SET lcao_ecut to 20
 In SCAN_BEGIN, can't find: NUMERICAL_DESCRIPTOR block.
 In SCAN_BEGIN, can't find: LATTICE_PARAMETERS block.
 In SCAN_BEGIN, can't find: <PP_SPIN_ORB> block.
 In SCAN_END, can't find: </PP_SPIN_ORB> block.
 In SCAN_END, can't find: </UPF> block.
 In SCAN_BEGIN, can't find: <PP_SPIN_ORB> block.
 In SCAN_END, can't find: </PP_SPIN_ORB> block.
 In SCAN_END, can't find: </UPF> block.
 AUTO_SET NBANDS to 0
 AUTO_SET NBANDS to 24
 functional  warning : file /home/ubuntu/abacus-develop/source/src_pw/xc_type.cpp line 297 may error 
 functional  warning : file /home/ubuntu/abacus-develop/source/src_pw/xc_type.cpp line 297 may error 
                            startmag_type = 1
                       charge from rho_at = 15
                         charge should be = 15
                       charge from rho_at = 13
                         charge should be = 13
 Warning: negative or imaginary starting charge :  neg = -0.0651382 ima = 0 SPIN = 0
 SETUP ATOMIC RHO FOR SPIN 1
                 Electron number from rho = 28
           total electron number from rho = 28
                                should be = 28
                 charge before normalized = 28
                  charge after normalized = 28
      Processor           Atom
              1             23
              2             22
 LCAO ALGORITHM ------------- ELEC=   1--------------------------------
 CHECK UPDATE INPUT INFORMATION
 sum_rho=0
 Charge::renormalize_rho  warning : Can't find even an electron!


N>=2:
> Warning: Lapack routine DSTEDC failed, info=       17, Trying DSTEQR!

### scalapack_gvx
1 process: correct
2+ processes: 
> what():  info=2. /home/ubuntu/abacus-develop/source/src_pdiag/pdiag_double.cpp line 1169
 
### hpseps
Correct.

**Comment by dyzheng** [comment]
another error reported for this test case :
* multi core result differ from one core's with hpseps ks_solver in docker environment.
* Only multi K points would have this difference, when gamma_only result is same between one core and multi cores.

**Comment by dyzheng** [comment]
There would be 3.0e-5 eV error in total energy between one core and 4 core results in newly version using hpseps solver.
In version e1c0d395e178f125d13ee2fc069ee2ac17e232d6 in 2021/05/21, there is no deviation using genelpa solver, and still have error 4.0e-5 eV using hpseps solver.

**Comment by dyzheng** [comment]
#383 solved error with ELPA, using ELPA2021 is ok for both intel oneAPI and GNU compiler

**Comment by dyzheng** [comment]
Now, only scalapack solver is error. Set parameter: "ks_solver  scalapack_gvx" and use multi cores calculation, the error will occurs in dyzheng's environment and will not occurs in PeizeLin's environment.

**Comment by dyzheng** [comment]
scalapack_gvx for k is correct now, but still has problem for gamma_only
