### ISSUE TITLE
why does the serial code run on all cores?

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#2682]
### Details

I am trying to understand the multi-processing method in ABACUS, but it seems even the serial code in ABACUS would run on multicores.
For example, this issue https://github.com/deepmodeling/abacus-develop/issues/2208.
Even the code in [module_io/write_HS_R.cpp](https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_io/write_HS_R.cpp)  doesn't use any `MPI` function, if I use more than 32 cores, there would be an error like:
```
 Initial plane wave basis and FFT box
 ---------------------------------------------------------
 -------------------------------------------
 SELF-CONSISTENT : 
 -------------------------------------------
 START CHARGE      : atomic
 DONE(12.1845    SEC) : INIT SCF
 ITER   TMAG      AMAG      ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
 GE1    -2.40e-13 1.82e+00  -9.289292e+03  0.000000e+00   1.071e-01  1.137e+01  
 GE2    2.11e-15  1.37e+00  -9.246873e+03  4.241861e+01   6.120e-02  1.098e+01  
abacus: /work/home/ac1mwf7gdw/software/abacus-develop/source/module_base/matrix.h:50: const double &ModuleBase::matrix::operator()(int, int) const: Assertion `ir<nr' failed.
abacus: /work/home/ac1mwf7gdw/software/abacus-develop/source/module_base/matrix.h:50: const double &ModuleBase::matrix::operator()(int, int) const: Assertion `ir<nr' failed.
abacus: /work/home/ac1mwf7gdw/software/abacus-develop/source/module_base/matrix.h:50: const double &ModuleBase::matrix::operator()(int, int) const: Assertion `ir<nr' failed.
abacus: /work/home/ac1mwf7gdw/software/abacus-develop/source/module_base/matrix.h:50: const double &ModuleBase::matrix::operator()(int, int) const: Assertion `ir<nr' failed.
GlobalV::CURRENT_SPIN = 0
v_eff.nr = 2
v_eff.nc = 2
srun: error: h08r2n07: tasks 32-35: Aborted
srun: launch/slurm: _step_signal: Terminating StepId=4862711.0
slurmstepd: error: *** STEP 4862711.0 ON h08r2n07 CANCELLED AT 2023-06-28T17:08:51 ***
srun: error: h08r2n07: tasks 0-31: Terminated
srun: Force Terminated StepId=4862711.0
```
So it seems the code of `module_io/write_HS_R.cpp` is running on all cores, and besides in four of the cores (32-35), the value of `ir` is NOT the same as the other cores.

My question is: does this mean all the code in abacus, even the serial code is running on all cores?

**Comment by caic99** [comment]
@Satinelamp
MPI routines are designed for communications. If you use `mpirun` to launch the binary, same codes are executed on each process.
I personally recommend you [this website](https://mpitutorial.com/) for MPI basics.
