### ISSUE TITLE
Abnormal numerical oscillation in tail of numerical orbital

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#2695]
### Describe the bug

Yesterday I found by chance there are oscillations in tail region of numerical orbitals (downloaded from ABACUS official website http://abacus.ustc.edu.cn/_upload/tpl/0c/d8/3288/template3288/download/Libs/SG15-Version1p0__AllOrbitals-Version2p0.zip). But the oscillation seems less significant if cutoff radius is large.
![Al_gga_6au_100Ry_4s4p1d orb_p](https://github.com/deepmodeling/abacus-develop/assets/67682086/74c9bab2-9615-4e8e-9930-fda107b4fa22)
Al_gga_6au_100Ry_4s4p1d.orb
![Al_gga_7au_100Ry_4s4p1d orb_p](https://github.com/deepmodeling/abacus-develop/assets/67682086/3dd36524-808d-4810-b39d-a93069dedcbd)
Al_gga_7au_100Ry_4s4p1d.orb
![Al_gga_8au_100Ry_4s4p1d orb_p](https://github.com/deepmodeling/abacus-develop/assets/67682086/30f5a0c2-b770-4fcf-8978-1661535efddc)
Al_gga_8au_100Ry_4s4p1d.orb
![Al_gga_9au_100Ry_4s4p1d orb_p](https://github.com/deepmodeling/abacus-develop/assets/67682086/24c5e00a-ea6b-48b0-b57f-c2b26f7441b4)
Al_gga_9au_100Ry_4s4p1d.orb
![Al_gga_10au_100Ry_4s4p1d orb_p](https://github.com/deepmodeling/abacus-develop/assets/67682086/bb413278-d482-48eb-8092-86ca40b42cdd)
Al_gga_10au_100Ry_4s4p1d.orb

### Expected behavior

In principle the radial function is from linear combination of truncated spherical Bessel functions, and this kind of functions do not have so many oscillations. Present behavior of radial function is hard to understand and will more or less impact precision of calculations. More importantly, a correct evaluation of density, not merely the value but also its first derivative (gradient) and the second derivative, will be of great importance for the use of GGA and meta-GGA functionals.

### To Reproduce

Numerical orbitals can be downloaded from ABACUS official website, the link is [here](http://abacus.ustc.edu.cn/_upload/tpl/0c/d8/3288/template3288/download/Libs/SG15-Version1p0__AllOrbitals-Version2p0.zip).

Here I provide a simple parser for plotting numerical orbitals file (.orb), the returned dictionary has keys named as sublayer of atomic orbitals, such as 's', 'p', 'd', etc. Also a realspace grid is saved (corresponding key is 'r'). For sublayers, their corresponding values are lists, each list contains at least one 1-d array storing radial function data.
(execute ABACUS_orb_parser.py)

Taking second derivative of radial function, oscillation can be seen more clearly, but using FFT as filter cannot remove it out, due to mixing of "vibrational" modes. But it may be reasonable to be considered that including the second derivative during numerical orbitals fitting procedure.

[issue_reproduce.zip](https://github.com/deepmodeling/abacus-develop/files/11938684/issue_reproduce.zip)

### Environment

Windows

**Comment by wenfei-li** [comment]
we have also noticed that many orbitals have oscilliatory radial part; it might require a systematic re-examination of the orbital generation scheme

**Comment by hongriTianqi** [comment]
- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by kirk0830** [comment]
seems I have found the reason:
https://ucoyxk075n.feishu.cn/docx/MAgOdvYP0ok0uNxB6q4cyjIxnhe

**Comment by hongriTianqi** [comment]
This issue will not update codes in ABACUS. So @kirk0830 closed it here.
