### ISSUE TITLE
Multiple copies of same pieces of code

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#2701]
### Describe Current Status and Possible Solution

It is noticed that there are multiple copies of the same pieces of code, such as pseudopot_cell_vnl::getvnl, setup_structure_factor, and so on. Presumably this has something to do with the rewritting and GPU adaptation of PW module, where the old code is no longer used but still kept.

**Comment by baixiaokuang** [comment]
@denghuilu Hello, any comments for this issue?

**Comment by denghuilu** [comment]
In the new implementation, an additional template function `template<typename FPTYPE, typename Device> pseudopot_cell_vnl::getvnl` was introduced outside the original function `pseudopot_cell_vnl::getvnl` to accommodate our multi-precision, multi-device computation implementation. The purpose of retaining the original function interface was to avoid modifying the calls that do not involve GPU/mixed-precision computations.
