### ISSUE TITLE
Symmetry error: Number of cells and number of vectors did not agree.

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#2702]
### Describe the bug

I try to run below example, but get the error:
```
 MAKE THE DIR         : OUT.ABACUS/
 UNIFORM GRID DIM     : 45 * 45 * 128
 UNIFORM GRID DIM(BIG): 45 * 45 * 128
 DONE(0.0383607  SEC) : SETUP UNITCELL
 ERROR: Number of cells and number of vectors did not agree.Try to change symmetry_prec in INPUT.

  |CLASS_NAME---------|NAME---------------|TIME(Sec)-----|CALLS----|AVG------|PER%-------
 ----------------------------------------------------------------------------------------
 See output information in : OUT.ABACUS/
```

The structure is 6 As atoms,
![image](https://github.com/deepmodeling/abacus-develop/assets/91927439/99c58ce9-1bbc-48f7-ac2e-c2f0b8ec12a5)

The error message is confused to me, and I don't know where the structure is abnormal and how much symmetry_prec should be changed to?

[As.zip](https://github.com/deepmodeling/abacus-develop/files/11964847/As.zip)

**Comment by pxlxingliang** [comment]
Hi, @maki49, I have re-run this example by using latest codes, and I did not suffer the previous error, but there is another error:
```
 Wed Jul 12 10:06:31 2023
 MAKE THE DIR         : OUT.ABACUS/
 UNIFORM GRID DIM     : 45 * 45 * 128
 UNIFORM GRID DIM(BIG): 45 * 45 * 128
 DONE(0.0714073  SEC) : SETUP UNITCELL
abacus: /root/abacus-develop/source/module_cell/module_symmetry/symmetry.cpp:2047: void ModuleSymmetry::Symmetry::hermite_normal_form(const ModuleBase::Matrix3 &, ModuleBase::Matrix3 &, ModuleBase::Matrix3 &) const: Assertion `equal(check_zeros(i, j), 0)' failed.
Aborted (core dumped)
```

**Comment by maki49** [comment]
> Hi, @maki49, I have re-run this example by using latest codes, and I did not suffer the previous error, but there is another error:

It's still a numerical error leading to the failure. I didn't encounter this problem in my last fix because I set `symmetry_prec` to 3e-5  rather than the default 1e-5 and forgot to change it back. 
In #2720 I use `near_equal` function to loose the error tolerence to 10*`symmetry_prec` (the same criterion as the beginning of this function).
