### ISSUE TITLE
Expecting new functionality

### ISSUE THREAD

**Issue by zc994646659** [deepmodeling/abacus-develop#2703]
### Describe Current Status and Possible Solution

用磁力定理去计算J，有一些开源程序 比如 TB2J的接口，数值轨道算不算局域的基矢，可能能直接求解。

**Comment by dyzheng** [comment]
Thanks for your suggestion, could you describe your requirements in detail?

**Comment by hongriTianqi** [comment]
- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by hongriTianqi** [comment]
We have not get your response for long. If you still have questions, please open it again and make a clear description of your question. Thanks! @zc994646659
