### ISSUE TITLE
Manually stop the calculation and output the results, such as STOPCAR of VASP.

### ISSUE THREAD

**Issue by sgyang345** [deepmodeling/abacus-develop#2708]
### Background

It is usually difficult to converge when calculating large systems, but people do not want to give up this calculation result, hoping that ABACUS will end normally and produce a complete file.

### Describe the solution you'd like

such as STOPCAR of VASP

### Additional Context

https://www.vasp.at/wiki/index.php/STOPCAR

**Comment by hongriTianqi** [comment]
- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.
