### ISSUE TITLE
The links in the docs of vdW correction are  404 Not Found.

### ISSUE THREAD

**Issue by Chentao168** [deepmodeling/abacus-develop#2711]
### Describe the bug

In the docs of [vdW correction](http://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#vdw-correction), the links in vdw_s6, vdw_s8, vdw_a1, and vdw_a2 are 404 Not Found.

![image](https://github.com/deepmodeling/abacus-develop/assets/76426373/dc3105c7-3fd8-4470-9dad-bb18fa57c398)

**Comment by caic99** [comment]
Should be https://www.chemiebn.uni-bonn.de/pctc/mulliken-center/software/dft-d3/dft-d3
