### ISSUE TITLE
When using SCAN in PW, enabling kpar parallelization can cause an error in pressure

### ISSUE THREAD

**Issue by Chentao168** [deepmodeling/abacus-develop#2719]
### Describe the bug

The pressure is correct when kpar parallelization (scan-no-kpar) is not enabled.
```
$ grep PRESSURE scan-*/OUT*/run*
scan-kpar/OUT.Sn-alpha-2-2/running_scf.log: TOTAL-PRESSURE: +784.204126 KBAR
scan-no-kpar/OUT.Sn-alpha-2-2/running_scf.log: TOTAL-PRESSURE: +8.949799 KBAR
```

### To Reproduce

[20230711-bug.zip](https://github.com/deepmodeling/abacus-develop/files/12013040/20230711-bug.zip)

### Environment

Intel MKL with ABACUS v3.2.5

**Comment by wenfei-li** [comment]
It might be that i didn't implement mGGA with kpar. I suppose I should add a warning_quit if these two are used simultaneously.
