### ISSUE TITLE
Automatic adjustment of 'symmetry' from 1 to 0

### ISSUE THREAD

**Issue by scott-5** [deepmodeling/abacus-develop#2723]
### Background

Sometimes when doing cell-relax calculations, several situations will occur like that:
```
 Refine the lattice parameters in STRU or use a different`symmetry_prec`. 
 CHECK IN FILE : OUT.ABACUS/warning.log
```
or
```
ERROR: Symmetry cannot be kept due to the lost of accuracy with atom position during cell-relax.
Please set `symmetry` to 0 or -1 in INPUT file.  
```
So we need to adjust `symmetry_prec` or `symmetry` manually. Especially when I need to lots of DFT calculations, for example in CALYPSO, in order to avoid manual intervention, I have to set symmetry to 0. But it costs more time.
[running_cell-relax.zip](https://github.com/deepmodeling/abacus-develop/files/12030882/running_cell-relax.zip)

### Describe the solution you'd like

If ABACUS can add an option that automatically `symmetry` switches from 1 to 0 when symmetry analysis goes wrong, that will save a lot of resources. Further, it would be better if it implement that when the accuracy is restored, `symmetry` dynamically turns  back to 1.

**Comment by maki49** [comment]
Good idea, seems not hard to implement. I'll have a try. 
Could you please upload the working directories producing these 2 error logs? I will use them as test cases for my implementation.

**Comment by scott-5** [comment]
Sure! 
[case.zip](https://github.com/deepmodeling/abacus-develop/files/12031349/case.zip)

**Comment by maki49** [comment]
@scott-5 There are 2 different kinds of errors: 
1. Error-exit at a too-large `symmetry_prec` (case 2). I've implemented your idea in #2736 , with a pdf file for details and test results.
2. Mismatch of bravis lattice (case 1). It only happens in 1st ion step and gives the same error message as VASP, so I didn't deal with it. Here's a related discussion: https://github.com/deepmodeling/abacus-develop/issues/2592.
    -  If automatically setting symmetry to 0 when mismatch is much more convenient in practice, I'd like to add a new bool parameter `symmetry_autoclose` (default: false) to control whether "error-exit" or "close-symmetry-and-continue" when mismatch, and update corresponding docs and tests in another PR. How do you think of this solution?

**Comment by scott-5** [comment]
@maki49 Thanks first for this pr, in which new algorithm is great.

About the solution for automatically setting symmetry to 0 when mismatch:
In fact, some initial structure is from the last relax-cell (STRU_ION_D) when gradient accuracy calculation. In original implementation, STRU_ION_D with low symmetry accuracy cause mismatch error in the next step beginning. With new `symmetry_prec` implementation, errors about mismatch may be avoided partly. 
But mismatch may still occur when the last step ends with inaccuracy coincidentally. So I think the solution is feasible and robust(not automatically setting symmetry to 0 directly within the program, instead, leave an option `symm_autoclose`).

**Comment by maki49** [comment]
@scott-5 Thanks for your agreement. The next pr is coming soon.
BTW, I've patched up the missing results in the pdf file provided in #2736.

**Comment by scott-5** [comment]
Looking forward to the next pr. And there is a slight problem with figure in Example 2 in patched pdf file: green line seems started with symmetry_prec less than 10-3.

**Comment by maki49** [comment]
> Looking forward to the next pr. And there is a slight problem with figure in Example 2 in patched pdf file: green line seems started with symmetry_prec less than 10-3.

It is because I didn't print the data in the beginning ion step. I'll fix the output in the next pr. 
Here's the log after I fix the output, grep `symmetry_prec` in this log and then you can see it increases to 1.28e-3 in 2nd ion step.
[running_cell-relax-example2-ion1-2.log](https://github.com/deepmodeling/abacus-develop/files/12104708/running_cell-relax-example2-ion1-2.log)

**Comment by maki49** [comment]
@scott-5 The new parameter is named `symmetry_autoclose`  to be consistent with  `symemtry` and `symemtry_prec`.

**Comment by scott-5** [comment]
> > Looking forward to the next pr. And there is a slight problem with figure in Example 2 in patched pdf file: green line seems started with symmetry_prec less than 10-3.
> 
> It is because I didn't print the data in the beginning ion step. I'll fix the output in the next pr. Here's the log after I fix the output, grep `symmetry_prec` in this log and then you can see it increases to 1.28e-3 in 2nd ion step. [running_cell-relax-example2-ion1-2.log](https://github.com/deepmodeling/abacus-develop/files/12104708/running_cell-relax-example2-ion1-2.log)

Got it.


> @scott-5 The new parameter is named `symmetry_autoclose` to be consistent with `symemtry` and `symemtry_prec`.

It is cool.
