### ISSUE TITLE
DOS plotting issue

### ISSUE THREAD

**Issue by cty07** [deepmodeling/abacus-develop#2724]
### Describe the bug

![image](https://github.com/deepmodeling/abacus-develop/assets/93380472/86b53a4c-6b61-4ffe-b2a0-d95105e59353)

**Comment by Satinelamp** [comment]
could you upload the test file?

**Comment by cty07** [comment]
You mean TDOS?
[TDOS.txt](https://github.com/deepmodeling/abacus-develop/files/12065563/TDOS.txt)
