### ISSUE TITLE
Suggestion on introduction of input parameters nx/y/z and bx/y/z in online documentation

### ISSUE THREAD

**Issue by LiuXiaohui123321** [deepmodeling/abacus-develop#2726]
In the online documentation, introduction of input parameters nx,ny,nz is,
> nx, ny, nz
Type: Integer
Description: If set to a positive number, then the three variables specify the numbers of FFT grid points in x, y, z directions, respectively. If set to 0, the number will be calculated from ecutwfc.
Default: 0

and bx,by,bz is,
> bx, by, bz
Type: Integer
Description: In the matrix operation of grid integral, bx/by/bz grids (in x, y, z directions) are treated as a whole as a matrix element. A different value will affect the calculation speed. The default is 0, which means abacus will automatically calculate these values.
Default: 0

When users set nx,ny,nz manually, but use default value of bx,by,bz, ABACUS will crash with error message,
> ===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 3348301 RUNNING AT cnode62
=   KILLED BY SIGNAL: 8 (Floating point exception)
===================================================================================

...
> [cnode62:3348306:0:3348306] Caught signal 8 (Floating point exception: integer divide by zero)
[cnode62:3348316:0:3348316] Caught signal 8 (Floating point exception: integer divide by zero)
[cnode62:3348317:0:3348317] Caught signal 8 (Floating point exception: integer divide by zero)

So in the online documentation, it's better to  remind users that when setting nx,ny,nz manually, bx,by,bz also need to set to a non-zero value.

**Comment by Satinelamp** [comment]
@LiuXiaohui123321 
I am wondering about the difference between `nx ny nz` and `fftnx fftny fftnz` in the code of ABACUS.

**Comment by kirk0830** [comment]
@Satinelamp 
> @LiuXiaohui123321 I am wondering about the difference between `nx ny nz` and `fftnx fftny fftnz` in the code of ABACUS.

for general cases, `fftnx` = `nx`, `fftny` = `ny` and `fftnz` = `nz`, respectively. For special case like the `gamma_only`, actual G space is reduced by half. You can find relevant information from:
`source/module_basis/module_pw/pw_basis_k.cpp: line 84 - 90`.
`source/module_basis/module_pw/pw_init.cpp: line 225 - 231`.

HTH.

**Comment by hongriTianqi** [comment]
This happens only in LCAO calculation. It happens in
```
void ESolver_FP::Init
{
...
            if (inp.nx * inp.ny * inp.nz == 0)
            this->pw_rho->initgrids(inp.ref_cell_factor * cell.lat0, cell.latvec, inp.ecutrho);
	    else
            this->pw_rho->initgrids(inp.ref_cell_factor * cell.lat0, cell.latvec, inp.nx, inp.ny, inp.nz);
...
}
```
where, if users have set nx, ny, nz, it will go to the second branch, then in the following function:
```
virtual void initgrids(
    const double lat0_in,
    const ModuleBase::Matrix3 latvec_in, // Unitcell lattice vectors
    const int nx_in, int ny_in, int nz_in
    )
{
...
        if(this->nx%this->bx != 0) this->nx += (this->bx - this->nx % this->bx);
        if(this->ny%this->by != 0) this->ny += (this->by - this->ny % this->by);
        if(this->nz%this->bz != 0) this->nz += (this->bz - this->nz % this->bz);
...
}
```
bx, by, bz are now zero, aborting the whole process.
