### ISSUE TITLE
Convergence problem with ks_solver = genelpa

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#273]
**Describe the bug**
I have recently been working on a Li3Sn system. With ks_solver = genelpa, convergence was achieved for gamma point calculation as well as k point sampling with a 2*2*2 mesh. However, k-point mesh 3*3*3 becomes problematic and convergence was not achieved after 100 SCF iterations.
Convergence was achieved for 3*3*3 after switching to ks_solver = hpseps.

**To Reproduce**
Relevant input files are attached, along with the output I got.

**Environment**
- OS: CentOS 7(Core)
- Compiler: Intel Parallel Studio XE 2018
- Optional Dependencies: Intel MKL; FFTW-3.3.4; boost_1_66_0; elpa-2016.05.004

[Li3Sn_333.zip](https://github.com/deepmodeling/abacus-develop/files/6973752/Li3Sn_333.zip)

**Comment by dyzheng** [comment]
From tests, all three solver has same result, this case is hard to convergent.
