### ISSUE TITLE
Add a readme.txt in each folder

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#2730]
### Describe Current Status and Possible Solution

We should have a readme.txt in each folder, to introduce all the files and their purpose. Maybe a flow chart about the call stack is better.

**Comment by hongriTianqi** [comment]
@Satinelamp Thanks for your suggestion. We will not add a README file in each directory. But I choose to add short introduction of each directory in our documentation website. Hope this can solve your issue.

**Comment by hongriTianqi** [comment]
@Satinelamp For understanding the contents of each cpp file, you are referred to the comments inside, or the corresponding unit tests. We also welcome contributions of comments of functions satisfying doxygen formats, as can be seen at http://abacus.deepmodeling.com/en/latest/CONTRIBUTING.html#comment-style-for-documentation
