### ISSUE TITLE
input parameter 'out_wf'

### ISSUE THREAD

**Issue by mohanchen** [deepmodeling/abacus-develop#274]
**Is your feature request related to a problem? Please describe.**
the 'out_wf' parameter controls the output format of wave functions, and we have more than one option.

**Describe the solution you'd like**
Add more options

**Describe alternatives you've considered**

**Additional context**

**Comment by Qianruipku** [comment]
"out_wf" has three options:
0: no output for wave functions
1: Wave functions are stored in text files
2: Wave functions are stored in binary files which need less storage space.
