### ISSUE TITLE
'Unknown PAO type' in reading oncvpsp

### ISSUE THREAD

**Issue by Chentao168** [deepmodeling/abacus-develop#2746]
### Describe the bug

I generated 'Cu_27.upf' with oncvpsp 4.0.1. However, abacus v3.3.0 cannot read it while qe v7.2.0 can read it. The error message is 'Unknown PAO type'. It might be the bug in function 'print_PAOs'.

### To Reproduce

[20230723-bug-PAO.zip](https://github.com/deepmodeling/abacus-develop/files/12137945/20230723-bug-PAO.zip)
ABACUS v3.3.0

### Environment

Intel oneAPI MKL 2022.1

**Comment by hongriTianqi** [comment]
@Chentao168 This is not a bug in function 'print_PAOs'. The error happens because ABACUS has limited the maximum of momentum number to 5 in the function print_PAOs. But `number_of_wfc` is 6 in your generated UPF file.

**Comment by hongriTianqi** [comment]
Do we need to expand the support of `ncpp.nchi` to 6 in pw calculation? @mohanchen
