### ISSUE TITLE
Add autotests for initialization of occupations/velocities in TDDFT

### ISSUE THREAD

**Issue by mohanchen** [deepmodeling/abacus-develop#275]
**Is your feature request related to a problem? Please describe.**
We need autotests to know the inputs of occupations and velocities are correct.

**Describe the solution you'd like**
Yuanbo will provide a few tests to ensure the correctness of TDDFT functions.

**Comment by lyb9812** [comment]
#295

**Comment by lyb9812** [comment]
#295
