### ISSUE TITLE
Reconstruction of the charge mixing module

### ISSUE THREAD

**Issue by mohanchen** [deepmodeling/abacus-develop#2768]
### Describe Current Status and Possible Solution

The charge mixing codes will be reconstructed soon. Following aspects are considered this time:
1. correctness of mixing method name. In previous code the 'pulay' mixing_type is actually implemented as 'broyden', and 'broyden' is itself. This time this will be corrected.
2. implementation of standard Pulay mixing method.
3. feature support. For DFT+U needs mixing of density matrix, other quantities will be possible to mix in the future, while previous code only support mixing of charge density data, there is also another place (module_ri) where mixing of density matrix is implemented, this time the mixing of density matrix will be also supported, the related code in module_ri is also planned to re-organized.
4. heterogeneous programming. The container Tensor is designed for supporting heterogeneous computing. To minimize data exchange between devices, i.e., CPU and GPU, history data will be directly saved in Tensor in device perform computation.

**Comment by hongriTianqi** [comment]
- [x] Identify the specific code file or section with the code quality issue.
- [x] Investigate the issue and determine the root cause.
- [x] Research best practices and potential solutions for the identified issue.
- [x] Refactor the code to improve code quality, following the suggested solution.
- [x] Ensure the refactored code adheres to the project's coding standards.
- [x] Test the refactored code to ensure it functions as expected.
- [x] Update any relevant documentation, if necessary.
- [x] Submit a pull request with the refactored code and a description of the changes made.

**Comment by hongriTianqi** [comment]
@mohanchen @Qianruipku It might help to manage related PR and issues with a project: Refactor charge mixing.

**Comment by PeizeLin** [comment]
@Qianruipku Here is my note for class Mix_Data. Hoping it's useful to you.
[Mix_Data 使用文档.pdf](https://github.com/deepmodeling/abacus-develop/files/12645255/Mix_Data.pdf)

I suggest to divide Mixing into two separate parts. The first part calculates the coefficients, and the second part mixes data (including charge, density matrix, ...) based on coefficients.
Class Mix_Data is used for the second part.

**Comment by dyzheng** [comment]
@Qianruipku Hello, would you like to add some notations for new mixing module?
The default value change should update in this Issue.
The characteristic of new mixing module also should update in this Issue.

**Comment by kirk0830** [comment]
> @Qianruipku Hello, would you like to add some notations for new mixing module? The default value change should update in this Issue. The characteristic of new mixing module also should update in this Issue.

@Qianruipku I have changed description of this issue, could you check if everything describes well?
