### ISSUE TITLE
I can't build ABACUS with -DBUILD_TESTING=1 

### ISSUE THREAD

**Issue by xuan112358** [deepmodeling/abacus-develop#2785]
### Describe the bug

When I tried to build ABACUS with -DBUILD_TESTING=1, I met a mistake. It looks like this:
<img width="1175" alt="image" src="https://github.com/deepmodeling/abacus-develop/assets/64718735/1c354976-9cd3-4665-bbab-bc5768df6dcd">
I will successfully install ABACUS when I build it without -DBUILD_TESTING=1.

### To Reproduce

When configuring , my command is:
cmake -B build -DCMAKE_INSTALL_PREFIX=./ -DELPA_DIR=~/03_library/elpa/elpa-2021.05.002 -DELPA_INCLUDE_DIR=~/03_library/elpa/elpa-2021.05.002/include/elpa-2021.05.002 -DCEREAL_INCLUDE_DIR=~/03_library/cereal/include -DMPI_CXX_COMPILER=mpiicpc  -DCMAKE_CXX_COMPILER=icpc -DBUILD_TESTING=1 -DCMAKE_PREFIX_PATH=~/03_library/libtorch -Dlibnpy_SOURCE_DIR=~/03_library/libnpy-master -DENABLE_DEEPKS=1 -DLibxc_DIR=~/03_library/libxc/libxc-5.2.3 -DENABLE_LIBRI=1

**Comment by WHUweiqingzhou** [comment]
if you enable -DBUILD_TESTING=1, GoogleTest is required. Please check the detail in our documentation-“Adding a unit test” Part (http://abacus.deepmodeling.com/en/latest/CONTRIBUTING.html).  But the error looks like a MKL bug. Anyway, you can try in this way first, and see what happens.

**Comment by hongriTianqi** [comment]
@xuan112358 Please have a try according to @WHUweiqingzhou 's suggestions. And please let us know if you still have problems.

**Comment by xuan112358** [comment]
@WHUweiqingzhou Hello! I checked that I have libgtest_main.a , libgtest.a etc. in my /usr/local/lib directory, so I think I have installed GoogleTest. But when I tried to build ABACUS , the mistake was still the same one.
It may be helpful to mention, by the way, that I haved successfully installed ABACUS v3.1.2,v3.1.3,v3.2.0,v3.2.1 using the same configuring command.

**Comment by WHUweiqingzhou** [comment]
@xuan112358
OK, it appears that the compiler and MKL library files may not be compatible. To ensure compatibility, you can write the following paths into the `.bashrc file` first,
`export PATH=/opt/intel/oneapi/mpi/2022.1.0/bin:$PATH`
`export PATH=/opt/intel/oneapi/mkl/2022.1.0/include:$PATH`
`export PATH=/opt/intel/oneapi/mkl/2022.1.0/lib/intel64:$PATH`
`source /opt/intel/oneapi/setvars.sh`
Then, specify the compiler during configuration,
`CC=mpiicc CXX=mpiicpc cmake -B build ...(your flags)`
Please let us know the result.

**Comment by xuan112358** [comment]
@WHUweiqingzhou 
I have tried the suggestion, but the result was still the same.
But I noted that I don't have /opt/intel/oneapi/mpi/2022.1.0/bin, so I tried what I have, which was /opt/intel/oneapi/mpi/2021.6.0/bin instead. Then I removed "-DMPI_CXX_COMPILER=mpiicpc -DCMAKE_CXX_COMPILER=icpc" in my configuration command, and added CC=mpiicc CXX=mpiicpc in the beginning.
Would these two change make some mistake?

**Comment by WHUweiqingzhou** [comment]
@xuan112358 
My suggestion is to ensure the consistency of the versions of the compiler and library files. I notice your MKL lib is 2022.1.0, therefore your compiler should also be version 2022.1.0. Or you can use MKL lib (2021.6.0). I strongly advise against mixing MKL library files from different versions of the Intel compiler.
If you encounter difficulties compiling in an Intel environment, you can try compiling under GNU, which is simpler and more stable. See Documentation https://github.com/deepmodeling/abacus-develop/blob/develop/Dockerfile.gnu. You can ignore libtorch part if you don't use deepKS.

**Comment by hongriTianqi** [comment]
@xuan112358 Please let us know if the problem has been solved. Thanks!

**Comment by hongriTianqi** [comment]
@xuan112358 This PR will be closed as was opened 2 weeks ago and its status is not updated more. If you still have questions, please open it again.
