### ISSUE TITLE
UnitTest `io_dm_io` fails under Intel Env

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#2792]
### Describe the bug

UnitTest `io_dm_io` fails in Intel Env, and report two related errors:

Error 1: "Attempting to use an MPI routine before initializing MPICH"
Error 2: "  can not match well (1.0e-5): 0.75(readin)  -0.25
                can not match well (1.0e-5): 0.75(readin)  -0.25"

But this UnitTest works under GNU Env.

**Comment by hongriTianqi** [comment]
@WHUweiqingzhou Thanks for pointing the problem. I will look into it.
