### ISSUE TITLE
Scf does not converge when using DFT+U

### ISSUE THREAD

**Issue by Chengqian-Zhang** [deepmodeling/abacus-develop#2799]
### Describe the bug

In Pb9Cu(PO4)6O system, scf converges when not using DFT+U but scf does not converges when using DFT+U(d orbital of Cu). I have tried different settings including 
1.hubbard_u=2.0 4.0 6.0
2.mixing_beta=0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 0.05  0.01  0.001  0.0001
3.smearing_sigma=0.03 0.02 0.0146
but all attempts do not converge

### Expected behavior

Scf can converge when using DFT+U

### To Reproduce

All input and output files:
[PbCuPO.zip](https://github.com/deepmodeling/abacus-develop/files/12269016/PbCuPO.zip)

### Environment

Image: registry.dp.tech/dptech/abacus:3.2.3
Platform: Bohrium

**Comment by wenfei-li** [comment]
https://github.com/deepmodeling/abacus-develop/issues/2639 similar problem

**Comment by wenfei-li** [comment]
This might require the implementation of new mixing algorithms, which is only possible after the refactoring of LCAO code. So this issue will be marked later.

**Comment by WHUweiqingzhou** [comment]
@Chengqian-Zhang,

After [test](https://labs.dp.tech/projects/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-issue-2799-abacustest-v0.3.68-2677ff) by using latest ABACUS after PR #3226, the calculations are still hard to converge with U.
According to the mixing roadmap Issue #3138, this issue calls for the mixing of Hamiltonian/Density Matrix.

**Comment by dyzheng** [comment]
Please pay attention to https://github.com/deepmodeling/abacus-develop/issues/3588 , the new DFT+U method would improve the convergence of SCF calculation.

**Comment by dyzheng** [comment]
You can try the latest version v3.6.0 , this case can converge.
