### ISSUE TITLE
Cannot output charge density DM(k) in the case of multik calculations, I will add it

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#2801]
### Background

Now, ABACUS can only output DM(k) with gamma-only = 1, and DM(R) with gamma-only = 0.
For detail analysis, I will add two functions to output and read DM(k) for multik cases.  

### Describe the solution you'd like

new functions:
write_dmk();
read_dmk();

**Comment by mohanchen** [comment]
OK, I would suggest to use new modules to implement this function.

**Comment by WHUweiqingzhou** [comment]
@mohanchen 
Good idea. I will add a new subdirectory `module_dm` in `module_elecstate/` to store density matrix source files.
