### ISSUE TITLE
COHP calculation part

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#2803]
### Background

reference link: http://bbs.keinsci.com/thread-12149-1-1.html
reference paper: J. Phys. Chem. 1993, 97, 8617-8624

COHP, namely Crystal Orbital Hamiltonian Population, is an efficient way to give the local interaction of a system by using the Hamiltonian calculated by LCAO basis set. In VASP and other PW-basis software, this calculation usually done by LOBSTER to give projection from PW-basis to LCAO-basis

Since ABACUS is based by LCAO basis set, can we implement COHP calculation as a part of software?

### Describe the solution you'd like

COHP calculation can be as a part of band-structure calculation by ABACUS using LCAO basis set
The output of COHP calculation will be likely as DOS calculation

**Comment by mohanchen** [comment]
Thanks, we will look into this. I guess probably we will wait for the reconstruction of LCAO code.

**Comment by hongriTianqi** [comment]
- [x] Review and understand the proposed feature and its importance.
- [x] Research on the existing solutions and relevant research articles/resources.
- [x] Discuss with the team to evaluate the feasibility of implementing the feature.
- [x] Create a design document outlining the proposed solution and implementation details.
- [x] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by kirk0830** [comment]
will fix in #3062

**Comment by mohanchen** [comment]
We will close this issue since no obvious solution can be found in a short time. We always welcome new issues.

**Comment by QuantumMisaka** [comment]
OK, I'll have contact with @kirk0830 about it
