### ISSUE TITLE
Enable Hamiltonian/psi/band training for DeePKS model

### ISSUE THREAD

**Issue by xuan112358** [deepmodeling/abacus-develop#2805]
### Background

The current version of ABACUS can only support training DeePKS model on energy, force, stress, bandgap etc.
But it can't support training on Hamiltonian, as well as its eigenvalues (band) and eigenvectors (psi), which are important for electronic structure properties.

### Describe the solution you'd like

Enable Hamiltonian/psi/band training for DeePKS model

**Comment by hongriTianqi** [comment]
- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.
