### ISSUE TITLE
Thermal Properties Calculation in ABACUS

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#2808]
### Details

ABACUS have the interface with phonopy:
https://abacus.deepmodeling.com/en/latest/advanced/interface/phonopy.html 
But the example in there is only the phonon band-structure calculation, but not include thermal properties calculation
Related parameter can be found in https://phonopy.github.io/phonopy/setting-tags.html#thermal-properties-related-tags

So if I want to use ABACUS to calculate ZPE, Entropy and Free Energy （of adsorbate on a slab）
How can I do setting with phonopy ? Is there any difference between VASP-phonopy workflow?

**Comment by hongriTianqi** [comment]
@QuantumMisaka Thanks for your question. For you information, ABACUS can be combined with phonopy, as well as ShengBTE to calculate thermal conductivities. Information on http://abacus.deepmodeling.com/en/latest/advanced/interface/ShengBTE.html
might help answer your questions. We do not have the hands-on documentation on calculating ZPE by using ABACUS and phonopy. But we welcome any contribution from users like you to contribute if successful trial has been done.

**Comment by hongriTianqi** [comment]
Or, would @Chentao168 like to improve online documentation and help @QuantumMisaka to calculate ZPE using ABACUS + phonopy?

**Comment by Chentao168** [comment]
There is no difference in calculating ZPE, Entropy, and Free Energy (of adsorbate on a slab) using ABACUS compared to the VASP-phonopy workflow. After generating `FORCE_SETS`, you can obtain `thermal_properties.yaml` by using `phonopy -p -t band.conf --abacus`.  Here is an example of the setting parameters in `band.conf`: 
```
ATOM_NAME = Al
DIM = 2 2 2
MESH = 8 8 8
PRIMITIVE_AXES = 0 1/2 1/2  1/2 0 1/2  1/2 1/2 0
BAND= 1 1 1  1/2 1/2 1  3/8 3/8 3/4  0 0 0   1/2 1/2 1/2
BAND_POINTS = 101
BAND_CONNECTION = .TRUE.
TPROP = .TRUE.
TMAX = 2000
TSTEP = 2
```
However, since I am not very familiar with this calculation, I cannot guarantee the reliability of the results. It is recommended that you conduct additional tests.

**Comment by QuantumMisaka** [comment]
@Chentao168 Thanks! I have tried the `band.conf` file, the thermal properties can be calculated, other application is still in need but the workflow can be used.

If I merely want to calculated thermal properties, the setting of band-structure in `band.conf` is no use, this is my `mesh.conf`

```
ATOM_NAME = Al
DIM = 2 2 2
MESH = 31 31 31
TMAX = 2000
TSTEP = 2
```
