### ISSUE TITLE
reconstruction of PW module in order to make it compatible with GPU

### ISSUE THREAD

**Issue by mohanchen** [deepmodeling/abacus-develop#281]
**Is your feature request related to a problem? Please describe.**
We need to have a clear line for PW that is suitable for both CPU, GPU, or even DCU versions.

**Describe the solution you'd like**
Reconstruction of some PW codes.

**Describe alternatives you've considered**

**Additional context**

**Comment by Qianruipku** [comment]
#127 src_pw can compile pw module solely.
#133 
#171 src_pw can be compiled without mpi

**Comment by ddhhss** [comment]
#297 add hpsi function, add_nonlocal function and fix bugs of FFT.

**Comment by Qianruipku** [comment]
#133

**Comment by mohanchen** [comment]
> #297 add hpsi function, add_nonlocal function and fix bugs of FFT.

Excellent, qianrui and I will help to reorganize the code structures regarding the GPU code for pw.

**Comment by mohanchen** [comment]
The PW module has been implemented and tested, the results are sufficiently accurate, at least for the tests provided in the module.
