### ISSUE TITLE
Different FFT grids for plane wave basis and electron density?

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#2812]
### Details

In QE, there are two input parameters : ecutwfc and ecutrho. The former controls the size of plane wave basis, and the latter the real-space grid point for electron density. The reason for having two separate parameter is that sometimes electron density require a denser grid for a good representation, while we can keep a relatively small basis size.
This is especially important for ultrasoft pseudopotential (and possibly PAW), as according to the QE website:

> If there are ultrasoft PP, a larger value than the default is often desirable (ecutrho = 8 to 12 times [ecutwfc](https://www.quantum-espresso.org/Doc/INPUT_PW.html#ecutwfc), typically). PAW datasets can often be used at 4*[ecutwfc](https://www.quantum-espresso.org/Doc/INPUT_PW.html#ecutwfc), but it depends on the shape of augmentation charge: testing is mandatory.
> The use of gradient-corrected functional, especially in cells with vacuum, or for pseudopotential without non-linear core correction, usually requires an higher values of ecutrho to be accurately converged.

(https://www.quantum-espresso.org/Doc/INPUT_PW.html#idm313)

In ABACUS, there is only one input parameter, namely ecutwfc. Ecutrho is always taken to be 4*ecutwfc as ecutrho is not an input variable anymore. Furthermore, the FFT dimensions of plane wave basis set and real-space grid for electron density are forced to be the same:

```
            this->pw_wfc->initgrids(inp.ref_cell_factor * ucell.lat0,
                                    ucell.latvec,
                                    this->pw_rho->nx,
                                    this->pw_rho->ny,
                                    this->pw_rho->nz);
```

The result is that we will always be using the maximum size of PW basis set for a fixed real-space grid. I'm not sure how this will affect the efficiency of PW calculation, but it might be better if we have more flexibility on the choice here.

**Comment by hongriTianqi** [comment]
@Qianruipku Would you please look into this issue?

**Comment by hongriTianqi** [comment]
@wenfei-li Has this issue been solved? If not, what is suggested for improving the performance of ABACUS later? Thank you.
