### ISSUE TITLE
Stress bug of SCAN when using 10 (or more) ncores for planewave parallel

### ISSUE THREAD

**Issue by Qianruipku** [deepmodeling/abacus-develop#2813]
### Describe the bug
We can repeat the bug:
  cd tests/integrate/116_PW_scan_Si2
  set kpar to 1
 mpirun -np 14 abacus
Then the results of stess will be different from `mpirun -np 1`

**Comment by wenfei-li** [comment]
might be relevant to this issue: https://github.com/deepmodeling/abacus-develop/issues/1945

where it is found that FFT introduces numerical discrepancies when running on different number of cores.
