### ISSUE TITLE
Different energy results from QE

### ISSUE THREAD

**Issue by sunml99** [deepmodeling/abacus-develop#2820]
### Details

I calculated the same system using ABACUS (PW basis) and QE, which use the same pseudopotentials and input, but the resulting system energy is inconsistent. The difference is about 0.2~0.4 eV.

Here are the input and output files of the two cases (Pt and Cu slab):
[test-cases.zip](https://github.com/deepmodeling/abacus-develop/files/12322943/test-cases.zip)

**Comment by Zhuxuegang2022** [comment]
I will try to solve this issue.

**Comment by Zhuxuegang2022** [comment]
We repeated your calculations of Cu_slab and the results show that the difference of total energy is more than two orders of magnitude smaller than your proposeds.  
Whatmore we re-check your calculations result of Cu-slab, and found that your difference is much smaller than the difference you proposed. ie. For Cu_slab the total energy of ABACUS is -134152.9022083832824137eV, and the total energy of QE is -9860.05291287 Ry (namely -134152.90219655809686000309968438 eV，For the conversion factor, we refer to the output of ABACUS，such as the runing_scf.log file has the content of " E_KohnSham                 -9860.0529118                -134152.902182" ), The difference is about -0.00001182518555369690031562 eV. We guess your difference may be introduce in the conversion process.
And the difference of Pt_slab of you result is ABACUS-92066.5470982724509668 ev, QE-92066.547102027191020195627eV, diff 0.000003754740053395627472584 eV.
whatmore in the output of QE we get "estimated scf accuracy    <       0.00000212 Ry"  under the line that contain total energy, which means difference energy under 2.88e-5 can be considered the same.

**Comment by sunml99** [comment]
Hi@Zhuxuegang2022, thanks for your reply! The conversion factor indeed causes the differences. When we use the same conversion factor as in ABACUS, the results are the same. 
In addition to energy,  I encountered another problem related to electrostatic potential that I would like you to help me check out. We found that the average electrostatic potential in QE and ABACUS seems not exactly the same in the above examples. The outputs of Pt_slab of ABACUS and QE are the attached ElecStaticPot_AVE  and avg.dat files, respectively. In the QE output, the planar average is the 2nd column as a function of the 1st one.
[ESP_results.zip](https://github.com/deepmodeling/abacus-develop/files/12342616/ESP_results.zip)

**Comment by hongriTianqi** [comment]
@sunml99 If this issue as entitled has been solved. Please close this issue and open a new one for new questions. Sorry for your inconvenience.

**Comment by hongriTianqi** [comment]
@sunml99 Please give a clearer explanation of the new question, for example, what do you mean by "exact"?

**Comment by sunml99** [comment]
> @sunml99 If this issue as entitled has been solved. Please close this issue and open a new one for new questions. Sorry for your inconvenience.

Okay.
