### ISSUE TITLE
Bug: INPUT keyword "out_mat_t" does not work as expected

### ISSUE THREAD

**Issue by jinzx10** [deepmodeling/abacus-develop#2821]
### Describe the bug

Specifying "out_mat_t 1" in INPUT produces data-dHRx/y/z-sparse_SPIN0.csr instead of data-TR.

### Expected behavior

By appending "out_mat_t 1" to INPUT, the calculation should write T(R) to file.

**Comment by jinzx10** [comment]
It seems this bug might result from a wrong order of arguments @hongriTianqi  :

![image](https://github.com/deepmodeling/abacus-develop/assets/26805483/9b7e0576-67da-434f-bb95-a45327f32023)
![image](https://github.com/deepmodeling/abacus-develop/assets/26805483/f922ddea-c4cd-422a-9573-90831bf12032)

**Comment by hongriTianqi** [comment]
@jinzx10 I will solve this.
