### ISSUE TITLE
Include container in Makefile build

### ISSUE THREAD

**Issue by jinzx10** [deepmodeling/abacus-develop#2824]
### Details

I'm working on refactoring two-center integrals where Denghui's container (module_base/module_container) is used to hold the radial table. My recent PR (https://github.com/deepmodeling/abacus-develop/pull/2823) attemps to implement the new two-center integrals. It passes all CMake build tests but fails the "Build with Makefile & Intel compilers" test (I did remenber to append the objects to Makefile.Objects). The error message is as follows:

![image](https://github.com/deepmodeling/abacus-develop/assets/26805483/5d242c94-a9f3-4549-8307-c4d849a0625c)

I find that Makefile build basically compile every source file into an object file and put them all into a "obj" folder. By doing so, source files with duplicate name conflict with each other and early-generated object files would be overwritten by later ones. Currently there are two "memory_op.cpp", one in module_psi/kernels/ and the other in /module_base/module_container/kernels/. The container one overwrites the psi one, thereby causing the linking error.

How do we resolve this? Shall we simply change the file names and prohibit any duplicates in the future, or shall we change the way Makefile works? @denghuilu @caic99

**Comment by denghuilu** [comment]
For the sake of simplifying the changes, I suggest renaming  the file `module_psi/kernels/memory_op.cpp` to `module_psi/kernels/psi_memory_op.cpp`. Also you need to change the related CMakeLists.txt as well.
I'll remove the psi_memory_op.cpp later with the upgraded module_container tensors.
