### ISSUE TITLE
Inconsistent bandgap compared to literature with dipole correction open

### ISSUE THREAD

**Issue by sgyang345** [deepmodeling/abacus-develop#2825]
对于有极化的二维体系，计算能带时需要打开偶极修正
在这里，我计算了双层In2Se3体系
能带结果使用与先前文献结果不同，主要表现为始终存在一个带隙，而先前的文献计算结果是无带隙
我使用的了不同的赝势进行测试，得到的结果均为有带缝隙（无论加不加SOC，结果均有隙）

以下为测试例子
[In2Se3_bilayer.zip](https://github.com/deepmodeling/abacus-develop/files/12330872/In2Se3_bilayer.zip)

**Comment by hongriTianqi** [comment]
@sgyang345 We need more details, where is the VBM, CBM, what's the band gap value for soc and non-soc cases?

**Comment by hongriTianqi** [comment]
@YuLiu98 Would you please follow this issue? Thanks!

**Comment by hongriTianqi** [comment]
@sgyang345 Please use English on GitHub. Thanks.

**Comment by sgyang345** [comment]
Thank you for your reply, all the details are in the file I uploaded earlier, in addition, this is the band structure form VASP.

[VASP_band.zip](https://github.com/deepmodeling/abacus-develop/files/12331266/VASP_band.zip)

**Comment by hongriTianqi** [comment]
@sgyang345 I have checked the band structure results. In my view, the material does not have band gap according to the results you have uploaded. Where do you find the band gap?

The minor split in figure 1 is only a matter of plotting the results, if that's what you mean by bandgap.


<img width="1095" alt="截屏2023-08-14 17 54 37" src="https://github.com/deepmodeling/abacus-develop/assets/18049272/8e63cf70-270f-4e94-accb-d5ca72705147">

**Comment by hongriTianqi** [comment]
@YuLiu98 @sgyang345 I think we need firstly make sure that the the dipole correction methods are consistent between ABACUS and VASP. Is the dipole correction method in ABACUS only used for external electric field, or it can also be used for intrinsic polarized samples like this example of bilayer In2Se3.

**Comment by sgyang345** [comment]
All the parameter settings of ABACUS are in the INPUT I provided, maybe there is a problem with my parameters?
I also tried using openMX, and the results were consistent with VASP.

**Comment by YuLiu98** [comment]
Hi, @sgyang345 @hongriTianqi , dipole correction in ABACUS is consistent with that of QE. You can double check using QE.

Besides, your INPUT parameters are inadequate. The decreased region of the saw-like potential should be put in vacuum. In other words, `efield_pos_max` and `efield_pos_dec` should be updated.

You can refer to the doc for more details:  http://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#electric-field-and-dipole-correction

**Comment by hongriTianqi** [comment]
Hi @sgyang345, does @YuLiu98's suggestion solve your problem?

**Comment by sgyang345** [comment]
As suggested above, ' The decreased region of the saw-like potential should be put in vacuum ', I try to set the parameters as follows but the situation does not change, the band gap still exists as before. 

- efield_flag    =    True
- dip_cor_flag    = True
- efield_dir          =   2
- efield_pos_max  = 0.9
- efield_pos_dec   = 0.1
- efield_amp        =  0
 
How should I set the parameters to get the correct results ?

**Comment by YuLiu98** [comment]
> As suggested above, ' The decreased region of the saw-like potential should be put in vacuum ', I try to set the parameters as follows but the situation does not change, the band gap still exists as before.
> 
> * efield_flag    =    True
> * dip_cor_flag    = True
> * efield_dir          =   2
> * efield_pos_max  = 0.9
> * efield_pos_dec   = 0.1
> * efield_amp        =  0
> 
> How should I set the parameters to get the correct results ?

You can compute the example using PW basis and compare it with QE. In principle, the results of ABACUS PW and QE are the same.

**Comment by sgyang345** [comment]
I used the trilayer In2Se3 as an example to compare the results of ABACUS and QE respectively as shown in the figure below.

Perhaps ABABCUS is not yet perfect for  the calculation of spontaneously polarized systems, and I will temporarily abandon the use of ABABCUS to calculate the polarization system, hoping that developers may be able to systematically test and upgrade the dipole correction function in the future.

Thank you very much for your reply and help!
![Trilayer_In2Se3](https://github.com/deepmodeling/abacus-develop/assets/68679106/5e647dc1-d861-4d07-9b55-9f903f386ed7)

**Comment by YuLiu98** [comment]
I tested your example using ABACUS and QE **without SOC and Vdw correction**. I find  that their all energy components are consistent in the cases **with/without** dipole correction. So the dipole correction is correct in this case, at least.

Of course, I modified some parameters:
1. I closed **symmetry** because it is not the same with QE;
2. I canceled **Vdw correction** because it is unrelated to the dipole correction. If you want it, the related parameters should be consistent with QE;
3. **LATTICE_CONSTANT** was set to be 1.8897270 instead of 1.8897259885789233;
4. I used **ONCV-1.0** pseudopotentials. Also, it is unrelated to the dipole correction.

If you want to test it with SOC and Vdw correction further, more parameters can be added based on the following examples I tested.
[test.tar.gz](https://github.com/deepmodeling/abacus-develop/files/12418726/test.tar.gz)

**Comment by sgyang345** [comment]
Thank you for your reply!

I considered the SOC effect for the example, and the result is still quite different from VASP **(the band structure of VASP has no band gap, no matter whether the SOC effect is considered or not, and ABACUS always has a band gap)**.

I guess this may not be a problem with the method, but with the pseudopotential **(I have tested many different pseudopotentials of QE, and the results are basically the same).** Because the results of QE are also different from VASP.

So one should first consider whether the accuracy of the result is acceptable when you want to use the QE's pseudopotential to calculate the intrinsic polarization system with ABACUS.

I think my problem has been solved, thank you!

**Comment by hongriTianqi** [comment]
Thanks for @sgyang345 ! We learn from this issue that ABACUS needs more tests on computing spontaneously polarized systems using dipole correction method and different combinations of pseudo potentials. Perhaps the current PAW project can help solve this issue completely in future.
