### ISSUE TITLE
An error is reported in the nscf step, when using lcao basis to calculate the wannier function.

### ISSUE THREAD

**Issue by shiruosong** [deepmodeling/abacus-develop#2830]
### Describe the bug

When I calculate the Maximum Localized Wannier Function (MLWF) using ABACUS, I got an error in the nscf step. But if I just change the basis_type from lcao to pw, it works fine. Even if I use the provided examples (interface_wannier90), as long as I change the basis_type to lcao, an error will be reported. So there may be a problem with the lcao basis.

The error is listed below: 

NONSELF-CONSISTENT : 
 -------------------------------------------
 START CHARGE      : file
 NON-SELF CONSISTENT CALCULATIONS
abacus: /abacus-develop/source/module_psi/psi.cpp:156: void psi::Psi<T, Device>::resize(int, int, int) [with T = std::complex<double>; Device = psi::DEVICE_CPU]: Assertion `nks_in > 0 && nbands_in >= 0 && nbasis_in > 0' failed.
Aborted

### To Reproduce

[test.zip](https://github.com/deepmodeling/abacus-develop/files/12342564/test.zip)

**Comment by hongriTianqi** [comment]
@shiruosong The lcao calculation can be run now, but the results are unstable. Please avoid using lcao basis to output Wannier function now. I have opened another issue to track the progress #2899
