### ISSUE TITLE
I want to design a new class `DensityMatrix`

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#2831]
### Background

In order to facilitate the upcoming refactoring, I will begin to design a new class `DensityMatrix`.  The new class will be located at `/module_elecstate/module_dm/`.
To this end, I will move the recent development related to density matrix to the new class, and do subsequent developments around this class.

### Describe the solution you'd like

A new class `DensityMatrix` at `/module_elecstate/module_dm/`

**Comment by hongriTianqi** [comment]
- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team and stakeholders on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.
