### ISSUE TITLE
Error when using Interface to Wannier90

### ISSUE THREAD

**Issue by ProPLr00** [deepmodeling/abacus-develop#2851]
### Details

Hi developers, I am a beginner at DFT calculations and trying to use ABACUS to run the wannier90 program. I had succeeded in running the examples in the Interface_Wannier90 folder, but when I am trying with my own sample, it keeps coming out with the "Error real_lattice in *.nnkp file". May I check with you about this?

Thanks for your help in advance!

[Internfacetowannier90.zip](https://github.com/deepmodeling/abacus-develop/files/12394565/Internfacetowannier90.zip)

**Comment by hongriTianqi** [comment]
Hi @ProPLr00, thanks for your report, this is one of the focus issue in this week. It will be looked into in this week.

**Comment by hongriTianqi** [comment]
Hi @ProPLr00 You didn't include necessary PP and ORB files for repeating the error.

**Comment by ProPLr00** [comment]
Hi @hongriTianqi, thanks for your reply, but actually I have downloaded the ORB file from http://abacus.ustc.edu.cn/pseudo/list.htm. May I know what you mean by the necessary PP and ORB files? Is it those listed in the STRU file?

[SG15-Version1p0__StandardOrbitals-Version2p0.zip](https://github.com/deepmodeling/abacus-develop/files/12426471/SG15-Version1p0__StandardOrbitals-Version2p0.zip)

**Comment by hongriTianqi** [comment]
Please attach all the PP and ORB files used in your example. Otherwise I need to check the consistency of PP and ORB files to repeat the issue. Thanks!

**Comment by ProPLr00** [comment]
Hereby the PP and ORB files used during the calculation, Thanks

[PP_ORB.zip](https://github.com/deepmodeling/abacus-develop/files/12426695/PP_ORB.zip)

**Comment by hongriTianqi** [comment]
I see the warning of "some atoms are too close", would you please check your STRU? is it really 2.38 Angstrom? Note that in ABACUS, the lattice parameter is in Bohr, which means that your lattices parameter will be 1.889*2.38 Bohr, and it equals to 2.38 Angstrom.

**Comment by hongriTianqi** [comment]
Another checking with your calculation: in scf calculation "INPUT1" you have used basis_type = lcao, but in nscf calculation, you have used default, which means basis_type = pw, this is an illed process.

**Comment by ProPLr00** [comment]
I am so sorry for the wrong file uploaded, as that STRU file was one of the attempts to overcome the Error in the real lattice, nnkp file. The original one is attached as follows: [STRU.zip](https://github.com/deepmodeling/abacus-develop/files/12426918/STRU.zip)

For the INPUT file, note that, I will change them accordingly, Thank you!

**Comment by hongriTianqi** [comment]
The lcao for obtaining Wannier function has a bug now. You may first use pw basis ...

**Comment by hongriTianqi** [comment]
Yes, the calculation should be ok with pw basis. Note that in .nnkp file the lattice parameters are in Angstrom. 4.5072 Angstrom should equal to 4.5072*1.889 Bohr. So in the STRU file, LATTICE_VECTORS should be the same as in .nnkp file if you have set LATTICE_CONSTANT to 1.889725989. If you change it to 2.38, that definitely will induce the above error. @ProPLr00

**Comment by ProPLr00** [comment]
Hi I tried to use the pw-basis during scf and nscf calculation, but the "Error real_lattice in *.nnkp file" still coming out.

[pw_VO2.zip](https://github.com/deepmodeling/abacus-develop/files/12429863/pw_VO2.zip)

**Comment by hongriTianqi** [comment]
Hi @ProPLr00 LATTICE_CONSTANT should be given more effective digits, i.e. 1.889725989, rather than 1.890...

**Comment by ProPLr00** [comment]
Wow, it is working now, really grateful for your help along the way!

**Comment by hongriTianqi** [comment]
This issue helps users along the way, so is a good practice.
