### ISSUE TITLE
I will develop MPI parallel transfer functions for HContainer

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#2852]
### Background

1. Hamiltonian for real space should be transfered from module_gint to operator_lcao.
2. Hamiltonian for gamma point in k-space should be transfered from module_gint to operator_lcao.
3. Density Matrix should be transfered from module_elecstate to module_gint.
4. HContainer should be transfered in read and write functions.

### Describe the solution you'd like

![image](https://github.com/deepmodeling/abacus-develop/assets/49852742/10985541-1f4b-461c-8a25-2396a4fd4003)

```
// class for type B 
template<typename T> 
class HTransPara
{
public:
    HTransPara(HContainer<T>* hr_in);
    
    // receive AtomPair_indexes from the ith rank
    // save to this->ap_indexes[irank]  
    void plan_indexes(int irank);
    
    // pack data in this->hr, and send to ith rank
    void send_data(int irank);
    
    // receive data from ith rank, save them to this->hr
    void receive_data(int irank);
    
private:
    std::vector<std::vector<int>> ap_indexes;
    HContainer<T>* hr = nullptr;    
    
    // calculate Orbital indexes and will be send to irank
    // called in plan_indexes
    std::vector<int> cal_orb_indexes(int irank);
    
    // pack BaseMatrix-values for ith rank
    std::vector<T> pack_data(int irank);
    // unpack BaseMatrix-values from ith rank
    void unpack_data(const std::vector<T>& values);
    
}
```

```
// class for type A
template<typename T> 
class HTransSerial
{
public:
    HTransSerial(HContainer<T>* hr_in);
    
    // receive Orbital_indexes from the ith rank
    // save to this->orb_indexes[irank]  
    void plan_indexes(int irank);
    
    // pack data in this->hr, and send to ith rank
    void send_data(int irank);
    
    // receive data from ith rank, save them to this->hr
    void receive_data(int irank);
    
private:
    std::vector<std::vector<int>> orb_indexes;
    HContainer<T>* hr = nullptr;    
    
    // calculate AtomPair indexes and will be send to irank
    // called in plan_indexes
    std::vector<int> cal_ap_indexes(int irank);
    
    // pack BaseMatrix-values for ith rank
    std::vector<T> pack_data(int irank);
    // unpack BaseMatrix-values from ith rank
    void unpack_data(const std::vector<T>& values);
    
}
```

### Additional Context

I will develop two classes and related functions with TDD(test driven development) first, then I will develop Function1 and Function2 with TDD method.

**Comment by hongriTianqi** [comment]
- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by WHUweiqingzhou** [comment]
This part has been done already. 
The source code can be found at `source/module_hamilt_lcao/module_hcontainer/func_transfer.cpp`
