### ISSUE TITLE
Parameter "fixed_axes" should not contain option "volume", another parameter "fixed_volume" would be better

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#2858]
### Background

http://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#fixed-axes

### Describe the solution you'd like

New setting "fixed_volume true " should replace the setting of "fixed_axes volume".

**Comment by hongriTianqi** [comment]
@dyzheng In my view, if the user don't read the manual on how to set relaxation methods, `fixed_volume` would be misunderstood as well. It will be redundant to add another parameter if changing `calculation` from `cell-relax` to `relax` has already solved the user's problem.

**Comment by hongriTianqi** [comment]
If you add another parameter `fixed_volume`, the it will cause new misleading options. For example, if users use `fixed_axes = a` together with `fixed_volume = true`, they will not get what they want, because these two options cannot be used together, they are mutually exclusive.

**Comment by wenfei-li** [comment]
My opinion is we follow QE whenever possible as we have a smaller chance of making mistakes this way.

**Comment by hongriTianqi** [comment]
- [x] Review and understand the proposed feature and its importance.
- [x] Research on the existing solutions and relevant research articles/resources.
- [x] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team and stakeholders on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by hongriTianqi** [comment]
@dyzheng We have not get response for long on this issue. If you still have questions, please open it again later and with more specific expectations.
