### ISSUE TITLE
temperature bug when using NVT Molecular Dynamics with LCAO 

### ISSUE THREAD

**Issue by Liu-RX** [deepmodeling/abacus-develop#288]
**Describe the bug**
I ran an MD of a single methane (CH4) in a 10\*10\*10 Angstrom^3 box with NVT ensemble. 
The basis is lcao and functional is LDA.
PBE ONCV pseudopotentials are used.

**To Reproduce**
1. Go to '1_lcao_md'
2. View '1.out'
3. Scroll down to line 75

**Expected behavior**
The temperature should not be '-nan'.

[1_lcao_md.zip](https://github.com/deepmodeling/abacus-develop/files/6989549/1_lcao_md.zip)

**Comment by dyzheng** [comment]
Direct run this test would cause this error: 
"NLOCAL < GlobalV::DSIZE"
(caused by ELPA in GNU compiler, using hpseps wouldn't cause this error.)

**Comment by dyzheng** [comment]
As for error mentioned in this issue, it is caused by no atom can move in MD calculation.
It is neccerary to add a warning_quit there to quit program when "nfrozen==ucell.nat"  .
Now, I recommend you to set atom movement label in STRU file.

**Comment by dyzheng** [comment]
#290 fixed bug that "all frozen atoms should not be allowed to run MD"
