### ISSUE TITLE
Constraint to preserve spacegroup symmetry during optimisation

### ISSUE THREAD

**Issue by 1041176461** [deepmodeling/abacus-develop#2901]
### Background

I found that the original symmetry may be broken during structure optimization. Can ABACUS support keeping the spacegroup symmetry unchanged during structure optimization?

### Describe the solution you'd like

I think you can refer to this code https://wiki.fysik.dtu.dk/ase/_modules/ase/spacegroup/symmetrize.html#FixSymmetry. And this function may have to be distinguished from electronic symmetry, because partial code (e.g. HSE) electronic calculation does not support symmetry

**Comment by hongriTianqi** [comment]
- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team and stakeholders on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.
