### ISSUE TITLE
Band decomposed charge densities of any K point

### ISSUE THREAD

**Issue by sgyang345** [deepmodeling/abacus-develop#2905]
### Background

At present, it seems that ABACUS can only calculate the partial (band decomposed) charge density for $\Gamma$ point according to parameter  `calculation = get_pchg`.

### Describe the solution you'd like

It is suggested to increase the function for band decomposed charge densities of **any K point**.

### Additional Context

In addition, I hope to get some help from the developers on how to calculate the partial charge density when the atomic orbitals and coefficients are obtained. 

I 'm developing post-processing functionality for DeepH programs, but I need some help in theory and technology, and I 'll be grateful !

**Comment by hongriTianqi** [comment]
@sgyang345 The Chapter 15 "Localized orbitals: full calculations" in the book of _**Electronic Structure: Basic Theory and Practical Methods**_  of Richard M. Martin is suggested.

**Comment by sgyang345** [comment]
Thank you very much for your help! 

The biggest difficulty I face is how to get the charge density in real space for LCAO. 
As far as I know, a Fourier transform from reciprocal space to real space is needed, and I have no clue about this part. 
Could you please provide me some suggestions? 

Thanks a lot!

**Comment by hongriTianqi** [comment]
@sgyang345 Fourier transform related codes are put in the module_basis/module_pw, maybe you can run the unit tests inside that module to find some clues.

**Comment by hongriTianqi** [comment]
@sgyang345 ABACUS's reference might also help: 
```
Pengfei Li, et al. “Large-scale ab initio simulations based on systematically improvable atomic basis.” Computational Materials Science 112 (2016): 503-517. 
```

**Comment by hongriTianqi** [comment]
- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team and stakeholders on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.
