### ISSUE TITLE
Refactor: I will refactor the planewave based wavefunction initial guess function, `wavefunc`, `WF_atomic` classes

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#2920]
### Describe the Code Quality Issue

To enable `lcao_in_pw` which supports initial guess of `psi` (the planewave representation of wavefunction, dimension always to be [nbands]*[npw], where nbands stands for number of bands to calculate and npw for (maximal) number of planewaves used) with numerical orbitals, the previously deprecated module `basis_type lcao_in_pw` will be re-added into code. However the way of organizing wavefunction allocation and initial guess is confusing, the place where the lcao_in_pw function is insert, can also be re-considered much more carefully this time:
1. the `random` type initial guess is implemented in `WF_atomic` class, while allocation of wavefunction, which is more general in concept, is implemented in `wavefunc`, the derived class of `WF_atomic`.
2. the deprecated `wavefunc_in_pw` was changed to a namespace rather than a class, presently it shows a non-parallel relation with `atomic` and `random` if we consider in aspect of initial guess of `psi` generation.
3. the function `diago_PAO_in_pw_k2()`, which stands for operation "diagonalize pseudo atomic orbital in planewave representation for each k point (2nd version)", now is in `hamilt` namespace, while the `hamilt` includes mainly method imposing `psi`, say `hpsi()` and `spsi()`, also handles operator class. Therefore `hamilt` namespace may be not an appropriate choice for placing this function (and its specializations).
4. the function `LCAO_in_pw_k()`, one belongs to `lcao_in_pw`, needs structure factor to convert atom-specific information (in present context, the numerical orbital) to reciprocal space, but in `WF_atomic` class there is already a pointer `Structure_Factor* psf` declared. Because one should always avoid adding redundant `include` line, to either improve code reuse and reduce code unnecessary dependence. 
5. now we have newly-implemented spherical Bessel transformation (SBT, author @jinzx10), therefore `WF_atomic::init_at_1()` (to do SBT on pseudo atomic wavefunction) and `wavefunc_in_pw::make_table_q()` (on numerical atomic orbitals) can be updated for better numerical accurancy.

Based on considerations and problems stated above, I plan to re-organize initial guess of `psi` related functions.
Functions now will be called in actually calculations are summarized below:
![whiteboard_exported_image](https://github.com/deepmodeling/abacus-develop/assets/67682086/c74bf7e5-4aae-4e5e-9a65-08ae23c7c816)
Tested calculation types are: scf (including soc and dos), md, vcrelax.

**Comment by hongriTianqi** [comment]
- [x] Identify the specific code file or section with the code quality issue.
- [x] Investigate the issue and determine the root cause.
- [x] Research best practices and potential solutions for the identified issue.
- [x] Refactor the code to improve code quality, following the suggested solution.
- [x] Ensure the refactored code adheres to the project's coding standards.
- [x] Test the refactored code to ensure it functions as expected.
- [x] Update any relevant documentation, if necessary.
- [x] Submit a pull request with the refactored code and a description of the changes made.

**Comment by hongriTianqi** [comment]
@kirk0830 Does this belong to the project: Refactor charge mixing?

**Comment by kirk0830** [comment]
> @kirk0830 Does this belong to the project: Refactor charge mixing?

Probably not, 
In aspect of LCAO refactor, this will provide a calibration on results, say keeping `basis_type lcao` and `basis_type pw` use the same starting wfc, so once new algorithm is implemented for LCAO, one can always check if everything is correctly run by comparing results with the one from `basis_type pw`.
In another aspect, the feature itself, actually provides a new way of initial guess generation method of planewave basis wavefunction. I plan to expand options of keyword `init_wfc`, so that user can use `init_wfc nao` to do `basis_type pw` calculation, especially when there is no pseudo-wavefunction defined in pseudopotential file.
Regards,
Yike

**Comment by kirk0830** [comment]
I find the reason why `init_wfc nao` cannot yield expected fast convergence, it is because in psi, each row just contains information of Fourier Transform of one numerical orbital, while in principle every row it should be better a linear combination of those nao(s). So a initial guess of nlocal * nlocal matrix should be given and imposed on nao-initialized psi, thus currently it is just a unity matrix (while not explicitly written)... to get a not-band result. While to have a not-bad initiali guess of nlocal * nlocal matrix, there are several methods, based on symmetry or not... But it is better to have each row orthogonal with all other rows in advance.
In this aspect, what will be the best choice?

**Comment by kirk0830** [comment]
@dyzheng how do you think?🤔

**Comment by kirk0830** [comment]
pull request #2983 linked to this issue

**Comment by kirk0830** [comment]
One pull request has been merged yesterday, while for exx and sdft, classes `wavefunc` and `WF_atomic` have not been fully replaced yet. Presently it seems sdft does not need the new feature but in the future it is better not keep two version of codes in ABACUS.
Temporarily I close it, reopen if needed.
