### ISSUE TITLE
output the wavefunction coefficients in binary files. 

### ISSUE THREAD

**Issue by QG-phy** [deepmodeling/abacus-develop#2922]
### Background

We need the ABACUS to generate the wavefunction coefficients in the LCAO basis, which can be used as labels for future development of new machine learning models like to learn and predict the wave function or charge density.

Therefore, we want to use ABACUS to calculate the wavefunction coefficients. However, when turning on the **out_wfc_lcao tag**， ABACUS will output the wavefunction coefficients into text files, which will consume large amounts of memory on the disk. 

The best way is to add a new switch to choose between binary files or readable text files. 

### Describe the solution you'd like

The best way is to add a new switch to choose between binary files or readable text files. 

Also, when adding this feature, please also supply a post-process code to read these binary files.

**Comment by hongriTianqi** [comment]
- [x] Review and understand the proposed feature and its importance.
- [x] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team and stakeholders on the design document.
- [ ] Develop the feature following the agreed design.
- [x] Write unit tests and integration tests for the feature.
- [x] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [x] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by hongriTianqi** [comment]
This is a repeat of the issue #2455

**Comment by hongriTianqi** [comment]
@QG-phy This issue has been solved. 
out_wfc_lcao = 0: no output
out_wfc_lcao = 1: output text files with .txt file
out_wfc_lcao = 2: output binary files with .dat file

**Comment by hongriTianqi** [comment]
This issue summarized the solved issue, so is a good practice issue. Furthermore, the corresponding PR has updated docs, tests.
