### ISSUE TITLE
Test results changed since #2915

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#2944]
### Describe the bug

The test case: tests/integrate/308_NO_GO_CF_RE

The results are :

- the result in result.ref is -196.3829868232920148 eV;
- the current result is -196.3380349818689581 eV;

### Expected behavior

Please check #2915 by @Satinelamp

### Task list for Issue attackers

- [x] Verify the issue is not a duplicate.
- [x] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by hongriTianqi** [comment]
208 has the same problem

**Comment by Satinelamp** [comment]
PR(https://github.com/deepmodeling/abacus-develop/pull/2977) could fix this issue.
