### ISSUE TITLE
HSE calculation doesn't work using toolchain installation

### ISSUE THREAD

**Issue by zhang-changwei** [deepmodeling/abacus-develop#2968]
### Details

I am tring to install abacus with the toolchain(offline mode). The installation seems to finish successfully. But when I try to run a LCAO HSE calculation, it stucks at the initializing charge step. (PBE calculation runs well)

Here's the environment of my machine.
+ CentOS
+ cmake 3.20.1
+ intel compiler 2021.3.0 + intelmpi 2021.3.0
+ gcc 7.3.0

Here are the packages I put into the toolchain/build/ folder
+ OpenBlas 0.3.23 (I don't know why I need this)
+ cereal 1.3.2 (toolchain cannot recognize it so I just unzip it manally. I have compared the hash, it matches.)
+ elpa 2021.11.002
+ libxc 6.2.2

Here are the packages I put into the deps/ folder
+ LibRI master version
+ LibComm 0.1.0

I slightly modify the `build_abacus_intel.sh` and `toolchain_intel.sh` script. I have put all the modified scripts, log files and test examples in the attachment. Please check it. Thank you.
[abacus.zip](https://github.com/deepmodeling/abacus-develop/files/12644487/abacus.zip)

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by QuantumMisaka** [comment]
Hi @zhang-changwei 
1. toolchain need tools from `OpenBLAS` to recognize your machine arch and CPU type, but gcc is no need ?
2. in you output:
```shell
 dft_functional readin is: hse
 dft_functional in pseudopot file is: PBE
In Pseudopot_upf::read_pseudo_header : dft_functional from INPUT does not match that in pseudopot file
```
Please check your pseudopotential file
3. Your example can be run in my machine, which ABACUS is also installed by toolchain method using intel-toolchain. I noticed that you use `srun` in slurm management system, I guess your submit setting cause problem, please check it

**Comment by zhang-changwei** [comment]
Thank you for your reply. But I still have some confusions.

1.  I need gcc to compile elpa (or it wouldn't be installed successfully)
2. About the output warning, I have used an old version of abacus on another machine, it prints the same warning but runs well. It shouldn't be a serious problem.
3. I don't know how to correctly set the submit script. If it's a link error, it should print the error and exit immediately. But it doesn't give any error message. I don't know what's going wrong.

Here is some link information about elpa
```
ldd elpa2_print_kernels_openmp 
	linux-vdso.so.1 =>  (0x00007ffd1ef61000)
	libelpa_openmp.so.17 => /public/home/wbchu/src/ABACUS/abacus-develop-3.3.4/toolchain/install/elpa-2021.11.002/cpu/lib/libelpa_openmp.so.17 (0x00002b6f7c7bf000)
	libcilkrts.so.5 => /software/compiler/intel/2021.3.0/compiler/lib/intel64_lin/libcilkrts.so.5 (0x00002b6f7ccb7000)
	libstdc++.so.6 => /software/compiler/gcc/7.3.1/lib64/libstdc++.so.6 (0x00002b6f7cef4000)
	libmkl_scalapack_lp64.so.1 => /software/compiler/intel/2021.3.0/mkl/lib/intel64/libmkl_scalapack_lp64.so.1 (0x00002b6f7d27f000)
	libmkl_gf_lp64.so.1 => /software/compiler/intel/2021.3.0/mkl/lib/intel64/libmkl_gf_lp64.so.1 (0x00002b6f7dbaa000)
	libmkl_sequential.so.1 => /software/compiler/intel/2021.3.0/mkl/lib/intel64/libmkl_sequential.so.1 (0x00002b6f7e940000)
	libmkl_core.so.1 => /software/compiler/intel/2021.3.0/mkl/lib/intel64/libmkl_core.so.1 (0x00002b6f8054d000)
	libmkl_blacs_intelmpi_lp64.so.1 => /software/compiler/intel/2021.3.0/mkl/lib/intel64/libmkl_blacs_intelmpi_lp64.so.1 (0x00002b6f84bbc000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b6f84e02000)
	libm.so.6 => /lib64/libm.so.6 (0x00002b6f8501e000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002b6f85320000)
	libmpifort.so.12 => /software/mpi/intelmpi/2021.3.0/lib/libmpifort.so.12 (0x00002b6f85524000)
	libmpi.so.12 => /software/mpi/intelmpi/2021.3.0/lib/release/libmpi.so.12 (0x00002b6f858e2000)
	librt.so.1 => /lib64/librt.so.1 (0x00002b6f86cd9000)
	libiomp5.so => /software/compiler/intel/2021.3.0/compiler/lib/intel64_lin/libiomp5.so (0x00002b6f86ee1000)
	libc.so.6 => /lib64/libc.so.6 (0x00002b6f872f6000)
	/lib64/ld-linux-x86-64.so.2 (0x00002b6f7c59b000)
	libgcc_s.so.1 => /software/compiler/gcc/7.3.1/lib64/libgcc_s.so.1 (0x00002b6f876c4000)
	libifport.so.5 => /software/compiler/intel/2021.3.0/compiler/lib/intel64_lin/libifport.so.5 (0x00002b6f878db000)
	libifcoremt.so.5 => /software/compiler/intel/2021.3.0/compiler/lib/intel64_lin/libifcoremt.so.5 (0x00002b6f7c5f3000)
	libimf.so => /software/compiler/intel/2021.3.0/compiler/lib/intel64_lin/libimf.so (0x00002b6f87b09000)
	libintlc.so.5 => /software/compiler/intel/2021.3.0/compiler/lib/intel64_lin/libintlc.so.5 (0x00002b6f88191000)
	libsvml.so => /software/compiler/intel/2021.3.0/compiler/lib/intel64_lin/libsvml.so (0x00002b6f88484000)
```

**Comment by y1ding** [comment]
I have meet the same troubles. The PBE calculations are quite OK, while the HSE calculation stops at the starts.
I just solve this problem by changing the different mpi/mkl/compile. The following combination seems be OK.
module load compiler/intel/2019.5
module load mathlib/mkl/2019.5
module load mpi/2021.5.1 
module load devtoolset/9

**Comment by y1ding** [comment]
examples/hse/lcao_Si2
running_scf.log_ref  abacus 3.2.3
 --------------------------------------------
 !FINAL_ETOT_IS -214.0648978976642 eV
 --------------------------------------------
ABACUS 3.4.1 !FINAL_ETOT_IS -213.1083681053610 eV
 
ABACUS 3.2.5 !FINAL_ETOT_IS -214.0648978976131 eV

**Comment by y1ding** [comment]
However, the 3.4.1 give the HSE results is quite different from the previous version.

**Comment by QuantumMisaka** [comment]
I consider that this is a problem from LibRI but not ABACUS toolchain ? @PeizeLin

**Comment by PeizeLin** [comment]
> ## examples/hse/lcao_Si2
> running_scf.log_ref abacus 3.2.3
> ## !FINAL_ETOT_IS -214.0648978976642 eV
> ABACUS 3.4.1 !FINAL_ETOT_IS -213.1083681053610 eV
> 
> ABACUS 3.2.5 !FINAL_ETOT_IS -214.0648978976131 eV

From v3.3.4, the new two-center integration significantly affects the calculation results.
You can check whether v3.3.3 and v3.3.4 are the same as above.

**Comment by QuantumMisaka** [comment]
Any update for this issue ? @zhang-changwei 
I'm trying using HSE in ABACUS compiled by toolchain, everything is OK

**Comment by QuantumMisaka** [comment]
I consider the problem lies in the MPI and OMP setting is missed in submit script. If not any update this issue can be closed @hongriTianqi
