### ISSUE TITLE
DFT+U Problem

### ISSUE THREAD

**Issue by iduygnay** [deepmodeling/abacus-develop#2976]
### Details

When I ran AIMD with DFT+U, the organic molecules decomposed. But when I use DFT+DPKS or PBE, they won’t. I’m unsure if the problem still exists when running DFT+U in ABACUS. Or it’s because the system just naturally decomposes when running AIMD with DFT+U. Could you please help look into it?
[+u_issue.zip](https://github.com/deepmodeling/abacus-develop/files/12657582/%2Bu_issue.zip)

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by iduygnay** [comment]
I tried this case in VASP with several different U values, the organic molecules did not decompose, so the issue might caused by abacus.

**Comment by dyzheng** [comment]
Please pay attention to https://github.com/deepmodeling/abacus-develop/issues/3588 , the new DFT+U method would improve the consistency of force field.

**Comment by iduygnay** [comment]
I tried version 3.5.4, but the problem still exists.

**Comment by dyzheng** [comment]
@iduygnay You can try the current version again, or wait for the PR #3837 to get a more efficient version.

I have tried and the screen output showed the energy fluctuation is stable. (before #3837 )
[log_dftu_md.txt](https://github.com/deepmodeling/abacus-develop/files/14785569/log_dftu_md.txt)
