### ISSUE TITLE
DeePKS out label is wrong

### ISSUE THREAD

**Issue by zheyuanhu01** [deepmodeling/abacus-develop#2994]
### Describe the bug

When running abacus to generate labels for training DeePKS by setting:

deepks_scf 0
deepks_bandgap 1
deepks_out_labels 1

Here, use deepks_out_labels=1 to output the labels for training DeePKS. Among the labels, one is the stress label named s_tot.npy and s_base.npy.

We find that the stress results saved in s_base.npy and s_tot.npy are different from the stress information in SCF log. After running, abacus produces a log file called running_scf.log, and the stress info in this file is different from that in s_base.npy or s_tot.npy.

This bug happens in abacus 3.3+, but everything is good in abacus 3.2.1.

### Expected behavior

We expect the DeePKS label in npy files should be the same as that in SCF logging info.

### Environment

Bohrium container
Abacus 3.2.1 is good, but Abacus 3.3.2 will lead to the bug.

### Task list for Issue attackers

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by hongriTianqi** [comment]
@dyzheng Please update

**Comment by dyzheng** [comment]
This Issue is solved by PR #2995 .
