### ISSUE TITLE
Add unittests for the 'orbital' module

### ISSUE THREAD

**Issue by mohanchen** [deepmodeling/abacus-develop#303]
**Is your feature request related to a problem? Please describe.**
The combination of the 'cell' and 'orbital' modules should have the ability to read in atomic positions and generate overlap matrix S.

**Describe the solution you'd like**
Wenfei will try to implement this new feature.

**Comment by wenfei-li** [comment]
A unit test for module_orbital is provided with PR [#320 ](url), which generates the T(R) and S(R) tables from atomic orbital basis set files
Another unit test for module_orbital, module_cell and module_neighour which generates the overlap (S) and kinetic (T) matrices from STRU, KPT and atomic orbital basis set files is provided in PR #347
