### ISSUE TITLE
Results wrong when compiled with Makefile

### ISSUE THREAD

**Issue by PeizeLin** [deepmodeling/abacus-develop#3033]
### Describe the bug

When ABACUS is compiled with Makefile, the results are wrong.
When ABACUS is compiled with cmake, the results are right.

[pbe_3.3.4_cmake.zip](https://github.com/deepmodeling/abacus-develop/files/12728193/pbe_3.3.4_cmake.zip)
[pbe_3.3.4_Makefile.zip](https://github.com/deepmodeling/abacus-develop/files/12728195/pbe_3.3.4_Makefile.zip)

### Environment

- ABACUS: 2023.09.20 - 042bdc80e8c0a
- Red Hat 4.8.5-44
- icpc version 2021.5.0 (gcc version 10.2.0 compatibility)
- OpenMP = ON
- Intel MPI 2021.5.0
- Intel MKL 2021.5.0
- ELPA 2021.11.002 OpenMP

### Task list for Issue attackers

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by caic99** [comment]
Hi @PeizeLin ,
Corresponding changes of #2927 should apply for Makefile.

**Comment by PeizeLin** [comment]
> Hi @PeizeLin , Corresponding changes of #2927 should apply for Makefile.

I've tried to add `OPTS += -fp-model=strict` in Makefile, but it doesn't work.

**Comment by maki49** [comment]
@PeizeLin Does this problem occur only on LCAO basis?

**Comment by PeizeLin** [comment]
> @PeizeLin Does this problem occur only on LCAO basis?

Yes, the result of PW is right.

**Comment by WHUweiqingzhou** [comment]
@PeizeLin, has it been solved?

**Comment by PeizeLin** [comment]
> @PeizeLin, has it been solved?

Yes, it has been solved.
2024.02.04-ec9e42fe is correct.
