### ISSUE TITLE
BUG: The value of the nspin of the H atom causes an error

### ISSUE THREAD

**Issue by ieiue** [deepmodeling/abacus-develop#3043]
### Describe the bug

This example from: https://nb.bohrium.dp.tech/detail/9119461238. When the nspin in the INPUT file is set to 2, there is an error:  "Can't find even an electron!". 

### Expected behavior

I expect a correct result.

### To Reproduce

[All input files.zip](https://github.com/deepmodeling/abacus-develop/files/12777115/All.input.files.zip)
[All result files.zip](https://github.com/deepmodeling/abacus-develop/files/12777116/All.result.files.zip)

### Environment

version: ABACUS v3.2.3
OMP_NUM_THREADS=2 mpirun -n 2 abacus

### Task list for Issue attackers

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@ieiue
According to your input, I make the calculations, but fail to reproduce the error. The job finishes normally. Please try the latest version, and let us know what happen.

**Comment by kirk0830** [comment]
With the newest release, I test the following running conditions:
```
abacus <-serial
OMP_NUM_THREADS=2 mpirun -n 2 abacus <- provided condition
OMP_NUM_THREADS=1 mpirun -np 6 abacus
OMP_NUM_THREADS=2 mpirun -np 6 abacus
```
all of these cases can run smoothly.

**Comment by hongriTianqi** [comment]
@ieiue Could you please check if this issue still exits?

**Comment by kirk0830** [comment]
@ieiue if you have further related questions please re-open this issue,
regards

**Comment by ieiue** [comment]
I can obtain a correct result with the latest version, thank you all. :-)
