### ISSUE TITLE
Orbital labels order does not match spherical harmonics order

### ISSUE THREAD

**Issue by 1041176461** [deepmodeling/abacus-develop#3078]
### Describe the bug

I've recently noticed that the labels for p orbitals, d orbitals, and f orbitals in the 'name_angular' function in ABACUS don't seem to match the order of spherical harmonics in 'ylm.cpp'. For example, in the 'name_angular' function, p orbitals are labeled as px, py, pz, but in 'ylm.cpp,' they should be pz, px, py. There's a similar issue with d and f orbitals. Could you please double-check this for me? Thank you."

### Task list for Issue attackers

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by xuan112358** [comment]
I think you're right.The labels in the 'Name_Angular' in module_base/name_angular.h don't match the order of spherical harmonics in 'ylm.cpp'.  The right order is specified in the doc https://abacus.deepmodeling.com/en/latest/advanced/pp_orb.html#basis-set, which is the same as in 'ylm.cpp'.

**Comment by 1041176461** [comment]
@xuan112358 Thanks! I submit a PR to fix it, could you please help me review it?
