### ISSUE TITLE
Feature: Another implementation of kerker preconditioner in charge mixing

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#3082]
### Background

Now ABACUS realize a kerker preconditioner in `Charge_Mixing::Kerker_screen_real()` & `Charge_Mixing::Kerker_screen_recip()`. This preconditioner is a simple diagonal model for the inverse of the dielectric matrix in metallic systems, and can effectively suppress the oscillations in the low-q components of the charge density:
$$G_q^1=\frac{q^2}{q^2+q_0^2}$$
Current implementation is:
`double filter_g = std::max(gg / (gg + gg0), 0.1);`
which mean low-q (gg / (gg + gg0)->0) contributions is always with a weight of 0.1, and once gg / (gg + gg0)>0.1, corresponding weight would increase as q-vector. Indeed, we can reduce the weight of relatively small q, but this implementation seem to be ineffective in significantly reducing the contribution of extremely low q.
My suggestion is realized kerker in this way:
`double filter_g = std::min(gg / (gg + gg0), A1);`
here, A1 is a variable. Different from previous implementation, current weight of low-q would decrease as q decrease, and we can choose a value to stop this reduction. b.t.w, the second implementation is the one VASP chooses (https://www.vasp.at/wiki/index.php/IMIX#cite_note-kerker:prb:81-1).

Sure, we need to perform many real calculations with various A1 and q0 to check which implementation is better for ABACUS.

### Describe the solution you'd like

Make tests with different q0 and A1 for different systems:
`double filter_g = std::min(gg / (gg + gg0), A1);`

### Task list for Issue attackers

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by LiuXiaohui123321** [comment]
Hi Weiqing! Do you test the different performance between using `double filter_g = std::min()` and `double filter_g = std::max()`? And at last which one is correct?
