### ISSUE TITLE
Bad performance with HSE for calculating magnetic structure.

### ISSUE THREAD

**Issue by zjdai** [deepmodeling/abacus-develop#3103]
### Details

1. abacus version: abacus-developer-3.3.1
2. aims: for calculating 2D and 3D magnetic structure with SOC in HSE functional
3. calculating more than 20 2D magnetic structure, little of them converged in HSE formula
4. trying to change hes parameter 'exx_separate_loop' and charge mixing parameter, but failed
5. following is some 2D& 3D magnetic structure and Input and simple outfile of two examples
[6](url)
[hes_mag.zip](https://github.com/deepmodeling/abacus-develop/files/13160788/hes_mag.zip)

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by hongriTianqi** [comment]
@PeizeLin Could you please comment on this issue?

**Comment by PeizeLin** [comment]
`mixing_gg0>0` will use Pulay-Kerker for Charge Mixing, but Pulay-Kerker is unavailable for Density Matrix Mixing.
There will be Density Matrix Mixing when calculating Hybrid density functional with `exx_loop_seperate=0`, so `mixing_gg0>0` will mismatch Charge Mixing and Density Matrix Mixing.
Setting `mixing_gg0=0` may be beneficial to this.

**Comment by WHUweiqingzhou** [comment]
@zjdai，
Hi, we have implemented new mixing method in PR #3226, could you double-check the new performance? Or you can give the complete input to us, including INPUT, STRU, PP, KPT file together, and corresponding outputs of course.
