### ISSUE TITLE
Energy and force discrepency of PBE between latest version and older version of ABACUS

### ISSUE THREAD

**Issue by xuan112358** [deepmodeling/abacus-develop#3112]
### Describe the bug

When runing ABACUS in water monomer system with pw (PBE), I found big discrepency in energy and force between latest version v3.4.1 and  older version v3.2.1. And I tested v3.3.1, and found that it's the same as v3.4.1, which was also not consistent with v3.2.1.
Then I tested in QE with the same configuration. The RMSE between force of QE and ABACUS v3.2.1 was only 0.0001eV/A. However,the RMSE between force of QE and ABACUS v3.3.1 was 6eV/A ! I think ABACUS v3.2.1 maybe is the right one.

commit Hashid:
v3.4.1:02035931a2ce28dae24439cc848aa640074962a3
v3.3.1:cf1270f4a8476ae64aea6ca001f90e2424666bdd
v3.2.1:9e4fe69874c674a92ce97dba9c0ac5828a17827b

### Expected behavior

Can you tell me is there any wrong with my calculation? 
Or if it's right, why this result happens? 

### To Reproduce

I attach my input and output files of both ABACUS and QE here:
[github_issue_files.zip](https://github.com/deepmodeling/abacus-develop/files/13175702/github_issue_files.zip)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by Qianruipku** [comment]
The result of v3.2.1 and v3.3.1 are the same? Are you sure that the RMSE between force of QE and ABACUS v3.3.1 was 6eV/A since the force is less than 6 eV/A.

**Comment by Qianruipku** [comment]
RMSE is .0006 eV/A. Maybe it is not bug.  The results are different since 2ffa3d4e9f0c31b1f17a899a3630964de02aa141.
Default mixing_type are changed from pulay to broyden

**Comment by Qianruipku** [comment]
The reason is that you compiled abacus with "-DCMAKE_CXX_COMPILER=icpx -DMPI_CXX_COMPILER=mpiicpc". The results are wrong.

**Comment by Qianruipku** [comment]
I will open an new issue.
