### ISSUE TITLE
Electron steps for MPI and omp are not the same

### ISSUE THREAD

**Issue by Shen-Zhen-Xiong** [deepmodeling/abacus-develop#3114]
### Details

For ABACUS version commit (c8fdd3c9046566f93813485fc85a677cd715b178), by using the same input,  through single step time  is only 150 seconds in mpi which is less than 180 seconds in omp, but the total electron steps for mpi about double times than omp, that causes performance degradation.
[issue_omp_mpi_steps.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13187614/issue_omp_mpi_steps.tar.gz)

**Comment by WHUweiqingzhou** [comment]
@Shen-Zhen-Xiong could you try the latest version?

**Comment by Shen-Zhen-Xiong** [comment]
I have test the same examples in ABACUS 3.8.3 version. There are all converge in 21 steps and delta energy is about  4e-06 that is ok. @WHUweiqingzhou @mohanchen
