### ISSUE TITLE
Bug: cell-relax and SCF problem in symmetry=1 for ferromagnetic system 

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#3115]
### Describe the bug

Example from @kirk0830 : CoFe2O4 cubic bulk, which is a ferromagnetic system. 

![image](https://github.com/deepmodeling/abacus-develop/assets/43902832/ccffcd81-f5d8-4369-a914-f0c3804ceed1)
```
ATOMIC_SPECIES
Fe   55.845  Fe_ONCV_PBE-1.0.upf
Co   58.933  Co_ONCV_PBE-1.0.upf
O   15.999  O_ONCV_PBE-1.0.upf

NUMERICAL_ORBITAL
Fe_gga_8au_100Ry_4s2p2d1f.orb
Co_gga_8au_100Ry_4s2p2d1f.orb
O_gga_7au_100Ry_2s2p1d.orb

LATTICE_CONSTANT
1.889726

LATTICE_VECTORS
8.563292000000  0.000000000000  0.000000000000
0.000000000000  8.563292000000  0.000000000000
0.000000000000  0.000000000000  8.563292000000

ATOMIC_POSITIONS
Direct

Fe
2.000
16
0.375000000000  0.875000000000  0.125000000000  1  1  1  
0.375000000000  0.125000000000  0.875000000000  1  1  1  
0.125000000000  0.875000000000  0.375000000000  1  1  1  
0.125000000000  0.125000000000  0.625000000000  1  1  1  
0.375000000000  0.375000000000  0.625000000000  1  1  1  
0.375000000000  0.625000000000  0.375000000000  1  1  1  
0.125000000000  0.375000000000  0.875000000000  1  1  1  
0.125000000000  0.625000000000  0.125000000000  1  1  1  
0.875000000000  0.875000000000  0.625000000000  1  1  1  
0.875000000000  0.125000000000  0.375000000000  1  1  1  
0.625000000000  0.875000000000  0.875000000000  1  1  1  
0.625000000000  0.125000000000  0.125000000000  1  1  1  
0.875000000000  0.375000000000  0.125000000000  1  1  1  
0.875000000000  0.625000000000  0.875000000000  1  1  1  
0.625000000000  0.375000000000  0.375000000000  1  1  1  
0.625000000000  0.625000000000  0.625000000000  1  1  1  

Co
-2.000
8
0.250000000000  0.750000000000  0.750000000000  1  1  1  
0.000000000000  0.000000000000  0.000000000000  1  1  1  
0.250000000000  0.250000000000  0.250000000000  1  1  1  
0.000000000000  0.500000000000  0.500000000000  1  1  1  
0.750000000000  0.750000000000  0.250000000000  1  1  1  
0.500000000000  0.000000000000  0.500000000000  1  1  1  
0.750000000000  0.250000000000  0.750000000000  1  1  1  
0.500000000000  0.500000000000  0.000000000000  1  1  1  

O 
0.000
32
0.135560000000  0.135560000000  0.864440000000  1  1  1  
0.135560000000  0.364440000000  0.635560000000  1  1  1  
0.364440000000  0.135560000000  0.635560000000  1  1  1  
0.364440000000  0.364440000000  0.864440000000  1  1  1  
0.114440000000  0.114440000000  0.385560000000  1  1  1  
0.114440000000  0.885560000000  0.614440000000  1  1  1  
0.385560000000  0.114440000000  0.114440000000  1  1  1  
0.385560000000  0.885560000000  0.885560000000  1  1  1  
0.135560000000  0.635560000000  0.364440000000  1  1  1  
0.135560000000  0.864440000000  0.135560000000  1  1  1  
0.364440000000  0.635560000000  0.135560000000  1  1  1  
0.364440000000  0.864440000000  0.364440000000  1  1  1  
0.114440000000  0.614440000000  0.885560000000  1  1  1  
0.114440000000  0.385560000000  0.114440000000  1  1  1  
0.385560000000  0.614440000000  0.614440000000  1  1  1  
0.385560000000  0.385560000000  0.385560000000  1  1  1  
0.635560000000  0.135560000000  0.364440000000  1  1  1  
0.635560000000  0.364440000000  0.135560000000  1  1  1  
0.864440000000  0.135560000000  0.135560000000  1  1  1  
0.864440000000  0.364440000000  0.364440000000  1  1  1  
0.614440000000  0.114440000000  0.885560000000  1  1  1  
0.614440000000  0.885560000000  0.114440000000  1  1  1  
0.885560000000  0.114440000000  0.614440000000  1  1  1  
0.885560000000  0.885560000000  0.385560000000  1  1  1  
0.635560000000  0.635560000000  0.864440000000  1  1  1  
0.635560000000  0.864440000000  0.635560000000  1  1  1  
0.864440000000  0.635560000000  0.635560000000  1  1  1  
0.864440000000  0.864440000000  0.864440000000  1  1  1  
0.614440000000  0.614440000000  0.385560000000  1  1  1  
0.614440000000  0.385560000000  0.614440000000  1  1  1  
0.885560000000  0.614440000000  0.114440000000  1  1  1  
0.885560000000  0.385560000000  0.885560000000  1  1  1  
```

When use `symmetry 1` to do calculation, the SCF-step will be faster, 
but it is hard for SCF to converge to `drho=1e-6`.
And when run `cell-relax` job, the BFGS optimization will break down.

While use `symmetry 0`, SCF will be slower, but can have a much much better convergence.

### Expected behavior

`symmetry 1` should have likely cell-relax and SCF convergence of `symmetry 0`, and also do quicker SCF calculation.

### To Reproduce

- build ABACUS with intel-oneAPI toolchain
- run by `OMP_NUM_THREADS=4 mpirun -np 16 abacus`

### Environment

- Intel-8358
- Rockylinux 8.5
- ABACUS 3.4.0 (3.4.1 can reproduce)
- Intel-MKL, compiled by icpx

### Additional Context

input and result

[CoFe2O4.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13190822/CoFe2O4.tar.gz)

### Task list for Issue attackers (only for developers)

- [X] Verify the issue is not a duplicate.
- [X] Describe the bug.
- [X] Steps to reproduce.
- [X] Expected behavior.
- [X] Error message.
- [X] Environment details.
- [X] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by maki49** [comment]
The commit you've used is: 923b69739 (Wed Oct 4 08:03:06 2023 +0800), you can try the latest develop branch. I've fixed a bug about magnetic in #3081.

**Comment by QuantumMisaka** [comment]
in ABACUS 3.4.1 (Commit: 77f178d04 (Thu Oct 26 11:32:59 2023 +0800)), the problem above can be reproduced

[3.4.1-result.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13194121/3.4.1-result.tar.gz)

**Comment by maki49** [comment]
I've reproduced the problem. It's not the fault of module symmetry itself.

The problem lies in poor symmetry keeping during the relaxation: the symmetry is broken after the 1st ion step from T_d to C_2v point group (I found it by running scf with `STRU_ION2_D`), but in the 2nd ion step ABACUS doesn't reanalyze the symmetry and still uses T_d to symmetrize the charge density, which possibly leads to non-convergence. 

This will be fixed in the future by implementing #2901 after a refactor of `UnitCell`.

**Comment by hongriTianqi** [comment]
Would you refactor the `module_cell`? @maki49

**Comment by maki49** [comment]
> Would you refactor the `module_cell`? @maki49

Yes. I want to make `Symmetry` a submodule of `UnitCell` to call it in `module_relax`. But now `Symmetry` itself depends on the entire class `UnitCell`. So I want to divide `UnitCell` into some submodules, firstly "lattice", "atoms" and "magnetic" on which `Symmetry` depends (too many parameters to pass if not packed as submodules).

**Comment by maki49** [comment]
It seems #3247 can fix this issue. Here's the log of my local test: 
[CoFe2O4_3247.log](https://github.com/deepmodeling/abacus-develop/files/13445911/CoFe2O4_3247.log)
