### ISSUE TITLE
smearing_method mp meets difficulty in energy convergence for a BCC Fe system 

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#3123]
### Describe the bug

Runned 8 LCAO calculation with different ecutwfc and mp smearing_method. 7 but 1 cannot converge.
<img width="1111" alt="xx" src="https://github.com/deepmodeling/abacus-develop/assets/18049272/cf9cf33a-8b2b-439b-a38a-587fef90d3f6">

### Expected behavior

The mp method is assumed to converge metals easier.

### To Reproduce

[test_ecut.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13213280/test_ecut.tar.gz)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by hongriTianqi** [comment]
This is related to #2290

**Comment by hongriTianqi** [comment]
https://labs.dp.tech/projects/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.53-6a2710

**Comment by ieiue** [comment]
@hongriTianqi ,
I change the kpoints to 10×10×10, and keep other parameters unchanged. Then I make calculations via the ABACUS(v3.5), 8 results are all converged. Before calculations, testing a suitable kpoint which can make calculation converge and efficient is of vital importance. Here are my results.
![image](https://github.com/deepmodeling/abacus-develop/assets/116336560/350bb037-5172-455e-84c8-87f89a5711bf)

**Comment by WHUweiqingzhou** [comment]
since `mp` method is not proved to be as stable as `gauss` in ABACUS, I will close it now.We have plan to make some tests about different smearing method.
