### ISSUE TITLE
total energy does not decrease with ecutwfc in lcao calculation

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#3124]
### Describe the bug

8 lcao calculations were performed for BCC iron. The total energy increase with larger ecutwfc in lcao calculation.

<img width="1078" alt="tt" src="https://github.com/deepmodeling/abacus-develop/assets/18049272/30ba39be-ccb1-4e82-bda6-2836b0fe0442">

The energies:
100:  -3409.938236110985
120: -3,409.938240929675
140: -3,409.9382876517293
160: -3,409.9382864238687
180: -3,409.938284804227
200: -3,409.938103098755
220: -3,409.938241676518
240: -3,409.938240318866

</body>
</html>

</body>
</html>

### Expected behavior

The total energy should decrease with larger ecutwfc in lcao calculation.

### To Reproduce

[test_ecut1.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13213287/test_ecut1.tar.gz)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by YuLiu98** [comment]
This is normal that the total energy do NOT decrease as the ecutwfc increases in LCAO calculations.
