### ISSUE TITLE
may hang randomly when more than one processes.

### ISSUE THREAD

**Issue by PeizeLin** [deepmodeling/abacus-develop#3128]
### Describe the bug

When mpirun with more than one processes, ABACUS may hang at the following codes.
Both of them occur randomly.

The first one is `MPI_Comm_split()` in `Parallel_Global::divide_pools()`  at https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_base/parallel_global.cpp#L376
see [Parallel_Global..divide_pools.zip](https://github.com/deepmodeling/abacus-develop/files/13215570/Parallel_Global.divide_pools.zip)

The second one is `MPI_Cart_create()` in `Parallel_2D::mpi_create_cart()` at https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_basis/module_ao/parallel_2d.cpp#L120
see [Parallel_2D..mpi_create_cart.zip](https://github.com/deepmodeling/abacus-develop/files/13215573/Parallel_2D.mpi_create_cart.zip)

### Environment

- ABACUS: 2023.10.25 - 223e00c042
- Red Hat 4.8.5-44
- icpc version 2021.5.0 (gcc version 10.2.0 compatibility)
- OpenMP = ON
- Intel MPI 2021.5.0
- Intel MKL 2021.5.0
- ELPA 2021.11.002 OpenMP

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by mohanchen** [comment]
We will close this issue since no obvious solution can be found in a short time. We always welcome new issues.
