### ISSUE TITLE
bug of `init_wfc=file` when more than one processes

### ISSUE THREAD

**Issue by PeizeLin** [deepmodeling/abacus-develop#3129]
### Describe the bug

Starting from `init_wfc=file`.
If the number of process = 1, the $\delta\rho$ of the first step is the same as the final step of `out_wfc`.
If the number of process > 1, the $\delta\rho$ of the first step is E-1.

[init_wfc_bug.zip](https://github.com/deepmodeling/abacus-develop/files/13218701/init_wfc_bug.zip)

### Environment

- ABACUS: 2023.10.31 - e2322fa0
- Red Hat 4.8.5-44
- icpc version 2021.5.0 (gcc version 10.2.0 compatibility)
- OpenMP = ON
- Intel MPI 2021.5.0
- Intel MKL 2021.5.0
- ELPA 2021.11.002 OpenMP

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by hongriTianqi** [comment]
This is related to #1235
