### ISSUE TITLE
Total energy increase with smaller smearing_sigma with gauss method

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#3131]
### Describe the bug

8 lcao calculations were performed to test smearing_sigma in gauss method. But the energy increase with decreasing smearing_sigma.
<img width="1318" alt="mm" src="https://github.com/deepmodeling/abacus-develop/assets/18049272/d5f86a0c-cf8a-4261-ab13-084d76f48cd3">

### Expected behavior

Total energy should decrease with smaller smearing_sigma with gauss method.

### To Reproduce

[test_smearing (1).tar.gz](https://github.com/deepmodeling/abacus-develop/files/13222506/test_smearing.1.tar.gz)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by y1ding** [comment]
I meet a similar problem . I have found for the same STRU, the total energy calculated by the gauss and mp method will be quite different.  （ABACUS3.4.1）
For example:
Gauss: FINAL_ETOT_IS -774.8254989127626 eV    MP：FINAL_ETOT_IS -774.8160354661076 eV

STRU：
ATOMIC_SPECIES
Li 6.94 Li_ONCV_PBE-1.0.upf upf201

NUMERICAL_ORBITAL
Li_gga_7au_100Ry_4s1p.orb

LATTICE_CONSTANT
1.88972612584

LATTICE_VECTORS
    4.3117989587    -0.0000000000     0.0000000000 #latvec1
   -0.0000000000     4.3117989587    -0.0000000000 #latvec2
    0.0000000000    -0.0000000000     4.3117989587 #latvec3

ATOMIC_POSITIONS
Direct

Li #label
0 #magnetism
4 #number of atoms
    0.0000000000     0.0000000000     0.0000000000 m  1  1  1
    0.0000000000     0.5000000000     0.5000000000 m  1  1  1
    0.5000000000     0.0000000000     0.5000000000 m  1  1  1
    0.5000000000     0.5000000000     0.0000000000 m  1  1  1

INPUT：
INPUT_PARAMETERS
pseudo_dir            ./
orbital_dir          ./
dft_functional  PBE
esolver_type ksdft
ks_solver genelpa
nspin 1
ecutwfc                 100
scf_thr 1e-7
basis_type lcao
basis_type              lcao
gamma_only              0
smearing_method         mp   
smearing_sigma          0.01
calculation             scf

KPT:
K_POINTS
0
Gamma
12 12 12 0 0 0

**Comment by hongriTianqi** [comment]
The trend is normal as learned from https://arxiv.org/pdf/2212.07988.pdf. Thanks for @jinzx10
