### ISSUE TITLE
a new parameter "nelec_delta" for easily changing the total number of electrons

### ISSUE THREAD

**Issue by xdzhu** [deepmodeling/abacus-develop#3135]
### Background

The current approach for modifying the total number of electrons in abacus using the "nelec" parameter requires users to know the total number of electrons in the system beforehand. This requires users to either calculate it from pseudopotential files or run an SCF calculation to check the log files, which is not very convenient.

### Describe the solution you'd like

It is desired to add a parameter "nelec_delta" as an increment in the total number of electrons, allowing users to set the nelec without the need to know the total electron numbers of the system beforehand.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by xdzhu** [comment]
Have you considered adding this parameter `nelec_delta`? It is quite practical in semiconductor calculations.

**Comment by xdzhu** [comment]
It will be appreciated that if you could add the parameter `nelec_delta` which refers to the variation of the [total electron number `nelec`](https://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#nelec)

**Comment by WHUweiqingzhou** [comment]
@xdzhu, could you change `nelec` directly?

**Comment by xdzhu** [comment]
@WHUweiqingzhou It's ok but not the most simplyfied. When we address the total number of electrons in the system and modify `nelec`, it is necessary to first calculate the total number of electrons either through the pseudopotential files and the number of atoms, or by running a self-consistent field (SCF) calculation once and obtaining the total electron number from the log file, before setting this `nelec` parameter.

This process can be simplified by adjusting the change in the number of electrons, denoted as `nelec_delta`, allowing users to modify it without needing to know the total number of electrons. This is particularly useful in research scenarios involving ions, defects, and doping. For example, if I have set `nelec` and then altered the structure to study the effects of doping/defects, it would change the total number of electrons, necessitating a retest and reset of my `nelec`. Being able to set just the change in the total number of electrons, `nelec_delta` (positive or negative), would be more convenient.

**Comment by WHUweiqingzhou** [comment]
@xdzhu,
I understand you want to change total number of electrons in system, just like `NELECT` in VASP. But a homogeneous background charge corresponding $n_{e}-n_{\delta}$ should be assumed at the same time. Before adding `nelec_delta`, we need to comfirm that:
**If the number of electrons is not compatible with the number derived from the valence and the number of atoms a homogeneous background charge is assumed.**
Has ABACUS realized this already? I notice that some CI test related with this, like `111_PW_*`. Anyone knows it?
If not, this function should be developed first.
