### ISSUE TITLE
Code Quality: not necessary to declare the memory of `rho_core` and `rhog_core` when ncpp.nlcc = 0

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#3137]
### Describe the Code Quality Issue

Now ABACUS allocate memory related with `Charge` in `Charge::allocate(const int& nspin_in)`. However, `rho_core` and `rhog_core` is allocated even when `ncpp.nlcc = 0`:
```cpp
this->rho_core = new double[nrxx]; // core charge in real space
ModuleBase::GlobalFunc::ZEROS(rho_core, nrxx);

this->rhog_core = new std::complex<double>[ngmc]; // reciprocal core charge
ModuleBase::GlobalFunc::ZEROS(rhog_core, ngmc);

ModuleBase::Memory::record("Chg::rho_core", sizeof(double) * nrxx);
ModuleBase::Memory::record("Chg::rhog_core", sizeof(double) * ngmc);
```
Maybe an extra if can mix this bug, f.e.

```cpp
bool bl = false;
for (int it = 0; it<GlobalC::ucell.ntype; it++)
{
  if (GlobalC::ucell.atoms[it].ncpp.nlcc)
  {
      bl = true;
      break;
  }
}
```
Before that, I just want to make clear that would `rho_core` be used in any calculation when `ncpp.nlcc = 0`?

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by YuLiu98** [comment]
Even if `ncpp.nlcc = 0`, `rho_core` are used in functions suah as `XC_Functional::gradcorr()`, `XC_Functional::v_xc()` and so on.
If you want that `rho_core` and `rhog_core` are not allocated when `ncpp.nlcc = 0`, you should add some judgements in these functions.
