### ISSUE TITLE
The energy/force/stress with symmetry on is large with compared with symmetry off

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3141]
### Describe the bug

I performed calculations on a series of structures with symmetry on and off, and found that the deviations in energy/force/stress are quite large. This difference also seems to be larger than the deviations in VASP.

ABACUS:
The maximum deviations of energy is about 3 meV/atom
The maximum deviations of force is about 0.88 eV/A
The maximum deviations of stress is about 84 kbar.

Example | NormalEnd | KPoints | IBZK | PointGroup | PointGroupInSpaceGroup | DeltaEnergy(meV) | DeltaEnergy/atom(meV) | MaxDeltaF(eV/A) | MaxDeltaStress(kbar)
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
\+ | TRUE | 125 | 16 | C_3v | C_4v | 1.58 | 0.4 | 0.38 | 16.94
C_1+ | TRUE | 64 | 18 | C_1 | C_1h | 13.46 | 3.36 | 0.02 | 11.8
C_2v+ | TRUE | 64 | 12 | C_2v | C_3h | 2.07 | 0.35 | 0.11 | 1.34
C_3+C_3v | TRUE | 196 | 55 | C_3 | C_3v | -5.8 | -2.9 | 0.05 | 84.29
C_3+D_3h | TRUE | 196 | 24 | C_3 | D_3h | -0.04 | -0.02 | 0.47 | 0.01
C_3h+ | TRUE | 64 | 12 | C_3h | C_3h | 5.55 | 0.93 | 0.23 | 1.53
C_3v+ | TRUE | 125 | 20 | C_3v | C_3v | 8.06 | 2.01 | 0.88 | 33.27
C_6+C_6 | TRUE | 64 | 20 | C_6 | C_6 | 5.07 | 0.85 | 0.1 | 12.58
D_2h+D_2h | TRUE | 98 | 32 | D_2h | D_2h | 6.51 | 1.3 | 0.01 | 2.09
D_3h+T_d | TRUE | 125 | 10 | D_3h | T_d | -0.05 | -0.02 | 0.33 | 0.01
T_d+O | TRUE | 125 | 10 | T_d | T_d | -0.1 | -0.02 | 0.14 | 2.89

VASP:
Example | NormalEnd | KPoints | IBZK | PointGroup | PointGroupInSpaceGroup | DeltaEnergy(eV) | DeltaEnergy/atom(eV) | MaxDeltaF(eV/A) | MaxDeltaStress(kbar)
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
\+ | FALSE | --- | --- | D_3h | D_3h | --- | --- | --- | ---
C_1+ | FALSE | --- | --- | C_1 | C_1 | --- | --- | --- | ---
C_2v+ | FALSE | --- | --- | C_2v | C_2v | --- | --- | --- | ---
C_3+C_3v | TRUE | 196 | 24 | C_3v | D_3h | -1.25E-05 | -6.24E-06 | 1.60E-05 | 0.01
C_3+D_3h | FALSE | --- | --- | C_2v | D_2h | --- | --- | --- | ---
C_3h+ | FALSE | --- | --- | C_3h | C_3h | --- | --- | --- | ---
C_3v+ | FALSE | --- | --- | D_3h | D_3h | --- | --- | --- | ---
C_6+C_6 | FALSE | --- | --- | C_6 | --- | --- | --- | --- | ---
D_2h+D_2h | TRUE | 98 | 32 | D_2h | --- | -1.65E-05 | -3.29E-06 | 0.01 | 1.08
D_3h+T_d | TRUE | 125 | 10 | T_d | --- | -1.33E-05 | -4.45E-06 | 6.30E-05 | 0.01
T_d+O | TRUE | 125 | 10 | T_d | O_h | 4.60E-07 | 1.15E-07 | 1.60E-05 | 0.04

[sym.zip](https://github.com/deepmodeling/abacus-develop/files/13237187/sym.zip)

### Expected behavior

The deviation of energy/force/stress is smaller than results of VASP.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by pxlxingliang** [comment]
I have chosen more systems (around 100) and tested different symmetry_prec, and compare the results to the results with symmetry closed. (https://labs.dp.tech/projects/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.53-d70a17)

symmetry_prec=1e-6
![all](https://github.com/deepmodeling/abacus-develop/assets/91927439/632daf42-946d-4503-bf36-6a3576fbb280)

symmetry_prec=5e-6
![all](https://github.com/deepmodeling/abacus-develop/assets/91927439/8f94e0f3-8f84-446d-9256-c8656d1a6057)

symmetry_prec=1e-5
![all](https://github.com/deepmodeling/abacus-develop/assets/91927439/ac2f6941-797d-4a56-8390-f1cf54e72c1f)

symmetry_prec=5e-5
![all](https://github.com/deepmodeling/abacus-develop/assets/91927439/864f8dc6-edd2-4677-8e25-eeaa788ee8fd)

symmetry_prec=1e-4
![all](https://github.com/deepmodeling/abacus-develop/assets/91927439/998fcc20-7b9d-4333-88f3-6d91dccf7074)

Different symmetry_prec will induce different symmetric operations, but when setting 1e-6 and 1e-4, the points with significant deviation in the results are the least.

**Comment by pxlxingliang** [comment]
I conducted another test using more configurations. And also compared the results of symmetry turned on with symmetry turned off.

![image](https://github.com/deepmodeling/abacus-develop/assets/91927439/4c773d3e-aa04-4347-a20e-508976de168b)

![a053526880bea7aff75b41be4d27cd45_da19812a-fa4a-4d75-a3bd-42dc9241b8fe](https://github.com/deepmodeling/abacus-develop/assets/91927439/a706eb67-681d-429d-ad48-dfdce2bf7334)

We can find that the results of structure with C_2 point group has a large deviation in force, especially for the cases with point_group_in_space_group is D_2.

Example | KPoints | IBZK | PointGroup | PointGroupInSpaceGroup | DeltaEnergy/atom(meV) | MaxDeltaF(eV/A) | MaxDeltaStress(kbar)
-- | -- | -- | -- | -- | -- | -- | --
C_2+D_2_1 | 486 | 100 | C_2 | D_2 | 9.64E-04 | 1.32 | 0.71
C_2+D_2_3 | 486 | 100 | C_2 | D_2 | -7.32E-04 | 1.28 | 1.56
C_2+D_2_4 | 486 | 100 | C_2 | D_2 | 1.24E-03 | 1.36 | 0.28
C_2+D_2_7 | 486 | 100 | C_2 | D_2 | 2.57E-03 | 1.26 | 0.78
C_2+D_2_9 | 486 | 100 | C_2 | D_2 | 9.64E-04 | 1.32 | 0.71
C_2+D_3_4 | 320 | 93 | C_2 | C_2 | 1.44 | 0.77 | 8.1
C_2+D_3_5 | 486 | 142 | C_2 | C_2 | 4.13 | 0.37 | 11.67
C_3v+C_3v_6 | 507 | 56 | C_3v | C_3v | 4.28E-04 | 0.4 | 7.03E-04


Jobs with symmetry = 0: https://labs.dp.tech/projects/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.53-99e2b8
Jobs with symmetry = 1:  https://labs.dp.tech/projects/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.53-a7c8cb

**Comment by QuantumMisaka** [comment]
Is there any explanation for the physical property difference for symmetry on/off ? Is just modify the default `symmetry_prec` a best way to improve it ?

**Comment by maki49** [comment]
> Is there any explanation for the physical property difference for symmetry on/off ? Is just modify the default `symmetry_prec` a best way to improve it ?

The difference comes from the symmetrization according to different space group (analyzed with different `symmetry_prec`) that directly change the value of charge density, force and stress.
You can regard using a smaller `symmetry_prec` as a compromize between symmetry on and off.

**Comment by pxlxingliang** [comment]
Hi @maki49, although we can reduce the symmetric operations by reducing `symmetry_prec`, and thus reduce the occurrence of large result deviations, we cannot ignore the fact that in some cases, there may be significant deviations in the results of opening symmetry calculations. 

And need your help to find the reason for the large deviation of those special cases. Or we need to find out under what conditions there will be a significant deviation in the results.

Otherwise, for users, turning on symmetric computation is a very dangerous thing, because they cannot confirm whether the calculation result is available or not. In actual calculations, it is impossible for users to perform another calculation that turns off symmetry to verify the correctness of the calculation result of opening symmetry.

**Comment by pxlxingliang** [comment]
Hi @maki49 , I try to use spglib to search the symmetric operations for C_3+C_3v, but there has only unit operation when I set  the symmetry prec to 1e-5/1e-4/1e-3/1e-2. Why ABAUCS/VASP can find other special operations? 

https://dptechnology.feishu.cn/docx/TGzYdX3kAo8NMHxyF3gcjbWInpb

**Comment by maki49** [comment]
> Hi @maki49 , I try to use spglib to search the symmetric operations for C_3+C_3v, but there has only unit operation when I set the symmetry prec to 1e-5/1e-4/1e-3/1e-2. Why ABAUCS/VASP can find other special operations?

It seems that spglib has a bug on searching symmetry operations for Hexagonal lattices.
The following code gives C2h point group, but the right answer should be D_6h: 
```
double lattice[3][3] = { {2.0, 0,0},{-1.0,std::sqrt(3), 0}, {0,0,2} };
double symprec = 1e-5;
char symbol[7];
int types[1] = { 1};
int nat = 1;
double position[1][3] = { {0.0, 0.0, 0.0} };
spg_get_schoenflies(symbol, lattice, position, types, nat, symprec);
```

**Comment by pxlxingliang** [comment]
As PR #3175 modify the default of symmetry_prec to 1e-6, it will increase the frequency of below error:
```
Optimized lattice type of reciprocal lattice cannot match the optimized real lattice. 
It is often because the inaccuracy of lattice parameters in STRU.
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 Possible solutions: 
 1. Refine the lattice parameters in STRU;
 2. Use a different`symmetry_prec`.  
 3. Close symemtry: set `symmetry` to 0 in INPUT. 
 4. Set `symmetry_autoclose` to 1 in INPUT to automatically close symmetry when this error occurs.
 CHECK IN FILE : OUT.ABACUS/warning.log
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

I have done a test, the ratio to suffer this error is increased to about 40%, and this may cause a poor user experience.

symmetry_prec | Symemtry_prec error number (total example number is 200)| Error ratio
-- | -- | --
1e-4 | 13 | 6.5%
1e-5 | 17 | 8.5%
1e-6 | 79 | 39.5%
 
  https://dptechnology.feishu.cn/docx/V3cldgMkAoVobvxBvWsc2bhRnXb

I think we should set the `symmetry_autoclose` to True to run continue with closed symmetry when suffer this error.

**Comment by maki49** [comment]
> I think we should set the `symmetry_autoclose` to True to run continue with closed symmetry when suffer this error.

You can set `symmetry_autoclose` to True in your special test cases. Usually a structure with enough precision will not meet this problem.
