### ISSUE TITLE
get larger force with the relaxed STRU by the same INPUT

### ISSUE THREAD

**Issue by xdzhu** [deepmodeling/abacus-develop#3142]
### Describe the bug

I have obtained the relaxed structure (STRU) from the previous relaxation calculation with a force threshold of 0.05 eV/Å. The output indicates that the "LARGEST GRAD (eV/A)" is 4.876e-02, as reported by abacus in the last ion step.

However, when I rerun the relaxation calculation using the same INPUT file and the previously relaxed STRU_ION_D, I notice that the "LARGEST GRAD (eV/A)" in the first ion step is not 4.876e-02 but 7.746e-02. What could be the cause of this issue?

If you have a solution, please kindly let me know. You can find the relevant input and output files below. Thank you.
[relax-force-issue.zip](https://github.com/deepmodeling/abacus-develop/files/13238600/relax-force-issue.zip)

![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/4366e738-f150-4846-925d-bd846ff25f69)

![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/29f11712-0a45-491e-a29b-b4af25cffec2)

### Expected behavior

same LARGEST GRAD (eV/A) with the same STRU

### To Reproduce

You can check the zip file.

### Environment

abacus v3.4.0

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by QuantumMisaka** [comment]
Your SCF seems to have some problem, which did not converge to a good electronic structure. I have reproduced your problem, after change the INPUT to 
```
INPUT_PARAMETERS
suffix                  ABACUS
ecutwfc                 100         # Rydberg
scf_thr                 1e-6            # Rydberg
basis_type              lcao            
calculation             relax
smearing_method         gauss
smearing_sigma          0.001

#Geometry relaxation
relax_nmax                      100
relax_method                    cg
relax_scale_force       0.2
cal_force                       1
force_thr_ev                    5e-2
cal_stress                      1
stress_thr                      0.5

scf_nmax     100

mixing_type  pulay
mixing_beta  0.4
mixing_gg0   1.5

out_stru     1
```
in the first step:
```
 LARGEST GRAD (eV/A)  : 6.630e-01
 LARGEST GRAD (eV/A)  : 7.657e-01
 LARGEST GRAD (eV/A)  : 2.539e-01
 LARGEST GRAD (eV/A)  : 1.888e-01
 LARGEST GRAD (eV/A)  : 2.723e-01
 LARGEST GRAD (eV/A)  : 1.542e-01
 LARGEST GRAD (eV/A)  : 2.335e-01
 LARGEST GRAD (eV/A)  : 1.911e-01
 LARGEST GRAD (eV/A)  : 2.082e-01
 LARGEST GRAD (eV/A)  : 1.108e-01
 LARGEST GRAD (eV/A)  : 3.285e-01
 LARGEST GRAD (eV/A)  : 2.614e-01
 LARGEST GRAD (eV/A)  : 2.539e-01
 LARGEST GRAD (eV/A)  : 1.451e-01
 LARGEST GRAD (eV/A)  : 1.550e-01
 LARGEST GRAD (eV/A)  : 9.259e-02
 LARGEST GRAD (eV/A)  : 1.222e-01
 LARGEST GRAD (eV/A)  : 8.899e-02
 LARGEST GRAD (eV/A)  : 1.248e-01
 LARGEST GRAD (eV/A)  : 9.285e-02
 LARGEST GRAD (eV/A)  : 7.840e-02
 LARGEST GRAD (eV/A)  : 5.683e-02
 LARGEST GRAD (eV/A)  : 1.233e-01
 LARGEST GRAD (eV/A)  : 1.051e-01
 LARGEST GRAD (eV/A)  : 7.768e-02
 LARGEST GRAD (eV/A)  : 6.964e-02
 LARGEST GRAD (eV/A)  : 8.178e-02
 LARGEST GRAD (eV/A)  : 5.712e-02
 LARGEST GRAD (eV/A)  : 8.229e-02
 LARGEST GRAD (eV/A)  : 8.745e-02
 LARGEST GRAD (eV/A)  : 1.219e-01
 LARGEST GRAD (eV/A)  : 8.147e-02
 LARGEST GRAD (eV/A)  : 6.817e-02
 LARGEST GRAD (eV/A)  : 5.679e-02
 LARGEST GRAD (eV/A)  : 7.345e-02
 LARGEST GRAD (eV/A)  : 7.246e-02
 LARGEST GRAD (eV/A)  : 7.115e-02
 LARGEST GRAD (eV/A)  : 6.240e-02
 LARGEST GRAD (eV/A)  : 5.989e-02
 LARGEST GRAD (eV/A)  : 4.015e-02
```
Which is different from your calculation. 

And when do relax again:
```
 LARGEST GRAD (eV/A)  : 4.096e-02
```
which is converged and have likely the same force of the first relax calculation
