### ISSUE TITLE
Different results when compiling with icpc and icpx.

### ISSUE THREAD

**Issue by Qianruipku** [deepmodeling/abacus-develop#3143]
### Describe the bug

When compiling with "-DCMAKE_CXX_COMPILER=icpx -DMPI_CXX_COMPILER=mpiicpc" and with "-DCMAKE_CXX_COMPILER=icpc -DMPI_CXX_COMPILER=mpiicpc", the results are different.
For icpx: 
![image](https://github.com/deepmodeling/abacus-develop/assets/76200646/73b00e99-d487-4166-b40f-91967ac8caba)
![image](https://github.com/deepmodeling/abacus-develop/assets/76200646/ee53f64d-10d5-4d43-a15d-facc199f8c47)

For icpc:
![image](https://github.com/deepmodeling/abacus-develop/assets/76200646/461197f5-5b83-4b14-a85f-2b763daba677)

example ：
[test.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13240020/test.tar.gz)
The results are the same at commit : 9e4fe69874c674a92ce97dba9c0ac5828a17827b  (v3.2.1)
The results are differents at commit: cf1270f4a8476ae64aea6ca001f90e2424666bdd   (v3.3.1)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by Qianruipku** [comment]
When you are using icpx, Clang 14.0.0 is used and USE_ABACUS_LIBM is turned ON. And the results are wrong.

**Comment by Qianruipku** [comment]
The reason of the bug is icpx is incompatible with ABACUS_LIBM.

**Comment by caic99** [comment]
> When you are using icpx, Clang 14.0.0 is used and USE_ABACUS_LIBM is turned ON. And the results are wrong.

Hi @Qianruipku ,

https://github.com/deepmodeling/abacus-develop/blob/57c903ae6c491db8469e84ff76ba55940398c8d0/CMakeLists.txt#L144-L148

When using `icpx`, the `CMAKE_CXX_COMPILER_ID` evals to be `IntelLLVM`, and the flag should be turned off.

**Comment by Qianruipku** [comment]
@caic99 But in this workstation, CXX id is Clang 14.0.0:
![image](https://github.com/deepmodeling/abacus-develop/assets/76200646/2f8bbb62-8c9b-45ce-a99e-8f4f76291aad)
LIBM will not be turned off

icpx version:
![image](https://github.com/deepmodeling/abacus-develop/assets/76200646/feb9cde5-062a-471f-beee-22c6b223778f)

**Comment by caic99** [comment]
Hi @Qianruipku ,
Would you check the value of variable `CMAKE_CXX_COMPILER_ID`?

**Comment by Qianruipku** [comment]
@caic99  #

> Hi @Qianruipku , Would you check the value of variable `CMAKE_CXX_COMPILER_ID`?

It is empty.

**Comment by caic99** [comment]
> @caic99 #
> 
> > Hi @Qianruipku , Would you check the value of variable `CMAKE_CXX_COMPILER_ID`?
> 
> It is empty.

@Qianruipku That's weird. Maybe it's a bug from CMake. Would you try updating it?

**Comment by Qianruipku** [comment]
> > @caic99 #
> > > Hi @Qianruipku , Would you check the value of variable `CMAKE_CXX_COMPILER_ID`?
> > 
> > 
> > It is empty.
> 
> @Qianruipku That's weird. Maybe it's a bug from CMake. Would you try updating it?

![image](https://github.com/deepmodeling/abacus-develop/assets/76200646/4a83ca0b-6e12-48ba-a386-57cc5dcd5c92)
![image](https://github.com/deepmodeling/abacus-develop/assets/76200646/2d915535-34b1-402d-a0d9-375a8445b535)

**Comment by Qianruipku** [comment]
![image](https://github.com/deepmodeling/abacus-develop/assets/76200646/54d34a0d-3b05-4401-b9f3-611d121e0452)

**Comment by caic99** [comment]
@Qianruipku Maybe your CMake version is too old for detecting Intel compiler. Since we requires CMake > 3.16, I think disabling libm by default would be a good choice.

**Comment by Qianruipku** [comment]
When CMake is updated to 3.20. The problem is solved.
![image](https://github.com/deepmodeling/abacus-develop/assets/76200646/56f7e86c-9b2e-41dc-a6f0-80b4929795d6)

**Comment by Qianruipku** [comment]
For CMake 3.16, it cannot identify icpx correctly. 
I also agree disabling libm by default.

**Comment by WHUweiqingzhou** [comment]
@caic99 and @Qianruipku,
could we close this issue?
