### ISSUE TITLE
Can ABACUS support ELF output?

### ISSUE THREAD

**Issue by 1041176461** [deepmodeling/abacus-develop#3150]
### Background

Electron localization functions (ELF) can be understood as a measure of the effect of the Pauli repulsion and used to do chemical bond analysis. ELF has values between 0 and 1, where 1 corresponds to perfect localization.

### Describe the solution you'd like

Only the charge density, density gradient and kinetic energy density are needed. The output file format is cube.

![image](https://github.com/deepmodeling/abacus-develop/assets/40336950/db75527f-04bb-4f1d-875d-8518016b0aed)

Ref1: https://www.nature.com/articles/371683a0.pdf
Ref2: https://www.lct.jussieu.fr/pagesperso/contrera/zcam2021/Chembondlab-ZCAM2021.pdf

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by QuantumMisaka** [comment]
In my recollection ,ELF can be calculated by Multifwfn? @kirk0830 So this is a request for ABACUS-Multiwfn interface

**Comment by kirk0830** [comment]
> In my recollection ,ELF can be calculated by Multifwfn? @kirk0830 So this is a request for ABACUS-Multiwfn interface

@QuantumMisaka Multiwfn needs MOLDEN file format, while the transformation from numerical atomic orbital or PW to GTO seems not ready for ABACUS, but I indeed have plan to do that.

**Comment by Satinelamp** [comment]
any updates? I'd like to output ELF at each step during AIMD
