### ISSUE TITLE
Question on supported CUDA architectures 

### ISSUE THREAD

**Issue by ignisfatuus28** [deepmodeling/abacus-develop#3158]
### Details

Dear developers and users,

I wonder if abacus supports RTX 40 series gpu, which is no on the supported CUDA architectures list from the official documentation website ?

Sincerely

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by caic99** [comment]
Hi @ignisfatuus28 ,
You can add your desired arch here:
https://github.com/deepmodeling/abacus-develop/blob/d0fe9b5d268fef140710ba1fe2b1da159986a34d/CMakeLists.txt#L236-L243

**Comment by ignisfatuus28** [comment]
Hi @caic99 ,
Thank you for your useful answer. However, I ran the example provided in abacus (abacus-develop/examples/gpu/si16_pw), after building gpu support.
 
Input: 

$ OMP_NUM_THREADS=1 mpirun -np 16 abacus

Output:

 ABACUS v3.4.2

               Atomic-orbital Based Ab-initio Computation at UStc                    

                     Website: http://abacus.ustc.edu.cn/                             
               Documentation: https://abacus.deepmodeling.com/                       
                  Repository: https://github.com/abacusmodeling/abacus-develop       
                              https://github.com/deepmodeling/abacus-develop         
                      Commit: d0fe9b5d2 (Sun Nov 5 22:43:19 2023 +0800)

 Mon Nov  6 20:10:32 2023
 MAKE THE DIR         : OUT.autotest/
 RUNNING WITH DEVICE     : GPU / NVIDIA GeForce RTX 4060 Laptop GPU

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 45563 RUNNING AT KATANA-15
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================

What can I do to solve it?

SIncerely

**Comment by caic99** [comment]
> 
> =   KILLED BY SIGNAL: 9 (Killed)
> 
> ===================================================================================
> 
> 
> 
> What can I do to solve it?
> 
> 
> 
> SIncerely

@ignisfatuus28 this is possibly an out of memory error. Please check http://abacus.deepmodeling.com/en/stable/community/faq.html#failed-jobs

**Comment by ignisfatuus28** [comment]
Hi @caic99 ,

Thank you for answering, problem had been solved.

Sincerely

**Comment by hongriTianqi** [comment]
This issue helps users along the way, so is a good practice.
