### ISSUE TITLE
BAD TERMINATION for abacus (install by conda)

### ISSUE THREAD

**Issue by AroundPeking** [deepmodeling/abacus-develop#3169]
### Describe the bug

The same test, which gave proper results for abacus installed by `cmake`, however, stopped at RPA calculation for abacus installed by `conda`.

Files given here:
[test.zip](https://github.com/deepmodeling/abacus-develop/files/13277545/test.zip)

### To Reproduce

Latest abacus installed by `conda` like
http://abacus.deepmodeling.com/en/latest/quick_start/easy_install.html#install-by-conda

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by mohanchen** [comment]
Did ABACUS support RPA calculations now?

**Comment by caic99** [comment]
Hi @AroundPeking ,
I've tested your case under my environment and it works well. Would you mind reinstalling abacus following the steps [here](https://abacus.deepmodeling.com/en/latest/quick_start/easy_install.html#install-by-conda) and try again? Thanks.

**Comment by AroundPeking** [comment]
Thanks! It works well now. ABACUS can be easily installed by `conda`.
