### ISSUE TITLE
The option to check input parameters only, for example abacus --check-input

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#3180]
### Background

I would like to have a function to check input parameters only for abacus before running calculations. This is for convenience to see if abacus can run before really run the calculation.

### Describe the solution you'd like

For example, add a command option of `abacus --check-input`, just like `abacus --version` to check if the input parameters are consistent with their types or they may cause any other warnings.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by pxlxingliang** [comment]
I think It is better to add the check of STRU.
