### ISSUE TITLE
Use conda to install abacus with gpu

### ISSUE THREAD

**Issue by Chentao168** [deepmodeling/abacus-develop#3195]
### Details

Using conda to install abacus with GPU is missing. The [doc](https://abacus.deepmodeling.com/en/latest/quick_start/easy_install.html) only provides the installation with CPU.

Also, I met the following issues when using conda to install abacus with GPU.

![img_v3_0252_44649ad9-29a1-4269-bafe-f12f54d15a6g](https://github.com/deepmodeling/abacus-develop/assets/76426373/3287cea4-37e9-4b75-b6c7-3977f93b300c)

### Have you read the online manual http://abacus.deepmodeling.com/en/latest/

- [X] Yes, I have read the online manual.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific section of the documentation with the issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Update the documentation to address the issue, following the suggested improvement.
- [ ] Ensure the updated documentation adheres to the project's documentation standards.
- [ ] Test the updated documentation to ensure it is clear and accurate.
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Publish the updated documentation and notify the issue reporter.

**Comment by caic99** [comment]
@Chentao168 
Please refer to the latest [docs](https://abacus.deepmodeling.com/en/latest/quick_start/easy_install.html#install-by-conda).
> Conda will install the GPU-accelerated version of ABACUS if a valid GPU driver is present.

**Comment by caic99** [comment]
To manually select the GPU-supported version, please use `conda install abacus=*=cuda_* -c conda-forge`.
[ref](https://conda-forge.org/docs/maintainer/knowledge_base.html#preferring-a-provider-usually-nompi)

If one want to install it in an environment without CUDA component, set `CONDA_OVERRIDE_CUDA` according to [the virtual package system](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-virtual.html?highlight=cuda#overriding-detected-packages) of conda.
