### ISSUE TITLE
DOJO SR Orbit files

### ISSUE THREAD

**Issue by iduygnay** [deepmodeling/abacus-develop#3204]
### Background

I just noticed that DOJO Pseudopotential only has the FR versions of orbit files on the website https://abacus.ustc.edu.cn/pseudo/list.htm. But as we know, the influence of SOC is tiny in relax/vc-relax calculation. And the results from  FR and SR Pseudopotentials are different. It's necessary to have SR orbit files for DOJO. Especially if I want to analyze the SOC effect in materials. 

### Describe the solution you'd like

I just need element Bi DOJO SR now, but if a whole version is available that would be great. Thank you so much. 

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by kirk0830** [comment]
[DOJO05_NCSR_Bi_issue3204.zip](https://github.com/deepmodeling/abacus-develop/files/13363089/DOJO05_NCSR_Bi_issue3204.zip)
here, you can dive in folders to find SIAB_INPUT, it is the method to generate it.
To generate by yourself, please refer to: https://mcresearch.github.io/abacus-user-guide/abacus-nac3.html
Pseudopotential-numerical orbitals auto-generation-test over systems workflow is under development: https://github.com/deepmodeling/abacus-develop/issues/3159 (#3159 )

**Comment by dyzheng** [comment]
@iduygnay My opinion is you don't need the DOJO-SR orbitals and DOJO-SR pseudopotentials. 

I think you can use the DOJO-FR orbital files with FR pseudopotential files of DOJO to get the correct result of SR.
You can set "lspinorb 1" to calculate the FR result and set "lspinorb 0" to calculate the SR result.

By the way, FR pseudopotential of SG15 without setting of "lspinorb 1" can not get the same result with SR-SG15, but DOJO can get the same result. You can calculate PW basis to verify it.

If you want to adjust effect of SOC, you can modify the parameter of "soc_lambda" to range of [0.0, 1.0], 0.0 refer to SR and 1.0 refer to FR.

**Comment by iduygnay** [comment]
Thank you so much!

**Comment by hongriTianqi** [comment]
This issue shares valuable insights on how to chose pseudopoential file. So I tagged it a good practice.
