### ISSUE TITLE
Too slow to compile parameter_pool.cpp

### ISSUE THREAD

**Issue by Qianruipku** [deepmodeling/abacus-develop#3209]
### Describe the Code Quality Issue

In my workstation, I need 45 s to compile parameter_pool.cpp. And it seems that it is not used in ABACUS yet.
Maybe we should remove it from the Cmakelist.
For comparison, input.cpp only takes 11 s.

CPU: Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by WHUweiqingzhou** [comment]
Second it.
