### ISSUE TITLE
Request: SCAN functional supporting forces and stress evaluation in spin-polarized calculations

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#3215]
### Describe the bug

When using `nspin 2` and `cal_stress 1` in ABACUS calculation, there will be error:
```
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 mgga stress not implemented for polarized case yet
 CHECK IN FILE : OUT.ABACUS/warning.log
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Expected behavior

Stress of cell can be calculated by ABACUS SCAN functional in spin-polarized system

### To Reproduce

INPUT
```
INPUT_PARAMETERS RUNNING ABACUS-DFT

#Parameters (1.General)
suffix                  ABACUS  # suffix of OUTPUT DIR
#ntype                   4   #  number of element
nspin                   2   #  1/2/4 4 for SOC
symmetry                1   #  0/1  1 for open, default
# symmetry_autoclose      1   # if symmetry error: set symmetry to 0
# symmetry_prec           1e-5  # default
esolver_type            ksdft  # ksdft, ofdft, sdft, tddft, lj, dp
dft_functional          scan  # same as upf file, can be lda/pbe/scan/hf/pbe0/hse
ks_solver             genelpa  # default for ksdft-lcao
pseudo_dir              ../PP_ORB
orbital_dir             ../PP_ORB

#Parameters (2.Iteration)
calculation             cell-relax # scf relax cell-relax md
ecutwfc                 100
scf_thr                 1e-8
scf_nmax                300
relax_nmax              400
relax_method            bfgs  # cg, bfgs, cg_bfgs, sd, "fire"
force_thr_ev            0.05  # ev
stress_thr            5

#Parameters (3.Basis)
basis_type              lcao  # lcao or pw

#Parameters (4.Smearing)
smearing_method         gau   # mp/gaussian/fixed
smearing_sigma          0.001  # Rydberg

#Parameters (5.Mixing)
#mixing_type             broyden  # pulay/broyden
#mixing_beta             0.2  # for metal: 0.05-0.4
#mixing_gg0              1.5  # only for metal
#mixing_ndim            8    # mixing dimension, for low-d can set to 20


#Parameters (6.Calculation)
cal_force          1
cal_stress         1
out_stru           1  # print STRU in OUT
out_chg            0  # print CHG or not
```

### Environment

- ABACUS: 3.4.2 Commit: dbb28dcbb (Sat Nov 4 21:38:54 2023 +0800)
- Dependence: Intel-oneAPI Toolchain

### Additional Context

Is SCAN functional usage the same as PBE? Is there and adjustment in pseudopotential, orbital basis and other input setting needed ?

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by wenfei-li** [comment]
i do not think this is a 'bug', but rather a feature request, as is clear from the error message

**Comment by wenfei-li** [comment]
working on it
