### ISSUE TITLE
Error of 4096 atoms with 1 process

### ISSUE THREAD

**Issue by PeizeLin** [deepmodeling/abacus-develop#3219]
### Describe the bug

When calculating too many atoms with few processes, there are still bugs.

After `DensityMatrix::DensityMatrix-MK()`, throw `std::length_error` `vector::_M_default_append`.

[Si_12_pbe_1-56.zip](https://github.com/deepmodeling/abacus-develop/files/13382778/Si_12_pbe_1-56.zip)

### Environment

ABACUS: 2023.11.16 - 4b4e7017
Red Hat 4.8.5-44
icpc version 2021.5.0 (gcc version 10.2.0 compatibility)
OpenMP = ON
Intel MPI 2021.5.0
Intel MKL 2021.5.0
ELPA 2021.11.002 OpenMP

**Comment by PeizeLin** [comment]
Some bugs have been fixed in PR #3341.
But there are still bugs exist.

Some bugs are in `class DMgamma_2dtoGrid`.
The toughest problem is `int` array in `MPI_Alltoallv()`.
One possible solution is to use `_c` functions in MPI-4.0. But how to fix these bugs with MPI<4.0 is unsolved.
@dyzheng

**Comment by mohanchen** [comment]
We will close this issue since no obvious solution can be found in a short time. We always welcome new issues.
