### ISSUE TITLE
Interface with GDPy package

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#3229]
### Background

[GDPy](https://github.com/hsulab/GDPy) stands for Generating Deep Potential with Python (GDPy/GDP¥), including a set of tools and Python modules to automate the structure exploration by using Monte Carlo and Genetic Algorism, and the training for machine learning interatomic potentials (MLIPs) like deepmd, lasp, eann and nequip. 

GDPy supported LAMMPS, VASP, QE, Plumed, LASP and other calculator, but ABACUS is missing

### Describe the solution you'd like

I'll develop interface with GDPy together with the developers of GDPy

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by QuantumMisaka** [comment]
I will do something on it (and also the interface to DPA-2 or deepmd-3.0.0) in May and June.

**Comment by mohanchen** [comment]
We will close this issue since no obvious solution can be found in a short time. We always welcome new issues.

**Comment by QuantumMisaka** [comment]
The interface is done by ASE-ABACUS interface by GDPy developer, I'll have test and try to do more
