### ISSUE TITLE
this version of abacus can't use gtest on my computer

### ISSUE THREAD

**Issue by A-006** [deepmodeling/abacus-develop#3232]
### Describe the bug

![image](https://github.com/deepmodeling/abacus-develop/assets/74701833/2299c216-194a-4114-8a76-6fe113211033)
when i use build_testing on my computer,this bug appended,however the gtest can comlpile the last verison on my computer,please check the the cmakelists files 

### To Reproduce

git colne https://github.com/deepmodeling/abacus-develop.git
cmake -B build -DBUILD_TESTING=ON
cmake --build build -j50

### Environment

Ubuntu 20.04
gcc 10.5
intel MKL

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by hongriTianqi** [comment]
@A-006 can you try: cmake -B build -DBUILD_TESTING=ON -DGTEST_DIR=${the path where googletest is}

**Comment by hongriTianqi** [comment]
@A-006 Do you still have problems on this issue? If not, we will close this issue then.
