### ISSUE TITLE
What's the lowest version of CUDA supported by ABACUS?

### ISSUE THREAD

**Issue by maki49** [deepmodeling/abacus-develop#3235]
### Details

Some platforms do not support CUDA >=12.0, while someone found that ABACUS does not support CUDA < 12.0 (Is it true? )

**Comment by Chentao168** [comment]
The cuda version installed using Conda is 11.8.

**Comment by QuantumMisaka** [comment]
I think this is related to the installation environment? In my WSL2 with cuda 11.7, ABACUS runs well in my Nvidia 2070 Super GPU on PW calculation

**Comment by haozhihan** [comment]
In my experience, every version after CUDA10.0 is OK.
