### ISSUE TITLE
Wrong real space wavefunction output in LCAO SOC calculation

### ISSUE THREAD

**Issue by zhang-changwei** [deepmodeling/abacus-develop#3241]
### Describe the bug

In my system, there are 1408 electrons in total, so I should expect 1408 valence bands in a SOC calculation. 
The lcao scf calculation work correctly. However, when I want to extract real space wavefunctions near VBM, the result seems wrong, The CBM should reveal Pb p orbital feature.  I wander whether the code extract the wavefunction of correct bands, since the band index for wanvefunction output is around 704. 
BTW: the get_wf calculation can not be accerlarated by MPI, otherwise there will be discontinuity between different real space regions.

[CsPbI3.zip](https://github.com/deepmodeling/abacus-develop/files/13435406/CsPbI3.zip)

### To Reproduce

1. run a scf lcao calculation
2. run get_wf calculation

### Environment

OS: CentOS
Compiler: gcc 10.2.0
Dependencies: openmpi, scalapack, libxc, fftw, elpa

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by dyzheng** [comment]
Can you try code changes in #3302 , and tell me if your problem can be solved?

**Comment by gawcista** [comment]
> Can you try code changes in #3302 , and tell me if your problem can be solved?

That's great. But I think there are similar problems in `get_pchg`. Besides. I noticed that there is an other mode `(mode==2)` to pick specific bands in `istate_charge.cpp`. May I know how to make use of it? This is related to #3266

**Comment by gawcista** [comment]
> Can you try code changes in #3302 , and tell me if your problem can be solved?

I met similar problem. Now it's solved for my case.

**Comment by dyzheng** [comment]
> > Can you try code changes in #3302 , and tell me if your problem can be solved?
> 
> I met similar problem. Now it's solved for my case.

Thank you for your report, I will merge this PR.

**Comment by gawcista** [comment]
> > > Can you try code changes in #3302 , and tell me if your problem can be solved?
> > 
> > 
> > I met similar problem. Now it's solved for my case.
> 
> Thank you for your report, I will merge this PR.

It's great! But I think the MPI problem is also important, especially for large systems.
