### ISSUE TITLE
Time of existed CI test should be shorten to add new integrate test cases

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#3249]
### Details

CI test have three parts:
- 1. integrate test cases (test/integrate/).
- 2. deepks integrate test cases (test/deepks/).
- 3. unittests set for independent code (source/*/test/).

the time limit of Ctest is 1400s , we can use three methods to alleviate the time:
- 1. replace integrate test cases with unittests which can cover save code region.
- 2. accelerate the performance of some integrate test cases.
- 3. fuse some integrate cases to one case.

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by WHUweiqingzhou** [comment]
b.t.w, the time limit can be modified in `.github/workflows/test.yml`
see https://github.com/deepmodeling/abacus-develop/blob/develop/.github/workflows/test.yml#L41
