### ISSUE TITLE
The deviation of energy/force/stress calculated by ABACUS and QE is large

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3251]
### Describe the bug

I have use ABACUS to perform the SCF calculations on a series of alloy systems (structures are downloaded from [material project](https://legacy.materialsproject.org/)) containing various elements. The PW (plane wave) base set was used, with ecutwfc set to 100 Ry and kspacing set to 0.2 1/Bohr. Smearing was set to mp with sigma 0.01 Ry, nbands used the default value, and scf_thr was set to 1e-6, and the symmetry was turned off. The results were compared with those of QE ([link](https://labs.dp.tech/projects/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.62-c53585)), which utilized the same pseudopotential and parameter settings. 

ABACUS job: https://launching.mlops.dp.tech/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.63-e5f9e1

The maximum deviation of energy per atom is about 90 meV.

![image](https://github.com/deepmodeling/abacus-develop/assets/91927439/1f6857dd-d275-4077-af33-d9102aff12cd)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by pxlxingliang** [comment]
The outputs of ABAUCS: [abacus.zip](https://github.com/deepmodeling/abacus-develop/files/13454331/abacus.zip)
 
The outputs of QE: 
[qe.zip](https://github.com/deepmodeling/abacus-develop/files/13454333/qe.zip)

**Comment by pxlxingliang** [comment]
At previous test, the force is small, which reduce the deviation is also small. Here I have made a little change on cell, and let the maximum absolute force component is larger than 0.1 eV/A. At the same time, I have set pseudo_rcut =10, and pseudo_mesh =1 to ensure that the cut-off for radial integration of pseudopotentials and the mesh are consistent with those in QE. And then run the test.
https://labs.dp.tech/projects/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fsched-abacustest-alloy-scf-1ab4a3

This time, we can find that the energy difference between ABACUS and QE is less than 0.1 meV/atom, and we can say their energy is consistent. But the stress/virial still have a large deviation.
![image](https://github.com/deepmodeling/abacus-develop/assets/91927439/f73a35a2-ba0d-47ff-a00f-feb26095de92)

**Comment by pxlxingliang** [comment]
Use 017_Co_Y, I have done the finite difference test of stress. The step is 0.0001.

STRESS | ABACUS | finite difference | QE
-- | -- | -- | --
11 | -29.23 | -71.49 | -70.84
22 | 19.83 | -19.45 | -19.46
33 | 18.44 | -19.98 | -20.88

As we can see, the result of finite difference is consistent with that by QE, and this means the analytical results from ABACUS is wrong.

[abacus.zip](https://github.com/deepmodeling/abacus-develop/files/13509949/abacus.zip)
[qe (2).zip](https://github.com/deepmodeling/abacus-develop/files/13509950/qe.2.zip)

**Comment by YuLiu98** [comment]
Taking `017_Co_Y` as an example, I tested the results of ABACUS and QE using two smearing methods `mp` and `gauss`, respectively.

I find that the results of ABACUS are consistent with QE, including **energy, force, and stress** when the smearing method is `gauss`.

However, the smearing method `mp` provides inconsistent stress, which is shown in the issue.

Here are the output files: [017_Co_Y.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13556725/017_Co_Y.tar.gz)

Overall, I think all the deviations resulted from the smearing method `mp`.

**Comment by YuLiu98** [comment]
`000_Ag_Au_Cd` is also the case.
[000_Ag_Au_Cd.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13557013/000_Ag_Au_Cd.tar.gz)

**Comment by YuLiu98** [comment]
I'm sorry that I have made a mistake!

The smearing method `mp` is correct!

Let abacus read `charge-density.dat` that qe outputs, and fixes the charge density during scf. **The results including energy, force, and stress are consistent** using `mp`.

Here are the output files for examples `000_Ag_Au_Cd` and `017_Co_Y`: [20231206.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13579397/20231206.tar.gz)


I think that the inconsistence comes from the fact that the converged charge density between QE and ABACUS is different.

**Comment by pxlxingliang** [comment]
I have try to increase the ecutwfc to 200 Ry, but the STRESS is still incorrect.

![image](https://github.com/deepmodeling/abacus-develop/assets/91927439/0d0f627b-d5bc-48d6-bd05-6518e67fc231)
