### ISSUE TITLE
Output partial charge density of a specific iband list

### ISSUE THREAD

**Issue by gawcista** [deepmodeling/abacus-develop#3266]
### Background

In current version, the partial charge can be obtained with `calculation=get_pchg`. However, the set of `nbands_istate` output too many unexpected result if one just want pchg with several specific band index. 

### Describe the solution you'd like

It is suggested to provide a keyword i.e. `iband` to determine a band index list. Only these wave functions are calculated. Similar tag can be found in VASP as `IBAND`: https://www.vasp.at/wiki/index.php/IBAND

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by WHUweiqingzhou** [comment]
Thanks to @wenfei-li, PR #3501 enables ABACUS can output partial charge density of a specific iband list in **PW** basis.

**Comment by AsTonyshment** [comment]
Closed by #3934.
