### ISSUE TITLE
abnormal problem encountered in the calculation of TDDFT + NPT ensemble

### ISSUE THREAD

**Issue by jiahangli7** [deepmodeling/abacus-develop#3273]
### Details

I would like to inquire about the When I used the TDDFT plus NPT ensemble, there would be extremely non-convergence of pressure and lattice in the system within five steps. When I use TDDFT plus NVE ensemble, I can complete the calculation. Moreover, I was able to complete the calculation successfully when I used NPT alone. May I ask why the calculation of TDDFT plus NPT cannot be performed completely? My INPUT and OUTPUT files are attached below. 
[test2.zip](https://github.com/deepmodeling/abacus-develop/files/13497555/test2.zip)

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by lyb9812** [comment]
TDDFT calculation do not support NPT ensemble. You can only use NVE ensemble.
