### ISSUE TITLE
shared library libxc.so link failed

### ISSUE THREAD

**Issue by JTaozhang** [deepmodeling/abacus-develop#3274]
### Details

Hi There,
I am installing abacus through toolchain_intel.sh. However I meet a error saying, 
[ 97%] Linking C shared library libxc.so
/usr/bin/ld: CMakeFiles/xc.dir/src/bessel.c.o: unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libxc.so.12] Error 1
make[1]: *** [CMakeFiles/xc.dir/all] Error 2
make: *** [all] Error 2
[  0%] Linking C shared library libxc.so
/usr/bin/ld: CMakeFiles/xc.dir/src/bessel.c.o: unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libxc.so.12] Error 1
make[1]: *** [CMakeFiles/xc.dir/all] Error 2
make: *** [all] Error 2
~/additional_sofware/abacus-develop-3.4.3/toolchain/scripts/tool_kit.sh: line 682: ~/additional_sofware/abacus-develop-3.4.3/toolchain/install/libxc-6.2.2/install_successful: No such file or directory

I have loaded  gcc-10.2.0, intel2021/oneapi/mkl/latest, intel2021/oneapi/compiler/latest,  intel2021/oneapi/compiler-rt/latest  intel2021/oneapi/mpi/latest, to compile it.

how to solve it ?

regards,
Tao

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by QuantumMisaka** [comment]
It seems your `libxc`  installation process failed, I recommend you to do 
```
rm -r install/libxc*
rm -r build/setup_* build/libxc*/
```
and do toolchain installation again by `toolchain_intel.sh` and `build_abacus_intel.sh`

**Comment by WHUweiqingzhou** [comment]
@JTaozhang,
Hi, have your problem solved already? if so or not, plz let us know.

**Comment by JTaozhang** [comment]
yes, I have solved the problem, thanks.
