### ISSUE TITLE
Abacus Computational Efficiency Issues in Molecular Dynamics

### ISSUE THREAD

**Issue by JiajiaLiu7451** [deepmodeling/abacus-develop#3280]
### Details

The computational system is the Ti metal (001) surface containing 72 atoms, and molecular dynamics simulations were performed on it with a timestep of 500 steps and a frequency of 1 fs. The simulation was conducted on a single node with 32 cores and 64 GB  memory. After running for two days, only 260 steps were completed, and the task was unexpectedly interrupted. Can the efficiency of Abacus molecular dynamics simulations be improved? 
upload the computation files as attachments：
[MD.zip](https://github.com/deepmodeling/abacus-develop/files/13521213/MD.zip)

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by mohanchen** [comment]
Thanks for the advice, we also want to improve the efficiency of AIMD.

**Comment by YuLiu98** [comment]
@JiajiaLiu7451 Can you please supply the output file for this example?

**Comment by YuLiu98** [comment]
@JiajiaLiu7451 Hi, I have tested this example and found no problem using the latest develop branch with AddressSanitizer enabled. So I will close this issue. If you still have problems, please submit another issue.

[test.tar.gz](https://github.com/user-attachments/files/17565323/test.tar.gz)
