### ISSUE TITLE
Abacus software encountered issues with task interruption during molecular dynamics simulation.

### ISSUE THREAD

**Issue by JiajiaLiu7451** [deepmodeling/abacus-develop#3289]
### Details

Running molecular dynamics simulations of Ti(0001) surface under NVT ensemble using Abacus software. The total timestep is set to 500 steps, but the simulation unexpectedly terminates after 269 steps. Seeking guidance on the possible reasons?
[MD.zip](https://github.com/deepmodeling/abacus-develop/files/13537925/MD.zip)

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by YuLiu98** [comment]
The interruption seems to be caused by the memory leak. There may be some memory leak during scf, and the memory leak is accumated during md, finally abacus interrupted.

**Comment by caic99** [comment]
@YuLiu98 Please check the test result of dynamic analysis on memory leak [here](https://deepmodeling.github.io/abacus-develop/).

**Comment by WHUweiqingzhou** [comment]
@JiajiaLiu7451,
We have solved a bug related with memory leak recently, which may result in the error you mention here. Could you double-check if the error have been solved by using the latest ABACUS?
