### ISSUE TITLE
Bug: weird behavior of drho when `nspin=4`

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#3300]
### Describe the bug

I run a non-colinear calculation whose `nspin` is 4, and output drho for different `is` in function `get_drho`. The result is followed:
![image](https://github.com/deepmodeling/abacus-develop/assets/33364058/1bff5970-8374-4cd1-9d13-15a7f9cc4d2d)
 $\rho$, $m_x$ and $m_y$ is almost same, while $m_z$ is obviously larger than them.
Is it a bug or not? Or any reasonable physics behind it?
[Fe_dimer.zip](https://github.com/deepmodeling/abacus-develop/files/13548674/Fe_dimer.zip)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by hongriTianqi** [comment]
This issue was closed because "data in this figure was wrong" from @WHUweiqingzhou .
