### ISSUE TITLE
error in GPU calculation

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3301]
### Describe the bug

I use Bohrium GPU (machine type: "1 * NVIDIA T4_16g") to run the below example, and suffer the error:
`cuBLAS Assert: CUBLAS_STATUS_INVALID_VALUE /abacus-develop/source/module_hsolver/kernels/cuda/math_kernel_op.cu 719`
[009_216Si.zip](https://github.com/deepmodeling/abacus-develop/files/13553689/009_216Si.zip)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by denghuilu** [comment]
I have tested this case before, which is caused by the system consuming a lot of graphics memory.  The work for more detailed device memory notifications is still in progress , please check #3106 .

**Comment by pxlxingliang** [comment]
Ok, In the daily GPU testing, let's skip the exmaple.
