### ISSUE TITLE
Feature: add brief Introduction of the Output Files in documentation

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#3311]
### Background

In ABACUS's [documentation](https://abacus.deepmodeling.com/en/latest/quick_start/input.html), we have a part **《brief Introduction of the Input Files》**. 
To avoid misunderstanding from user-side, such as #3240, a new part **《brief Introduction of the Output Files》** is urgently needed.

### Describe the solution you'd like

Add **《brief Introduction of the Output Files》** in [documentation](https://abacus.deepmodeling.com/en/latest/quick_start/input.html)

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by QuantumMisaka** [comment]
Good! It is very important for users to know how to get concerned properties. like use `grep ETOT OUT*/run*.log` to get total energy
