### ISSUE TITLE
Cannot complete calculation when set exx_separate_loop=0

### ISSUE THREAD

**Issue by iduygnay** [deepmodeling/abacus-develop#3332]
### Describe the bug

Every time it calculates hse functional calculation, it will stop at the second EXX scf step at the fifth electron step. I ssh to the node and top to see the CPU use rate, it is zero. I've tested this twice and got the same results so I guess this is a bug.
![image](https://github.com/deepmodeling/abacus-develop/assets/109792836/68380c65-98eb-4c83-b3f7-4cf252f19466)
[loop0.zip](https://github.com/deepmodeling/abacus-develop/files/13661652/loop0.zip)

### To Reproduce

abacus version is 3.4.3

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by iduygnay** [comment]
I just noticed that the electron step time is too long. A normal electron step time should be around 30s.
![image](https://github.com/deepmodeling/abacus-develop/assets/109792836/c77bda59-37b0-4353-9206-7f49a45fa23f)

**Comment by iduygnay** [comment]
But in the issue case, it is 10^3 s.

**Comment by maki49** [comment]
The CPU usage in your screenshot is 6373% which is resonable if you use 64 threads.
I tested your case on my workstation and found that the long hanging can be shortened by enlarging the following thresholds:
```
exx_cauchy_threshold 1e-3
exx_dm_threshold 1e-2
exx_c_threshold 1e-2
```
So I think it may be solely a matter of efficiency.
By the way, thanks for your case by which I found another bug during the test ： #3564
