### ISSUE TITLE
Charge extrapolation yielded OLD_SPIN_CHG.cube and NEW_SPIN_CHG.cube files are needed to delete before program quit

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#3333]
### Details

I dive into the codes and find these two files are dumped everytime when charge extrapolation is needed, in ESOLVER_*::afterscf() function. However these two files are not needed by user and it seems that these two files are just temporary files, their existence is because of the strategy of i/o of charge extrapolation.
I suggest to delete these two files.

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by YuLiu98** [comment]
Yes, you are right. Could you please do the modification?
