### ISSUE TITLE
Download failed when installing by using CMake

### ISSUE THREAD

**Issue by wszhang** [deepmodeling/abacus-develop#3340]
### Describe the bug

[ 11%] Creating directories for 'cereal-populate'
[ 22%] Performing download step (download, verify and extract) for 'cereal-populate'
-- Downloading...
   dst='/home/wenshuai/abacus-develop/build/_deps/cereal-subbuild/cereal-populate-prefix/src/v1.3.0.tar.gz'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://github.com/USCiLab/cereal/archive/refs/tags/v1.3.0.tar.gz'
CMake Error at cereal-subbuild/cereal-populate-prefix/src/cereal-populate-stamp/download-cereal-populate.cmake:170 (message):
  Each download failed!

    error: downloading 'https://github.com/USCiLab/cereal/archive/refs/tags/v1.3.0.tar.gz' failed
          status_code: 35
          status_string: "SSL connect error"
          log:
          --- LOG BEGIN ---
          Uses proxy env variable https_proxy == 'https://X.X.X.X:3128'
    Trying X.X.X.X:3128...

  Connected to X.X.X.X (X.X.X.X) port 3128 (#0)

  ALPN, offering http/1.1

  Cipher selection:
  ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH

  TLSv1.2 (OUT), TLS header, Certificate Status (22):

  [5 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  OpenSSL SSL_connect: Connection reset by peer in connection to
  96.10.130.3:3128

  Closing connection 0

  

          --- LOG END ---

### Expected behavior

One can download the files in github website without checking the SSL certificate. Taking Wget for example, the code can use the option "--no-check-certificate" to download the "cereal" in some limited cluster environment.

### To Reproduce

Need to compile in limited cluster environment. 

### Environment

private enterprise cluster.

### Task list for Issue attackers (only for developers)

- [X] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by caic99** [comment]
Hi @wszhang ,
Is it possible for you to download Cereal prior to installation?

**Comment by hongriTianqi** [comment]
This issue has not been responsed for a long time. We will close it then. If the raiser still has problems, please open it again. @wszhang
