### ISSUE TITLE
Support the GPU version of libxc

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/abacus-develop#3344]
### Background

See the previous discussion at https://github.com/conda-forge/libxc-feedstock/pull/59.

[Libxc docs](https://gitlab.com/libxc/libxc#gpu-support-with-cuda) said

>  When running with libxc compiled with Cuda, both the input and output arrays must always be allocated on the GPU (or using unified memory).
>  Libxc will fail (most likely you will get a segmentation fault) if a CPU array is passed.

For now, we have to use libxc CPU since abacus doesn't support the GPU version. (https://github.com/conda-forge/abacus-feedstock/pull/20)

### Describe the solution you'd like

Add a compile flag. When this flag is enabled, the CUDA array is passed to libxc, instead of the array on the host CPU.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by mohanchen** [comment]
We will close this issue since the LibXC is not the bottleneck right now. We always welcome new issues in future.
