### ISSUE TITLE
Docs: the default documentation is not latest version

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#3347]
### Details

I find the online documentation is stable, instead of latest version. Should we use latest version directly?  

![image](https://github.com/deepmodeling/abacus-develop/assets/33364058/9c516d7a-6205-4f03-ac72-7c5c299da162)

### Have you read the online manual http://abacus.deepmodeling.com/en/latest/

- [X] Yes, I have read the online manual.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific section of the documentation with the issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Update the documentation to address the issue, following the suggested improvement.
- [ ] Ensure the updated documentation adheres to the project's documentation standards.
- [ ] Test the updated documentation to ensure it is clear and accurate.
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Publish the updated documentation and notify the issue reporter.

**Comment by caic99** [comment]
Hi @WHUweiqingzhou ,
I've changed the default version to latest in readthedocs control panel.
Using latest version aligns with the link in issue template.
