### ISSUE TITLE
Delete class Wavefunc_in_pw after #3057

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#3365]
### Describe the Code Quality Issue

I found LCAO_in_PW feature is repaired in #3057 , I think these two files related to LCAO_in_PW is outdated:
- /abacus-develop/source/module_hamilt_lcao/hamilt_lcaodft/wavefunc_in_pw.h
- /abacus-develop/source/module_hamilt_lcao/hamilt_lcaodft/wavefunc_in_pw.cpp 
there is fatal bug in these two files for spin-orbit coupling calculation while they are used in two features.
I hope developer can refactor them follow new LCAO_in_PW code.

### Task list for Issue attackers (only for developers)

- [x] Identify the specific code file or section with the code quality issue.
- [x] Investigate the issue and determine the root cause.
- [x] Research best practices and potential solutions for the identified issue.
- [x] Refactor the code to improve code quality, following the suggested solution.
- [x] Ensure the refactored code adheres to the project's coding standards.
- [x] Test the refactored code to ensure it functions as expected.
- [x] Update any relevant documentation, if necessary.
- [x] Submit a pull request with the refactored code and a description of the changes made.

**Comment by kirk0830** [comment]
Will solve this asap

**Comment by kirk0830** [comment]
for towannier90 interface, see #3371
