### ISSUE TITLE
For H2 case, the diagonal element of the overlap matrix calculated by the LCAO basis set is not 1.0

### ISSUE THREAD

**Issue by haozhihan** [deepmodeling/abacus-develop#3366]
### Describe the bug

When I used the test example provided by the abacus project (abacus-develop/tests/integrate/215_NO_sol_H2/), I found that the diagonal element of the overlap matrix calculated by the LCAO basis set of the H2 case was not 1.

```
output s_mat:
1.006418649036	0.024574484465	0.000000000000	-0.000000000000	0.000000000000	0.716703511116	0.290039274347	0.430747397416	0.000000000000	-0.003020658420	
0.024574484465	1.090174667141	0.000000000000	-0.000000000000	0.000000000000	0.290039274347	0.601513221898	-0.388829002566	0.000000000000	0.002768223349	
0.000000000000	0.000000000000	0.978347046255	0.000000000000	0.000000000000	-0.430747397416	0.388829002566	-0.149673383195	0.000000000000	0.004716661246	
-0.000000000000	-0.000000000000	0.000000000000	0.978347046255	0.000000000000	-0.000000000000	-0.000000000000	0.000000000000	0.472864443182	0.000000000000	
0.000000000000	0.000000000000	0.000000000000	0.000000000000	0.978347046255	0.003020658420	-0.002768223349	0.004716661246	0.000000000000	0.472832255714	
0.716703511116	0.290039274347	-0.430747397416	-0.000000000000	0.003020658420	1.006418649036	0.024574484465	0.000000000000	-0.000000000000	0.000000000000	
0.290039274347	0.601513221898	0.388829002566	-0.000000000000	-0.002768223349	0.024574484465	1.090174667141	0.000000000000	-0.000000000000	0.000000000000	
0.430747397416	-0.388829002566	-0.149673383195	0.000000000000	0.004716661246	0.000000000000	0.000000000000	0.978347046255	0.000000000000	0.000000000000	
0.000000000000	0.000000000000	0.000000000000	0.472864443182	0.000000000000	-0.000000000000	-0.000000000000	0.000000000000	0.978347046255	0.000000000000	
-0.003020658420	0.002768223349	0.004716661246	0.000000000000	0.472832255714	0.000000000000	0.000000000000	0.000000000000	0.000000000000	0.978347046255	

```

### Environment

OS: Ubuntu 22.04
Compiler: gcc 11.3.0
Dependencies: Intel MKL

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by jinzx10** [comment]
Hi @haozhihan,  the matrix in OP agrees with the output file "data-S-0" when I added "out_mat_hs 1"  to INPUT. This suggests that it is likely to be S(k), which is the Fourier transform of S(R). If a system has a small cell such that equivalement atoms in neighboring cells have overlapped basis, the diagonal elements of S(k=[0,0,0]) could deviate from 1.

The raw orbital overlap matrix S(R) could be found by adding "out_mat_hs2 1" to INPUT, which will create a file called "data-SR-sparse_SPIN0.csr" that stores the sparse matrix in CSR format for each R. In general S(R) means the overlap matrix between the orbitals in two unit cells separated apart by R (in unit of Bravais lattice), so S(R=[0,0,0]) is the overlap matrix for orbital with themselves. I tried running this test and found that S(R=[0,0,0]) does have diagonal elements of 1, which is expected.

S(R=[0,0,0])
![image](https://github.com/deepmodeling/abacus-develop/assets/26805483/341480e5-ae31-4310-a7cb-305076a0a899)

S(k=[0,0,0])
![image](https://github.com/deepmodeling/abacus-develop/assets/26805483/19751275-61e1-49e9-8a61-fe90177d459c)
