### ISSUE TITLE
Can ABACUS support auto-set of dipole correction related parameters?

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#3386]
### Details

no matter QE or ABACUS, I always find this kind of parameter need some calculation by user to determine their values, like `efield_pos_max`, `efield_pos_dec` and `efield_amp`. However, if these parameter can be set automatically if `dip_cor_flag       1`, it will be much more use-friendly especially for surface-catalysis context.

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by QuantumMisaka** [comment]
I consider it is needed, for:
1. in some tasks of surface calculation like Genetic Algorism, Monte Carlo and others, the position of vacuum layer will vary and there might by molecular in vacuum layer. Also for now the default value of `efield_pos_max` is 0.0, which means dipole correction will always be set in the edge of cell, this is good for center-ed system but bad for surface model that all atom position along vacuum direction is below 0.5, which is also a habitual usage for surface modeling.  An automatically detection is needed
2. VASP and CP2K can set dipole correction automatically, for VASP, user only need to set `LDIPOL = .TRUE.` and `IDIPOL` to 1-3 or 4 ( 4 for all direction ), and VASP will automaticaly add dipole correction. in `DIPOL` option of VASP from VASPWIKI, it says:
> Mind: If the flag is not set, VASP determines where the charge density averaged over one plane drops to a minimum and calculates the center of the charge distribution by adding half of the lattice vector perpendicular to the plane where the charge density has a minimum (this is a rather reliable approach for orthorhombic cells)

I think we can use the likely way.

**Comment by WHUweiqingzhou** [comment]
This issue calls for a more reasonable default values for dipole-related parameters.
@sunml99 do you have any suggestion?

**Comment by WHUweiqingzhou** [comment]
@YuLiu98
do you have any suggestion about this issue?

**Comment by YuLiu98** [comment]
> I consider it is needed, for:
> 
> 1. in some tasks of surface calculation like Genetic Algorism, Monte Carlo and others, the position of vacuum layer will vary and there might by molecular in vacuum layer. Also for now the default value of `efield_pos_max` is 0.0, which means dipole correction will always be set in the edge of cell, this is good for center-ed system but bad for surface model that all atom position along vacuum direction is below 0.5, which is also a habitual usage for surface modeling.  An automatically detection is needed
> 2. VASP and CP2K can set dipole correction automatically, for VASP, user only need to set `LDIPOL = .TRUE.` and `IDIPOL` to 1-3 or 4 ( 4 for all direction ), and VASP will automaticaly add dipole correction. in `DIPOL` option of VASP from VASPWIKI, it says:
> 
> > Mind: If the flag is not set, VASP determines where the charge density averaged over one plane drops to a minimum and calculates the center of the charge distribution by adding half of the lattice vector perpendicular to the plane where the charge density has a minimum (this is a rather reliable approach for orthorhombic cells)
> 
> I think we can use the likely way.

Do you mean that parameters `efield_pos_max` should be reset per ion step? Or just set it once according to the initial vacuum area?

**Comment by QuantumMisaka** [comment]
> Do you mean that parameters `efield_pos_max` should be reset per ion step? Or just set it once according to the initial vacuum area?

Normally just once is enough, but can we leave a parameter for reset it before each ion step ?

**Comment by YuLiu98** [comment]
> > Do you mean that parameters `efield_pos_max` should be reset per ion step? Or just set it once according to the initial vacuum area?
> 
> Normally just once is enough, but can we leave a parameter for reset it before each ion step ?

I worry that the change of `efield_pos_max` will affect the total energy, which may be unphysical. For example, the total energy should be conserved in NVE ensemble, which will be changed by `efield_pos_max`.

Which way does VASP employ?

**Comment by QuantumMisaka** [comment]
> 
> I worry that the change of `efield_pos_max` will affect the total energy, which may confuse users. Which way does VASP employ?
>

I think VASP is the former way, just set in once
