### ISSUE TITLE
SCF convergence of meta-GGA for magnetic system need more enhancement

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#3390]
### Details

I am using meta-GGA functional like SCAN to do SCF (and relaxation) in Fe5C2 (510) surface model, which have approx 100 atoms and 12 Ang of vacuum layer along y-axis (transformed from z-axis)

![image](https://github.com/deepmodeling/abacus-develop/assets/43902832/8eabea3a-4209-4a2d-8537-ef20579ccd7e)

[Fe5C2_510_r2scan.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13774796/Fe5C2_510_r2scan.tar.gz)

Practice results below:
1. in my SCAN practice:
```
symmetry                0
dft_functional          scan 
calculation             scf # scf relax cell-relax md
ecutwfc                 100
scf_thr                 1e-7
scf_nmax                300
ks_solver             genelpa
smearing_method         mp  
smearing_sigma          0.010 
mixing_type             broyden  
mixing_tau              true
mixing_ndim             20   
efield_flag        1   
dip_cor_flag       1   
efield_dir         1   
efield_pos_max     0.7 
efield_pos_dec     0.1 
```
The SCF DRHO only converged to 2e-6 after 300 electronic steps
```
 ITER   TMAG      AMAG      ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
 GE290  1.81e+02  2.04e+02  -2.630745e+05  -1.082119e-05  1.848e-06  5.711e+01  
 GE291  1.81e+02  2.04e+02  -2.630745e+05  1.414790e-05   2.020e-06  5.704e+01  
 GE292  1.81e+02  2.04e+02  -2.630745e+05  -1.238594e-05  1.916e-06  5.703e+01  
 GE293  1.81e+02  2.04e+02  -2.630745e+05  -9.542969e-06  1.802e-06  5.696e+01  
 GE294  1.81e+02  2.04e+02  -2.630745e+05  -3.928596e-07  1.776e-06  5.688e+01  
 GE295  1.81e+02  2.04e+02  -2.630745e+05  9.952509e-06   1.869e-06  5.719e+01  
 GE296  1.81e+02  2.04e+02  -2.630745e+05  -1.294170e-05  1.684e-06  5.710e+01  
 GE297  1.81e+02  2.04e+02  -2.630745e+05  -4.320654e-05  2.017e-06  5.707e+01  
 GE298  1.81e+02  2.04e+02  -2.630745e+05  1.087831e-05   2.024e-06  5.717e+01  
 GE299  1.81e+02  2.04e+02  -2.630745e+05  -5.535573e-06  2.218e-06  5.718e+01  
 GE300  1.81e+02  2.04e+02  -2.630745e+05  -3.021876e-05  1.962e-06  5.704e+01  
 !! CONVERGENCE HAS NOT BEEN ACHIEVED !!
----------------------------------------------------------------
TOTAL-STRESS (KBAR)                                           
----------------------------------------------------------------
   -15809.3102873718       577.0600800228     25021.0458445989
      577.0600800228    -55633.7239429407    -14423.8390696038
    25021.0458445989    -14423.8390696038    -75970.9066761111
----------------------------------------------------------------
```

[abacus.log](https://github.com/deepmodeling/abacus-develop/files/13774827/abacus.log)

(And also the stress result is nonsense)

If turn off `mixing_tau`, the EDIFF will NOT converge to 1e-4.

Also SCAN have multiple version, and the default SCAN in ABACUS is the original version, which is likely to have some shortness. I tried r2SCAN in libxc by using `dft_functional MGGA_X_R2SCAN+MGGA_C_R2SCAN`, the SCF convergence performance is better and the stress value is somehow better.
```
 GE290  1.79e+02  2.02e+02  -2.631329e+05  1.012268e-06   5.014e-07  6.236e+01  
 GE291  1.79e+02  2.02e+02  -2.631329e+05  -1.762745e-06  3.876e-07  6.232e+01  
 GE292  1.79e+02  2.02e+02  -2.631329e+05  2.624443e-06   4.107e-07  6.231e+01  
 GE293  1.79e+02  2.02e+02  -2.631329e+05  -1.436558e-06  4.271e-07  6.238e+01  
 GE294  1.79e+02  2.02e+02  -2.631329e+05  2.996909e-06   4.670e-07  6.232e+01  
 GE295  1.79e+02  2.02e+02  -2.631329e+05  5.576359e-07   4.650e-07  6.245e+01  
 GE296  1.79e+02  2.02e+02  -2.631329e+05  -8.244755e-07  4.248e-07  6.239e+01  
 GE297  1.79e+02  2.02e+02  -2.631329e+05  -3.131294e-06  4.382e-07  6.247e+01  
 GE298  1.79e+02  2.02e+02  -2.631329e+05  -8.919898e-07  4.610e-07  6.266e+01  
 GE299  1.79e+02  2.02e+02  -2.631329e+05  2.869504e-06   4.529e-07  6.270e+01  
 GE300  1.79e+02  2.02e+02  -2.631329e+05  -2.035277e-06  4.607e-07  6.267e+01  
 !! CONVERGENCE HAS NOT BEEN ACHIEVED !!
----------------------------------------------------------------
TOTAL-STRESS (KBAR)                                           
----------------------------------------------------------------
    -1245.4870636966        45.0248977389        24.9601729040
       45.0248977389     -2359.5341561726        17.1095966128
       24.9601729040        17.1095966128     -1204.5984113136
----------------------------------------------------------------
```
[abacus.log](https://github.com/deepmodeling/abacus-develop/files/13774860/abacus.log)

which means, if I set `scf_thr 1e-6`, the SCF will converge after 150 - 210 elec steps. but which is not good. by contrast, in PBE, I can make it converge within 80 elec steps by using `scf_thr 1e-7` and `mixing_ndim 20`. 

Also, for meta-GGA, set `mixing_ndim 20` seems to have no help but harm to SCF convergence. For example, in SCF task above, if I set `mixing_ndim 20`, the SCF will converge to drho<1e-6 in 
```
 GE223  1.79e+02  2.02e+02  -2.631329e+05  2.400567e-06   1.200e-06  6.247e+01  
 GE224  1.79e+02  2.02e+02  -2.631329e+05  -6.863337e-06  1.141e-06  6.252e+01  
 GE225  1.79e+02  2.02e+02  -2.631329e+05  1.378795e-06   1.019e-06  6.241e+01  
 GE226  1.79e+02  2.02e+02  -2.631329e+05  2.809117e-06   9.583e-07  6.258e+01  
 GE227  1.79e+02  2.02e+02  -2.631329e+05  -5.284820e-06  9.615e-07  6.264e+01  
 GE228  1.79e+02  2.02e+02  -2.631329e+05  -1.214860e-06  8.951e-07  6.234e+01  
```
But if make it default:
```
 GE156  1.79e+02  2.02e+02  -2.631329e+05  3.098527e-08   1.613e-06  5.757e+01  
 GE157  1.79e+02  2.02e+02  -2.631329e+05  -8.593711e-07  1.007e-06  5.766e+01  
 GE158  1.79e+02  2.02e+02  -2.631329e+05  -1.191349e-06  1.079e-06  5.770e+01  
 GE159  1.79e+02  2.02e+02  -2.631329e+05  -1.091563e-06  9.528e-07  5.759e+01  
 GE160  1.79e+02  2.02e+02  -2.631329e+05  -4.231074e-06  7.269e-07  5.761e+01  
 GE161  1.79e+02  2.02e+02  -2.631329e+05  1.240549e-06   6.797e-07  5.746e+01
```
Sadly, the latter SCF also can not converge to drho<1e-7
[abacus.log](https://github.com/deepmodeling/abacus-develop/files/13774894/abacus.log)

I'm also trying using `mixing_tau false` in R2SCAN calculation.

Moreover, I have tried other meta-GGA functional, if using TPSS, rev-TPSS and RTPSS in LibXC, this error will occur:
```
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 Eigenvalues are too large!
 CHECK IN FILE : OUT.ABACUS/warning.log
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
And for MN15L, the convergence is not good as these Minnesota functional will be :
```
 GE290  1.74e+02  1.97e+02  -2.620560e+05  2.611788e-04   1.737e-05  8.150e+01  
 GE291  1.74e+02  1.97e+02  -2.620560e+05  -3.318980e-03  1.398e-05  8.155e+01  
 GE292  1.74e+02  1.97e+02  -2.620560e+05  -1.240796e-04  1.226e-05  8.153e+01  
 GE293  1.74e+02  1.97e+02  -2.620560e+05  3.756863e-03   1.308e-05  8.148e+01  
 GE294  1.74e+02  1.97e+02  -2.620560e+05  2.412256e-03   1.607e-05  8.146e+01  
 GE295  1.74e+02  1.97e+02  -2.620560e+05  -5.743140e-03  1.270e-05  8.154e+01  
 GE296  1.74e+02  1.97e+02  -2.620560e+05  6.224327e-03   1.593e-05  8.146e+01  
 GE297  1.74e+02  1.97e+02  -2.620560e+05  -6.085941e-03  1.289e-05  8.155e+01  
 GE298  1.74e+02  1.97e+02  -2.620560e+05  -7.832315e-05  1.172e-05  8.146e+01  
 GE299  1.74e+02  1.97e+02  -2.620560e+05  2.376403e-03   1.301e-05  8.172e+01  
 GE300  1.74e+02  1.97e+02  -2.620560e+05  -3.401732e-03  1.131e-05  8.153e+01  
``` 

But I consider that R2SCAN and other revised-SCAN functional need to be good in ABACUS.

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by QuantumMisaka** [comment]
@dyzheng @WHUweiqingzhou I consider this problem need some attention

**Comment by WHUweiqingzhou** [comment]
@QuantumMisaka 
The surface is relatively hard to converge, we suggest you can reduce `scf_thr`, which is 10^-6 defaultly for LCAO. And we will try some new mixing method for metaGGA in the future.

**Comment by QuantumMisaka** [comment]
I wonder if we are using a high-level DFT method, like now from PBE to R2SCAN, a larger basis set is needed. The calculation above is in LCAO std basis which is DZP and cutoff radius for Fe is 8, for C is 7, I tried DZP LCAO basis with cutoff for Fe is 10 and for C is 9, the convergence is much better, which can converge to drho<10^-6 within 80 elec steps.

I'm having more testing

**Comment by WHUweiqingzhou** [comment]
Based on current data, there is no big problem of SCF convergence for meta-GGA. We can restart to discuss this issue if someone finds other cases hard to converge.
