### ISSUE TITLE
memory leak in AIMD with device=GPU 

### ISSUE THREAD

**Issue by Liu-RX** [deepmodeling/abacus-develop#3394]
### Describe the bug

The GPU flash memory grows as AIMD proceeds when GPU is used.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by dyzheng** [comment]
I tested test/integrate/120 case with ENABLE_ASAN=1 , and found the direct memory leak related with Tensor, I hope you can fix memory lead with CPU at the same time.
`
Direct leak of 43008 byte(s) in 896 object(s) allocated from:
    #0 0x7f3f24c2d1c7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x55d861105751 in container::Tensor::Tensor(base::core::Allocator*, container::DataType, container::DeviceType, container::TensorShape const&) /abacus-develop/source/module_base/module_container/ATen/core/tensor.cpp:26
    #2 0x55d861105989 in container::Tensor::Tensor(container::DataType, container::DeviceType, container::TensorShape const&) /abacus-develop/source/module_base/module_container/ATen/core/tensor.cpp:20
    #3 0x55d86111a5d9 in container::TensorMap::TensorMap(void*, container::DataType, container::DeviceType, container::TensorShape const&) /abacus-develop/source/module_base/module_container/ATen/core/tensor_map.cpp:6
    #4 0x55d86110f0eb in container::Tensor::operator[](int const&) const /abacus-develop/source/module_base/module_container/ATen/core/tensor.cpp:321
    #5 0x55d86088f599 in hsolver::DiagoCG<std::complex<double>, psi::DEVICE_CPU>::schmit_orth(int const&, container::Tensor const&, container::Tensor const&, container::Tensor&) /abacus-develop/source/module_hsolver/diago_cg.cpp:511
    #6 0x55d86089f564 in hsolver::DiagoCG<std::complex<double>, psi::DEVICE_CPU>::diag_mock(container::Tensor const&, container::Tensor&, container::Tensor&) /abacus-develop/source/module_hsolver/diago_cg.cpp:127
    #7 0x55d8608a235a in hsolver::DiagoCG<std::complex<double>, psi::DEVICE_CPU>::diag(std::function<void (container::Tensor const&, container::Tensor&)> const&, std::function<void (container::Tensor const&, container::Tensor&)> const&, container::Tensor&, container::Tensor&, container::Tensor const&) /abacus-develop/source/module_hsolver/diago_cg.cpp:582
    #8 0x55d8608f02b6 in hsolver::HSolverPW<std::complex<double>, psi::DEVICE_CPU>::hamiltSolvePsiK(hamilt::Hamilt<std::complex<double>, psi::DEVICE_CPU>*, psi::Psi<std::complex<double>, psi::DEVICE_CPU>&, double*) /abacus-develop/source/module_hsolver/hsolver_pw.cpp:656
    #9 0x55d8608f8d05 in hsolver::HSolverPW<std::complex<double>, psi::DEVICE_CPU>::solve(hamilt::Hamilt<std::complex<double>, psi::DEVICE_CPU>*, psi::Psi<std::complex<double>, psi::DEVICE_CPU>&, elecstate::ElecState*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) /abacus-develop/source/module_hsolver/hsolver_pw.cpp:215
    #10 0x55d860c16989 in ModuleESolver::ESolver_KS_PW<std::complex<double>, psi::DEVICE_CPU>::hamilt2density(int, int, double) /abacus-develop/source/module_esolver/esolver_ks_pw.cpp:725
    #11 0x55d860bde88f in ModuleESolver::ESolver_KS<std::complex<double>, psi::DEVICE_CPU>::Run(int, UnitCell&) /abacus-develop/source/module_esolver/esolver_ks.cpp:385
    #12 0x55d860431d30 in MD_func::force_virial(ModuleESolver::ESolver*, int const&, UnitCell&, double&, ModuleBase::Vector3<double>*, bool const&, ModuleBase::matrix&) /abacus-develop/source/module_md/md_func.cpp:231
    #13 0x55d86045a1af in Run_MD::md_line(UnitCell&, ModuleESolver::ESolver*, MD_para&) /abacus-develop/source/module_md/run_md.cpp:60
    #14 0x55d86082e232 in Driver::driver_run() /abacus-develop/source/driver_run.cpp:55
    #15 0x55d86082b04b in Driver::atomic_world() /abacus-develop/source/driver.cpp:92
    #16 0x55d86082d8a3 in Driver::init() /abacus-develop/source/driver.cpp:32
    #17 0x55d8600f9214 in main /abacus-develop/source/main.cpp:38
`

**Comment by dyzheng** [comment]
@Liu-RX Can you test with PR #3405 ?

**Comment by Liu-RX** [comment]
> @Liu-RX Can you test with PR #3405 ?

I am still running the MD. It has already run for one night, and it seems that the memory did not grow significantly. If the memory remains the same tomorrow, I will close the issue.
