### ISSUE TITLE
Abnormal energy values in the ground state and distorted state

### ISSUE THREAD

**Issue by jiahangli7** [deepmodeling/abacus-develop#3395]
### Details

When abacus calculated the elastic constant using energy-strain method, I did some manual calculations on my side. It is always the case that the energy of some perturbed structures are lower than that of the ground state. I firstly doing relaxing step under ground state and then apply a range of strains on it. But some strained structure showing abnormal energy values. Below I attach my two directory files which contain ground state and the strain of 0.0015, please help me to see what is wrong. Thank you very much!
[elastic_cal.zip](https://github.com/deepmodeling/abacus-develop/files/13779128/elastic_cal.zip)

**Comment by Liu-RX** [comment]
Dear Jiahangli,
I did not see anything wrong in your attached files. If you want to relax the cell constant, i.e., find the optimized cell constant, you should specify the `calculation` as `cell-relax`, which could optimize both atomic positions and cell constant at the same time. As for `calculation relax`, only atomic positions are optimized, so setting `stress_thr` is only useful for `calculation cell-relax.`
You could also refer to http://abacus.deepmodeling.com/en/latest/advanced/opt.html for more info.

**Comment by mohanchen** [comment]
Since no further discussions, I will close this issue.
