### ISSUE TITLE
Add phonopy example for ABACUS

### ISSUE THREAD

**Issue by 1041176461** [deepmodeling/abacus-develop#3396]
### Describe the Testing Issue

1. I fixed a bug when parsing forces in ABACUS v3.4.4 output using phonopy in this PR(https://github.com/phonopy/phonopy/pull/322). 
2. Here are my examples for phonopy interface, but I don't know how to add them to ABACUS, maybe someone can help me finish it.  
[phonopy-test.zip](https://github.com/deepmodeling/abacus-develop/files/13779165/phonopy-test.zip)

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by kirk0830** [comment]
Hi, I would like suggest you consider the following way to parse to make this interface stable:
```python
def read_abacus_output(filename):
    """Read ABACUS forces from last self-consistency iteration."""
    force = None
    with open(filename, "r") as file:
        for line in file:
            if re.search(r"TOTAL ATOM NUMBER = [0-9]+", line):
                natom = int(re.search("[0-9]+", line).group())
            if re.search(r"TOTAL-FORCE \(eV/Angstrom\)", line):
                force = np.zeros((natom, 3))
                _match_pattern = r"^(\s*)([A-Za-z]*[0-9]+)((\s*[-]?[0-9]+\.[0-9]+){3})(.*)$"
                _match = re.match(_match_pattern, line)
                while not _match:
                    line = file.readline()
                    _match = re.match(_match_pattern, line)
                iatom = 0
                while _match:
                    fx, fy, fz = (_match.group(3).split()[i].strip() for i in range(3))
                    force[iatom] = (float(fx), float(fy), float(fz))
                    iatom += 1
                    if iatom == natom:
                        break
                    else:
                        line = file.readline()
                        _match = re.match(_match_pattern, line)

    if force is None:
        raise ValueError("Force data not found.")

    return force
```

**Comment by pxlxingliang** [comment]
Hi, @1041176461, I can help to add this example to abacus weekly testing, but I need you to supply an extra script run.sh.
This script should archive 3 things:
1. run the test
2. judge if the results are correct
3. write the version/running time/pass information to files

This script may be like:
```
##################################
# Run commands
##################################
pass=1
start_time=$(date +%s)

# commands to run the interface test

end_time=$(date +%s)
elapsed_time=$((end_time - start_time))

##################################
#Check results
##################################

# commands to check if the test is passed
# may be like:
# for ipath in "file1 that should be produced after running test" \
#              "file2 that should be produced after running test" \
#              "path1 that should be produced after running test" 
# do
#        if [ ! -e $ipath ];then
#                echo "ERROR: Can not find file \"$ipath\"!!!"
#                pass=0
#        fi
# done


##################################
#Get ABACUS version
##################################
version="unknow"
commit="unknow"
for i in OUT.*/running_*.log  # please modify the file name
do 
    version=$(grep "                              ABACUS" $i| awk '{print $2}')
    commit=$(grep "                      Commit:" $i| awk -F "ommit:" '{print $2}')
    commit=$(echo "$commit" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
    break
done

# write results
echo "$version($commit)" > version
echo ${elapsed_time} > run.time
echo $pass > run.pass
```

**Comment by 1041176461** [comment]
@kirk0830 This code is not compatible with ABACUS v3.3.1

**Comment by pxlxingliang** [comment]
> @kirk0830 This code is not compatible with ABACUS v3.3.1

Hi @1041176461, You can try to use the below codes, which should be effective. Need change the self.LOG to be the line list of logfile, and the force list here is a list of one dimension, and you may need to change to be two dimension.

```
def GetForceFromLog(self):
        force = None
        for i in range(len(self.LOG)):
            i = -1*i - 1
            line = self.LOG[i]
            if 'TOTAL-FORCE (eV/Angstrom)' in line:
                #head_pattern = re.compile(r'^\s*atom\s+x\s+y\s+z\s*$')
                value_pattern = re.compile(r'^\s*[A-Z][a-z]?[1-9][0-9]*\s+[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?\s+[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?\s+[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?\s*$')
                j = i
                noforce = False
                while not value_pattern.match(self.LOG[j]):
                    j += 1
                    if j >= i + 10:
                        print("Warning: can not find the first line of force")
                        noforce = True
                        break
                if noforce:
                    break
                
                while value_pattern.match(self.LOG[j]):
                    if force == None:
                        force = []
                    force += [float(ii) for ii in self.LOG[j].split()[1:4]]
                    j += 1
                break
```

**Comment by 1041176461** [comment]
Hi, @pxlxingliang Here are run.sh, input and output files. Please help me add them to ABACUS. Thanks!
[phonopy-test.zip](https://github.com/deepmodeling/abacus-develop/files/13786949/phonopy-test.zip)

**Comment by pxlxingliang** [comment]
> Hi, @pxlxingliang Here are run.sh, input and output files. Please help me add them to ABACUS. Thanks! [phonopy-test.zip](https://github.com/deepmodeling/abacus-develop/files/13786949/phonopy-test.zip)

This example has been added to the weekly test.
The test result can be found in: https://labs.dp.tech/projects/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fsched-abacustest-interface-test-1a948e
