### ISSUE TITLE
Duplicate code in hamilt.cu

### ISSUE THREAD

**Issue by caic99** [deepmodeling/abacus-develop#341]
In the branches regarding `NPOL==1`, the code segments are almost the same. 
https://github.com/deepmodeling/abacus-develop/blob/bf6ded3ff4a22ca76872b8f276c68efa662782e0/source/src_pw/hamilt.cu#L97
Possible solution: assign variables in if statement, and put the main part outside of it.

**Comment by ddhhss** [comment]
I chceked the code again, and because the diag function requires both dim and dmx parameters, the two parts of the code are not easy to combine.
