### ISSUE TITLE
In the CI test some warning get different value between github test

### ISSUE THREAD

**Issue by Zhuxuegang2022** [deepmodeling/abacus-develop#3414]
### Describe the Testing Issue

In the CI test some warning get different value between github test, 
____
101_PW_upf201_uspp_NaCl 
mywarn    [WARNING   ]  totalforceref cal=9.44457600 ref=9.44612000 deviation=0.00154400
githup  1: [WARNING   ]  totalforceref cal=9.44971600 ref=9.44612000 deviation=-0.00359600
____
281_NO_KP_HSE 与github
mywarn [WARNING   ]  totalstressref cal=4160.37924100 ref=4160.36613500 deviation=-0.01310600
githup   [WARNING   ]  totalstressref cal=4160.37931600 ref=4160.36613500 deviation=-0.01318100
____
286_NO_KP_CR_HSE
mywarn    [WARNING   ]  etotref cal=-192.65701443 ref=-192.65714944 deviation=-0.00013501
githup  1: [WARNING   ]  etotref cal=-192.65701432 ref=-192.65714944 deviation=-0.00013512
____
I want to change the result.ref, which comfirm before it avalable, but some test get different value and I don't now how to solve it.
this issue related PR is #3412  and #3382 , it also related to the issues before #2844

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by YuLiu98** [comment]
You can get the same machine environment as GitHub through docker. 

@hongriTianqi @pxlxingliang What's your advice?

**Comment by WHUweiqingzhou** [comment]
@Zhuxuegang2022,
Is there any update about this issue to share with us?

**Comment by Zhuxuegang2022** [comment]
> @Zhuxuegang2022, Is there any update about this issue to share with us?

Yes, it seem that the different are related to the compile method, or may related to the OMP_NUM_THREADS=n. 
I think it is an issue need pay more attention, which may give different result for different compile method or different persion.
What more, the PR #3412  is already get correct value by get the same situation of github.
If one think this issue is not need pay more attention, it may be closed.

**Comment by WHUweiqingzhou** [comment]
closed due to #4493
