### ISSUE TITLE
PBEsol+U calculation not converge in the scf step

### ISSUE THREAD

**Issue by xdzhu** [deepmodeling/abacus-develop#3422]
### Describe the bug

I have explored various mixing parameters including pulay, broyden, mixing_beta, and mixing_ndim, but unfortunately, I am encountering convergence issues with the PBEsol+U calculation in ABACUS for my specific structure.

Initially, the structure successfully converged with the PBEsol+U setting, allowing for the completion of structural optimization. **However, challenges arose when I modified the structure by removing one oxygen atom**. Despite reattempting the optimization, the SCF electronic steps in each ionic step continued for 200 steps without achieving convergence, and I observed a concerning trend of diverging energy. It's worth mentioning that the structure, from which the oxygen atom was removed, does converge when calculated using PBE without adding U.

Here is the calculation sample and you could check the results above.
[PBEsol+U-not-coinverge.zip](https://github.com/deepmodeling/abacus-develop/files/13815331/PBEsol%2BU-not-coinverge.zip)

Could you provide recommended parameters for this example in a PBEsol+U calculation? I would greatly appreciate any insights or recommendations you could provide to address this issue.  Thank you for your time and assistance.

![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/6423c133-d1c1-40e1-8bcf-42e717412fce)

### To Reproduce

To replicate this issue, you could **run the SCF calculation directly** instead of the RELAX calculation to verify the convergence of the SCF step.

### Environment

ABACUS 3.4.4

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by mohanchen** [comment]
It's related to DFT+U.

**Comment by xdzhu** [comment]
@mohanchen Hi Prof. Chen, thanks for your suggestion. I finally got this issue resolved after discussion with Prof. Lixin He. 

The convergence problem originated from structural changes in the atomic configuration after removing an oxygen atom, which also altered the electronic structure of the entire system. **Now this system is no longer an insulator but a metal, with occupied states at the Fermi level. The default smearing_sigma value of 0.01 led to collapse in the electronic structure. Increasing smearing_sigma to 0.05 effectively achieved convergence in the SCF step.**

[converged-smearing=0.05.zip](https://github.com/deepmodeling/abacus-develop/files/13824997/converged-smearing.0.05.zip)
Now SCF is converged.
![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/ae919a1a-922c-4d9c-9088-a46c2d9b6f5d)

**Comment by hongriTianqi** [comment]
This is a good practice as it provide insights on how to run DFT+U calculations for defect systems.
