### ISSUE TITLE
Number of charge in `mulliken.txt` .ne. number of electrons in `running_scf.log`

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#3423]
### Describe the bug

The number of electrons in `running_scf.log` is 336, while it is different whatever nspin calculation:

nspin 1: total charge 330.2
nspin 2: total charge 333.1
nspin 4: total charge 333.1

### Expected behavior

They should be equal?

### To Reproduce
see results in the attached file:
[issue_FeO2.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13816419/issue_FeO2.tar.gz)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by hongriTianqi** [comment]
This is normal as the Mulliken charge analysis does not ensure the sum rule.

**Comment by jinzx10** [comment]
> This is normal as the Mulliken charge analysis does not ensure the sum rule.

How come? Given the density matrix $P(k) = C(k) O(k) C^{\dagger}(k)$ where $O(k) = \text{diag}(f_i(k))$ corresponds to the occupation, 

$$\sum_{k}w_k\text{Tr}(P(k)S(k)) = \sum_{k}w_k\text{Tr}( O(k) C^{\dagger}(k)S(k)C(k) ) = \sum_k w_k\text{Tr}(O(k)) = N$$

Let

$$q_A \equiv \sum_{\mu\in{}A} \sum_{k}w_k[P(k)S(k)]_{\mu\mu}$$

we have the sum rule $\sum_A q_A = N$.

**Comment by hongriTianqi** [comment]
This issue is resolved by PR #3503.
