### ISSUE TITLE
USPP can't work

### ISSUE THREAD

**Issue by ieiue** [deepmodeling/abacus-develop#3428]
### Describe the bug

When using uspp, there will be some errors.
![img_v3_026o_4dc924a6-f213-4453-9d7c-8e8ab5e6fc6g](https://github.com/deepmodeling/abacus-develop/assets/116336560/4db3ffd9-d6f0-42bd-a912-7fbc4a5fbab5)

### Expected behavior

ABACUS should complete the scf calculation using uspp.

### To Reproduce

[Fe_uspp.zip](https://github.com/deepmodeling/abacus-develop/files/13818544/Fe_uspp.zip)

### Environment

ABACUS 3.4

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by YuLiu98** [comment]
You should retry this example via the latest version (v3.5). 

The following is my test result: [Fe.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13819422/Fe.tar.gz)
