### ISSUE TITLE
We need memory check report every day or every release

### ISSUE THREAD

**Issue by mohanchen** [deepmodeling/abacus-develop#3431]
### Background

Occasionally, we have memory leak issues, and it costs a lot of time to debug. Therefore, we need a memory check report every day or every release.

### Describe the solution you'd like

We need a memory check report every day or every release.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by kirk0830** [comment]
seems our github-pages is designed for this purpose? Not sure: https://deepmodeling.github.io/abacus-develop/

**Comment by caic99** [comment]
Hi @mohanchen ,
The memory leak check report is published at https://deepmodeling.github.io/abacus-develop/ .
The [test](https://github.com/deepmodeling/abacus-develop/actions/workflows/dynamic.yml) is executed every Sunday.

**Comment by Liu-RX** [comment]
I think I could add a text analysis for the release check report at the end of the leak check, and publish which of the tests are having real leak problem.  @mohanchen

**Comment by mohanchen** [comment]
We will close this issue since no obvious solution can be found in a short time. We always welcome new issues.
