### ISSUE TITLE
Failed compilation ABACUS with DeepMD dependency (inflateValidate@ZLIB_1.2.9)

### ISSUE THREAD

**Issue by xdzhu** [deepmodeling/abacus-develop#3439]
### Describe the bug

After introducing DeepMD and TensorFlow dependencies, I encountered a compilation failure while trying to compile ABACUS. 

Using the same Intel OneAPI 2023.2.0 suite and GCC-11.3.0, the compilation was successful in my local WSL2-Ubuntu-22.04 environment but failed in the cluster environment. The key difference is that the local environment has GPU-version of DeepMD, while the failure occurred with CPU-version of DeepMD in the cluster. 

Despite re-installing zlib and libpng in the conda environment as advised, or even compile the standalone versions of zlib and libpng manually, the issue still persists. Any help in resolving this issue would be greatly appreciated.

The detailed compilation log is attached. 
[compile_abacus_with_deepmd.zip](https://github.com/deepmodeling/abacus-develop/files/13829677/compile_abacus_with_deepmd.zip)

The compilation error of screen output was as:
> [100%] Building CXX object CMakeFiles/abacus.dir/source/main.cpp.o
> [100%] Linking CXX executable abacus
> /public/home/zhuxd/Software/Anaconda3/envs/dp2024/lib/libpng16.so.16: undefined reference to `inflateValidate@ZLIB_1.2.9'
> icpx: error: linker command failed with exit code 1 (use -v to see invocation)
> gmake[2]: *** [abacus] Error 1
> gmake[1]: *** [CMakeFiles/abacus.dir/all] Error 2
> gmake: *** [all] Error 2
> -- Install configuration: ""
> -- Up-to-date: /public/home/zhuxd/Software/abacus/INSTALL/3.5.0-DP/include/backward.hpp
> -- Up-to-date: /public/home/zhuxd/Software/abacus/INSTALL/3.5.0-DP/lib64/backward/BackwardConfig.cmake
> CMake Error at build/cmake_install.cmake:51 (file):
>   file INSTALL cannot find
>   "/public/home/zhuxd/Software/abacus/with-Deep/abacus-develop-3.5.0-dp/build/abacus":
>   No such file or directory.

Although there is an error `/usr/bin/ld: cannot find -lpthreads` in the CMakeError.log, I tried the commad gcc -lpthreads in either platform also cannot find the pthreads.
It seems due to the `libpng16.so.16: undefined reference to inflateValidate@ZLIB_1.2.9` stage is not completed so that the later stage of pthread.h run into some problems.

CMakeError.log

> Performing C++ SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
> Change Dir: /public/home/zhuxd/Software/abacus/with-Deep/abacus-develop-3.5.0-dp/build/CMakeFiles/CMakeTmp
> 
> Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_53f39/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_53f39.dir/build.make CMakeFiles/cmTC_53f39.dir/build
> gmake[1]: Entering directory `/public/home/zhuxd/Software/abacus/with-Deep/abacus-develop-3.5.0-dp/build/CMakeFiles/CMakeTmp'
> Building CXX object CMakeFiles/cmTC_53f39.dir/src.cxx.o
> /public/home/zhuxd/intel/oneapi/compiler/2023.2.0/linux/bin/icpx -DCMAKE_HAVE_LIBC_PTHREAD -I/public/home/zhuxd/Software/abacus/INSTALL/elpa-2023.05.001-2023/include -Wno-write-strings -Wno-tautological-constant-compare  -std=gnu++11 -MD -MT CMakeFiles/cmTC_53f39.dir/src.cxx.o -MF CMakeFiles/cmTC_53f39.dir/src.cxx.o.d -o CMakeFiles/cmTC_53f39.dir/src.cxx.o -c /public/home/zhuxd/Software/abacus/with-Deep/abacus-develop-3.5.0-dp/build/CMakeFiles/CMakeTmp/src.cxx
> Linking CXX executable cmTC_53f39
> /public/software/compiler/cmake/3.24.1/bin/cmake -E cmake_link_script CMakeFiles/cmTC_53f39.dir/link.txt --verbose=1
> /public/home/zhuxd/intel/oneapi/compiler/2023.2.0/linux/bin/icpx  -Wno-write-strings -Wno-tautological-constant-compare  -Wl,-rpath=$base_path/lib64 -Wl,-rpath=$base_path/lib  CMakeFiles/cmTC_53f39.dir/src.cxx.o -o cmTC_53f39 
> CMakeFiles/cmTC_53f39.dir/src.cxx.o: In function `main':
> src.cxx:(.text+0x25): undefined reference to `pthread_create'
> src.cxx:(.text+0x2f): undefined reference to `pthread_detach'
> src.cxx:(.text+0x39): undefined reference to `pthread_cancel'
> src.cxx:(.text+0x45): undefined reference to `pthread_join'
> src.cxx:(.text+0x50): undefined reference to `pthread_atfork'
> icpx: error: linker command failed with exit code 1 (use -v to see invocation)
> gmake[1]: *** [cmTC_53f39] Error 1
> gmake[1]: Leaving directory `/public/home/zhuxd/Software/abacus/with-Deep/abacus-develop-3.5.0-dp/build/CMakeFiles/CMakeTmp'
> gmake: *** [cmTC_53f39/fast] Error 2
> 
> 
> Source file was:
> #include <pthread.h>
> 
> static void* test_func(void* data)
> {
>   return data;
> }
> 
> int main(void)
> {
>   pthread_t thread;
>   pthread_create(&thread, NULL, test_func, NULL);
>   pthread_detach(thread);
>   pthread_cancel(thread);
>   pthread_join(thread, NULL);
>   pthread_atfork(NULL, NULL, NULL);
>   pthread_exit(NULL);
> 
>   return 0;
> }
> 
> Determining if the function pthread_create exists in the pthreads failed with the following output:
> Change Dir: /public/home/zhuxd/Software/abacus/with-Deep/abacus-develop-3.5.0-dp/build/CMakeFiles/CMakeTmp
> 
> Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_d9c58/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_d9c58.dir/build.make CMakeFiles/cmTC_d9c58.dir/build
> gmake[1]: Entering directory `/public/home/zhuxd/Software/abacus/with-Deep/abacus-develop-3.5.0-dp/build/CMakeFiles/CMakeTmp'
> Building CXX object CMakeFiles/cmTC_d9c58.dir/CheckFunctionExists.cxx.o
> /public/home/zhuxd/intel/oneapi/compiler/2023.2.0/linux/bin/icpx   -Wno-write-strings -Wno-tautological-constant-compare -DCHECK_FUNCTION_EXISTS=pthread_create -std=gnu++11 -MD -MT CMakeFiles/cmTC_d9c58.dir/CheckFunctionExists.cxx.o -MF CMakeFiles/cmTC_d9c58.dir/CheckFunctionExists.cxx.o.d -o CMakeFiles/cmTC_d9c58.dir/CheckFunctionExists.cxx.o -c /public/home/zhuxd/Software/abacus/with-Deep/abacus-develop-3.5.0-dp/build/CMakeFiles/CheckLibraryExists/CheckFunctionExists.cxx
> Linking CXX executable cmTC_d9c58
> /public/software/compiler/cmake/3.24.1/bin/cmake -E cmake_link_script CMakeFiles/cmTC_d9c58.dir/link.txt --verbose=1
> /public/home/zhuxd/intel/oneapi/compiler/2023.2.0/linux/bin/icpx  -Wno-write-strings -Wno-tautological-constant-compare -DCHECK_FUNCTION_EXISTS=pthread_create -Wl,-rpath=$base_path/lib64 -Wl,-rpath=$base_path/lib  CMakeFiles/cmTC_d9c58.dir/CheckFunctionExists.cxx.o -o cmTC_d9c58  -lpthreads 
> /usr/bin/ld: cannot find -lpthreads
> icpx: error: linker command failed with exit code 1 (use -v to see invocation)
> gmake[1]: *** [cmTC_d9c58] Error 1
> gmake[1]: Leaving directory `/public/home/zhuxd/Software/abacus/with-Deep/abacus-develop-3.5.0-dp/build/CMakeFiles/CMakeTmp'
> gmake: *** [cmTC_d9c58/fast] Error 2
> 
> 
> 
> Looking for a CUDA compiler failed with the following output:
> CMake Error at /public/software/compiler/cmake/3.24.1/share/cmake-3.24/Modules/CMakeDetermineCUDACompiler.cmake:180 (message):
>   Failed to find nvcc.
> 
>   Compiler requires the CUDA toolkit.  Please set the CUDAToolkit_ROOT
>   variable.
> Call Stack (most recent call first):
>   CMakeLists.txt:2 (project)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/public/home/zhuxd/Software/abacus/with-Deep/abacus-develop-3.5.0-dp/build/CMakeFiles/CheckCUDA/CMakeFiles/CMakeOutput.log".
> See also "/public/home/zhuxd/Software/abacus/with-Deep/abacus-develop-3.5.0-dp/build/CMakeFiles/CheckCUDA/CMakeFiles/CMakeError.log".
> 

### Environment

OS: CentOS-7
Compiler: gcc-11.3.0, oneapi-2023.2.0
Dependency: deepmd-kit-2.2.7 (cpu version) installed with conda, zlib==1.2.13 and libpng==1.6.39

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by xdzhu** [comment]
Now, using the version of [3.5.1](https://github.com/deepmodeling/abacus-develop/releases/tag/v3.5.1), I can successfully compile ABACUS with DeepMD dependency. The only thing you need to do is just claim your deepmd directory when you run `cmake` as below:

DP_DIR=~/Software/Anaconda3/envs/deepmd

```
cmake -B build \
(...other compiling flag here)
-DDeePMD_DIR=$DP_DIR \
-DTensorFlow_DIR=$DP_DIR \
```

![945165706eafcd96bed538a2a35840b](https://github.com/deepmodeling/abacus-develop/assets/55775434/e41704b3-f7c1-42b8-b2df-19b416b376bb)

**Comment by hongriTianqi** [comment]
Good Practice as it provides useful experience.
