### ISSUE TITLE
output XC matrix

### ISSUE THREAD

**Issue by maki49** [deepmodeling/abacus-develop#3443]
Output the XC matrix in Kohn-Sham orbital representation $V^\text{xc}_{ij}=\braket{\psi_i|\hat{V}^\text{xc}|\psi_j}$ , useful for GW calculation.

**Comment by kirk0830** [comment]
wow fantastic, ABACUS will be capable to do GW calculation later? That will provide a in-built calibration of ABACUS TDDFT predicted optical spectrum results
