### ISSUE TITLE
Unconverged non-magnetic HClO System.

### ISSUE THREAD

**Issue by Carrotkingdom** [deepmodeling/abacus-develop#3448]
### Details

**System: H10Cl6O4. Totally 20 atoms. Calypso generated structure.**
**Machine: 32 core 256G cpu on paratera.**

SCF is not converged in 100 SCF steps when ENCUT is increased to 100 Ry. See attached.
[notconverged.zip](https://github.com/deepmodeling/abacus-develop/files/13838676/notconverged.zip)

The last few steps indicate that it is quite hard to converge below 1e-8
![image](https://github.com/deepmodeling/abacus-develop/assets/86839379/c4999713-266d-4a7a-ae86-40a6852203ef)

SCF increases with ENCUT.()
ENCUT=50Ry, Nnumber of SCF is 38
ENCUT=60Ry, Nnumber of SCF is 42
ENCUT=70Ry, Nnumber of SCF is 45
ENCUT=80Ry, Nnumber of SCF is 49
ENCUT=90Ry, Nnumber of SCF is 90
Convergence is not reached for ENCUT=100

Also 
[test.zip](https://github.com/deepmodeling/abacus-develop/files/13838752/test.zip)
SCF is not converged in 100 SCF steps when KSPACING is increased up to **larger (which means less kpoints)** than 0.09522 bohr-1. See attached

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by WHUweiqingzhou** [comment]
@Carrotkingdom,
Just for mixing, I suggest you to reduce `mixing_beta` and `mixing_beta_mag`, see detail in [scf-docs](https://abacus.deepmodeling.com/en/latest/advanced/scf/converge.html#charge-mixing).

I think convergence performance get worse with increasing `ENCUT` is quite weird. From my opinion, it is not a charge-mixing problem.

**Comment by mohanchen** [comment]
> @Carrotkingdom, Just for mixing, I suggest you to reduce `mixing_beta` and `mixing_beta_mag`, see detail in [scf-docs](https://abacus.deepmodeling.com/en/latest/advanced/scf/converge.html#charge-mixing).
> 
> I think convergence performance get worse with increasing `ENCUT` is quite weird. From my opinion, it is not a charge-mixing problem.

I agree, if there are no further discusssions, I suggest to close this issue.

**Comment by WHUweiqingzhou** [comment]
Without further update, I decide to close this issue.
