### ISSUE TITLE
An issue with the screen output starting from the second step when relaxing

### ISSUE THREAD

**Issue by Chentao168** [deepmodeling/abacus-develop#3450]
### Describe the bug

As showin in the figure, there is an issue with the screen output starting from the second step when relaxing.
![img_v3_026r_b1c83934-8fe7-4ac3-841b-c26c4146023g](https://github.com/deepmodeling/abacus-develop/assets/76426373/611ac42c-74a1-4d8a-a01c-dfbd1fa9d90b)

### To Reproduce

In the `examples/relax/pw_al`

### Environment

OS: Ubuntu 20.04
Compiler: oneapi 2021.5.0
Dependencies: Intel MKL

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by QuantumMisaka** [comment]
Same issue of https://github.com/deepmodeling/abacus-develop/issues/3415 ?

**Comment by Chentao168** [comment]
Yes, they are same!

**Comment by caic99** [comment]
Duplication of #3415
