### ISSUE TITLE
Need 2D-block-parallel form to serial form of matrix transformation interface for future development

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#3455]
### Background

Some matrix multiplication operations need the full matrix, while presently this interface seems to be absent?

### Describe the solution you'd like

A easy-to-use interface for this purpose, will be helpful for representation-related feature development, including integrate QO inside ABACUS rather than use an external python-end post-processing package

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by WHUweiqingzhou** [comment]
I also think this interface is quite useful. Actually, in `source/module_hamilt_lcao/module_hcontainer/func_transfer.cpp`, there are several interfaces between 2D para and serial, but only for `HContainer`.

**Comment by jinzx10** [comment]
I second this. I think we definitely need an RAII container for block-cyclic distributed data. Linear algebra operations can also be encapsulated into this container.
