### ISSUE TITLE
Regarding PR #3444

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#3459]
### Describe the Code Quality Issue

I am not convinced by this change. Allegedly it fixed some 'bug', but simply look at the pr should reveal that this change in principle does not affect anything. I'm concerned that the real bug exists elsewhere and the current 'fix' only works by chance.
I need more information : what is the 'bug' that was said to be fixed? what is the test case? what are the results before and after the modification? the best way to validate stress is by finite difference test, was it carried out and what are the results?
![image](https://github.com/deepmodeling/abacus-develop/assets/38569667/e8932b70-351d-4600-9382-a8f87b290e80)

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by dyzheng** [comment]
Sorry I didn't complete the information, the bug come from PR #3256 . 
When user training DeePKS model with ABACUS, force and stress labels contain two gradient files named "grad_vx.npy" and "grad_vepsl.npy".
These two files are needed by DeePKS-kit but don't affect the self-consistent computation with loading DeePKS model in ABACUS.
Before #3444 , when "cal_stress = 1", the line of " https://github.com/deepmodeling/abacus-develop/blob/v3.5.0/source/module_hamilt_lcao/module_deepks/LCAO_deepks_pdm.cpp#L869 " conflict with the line of "https://github.com/deepmodeling/abacus-develop/blob/v3.5.0/source/module_hamilt_lcao/module_deepks/LCAO_deepks_pdm.cpp#L808" , which will cause severe bug that "grad_vx.npy" and "grad_vepsl.npy" are wrong and convergence of DeePKS model training won't be achieved.

This bug will be fixed after #3444 , I also add checklists in deepks test cases for protecting these code.

**Comment by wenfei-li** [comment]
I don't understand. You may write it either way; move the nlm1 line in the previous file outside the inner loop should also not affect anything. If it does, then there must be something wrong elsewhere

**Comment by dyzheng** [comment]
> I don't understand. You may write it either way; move the nlm1 line in the previous file outside the inner loop should also not affect anything. If it does, then there must be something wrong elsewhere

In #3256 I make the same mistake that nlm1 can be move outside the inner loop, but if cal_stress=1 , the nlm1 and nlm2 will be covered in the inner loop.

**Comment by wenfei-li** [comment]
ok, now i get it
