### ISSUE TITLE
Refactor: present orbital generation codes in tools/ can hardly maintain in the future

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#3460]
### Describe the Code Quality Issue

Under optimization of orbital generation strategy by @jinzx10 and ABACUS Pseudopot-Nao Square projects, the orbital generation codes will be uiltilized frequently in very near future. However present code appears to be hard to maintain and, as has been pointed out by issue #3334, after refactor the time cost will be reduced by 3 or 4 even 5 folds.

Refactor will be done by me and @jinzx10 

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by WHUweiqingzhou** [comment]
Good! Look forward to it!

**Comment by kirk0830** [comment]
Update: tools/opt_orb_pytorch and tools/opt_orb_pytorch_dpsi will be removed after refactor

**Comment by kirk0830** [comment]
[new version of orbital generation repo (temporarily)](https://github.com/kirk0830/abacus_orbital_generation)
update almost everyday

**Comment by kirk0830** [comment]
link external repo PR: https://github.com/abacusmodeling/ABACUS-orbitals/pull/7

**Comment by WHUweiqingzhou** [comment]
Update 3/27:
refactor std:out
complete default value.
Generate new PSP for Co

**Comment by kirk0830** [comment]
we now have new input script and front-end, with parallelization on rcuts, as much as possible to reduce the computation cost. Will release a new package soon. Due to this is a "refactor issue" and present stage the corresponding refactor has been done, this issue I will close.
