### ISSUE TITLE
Unittest of module_cell can not avoid code changes

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#3465]
### Describe the Testing Issue

In unittest "abacus-develop/source/module_cell/test/unitcell_test.cpp" , the test of "read_atom_positions" only test if the function can end normally, without checking of variables of UnitCell.

For example, in #3453 , I found that values of atomic magnetizations have been changed but the unittest reported nothing to protect the code.

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by WHUweiqingzhou** [comment]
Roger that, I will fix it.

**Comment by WHUweiqingzhou** [comment]
As far as I know, in some cases hard to design `EXPECT_EQ`, `unitcell_test` protect related vars by running it with help of `WarnningQuit` in code itself.
