### ISSUE TITLE
 improvement on the output of 2nd colomn of BAND_1.dat: list of X for ploting band strucuture

### ISSUE THREAD

**Issue by QG-phy** [deepmodeling/abacus-develop#3482]
### Background

when I use the KPT in the screenshot to perform the band structure calculations, I want to get the bands along the k-path of G-X-U | K-G ... . The whole K-path is not continuous. 
<img width="466" alt="image" src="https://github.com/deepmodeling/abacus-develop/assets/98570179/92701ad6-2f2d-4ccd-84ea-dc7fff3a6dd9">

The 2nd column of BADN-1.dat behaves as the list of X in plotting the band structure. But here it shows an step change of the x value, which should not be there for ploting bands.

![image](https://github.com/deepmodeling/abacus-develop/assets/98570179/0ff4f3f3-bfeb-494b-b233-bae977a0a654)

### Describe the solution you'd like

just modify the mapping from the K-path to the x-list， making the x-list continuous. 

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by kirk0830** [comment]
Hi, I have carefully checked both the case you provided and corresponding source code details. I find the No. 61 and 62 kpoints are not identical, they seem just have identical energy spectra. To verify this, I run the example in `examples/band/lcao_Si2`, with a little change in `KLINES` file:
original:
```
K_POINTS
6
Line
0.5 0.0 0.5 20
0.0 0.0 0.0 20
0.5 0.5 0.5 20
0.5 0.25 0.75 20
0.375 0.375 0.75 20
0.0 0.0 0.0 1
```
to-test:
```
K_POINTS
7
Line
0.5 0.0 0.5 20
0.0 0.0 0.0 20
0.5 0.5 0.5 20
0.0 0.0 0.0 1
0.5 0.25 0.75 20
0.375 0.375 0.75 20
0.0 0.0 0.0 1
```
Therefore I can also check what happened to No.61 and No.62 kpoints:
`kpoints` file:
```
...
      61   0.00000000   0.00000000   0.00000000 1.0000
      62   0.50000000   0.25000000   0.75000000 1.0000
...
```
`BAND_1.dat`
```
...
  61   2.73205081  -5.33892624   6.68534236   6.68534236   6.68534236   9.41056995   9.41056995   9.41056995  10.29720579
  62   3.85008480  -0.96935813  -0.96935813   2.47467459   2.47467459  11.54795528  11.54795528  12.20365346  12.20365346
...
```
Thus the problem relies on **distinguish the user demand that once a kpoint is specified with number "1", should ABACUS consider it is a new segment of kline**.

I think it is a newly required feature and will be supported in recent PR(s).
