### ISSUE TITLE
Error while use gpu device with precision is single

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3498]
### Describe the bug

For below example, I run it on Sugon dcu with single precision, and suffer below error message:
```
abacus_pw: /public/home/abacus/abacus-develop/source/module_hsolver/diago_david.cpp:918: void hsolver::DiagoDavid<std::complex<float>, psi::DEVICE_GPU>::SchmitOrth(const int &, const int, const int, psi::Psi<T, Device> &, const T *, T *, const int, const int) [T = std::complex<float>, Device = psi::DEVICE_GPU]: Assertion `psi_norm > 0.0' failed.
```

[dcu.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13945439/dcu.tar.gz)

### Expected behavior

Run the example normally.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by denghuilu** [comment]
The stability of the `davison` method with single precision implementation is currently not guaranteed. We should keep this issue open and revisit it once the new DAV algorithm is released.
