### ISSUE TITLE
wannier90 for LCAO can not running in nscf

### ISSUE THREAD

**Issue by Shen-Zhen-Xiong** [deepmodeling/abacus-develop#3505]
### Describe the bug

[3_abacus_nscf.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13960436/3_abacus_nscf.tar.gz)
Please see the example, when I running a nscf to output wannier function, Screen output always shows "KILLED BY SIGNAL: 9 (Killed)", and nscf log stop with "spin1final_state".

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by jingan-181** [comment]
I retested your example using ABACUS v3.5.1 and found two issues that need to be addressed:

1. There is a problem with the parameters in your Wannier90 input file, specifically `Sr2Mn2O6.win`. When SOC  is enabled, it is necessary to add `spinors = .True.` in the .win file, and then generate the nnkp file to ensure the spin information is correctly recognized. After adding this, the program should run correctly.

2. Regarding the file format error, ABACUS did not provide a clear error message. I will include clear error prompts in the new version.

**Comment by Shen-Zhen-Xiong** [comment]
Thank you for your answer, while I add "spinors = true" in the "Sr2Mn2O6.win" file,  then run "wannier90.x -pp Sr2Mn2O6.win" to create a new Sr2Mn2O6.nnkp file, ABACUS run correctly and  I find "Sr2Mn2O6.amn  Sr2Mn2O6.eig  Sr2Mn2O6.mmn" file.
[4_abacus_nscf.tar.gz](https://github.com/deepmodeling/abacus-develop/files/14064984/4_abacus_nscf.tar.gz)

**Comment by mohanchen** [comment]
Has this issue been solved?

**Comment by Shen-Zhen-Xiong** [comment]
Not completely resolved.  After request  #3563 is received, I will test again.
