### ISSUE TITLE
need support to Compute Overlap Matrix only

### ISSUE THREAD

**Issue by floatingCatty** [deepmodeling/abacus-develop#3510]
### Background

The document says it should support the "get_S" as calculation mode, to output the overlap matrix only. However, when I try to use this function, it hasn't done the calculation properly. Instead, several warning is raised, which looks like:

 In SCAN_BEGIN, can't find: ABFS_ORBITAL block.
 In SCAN_END, can't find: </PP_RELWFC.1> block.
 In SCAN_END, can't find: </PP_RELWFC.2> block.
 In SCAN_END, can't find: </PP_RELWFC.3> block.
 In SCAN_END, can't find: </PP_RELWFC.4> block.
 In SCAN_END, can't find: </PP_RELWFC.5> block.
 In SCAN_END, can't find: </PP_RELBETA.1> block.
 In SCAN_END, can't find: </PP_RELBETA.2> block.
 In SCAN_END, can't find: </PP_RELBETA.3> block.
 In SCAN_END, can't find: </PP_RELBETA.4> block.
 In SCAN_END, can't find: </PP_RELBETA.5> block.
 In SCAN_END, can't find: </PP_RELBETA.6> block.
 In SCAN_END, can't find: </PP_RELBETA.7> block.
 In SCAN_END, can't find: </PP_RELBETA.8> block.
 In SCAN_END, can't find: </PP_RELBETA.9> block.
 In SCAN_END, can't find: </PP_RELBETA.10> block.
 In SCAN_END, can't find: </PP_SPIN_ORB> block.
 dft_functional readin is: hse
 dft_functional in pseudopot file is: PBE
 Please make sure this is what you need
 dft_functional readin is: hse
 dft_functional in pseudopot file is: PBE
 Please make sure this is what you need
 AUTO_SET NBANDS to 0
 Generate k-points file according to KSPACING: KPT
 ElecState::cal_nbands  warning : for smearing, num. of bands > num. of occupied bands.

My input file is:
INPUT_PARAMETERS
# Created by Atomic Simulation Enviroment
ntype                                   2
ecutwfc                                 100
cal_force                               True
cal_stress                              True
scf_nmax                                100
smearing_method                         gaussian
smearing_sigma                          0.002
basis_type                              lcao
ks_solver                               genelpa
mixing_type                             pulay
mixing_beta                             0.7
scf_thr                                 1e-07
out_chg                                 1
symmetry                                0
calculation                             get_S
out_band                                1
force_thr                               0.001
out_stru                                1
kspacing                                0.08
lspinorb                                0
out_wfc_lcao                            0
dft_functional                          hse
out_mat_hs2                             True

### Describe the solution you'd like

Output the Overlap matrix only when set the calculation to "get_S"

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by mohanchen** [comment]
Thanks for reporting this issue, we will fix this.

**Comment by WHUweiqingzhou** [comment]
@floatingCatty,
could you offer the input files, including `INPUT, SRTU, KPT, .upf, .orb`? we will reproduce the problem.

**Comment by dyzheng** [comment]
I tried test case abacus-develop/tests/integrate/207_NO_KP_OS , the calculation is correct with output file SR.csr.
Can you report your input files in this Issue?

**Comment by floatingCatty** [comment]
Of course, thank you for the help, here I attached the calculation output with the input files.
[out.zip](https://github.com/deepmodeling/abacus-develop/files/14156084/out.zip)

**Comment by dyzheng** [comment]
I have repeated your bug, and I will fix it later.
You can set "nbands 1" (whatever number larger than 0) to avoid the bug for current version.

**Comment by floatingCatty** [comment]
> I have repeated your bug, and I will fix it later. You can set "nbands 1" (whatever number larger than 0) to avoid the bug for current version.

Thank you for the effort ! It works now. Looking for the updates !

**Comment by dyzheng** [comment]
Related to #1887 , @lyb9812 can you try to fix it ?
In this line: https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_elecstate/elecstate.cpp#L271
nbands and occupied_nbands are both zero in this case.

**Comment by lyb9812** [comment]
> Related to #1887 , @lyb9812 can you try to fix it ?
> In this line: https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_elecstate/elecstate.cpp#L271
> nbands and occupied_nbands are both zero in this case.

Ok.
