### ISSUE TITLE
"smearing_method: mp2"

### ISSUE THREAD

**Issue by ieiue** [deepmodeling/abacus-develop#3525]
### Details

In the documentation, the "smearing_method" can set to "mp", however, there is no mention of "mp2". I want to know if this parameter is available. But in the INPUT file which obtained after calculation, annotation has "mp2". 
![image](https://github.com/deepmodeling/abacus-develop/assets/116336560/3a8c9993-1a99-40b0-a4cd-b529b133fa94)
![image](https://github.com/deepmodeling/abacus-develop/assets/116336560/22e1c0e0-95aa-46a9-a56c-7f716223c025)

### Have you read the online manual http://abacus.deepmodeling.com/en/latest/

- [X] Yes, I have read the online manual.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific section of the documentation with the issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Update the documentation to address the issue, following the suggested improvement.
- [ ] Ensure the updated documentation adheres to the project's documentation standards.
- [ ] Test the updated documentation to ensure it is clear and accurate.
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Publish the updated documentation and notify the issue reporter.

**Comment by WHUweiqingzhou** [comment]
@ieiue,
ABACUS support "mp" and "mp2" both currently. I pull a PR to modify the corresponding docs. After then, I will make ABACUS support any order of mp method in next PR. #3534

**Comment by QuantumMisaka** [comment]
@WHUweiqingzhou Do we need to introduce `mp`, `mp2` and other mp method, especially for their Pros & Cons and commonly-used system ?
