### ISSUE TITLE
how to make numerical atomic orbital file's information fully self-contained?

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#3529]
### Details

Because we are exploring new method for generating numerical atomic orbitals, there are more aspects can be re-considered, too.
For example we have more kinds of pseudopotentials used nowadays, not only SG15 now. But **the numerical atomic orbital file does not contain any information about which pseudopotential it is generated from**.
My suggestion would be contain this information in some way, either simply change the way of naming numerical atomic orbital file, or change a little bit inside, for example the human-readable part, the header of file.

Comparatively pseudopotential file does not have such problem. Inside there are sections recording valence-treated electrons, reference configurations, code which it is generated from, code version, author and other information.

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by mohanchen** [comment]
This is an excellent idea.

**Comment by WHUweiqingzhou** [comment]
@kirk0830 can we close this issue now?
