### ISSUE TITLE
Feature: require initial density matrix for further density matrix mixing

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#3536]
### Background

Before SCF, ABACUS will construct an initial charge density. As is purposed in #3535, if we want to mix density matrix as same as charge density at the very beginning. ABACUS should construct an initial density matrix as well.

### Describe the solution you'd like

ABACUS should construct an initial density matrix as well.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by kirk0830** [comment]
I also wander if the initial superposition of atomic charges corresponds to the normalized atomic pseudowavefunction in some way, will try to derive it.

**Comment by WHUweiqingzhou** [comment]
@kirk0830,
Besides the idea just mentioned above, another solution is to fix initial charge density unchanged at first several iterations, while update density matrix to find the density matrix corresponding to the initial charge density.
Compared with the first idea, this second idea can be implemented without uncertainty.

b.t.w, this discussion is to concern the restart calculation of those which need density matrix, just like DFTU/DeePKS/EXX #3413

**Comment by kirk0830** [comment]
I don't think it is a trivial task to get a (might be with high quality) wavefunction corresponds to a fixed rho. It can be obtained by one-single rho-fixed diagonalization (means optimal wavefunction, according to concepts of Levy constrainted search) but there are surely other ways but, might be not easy cuz states are needed to be orhogonal...
Seems need some time-consuming implementation on numerical algorithm, if really not interested in diagonalization with a fixed-rho

**Comment by WHUweiqingzhou** [comment]
I think this issue can be closed now, which has been solved in some extend by PR #3542 `mixing_restart`.
