### ISSUE TITLE
The efficiency of DCU can be improved

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3541]
### Details

In this [test](https://labs.dp.tech/projects/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.90-5b9ec3), I have test some examples on sugon DCU and BOHRIUM c32_m128_cpu machine. 

In the DCU calculations  case WRe, the time ratio of `diag_zhegvx` is high to 55%, which is unreasonable.

![7802eeda82161c3c2c5cde249cfc945c_D2ZOebHEGFC4AAAAAElFTkSuQmCC](https://github.com/deepmodeling/abacus-develop/assets/91927439/fe4fdcb5-0452-4cdc-9dfb-c59d23d8c339)

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by pxlxingliang** [comment]
In this [test](https://labs.dp.tech/projects/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fsched-abacustest-alloy-dcu-ccdfa5), I have done the DCU (sugo) calculations on some alloy systems (the atom number is about 2-10)
In some cases, the time ratio of doing `Spherical_Bessel` is high to 32% (030_Mg_Pr_Tm dcu)

**Comment by denghuilu** [comment]
Related PR #3556

**Comment by WHUweiqingzhou** [comment]
This issue is close by PR #3556.
