### ISSUE TITLE
Failed compilation with "-DENABLE_PAW=1" by source code

### ISSUE THREAD

**Issue by jiongwalai** [deepmodeling/abacus-develop#3552]
### Describe the bug

Configure with:
`CC=mpiicc FC=mpiifort CCX=mpiicpc cmake -B build -DENABLE_PAW=1 -DCMAKE_INSTALL_PREFIX=/software/abacus/3.5.1 -DCEREAL_INCLUDE_DIR=/software/cereal/cereal-1.3.2/include -DELPA_DIR=/software/elpa/elpa/intel21-skx-omp`
Build with:
`cmake --build build -j8`
At the end of building code `[100%] Linking CXX executable paw_lib`
A series of errors appeared:
```.........
/usr/bin/ld: CMakeFiles/libpaw_interface_files.dir/set_rhoij.f90.o: relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
deps/libpaw_interface/test/CMakeFiles/paw_lib.dir/build.make:221: recipe for target 'deps/libpaw_interface/test/paw_lib' failed
make[2]: *** [deps/libpaw_interface/test/paw_lib] Error 1
CMakeFiles/Makefile2:1512: recipe for target 'deps/libpaw_interface/test/CMakeFiles/paw_lib.dir/all' failed
make[1]: *** [deps/libpaw_interface/test/CMakeFiles/paw_lib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target paw
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2```

### Expected behavior

_No response_

### To Reproduce

```git clone https://github.com/deepmodeling/abacus-develop.git
cd abacus-develop
CC=mpiicc FC=mpiifort CCX=mpiicpc cmake -B build -DENABLE_PAW=1 -DUSE_ELPA=0
cmake --build build -j`nproc`
```

### Environment

OS: Ubuntu 16.04
Compiler: Intel OneAPI 2021
Dependencies: ELPA2021, Intel MKL

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@wenfei-li do you have any suggestion?

**Comment by wenfei-li** [comment]
In the error message it suggests ' recompile with -fPIC', have you tried this?
Thank you for your interest in PAW, but I want to emphasize that there are still bugs in the PAW implementation, and the results will be unreliable. I am working on it and once finished we will officially release PAW as an option.

**Comment by jiongwalai** [comment]
I tried to switch to serial compilation with `cmake --build build/`
The previous error may have originated
`/usr/bin/ld: deps/libpaw_interface/CMakeFiles/paw_level2.dir/m_pawcprj.F90.o: undefined reference to symbol 'for_contig_array'
/software/intel/oneapi/compiler/2021.4.0/linux/compiler/lib/intel64_lin/libifcoremt.so.5: error adding symbols: DSO missing from command line`

In this case, I will not use PAW feature for a while until you finish the PAW development. Thank you for your hard work~

**Comment by yizeyi18** [comment]
> The previous error may have originated
`/usr/bin/ld: deps/libpaw_interface/CMakeFiles/paw_level2.dir/m_pawcprj.F90.o: undefined reference to symbol 'for_contig_array' /software/intel/oneapi/compiler/2021.4.0/linux/compiler/lib/intel64_lin/libifcoremt.so.5: error adding symbols: DSO missing from command line`

Use intel's `xild` instead of gnu `ld` while using intel compiler, or leave this to `mpiifort`. You could add `LD=/path/to/intel/xild` or `FCLD=mpiifort` in your cmake command line.
The issue is `mpiifort` used symbols specific to intel libraries and gnu  `ld` does not link them implicitly; gnu compiler works well with gnu `ld`. Here, you did not specify a `LD` and cmake selects gnu's automatically.
