### ISSUE TITLE
Add some stdout information in NSCF calculation

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#3554]
### Background

at present there is not any information printed out when NSCF runs, it will not only bring inconvienence for users even will make user confused, but also is too informationless for developers.

### Describe the solution you'd like

Print some information showing the progress of NSCF runs

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by mohanchen** [comment]
Should we use formatter？

**Comment by kirk0830** [comment]
> Should we use formatter？

I think it depends on amount of information want to print. If there are relatively large amount of data, certainly we can use formatter. So what matters at first would be what information is needed to print when NSCF. I will consider with more details then.
