### ISSUE TITLE
Broken CIF format of files dumped by ABACUS

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#3555]
### Background

the key `_symmetry_equiv_pos_as_xyz` is necessary for determining whether there are equivalent atoms. For some CIF files, there are only few atoms in the last position section, but with long data in `_symmetry_equiv_pos_as_xyz` section. Therefore this section is as much as important as the last one.
Lack of this information will cause crash for dpdata or atomkit

### Describe the solution you'd like

At least add a section:
```
_symmetry_equiv_pos_as_xyz
1 'x,y,z'
```
telling for each atom, equivalent atom is itself.

I also attach template and example provided by **INTERNATIONAL UNION OF CRYSTALLOGRAPHY (IUCr)**, is a complete version of cif file.
[example.cif.txt](https://github.com/deepmodeling/abacus-develop/files/14060338/example.cif.txt)
[form.cif.txt](https://github.com/deepmodeling/abacus-develop/files/14060339/form.cif.txt)
More reference:
https://www.iucr.org/resources/cif/dictionaries
https://www.iucr.org/resources/cif/documentation/cifguide

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by mohanchen** [comment]
We need someone who can quickly response to this kind of issue.
