### ISSUE TITLE
CMake Error when install ABACUS by cmake

### ISSUE THREAD

**Issue by ESROAMER** [deepmodeling/abacus-develop#3569]
### Details

I was trying to update my ABACUS from version 3.5.0 to the latest develop branch. My old configuration had always worked well until this time. It jumped out Cmake error info as showed below.
<img width="762" alt="2" src="https://github.com/deepmodeling/abacus-develop/assets/104255052/02548b51-0ebf-4b13-ae48-d33137f72a6c">
This is my configuration:
<img width="478" alt="3" src="https://github.com/deepmodeling/abacus-develop/assets/104255052/fafeed0c-1f90-4b69-9ca0-fb593adb3e17">
Are there any changes between version 3.5.0 and the latest develop branch? What should I do to install the latest branch properly? Or is it just another bug needs to be fixed?

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by caic99** [comment]
@ESROAMER 
This bug is expected to be fixed by #3540. Please try using the latest develop branch, or waiting for version 3.5.2 to be released today.

**Comment by ESROAMER** [comment]
> @ESROAMER This bug is expected to be fixed by #3540. Please try using the latest develop branch, or waiting for version 3.5.2 to be released today.

It was already the latest version. Obviously a PR merged 4 days ago won't fix a problem happened today.

**Comment by caic99** [comment]
@yizeyi18 @QuantumMisaka Could you please help take a look? Thanks.

**Comment by yizeyi18** [comment]
Previously, ABACUS uses a non-standard method to find ELPA includes, as the document([https://abacus.deepmodeling.com/en/latest/quick_start/easy_install.html#configure](url)) suggested, "add a symlink to avoid the additional include file folder with version name". 
You used another non-standard method to avoid this: providing a manually specified ELPA_INCLUDE_DIR; this variable's name changed, in #3478, to ELPA_INCLUDE_DIRS. Changing -DELPA_INCLUDE_DIR to -DELPA_INCLUDE_DIRS in your configuration script should help. 

But --- although your manually specified ELPA_INCLUDE_DIR does not work now, it is strange that pkg-config did not found its target in your ELPA_DIR. May you show what's in your $ELPA_DIR/lib/pkgconfig(if exists), to help us improving our cmake scripts?

**Comment by ESROAMER** [comment]
Thanks a lot, it works now.
Here is the file I find in my $ELPA_DIR/lib/pkgconfig. I changed its file type to txt so it can be uploaded here. I hope it helps.
<img width="576" alt="5" src="https://github.com/deepmodeling/abacus-develop/assets/104255052/ae5d7053-87ec-4c1f-927a-a438f9469ced">
[elpa-2021.05.002.pc.txt](https://github.com/deepmodeling/abacus-develop/files/14094917/elpa-2021.05.002.pc.txt)

**Comment by yizeyi18** [comment]
@ESROAMER Thanks for your kind upload.

**Comment by yizeyi18** [comment]
Here the not-founding occurs for not founding "elpa_openmp.pc". Although this elpa had no openmp enabled, it is compatible with older versions of ABACUS; it may worth a PR to add mpi-only elpa support with USE_OPENMP defined.
Another point is ELPA use elpa(_openmp)-$version.pc instead of elpa(_openmp).pc in 2021.05.001, maybe also earlier versions. I had not noticed this since after 2021.11.001, all versions uses elpa(_openmp).pc. Should this feature also get supported?

**Comment by yizeyi18** [comment]
As #3623 got merged, is this issue solved?
