### ISSUE TITLE
Feature: Support calculation of multi-k point band-decomposed charge density under LCAO basis.

### ISSUE THREAD

**Issue by AsTonyshment** [deepmodeling/abacus-develop#3572]
### Background

Currently, ABACUS only supports multi-k point calculation of band-decomposed charge density under PW basis, while under LCAO basis the calculation can be carried out only when `gamma_only` is set to be true. It is necessary to support calculation of multi-k point charge density under LCAO basis when INPUT keyword is set as `calculation = get_pchg`.

### Describe the solution you'd like

Changes of INPUT keywords:
1. Delete INPUT keyword `nbands_istate`.
2. Add a new INPUT parameter `bands_to_print`(similar to `ocp_set`), which enables users to choose which band to calculate.
3. Add a new INPUT boolean parameter `out_all_kpt`, which enables users to choose whether to calculate all k-points or gamma point only.

Possible changes of source code: `source/module_io/istate_charge.cpp`. Currently the calculation of density matrix under LCAO basis set is still using old-fashioned data structure. We plan to rewrite these codes with new density matrix using HContainer (see `source/module_elecstate/module_dm/density_matrix.cpp`).

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Notice any changes of core modules (Reminder only for developers)

Only source code in `module_io` will be changed. See solution description.

### Additional Context

For a more detailed description (formulae etc.), see Feishu doc [https://xmywuqhxb0.feishu.cn/docx/FBHldIvHxoP99axSZeLcHIenntg](url). One can ask @AsTonyshment for access permission.

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by WHUweiqingzhou** [comment]
Look forward to it!
b.t.w, there is a similar PR #3501 for PW basis recently.

**Comment by WHUweiqingzhou** [comment]
And This issue will be close as Issue #3266

**Comment by WHUweiqingzhou** [comment]
@AsTonyshment can we close this issue now?

**Comment by AsTonyshment** [comment]
The implementation for multi-k is not yet complete and must wait for other refactoring tasks to be finished (for example, getting rid of class `LocalOrbitalCharge`).

**Comment by hongriTianqi** [comment]
@AsTonyshment LOC has been removed. Would you take care of this issue in near future?

**Comment by AsTonyshment** [comment]
@hongriTianqi This has already been implemented, as you may have just seen in the Feishu doc (which includes a detailed benchmark with VASP). The PR will follow next week.
