### ISSUE TITLE
NSCF calculation should throw an ERROR with `symmetry=1` instead of exiting silently

### ISSUE THREAD

**Issue by xdzhu** [deepmodeling/abacus-develop#3573]
### Describe the bug

When I perform the NSCF calculation after running the SCF calculation using ABACUS, the NSCF calculation does not proceed correctly due to `symmetry=1` in the INPUT file. However, neither the screen output nor the log file shows any corresponding error messages. Although it has been mentioned in the [manual](https://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#symmetry) that symmetry should be set to 0 if calculation==md/nscf/get_pchg/get_wf/get_S, some errors or warnings should be throwed out in this circumstance.

When performing the NSCF calculation, if `symmetry=1` is detected, **it should be forcibly modified to `symmetry=0` with a warning message, advising the user to disable symmetry during NSCF calculation**.

See details in [nscf_output_with_symmetry=1.zip](https://github.com/deepmodeling/abacus-develop/files/14096737/nscf_output_with_symmetry.1.zip)
Here is running_nscf.log with  `symmetry=1` 
![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/f95a79ca-8964-476e-956a-722567b1b023)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@maki49, do you have any comment about this?

**Comment by maki49** [comment]
https://github.com/deepmodeling/abacus-develop/blob/49c85af41e59e04c6a8d60ef377092e409d0cdb9/source/module_esolver/esolver_ks_lcao_elec.cpp#L616-L621

It seems you're doing a berry phase calculation which is automatically skipped when symmetry=1. 
I'm not familiar with berry phase, so I don't know what's the best way to deal with symmetry=1: error-exit? or warning, auto set to 0 and finish the calculation normally?
(For example, if it needs the same number of k-points with SCF's output, maybe we cannot continue with symmetry=0 ...)
 @jingan-181 What's your suggestion?

**Comment by jingan-181** [comment]
Berry phase calculation belongs to the NSCF functionality, and symmetry=-1 (No symmetry will be considered) must be ensured in order to perform Berry phase calculations properly. Any other settings for symmetry should prompt an error, advising the user to change the symmetry to -1. I will submit a PR to address this issue.
