### ISSUE TITLE
undefined reference to `Json::json_output()'

### ISSUE THREAD

**Issue by ESROAMER** [deepmodeling/abacus-develop#3578]
### Details

I was trying to add some new features for abacus. Several files were added and some code was changed in my local repository. It goes well untill I update my abacus to the latest develop branch. The compilation failed and told me 'undefined reference to `Json::json_output()''.
<img width="678" alt="2" src="https://github.com/deepmodeling/abacus-develop/assets/104255052/c1f2dc1f-8505-41c4-b22c-a701a7b85c0d">
I noticed that this is a recently added function. Please tell me what does the function do, why is my code conflicts with it and how to solve it. You may refer to my code in #3576 

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by pxlxingliang** [comment]
Hi @ESROAMER, you should not remove compilation of para_json in [source/module_io/CMakeLists.txt](https://github.com/deepmodeling/abacus-develop/pull/3576/files/09109a3ffd99b5d94b67a6bf4dcd32abaf8aa985#diff-2227640c8b680f9163deaacd1b88892576e2a20bcbb0b0280e7ebc8e470aa817)

**Comment by ESROAMER** [comment]
That's it! Thank you for your help. I' m sorry to bother you for such a simple question. I should be more careful about directly overwriting the file next time
