### ISSUE TITLE
Feature: require an automatic workflow of electron-number adjustment for a constant work function

### ISSUE THREAD

**Issue by sunml99** [deepmodeling/abacus-develop#3579]
### Background

Realistic electrochemical reactions often occur under a constant applied potential. It is therefore crucial to achieve a constant potential condition for DFT-based electrochemcial surface reaction simulations. DFT calculations in ABACUS are currently based on a constant number of electrons instead of a constant potential (i.e., work function).

### Describe the solution you'd like

Since we are already able to adjust the total number of electrons in ABACUS slab models to approximate an effective electrical double-layer condition, we would like to request the ABACUS team to construct an automatic workflow of electron-number adjustment for converging the slab model's work function to a certain value. We would also prefer this constant-potential workflow/module to combine with CI-NEB calculations, which can help people do transition-state optimization under a constant potential condition.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by WHUweiqingzhou** [comment]
@sunml99,
Thanks for your idea!
Indeed, this function is quite important for surface application. We will consider a practical schedule about it.

**Comment by WHUweiqingzhou** [comment]
Maybe we can implement this method in ABACUS referred by **_J. Chem. Theory Comput. 2023, 19, 5168−5175_**.

**Comment by sunml99** [comment]
https://bohrium.dp.tech/notebooks/86445129178
