### ISSUE TITLE
OpenMP Warning when compiling ABACUS with cmake

### ISSUE THREAD

**Issue by Qianruipku** [deepmodeling/abacus-develop#358]
## Describe the Bug
ABACUS can be compiled successfully.
However, there is a "unrecognized OpenMP #pragma" warning when compiling ABACUS with cmake. 

## To Reproduce
1. cmake -B build -DCMAKE_CXX_COMPILER=icpc -DMPI_CXX_COMPILER=mpiicpc -DCMAKE_INSTALL_PREFIX=~/intelcompile/testabacus -DELPA_DIR=/home/qianrui/intelcompile/impi_elpa -DCEREAL_INCLUDEDIR=/home/qianrui/intelcompile/cereal/include
2. cmake --build build/ -j8

## Environment
- OS: [e.g. CentOS 7.6]
- Compiler: intel 2021.3.0 20210609
- Optional Dependencies: [e.g. Intel MKL]

**Comment by caic99** [comment]
It seems that the openmp compiler flag is not properly linked in `CMakeLists.txt`. I will look into it.

**Comment by dyzheng** [comment]
#389 caic99 has fixed this problem.
