### ISSUE TITLE
The parallel efficiency for USPP calculation

### ISSUE THREAD

**Issue by jiongwalai** [deepmodeling/abacus-develop#3582]
### Details

The system contains 5 atoms, and the USPP is downloaded from [QE website](https://pseudopotentials.quantum-espresso.org/legacy_tables).
I tried to calculate with different kpar value, the solution time increases with the KPAR variable, which is the opposite of the reultus calculated with ONCV.
The results are shown below:
```
grep total */output
kpar_16/output:                     total                209.26          17  12.31   100.00
kpar_1/output:                     total                 88.67          17   5.22   100.00
kpar_2/output:                     total                 78.55          17   4.62   100.00
kpar_4/output:                     total                 97.35          17   5.73   100.00
kpar_8/output:                     total                143.54          17   8.44   100.00
```
[Uploading abacus-uspp-kpar.zip…]()

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by YuLiu98** [comment]
Can you upload your examples, please?

When the total number of cores is fixed, as kpar increases, the calculation time generally takes on a parabolic shape, that is, it first decreases and then increases. Here is also the case, so I think it is normal.

Maybe you can test the example with QE using the same setting, and compare it with ABACUS.

**Comment by jiongwalai** [comment]
[Uploading abacus-uspp-kpar.zip…]()

**Comment by jiongwalai** [comment]
[abacus-uspp-kpar.zip](https://github.com/deepmodeling/abacus-develop/files/14114238/abacus-uspp-kpar.zip)

**Comment by jiongwalai** [comment]
> Can you upload your examples, please?
> 
> When the total number of cores is fixed, as kpar increases, the calculation time generally takes on a parabolic shape, that is, it first decreases and then increases. Here is also the case, so I think it is normal.
> 
> Maybe you can test the example with QE using the same setting, and compare it with ABACUS.

But the time to solution increases as kpar. It is strange.

**Comment by YuLiu98** [comment]
> > Can you upload your examples, please?
> > When the total number of cores is fixed, as kpar increases, the calculation time generally takes on a parabolic shape, that is, it first decreases and then increases. Here is also the case, so I think it is normal.
> > Maybe you can test the example with QE using the same setting, and compare it with ABACUS.
> 
> But the time to solution increases as kpar. It is strange.

kpar =2 is the most efficient here. You'd better test it with QE.

**Comment by mohanchen** [comment]
K-point parallelization (KPAR>1) is not always more efficient than the plane wave parallelizaiton (KPAR=1), especially when the number of atoms is relatively small

**Comment by mohanchen** [comment]
We will close this issue since no obvious solution can be found in a short time. We always welcome new issues.
