### ISSUE TITLE
Expected plain mixing behavior

### ISSUE THREAD

**Issue by kluophysics** [deepmodeling/abacus-develop#3586]
### Describe the Testing Issue

Using `mixing_type plain` and `mixing_beta 1.0`, after each call of mix_rho() I would expect the density stored in `rho` and `rho_save` to be the same. If a call of `get_drho`, I think it should give zero. However, the output shows it is non-zero and behaves like this.

```
-------------------------------------------
 SELF-CONSISTENT : 
 -------------------------------------------
 START CHARGE      : atomic
 DONE(7.28308    SEC) : INIT SCF
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
drho = 0.0882383
 GE1    -3.150726e+01  0.000000e+00   8.824e-02  6.611e+00  
drho = 3.348e-02
 GE2    -3.167106e+01  -1.638006e-01  3.348e-02  6.636e+00  
drho = 2.081e-02
 GE3    -3.167290e+01  -1.836713e-03  2.081e-02  6.567e+00  
drho = 1.557e-02
 GE4    -3.167413e+01  -1.224059e-03  1.557e-02  6.598e+00  
drho = 1.241e-02
 GE5    -3.167478e+01  -6.560993e-04  1.241e-02  6.613e+00  
drho = 1.027e-02
 GE6    -3.167512e+01  -3.396590e-04  1.027e-02  6.615e+00  
```
See attached test files.
[mixrho-test.zip](https://github.com/deepmodeling/abacus-develop/files/14119038/mixrho-test.zip)

### Additional Context

The test was done with github/develop branch on H_2 molecule. 

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by WHUweiqingzhou** [comment]
This unexpected behavior is induced by Kerker precondition. In ABACUS, we consider Kerker precondition during mixing. However, the Kerker precondition is open by default. You can close by setting `mixing_gg0   0.0` manually. Then, you will get `drho=0.0` as expected.
