### ISSUE TITLE
The PDOS is wrong

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3587]
### Describe the bug

For below system, I have do the DOS calculation, and plot the pdos of Co, and it show that there has no occupied electron, which is unreasonable.

[pdos (3).zip](https://github.com/deepmodeling/abacus-develop/files/14120411/pdos.3.zip)

![image](https://github.com/deepmodeling/abacus-develop/assets/91927439/ee6cd3ad-a8dc-461a-8520-61ac8382a696)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by kirk0830** [comment]
find it is because EFERMI fails to get its value, PDOS code seems fine

**Comment by WHUweiqingzhou** [comment]
@pxlxingliang,
if you get correct result, please let us know. Then we can close this issue.

**Comment by pxlxingliang** [comment]
This is because that I have use a incorrect fermi energy. 
In the running_scf.log and running_nscf.log, the fermi energy is 0, which is incorrect, and the correct value can be read in the energy output block, where list the value of item E_Fermi_up and E_Fermi_dw. 

fermi energy in running_scf.log
![image](https://github.com/deepmodeling/abacus-develop/assets/91927439/b570b12a-7101-4fba-9653-1ae121088b3e)

fermi energy in running_nscf.log
![image](https://github.com/deepmodeling/abacus-develop/assets/91927439/cdeee6d4-d8ac-4d9e-873d-b24fb3826c16)

After use the correct fermi energy, the pdos will be like:
![image](https://github.com/deepmodeling/abacus-develop/assets/91927439/53e57f3f-7f86-4aa4-b86e-e5c6604b75e4)

Now, it seems reasonable.
