### ISSUE TITLE
DFT+U: develop a new DFT+U method with variable projectors for on-site occupations.

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#3588]
### Background

The theoretical formula is from https://dptechnology.feishu.cn/wiki/HgspwrZu7i8W5DkyokBcpugtnvb

The test branch is [dftu_new](https://github.com/deepmodeling/abacus-develop/tree/dftu_new)

**Comment by WHUweiqingzhou** [comment]
@dyzheng,
Is there any news which can be shared with community? We will be very glad to hear it.

**Comment by dyzheng** [comment]
I have implemented the new DFT+U method in the branch dftu_new, add new parameter "onsite_radius" for choosing the radius of projections. 
Users can test this branch for calculation of scf, relax, cell-relax, md, nscf now.

**Comment by dyzheng** [comment]
During tests, #3621 reports a bug during cell-relax calculation. Then #3620 fixed it.

**Comment by dyzheng** [comment]
In my test of Fe2 case, mixing_beta = 0.2 and 0.1 would lead to results:

>  GE1    5.21e-13  4.78e+00  -6.809346e+03  0.000000e+00   1.411e-01  2.174e+00  
>  GE2    -2.38e-12 6.86e+00  -6.808836e+03  5.105508e-01   8.780e-02  3.319e+00  
>  GE3    1.80e-10  7.56e+00  -6.810104e+03  -1.267898e+00  5.156e-02  3.203e+00  
>  GE4    -1.58e-09 7.16e+00  -6.810557e+03  -4.537049e-01  3.242e-02  3.140e+00  
>  GE5    1.60e-08  7.21e+00  -6.810738e+03  -1.804531e-01  2.324e-02  3.242e+00  
>  GE6    -3.96e-07 7.35e+00  -6.810644e+03  9.338955e-02   2.569e-02  3.153e+00  
>  GE7    -4.28e-07 7.26e+00  -6.810710e+03  -6.593455e-02  8.380e-03  3.148e+00  
>  GE8    2.24e-06  7.22e+00  -6.810715e+03  -4.738086e-03  1.309e-03  3.666e+00  
>  GE9    -8.49e-06 7.20e+00  -6.813265e+03  -2.549590e+00  1.430e-03  3.147e+00  
> SCF restart after this step!
>  GE10   6.86e-04  7.22e+00  -6.810715e+03  2.549423e+00   2.750e-03  3.134e+00  
>  GE11   -3.65e-03 7.21e+00  -6.810716e+03  -3.844413e-04  8.951e-04  3.148e+00  
>  GE12   2.39e-02  7.20e+00  -6.810716e+03  -1.402732e-04  1.047e-03  3.146e+00  
>  GE13   1.04e-03  7.20e+00  -6.810716e+03  -6.057197e-05  7.650e-04  3.142e+00  
>  GE14   -3.58e-03 7.20e+00  -6.810716e+03  2.425858e-05   5.167e-04  3.300e+00  
>  GE15   -1.38e-04 7.20e+00  -6.810716e+03  -1.505624e-05  1.273e-04  3.197e+00  
>  GE16   -8.67e-05 7.20e+00  -6.810716e+03  -9.755210e-07  2.033e-04  3.142e+00  
>  GE17   1.06e-04  7.20e+00  -6.810716e+03  1.419512e-06   6.224e-05  3.150e+00  
>  GE18   -2.38e-04 7.20e+00  -6.810716e+03  -1.028543e-06  6.340e-05  3.139e+00  
>  GE19   -6.78e-04 7.20e+00  -6.810716e+03  -5.453591e-08  2.672e-05  3.141e+00  
>  GE20   7.80e-05  7.20e+00  -6.810716e+03  -5.315772e-08  1.403e-05  3.143e+00  
>  GE21   1.02e-04  7.20e+00  -6.810716e+03  1.062953e-08   5.654e-06  3.185e+00  
>  GE22   5.86e-06  7.20e+00  -6.810716e+03  -1.258313e-09  2.780e-06  3.141e+00  
>  GE23   -4.19e-06 7.20e+00  -6.810716e+03  -6.589320e-10  1.878e-06  3.145e+00  
>  GE24   -5.52e-07 7.20e+00  -6.810716e+03  -5.336421e-11  2.341e-06  3.146e+00  
>  GE25   -4.56e-06 7.20e+00  -6.810716e+03  -8.429999e-11  6.988e-07  3.142e+00  
>  GE26   -3.25e-06 7.20e+00  -6.810716e+03  -5.645779e-11  6.875e-07  3.157e+00  
>  GE27   -6.89e-06 7.20e+00  -6.810716e+03  -3.093578e-12  1.130e-06  3.151e+00  
>  GE28   -5.90e-06 7.20e+00  -6.810716e+03  -1.941220e-10  9.044e-07  3.149e+00  
>  GE29   -3.52e-06 7.20e+00  -6.810716e+03  1.995358e-10   3.314e-07  3.137e+00  
>  GE30   -1.04e-06 7.20e+00  -6.810716e+03  -2.235110e-10  4.788e-07  3.143e+00  
>  GE31   5.20e-06  7.20e+00  -6.810716e+03  2.598605e-10   3.033e-07  3.153e+00  
>  GE32   1.26e-06  7.20e+00  -6.810716e+03  7.579265e-11   2.780e-07  3.140e+00  
>  GE33   9.20e-07  7.20e+00  -6.810716e+03  2.969834e-10   1.773e-07  3.152e+00  
>  GE34   1.11e-06  7.20e+00  -6.810716e+03  -6.960550e-11  2.170e-07  3.145e+00  
>  GE35   1.49e-06  7.20e+00  -6.810716e+03  -3.866972e-10  1.844e-07  3.142e+00  
>  GE36   1.92e-06  7.20e+00  -6.810716e+03  2.745550e-10   2.575e-07  3.152e+00  
>  GE37   9.57e-07  7.20e+00  -6.810716e+03  -2.389789e-10  1.639e-07  3.137e+00  
>  GE38   9.45e-07  7.20e+00  -6.810716e+03  -9.280733e-11  1.703e-07  3.154e+00  
>  GE39   9.50e-07  7.20e+00  -6.810716e+03  2.227376e-10   1.757e-07  3.156e+00  
>  GE40   8.39e-07  7.20e+00  -6.810716e+03  1.059550e-10   1.528e-07  3.154e+00  
>  GE41   -9.93e-09 7.20e+00  -6.810716e+03  4.098990e-11   1.696e-07  3.158e+00  
>  GE42   -1.92e-06 7.20e+00  -6.810716e+03  1.624128e-11   2.071e-07  3.148e+00  
>  GE43   -2.13e-06 7.20e+00  -6.810716e+03  4.795045e-11   2.024e-07  3.152e+00  
>  GE44   -6.66e-07 7.20e+00  -6.810716e+03  -4.098990e-11  1.702e-07  3.147e+00  
>  GE45   -6.90e-07 7.20e+00  -6.810716e+03  -4.624898e-10  1.537e-07  3.163e+00  
>  GE46   -6.62e-07 7.20e+00  -6.810716e+03  2.977568e-10   1.476e-07  3.150e+00  
>  GE47   -5.60e-07 7.20e+00  -6.810716e+03  4.872385e-11   1.440e-07  3.144e+00  
>  GE48   -5.50e-07 7.20e+00  -6.810716e+03  -1.268367e-10  1.440e-07  3.135e+00  
>  GE49   -7.25e-07 7.20e+00  -6.810716e+03  -3.402935e-11  1.643e-07  3.146e+00  
>  GE50   -1.27e-06 7.20e+00  -6.810716e+03  -2.428458e-10  2.241e-07  3.148e+00  
>  GE51   -4.79e-07 7.20e+00  -6.810716e+03  1.515853e-10   1.237e-07  3.139e+00  
>  GE52   -5.18e-07 7.20e+00  -6.810716e+03  6.032476e-11   1.247e-07  3.155e+00  
>  GE53   1.77e-07  7.20e+00  -6.810716e+03  -6.573852e-11  1.425e-07  3.150e+00  
>  GE54   5.42e-07  7.20e+00  -6.810716e+03  2.753284e-10   1.303e-07  3.152e+00  
>  GE55   7.47e-07  7.20e+00  -6.810716e+03  -2.041761e-10  1.377e-07  3.155e+00  
>  GE56   8.41e-07  7.20e+00  -6.810716e+03  -9.126054e-11  1.376e-07  3.148e+00  
>  GE57   1.41e-06  7.20e+00  -6.810716e+03  2.003091e-10   1.525e-07  3.155e+00  
>  GE58   2.12e-06  7.20e+00  -6.810716e+03  -8.507338e-11  1.704e-07  3.142e+00  
>  GE59   1.16e-06  7.20e+00  -6.810716e+03  1.840679e-10   1.545e-07  3.156e+00  
>  GE60   9.37e-07  7.20e+00  -6.810716e+03  -5.877797e-11  1.477e-07  3.162e+00  
>  GE61   1.59e-07  7.20e+00  -6.810716e+03  6.573852e-11   1.588e-07  3.155e+00  
>  GE62   1.59e-06  7.20e+00  -6.810716e+03  -3.866972e-10  1.484e-07  3.143e+00  
>  GE63   1.10e-06  7.20e+00  -6.810716e+03  3.743229e-10   1.505e-07  3.150e+00  
>  GE64   8.64e-07  7.20e+00  -6.810716e+03  9.126054e-11   1.612e-07  3.137e+00  
>  GE65   -1.08e-06 7.20e+00  -6.810716e+03  -3.255990e-10  2.065e-07  3.162e+00  
>  GE66   -4.69e-06 7.20e+00  -6.810716e+03  3.016238e-11   3.239e-07  3.182e+00  
>  GE67   -4.93e-06 7.20e+00  -6.810716e+03  4.176330e-11   2.731e-07  3.153e+00  
>  GE68   -3.71e-06 7.20e+00  -6.810716e+03  1.887082e-10   2.962e-07  3.161e+00  
>  GE69   -2.54e-06 7.20e+00  -6.810716e+03  -1.469449e-10  1.738e-07  3.147e+00  
>  GE70   -2.09e-06 7.20e+00  -6.810716e+03  1.160092e-10   1.593e-07  3.148e+00

and 

>  GE1    -1.69e-15 4.81e+00  -6.810419e+03  0.000000e+00   1.441e-01  2.204e+00  
>  GE2    6.88e-11  6.02e+00  -6.808222e+03  2.197620e+00   1.322e-01  3.161e+00  
>  GE3    -6.43e-10 6.19e+00  -6.811732e+03  -3.510024e+00  1.266e-01  3.168e+00  
>  GE4    -1.73e-09 6.28e+00  -6.811927e+03  -1.949197e-01  8.083e-02  3.146e+00  
>  GE5    4.89e-08  6.41e+00  -6.811870e+03  5.620519e-02   3.561e-02  3.155e+00  
>  GE6    -3.53e-06 6.68e+00  -6.812077e+03  -2.067004e-01  2.896e-02  3.137e+00  
>  GE7    2.75e-04  6.76e+00  -6.812103e+03  -2.620147e-02  6.846e-03  3.147e+00  
>  GE8    8.91e-04  6.74e+00  -6.812111e+03  -7.944057e-03  6.863e-03  3.180e+00  
>  GE9    -9.94e-02 6.72e+00  -6.819571e+03  -7.459643e+00  5.715e-03  3.139e+00  
> SCF restart after this step!
>  GE10   5.71e-01  6.85e+00  -6.811947e+03  7.624119e+00   3.044e-02  3.140e+00  
>  GE11   2.19e-01  6.75e+00  -6.812093e+03  -1.461710e-01  7.338e-03  3.140e+00  
>  GE12   -2.19e-01 6.74e+00  -6.812109e+03  -1.616821e-02  1.353e-02  3.152e+00  
>  GE13   -1.25e-01 6.74e+00  -6.812103e+03  5.742607e-03   9.216e-03  3.142e+00  
>  GE14   1.25e-01  6.73e+00  -6.812116e+03  -1.256051e-02  3.973e-03  3.165e+00  
>  GE15   -1.09e-01 6.72e+00  -6.812117e+03  -1.053064e-03  3.591e-03  3.137e+00  
>  GE16   -1.25e-01 6.72e+00  -6.812117e+03  2.913601e-04   4.280e-03  3.138e+00  
>  GE17   -1.25e-01 6.72e+00  -6.812116e+03  7.344074e-04   4.135e-03  3.143e+00  
>  GE18   -9.87e-02 6.72e+00  -6.812117e+03  -1.137833e-03  3.003e-03  3.143e+00  
>  GE19   -1.25e-01 6.72e+00  -6.812117e+03  4.225479e-04   4.105e-03  3.146e+00  
>  GE20   -1.25e-01 6.72e+00  -6.812117e+03  -1.535089e-04  4.002e-03  3.139e+00  
>  GE21   -1.25e-01 6.72e+00  -6.812116e+03  8.022487e-04   4.051e-03  3.236e+00  
>  GE22   -1.04e-02 6.72e+00  -6.812116e+03  -5.407012e-04  2.392e-03  3.188e+00  
>  GE23   3.55e-02  6.73e+00  -6.812119e+03  -2.480230e-03  2.707e-03  3.164e+00  
>  GE24   1.88e-01  6.73e+00  -6.812113e+03  5.975040e-03   8.199e-03  3.469e+00  
>  GE25   1.02e-01  6.72e+00  -6.812116e+03  -3.304604e-03  4.018e-03  3.139e+00  
>  GE26   6.34e-03  6.72e+00  -6.812116e+03  -1.884069e-04  2.159e-03  3.140e+00  
>  GE27   3.98e-02  6.72e+00  -6.812117e+03  -1.530208e-04  2.238e-03  3.296e+00  
>  GE28   1.09e-01  6.72e+00  -6.812117e+03  -4.207834e-04  4.331e-03  3.184e+00  
>  GE29   1.25e-01  6.72e+00  -6.812117e+03  2.650295e-04   4.912e-03  3.136e+00  
>  GE30   1.25e-01  6.72e+00  -6.812114e+03  2.871055e-03   4.928e-03  3.148e+00  
>  GE31   -1.49e-10 6.72e+00  -6.812118e+03  -3.892846e-03  2.185e-03  3.176e+00  
>  GE32   -1.01e-01 6.73e+00  -6.812118e+03  2.320563e-04   5.218e-03  3.153e+00  
>  GE33   -5.64e-02 6.73e+00  -6.812118e+03  -8.743608e-04  3.003e-03  3.170e+00  
>  GE34   -3.76e-02 6.72e+00  -6.812117e+03  1.428027e-03   2.661e-03  3.139e+00  
>  GE35   -8.19e-10 6.72e+00  -6.812118e+03  -5.989148e-04  2.090e-03  3.167e+00  
>  GE36   -1.38e-03 6.72e+00  -6.812117e+03  7.239924e-04   2.280e-03  3.168e+00  
>  GE37   -4.20e-02 6.72e+00  -6.812117e+03  2.527598e-04   2.174e-03  3.152e+00  
>  GE38   -4.79e-10 6.72e+00  -6.812117e+03  -6.379407e-04  2.083e-03  3.294e+00  
>  GE39   -1.36e-10 6.72e+00  -6.812117e+03  -1.013951e-04  1.985e-03  3.154e+00  
>  GE40   -1.25e-01 6.72e+00  -6.812117e+03  3.407705e-04   5.015e-03  3.163e+00  
>  GE41   -1.25e-01 6.72e+00  -6.812117e+03  3.166437e-04   4.826e-03  3.220e+00  
>  GE42   -8.72e-10 6.72e+00  -6.812117e+03  -7.778456e-04  1.969e-03  3.158e+00  
>  GE43   9.82e-05  6.72e+00  -6.812119e+03  -1.535610e-03  1.487e-03  3.176e+00  
>  GE44   3.13e-02  6.73e+00  -6.812119e+03  -2.586304e-04  2.341e-03  3.161e+00  
>  GE45   3.13e-02  6.73e+00  -6.812118e+03  1.473629e-03   2.132e-03  3.157e+00  
>  GE46   -2.09e-11 6.73e+00  -6.812119e+03  -1.273087e-03  8.214e-04  3.164e+00  
>  GE47   -4.47e-11 6.73e+00  -6.812119e+03  1.929944e-05   7.394e-04  3.238e+00  
>  GE48   1.48e-10  6.73e+00  -6.812119e+03  -6.232216e-05  6.591e-04  3.144e+00  
>  GE49   3.10e-10  6.73e+00  -6.812119e+03  -2.730031e-05  6.218e-04  3.144e+00  
>  GE50   3.46e-10  6.73e+00  -6.812119e+03  1.050580e-04   5.918e-04  3.155e+00  
>  GE51   -3.76e-10 6.73e+00  -6.812119e+03  -2.058650e-04  6.254e-04  3.153e+00  
>  GE52   -4.53e-10 6.73e+00  -6.812119e+03  6.798742e-06   5.389e-04  3.162e+00  
>  GE53   -4.00e-10 6.73e+00  -6.812119e+03  -1.949580e-05  4.329e-04  3.139e+00  
>  GE54   -3.79e-10 6.73e+00  -6.812119e+03  6.909002e-05   4.391e-04  3.153e+00  
>  GE55   -1.55e-11 6.73e+00  -6.812119e+03  -7.688090e-05  2.111e-04  3.141e+00  
>  GE56   -1.68e-11 6.73e+00  -6.812119e+03  -5.754008e-07  1.601e-04  3.138e+00  
>  GE57   5.72e-11  6.73e+00  -6.812119e+03  -4.985439e-06  8.607e-05  3.146e+00  
>  GE58   5.31e-11  6.73e+00  -6.812119e+03  -4.250220e-07  7.195e-05  3.143e+00  
>  GE59   6.48e-12  6.73e+00  -6.812119e+03  -7.105584e-07  2.961e-05  3.149e+00  
>  GE60   3.49e-12  6.73e+00  -6.812119e+03  -9.972921e-08  1.631e-05  3.152e+00  
>  GE61   2.77e-12  6.73e+00  -6.812119e+03  5.425362e-09   1.334e-05  3.146e+00  
>  GE62   -9.09e-13 6.73e+00  -6.812119e+03  -1.593734e-08  6.632e-06  3.154e+00  
>  GE63   -9.26e-13 6.73e+00  -6.812119e+03  -3.473314e-09  2.924e-06  3.155e+00  
>  GE64   -6.61e-13 6.73e+00  -6.812119e+03  6.187155e-12   2.322e-06  3.156e+00  
>  GE65   -3.07e-13 6.73e+00  -6.812119e+03  -4.261403e-10  1.101e-06  3.151e+00  
>  GE66   -2.69e-13 6.73e+00  -6.812119e+03  -1.075018e-10  8.018e-07  3.139e+00  
>  GE67   -2.75e-13 6.73e+00  -6.812119e+03  3.557614e-11   6.439e-07  3.141e+00  
>  GE68   1.52e-13  6.73e+00  -6.812119e+03  -1.569991e-10  3.814e-07  3.153e+00  
>  GE69   1.74e-13  6.73e+00  -6.812119e+03  1.778807e-11   3.189e-07  3.138e+00  
>  GE70   -3.07e-14 6.73e+00  -6.812119e+03  -3.093578e-11  8.282e-08  3.142e+00

**Comment by dyzheng** [comment]
It looks that kerker mixing would lead to unconvergence when DRHO less than 1e-4 or 1e-5, I would like to use a feature that close kerker mixing when DRHO is small enough. @WHUweiqingzhou 
the test case is : 
[Fe-AFM.zip](https://github.com/deepmodeling/abacus-develop/files/14368799/Fe-AFM.zip)
