### ISSUE TITLE
no

### ISSUE THREAD

**Issue by yl960122** [deepmodeling/abacus-develop#3590]
### Describe the bug

"I encountered many macro definition issues when compiling abacus-3.5.2, and I added many macro definitions in the file module_hamilt_general/module_xc/xc_funcs.h. However, I am not sure if it i
![abacus](https://github.com/deepmodeling/abacus-develop/assets/65180595/6eca904a-4a7f-4406-8d84-bee65db017f3)
s appropriate to do so."

### Expected behavior

"It appears that the compilation was successful. "
![success](https://github.com/deepmodeling/abacus-develop/assets/65180595/667a4fa7-da2a-42c0-bad0-f68f6c7e1bff)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@yl960122,
Have you tried to turn on `-DENABLE_LIBXC=ON`? If not, please try this.

**Comment by yl960122** [comment]
After recompiling with the -DENABLE_LIBXC=ON option turned on, I still get the same error. I think there is a macro definition missing in the source code, and some cpp source files don't include a header declaration.
![abacus](https://github.com/deepmodeling/abacus-develop/assets/65180595/97446993-2a1b-4776-96f3-c7fce1c79777)

**Comment by yl960122** [comment]
Environment 
OS: centos7.6 
Compiler: gcc 10.2.0 
Dependencies: ELPA, libxc, cereal


# The compilation process
export ELPA_ROOT=./abacus-develop-3.4.3/source/deps/elpa-2021.05.002/install 
export LIBXC_ROOT=./abacus-develop-3.4.3/source/deps/libxc-5.2.3/install 
export CEREAL_ROOT=./abacus-develop-3.4.3/source/deps/cereal

cmake ../ -DCMAKE_INSTALL_PREFIX=./install \ -DCMAKE_C_COMPILER=mpiicc \ -DCMAKE_CXX_COMPILER=mpiicpc \ -DCMAKE_Fortran_COMPILER=mpiifort \ -DENABLE_LIBXC=ON \ - DELPA_DIR=$abacus-develop-3.4.3/source/deps/cereal \ - DELPA_DIR=$abacus-develop-3.4.3/source/deps/cereal cmake .DELPA_DIR=$ELPA_ROOT \ -DELPA_INCLUDE_DIR=$ELPA_ROOT\include \ -DCEREAL_INCLUDE_DIR=$CEREAL_ROOT/include \ -DLibxc_DIR=$LIBXC_ROOT

make 
make install

**Comment by WHUweiqingzhou** [comment]
@yl960122,
I notice that you change the title to `no`. Did you want to reply to me 'no'?
Has issue been solved after `-DENABLE_LIBXC=ON`? If solved, please let us know.
