### ISSUE TITLE
Automatic switch to gamma_only calculation

### ISSUE THREAD

**Issue by scott-5** [deepmodeling/abacus-develop#3591]
### Background

For a larger system, when setting kspacing, only one k-point is often obtained. Actually, users can manually change `kspacing` to `gamma_only` to accelerate calculations.

### Describe the solution you'd like

If the program can determine whether to switch to `gamma_only` when there is only one k-point, that will save users from frequent changes to the INPUT. I am not sure if implementing this feature will result in significant code changes.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by WHUweiqingzhou** [comment]
Thanks for your feedback. I think it is a reasonable idea, we will think about it.

**Comment by hongriTianqi** [comment]
The STRU and KPT files are read after esolver is built, which cause difficulty to solve this issue. In other words, it needs substantial development before this issue can be solved.

**Comment by WHUweiqingzhou** [comment]
We design this feature on purpose. We think someone set `kspacing`, indicating that they do not want Gamma-Only Calculations.
