### ISSUE TITLE
ABACUS will output two fermi energy when set nupdown

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3595]
### Describe the bug

If one set nupdown parameter (not 0) in INPUT, ABACUS will output two fermi energy:  E_Fermi_up and E_Fermi_dw. It seams unreasonable. For one system, there should has only one fermi energy. ABACUS should sum both spin up and spin down.

![image](https://github.com/deepmodeling/abacus-develop/assets/91927439/9463861b-cef0-40b8-955f-e113cf4766e3)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@pxlxingliang,
Actually, two fermi-energy is necessary for keeping number of electrons obey the magnetic moment defined in `NUPDOWN`.
According to https://www.vasp.at/forum/viewtopic.php?t=18543, only fermi energy of down channel is printed in VASP, which is not well-defined.
