### ISSUE TITLE
Docs: request docs to show how to perform ABACUS calculations in different devices

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#3613]
### Details

we need some docs to show how to perform ABACUS calculations in different device, f.e DCU/GPU.

### Have you read the online manual http://abacus.deepmodeling.com/en/latest/

- [X] Yes, I have read the online manual.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific section of the documentation with the issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Update the documentation to address the issue, following the suggested improvement.
- [ ] Ensure the updated documentation adheres to the project's documentation standards.
- [ ] Test the updated documentation to ensure it is clear and accurate.
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Publish the updated documentation and notify the issue reporter.

**Comment by pxlxingliang** [comment]
I have written a document about how to use the DCU ABACUS on Sugon platform:  https://dptechnology.feishu.cn/docx/MNmNdOevCo2QWWxhxKBctLPdn9e
