### ISSUE TITLE
Question: unexpected phase exists in `OVERLAP_Q` matrix <psi|jY>, where does it come from?

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#3616]
### Details

@jinzx10 and I find the `OVERLAP_Q` matrix in `orb_matrx*` output files always has a constant phase, for example given, the generation of Si numerical atomic orbital, has real/imag as a uniform value of -2.13. Not sure about whether it will cause some unexpected behavior when generating numerical orbitals.

$\langle\psi_n(\mathbf{k})|j_l\left(q\right) Y_{lm}\rangle =\sum_{\mathbf{G}}{c_{n\mathbf{G}}^{*}(\mathbf{k})\langle \mathbf{G}+\mathbf{k}|j_l\left( q \right) Y_{lm}\rangle}$

$=\sum_{\mathbf{G}}{c_{n\mathbf{G}}^{*}(\mathbf{k})\int{\mathrm{d}\mathbf{r}}e^{-i\mathbf{G}\cdot\mathbf{r}}j_l\left(qr \right) Y_{lm}\left( \hat{\mathbf{r}}\right)}$

$=4\pi\left(-i\right)^l\sum_{\mathbf{G}}{c_{n\mathbf{G}}^{*}(\mathbf{k})Y_{lm}(\hat{\mathbf{G}})\int{\mathrm{d}r\,\,r^2j_l\left( Gr \right) j_l\left( qr \right)}}$

There is not any phase factor can emerge from this formulation.

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by kirk0830** [comment]
Seems for different systems, the const phase varies:
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/010d0a74-3aac-44b7-8f57-dc2937791c40)
But for different derivative order, seems const phases are identical:
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/cdecdd63-181e-4075-98bc-4420dca49f93)
This is from <OVERLAP_Q> of Si-trimer with bond length 2.6, **const phase -1.37**
Adviced by @jinzx10, divide the phase from the number whose norm is maximal, say:
for one number written as $r_1e^{i\theta_1}$, then for another complex number $r_2e^{i\theta_2}$, after removal of phase from the first complex number, is:
$r_2e^{i(\theta_2-\theta_1)}$  
of which the imaginary part is:  
$r_2\sin(\theta_2-\theta_1)=r_2(\sin\theta_2\cos\theta_1-\cos\theta_2\sin\theta_1)$  
or say:  
$\Im_2^\prime=\Im_2\cos\theta_1-\Re_2\sin\theta_1$
![img_v3_028a_50e481ef-d8d6-4c79-b204-4c1fdff5551g](https://github.com/deepmodeling/abacus-develop/assets/67682086/716e74ec-f5c0-43e3-bf74-d5b7ec96f202)

**Comment by kirk0830** [comment]
the random const phase may generate from diagonalization.

**Comment by WHUweiqingzhou** [comment]
could you try CG method?

**Comment by kirk0830** [comment]
> could you try CG method?

@WHUweiqingzhou yes, I did try CG method but phase presists. It is not the problem that algorithm-specific, @jinzx10 will explain more.

**Comment by jinzx10** [comment]
First of all, our current gamma-only calculation are not handled specifically to guarantee a real real-space wave function, so an overall phase could exist. 

Moreover, @kirk0830 and I just realized that, in the presence of degeneracy, current gamma-only calculations cannot even guarantee that the real-space wave functions have a form of 【overall phase】 $\times$【real function】 for degenerate states. Suppose there exists two degenerate eigenstates with real real-space wave functions $\psi_1(r)$ and $\psi_2(r)$, the present diagonalization scheme may actually yield something like $\psi_1(r) + i\psi_2(r)$ and $\psi_1(r) - i\psi_2(r)$, both of which have non-trivial phases. Therefore, the following behavior should be expected: 
- non-degenerate state may carry an overall phase;
- degenerate states may carry non-trivial phases; but let $Y = \langle\psi|jY\rangle$ ,  $Y^{\dagger}Y$ should eliminate such mixing and yield real quantities. 

I applied the above test to a Si orbital generation and found that the maximum imaginary part of $Y^{\dagger}Y$ is less than  $10^{-5}$, which suggests that everything might be OK.
