### ISSUE TITLE
The deepks model doesn't work as well as the tutorial which is training with a single water molecule.

### ISSUE THREAD

**Issue by yycx1111** [deepmodeling/abacus-develop#3627]
### Details

Background
Use the file provided by Notebooks to follow the tutorial's instructions for deepks training for a single water molecule. Use the generated deepks model for SCF calculations and compare the results with those under the PBE functional and the LDA functional.
Result
The computation time is longer than that under the PBE functional, and the ground state energies differ from those computed under the PBE functional and do not match the results presented. Modifying the training parameters, using different training sets, and increasing the number of training rounds did not yield results as expected.
Questions
1. How many training sets were used and how many rounds of training were performed to achieve such good results in the case study? 
2. What adjustments should be made in this training to make the results as explained in the video?
3. If I use this set of methods for deepks training in other systems, how do I get a training set? What is the method to make the training set?
[单一水分子训练结果不符合预期.zip](https://github.com/deepmodeling/abacus-develop/files/14369159/default.zip)

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by dyzheng** [comment]
Can you give me your .ptg model file and the ABACUS input files containes of "INPUT, STRU, KPT" , I want to retest it.
Another question is which version of ABACUS did you used? v3.1.4 or the latest v3.5.3?

**Comment by yycx1111** [comment]
> Can you give me your .ptg model file and the ABACUS input files containes of "INPUT, STRU, KPT" , I want to retest it. Another question is which version of ABACUS did you used? v3.1.4 or the latest v3.5.3?

The deepks training was performed in abacus:3.1.4-toolkit-notebook. SCF calculation was performed in abacus v3.5.0 because the SCF calculation in v3.1.4 reported the error "abacus: error while loading shared libraries: libmkl_cdft_core.so.2: cannot open shared object file: No such file or directory".
[input files.zip](https://github.com/deepmodeling/abacus-develop/files/14369777/input.files.zip)

**Comment by dyzheng** [comment]
[retest-results.zip](https://github.com/deepmodeling/abacus-develop/files/14369861/retest-results.zip)
I have retested your test case with your deepks model, I think the result is correct.
You should be care for the setting of "dft_functional" in INPUT file, which is default same with the pseudopotential file (in this case : pbe), I set this parameter to "lda" with deepks model is used, which can get pbe-like results with lda-like efficiency. 

Can you retry with this suggestion?

**Comment by dyzheng** [comment]
Another important notation is that users would better not train deepks model with ABACUS v3.5.0, versions before v3.4.3 and after v3.5.1 is correct with printing DeePKS labels for training models.

**Comment by yycx1111** [comment]
> [retest-results.zip](https://github.com/deepmodeling/abacus-develop/files/14369861/retest-results.zip) I have retested your test case with your deepks model, I think the result is correct. You should be care for the setting of "dft_functional" in INPUT file, which is default same with the pseudopotential file (in this case : pbe), I set this parameter to "lda" with deepks model is used, which can get pbe-like results with lda-like efficiency.
> 
> Can you retry with this suggestion?

Yes, I can. After setting "dft_functional" to "lda", I get the expected results. Thank you!

**Comment by yycx1111** [comment]
> Another important notation is that users would better not train deepks model with ABACUS v3.5.0, versions before v3.4.3 and after v3.5.1 is correct with printing DeePKS labels for training models.

Okay, I got it. Thanks you!
