### ISSUE TITLE
Need the auto test of abacus running on DCU

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3631]
### Describe the Testing Issue

In abacus dailytest, there has no testing about running of abaucs on DCU. 

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by caic99** [comment]
@pxlxingliang FYI: You can use [OpenAPI](https://ac.sugon.com/ac/openapi/doc/2.0/api/jobmanager/job.html) to submit jobs on the Sugon platform.

**Comment by WHUweiqingzhou** [comment]
@pxlxingliang has added a DCU test for abacus dailytest. Thanks for his effort!
