### ISSUE TITLE
Signal 9 met in dftu_new branch

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#3634]
### Describe the bug

I run a deltaspin calculation with nspin =4 on develop and dftu_new branch respectively:
dftu_new: https://bohrium.dp.tech/jobs/detail/11277338
develop: https://bohrium.dp.tech/jobs/detail/11277340

I met signal 9 error at 13th step for the dftu_new branch, but no error untill 26 step in the develop branch. There might be memory issues in the dftu_new branch.

### Expected behavior

The same behavior for develop and dftu_new branch.

### To Reproduce

to test dftu_new branch
[dftu.tar.gz](https://github.com/deepmodeling/abacus-develop/files/14372095/dftu.tar.gz)
to test develop branch
[dev.tar.gz](https://github.com/deepmodeling/abacus-develop/files/14372106/dev.tar.gz)

This is a Fe2 system

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by caic99** [comment]
Hi @hongriTianqi ,
Please check 计算节点->监控 in the bottom of your job page. The job failed due to out of memory error.

**Comment by WHUweiqingzhou** [comment]
So, it maybe solved by setting `ks_solver = 'scalapack_gvx'` a.t.m., and indicates our memory issue has not solved completely.

**Comment by dyzheng** [comment]
@hongriTianqi can you try #3637 to test whether memory increasing or not? I can't find memory leak in my developing machine.

**Comment by WHUweiqingzhou** [comment]
fixed by #3637
