### ISSUE TITLE
The finite difference of force cannot match well with the analytical value

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3645]
### Describe the bug

I use the GaAs system to do the finite difference test of force. The scf_thr is set to 1e-12, and  the symmetry is set to 0. The finite difference of As2 y direction is same as that by analytical, but for Ga1 x direction, there has a difference of 5e-5 eV/A difference between finite difference and analytical value.

[0 (3).zip](https://github.com/deepmodeling/abacus-develop/files/14402826/0.3.zip)

![a6f27474b5fd8915660824ed57066028_b1f4eef5-a788-4348-818f-758e49af8352](https://github.com/deepmodeling/abacus-develop/assets/91927439/2e462ca7-f544-427c-ad46-57a0c6825794)
![0261294c263d9816880c0ad0286d7cd9_add35ed2-8351-4799-9a75-016961f2550a](https://github.com/deepmodeling/abacus-develop/assets/91927439/f87265b2-1514-42d0-a5b6-973bdb7dfe44)

https://labs.dp.tech/projects/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.95-9b7afd

The INPUT is:
```
INPUT_PARAMETERS
#Parameters (1.General)
calculation             scf
ntype                   2
nbands                  46
symmetry                0

#Parameters (2.Iteration)
ecutwfc                 60
scf_thr                 1e-12
scf_nmax                100
cal_force               1
cal_stress              1
#Parameters (3.Basis)
basis_type              pw

#Parameters (4.Smearing)
smearing_method         gauss
smearing_sigma          0.002

#Parameters (5.Mixing)
mixing_type             broyden
mixing_beta             0.7
mixing_gg0              1.0
ks_solver               cg
pw_seed 1
```

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by jinzx10** [comment]
Hi @pxlxingliang , I think the step size used in finite difference deserves a more carefu selection, e.g., following the suggestion of

https://en.wikipedia.org/wiki/Numerical_differentiation#Step_size

Roughly speaking, numerical differentiation suffers from two errors: finite precision error and formula error. On the one hand, a large step size would lead to a large formula error; on the other hand, a small step size might make finite precision error significant. Therefore, there's usually some intermediate choice which minimizes the total numerical error.

If I understand correctly, total energies in SCF are evaluated with a precision up to scf_thr. If we take f(x)~7800, f''(x)~1.6, $\epsilon$~1e-12 in the recommended step size formula

$$
h = 2\sqrt{\epsilon\left|\frac{f(x)}{f''(x)}\right|}
$$

we'll get a step size of about 0.00014, which is about 3 times larger than the one used in the figure.

PS: I think we can try to reproduce the V-shaped log(error) vs. log(step size) curve to verify the above statement.

**Comment by jinzx10** [comment]
However, a real concern here is that the E vs. distance curve in the second figure is not symmetric. It seems to suggest that the energy is merely accurate up to 12 digits, but not the promised precision (1e-12).

**Comment by pxlxingliang** [comment]
I have done another test that increase the ecut_wfc from 60 Ry to 100 Ry, and increase K points from 7 7 7 to 11 11 11, and this time the difference between finite difference force and analytical force match well.
![e1cd8509303f7d53d821bccb47725557_20e55209-af48-41d4-a994-68a4c73c1eb0](https://github.com/deepmodeling/abacus-develop/assets/91927439/7385001c-f95e-464d-b333-b54fc36d409f)
![eb71945fbcf76d7330e070899e8c8fea_414abc63-a678-4fda-9ed7-d5dba4be0948](https://github.com/deepmodeling/abacus-develop/assets/91927439/0d214a54-dd6b-45e1-986f-b70fc9cb0a26)

JOB: https://labs.dp.tech/projects/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.95-b59e47

In the previous test, even the scf_thr is 1e-12, the energy precision cannot reach 1e-10~1e-12 eV, which is limited by ecut_wfc and K points.

**Comment by WHUweiqingzhou** [comment]
It has been solved.
