### ISSUE TITLE
KILLED BY SIGNAL: 9 (Killed) met in a deltaspin calculation

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#3652]
### Describe the bug

KILLED BY SIGNAL: 9 (Killed) met in a deltaspin calculation

See the result in https://bohrium.dp.tech/jobs/detail/11328068

### Expected behavior

No error.

### To Reproduce

[example.tar.gz](https://github.com/deepmodeling/abacus-develop/files/14416581/example.tar.gz)
This is a Fe16 system.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
fixed by #3637
