### ISSUE TITLE
Auto rotate coordinate to make orbital on standard direction in PDOS

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3653]
### Background

For the input coordinate, the direction of orbital may not exactly on standard direction, such as dxy may not exactly on xy platform.
And when I plot the PDOS, the atomic orbital (such as dxy, dyz,..) is not pure.

### Describe the solution you'd like

Auto rotate the coordinate to make the direction of orbital on standard direction.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by WHUweiqingzhou** [comment]
Please reopen it if anyone faces the same issue.
