### ISSUE TITLE
mulliken charge is  Inequivalent

### ISSUE THREAD

**Issue by Shen-Zhen-Xiong** [deepmodeling/abacus-develop#3655]
### Describe the bug

[issue_mulliken.tar.gz](https://github.com/deepmodeling/abacus-develop/files/14427838/issue_mulliken.tar.gz)
Please see details from test case "issue_mulliken.tar.gz". While I calculate Sr2Mn2O6 systems and output mulliken.txt file,  Total Charge on atom for two Mn is Unequal， one is 14.71, another is 13.28.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
hi @Shen-Zhen-Xiong,
we have fixed a bug about Mulliken charge in v3.5.3, have you tried the latest version?

**Comment by Shen-Zhen-Xiong** [comment]
Thanks your very much. I test the case in v3.5.1, when i try the v3.5.3, it is ok

**Comment by WHUweiqingzhou** [comment]
This bug has been fixed by PR #3503.
