### ISSUE TITLE
Need ouput the commit information in the DCU calculation

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3656]
### Background

The COMMIT_INFO option needs to be closed when compile the abacus with USE_ROCM=ON, while compiling the DCU version need set USE_ROCM=ON. So the calculation of DCU can not output the commit informations.

```
if(USE_ROCM)
  if(COMMIT_INFO)
    message(FATAL_ERROR "Commit info is not supported on ROCm. Try to recompile with cmake command -DCOMMIT_INFO=OFF.")
  endif()
```

### Describe the solution you'd like

Support the COMMIT_INFO=ON and USE_ROCM=ON when compiling DCU abacus

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by pxlxingliang** [comment]
I try to comment the FATAL_ERROR line in CMakeList.txt, and compile abacus with USE_ROCM and COMMIT_INFO with command `CC=clang CXX=clang++ cmake -B build-dcu -DUSE_OPENMP=OFF -DENABLE_LCAO=OFF -DUSE_ROCM=ON -DCOMMIT_INFO=ON`

```
if(USE_ROCM)
  if(COMMIT_INFO)
    #message(FATAL_ERROR "Commit info is not supported on ROCm. Try to recompile with cmake command -DCOMMIT_INFO=OFF.")
  endif()
```
I get the below errors:
```
CMake Warning (dev) at device_rocm_generated_xc_functional_op.hip.cu.o.cmake:33:
  Syntax Warning in cmake code at column 30

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

clang-14: error: no such file or directory: '0d1fcde (Wed Feb 28 11:25:51 2024 +0800)'
CMake Error at device_rocm_generated_xc_functional_op.hip.cu.o.cmake:126 (message):
  Error generating
  /public/home/abacus/abacus-dcu/build-dcu/source/CMakeFiles/device_rocm.dir/module_hamilt_general/module_xc/kernels/rocm/./device_rocm_generated_xc_functional_op.hip.cu.o


make[2]: *** [source/CMakeFiles/device_rocm.dir/build.make:183: source/CMakeFiles/device_rocm.dir/module_hamilt_general/module_xc/kernels/rocm/device_rocm_generated_xc_functional_op.hip.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:969: source/CMakeFiles/device_rocm.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```

**Comment by caic99** [comment]
@pxlxingliang I suggest using the [configure_file](https://cmake.org/cmake/help/latest/command/configure_file.html#example) feature of cmake to render version info string, but not passing complex compilation flags.
