### ISSUE TITLE
Mixing_restart should be more user friendly

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#3661]
### Background

Now, users can set "mixing_restart n" to drop history of Pulay mixing and use the n-th output charge density as the (n+1)-th input charge density.
It is hard to choose "n" for users.

### Describe the solution you'd like

I suggest use DRHO threshold for mixing_restart, such as "mixing_restart 1e-3" to drop Pulay history since DRHO<1e-3.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by WHUweiqingzhou** [comment]
To this end, I plan to define a new member of `Charge_Mixing`, like `chgmix.mixing_restart` to replace `GlobalV::MIXING_RESTART`.
1. I will value `chgmix.mixing_restart` as GlobalV::SCF_MAX at the first SCF step of every iteration.
2. change `GlobalV::MIXING_RESTART` from INT to double.
3. to make sure restart runs once, I will add a if(iter <= chgmix.mixing_restart) in `ESolver::Run()`.
