### ISSUE TITLE
Feature: Supports the calculation of local density of states.

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#3665]
### Background
local density of states is defined by:
$$D(\varepsilon,\mathbf{x})=\sum_{i}f_{i}||\psi(\varepsilon,\mathbf{x})\rangle|^2$$

ABACUS can calculate local density of states to simulate STM image.

### Describe the solution you'd like

Supports the calculation of local density of states.

**Comment by WHUweiqingzhou** [comment]
see #4192.

**Comment by kirk0830** [comment]
this feature has been implemented by @YuLiu98 in PR #6100, #6109 and #6123
