### ISSUE TITLE
ERROR：THE NUMBER OF PRIMITIVE CELL IS NOT AN INTEGER！

### ISSUE THREAD

**Issue by ieiue** [deepmodeling/abacus-develop#3668]
### Describe the bug

When making a calculation of cell-relax for Al108, here is an error at the relaxation step 13. 

### Expected behavior

How can I solve this problem.

### To Reproduce

[Al108_cell-relax(1).zip](https://github.com/deepmodeling/abacus-develop/files/14468195/Al108_cell-relax.1.zip)
Here are INPUT、STRU、KPT file、 pseudopotential and the orbital. 
I use ABACUS v3.4.0.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by ieiue** [comment]
![image](https://github.com/deepmodeling/abacus-develop/assets/116336560/a09cec54-8445-449c-b232-618e27b3d446)
Here is the error.

**Comment by maki49** [comment]
You can try a larger `symmetry_prec` (default=1e-6) in the INPUT file. For example: 
```
symmetry_prec 1e-5
```
