### ISSUE TITLE
Poor Convergence in AIMD Dataset Generation with VASP for Abacus Calculation

### ISSUE THREAD

**Issue by Shangguanying992** [deepmodeling/abacus-develop#3672]
### Describe the bug

While generating a dataset for AIMD using VASP and subsequent calculation with Abacus, I encountered the following issues:
Upon setting the lattice constant to 1 in VASP, I received the warning message "!!! WARNING: Some atoms are too close!!!!!! Please check the nearest-neighbour list". Additionally, the convergence was very poor, approximately 0.3.
After realizing that VASP uses Angstrom units, I adjusted the lattice constant to 1.8897259886. However, none of the configurations converged.
Upon inspecting the configurations, I did not notice significant deformations beyond the normal range for molecular dynamics simulations.

### Expected behavior

I am seeking guidance on addressing these issues to ensure proper convergence.

### To Reproduce

The system is transition metal oxides

### Environment

abacus 3.5.3
VASP 6.3.1
deepks

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@Shangguanying992 
could you offer us an example, including INPUT/KPT/STRU, we will make some tests.

**Comment by WHUweiqingzhou** [comment]
This issue has been solved by the feedback from @Shangguanying992
.
