### ISSUE TITLE
The performance of gnu-dav/omp-intel-dav/gnu-elpa/omp-intel-elpa in daily test is decreased

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3673]
### Details

Since 20240229, the performance of gnu-dav/omp-intel-dav/gnu-elpa/omp-intel-elpa in daily test is decreased.

![image](https://github.com/deepmodeling/abacus-develop/assets/91927439/e4f039dd-1de1-4432-b784-8c5830ee21eb)
![image](https://github.com/deepmodeling/abacus-develop/assets/91927439/fb8c94a9-4a58-480b-8a00-79656301dcc8)

https://labs.dp.tech/projects/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fsched-abacustest-summary-daily-b5e029

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by pxlxingliang** [comment]
The machine used at 2-28 and 2-29 are both c32_m64_cpu, and the cpu type are both "8269CY CPU @ 2.50GHz".
I have connected with Bohrium, and they are checking the difference of the machines used at two days.

**Comment by pxlxingliang** [comment]
I have tested the commit between 2-28 and 2-29


  | total time of 000_4GaAs in omp-intel-dav test
-- | --
tested on 02-28, commit: c1fb694 | 38.2067
tested on 03-04, commit: c1fb694 | 46.3295
tested on 03-04, commit: dfaa54d5 | 44.16
tested on 03-04, commit: 54b4268e | 43.84
tested on 03-04, commit: 0d1fcde5 | 43.81
tested on 02-28, commit: 67474ff | 46.1445

As we can see, the total time of example run by commit c1fb694 is different at 0228 and 0304. This indicate that the slower is not related to the different version of abacus.

**Comment by WHUweiqingzhou** [comment]
So, this reduction comes from different hardware?

**Comment by pxlxingliang** [comment]
> So, this reduction comes from different hardware?

Most likely, we are still in contact with Bohrium/Ali to check the hardware.

**Comment by WHUweiqingzhou** [comment]
> > So, this reduction comes from different hardware?
> 
> Most likely, we are still in contact with Bohrium/Ali to check the hardware.

Any update?

**Comment by WHUweiqingzhou** [comment]
Update 3/27:
Have not figured it out the reason of drop. but we plan to make a benchmarks.
