### ISSUE TITLE
Atomic force not consistent between analytic and finite difference results for a BCC Fe system

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#3685]
### Describe the bug

Atomic force not consistent between analytic and finite difference results for a BCC Fe system.
The test is presented here:
https://app.bohrium.dp.tech/abacustest?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.97-d70197

### Expected behavior

 Exact consistency between analytic and finite difference results of force for the BCC Fe system.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by wenfei-li** [comment]
Is there maybe a screenshot or something? It seems the link attached is not open to the public.

**Comment by WHUweiqingzhou** [comment]
> Is there maybe a screenshot or something? It seems the link attached is not open to the public.

Now the link is open to the public.

**Comment by dyzheng** [comment]
One possible reason is egg-box effect derived from grid-integral calculation, there is a method to avoid egg-box effect in finite-difference force calculation for LCAO base that set "basis_type  lcao_in_pw" to calculate the final energy using plane wave base to construct NAOs Hamiltonian. 

I hope the curve of FD-force from basis_type = lcao or lcao_in_pw can be coincident, if not, this will be a interested evidence that egg-box effect influent the FD-force.

Note: lcao_in_pw only can be used by "OMP_NUM_THREADS=n mpirun -np 1 abacus"

**Comment by pxlxingliang** [comment]
I have done some tests with more finite difference points with step size = 0.001 bohr, and there is a obvious difference between the analytic force and finite difference force.
https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.97-e306ee
![image](https://github.com/deepmodeling/abacus-develop/assets/91927439/5ad8a607-efb6-4351-995c-fbb4a5d04af0)

When I set the step size to 0.01 Bhor, it seems that the finite difference force match well with the analytical force.
https://app.bohrium.dp.tech/abacustest?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.97-770b66
![18293a5aadd1019c322aced82463fca0_7996992a-aa33-44cb-b290-f0a26b2abe43](https://github.com/deepmodeling/abacus-develop/assets/91927439/bad4a941-4f89-4a0e-bc57-827826aa4ed2)

But the RMSE of finite difference value and analytical value is the same grade (5.61e-3 and 1.28e-3 eV/A for step size 0.001 and 0.01 bohr respectively)

Use the same system, I also tested the performance in PW basis with the stepsize of 0.001 Bohr, and the RMSE is only 2.37 e-4 eV/A.
https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.97-43059a
![c7ec693fb19293d423cb713d1c402f2f_ce39778c-99b9-4675-988f-de88db9718d0](https://github.com/deepmodeling/abacus-develop/assets/91927439/c374e687-1599-4810-b94d-6de2d4cfb2b6)

These results indicate that the accuracy of force in PW basis is better than that in LCAO basis.

**Comment by pxlxingliang** [comment]
Another issue is that there may be eggbox effect as @dyzheng motioned.
The system in this test is two Fe atoms, and the fraction coordinates are [0,0,0] and [0.55,0.55,0.55] respectively.
These two atoms should be totally equivalent, but the finite difference plot of Fe1 and Fe 2 is different.

https://app.bohrium.dp.tech/abacustest?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.97-32121f

x|y|z
---|---|---
![624c4d56d03031ff4679c06b85cfa8bd_f7f194cd-c7cd-4f67-92c4-b616e606a923](https://github.com/deepmodeling/abacus-develop/assets/91927439/6e8c90cc-87f9-49e9-b7c5-5837f37095df) | ![838fad5878506aaadb3670fd614b34c1_85508fec-5730-4642-b860-26d6029b56ac](https://github.com/deepmodeling/abacus-develop/assets/91927439/a98672d0-f387-4eba-be15-b870717cd880)|![c345a10caa67414a90aafdc065eb7573_e03fae8b-3183-4163-a49d-b67fe59a92da](https://github.com/deepmodeling/abacus-develop/assets/91927439/d9934fe4-122c-4bb2-ae2b-e78565dcbf3f)
![ca05348cede17b7035d2eba0784a0034_3d1d7454-94ad-47d3-a816-550f334b56d5](https://github.com/deepmodeling/abacus-develop/assets/91927439/2865ce50-e350-430d-8e40-f75ec30ed997)|![36b627c86f2b029c807733564d66659e_81984daa-6488-4fc2-81ad-50021b6c1dc8](https://github.com/deepmodeling/abacus-develop/assets/91927439/a5092742-9b62-4943-b729-0c5a5e816e33)|![57573cc2a13981f7ccd98536367da888_6d9d11b1-1147-4eca-885e-7d147a6726e6](https://github.com/deepmodeling/abacus-develop/assets/91927439/9d24caef-9a5a-4606-b65e-bf4918d0600d)

The difference may be aroused from the eggbox effect.
I try increased the grids in real space by set ecutwfc to 200/400/800

ecutwfc|Fe1|Fe2
---|---|---
150| ![image](https://github.com/deepmodeling/abacus-develop/assets/91927439/319d36c6-2c9a-408e-89bb-af5ce459f233)| ![image](https://github.com/deepmodeling/abacus-develop/assets/91927439/9363d3ea-061d-4231-a14f-ed58f09180aa)
200| ![d454526f6b55f4b5258207c17930ee86_28c2013b-b742-4358-aa62-c9b3f8120ae9](https://github.com/deepmodeling/abacus-develop/assets/91927439/efefcd0b-7d1c-4d7a-881f-80437a176a54)|![69d9a67984f8721d193efa3d69cef01f_141816d3-9d9f-465f-b454-671506626730](https://github.com/deepmodeling/abacus-develop/assets/91927439/371dd16c-c7f7-432b-9dde-aa33953852c0)
400| ![ac182e3558faa6662717d7a30b8cc19e_8f6dcf66-591a-436e-b290-fa8407588ce0](https://github.com/deepmodeling/abacus-develop/assets/91927439/f5bbca73-fe58-402a-913c-68c2b12fede5)|![6eab214eebe7249f3e7882ebb2a14c1c_32b262a6-cac4-4ead-bbcf-a9db66131838](https://github.com/deepmodeling/abacus-develop/assets/91927439/ccabecb8-b697-4e71-a7a8-2d1d527a45e6)
800| ![a0e17011008675f8dfb88b62f32c7077_9P7gTi9s5Us3zAAAAAElFTkSuQmCC](https://github.com/deepmodeling/abacus-develop/assets/91927439/29a8d3eb-d094-4bbb-b2ea-46b81806dd00)| ![Uploading 11730bfaee787865606181bcddb3392d_BNCCCGEEEIIIYQQQgghhBDiKSHBPyGEEEIIIYQQQgghhBBCCCGeEv8Hs22J7fNCJ0AAAAAASUVORK5CYII=.png…]()

As we can see, the RMSE decrease along with the increase of ecutwfc (grid in real space)

jobs:
ecutwfc=200: https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.97-15ba39
ecutwfc=400: https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.97-031124
ecutwfc= 800: https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.97-78aef6

**Comment by WHUweiqingzhou** [comment]
@pxlxingliang could you upload some new result, has it been figured out?

**Comment by pxlxingliang** [comment]
I have do the test with basis type = lcao_in_pw, and compared the finite difference force with the analytic force of LCAO basis
![7d775f22cbd5ad3c25ed95aa998bca35_2b8b9d32-aae5-4b71-be0e-75203aa59188](https://github.com/deepmodeling/abacus-develop/assets/91927439/96d6914f-9721-452d-b3e4-a9be55a1102f)

NOTE: The energy difference between v3.0.0 and lcao_in_pw is from the fix of two-center integral.

As we can see, the finite difference force has good linearity, and is very close to the LCAO analytic value. This indicate that the mismatch of finite difference and analytic force is from the grid integral.
