### ISSUE TITLE
Feature: QO might be highly parallelized on both cell vectors R and k vectors

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#3688]
### Describe the Code Quality Issue

Not sure if it is of high priority, but once cell vectors are scanned, it can be distributed to different processors to do two-center-integrals respectively, then turn to k point parallelization to print different `QO_ovlp_ik.dat` files. A feasible (R, k) two dimensional parallelism strategy might be the key.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by WHUweiqingzhou** [comment]
ABACUS offers K-point Parallelization for PW calculations currently, you can see https://abacus.deepmodeling.com/en/latest/advanced/scf/performance.html#k-point-parallelization
