### ISSUE TITLE
Tests building doesn't build when ELPA version is 2023.05.001-1

### ISSUE THREAD

**Issue by Flying-dragon-boxing** [deepmodeling/abacus-develop#3689]
### Describe the Testing Issue

In `module_hsolver/my_elpa.h`,
``` c++
// ELPA only provides a C interface header, causing inconsistence of complex
// between C99 (e.g. double complex) and C++11 (std::complex).
// Thus, we have to define a wrapper of complex over the c api
// for compatiability.
#define complex _Complex
#include <elpa/elpa_generated.h>
#undef complex
#include <elpa/elpa_generic.h>
```
This works fine on ELPA version 2021.11.001-1, which ships with Ubuntu 22.04. However on newer versions, 2023.05.001-1 for example, the C++ interface seems to have been implemented: 
``` c++
 #ifdef __cplusplus
 #define double_complex std::complex<double>
 #define float_complex std::complex<float>
 extern "C" {
 #else
 #define double_complex double complex
 #define float_complex float complex
 #endif

// whatever

 #ifdef __cplusplus
 }
 #endif
```
This judgement of  marco `__cplusplus` conflicts with current building process for tests, generating errors below: 
``` bash
/home/username/documents/projects/abacus-develop/source/module_hsolver/my_elpa.h:22:17: 错误：expected identifier before ‘_Complex’
   22 | #define complex _Complex
      |                 ^~~~~~~~
In file included from /home/username/documents/abacus-develop/source/module_hsolver/my_elpa.h:23:
/usr/include/elpa_openmp-2023.05.001/elpa/elpa_generated.h:176:90: 错误：expected ‘,’ or ‘...’ before ‘<’ token
  176 |  void elpa_hermitian_multiply_a_h_a_dc(elpa_t handle, char uplo_a, char uplo_c, int ncb, double_complex *a, double_complex *b, int nrows_b, int ncols_b, double_complex *c, int nrows_c, int ncols_c, int *error);
      |                                                                                          ^~~~~~~~~~~~~~
/home/username/documents/abacus-develop/source/module_hsolver/my_elpa.h:22:17: 错误：expected identifier before ‘_Complex’
   22 | #define complex _Complex
      |                 ^~~~~~~~
/usr/include/elpa_openmp-2023.05.001/elpa/elpa_generated.h:177:90: 错误：expected ‘,’ or ‘...’ before ‘<’ token
  177 |  void elpa_hermitian_multiply_a_h_a_fc(elpa_t handle, char uplo_a, char uplo_c, int ncb, float_complex *a, float_complex *b, int nrows_b, int ncols_b, float_complex *c, int nrows_c, int ncols_c, int *error);
      |                                                                                          ^~~~~~~~~~~~~
# and even more errors
```
The unit tests doesn't build. Judgement for this may be added? 
``` c++
// in /usr/include/elpa_openmp-2023.05.001/elpa/elpa_version.h
#define ELPA_API_VERSION 20231705
#define ELPA_AUTOTUNE_API_VERSION 20231705
```

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by WHUweiqingzhou** [comment]
@caic99, could you have a look?

**Comment by caic99** [comment]
> @caic99, could you have a look?

Sorry, I'm not familiar with this part. @dyzheng @pplab Could you please help update the interface? Thanks.

**Comment by WHUweiqingzhou** [comment]
@dyzheng could you have a look.

**Comment by WHUweiqingzhou** [comment]
@Flying-dragon-boxing please see the solution in #3461
