### ISSUE TITLE
Unexpected ionic states in a series of LiCoO systems after nupdown calculations

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#3696]
### Describe the bug

The test report is presented here:
https://app.bohrium.dp.tech/abacustest?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.97-46416f

In the report table, Co atoms, Co3+ ions, Co4+ ions, O atoms, Li atoms are the number of atoms/ions expected.

Co3+ ions cal., Co4+ ions cal., O2- ions cal. Li+ ions cal. are the number of ions actually obtained after nupdown calculation.
They are obtained in the following way:
Co3+ should have spin 0, and the actual absolute value of the magnetic moment should not be larger than 0.5 uB.
Co4+ should have spin 1, and the actual absolute value of the magnetic moment should not deviate from 1 uB more than 0.5 uB.
Li+ should have spin 0, and the actual absolute value of the magnetic moment should not be larger than 1e-2 uB.
O2- should have spin 0, and the actual absolute value of the magnetic moment should not be larger than 0.2 uB.

'Co3+ compare' compares 'Co3+ ions' with 'Co3+ ions cal.', it is true if equal, otherwise false.
The same for 'Co4+ compare' to compare 'Co4+ ions' and 'Co4+ ions cal.',
'O2- compare' to compare 'O atoms' and 'O2- ions cal.'
'Li+ compare' to compare 'Li atoms' and 'Li+ ions cal.'

For example, the system Li3Co12O24-000 has calculated wrong number of Co3+ and Co4+ ions, we can check the magnetic moments here:
https://app.bohrium.dp.tech/abacustest?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.97-46416f

<img width="1350" alt="截屏2024-03-08 上午10 48 38" src="https://github.com/deepmodeling/abacus-develop/assets/18049272/b0bcda51-54ff-43a8-8ce0-1be02736788f">

The firstly 12 data from 0 to 11 are magnetic moments of Co ions:
we see that 4 numbers are close to zero, 7 numbers are close to one, with one data being 1.606, larger than 1.5. Which is unacceptable.

### Expected behavior

1. The convergence should be achieved for all the systems.

2. The number of ions calculated from the results of magnetic moments should equal to the expected values.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by hongriTianqi** [comment]
@dyzheng To update, the new magnetic moments method as raised in the dftu_new branch has been tested on the same series of materials, the report is represented here:
https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.97-cf6652

The input parameters for U were set as
```
dft_plus_u    1
orbital_corr  2 1 0
hubbard_u    5.14 0.0 0.0
```
for Co, O, Li, respectively.

By the way, the results from Mulliken population after the same calculation are presented here:
https://app.bohrium.dp.tech/abacustest?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.97-7902e8

**Comment by mohanchen** [comment]
Will close this issue since no actions are expected.
