### ISSUE TITLE
Suggest including pseudopotential information in the orbit file

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3704]
### Details

The orbital file required for ABACUS lcao calculation is generated by a specified pseudopotential, and the corresponding pseudopotential also needs to be matched during the calculation. So when generating orbital files, can we include the information of pseudopotentials in the orbital files? This can avoid the mismatch of pseudopotential and orbital in the calculation.

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by kirk0830** [comment]
It is a  very straightforward idea but in this case the name of section in STRU, like `ATOMIC_SPECIES` and/or `NUMERICAL_ORBITAL` may need to change accordingly, but we can deprecate the latter one and read both pseudpotential and numerical atomic orbital information from section `ATOMIC_SPECIES`, that possibly also makes sence and, in this case I would suggest future version of numerical atomic orbital also organize in xml format and, a direct result would be user can only use those pseudopotential-numerical atomic orbital bundle what ABACUS developer team provided.
```bash
ATOMIC_SPECIES
Si 1.000 Si_NCSG15_1.0.apob # apob = Abacus Pseudopotential numerical atomic Orbital Bundle
```

```xml
<APOB version="1.0">
  <PSEUDOPOTENTIAL>
    <UPF version="2.0.1">
      <!-- contents -->
    </UPF>
  </PSEUDOPOTENTIAL>
  <NUMERICAL_ORBITAL bessel_nao_ecut="100" bessel_nao_rcut="10" lmax="3" nzeta="4,2,2,1">
    <CHI.1 l="0">
      <!-- contents -->
    </CHI.1>
    <!-- contents -->
  </NUMERICAL_ORBITAL>
  <DFTU>
    <SHELL.1 l="2" onsite_radius="3"/>
    <SHELL.2 l="1" onsite_radius="2"/>
    <!-- contents -->
  </DFTU>
</APOB>
```
Is this a good idea? I wonder other developers' opinion. Also in that case, more atom-specific information can be embeded into the file, like DFTU the `onsite_radius`, suggested `ecutwfc`, etc.
@dyzheng @WHUweiqingzhou @jinzx10 
But ABACUS now has a rapidJson module, so what kind of format is preferred?...

**Comment by kirk0830** [comment]
Will add one line like:
```
---------------------------------------------------------------------------
Element                     As
Pseudopotential             [MD5 of pseudopotential file]
Energy Cutoff(Ry)           100
Radius Cutoff(a.u.)         9
Lmax                        2
Number of Sorbital-->       2
Number of Porbital-->       2
Number of Dorbital-->       1
---------------------------------------------------------------------------
```

**Comment by jinzx10** [comment]
> Will add one line like:
> 
> ```
> 
> ---------------------------------------------------------------------------
> 
> Element                     As
> 
> Pseudopotential             [MD5 of pseudopotential file]
> 
> Energy Cutoff(Ry)           100
> 
> Radius Cutoff(a.u.)         9
> 
> Lmax                        2
> 
> Number of Sorbital-->       2
> 
> Number of Porbital-->       2
> 
> Number of Dorbital-->       1
> 
> ---------------------------------------------------------------------------
> 
> ```

While this solution provides sufficient information for developers, I don't think it helps  users very much. I feels we might need an extra line of human-readable information.

**Comment by kirk0830** [comment]
> > Will add one line like:
> > ```
> > 
> > ---------------------------------------------------------------------------
> > 
> > Element                     As
> > 
> > Pseudopotential             [MD5 of pseudopotential file]
> > 
> > Energy Cutoff(Ry)           100
> > 
> > Radius Cutoff(a.u.)         9
> > 
> > Lmax                        2
> > 
> > Number of Sorbital-->       2
> > 
> > Number of Porbital-->       2
> > 
> > Number of Dorbital-->       1
> > 
> > ---------------------------------------------------------------------------
> > ```
> 
> While this solution provides sufficient information for developers, I don't think it helps users very much. I feels we might need an extra line of human-readable information.

I see, something like valence electrons?
