### ISSUE TITLE
Install the abacus failed with DCU on Sugon platform

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3706]
### Details

I try to install abacus (the latest version: v3.5.4) with DCU on Sugon platform with below commands:
```
module purge
module load compiler/rocm/dtk-22.10
module load compiler/devtoolset/7.3.1
module load compiler/cmake/3.17.2
module load mpi/hpcx/2.6.0/gcc-7.3.1

lib_path=/public/home/abacus/libs #the path of fftw，openblas和scalapack

test -d build-dcu || mkdir build-dcu

CC=clang CXX=clang++ cmake -B build-dcu -DUSE_OPENMP=OFF -DENABLE_LCAO=OFF -DFFTW3_DIR=${lib_path}/fftw-3.3.10/install -DLAPACK_DIR=${lib_path}/OpenBLAS_install/lib -DSCALAPACK_DIR=${lib_path}/scalapack-2.2.0 -DUSE_ROCM=ON -DCOMMIT_INFO=OFF

cd ./build-dcu
make
cd ..
```

But it is failed, and I get the error message:
![image](https://github.com/deepmodeling/abacus-develop/assets/91927439/e575f4da-02e1-47d2-bfc3-f3b9a8c4014a)

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by caic99** [comment]
Hi @pxlxingliang ,
Would you attach the whole configuring log as text? Thanks.

**Comment by pxlxingliang** [comment]
[test.zip](https://github.com/deepmodeling/abacus-develop/files/14583812/test.zip)
@caic99 Please check it.

**Comment by caic99** [comment]
@pxlxingliang And also the screen output, please

**Comment by caic99** [comment]
@yizeyi18 Could you please take a look? Seems that `LAPACK::LAPACK` target is not created correctly.
Ref: #3623

**Comment by yizeyi18** [comment]
In your command line, `LAPACK_DIR` was set as `${lib_path}/OpenBLAS_install/lib`; may you try  `${lib_path}/OpenBLAS_install`, as done in `SCALAPACK_DIR`?
#3623 should not affect here, as it is merged after release of v3.5.4; according to FindLAPACK.cmake, path to find `openblas` should be `${LAPACK_DIR}/lib`.

EDIT: here it seems #3623 was enabled for unknown reason:  `bfe2925` introduces `BLAS::BLAS` for compatibility to more BLAS library, which appeared here. 

EDIT2: The cmake log shows that libopenblas.so was found, but the target is still not found, this is strange. Which version of cmake do you use?

EDIT3: I see the cmake on Sugon Platform: `3.17.2` in `/public/software/compiler/cmake-3.17.2`, with its `FindBLAS.cmake` at `/public/software/compiler/cmake-3.17.2/share/cmake-3.17/Modules/FindBLAS.cmake`, an old script only sets `BLAS_LIBRARIES` but no target; similar does `FindLAPACK.cmake`. It's a tragedy that foretold in https://github.com/deepmodeling/abacus-develop/pull/3623#issuecomment-1960718144 becomes true.

**Comment by pxlxingliang** [comment]
I used a higher cmake version 3.23.3, and abacus can be installed successfully.

**Comment by caic99** [comment]
> EDIT3: I see the cmake on Sugon Platform: `3.17.2` in `/public/software/compiler/cmake-3.17.2`, with its `FindBLAS.cmake` at `/public/software/compiler/cmake-3.17.2/share/cmake-3.17/Modules/FindBLAS.cmake`, an old script only sets `BLAS_LIBRARIES` but no target; similar does `FindLAPACK.cmake`. It's a tragedy that foretold in [#3623 (comment)](https://github.com/deepmodeling/abacus-develop/pull/3623#issuecomment-1960718144) becomes true.

@yizeyi18 Since ABACUS supports CMake 3.16+, please add a target if not present for forward compatibility.

**Comment by yizeyi18** [comment]
@caic99 would we continue using cmake's FindBLAS/LAPACK in this fix, and add some wrapper to support old versions? Or go back to abacus's FindLAPACK?

**Comment by caic99** [comment]
> @caic99 would we continue using cmake's FindBLAS/LAPACK in this fix, and add some wrapper to support old versions? 

That would be fine!

**Comment by yizeyi18** [comment]
@caic99 PR submitted, please take a look.
