### ISSUE TITLE
KILLED BY SIGNAL: 9 (Killed) error

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3714]
### Describe the bug

For below system, ABACUS throw below error, after calculation of force:
```
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 38 RUNNING AT dp-lbg-471-11467972
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================
```
[057.zip](https://github.com/deepmodeling/abacus-develop/files/14609914/057.zip)

The INPUT is:
```
INPUT_PARAMETERS
calculation     scf
basis_type      pw
symmetry        0
ecutwfc 100
scf_thr 1e-08
scf_nmax 200
cal_force       1
cal_stress      1
kspacing        0.08
pseudo_rcut     10
pseudo_mesh     1
ks_solver       dav
smearing_method gauss
smearing_sigma 0.015
```
The system is an alloy of 36 Sr and 24 Al.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by pxlxingliang** [comment]
I try to use c32_m128_cpu machine (the previous machine is c32_m64_cpu, which memory is only 64G), and the memory is 128G. This time, the job can be calculated successfully.
[057 (2).zip](https://github.com/deepmodeling/abacus-develop/files/14611939/057.2.zip)

**Comment by WHUweiqingzhou** [comment]
@dyzheng,
do you think it is reasonable cost or not?
