### ISSUE TITLE
Magnetic moment: initial input is positive, but the final calculated result is negative

### ISSUE THREAD

**Issue by LiuXiaohui123321** [deepmodeling/abacus-develop#3719]
### Details

I'm working on test calculations for magnetic materials. In the calculation, I set the initial moments of the atoms to be positive, but the final results give negative total moments.

>  The readin total magnetization is 14
...
 LCAO ALGORITHM --------------- ION=   1  ELEC=  23--------------------------------
          total magnetism (Bohr mag/cell) = -0.930826
       absolute magnetism (Bohr mag/cell) = 0.994949
                        nelec for spin up = 59.5346
                      nelec for spin down = 60.4654
...

[magnetic-RbNaMg6O7.tar.gz](https://github.com/deepmodeling/abacus-develop/files/14612251/magnetic-RbNaMg6O7.tar.gz)

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by WHUweiqingzhou** [comment]
@LiuXiaohui123321
I think the result is normal and correct. It will happen if `mixing_beta_mag` is large. And this result does not mean the ground state is wrong.

**Comment by LiuXiaohui123321** [comment]
> @LiuXiaohui123321 I think the result is normal and correct. It will happen if `mixing_beta_mag` is large. And this result does not mean the ground state is wrong.

@dyzheng Any comments?

**Comment by dyzheng** [comment]
For a Ferromagnetic system, there are two ground states with total magnetization along z-axis and -z-axis, so the positive and negative total moments are both correct.

In ABACUS, there two method to choose target total moment orientation:
1. set initial atomic mags near with the final atomic mags.
2. set mixing_beta_mag in range (0, 1)

**Comment by WHUweiqingzhou** [comment]
@LiuXiaohui123321,
as @dyzheng explain above, a large `mixing_beta_mag>1` sometimes leads a orientation change of atomic magmon, but it is perfectly fine for collinear calculations.
