### ISSUE TITLE
Docs: remove unrelevant author names from toolchain scripts

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#3722]
### Details

for example, see: https://github.com/deepmodeling/abacus-develop/blob/develop/toolchain/install_requirements_ubuntu.sh#L3C1-L3C22

### Have you read the online manual http://abacus.deepmodeling.com/en/latest/

- [X] Yes, I have read the online manual.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific section of the documentation with the issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Update the documentation to address the issue, following the suggested improvement.
- [ ] Ensure the updated documentation adheres to the project's documentation standards.
- [ ] Test the updated documentation to ensure it is clear and accurate.
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Publish the updated documentation and notify the issue reporter.

**Comment by QuantumMisaka** [comment]
I consider it is truly needed, for lots of scripts in toolchain is just a copy from CP2K toolchain and many label are left in there. I will found a time to finish it.

**Comment by caic99** [comment]
@QuantumMisaka Please be aware that CP2K uses GPL license.
