### ISSUE TITLE
Can anyone provide a script to convert the basis sets in CP2K to the basis sets of abacus? (Discussion on ABACUS and CP2K atomic orbitals)

### ISSUE THREAD

**Issue by hellozhaoming** [deepmodeling/abacus-develop#3737]
### Background

I want to simulate materials with Lanthanide elements with abacus. There is  pseudopotentials of lanthanides in cp2k and a upf version (https://github.com/simonpintarelli/lanthanides-nc-pseudos). However, no basis sets can be used by abacus except planewave basis. DFT SCF with planewave basis for Lanthanides are hard to converge. Thus, I want to convert basis sets in cp2k to the abacus compatible version to make banchmarks between cp2k and abacus.

### Describe the solution you'd like

Can anyone provide a python script？ Or implement this funtion in abacus to make it compatible with cp2k basis sets and pseudopotentials

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by kirk0830** [comment]
lanthanides pseudopotentials always suffer from hard-to-converge issues, no matter which software. For I have tested the GTH pseudopotential under implementation framework of ABACUS and QE, seems GTH is usually not the best choice. I attach the test report here:
https://ucoyxk075n.feishu.cn/docx/QwjwdUVu9oszJjxjEfOcqS4Knef

On the other hand, the numerical atomic orbital of ABACUS and GTO used in CP2K are actually under different theoretical framework. For the former, the numerical atomic orbital is the result of **learning** on spaces spanned by planewave basis, while CP2K GTO is generated based on different consideration. Therefore, the directly conversion of GTO to numerical atomic orbital of ABACUS is not quite meaningful though viable, instead, a more strict and safe way I would suggest would be generating numerical atomic orbitals for specific pseudopotential.

**Comment by kirk0830** [comment]
#3762 provides pseudopot-nao bundles for La and Ce. If you need more pseudopot-nao bundles e.g. for other elements or other pseudopotentials, please reopen this issue and mention me.
