### ISSUE TITLE
There are errors between the calculation examples and those given on the official website

### ISSUE THREAD

**Issue by Timtansiyu** [deepmodeling/abacus-develop#3747]
### Details

On the left is the band diagram directly given in the example, and on the right is the result I got after calculating the example, but the blue band is different, what is the problem?
[electric_field.zip](https://github.com/deepmodeling/abacus-develop/files/14650477/electric_field.zip)
![微信图片_20240319202655](https://github.com/deepmodeling/abacus-develop/assets/164017480/0f871094-edf8-4c2f-b8df-a1043ce3229e)

### Have you read the online manual http://abacus.deepmodeling.com/en/latest/

- [X] Yes, I have read the online manual.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific section of the documentation with the issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Update the documentation to address the issue, following the suggested improvement.
- [ ] Ensure the updated documentation adheres to the project's documentation standards.
- [ ] Test the updated documentation to ensure it is clear and accurate.
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Publish the updated documentation and notify the issue reporter.

**Comment by YuLiu98** [comment]
Hi @Timtansiyu , I'm sorry about the problem.

Recently, ABACUS has implemented charge mixing for magnetic systems, so the parameters need to be updated. 

You should add these two parameters when doing scf calculations:

```
mixing_beta_mag         0.1
mixing_gg0_mag          1.5
```

The details can refer to issue #3560 and PR #3571 .
