### ISSUE TITLE
Request: restart from Hexx in OUT.suffix directory

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#3752]
### Background

in #3451 we can restart from Hexx in OUT.suffix/restart directory, but there will be Hexx print-out in OUT.suffix directory

```
-rw-rw-r-- 1 2201110432 2201110432 160M Mar 20 04:11 HexxR_0
-rw-rw-r-- 1 2201110432 2201110432 127M Mar 20 04:11 HexxR_1
-rw-rw-r-- 1 2201110432 2201110432 113M Mar 20 04:11 HexxR_10
-rw-rw-r-- 1 2201110432 2201110432 121M Mar 20 04:11 HexxR_11
-rw-rw-r-- 1 2201110432 2201110432 144M Mar 20 04:11 HexxR_12
-rw-rw-r-- 1 2201110432 2201110432 114M Mar 20 04:11 HexxR_13
-rw-rw-r-- 1 2201110432 2201110432 121M Mar 20 04:11 HexxR_14
-rw-rw-r-- 1 2201110432 2201110432 129M Mar 20 04:11 HexxR_15
-rw-rw-r-- 1 2201110432 2201110432 135M Mar 20 04:11 HexxR_2
-rw-rw-r-- 1 2201110432 2201110432 144M Mar 20 04:11 HexxR_3
-rw-rw-r-- 1 2201110432 2201110432 127M Mar 20 04:11 HexxR_4
-rw-rw-r-- 1 2201110432 2201110432 100M Mar 20 04:11 HexxR_5
-rw-rw-r-- 1 2201110432 2201110432 106M Mar 20 04:11 HexxR_6
-rw-rw-r-- 1 2201110432 2201110432 114M Mar 20 04:11 HexxR_7
-rw-rw-r-- 1 2201110432 2201110432 135M Mar 20 04:11 HexxR_8
-rw-rw-r-- 1 2201110432 2201110432 106M Mar 20 04:11 HexxR_9
-rw-rw-r-- 1 2201110432 2201110432  27K Mar 20 18:52 INPUT
-rw-rw-r-- 1 2201110432 2201110432 833K Mar 20 17:08 istate.info
-rw-rw-r-- 1 2201110432 2201110432  11K Mar 20 18:52 kpoints
-rw-rw-r-- 1 2201110432 2201110432 125K Mar 20 04:11 mulliken.txt
-rw-rw-r-- 1 2201110432 2201110432  24K Mar 20 04:11 Orbital
-rw-rw-r-- 1 2201110432 2201110432  33K Mar 20 18:57 running_scf.log
-rw-rw-r-- 1 2201110432 2201110432 4.5M Mar 20 04:10 SPIN1_CHG.cube
-rw-rw-r-- 1 2201110432 2201110432 4.5M Mar 20 04:11 SPIN2_CHG.cube
-rw-rw-r-- 1 2201110432 2201110432  973 Mar 20 18:52 STRU_READIN_ADJUST.cif
-rw-rw-r-- 1 2201110432 2201110432 1.4K Mar 20 18:57 warning.log
```

It seems these Hexx is print-out when `out_chg 1` is set, I'm testing whether they are the same Hexx files.

### Describe the solution you'd like

restart from those Hexx in OUT.suffix directory

### Task list only for developers

- [X] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by QuantumMisaka** [comment]
They are not the same Hexx files, put those Hexx files in `OUT.suffix/restart` will have no effect

**Comment by maki49** [comment]
The `restart_load`ed Hexxs are Hexx(k) saved to `OUT.suffix/restart` when set `restart_save` to 1.
Those in `OUT.suffix/` are Hexx(R) for subsequent NSCF.

**Comment by QuantumMisaka** [comment]
> The `restart_load`ed Hexxs are Hexx(k) saved to `OUT.suffix/restart` when set `restart_save` to 1. Those in `OUT.suffix/` are Hexx(R) for subsequent NSCF.

I consider this difference should be in the docs

**Comment by WHUweiqingzhou** [comment]
@maki49  
could you update the corresponding docs?
