### ISSUE TITLE
Different OMP and MPI Settings have different efficiency

### ISSUE THREAD

**Issue by Timtansiyu** [deepmodeling/abacus-develop#3758]
### Details

In the actual calculation, the running script in the left picture can output the calculation results, but sometimes ELPA problems occur. In the right picture, the result of running this script for 1 hour and 1 step cannot be calculated。How to set up to reasonably invoke computer resources？
![屏幕截图 2024-03-21 161808](https://github.com/deepmodeling/abacus-develop/assets/164017480/893bb2ce-c036-4159-a9fb-b933a9dbc95c)
![屏幕截图 2024-03-21 161926](https://github.com/deepmodeling/abacus-develop/assets/164017480/bba4ffc8-deaa-4d75-93cd-950bb82cf31b)

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by QuantumMisaka** [comment]
@Timtansiyu Can you share your ABACUS installation dependence and environments? ABACUS installed by gcc-openmpi-openblas toolchain will have poor OpenMP performance when OMP_NUM_THREADS>4

**Comment by Timtansiyu** [comment]
How to look at software installation dependencies and environments? I'm not sure

**Comment by Timtansiyu** [comment]
> Reference in new issue
How to look at software installation dependencies and environments? I'm not sure

**Comment by QuantumMisaka** [comment]
@Timtansiyu Can you have a test by using `export OMP_NUM_THREADS=4` and `mpirun -np 16 abacus` ?

**Comment by QuantumMisaka** [comment]
> > Reference in new issue
> > How to look at software installation dependencies and environments? I'm not sure

@Timtansiyu 
You can find the executable file of abacus (always in path/to/abacus/bin/abacus) and 
```
ldd abacus
```
to check the dependencies

**Comment by Timtansiyu** [comment]
> > > 新一期的参考资料 如何查看软件安装依赖关系和环境？我不确定
> 
> 您可以找到算盘的可执行文件（始终在路径/to/abacus/bin/abacus）和
> 
> ```
> ldd abacus
> ```
> 
> 检查依赖项

![image](https://github.com/deepmodeling/abacus-develop/assets/164017480/59c5d326-1d19-43e6-af37-585d92dac438)

**Comment by Timtansiyu** [comment]
> @Timtansiyu Can you have a test by using `export OMP_NUM_THREADS=4` and `mpirun -np 16 abacus` ?

This core call is automatically stopped by the system after running for one second. I seem to have to use export OMP_NUM_THREADS=64mpirun -np 1 abacus to get the result, but sometimes it fails

**Comment by QuantumMisaka** [comment]
@Timtansiyu In which way have you installed your ABACUS ? it seems GLIBC is lacked

**Comment by mohanchen** [comment]
We will close this issue since no obvious solution can be found in a short time. We always welcome new issues.
