### ISSUE TITLE
Problem when getting KPT files

### ISSUE THREAD

**Issue by yycx1111** [deepmodeling/abacus-develop#3759]
### Details

I use python get_kpath.py to get KPT file for band structure calculation. But no KPT file was generated.
KPT file can be generated when the system is GaN. But KPT file can not be generated when the system is H2O.
Why can't generate a KPT file when STRU file is H2O?
Here is the STRU file.
[STRU.txt](https://github.com/deepmodeling/abacus-develop/files/14692821/STRU.txt)

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by WHUweiqingzhou** [comment]
@yycx1111, where do you get the script get_kpath.py, code it by yourself?

**Comment by yycx1111** [comment]
> @yycx1111, where do you get the script get_kpath.py, code it by yourself?

I got it from a notebook tutorial. Here is the notebook url and the scripts.
https://nb.bohrium.dp.tech/detail/1211642609
[get_kpath.txt](https://github.com/deepmodeling/abacus-develop/files/14716298/get_kpath.txt)

**Comment by hongriTianqi** [comment]
@yycx1111 Sorry not to mind that the provided script is only for 2D and 3D systems. For isolated molecules, you should only set the gamma point like:
```
K_POINTS
0
Gamma
1 1 1 0 0 0
```
Usually, there is barely no band structure calculation for isolated molecules.
