### ISSUE TITLE
Bug of mpi stuck in mid-run

### ISSUE THREAD

**Issue by LiuXiaohui123321** [deepmodeling/abacus-develop#3770]
### Describe the bug

When running ABACUS with more CPU cores, the program gets stuck in the middle of running. So far I've found the code location, and it looks like it's related to the MPI_alltoallv() function.
https://github.com/deepmodeling/abacus-develop/blob/4a49a312036afb35d662a075ad8bc848d6e65a5e/source/module_hamilt_lcao/module_hcontainer/func_transfer.cpp#L452

Similar problems will come up again here,
https://github.com/deepmodeling/abacus-develop/blob/4a49a312036afb35d662a075ad8bc848d6e65a5e/source/module_hamilt_lcao/module_hcontainer/func_transfer.cpp#L371

or here,
https://github.com/deepmodeling/abacus-develop/blob/4a49a312036afb35d662a075ad8bc848d6e65a5e/source/module_hamilt_lcao/hamilt_lcaodft/DM_gamma_2d_to_grid.cpp#L200

### Environment

- gcc-9.3.1
- intel-2021.3.0
- intelmpi-2021.3.0
- elpa-2021.11.102

[Si64_512cores_mpi-stuck.tar.gz](https://github.com/deepmodeling/abacus-develop/files/14719208/Si64_512cores_mpi-stuck.tar.gz)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by LiuXiaohui123321** [comment]
The first time I had this problem was when I was calculating a system with more than 8000 atoms, which needs more CPU cores. For debugging purposes, I have prepared here a system with 64 atoms in which this problem also occurs.

**Comment by WHUweiqingzhou** [comment]
@dyzheng could you have a look?

**Comment by dyzheng** [comment]
[log-512core-Si64.zip](https://github.com/deepmodeling/abacus-develop/files/14739847/log-512core-Si64.zip)
@LiuXiaohui123321 I repeat this case and found no stuck of MPI, this is my screen output. 
My test calculated by one node, maybe the problem come from communication between different nodes?
