### ISSUE TITLE
H2_relax_lcao calculated by 8 processors was unable to get a result.

### ISSUE THREAD

**Issue by ieiue** [deepmodeling/abacus-develop#3772]
### Describe the bug

When making a relax calculation of Hydrogen molecule with lcao basis type, if the processors set to 8, the first ITER step yielded no results. If the processors set to 16, there is an error "nbands<ncpus". 4 processors can obtain a results.
![img_v3_0297_f1c212dd-83a5-4cdb-890e-76bd9e14336g](https://github.com/deepmodeling/abacus-develop/assets/116336560/da92c5da-c5a2-4eb0-9e83-d9d9e8264de4)

### Expected behavior

Why do the 8 processes not report errors or produce results. 

### To Reproduce

[H.zip](https://github.com/deepmodeling/abacus-develop/files/14722335/H.zip)
mpirun -n 8 abacus

### Environment

ubuntu 20.04 
gcc 9.4
ABACUS v.3.5.4

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by maki49** [comment]
There seems to be some bug with ELPA. I changed `ks_solver` to `scalapack_gvx` and got a normal end.

**Comment by WHUweiqingzhou** [comment]
@ieiue, could you think we can close this issue or keep it open?
b. t. .w, if you want to perform magnetic calculations of very small system, and meet the convergence issues, please refer to #3560
