### ISSUE TITLE
Installing errors

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#3778]
### Describe the bug

From https://github.com/abacusmodeling/abacus-develop/issues/299

### Expected behavior

.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@caic99 could you have a look?

**Comment by caic99** [comment]
Hi @liqiuyua,
ABACUS installed by conda supports Libxc-related functions.
If you wish to build from source, you may follow [the installation instructions](https://abacus.deepmodeling.com/en/latest/quick_start/easy_install.html#easy-installation).

Feel free to ask if you encounter any questions.
