### ISSUE TITLE
Error of the new VNL calculation method

### ISSUE THREAD

**Issue by YuLiu98** [deepmodeling/abacus-develop#378]
## Describe the Bug
I test the AlH system by running AIMD with LCAO in reconstruction branch.
In the first MD step, everything is OK, but something goes wrong in the second MD step.
It seems that the function build_Nonlocal_mu_new in src_lcao/LCAO_gen_fixedH.cpp has some problems.

## To Reproduce
Relevant input files are attached, along with the output I got.

## Environment
- OS: Ubuntu18.04
- Compiler: Intel oneAPI
- Optional Dependencies: Intel MKL; FFTW-3.3.8; elpa-2016.05.004

## Additional Context
[AlH.tar.gz](https://github.com/deepmodeling/abacus-develop/files/7256423/AlH.tar.gz)

**Comment by dyzheng** [comment]
Can you recheck this test case using the branch "newelpa"? I runned this branch and didn't find any error.

**Comment by dyzheng** [comment]
#387 wenfei-li has fixed this bug.
