### ISSUE TITLE
SCF can not converged for Na0.5CoO2 with +U

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3780]
### Describe the bug

The SCF cannot converged for NaCoO in 200 steps.

The last steps are:
```
 ITER   TMAG      AMAG      ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)
 GE1    6.00e+00  6.81e+00  -6.731536e+04  0.000000e+00   1.051e-01  1.962e+01
 GE2    9.45e-01  1.79e+00  -6.730048e+04  1.488006e+01   7.656e-02  1.692e+01
 GE3    6.90e+00  7.95e+00  -6.729208e+04  8.395702e+00   9.044e-02  1.668e+01
...
 GE189  -8.49e-14 2.73e-13  -6.732507e+04  1.893518e+01   5.961e-02  1.680e+01
 GE190  5.06e-15  1.92e-13  -6.734227e+04  -1.719561e+01  3.590e-02  1.692e+01
 GE191  -4.29e-15 1.64e-13  -6.734129e+04  9.742499e-01   3.581e-02  1.730e+01
 GE192  -9.59e-15 1.58e-13  -6.733680e+04  4.496442e+00   3.581e-02  1.736e+01
 GE193  -2.94e-14 2.15e-13  -6.732916e+04  7.642345e+00   6.101e-02  1.733e+01
 GE194  2.53e-15  1.54e-13  -6.733562e+04  -6.461525e+00  3.643e-02  1.748e+01
 GE195  7.34e-15  1.68e-13  -6.732985e+04  5.765170e+00   6.109e-02  1.728e+01
 GE196  1.14e-15  1.69e-13  -6.733909e+04  -9.242164e+00  3.589e-02  1.680e+01
 GE197  -1.73e-15 1.49e-13  -6.734400e+04  -4.902584e+00  3.643e-02  1.861e+01
 GE198  4.45e-14  2.13e-13  -6.732504e+04  1.895697e+01   5.961e-02  1.923e+01
 GE199  3.51e-15  1.62e-13  -6.787831e+04  -5.532747e+02  3.589e-02  2.027e+01
SCF restart after this step!
 GE200  -4.92e-14 3.67e-13  -4.841874e+04  1.945958e+04   6.696e-01  1.719e+01
 !! CONVERGENCE HAS NOT BEEN ACHIEVED !!
```

The INPUT is:
```
INPUT_PARAMETERS
suffix  abacus

calculation scf
ecutwfc 100
scf_thr 1e-07
scf_nmax        200
smearing_method gaussian
smearing_sigma  0.0037
mixing_type     pulay


ks_solver       genelpa
basis_type      lcao
gamma_only      0
symmetry        0
nspin   2
dft_plus_u      0
orbital_corr    -1  2 -1
hubbard_u       0 5.14  0

out_mul 1
out_bandgap     1
mixing_restart 1e-3
mixing_dmr      1

onsite_radius 4
```
[nacoo.zip](https://github.com/deepmodeling/abacus-develop/files/14738096/nacoo.zip)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
It is very weird that a non-DFTU calculation is so hard to converge.

**Comment by WHUweiqingzhou** [comment]
@pxlxingliang, I reproduce your non-DFTU calculation, and found its `drho` indeed oscillates around 1e-2. I think it is unacceptable. Meanwhile, I notice it is a LCAO calculation. I perform a PW calculation by only setting `basis_type=pw`. It converges in 43 steps (see details in [link)](https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-nacoo-pw-abacustest-v0.3.107-892693), indicates poor quality of Co orbitals result in poor convergence performance. 

As for Co orbitals (refers to Co.upf), do @jinzx10 and @kirk0830 have any comment/suggestion?

**Comment by jinzx10** [comment]
> @pxlxingliang, I reproduce your non-DFTU calculation, and found its `drho` indeed oscillates around 1e-2. I think it is unacceptable. Meanwhile, I notice it is a LCAO calculation. I perform a PW calculation by only setting `basis_type=pw`. It converges in 43 steps (see details in [link)](https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-nacoo-pw-abacustest-v0.3.107-892693), indicates poor quality of Co orbitals result in poor convergence performance.
> 
> As for Co orbitals (refers to Co.upf), do @jinzx10 and @kirk0830 have any comment/suggestion?

I can verify that, by turning of +U, basic SCF still fails to converge. However, I notice that drho exhibits some periodic pattern, which resembles many Pulay mixing in gaussian-basis calculations where a conventional solution is to increase the size of the mixing space. I added "mixing_ndim 15" to INPUT and it converges successfully in 83 steps with the following INPUT:

I plotted the given Co orbitals and feel that the room for improvement might be very limited. There's indeed a "consistency issue" that the given Co orbitals do not seem to be generated from the given pseudopotential; using customized Co orbitals generated with the given pp might help.

```
INPUT_PARAMETERS
suffix  abacus

calculation scf
ecutwfc 100
scf_thr 1e-07
scf_nmax    200
smearing_method gaussian
smearing_sigma  0.0037
mixing_type pulay


ks_solver   genelpa
basis_type  lcao
gamma_only  0
symmetry    0
nspin   2
#dft_plus_u 0
#orbital_corr   -1  2 -1
#hubbard_u  0 5.14  0

out_mul 1
out_bandgap 1

#mixing_dmr 1
#mixing_restart 1e-3
mixing_ndim 15

onsite_radius 4
```

**Comment by WHUweiqingzhou** [comment]
Thanks to @jinzx10, `mixing_ndim=15` is indeed helpful for convergence, where PBE's SCF converges in 85 steps [3bc5e0](https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-nacoo-ndim15-abacustest-v0.3.108-3bc5e0).
Based on converged PBE calculation, we try DFTU + `mixing_restart` calculations, and get the results [c51282](https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-nacoo-3780-u-abacustest-v0.3.108-c51282)
- mixing_restart=1e-3：TMAG=2.07；AMAG=15.5；converged in 198 steps
- mixing_restart=5e-4：TMAG=2.07；AMAG=15.5；converged in 199 steps
- mixing_restart=5e-4：TMAG=2.07；AMAG=15.5；not converged in 200 steps（last drho ~ 10e-6）

And I try DFTU+mixing_restart+uramping (PR #3890), and get the result [f3a1f0](https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-nacoo-uramping-abacustest-v0.3.108-f3a1f0):
- mixing_restart=1e-3，uramping=1.3 eV：TMAG=-2.00；AMAG=11.2；converged in 290 steps
- mixing_restart=5e-4，uramping=1.3 eV：TMAG=6.00；AMAG=11.4；converged in 171 steps
- mixing_restart=1e-4，uramping=1.3 eV：TMAG=6.00；AMAG=11.4；converged in 189 steps
- mixing_restart=5e-5，uramping=1.3 eV：TMAG=6.00；AMAG=11.4；converged in 196 steps

The convergence process above reveals multiple states obtained through calculation. A comparison of total energy levels indicates that the ground state derived from mixing_restart (TMAG=2.07; AMAG=15.5, total energy=-6.731162e+04) is a local minimum, while the ground state produced by U-Ramping (TMAG=6.00; AMAG=11.4, total energy=-6.731222e+04) has a lower energy.

Conclusions from these calculations can be summarized as follows:
- Increasing mixing_ndim assists in the convergence of DFTU calculations.
- Both mixing_restart and the U-Ramping method can resolve non-convergence issues in DFTU computations.
- However, even if convergence is achieved with mixing_restart, the result might still be a local minimum, which would be an incorrect magnetic ground state.
- The U-Ramping method can stably yield the correct magnetic ground state.
