### ISSUE TITLE
Memory logging of "LOC" is ridiculous

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#3789]
### Describe the bug

![image](https://github.com/deepmodeling/abacus-develop/assets/49852742/7526f4a2-64e1-49a4-8414-17be50b8940d)

### Expected behavior

1. Fix this line and related lines: `    memory_sender += sender_size * (sizeof(int) * sizeof(double));`
2. Try to delete the use of LOC
3. Try to delete the use of DMK

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
`LOC` class has been deleted now,
