### ISSUE TITLE
Electronic scf convergence problem during cell relax

### ISSUE THREAD

**Issue by sunliang98** [deepmodeling/abacus-develop#379]
## Describe the Bug
I run cell-relax in a fcc Al system, containing 21 atoms arranged along fcc[111] direction. With force_thr_ev = 0.000001, electronic convergence  cannot be achieved after 100 scf, while it can be achieved when force_thr_ev=0.01.
Then, I test the cell-relax of fcc Al primitive cell. There is no problem in electronic scf, but the program wouldn't stop even if force = 0, with force_thr_ev = 1.

## To Reproduce
I have attached relevant input files.

## Environment
- OS: Ubuntu 16
- Compiler: Intel2018
- Optional Dependencies: Intel MKL
[abacus-cell-relax.tar.gz](https://github.com/deepmodeling/abacus-develop/files/7270806/abacus-cell-relax.tar.gz)

**Comment by wenfei-li** [comment]
I've tested the two test cases using ABACUS compiled with intel oneapi, and it seems both issues have been resolved.
