### ISSUE TITLE
Integrated tests failed: 101_PW_lps_pseudopots

### ISSUE THREAD

**Issue by AsTonyshment** [deepmodeling/abacus-develop#3792]
### Describe the Testing Issue

When I run Autotest.sh under `tests/integrate`, failure occurs. It seems that the file `tests/integrate/CASES` hasn't been changed simultaneously when the folder names under `tests/integrate` were changed to `101_PW_lps6_pseudopots` and ` 101_PW_lps8_pseudopots`.

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by WHUweiqingzhou** [comment]
@sunliang98, could you update the `tests/integrate/CASES`?

**Comment by sunliang98** [comment]
I just see this message, thank you for fixing this issue! @WHUweiqingzhou
