### ISSUE TITLE
Error in GPU Calculation

### ISSUE THREAD

**Issue by ieiue** [deepmodeling/abacus-develop#3795]
### Describe the bug

When making a calculation with gpu, here is an error from INPUT parameters.
![img_v3_029a_b1f73a6c-f3b6-453a-8d5d-fae58a0e5c1g](https://github.com/deepmodeling/abacus-develop/assets/116336560/9e7bcd41-a971-4c50-9dc4-bf0b7db820f9)

### Expected behavior

How to change parameters to complete this gpu calculation? 

### To Reproduce

[Si2_pw.zip](https://github.com/deepmodeling/abacus-develop/files/14739997/Si2_pw.zip)

### Environment

Ubuntu 20.04
ABACUS v.3.5.4
gcc 9.4

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@denghuilu, could you have a look?

**Comment by denghuilu** [comment]
The issue is due to the `cudaGetDeviceCount` function not recognizing any available GPU devices in your environment. My suggestion would be  to ensure the availability of GPUs in your environment, check the compilation/installation of ABACUS again, and consider checking the CUDA Driver, among other things.
