### ISSUE TITLE
a mismatch appears in constraining magnetism in an AFM system 

### ISSUE THREAD

**Issue by HongSPang** [deepmodeling/abacus-develop#3796]
### Describe the bug

[constrained.zip](https://github.com/deepmodeling/abacus-develop/files/14739989/constrained.zip)
[normal (1).zip](https://github.com/deepmodeling/abacus-develop/files/14739993/normal.1.zip)

In computing an AFM system, I match the result from a normal ab-initio calculation as well as constraining the magnetic magnitude to a known number. The normal calculation is able to reproduce the result beyond approach, yet when constraining the magnetic(which is consistant with normal calcualtion ), the result diverges.

### Expected behavior

ABACUS should present the same result with or without constraining magnetic magnitude.

### To Reproduce

[constrained.zip](https://github.com/deepmodeling/abacus-develop/files/14740046/constrained.zip)
[normal (1).zip](https://github.com/deepmodeling/abacus-develop/files/14740047/normal.1.zip)

### Environment

server 235, ABACUS version 3.5.3

### Additional Context

[band (1).pdf](https://github.com/deepmodeling/abacus-develop/files/14740066/band.1.pdf)
[band.pdf](https://github.com/deepmodeling/abacus-develop/files/14740067/band.pdf)
[band.pdf](https://github.com/deepmodeling/abacus-develop/files/14740068/band.pdf)
[Input (1).txt](https://github.com/deepmodeling/abacus-develop/files/14740077/Input.1.txt)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by dyzheng** [comment]
@hongriTianqi Could you look at this?

**Comment by hongriTianqi** [comment]
@HongSPang Thanks for testing the performance of deltaspin. 


Please check the magnetic moments on oxygen atoms without deltaspin calculation by setting out_mul in the INPUT file. The key is to set all the magnetic moments exactly the same with and without deltaspin.


My suggestion is to explicitly set the constraint spin of all oxygen atoms to 0.0 if they are exactly zero in non-deltaspin calculation, and then try the calculation again. The energy diferrence might be caused by the magnetic moment on oxygen atoms:

```
Total Magnetism on atom: 0  (0.0000000000e+00, 0.0000000000e+00, 1.1000010629e+00)
Total Magnetism on atom: 1  (0.0000000000e+00, 0.0000000000e+00, -1.1000016597e+00)
Total Magnetism on atom: 2  (0.0000000000e+00, 0.0000000000e+00, -1.2257333437e-03)
Total Magnetism on atom: 3  (0.0000000000e+00, 0.0000000000e+00, -1.2161704376e-03)
Total Magnetism on atom: 4  (0.0000000000e+00, 0.0000000000e+00, 1.5111108524e-03)
Total Magnetism on atom: 5  (0.0000000000e+00, 0.0000000000e+00, 1.4972944774e-03)
```
The new json file should be like:
```json
[
{
"element": "Ru",
"itype": 0,
"ScDecayGrad": 0.9,
"ScAtomData": [
{
"index": 0,
"lambda": [0, 0, 0],
"target_mag": [0.0, 0.0, 1.1],
"constrain": [1,1,1]
},
{
"index": 1,
"lambda": [0, 0, 0],
"target_mag": [0.0, 0.0, -1.1],
"constrain": [1,1,1]
},
{
"element": "O",
"itype": 1,
"ScAtomData": [
{
"index": 0,
"lambda": [0, 0, 0],
"target_mag": [0.0, 0.0, 0.0],
"constrain": [1,1,1]
},
{
"index": 1,
"lambda": [0, 0, 0],
"target_mag": [0.0, 0.0, 0.0],
"constrain": [1,1,1]
},
{
"index": 2,
"lambda": [0, 0, 0],
"target_mag": [0.0, 0.0, 0.0],
"constrain": [1,1,1]
},
{
"index": 3,
"lambda": [0, 0, 0],
"target_mag": [0.0, 0.0, 0.0],
"constrain": [1,1,1]
}
]
}
]
```

**Comment by HongSPang** [comment]
> @HongSPang Thanks for testing the performance of deltaspin.
> 
> Please check the magnetic moments on oxygen atoms without deltaspin calculation by setting out_mul in the INPUT file. The key is to set all the magnetic moments exactly the same with and without deltaspin.
> 
> My suggestion is to explicitly set the constraint spin of all oxygen atoms to 0.0 if they are exactly zero in non-deltaspin calculation, and then try the calculation again. The energy diferrence might be caused by the magnetic moment on oxygen atoms:
> 
> ```
> Total Magnetism on atom: 0  (0.0000000000e+00, 0.0000000000e+00, 1.1000010629e+00)
> Total Magnetism on atom: 1  (0.0000000000e+00, 0.0000000000e+00, -1.1000016597e+00)
> Total Magnetism on atom: 2  (0.0000000000e+00, 0.0000000000e+00, -1.2257333437e-03)
> Total Magnetism on atom: 3  (0.0000000000e+00, 0.0000000000e+00, -1.2161704376e-03)
> Total Magnetism on atom: 4  (0.0000000000e+00, 0.0000000000e+00, 1.5111108524e-03)
> Total Magnetism on atom: 5  (0.0000000000e+00, 0.0000000000e+00, 1.4972944774e-03)
> ```
> 
> The new json file should be like:
> 
> ```json
> [
> {
> "element": "Ru",
> "itype": 0,
> "ScDecayGrad": 0.9,
> "ScAtomData": [
> {
> "index": 0,
> "lambda": [0, 0, 0],
> "target_mag": [0.0, 0.0, 1.1],
> "constrain": [1,1,1]
> },
> {
> "index": 1,
> "lambda": [0, 0, 0],
> "target_mag": [0.0, 0.0, -1.1],
> "constrain": [1,1,1]
> },
> {
> "element": "O",
> "itype": 1,
> "ScAtomData": [
> {
> "index": 0,
> "lambda": [0, 0, 0],
> "target_mag": [0.0, 0.0, 0.0],
> "constrain": [1,1,1]
> },
> {
> "index": 1,
> "lambda": [0, 0, 0],
> "target_mag": [0.0, 0.0, 0.0],
> "constrain": [1,1,1]
> },
> {
> "index": 2,
> "lambda": [0, 0, 0],
> "target_mag": [0.0, 0.0, 0.0],
> "constrain": [1,1,1]
> },
> {
> "index": 3,
> "lambda": [0, 0, 0],
> "target_mag": [0.0, 0.0, 0.0],
> "constrain": [1,1,1]
> }
> ]
> }
> ]
> ```

I tried with this json file and it helps poorly.

**Comment by dyzheng** [comment]
@HongSPang can you show more detail in this Issue? such as the key result of energy or band structure, screen output or running_scf.log file would be better.

**Comment by hongriTianqi** [comment]
@HongSPang Can you show me the `mulliken.txt` file in the `scf` calculation without deltaspin?

**Comment by hongriTianqi** [comment]
> > [@HongSPang](https://github.com/HongSPang) Thanks for testing the performance of deltaspin.
> > Please check the magnetic moments on oxygen atoms without deltaspin calculation by setting out_mul in the INPUT file. The key is to set all the magnetic moments exactly the same with and without deltaspin.
> > My suggestion is to explicitly set the constraint spin of all oxygen atoms to 0.0 if they are exactly zero in non-deltaspin calculation, and then try the calculation again. The energy diferrence might be caused by the magnetic moment on oxygen atoms:
> > ```
> > Total Magnetism on atom: 0  (0.0000000000e+00, 0.0000000000e+00, 1.1000010629e+00)
> > Total Magnetism on atom: 1  (0.0000000000e+00, 0.0000000000e+00, -1.1000016597e+00)
> > Total Magnetism on atom: 2  (0.0000000000e+00, 0.0000000000e+00, -1.2257333437e-03)
> > Total Magnetism on atom: 3  (0.0000000000e+00, 0.0000000000e+00, -1.2161704376e-03)
> > Total Magnetism on atom: 4  (0.0000000000e+00, 0.0000000000e+00, 1.5111108524e-03)
> > Total Magnetism on atom: 5  (0.0000000000e+00, 0.0000000000e+00, 1.4972944774e-03)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The new json file should be like:
> > [
> > {
> > "element": "Ru",
> > "itype": 0,
> > "ScDecayGrad": 0.9,
> > "ScAtomData": [
> > {
> > "index": 0,
> > "lambda": [0, 0, 0],
> > "target_mag": [0.0, 0.0, 1.1],
> > "constrain": [1,1,1]
> > },
> > {
> > "index": 1,
> > "lambda": [0, 0, 0],
> > "target_mag": [0.0, 0.0, -1.1],
> > "constrain": [1,1,1]
> > },
> > {
> > "element": "O",
> > "itype": 1,
> > "ScAtomData": [
> > {
> > "index": 0,
> > "lambda": [0, 0, 0],
> > "target_mag": [0.0, 0.0, 0.0],
> > "constrain": [1,1,1]
> > },
> > {
> > "index": 1,
> > "lambda": [0, 0, 0],
> > "target_mag": [0.0, 0.0, 0.0],
> > "constrain": [1,1,1]
> > },
> > {
> > "index": 2,
> > "lambda": [0, 0, 0],
> > "target_mag": [0.0, 0.0, 0.0],
> > "constrain": [1,1,1]
> > },
> > {
> > "index": 3,
> > "lambda": [0, 0, 0],
> > "target_mag": [0.0, 0.0, 0.0],
> > "constrain": [1,1,1]
> > }
> > ]
> > }
> > ]
> 
> I tried with this json file and it helps poorly.

@HongSPang The key is to set all the atomic mag to results in the original mulliken.txt file without deltaspin. If in that file the oxygen has mag moments. Try this json file and get poor results is expected.

**Comment by hongriTianqi** [comment]
@dyzheng @WHUweiqingzhou I have replied to ask the author to provide more info on the test.

**Comment by HongSPang** [comment]
[mulliken.txt](https://github.com/deepmodeling/abacus-develop/files/14832863/mulliken.txt)
this is the mulliken charge file without deltaspin as requested

**Comment by hongriTianqi** [comment]
@HongSPang Thanks. Please set the json file as below to do test and check the energy:
```json
[
{
"element": "Ru",
"itype": 0,
"ScDecayGrad": 0.9,
"ScAtomData": [
{
"index": 0,
"lambda": [0, 0, 0],
"target_mag": [0.0, 0.0, -1.09],
"constrain": [1,1,1]
},
{
"index": 1,
"lambda": [0, 0, 0],
"target_mag": [0.0, 0.0, 1.09],
"constrain": [1,1,1]
},
{
"element": "O",
"itype": 1,
"ScAtomData": [
{
"index": 0,
"lambda": [0, 0, 0],
"target_mag": [0.0, 0.0, 0.0],
"constrain": [1,1,1]
},
{
"index": 1,
"lambda": [0, 0, 0],
"target_mag": [0.0, 0.0, 0.0],
"constrain": [1,1,1]
},
{
"index": 2,
"lambda": [0, 0, 0],
"target_mag": [0.0, 0.0, 0.0],
"constrain": [1,1,1]
},
{
"index": 3,
"lambda": [0, 0, 0],
"target_mag": [0.0, 0.0, 0.0],
"constrain": [1,1,1]
}
]
}
]
```

**Comment by HongSPang** [comment]
> @HongSPang Thanks. Please set the json file as below to do test and check the energy:
> 
> ```json
> [
> {
> "element": "Ru",
> "itype": 0,
> "ScDecayGrad": 0.9,
> "ScAtomData": [
> {
> "index": 0,
> "lambda": [0, 0, 0],
> "target_mag": [0.0, 0.0, -1.09],
> "constrain": [1,1,1]
> },
> {
> "index": 1,
> "lambda": [0, 0, 0],
> "target_mag": [0.0, 0.0, 1.09],
> "constrain": [1,1,1]
> },
> {
> "element": "O",
> "itype": 1,
> "ScAtomData": [
> {
> "index": 0,
> "lambda": [0, 0, 0],
> "target_mag": [0.0, 0.0, 0.0],
> "constrain": [1,1,1]
> },
> {
> "index": 1,
> "lambda": [0, 0, 0],
> "target_mag": [0.0, 0.0, 0.0],
> "constrain": [1,1,1]
> },
> {
> "index": 2,
> "lambda": [0, 0, 0],
> "target_mag": [0.0, 0.0, 0.0],
> "constrain": [1,1,1]
> },
> {
> "index": 3,
> "lambda": [0, 0, 0],
> "target_mag": [0.0, 0.0, 0.0],
> "constrain": [1,1,1]
> }
> ]
> }
> ]
> ```

I used the upper json file and the band structure stays identical with previous json file setting. The mismatch still exists.
[band-notfixed.pdf](https://github.com/deepmodeling/abacus-develop/files/14994269/band-notfixed.pdf)
[band-fixed.pdf](https://github.com/deepmodeling/abacus-develop/files/14994270/band-fixed.pdf)

**Comment by hongriTianqi** [comment]
@HongSPang Thanks for the feedback. Could you please firstly show if the total energy matches?
