### ISSUE TITLE
mulliken charge output is disabled in nscf calculation

### ISSUE THREAD

**Issue by HongSPang** [deepmodeling/abacus-develop#3802]
### Describe the bug

ABACUS fails to present mulliken charge output in nscf procedure, however scf gives the correct result.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@dyzheng could you have a look?

**Comment by WHUweiqingzhou** [comment]
mulliken charge is calculated by using Density Matrix and Overlap Matrix.
