### ISSUE TITLE
What is the best default input settings for DFT+U

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#3803]
### Details

New parameter lists for DFT+U calculation:
mixing_restart
mixing_dmr
onsite_radius

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by WHUweiqingzhou** [comment]
I am still working on this issue.

**Comment by WHUweiqingzhou** [comment]
I think DFT+U calculation can cooperate with some advanced mixing method, like `mixing_restart`/`mixing_dmr`/`uramping`. I make some tests, see #3844 and #3780. I will suggest three level INPUT for DFT+U:

Level 1: Pure DFT+U, just DIIS mixing
```bash
mixing_beta = 0.4/0.2
```

Level 2: If DIIS mixing is hard to converge, try `mixing_dmr`
```bash
mixing_beta = 0.4/0.2
mixing_restart = 5e-3/1e-3
mixing_dmr   = true
```

Level 3: if Level 2 still fail to converge, try U-Ramping method
```bash
mixing_beta = 0.4/0.2
mixing_restart = 5e-3/1e-3
mixing_dmr   = true
uramping = 1.0
```
You can set `uramping` carefully to get fewer restarts. F.e `U=5.14 eV`, you can set `uramping=1.3 eV`, where you can get converged U by restarting 4 times.

For default setting:
I suggest level 2 as mixing default.
