### ISSUE TITLE
Is the `mixing_restart` parameter set correctly when `init_chg=file`?

### ISSUE THREAD

**Issue by xdzhu** [deepmodeling/abacus-develop#3805]
### Describe the bug

During a previous DFT+U calculation, it exited at step 150, which was the maximum step count. 

Then, I proceeded to continue the calculation by reading the charge density from the SCF calculation above (which had already converged to about the 1e-5 level). At this point, after loading the charge density by setting `init_chg file`, the `mixing_restart` was triggered at the first step. 

Is this reasonable? Or should the steps for triggering `mixing_restart` be more when calculating with `init_chg file`?

![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/bb41ce08-d916-4085-b201-2a2acd7b4896)

### To Reproduce

ABACUS-3.5.4 latest develop version
You can reproduce it by any case or the sample as below:
[mixing_restart-with-charge-file.zip](https://github.com/deepmodeling/abacus-develop/files/14742657/mixing_restart-with-charge-file.zip)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
Comment: change the screen output.

**Comment by WHUweiqingzhou** [comment]
@xdzhu,
it is reasonable, since SCF restarts once `drho<mixing_restart`. You can see the `drho` of 1-st SCF is 1.2e-3, which should be smaller than what you set `mixing_restart`.
