### ISSUE TITLE
Refactoring Plan to Remove Global Variables in \"GlobalV\" Namespace and Improve Code Quality

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#3806]
### Describe the Code Quality Issue

Objective: The goal of this refactoring plan is to eliminate the dependencies on global variables within the \"GlobalV\" namespace in order to maintain and improve the code quality. This document outlines the steps that need to be taken by the developers to achieve this objective and provides guidelines for ensuring proper synchronization and unit testing during the refactoring process.

### Additional Context

1. Analyze and Identify: The first step is to analyze the existing codebase and identify all the instances where global variables from the \"GlobalV\" namespace are being used. Create a comprehensive list of these instances and share it with the entire development team. This will give everyone a clear understanding of the scope of the refactoring process.

2. Plan the Refactoring: Once the instances have been identified, assess the impact of removing the global variables on the overall functionality of the application. Develop a plan for refactoring each instance, taking into consideration the impact on other parts of the application. Ensure that the plan is well-documented and shared with the entire development team.

3. Synchronize with the Development Team: Before starting the refactoring process, it is crucial to ensure that all developers are on the same page and aware of the plan. Schedule a meeting with the development team to discuss the refactoring plan, address any concerns or questions, and ensure that everyone understands the importance of this process and the benefits it will bring to the code quality.

4. Implement the Refactoring: Begin the refactoring process as per the plan. Make sure that each developer is responsible for refactoring the instances assigned to them. Encourage the developers to communicate with each other during the process to address any issues or concerns that may arise and ensure smooth progress.

5. Add Unit Tests: As the refactoring process is being carried out, it is essential to simultaneously add unit tests for the modified code. This will help in verifying that the changes made during the refactoring process do not break any existing functionality and that the application remains stable.

6. Code Review: After the refactoring process is complete, conduct a thorough code review to ensure that the changes made are in line with the plan and that all instances of global variables in the \"GlobalV\" namespace have been successfully removed. Address any issues or concerns raised during the code review and make any necessary adjustments.

7. Final Testing: Once the code review is complete and any necessary adjustments have been made, perform a final round of testing to ensure that the application is working correctly and that the removal of global variables has not introduced any new issues.

8. Documentation and Knowledge Sharing: Update the project documentation to reflect the changes made during the refactoring process. Ensure that all team members are aware of the changes and understand the reasons behind them. This will help in maintaining the improved code quality going forward.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by dzzz2001** [comment]
#3794 remove some global variables in read_dm and read_wfc_nao.

**Comment by AsTonyshment** [comment]
#3797 Removed GlobalVs related to function `ModuleIO::write_dm`.
#3801 Removed GlobalVs related to `module_io/istate_envelope.cpp`.

**Comment by Cstandardlib** [comment]
Plan: Refactor (read_cube, read_rho): Replace direct references to GlobalV with function parameters.
#3824
