### ISSUE TITLE
Observation regarding convergence of electron density

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#3813]
### Describe the bug

Lately I've been implementing the reading of density matrices and the subsequent calculation of electron density. During the process I made the following observation regarding the convergence of electron density. The test system is a single water molecule in a rather large box.
If we turn on the flag out_chg, the content of array rho_save will be printed at the end of SCF calculation. According to what I heard from other developers, the density is not updated once SCF is converged. So presumably what we print would be the 'input' density for the last SCF step, obtained from density mixing after the second-last SCF step.
Now for validation purpose, I would like to print the 'output' density of the last SCF step, namely the one obtained immediately after diagonaliation of Hamiltonian. It is rather easy to obtain it. I did the following changes:
1. insert the subroutine for printing of density after solving the Hamiltonian, so at around line 600 of hamilt2density, I inserted several lines after 'solve':
```
        this->phsol->solve(this->p_hamilt, this->psi[0], this->pelec, GlobalV::KS_SOLVER);

        this->create_Output_Rho(0, istep).write();
        if(GlobalV::NSPIN == 2)
        {
            this->create_Output_Rho(1, istep).write();
        }
```
2. change the array being printed to 'rho' instead of 'rho_save', so in create_output_rho:
```
        return ModuleIO::Output_Rho(this->pw_big,
                                    this->pw_rhod,
                                    is,
                                    GlobalV::NSPIN,
                                    pelec->charge->rho[is],
                                    //pelec->charge->rho_save[is],
```

In this way, the 'output' density of last SCF step will be printed.
I then used a python subscript to check the difference between the two densities, and found that max(rho-rho_save) is at order of 1e-3. I also printed the difference in cube format and visualized it using VESTA:
![image](https://github.com/deepmodeling/abacus-develop/assets/38569667/bbade4c9-3072-491d-8254-dbf717147444)

### Expected behavior

I do not think this is a 'bug' in the strict sense as it seems all subroutines are working as intended in the process. But I would like to report this observation anyway in case it might be of some interest.

### To Reproduce

I attach the directory containing all output files.
out_save/SPIN1_CHG.cube contains the output density of last SCF step; while OUT.autotest/SPIN1_CHG.cube contains the normal output of out_chg.

[tmp.zip](https://github.com/deepmodeling/abacus-develop/files/14755679/tmp.zip)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
Many thanks for sharing. `rho_save` and `rho` at last SCF represent input and output charge density, respectively. But `drho<1e-6` does not mean the delta between input and output density is smaller 1e-6 at every single grid, since `drho` is defined as the average over gird:
```cpp
#ifdef _OPENMP
#pragma omp parallel for reduction(+ : drho)
#endif
            for (int ir = 0; ir < this->rhopw->nrxx; ir++)
            {
                drho += std::abs(chr->rho[is][ir] - chr->rho_save[is][ir]);
            }
        }
#ifdef __MPI
        Parallel_Reduce::reduce_pool(drho);
#endif
        assert(nelec != 0);
        assert(GlobalC::ucell.omega > 0);
        assert(this->rhopw->nxyz > 0);
        drho *= GlobalC::ucell.omega / static_cast<double>(this->rhopw->nxyz);
        drho /= nelec;
```
Indeed, it is not a bug. If you have special need for convergence, you can change the definition of `drho`. f. e., the delta between input and output density should be smaller `scf_thr` at every single grid instead of averaging it.
