### ISSUE TITLE
Please explain the warning on screen of json output

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#3816]
### Details

The warning be like:
```
Warning: write to json, key element exist and is an object, and abacus will overwrite it with a value.
Warning: write to json, key element exist and is an object, and abacus will overwrite it with a value.
```

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by WHUweiqingzhou** [comment]
@grysgreat, could you have a look?

**Comment by grysgreat** [comment]
> @grysgreat, could you have a look?

Sure! In which test this warning appears？

**Comment by WHUweiqingzhou** [comment]
> > @grysgreat, could you have a look?
> 
> Sure! In which test this warning appears？

@hongriTianqi could you provide more detail?

**Comment by grysgreat** [comment]
I probably figure out what the problem was, and the change was committed in PR#3818, which might fix it.
