### ISSUE TITLE
A walltime INPUT parameter is needed to realize a scheduled exit

### ISSUE THREAD

**Issue by xdzhu** [deepmodeling/abacus-develop#3819]
### Background

Sometimes the computing cluster may face corresponding time limits such as 2:00:00 or 1-00:00:00. When we run some SOC and HSE calculations (which are time-consuming) and reach the time limit, ABACUS will exit without warning. 

### Describe the solution you'd like

We hope there is a walltime-related parameter so that when it reaches the specified time during iteriaion, ABACUS can directly jump to the output process and throw a warning about WALLTIME is up for subsequent continuation of the calculation.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by dyzheng** [comment]
Hello, @xdzhu have you tried the parameter https://abacus-rtd.readthedocs.io/en/latest/advanced/input_files/input-main.html#out-freq-elec

**Comment by xdzhu** [comment]
@dyzheng Thanks, I will try it.
