### ISSUE TITLE
Nonclinear calculation with symmetry cannot converge

### ISSUE THREAD

**Issue by Shen-Zhen-Xiong** [deepmodeling/abacus-develop#3830]
### Describe the bug

[nonclinear.tar.gz](https://github.com/deepmodeling/abacus-develop/files/14770133/nonclinear.tar.gz)
Please see the example, I calculate a CrI3 system with nonclinear, only when symmetry=-1, it can converge, but for symmetry=0 or 1, it is not converged.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by dyzheng** [comment]
To be honest, I think the convergence of symmetry=-1 is a lucky case.

I recommand you to try smaller  `mixing_beta` and try to set `mixing_angle` .

**Comment by Shen-Zhen-Xiong** [comment]
I try mixing_beta = 0.1 and 0.02 , after 500 step in symmetry =1, it is not converged.
[scf.log](https://github.com/deepmodeling/abacus-develop/files/14821399/scf.log)

**Comment by dyzheng** [comment]
@Shen-Zhen-Xiong have you tried to set 'mixing_angle', which refer to function specifically designed to optimize the convergence of noncollinear magnetic moments.

**Comment by dyzheng** [comment]
@WHUweiqingzhou any suggestion for this Issue ?

**Comment by dyzheng** [comment]
@Shen-Zhen-Xiong Another suggestion is symmetry should not be used for non-collinear spin case, it will lead to error result now. 
Only symmetry = -1 is recommended.

**Comment by Shen-Zhen-Xiong** [comment]
I think symmetry = -1 should be recommended for non-collinear spin case,  symmetry is very complex for non-collinear calculation.  Maybe it is a good choice for default symmetry = -1 in non-collinear spin case?
