### ISSUE TITLE
There are useless outputs in MD calculation

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#3836]
### Details

Is this output right during MD calculation？
```
 Find the file, try to read charge from file.
 read in fermi energy = 0.00000000000
 second order charge density extrapolation !
 alpha = 1.94335197073
 beta = -0.97341464763
 Find the file, try to read charge from file.
 read in fermi energy = 0.00000000000
 Find the file, try to read charge from file.
 read in fermi energy = 0.00000000000
```
In second order charge density extrapolation, why charge file will be read?

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by kirk0830** [comment]
seems the cube files are processed during charge extrapolation, for more information, see issue #3333

**Comment by dyzheng** [comment]
@kirk0830 Do you think if the file is large, the reading/writing of CUBE file would lead to poor performance?

**Comment by dyzheng** [comment]
Is this feature designed for restarting MD calculation?

**Comment by YuLiu98** [comment]
> @kirk0830 Do you think if the file is large, the reading/writing of CUBE file would lead to poor performance?

The method is consistent with QE. Compared to the scf calculation, the time cost of IO of CUBE files is ignorable. 

Besides, in the cell-relax calculation, we provide the option to reconstruct the FFT grid at each step, which will result in different real-space grid dimensions between different ion steps. It is a straightforward approach to implement the function via reading and writing files. 

At that time, ABACUS did not have the function of reading and writing binary charge density, so for the time being, it was in the form of reading and writing cube files.

Maybe in the future, I can implement the function via reading and writing binary files.

**Comment by YuLiu98** [comment]
> Is this feature designed for restarting MD calculation?

Just for charge extrapolation, currently.
