### ISSUE TITLE
Inf in BAND_*.dat and Missing 1 to 36 in `BAND_2.dat`

### ISSUE THREAD

**Issue by Chentao168** [deepmodeling/abacus-develop#3843]
### Describe the bug

Fe, 2 atoms, nspin = 2, inf in `BAND_1.dat` and `BAND_2.dat`. Missing 1 to 36 in `BAND_2.dat`.
![image](https://github.com/deepmodeling/abacus-develop/assets/76426373/ac2a80aa-b41a-492e-8865-e18f054b17c0)
![image](https://github.com/deepmodeling/abacus-develop/assets/76426373/e458c09a-d2e1-4d5f-bb90-f373605cc957)

### To Reproduce

[20240329-band-inf.zip](https://github.com/deepmodeling/abacus-develop/files/14799009/20240329-band-inf.zip)

### Environment

ABACUS v3.5.4

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by kirk0830** [comment]
I did not reproduce your issue with input files you provided, I think I made minor changes and should not affect the behavior of as-written codes (if you are interested, see pull request draft #3855 ):
`BANDS_1.dat`:
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/dc875291-5edb-4dda-a36f-fa981ea092b2)
`BANDS_2.dat`:
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/3b3c79d0-4f23-4ba2-9ede-60fda937e2e3)

**Comment by Chentao168** [comment]
I also tested in ABACUS version 3.6.0, where the aforementioned issue persisted, specifically the appearance of 'inf' in BAND_1.dat and BAND_2.dat, as well as missing entries from 1 to 36 in BAND_2.dat. The pull request [#3855](https://github.com/deepmodeling/abacus-develop/pull/3855) has not yet been merged into the develop branch. Is it feasible to conduct tests using version 3.6.0?

**Comment by kirk0830** [comment]
> I also tested in ABACUS version 3.6.0, where the aforementioned issue persisted, specifically the appearance of 'inf' in BAND_1.dat and BAND_2.dat, as well as missing entries from 1 to 36 in BAND_2.dat. The pull request [#3855](https://github.com/deepmodeling/abacus-develop/pull/3855) has not yet been merged into the develop branch. Is it feasible to conduct tests using version 3.6.0?

@Chentao168 Could you provide your environment setting information? This seems to relate to some undefined behavior

**Comment by Qianruipku** [comment]
ABACUS has bugs when out_band = 1 and kpar > 1。 
Currently, when kpar > 1, there will be a memory overflow in the band calculation, resulting in the appearance of 'inf' in the results. The program has issues and does not support k-point parallelism, which needs to be addressed.
