### ISSUE TITLE
Feature request: reading vector field from file

### ISSUE THREAD

**Issue by bearkk** [deepmodeling/abacus-develop#3845]
### Background

For real-time tddft calculations of periodic systems, velocity gauge should be adoped, and only the vector potential A(t) is needed in solving the td Kohn-Sham equations. Currently, abacus provides the configuration of 4 types of applied time-dependent electric field E(t), and A(t) is calculated from the integration of E(t). It will be convenient to directly input A(t), either from math expression or read from the files (we only need the A(t_i) at the time step t_i). This not only can save time for integrating E(t), but it also enables inputing arbitrary kind of A(t). 

### Describe the solution you'd like

Please consider to add the feature of reading the vector field A(t) from file. 

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by WHUweiqingzhou** [comment]
@mohanchen, could you have a look who could be assigned?

**Comment by ESROAMER** [comment]
@bearkk Let me handle this. I'll do it in this way: there would be four lines required in the At input files like
```
istep Ax Ay Az
  1    x  x  x
  2    x  x  x
  3    x  x  x
...
```
Vector potential A(t) of each step would be decided by the data you put in 'x'. And you don't need to spcify all the steps. If you run a 10000 steps calculation, you may need to just specify the first 2000 steps. For the rest 8000 steps, I'll just make $A(t_{2000+})=A(t_{2000})$ to avoid abrupt change of $A(t)$.

And at the same time, I'll allow the output of $A(t)$ in tddft running in the same form. So it would be convinent to compare A(t) with other softwares or to make a input file of A(t) through integral of E.

Is this plan good enough for you? Please let me know if you have any other needs or suggestions.

**Comment by bearkk** [comment]
Thanks, I think it's enough for this problem.
PS: I guess it's a typo in the post. It is intended to express "there would be four columns required in the At input files like"?

**Comment by ESROAMER** [comment]
> Thanks, I think it's enough for this problem. PS: I guess it's a typo in the post. It is intended to express "there would be four columns required in the At input files like"?

Yes, of course. Sorry for causing confusion. And sorry for my poor vocabulary :)
