### ISSUE TITLE
unit test base_math_sphbes can not passed in intel compilation environment 

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3847]
### Describe the Testing Issue

There have lots of failure, when I run the unittest base_math_sphbes compiled with intel.
```
[  FAILED  ] Sphbes.SphericalBesselPrecisionNearZero (3 ms)
[ RUN      ] Sphbes.Zeros
[       OK ] Sphbes.Zeros (26 ms)
[ RUN      ] Sphbes.ZerosOld
[       OK ] Sphbes.ZerosOld (16 ms)
[ RUN      ] Sphbes.Derivatives
[       OK ] Sphbes.Derivatives (0 ms)
[ RUN      ] Sphbes.DerivativesOld
l = 3, r = 2, errs = 8.87874e-12
l = 3, r = 4, errs = 5.42921e-13
l = 3, r = 8, errs = 1.40672e-14
l = 4, r = 1, errs = 1.38778e-06
l = 4, r = 2, errs = 4.33681e-08
l = 4, r = 8, errs = 4.23517e-11
l = 4, r = 16, errs = 1.32305e-12
l = 5, r = 1, errs = 2.77556e-10
l = 5, r = 2, errs = 1.73472e-11
l = 5, r = 8, errs = 6.77627e-14
[       OK ] Sphbes.DerivativesOld (0 ms)
[ RUN      ] Sphbes.SphericalBesselsjp
[       OK ] Sphbes.SphericalBesselsjp (0 ms)
[----------] 11 tests from Sphbes (12163 ms total)

[----------] Global test environment tear-down
[==========] 11 tests from 1 test suite ran. (12163 ms total)
[  PASSED  ] 9 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] Sphbes.SphericalBesselPrecisionGrid
[  FAILED  ] Sphbes.SphericalBesselPrecisionNearZero
```

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by jieli-matrix** [comment]
The errors happened since `base_math_sphbes` needs to read the ground truth data from data file otherwise it will set the ground truth data as uninitialized values or zeros. CMake `install` after `build` and you will get the tests passed.
