### ISSUE TITLE
I plan to develop a new DeltaSpin algorithm option

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#3848]
### Background

The algorithm is similar to DFT+U.
New option for user to calculate constraint DFT.

### Describe the solution you'd like

https://dptechnology.feishu.cn/wiki/IpqewMtQgi04NYkRkaRcWtZsnXd?from=from_copylink

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by WHUweiqingzhou** [comment]
@flinky-ai, you can post some test results here.

**Comment by RenguangLiu** [comment]
I used this new version for the bcc iron in FM and two different magnetic conditions tests with 6 different numbers of atoms and diverse symmetry. The results are posted in the following:

### 1. Mag constrained to [0.0 0.0 2.0]

Element | N | Cores | symmetry | K points number | Energy per atom (eV) | Times (s) | Loop Steps | Cost (RMB)
-- | -- | -- | -- | -- | -- | -- | -- | --
Fe | 2 | 16 | 1 | 35 | -3219.637177 | 376 | 200 | 0.301157
Fe | 4 | 16 | 1 | 45 | -3219.637382 | 123 | 27 | 0.098517
Fe | 6 | 16 | 1 | 30 | -3219.637176 | 1553 | 200 | 1.243874
Fe | 8 | 16 | 1 | 30 | -3219.637568 | 1867 | 200 | 1.495372
Fe | 12 | 16 | 1 | 30 | -3219.637381 | 696 | 51 | 0.557461
Fe | 16 | 16 | 1 | 18 | -3219.633744 | 920 | 55 | 0.736873
Fe | 2 | 16 | 0 | 365 | -3219.637176 | 263 | 21 | 0.21065
Fe | 4 | 16 | 0 | 203 | -3219.637381 | 469 | 29 | 0.375645
Fe | 6 | 16 | 0 | 122 | -3219.637177 | 670 | 37 | 0.536636
Fe | 8 | 16 | 0 | 113 | -3219.637566 | 2238 | 91 | 1.792524
Fe | 12 | 16 | 0 | 68 | -3219.637381 | 953 | 39 | 0.763304
Fe | 16 | 16 | 0 | 63 | -3219.633742 | 1364 | 31 | 1.092494
Fe | 2 | 16 | -1 | 729 | -3219.637176 | 575 | 33 | 0.460546
Fe | 4 | 16 | -1 | 405 | -3219.637381 | 832 | 27 | 0.66639
Fe | 6 | 16 | -1 | 243 | -3219.637176 | 2346 | 71 | 1.879026
Fe | 8 | 16 | -1 | 225 | -3219.637568 | 3681 | 83 | 2.948293
Fe | 12 | 16 | -1 | 135 | -3219.637381 | 1572 | 33 | 1.259092
Fe | 16 | 16 | -1 | 125 | -3219.633742 | 2129 | 27 | 1.705221

### 2. Mag constrained to [0.115, 0.034, 1.9964015127223282]

Element | N | Cores | symmetry | K points number | Energy per atom (eV) | Times (s) | Loop Steps | Cost (RMB)
-- | -- | -- | -- | -- | -- | -- | -- | --
Fe | 2 | 16 | 1 | 35 | -3219.637176 | 432 | 200 | 0.34601
Fe | 4 | 16 | 1 | 45 | -3219.637381 | 958 | 200 | 0.767309
Fe | 6 | 16 | 1 | 30 | -3219.637177 | 1499 | 200 | 1.200623
Fe | 8 | 16 | 1 | 30 | -3219.637568 | 2039 | 200 | 1.633135
Fe | 12 | 16 | 1 | 30 | -3219.637381 | 1485 | 87 | 1.189409
Fe | 16 | 16 | 1 | 18 | -3219.633742 | 1399 | 67 | 1.120528
Fe | 2 | 16 | 0 | 365 | -3219.637177 | 2723 | 200 | 2.180984
Fe | 4 | 16 | 0 | 203 | -3219.637381 | 3970 | 200 | 3.179768
Fe | 6 | 16 | 0 | 122 | -3219.637177 | 1726 | 75 | 1.382438
Fe | 8 | 16 | 0 | 113 | -3219.637568 | 6127 | 200 | 4.907415
Fe | 12 | 16 | 0 | 68 | -3219.637381 | 6205 | 200 | 4.969889
Fe | 16 | 16 | 0 | 63 | -3219.633742 | 3967 | 69 | 3.177365
Fe | 2 | 16 | -1 | 729 | -3219.637121 | 7666 | 200 | 6.140075
Fe | 4 | 16 | -1 | 405 | -3219.637381 | 7769 | 200 | 6.222573
Fe | 6 | 16 | -1 | 243 | -3219.637177 | 3739 | 79 | 2.994748
Fe | 8 | 16 | -1 | 225 | -3219.637568 | 11651 | 200 | 9.331857
Fe | 12 | 16 | -1 | 135 | -3219.637381 | 11197 | 200 | 8.968226
Fe | 16 | 16 | -1 | 125 | -3219.633743 | 6307 | 59 | 5.051586


### 3. Mag constrained to [0.115, 0.034, 1.9964015127223282]

Element | N | Cores | symmetry | K points number | Energy per atom (eV) | Times (s) | Loop Steps | Cost (RMB)
-- | -- | -- | -- | -- | -- | -- | -- | --
Fe | 2 | 16 | 1 | 35 | -3219.637176 | 475 | 200 | 0.380451
Fe | 4 | 16 | 1 | 45 | -3219.637381 | 1024 | 200 | 0.820172
Fe | 6 | 16 | 1 | 30 | -3219.637176 | 1542 | 200 | 1.235063
Fe | 8 | 16 | 1 | 30 | -3219.637568 | 2142 | 200 | 1.715633
Fe | 12 | 16 | 1 | 30 | -3219.637381 | 1904 | 99 | 1.525007
Fe | 16 | 16 | 1 | 18 | -3219.633742 | 1506 | 71 | 1.206229
Fe | 2 | 16 | 0 | 365 | -3219.637177 | 3414 | 200 | 2.73444
Fe | 4 | 16 | 0 | 203 | -3219.637381 | 3965 | 200 | 3.175763
Fe | 6 | 16 | 0 | 122 | -3219.637004 | 6444 | 200 | 5.161316
Fe | 8 | 16 | 0 | 113 | -3219.637568 | 6622 | 200 | 5.303885
Fe | 12 | 16 | 0 | 68 | -3219.637381 | 6122 | 200 | 4.90341
Fe | 16 | 16 | 0 | 63 | -3219.633742 | 4739 | 92 | 3.795697
Fe | 2 | 16 | -1 | 729 | -3219.636905 | 9187 | 200 | 7.358319
Fe | 4 | 16 | -1 | 405 | -3219.637381 | 8123 | 200 | 6.506109
Fe | 6 | 16 | -1 | 243 | -3219.637177 | 5090 | 97 | 4.076831
Fe | 8 | 16 | -1 | 225 | -3219.637567 | 12962 | 200 | 10.3819
Fe | 12 | 16 | -1 | 135 | -3219.637381 | 11878 | 200 | 9.513673
Fe | 16 | 16 | -1 | 125 | -3219.633742 | 11685 | 133 | 9.35909

The INPUT parameters are setted as the following:
```
INPUT_PARAMETERS
suffix                          ABACUS
calculation                     scf
ecutwfc                         100
scf_thr                         1.0e-7
scf_nmax                        200
out_chg                         0
smearing_method                 gauss
smearing_sigma                  0.01
mixing_type                     broyden
mixing_ndim                     10
mixing_beta                     0.4
mixing_beta_mag			1.0
mixing_gg0_mag                  0
ks_solver                       genelpa
basis_type                      lcao
symmetry                        1
noncolin			1
lspinorb			0
nspin                           4
out_mul                         true
kspacing                        0.13


#deltaspin
sc_mag_switch                   1
decay_grad_switch               0
sc_thr                          1e-7
nsc                             100
nsc_min                         2
sc_file                         sc.json
alpha_trial                     0.01
sccut                           3
```

`Fe_gga_7au_100Ry_4s2p2d1f.orb` and `Fe_ONCV_PBE-1.2.upf` were used.
