### ISSUE TITLE
Incorrect Stress and volume during GPU Calculation

### ISSUE THREAD

**Issue by ieiue** [deepmodeling/abacus-develop#3851]
### Describe the bug

When making cell-relax calculation of Fe_16 by GPU, the stress(of 2nd step) and volume(of last step) were quite different from the results of CPU. The parameters are same, except "device" to decide GPU or CPU. And I compare those two lattice vectors with Fe_2, the Fe_16 CPU result was more accurate. Then I expanded "stress_thr" from 0.5 to 0.1 and calculate with GPU again, and got the same 2nd step stress with CPU. 
![img_v3_029f_bd8d5cc6-1b03-4c29-ba63-43430f8e014g](https://github.com/deepmodeling/abacus-develop/assets/116336560/4a134090-c40d-4280-aafe-3c54e698bdd6)

 

### Expected behavior

Why are the stress and volume so strange?

### To Reproduce

[Fe16_pw.zip](https://github.com/deepmodeling/abacus-develop/files/14811294/Fe16_pw.zip)

### Environment

ubuntu 20.04
ABACUS v3.5.4 (both CPU and GPU)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by dyzheng** [comment]
Firstly, please close symmetry and retest again.

**Comment by dyzheng** [comment]
Secondly, I suggest to set nspin=1 and retest again.

**Comment by ieiue** [comment]
When calculating with gpu,  do not set the number of processes to more than 1, this will get the same result as the cpu. It's related to the default "kpar" value set by the gpu.
I made two calculations:
1. Fe_2    cpu   "kpar"=4.        The same error occurred with the gpu.
2. Fe_16  gpu   processes=1.  Volume and stress are no longer strange.
Here are the results.
Fe2:
![image](https://github.com/deepmodeling/abacus-develop/assets/116336560/97bf4bc7-0226-4ed7-bc26-09b2ca111caf)
![image](https://github.com/deepmodeling/abacus-develop/assets/116336560/ed106da9-07a7-4788-9252-c734709dcecf)
Fe16:
![image](https://github.com/deepmodeling/abacus-develop/assets/116336560/38f66bc0-a382-4bb0-b81f-af4acf2b4a53)
![image](https://github.com/deepmodeling/abacus-develop/assets/116336560/6011f02e-f448-4c80-872f-5d3fba220ff0)

**Comment by ieiue** [comment]
> Secondly, I suggest to set nspin=1 and retest again.

Thanks for your suggestion. The developers found that the values of nspin and kapr were the problem.

**Comment by WHUweiqingzhou** [comment]
@pxlxingliang, I suggest adding an example about `kpar` in CI test once this issue is solved.

**Comment by WHUweiqingzhou** [comment]
@Qianruipku, could you have a look?

**Comment by WHUweiqingzhou** [comment]
Since this issue is not related with DCU, I will close this issue and post a new one.
