### ISSUE TITLE
The magnetism in STRU_ION_D after relaxation is incorrect

### ISSUE THREAD

**Issue by mohanchen** [deepmodeling/abacus-develop#3856]
### Describe the bug

After relaxing a cell with spin=2, the final magnetism is not printed correctly in the STRU_ION_D file. The magnetism in STRU_ION_D is still the initial magnetism.

### Expected behavior

The STRU_ION_D file should contain the final magnetism information.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
This issue can be solved by:
1. after relaxation, calculate atomic magnetic moment. refer to `out_mulliken()`.
2. output atomic magnetic moment in `print_stru_file()`

I think it wiil be a good practice for the junior developer.

**Comment by WHUweiqingzhou** [comment]
@mohanchen,
After #4044, ABACUS will output final mag instead of initial mag in `STRU_ION_D` with `out_mul 1`.
