### ISSUE TITLE
Bugs for TDDFT

### ISSUE THREAD

**Issue by lyb9812** [deepmodeling/abacus-develop#386]
## Describe the Bug
The forces of AlH system are different for different core numbers after scf calculation in reconstruction branch.

## To Reproduce
Relevant files are in the attachment.  Run scf.sh to calculate  and then run_result_scf.sh to see the result.

## Environment
- OS: CentOS Linux release 7.6.1810
- Compiler: intel2018
- Optional Dependencies: fftw-3.3.8 boost_1_64_0 elpa-2016.05.004

## Additional Context
The z length of the lattice in AlH_1.tar.gz is half of the one in AlH_2.tar.gz. For different core numbers, results in AlH_1.tar.gz are the same, while results in AlH_2.tar.gz are different.
[AlH_1.tar.gz](https://github.com/deepmodeling/abacus-develop/files/7337231/AlH_1.tar.gz)
[AlH_2.tar.gz](https://github.com/deepmodeling/abacus-develop/files/7337232/AlH_2.tar.gz)

**Comment by mohanchen** [comment]
I guess this problem origins from the implemented algorithm was still incorrect, right? @lyb9812

**Comment by lyb9812** [comment]
> I guess this problem origins from the implemented algorithm was still incorrect, right? @lyb9812

Yes, but the importance of the small difference for tddft need further test after completing the new implementation.

**Comment by caic99** [comment]
Hi @lyb9812 ,
Do you have any update on this issue? Will you try to reproduce it with the latest codes?

**Comment by lyb9812** [comment]
> Hi @lyb9812 ,
> Do you have any update on this issue? Will you try to reproduce it with the latest codes?

I will update codes for parallel version recently and test the case again.

**Comment by caic99** [comment]
@lyb9812 Any update?

**Comment by lyb9812** [comment]
> @lyb9812 Any update?

Now TDDFT branch doesn't have this bug anymore.
