### ISSUE TITLE
The performance of add_json is uncertain

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3862]
### Details

Some `add_json` codes are not included in timer, like:
https://github.com/deepmodeling/abacus-develop/blob/fe07b2e5adaa07365e4de22406c843935eb7135d/source/module_esolver/esolver_ks.cpp#L551-L558

What is the performance of these codes?

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by grysgreat** [comment]
This function is only added after each `scf` iteration is complete. It is actually equivalent to a string operation function, and takes up very little time: a single execution is about 1us, accounting for about 0.0001% of the total time of the program.

**Comment by grysgreat** [comment]
![image](https://github.com/deepmodeling/abacus-develop/assets/57103981/82c73f69-ac92-4dc8-9ef6-d9ecb1c00c62)

**Comment by WHUweiqingzhou** [comment]
Look like the time cost of `add_json` is negligible.
