### ISSUE TITLE
Tests: we need a more comprehensive DCU test report.

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#3864]
### Describe the Testing Issue

Current DCU report only considers some simple cases with `nspin=1`. We need to design a more comprehensive test to make sure our DCU is reliable. Any suggestion is welcomed!

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by pxlxingliang** [comment]
In current daily test, the pw datasets already have two examples with nspin =2 (006_27Fe and 008_Li27Ni9O54Mn9Co9):
https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fsched-abacustest-dcu-cg-bcd0c4

**Comment by WHUweiqingzhou** [comment]
This issue is closed temporarily.
