### ISSUE TITLE
SCF is hard to converge

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3883]
### Describe the Testing Issue

For below 5 alloy system, the SCF is hard to converge in 100 steps, and three of them have a large drho about 1e0 even in ~100 SCF steps.

The inputs and log files:
[scf.zip](https://github.com/deepmodeling/abacus-develop/files/14830345/scf.zip)

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by WHUweiqingzhou** [comment]
This converge issue is induced by 5f electron, we can discuss it in #3937
