### ISSUE TITLE
The output of MD with OFDFT is hexadecimal

### ISSUE THREAD

**Issue by sunliang98** [deepmodeling/abacus-develop#3895]
### Describe the bug

When running MD with OFDFT, for example `tests/integrate/920_OF_MD_LDA`, the output on the screen is hexadecimal after the first ion step:

>  -------------------------------------------
>  STEP OF MOLECULAR DYNAMICS : 1
>  -------------------------------------------
> ============================== Running OFDFT ==============================
> Iter        Etot(Ha)          Mu(Ha)      Theta      PotNorm     deltaE(Ha)
> 0     -0x1.064a92506c435p+3 0x1.3a12bbb7c5bd5p-20x1.999999999999ap-30x1.a7691fbc10e43p-30x1.45de87390732p-2
> 1     -0x1.0862de7f6e897p+3 0x1.34096b50fb5b1p-20x1.e99cff841acd8p-50x1.dfa32827b3271p-3-0x1.0c261781231p-4
> 2     -0x1.105007225b77ap+3 0x1.1df1a64cba103p-20x1.01c89b4416a8dp-40x1.703f72dba7b45p-5-0x1.fb4a28bb3b8cp-3
> 3     -0x1.1077c36f169a2p+3 0x1.1d50b28602563p-20x1.0f06feb865a3cp-70x1.e033d0a3ce699p-8-0x1.3de265d914p-8
> 4     -0x1.1078e5e74461fp+3 0x1.1d47ec6202319p-20x1.c64c4a3626301p-100x1.37940de0e9e91p-10-0x1.22782dc7dp-13
> 5     -0x1.1078ed90c161ep+3 0x1.1d46f789e1052p-20x1.20298952c1de6p-120x1.63531d0536bf4p-12-0x1.ea5f3ffcp-19
> 6     -0x1.1078ee27cc672p+3 0x1.1d473e15a42d7p-20x1.c8068a136966cp-140x1.bd17a759422b2p-15-0x1.2e160a8p-22
> 7     -0x1.1078ee2ba5db8p+3 0x1.1d474a38d2145p-20x1.28a9baceff18dp-160x1.15e5c569f4c83p-17-0x1.ecba3p-28

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by mohanchen** [comment]
need unit tests in future

**Comment by sunliang98** [comment]
> need unit tests in future

OK
