### ISSUE TITLE
PW, Ewald part, 4core and below get stuck, above 4 core return error

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#392]
## Describe the Bug

PW, Ewald part, 4core and below get stuck, above 4 core return error
[H_Ewald_pw rgen.zip](https://github.com/deepmodeling/abacus-develop/files/7344766/H_Ewald_pw.rgen.zip)

**Comment by wenfei-li** [comment]
This issue has not been resolved yet. I'll take a look.

**Comment by wenfei-li** [comment]
@dyzheng It seems you are testing on a pretty extreme structure, where the unit cell is only 1 Bohr^3 in real space. Therefore in computing Ewald term, the 'short range' part will include more cells in the real space. We used to set H_Ewald_pw::mxr to 50, which falls insufficient in this case. Setting the parameter to 100 and it works fine.

**Comment by wenfei-li** [comment]
Furthremore, if you set unit cell to be twice big and put repetitive atoms in the unit cell, mxr of 50 is sufficient, and the Ewald term evaluated is exactly 8 times. Therefore the only issue is with mxr. I checked qe and for certain purposes they are using a mxr of 500, I'll update our mxr to 200 just in case someone uses such an extreme structure like in this issue.

**Comment by dyzheng** [comment]
Thanks for your solution!
