### ISSUE TITLE
NSCF should EXIT with `init_chg file` when there is no SPIN1_CHG.cube file from the SCF step

### ISSUE THREAD

**Issue by xdzhu** [deepmodeling/abacus-develop#3923]
### Describe the bug

When I use ABACUS for the NSCF Berry phase calculation, I utilize the `init_chg file` parameter. However, when my previous self-consistent field SCF run fails and does not output any SPIN1_CHG.cube file, the NSCF calculation still continues.

In my opinion, it makes no sense because it gives WRONG result using a charge density that is not converged from an SCF calculation. I think it should throw an error and exit instead.

![a1a889e32893b9c8ae0dcb86aa62ca6](https://github.com/deepmodeling/abacus-develop/assets/55775434/783fa94c-3cf5-47d4-8f06-6d84f10c1ca3)

### Expected behavior

NSCF throw an error and exit instead when using `init_chg file` but there is no CHG.cube file

### To Reproduce

[issue-nscf-not-exit.zip](https://github.com/deepmodeling/abacus-develop/files/14895675/issue-nscf-not-exit.zip)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by pxlxingliang** [comment]
This is fix in : https://github.com/deepmodeling/abacus-develop/pull/4560
