### ISSUE TITLE
Poor performance of zdot.

### ISSUE THREAD

**Issue by grysgreat** [deepmodeling/abacus-develop#3925]
### Details

The performance of the Zdot function is too low compared to other vector operations (axpy, vecmul).

According to perf_math_kernel tests, several blas functions have the following performance results：
![img_v3_029n_4f1c5285-e9fe-49b4-a0af-af8790dc0efg](https://github.com/deepmodeling/abacus-develop/assets/57103981/2cf3d7d2-12ce-497d-bf81-4c59d58db27f)

Look up the implementation of these functions in Abacus: find that the Zdot function is written entirely by using for loop. But the other blas functions are called by abacus' external blas library implementation. This may be the reason why zdot is relatively slow.
![QbE3e4IpcP](https://github.com/deepmodeling/abacus-develop/assets/57103981/0efabaee-ada5-48ed-b58c-f57a8c8c539b)

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by WHUweiqingzhou** [comment]
@grysgreat do you have any plan to fix it by yourself?

**Comment by Critsium-xy** [comment]
![Image](https://github.com/user-attachments/assets/a233face-7cfa-46a8-b1a2-e2740344e13b)
![Image](https://github.com/user-attachments/assets/a64c96e9-fceb-4a95-8aab-f1f3d973db7e)
![Image](https://github.com/user-attachments/assets/db4fb784-0339-471a-bba5-4955f05820ec)

Are you sure this zdot used in the benchmark is implemented by ourselves? I remember that this zdot is also directly using dot from cblas. If it is just using cblas we are actually unable to modify it to make it faster.
