### ISSUE TITLE
The noncollinear spin polarized calculation does not work properly

### ISSUE THREAD

**Issue by planewavewzr** [deepmodeling/abacus-develop#3927]
### Describe the bug

noncolin=1, lspinorb=1
The nscf calculation seems to stop when 'Read in the charge density: OUT.CrTaS/SPIN4_CHG.cube'

### To Reproduce

[nscf.zip](https://github.com/deepmodeling/abacus-develop/files/14897664/nscf.zip)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@dyzheng, could you have a look?

**Comment by WHUweiqingzhou** [comment]
@planewavewzr 
I reproduce your calculation by using INPUT you provide in the attachment, and get a normal end without error [test](https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-issue3927-abacustest-v0.3.110-76f9ea). Please try the latest version, and re-run it.
Please reopen this issue if you can reproduce the error.
