### ISSUE TITLE
Perf: Large memory cost of Force&Stress calculations result in Out-Of-Memory Issues

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#3931]
### Details

Large memory cost of Force&Stress calculations result in Out-Of-Memory Issue. I upload an example from user in the attachment, that case meets a OOM issue in DCU, since DCU's memory is limited.

[example.zip](https://github.com/deepmodeling/abacus-develop/files/14901149/example.zip)

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by yizeyi18** [comment]
For a fast solve, adding cards(or say, nodes) would help.
Managing accelerator's memory may be a bit harder than host's. As far as I known, umpire(https://github.com/LLNL/Umpire) does this, may we do something similar or just use some solver based on this...?
