### ISSUE TITLE
SOC convergence problem for BCC Fe 

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#3939]
### Describe the bug

`scf_nmax` is set to 200. Finally drho 5.496971e-06, energy difference = 1.226634e-03 eV. The energy difference is very large.

### Expected behavior

Get converged results.

### To Reproduce

[soc_convergence.tar.gz](https://github.com/deepmodeling/abacus-develop/files/14912577/soc_convergence.tar.gz)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
I suggest you can use so-called Angle Mixing method (PR #3356), which is expected to give a better convergence than DIIS method for non-colinear calculations. Since `drho` is defined by summing over all spinor, `drho` is quite hard to converge into `1e-6` and you can release it a little bit, f.e. `2e-6` or `4e-6`. You can set
```bash
mixing_angle   1.0
mixing_beta     0.2
mixing_beta_mag   1.0
scf_thr      2e-6
```

**Comment by hongriTianqi** [comment]
Thanks for your suggestion. The results come very well: https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.108-538675

**Comment by hongriTianqi** [comment]
@WHUweiqingzhou Thanks for your suggestion. Sorry to inform that some cases still met convergence difficulty with the above setting:
```
GE181  -6.819687e+03  -3.368666e-07  2.619e-06  2.029e+01
 GE182  -6.819687e+03  5.968269e-07   3.183e-06  2.027e+01
 GE183  -6.819687e+03  -6.700650e-07  3.033e-06  2.030e+01
 GE184  -6.819687e+03  4.082850e-07   3.415e-06  2.029e+01
 GE185  -6.819687e+03  -4.099856e-07  2.604e-06  2.025e+01
 GE186  -6.819687e+03  6.698856e-07   3.364e-06  2.028e+01
 GE187  -6.819687e+03  -5.939329e-07  3.104e-06  2.035e+01
 GE188  -6.819687e+03  3.345604e-07   3.137e-06  2.030e+01
 GE189  -6.819687e+03  -4.127807e-07  2.616e-06  2.032e+01
 GE190  -6.819687e+03  6.707603e-07   3.300e-06  2.032e+01
 GE191  -6.819687e+03  -5.941463e-07  3.141e-06  2.027e+01
 GE192  -6.819687e+03  3.321969e-07   3.075e-06  2.028e+01
 GE193  -6.819687e+03  -4.087041e-07  2.631e-06  2.030e+01
 GE194  -6.819687e+03  6.696188e-07   3.322e-06  2.032e+01
 GE195  -6.819687e+03  -5.947372e-07  3.046e-06  2.033e+01
 GE196  -6.819687e+03  3.326717e-07   3.132e-06  2.035e+01
 GE197  -6.819687e+03  -4.088140e-07  2.639e-06  2.027e+01
 GE198  -6.819687e+03  6.673551e-07   3.317e-06  2.029e+01
 GE199  -6.819687e+03  -5.930790e-07  3.090e-06  2.046e+01
 GE200  -6.819687e+03  3.324552e-07   3.138e-06  2.028e+01
 !! CONVERGENCE HAS NOT BEEN ACHIEVED !!
```


See the attached case:

[soc_converge.tar.gz](https://github.com/deepmodeling/abacus-develop/files/14940584/soc_converge.tar.gz)

**Comment by WHUweiqingzhou** [comment]
@hongriTianqi,
I make some tests, and find old DIIS mixing with `mixing_beta=0.1` can reach a quite low `EDIFF~1e-10`, which is better than `mixing_angle=1.0` method.
