### ISSUE TITLE
ABACUS MD output 

### ISSUE THREAD

**Issue by Liu-RX** [deepmodeling/abacus-develop#394]
## Background
The problems are encountered when I was adding ABACUS MD interface in dpdata (https://github.com/deepmodeling/dpdata).

## Problems
(1) The index number of output cif file containing atomic coordinates does NOT match the ion iteration index written in `running_md.log`.
For example, file `md_pos_1.cif` actually corresponds to atomic coordinates of `ION=   2` iteration, rather than `ION=   1` iteration. `ION=   1` iteration actually corresponds to the atomic coordinates in input STRU file.
(2) The output atomic positions are in direct coordinates, but the output forces and stresses are in Cartesian coordinates. They don't match each other. 
One has to either convert atomic positions to Cartesian coordinates or convert forces, stresses to direct coordinates if he/she wishes to use positions, stresses and forces at the same time.
If the output level is turned to `ie`, the Cartesian coordinates of atomic positions will be output, but loads of other useless information of electron iterations will also be output.
The lattice vector of each iteration should also be output, if NpT ensemble is to be implemented.

**Comment by Liu-RX** [comment]
I think it's also necessary to add a parameter recording number of element species in STRU file. 
Right now we have element number stored in INPUT while the structure information is stored in STRU. In this way, we cannot decouple input calculation parameters and structure information into the two files, since the number of elements is stored in INPUT rather than STRU.

**Comment by mohanchen** [comment]
@YuLiu98 please take a look

**Comment by YuLiu98** [comment]
The format of output structure files is the same with STRU now in update_MD branch, but only for CMD.

I will conticue the reconstruction of MD to solve the problems.

Besides, I have a problem: Whether the force and stress need to be stored in independent files? @Liu-RX

**Comment by Liu-RX** [comment]
> The format of output structure files is the same with STRU now in update_MD branch, but only for CMD.
> 
> I will conticue the reconstruction of MD to solve the problems.
> 
> Besides, I have a problem: Whether the force and stress need to be stored in independent files? @Liu-RX

I think you'd better save the cell, forces and stresses in independent files, like qe does. Maybe you could provide an option in INPUT file for users to choose, whether to use the old output mode or output as independent files.
Another problem I have with the old output mode is that no matter what the coordinates output frequency is, it always writes stresses and forces for each single MD step. But there is no reason to write stresses and forces if no coordinates are written. I think the output frequency for stresses and forces should be the same as coordinates output.

**Comment by dyzheng** [comment]
Is there any development for this Issue recently? 
I have added this Issue to program ABACUS_v2.2.0 several months ago, if the solution is still undel discussion, I will remove this Issue to another program.
@Liu-RX @YuLiu98 @mohanchen

**Comment by YuLiu98** [comment]
> Is there any development for this Issue recently? I have added this Issue to program ABACUS_v2.2.0 several months ago, if the solution is still undel discussion, I will remove this Issue to another program. @Liu-RX @YuLiu98 @mohanchen

The MD output format has been determined: 
1) output STRU files and thermostat information per `md_restartfreq` step;
2) dump cell lattice, virial, atomic positions, and atomic forces into the `MD_dump` file per `md_dumpfreq` step;

**Comment by caic99** [comment]
Related: #609
