### ISSUE TITLE
Atomic magnetic information loss in STRU file during the dpgen + abacus workflow

### ISSUE THREAD

**Issue by KK33999** [deepmodeling/abacus-develop#3942]
### Describe the bug

When I perform a workflow of dpgen + abacus, I prepare a perturbed structure in init/STRU.01x01x01/00.place_ele/sys-0036-0096/STRU file and add atomic magnetic information in STRU file. I use this structure as a initial structure to use **dpgen run param.json machine.json**. However, when I reach the 02.fp step, it seems that after a dpdata conversion, the atomic magnetic information in the STRU file has been lost. 

### Expected behavior

I am not sure this problem can be attributed to ABACUS or Dpgen. But I wish that atomic magnetic information don't loss.

### To Reproduce

**my initial STRU file:**
ATOMIC_POSITIONS
Direct 	//Cartesian or Direct coordinate.
Nb 	// Element type
0.0 	// magnetism
36 	// number of atoms
     0.803569973         0.267859995         0.082450002 mag  0.5
     0.303570002         0.767859995         0.082450002 mag  0.5
     0.196429998         0.398809999         0.250880003 mag  -0.5
     0.696430027         0.898810029         0.250880003 mag  -0.5
............

**STRU in 02.fp file:**
ATOMIC_POSITIONS
Cartesian    # Cartesian(Unit is LATTICE_CONSTANT)
Nb
0.0
36
6.152880000000 3.620300000000 3.388680000000 1 1 1
2.277500000000 10.205400000000 3.441630000000 1 1 1
1.473130000000 5.270050000000 10.539500000000 1 1 1
5.311980000000 11.826200000000 10.575700000000 1 1 1
1.461040000000 3.549240000000 3.348810000000 1 1 1
..........

**It is obvious that atomic magnetic information have been lost.
This phenomenon can be observed from the file in abacus-user-guide/examples/abacus-dpgen/**

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by KK33999** [comment]
I find the same issue about this ploblem in the website of dpgen: https://github.com/deepmodeling/dpgen/issues/1487

**Comment by kaiqi-wang** [comment]
I find the same issue about this ploblem in the website of dpgen: https://github.com/deepmodeling/dpgen/issues/1487
