### ISSUE TITLE
Add single-atom to the reference systems of spillage-based orbital generation

### ISSUE THREAD

**Issue by jinzx10** [deepmodeling/abacus-develop#3946]
### Background

In the current spillage-based orbital generation, reference structures are chosen to be dimers and trimers of different geometric configurations. However, since the spillage function have multiple local minima, a good initial guess is very important. For that purpose, an option is to take advantage of the single-atom spillage function where an analytic expression of the optimal spillage exists.

### Describe the solution you'd like

there are two possible ways:

1. always make a single-atom calculation in the orbital generation, or
2. make an extra reference structure "single atom" available, and only perform a single-atom calculation on demand

I personally prefers 1, but 2 is also acceptable.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by kirk0830** [comment]
@dyzheng Directly including single atom into numerical atomic orbital fitting means including explicit consideration on the case that "atom to be isolated". How do you think? Will it enhance the transferability or contrarily it might be detriment?

**Comment by kirk0830** [comment]
I have added one keyword `spill_guess` in orbital generation codes, once specified as `atomic`, will perform calculation on single atom, yields folder as:
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/91be0d43-b6f3-4ba0-89fb-4bdd4ce800ab)
. The keyword `spill_guess` has default value `random`, in this case, the single atom case calculation will not be performed.
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/79eeb698-9492-4132-b34b-b0b112e8433e)

PR: https://github.com/kirk0830/abacus_orbital_generation/pull/29
