### ISSUE TITLE
Relax of Pt(111)-OH CANNOT converge #3560

### ISSUE THREAD

**Issue by Luc1anoo** [deepmodeling/abacus-develop#3948]
### Describe the Testing Issue

[data.zip](https://github.com/deepmodeling/abacus-develop/files/14930206/data.zip)

Relax of Pt(111)-OH CANNOT converge. The STRU is constructed by Materials Studio in .cif format and then converted into STRU format using ase-abacus (python3 cif2STRU.py), and I have manually set the bottom two layers fixed. 
The reason why using relax instead of cell-relax is that ATST-Tools doesn't support different cell between initial structure and final structure in NEB calculation. This structure can relax successfully in VASP but cannot in ABACUS now.
I have redirected the stdout into result_lcao and result_pw respectively. I haven't fully test the "pw" basis since it's too time-consuming.

version: ABACUS v3.3.2

### Additional Context
The structure before relaxing should be:
![IS-before_relax](https://github.com/deepmodeling/abacus-develop/assets/105922114/ab226771-8157-40e7-97ba-fbd95633c9f1)

The structure after relaxing should be:
![IS-after_relax](https://github.com/deepmodeling/abacus-develop/assets/105922114/fdbd00b2-1ab3-4026-bb93-ed2d4fc6ad1f)

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by kirk0830** [comment]
After refactor of two-center-integral for estimating matrix element between numerical atomic orbitals and that of BFGS for fully considering PBC in ion movement, I would suggest you try the latest version of ABACUS.

Hope that helps

**Comment by WHUweiqingzhou** [comment]
As @kirk0830 suggests, please try the latest version, after v3.3.2, we made some changes which may affect relaxation.

**Comment by Luc1anoo** [comment]
SCF will converge after the ABACUS version is changed from v3.3.2 to 3.6.0, with all parameters remaining unchanged. Thanks!

**Comment by QuantumMisaka** [comment]
@Luc1anoo 
One notice: for surface simulation in ABACUS, it is better to let the vacuum layer along y-direction (in most of my test), which will have the best MPI parallel performance and enhance SCF performance a lot ( due to the lattice integral algorism in ABACUS )
