### ISSUE TITLE
The energy in abacus.json is null when esolver is not KS

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3955]
### Describe the bug

I use lj esolver to run a relax job, and the energy in outputed abacus.json is `null`.

At current version, only KS esolver can output the energy in abacus.json, we should support other esolvers.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@pxlxingliang do you have plan to solve it recently?
