### ISSUE TITLE
[APNS] Feature: high throughput EOS test workflow will be available soon

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#3992]
### Describe the Testing Issue

for benchmarking precision of various pseudopotentials

### Additional Context

![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/89dff1da-0274-413a-809e-c84db84db42e)

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by mohanchen** [comment]
Will you set symmetry=1?

**Comment by kirk0830** [comment]
> Will you set symmetry=1?

@mohanchen yes but seems it will affect fewer than expected, because actually in paper 10.1038/s42254-023-00655-3 what authors actually used are arbitrary structures like SC, BCC, FCC and Diamond for all elements, therefore the number of atoms in cell would be small.

**Comment by kirk0830** [comment]
EOS high-throughput test workflow can run, but please see following issue #4011
