### ISSUE TITLE
force compute error in Fe128 in lcao

### ISSUE THREAD

**Issue by A-006** [deepmodeling/abacus-develop#3994]
### Describe the bug

when i use abacus to calculate force in Fe128,the force is not same when i try.
I use MPI=4 and openmp=7 to compute this case,
however the result came as 
![image](https://github.com/deepmodeling/abacus-develop/assets/74701833/9ee826f2-c861-4e95-9c2e-13c7179e5d6f)
![image](https://github.com/deepmodeling/abacus-develop/assets/74701833/d2d61992-e3e8-4955-8fd7-9df45852bff4)
and the INPUT file set as below
INPUT_PARAMETERS
#Parameters (1.General)
suffix			autotest
calculation     scf

#nbands			8
symmetry		1

#Parameters (2.Iteration)
ks_solver       genelpa
cal_stress      1
cal_force       1
gamma_only      1
ecutwfc			100
scf_thr				1e-6
scf_nmax			100

#Parameters (3.Basis)
basis_type		lcao

#Parameters (4.Smearing)
smearing_method		gauss
smearing_sigma			0.002

#Parameters (5.Mixing)
mixing_type		pulay
mixing_beta		0.3
ks_solver  genelpa
gamma_only 1
cal_stress 1
cal_force 1
 

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@A-006,
Do you mean you get the different force by using different parallel settings.
I will suggest you decrease `scf_thr`, f.e, `scf_thr=1e-8` even less since force and stress is more sensitive compared with charge density and energy.

**Comment by WHUweiqingzhou** [comment]
@A-006  any update?

**Comment by A-006** [comment]
I set `scf_thr=1e-8`, but the calculation still couldn't converge. When I changed the settings to `scf_thr=1e-7`, `MPI=1`, and `OPENMP=1`, the results of the force calculation continued to differ. I suspect that there are small variations in `rho` with each iteration. As a result, while the stress calculations appear correct, the forces remain inconsistent.
