### ISSUE TITLE
AIMD stops at 75-th MD step

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#400]
## Describe the Bug
I've been running some AIMD calculations on CH4, starting from slightly different configurations. All of the calculations stop in the middle of the 75-th MD step with errors.

## To Reproduce
1. Code : the latest newelpa branch
2. Compile : on Lebesgue, follow the steps in Dockerfile.intel
3. Running : I used 4 MPI threads to run the job
4. Example : see attached
[md_example.zip](https://github.com/deepmodeling/abacus-develop/files/7363386/md_example.zip)

**Comment by dyzheng** [comment]
caused by ELPA, use scalapack_gvx is okay for this test.
