### ISSUE TITLE
Some strange task that fails to run properly.

### ISSUE THREAD

**Issue by floatingCatty** [deepmodeling/abacus-develop#4007]
### Describe the bug

There are some task that I've run recently but not finished normally, including a scf task on MoS2 and two cell-relax tasks on GaN and GaSbN. Here I attached the files for your reference. Please help me to see if there is something wrong with my configuration.

### Expected behavior

Just find out why these tasks failed and how to fix that.

### Environment

[GaN.zip](https://github.com/deepmodeling/abacus-develop/files/15004871/GaN.zip)
[GaSbN.zip](https://github.com/deepmodeling/abacus-develop/files/15004876/GaSbN.zip)
[MoS2-hse.zip](https://github.com/deepmodeling/abacus-develop/files/15004882/MoS2-hse.zip)

### Additional Context

The output of the relaxation task is a bit abnormal, which looks like this:
![image](https://github.com/deepmodeling/abacus-develop/assets/64253517/481db03a-af20-411f-a1ce-36c2b866580c)
The mos2 task just kept running, not converging for almost 3 days.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@floatingCatty,
this issue has been solved in issue #3415. Please try the latest version.

**Comment by WHUweiqingzhou** [comment]
@floatingCatty，
if the issue still exists at the latest version, please reopen it and update your result. We will have a look at it.
