### ISSUE TITLE
Error Output of Magnetic Moment in STRU

### ISSUE THREAD

**Issue by ieiue** [deepmodeling/abacus-develop#4008]
### Describe the bug

When making a calculation which has "nspin=2", the result STRU from OUT.suffix has incorrect magnetic moment.
![image](https://github.com/deepmodeling/abacus-develop/assets/116336560/5987aacb-684b-4372-bc28-11ebbbe64904)

### Expected behavior

Output the correct mag or output nothing?

### Environment

ABACUS v.3.6.0

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by ieiue** [comment]
4 is my initial magnetic moment. But it still stays the same in the STRU after calculation.

**Comment by WHUweiqingzhou** [comment]
@ieiue, it is the same issue with #3856

**Comment by QuantumMisaka** [comment]
@WHUweiqingzhou @mohanchen This aspect has been mentioned by myself in the last year and then till now no change has happened, I consider that we should have a mind on it.

**Comment by WHUweiqingzhou** [comment]
@ieiue and @QuantumMisaka 
After #4044, ABACUS will output final mag instead of initial mag in `STRU_ION_D` with `out_mul 1`.
