### ISSUE TITLE
SIAB: we need parallelism across nodes on pw calculations in generating reference results in orbital generation

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#4023]
### Background

Thanks to @kirk0830 , we now have an excellent workflow for generating orbitals in LCAO calculation (https://github.com/kirk0830/abacus_orbital_generation). After discussion with @pxlxingliang , we rose an interesting issue on how to make the process more parallel. The parallelism on pw calculations in generating reference results would greatly reduce the time needed in orbital generation.

### Describe the solution you'd like

Having access to an workflow combining abacus_test and abacus_orbital_generation will greatly facilitate orbital generation.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by kirk0830** [comment]
will incorprate with abacustest workflow by following procedure:

generate all folders and invoke abacustest, do upload and waiting for job complete and download,
then do next steps.

Possible workflow changes:
change run_all or deeper functions called. Need auto-download and job-completeness check

**Comment by kirk0830** [comment]
This feature's implementation seems beyond my initial estimation. For I need to call job submission in Python, this is, not similar with the way how abacustest is used. And then a sign is needed to let the program know when the pw calculation is completed and can optimization of orbital proceed.
@pxlxingliang suggest me try to incorporate with dflow directly.
