### ISSUE TITLE
abacus-plot needs enhancement

### ISSUE THREAD

**Issue by Chentao168** [deepmodeling/abacus-develop#4030]
### Background

Compared to vaspkit, abacus-plot requires improvements in the following aspects

### Describe the solution you'd like

1. Improved data export for easier plotting customization.
2. Increased readability of its user manual, for better user onboarding.
Such as rewriting the PDOS plotting tutorial compared with vaspkit's example, 
![image](https://github.com/deepmodeling/abacus-develop/assets/76426373/4be4f947-8715-4cda-9974-a2ac8a0db267)
![image](https://github.com/deepmodeling/abacus-develop/assets/76426373/8ad4fbeb-b267-4ba6-a093-7fd33e968871)

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by dyzheng** [comment]
@1041176461 Can you help for this Issue?

**Comment by 1041176461** [comment]
1. Parsed data output have already been supported, one can use command line
![image](https://github.com/deepmodeling/abacus-develop/assets/40336950/f45c4814-7985-47a0-bcec-1a4e558528fa)
or Python script with write function 
![image](https://github.com/deepmodeling/abacus-develop/assets/40336950/67a0e3be-8b93-41ce-9e87-17f2742c6486)

2. We currently do not support a user interface like vaspkit, so there is no way to further simplify the input settings. If a user interface is required, this functionality can be scheduled, and it will require some time.

**Comment by Chentao168** [comment]
I tested abacus-plot and it can indeed output pdos.
