### ISSUE TITLE
Decreasing performance of convergence for new versions

### ISSUE THREAD

**Issue by AroundPeking** [deepmodeling/abacus-develop#4035]
### Details

Previously,  v3.3.2(`e39b50e`) was used for a long time. Recently, after updating to v3.6.0(`71b1159`), my calculations show lower performance. Attach is one of the tests, in which 290932 is calculated by v3.3.2 and 291618 by v3.6.0. 

Actually, I have encountered more severe situations. For example,  SCF is not converged by v3.3.2 but v3.6.0 succeeded in converging. I am sorry for losing this test. But the latter seems to be the same issue as the first one.

Test:
[H2.tar.gz](https://github.com/deepmodeling/abacus-develop/files/15050843/H2.tar.gz)

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by WHUweiqingzhou** [comment]
Hi @AroundPeking,
Thanks for your feedback. The difference you get is originated from so-called Kerker preconditioning. In v3.3.2, this preconditioning is turned off, while we default turn on it after v3.5.0 based on many tests. This preconditioning has very good improvement for the convergence of most metalic systems.
But from perspective of physics, this preconditioning is not necessary for isolated systems, f.e. H2.
You can turn it off by setting `mixing_gg0 0.0`, and result looks good:

```bash
 START CHARGE      : atomic
 DONE(3.63523    SEC) : INIT SCF
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
 GE1    -3.157212e+01  0.000000e+00   4.114e-01  2.158e+00  
 GE2    -3.173153e+01  -1.594153e-01  1.745e-02  2.119e+00  
 GE3    -3.173176e+01  -2.256923e-04  3.254e-03  2.037e+00  
 GE4    -3.173176e+01  -8.058602e-07  2.210e-04  2.035e+00  
 GE5    -3.173176e+01  -5.984361e-08  1.795e-05  2.081e+00  
 GE6    -3.173176e+01  -3.263664e-10  4.263e-08  1.917e+00  
``` 

I have added some  explanation in our online docs, see PR #4039.

**Comment by AroundPeking** [comment]
Thanks. I get it.
