### ISSUE TITLE
abacustest: output of the magnetic force metrics is needed in abacustest

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#4041]
### Background

In deltaspin calculation, the final results include final optimized lambda and magnetic force. If abacustest can retrieve the corresponding values, the post-process will become more convenient.

### Describe the solution you'd like

For example, the final optimal lambda and Magnetic force are now output on screen as:
```
Inner optimization for lambda ends.
===============================================================================
 GE64   -6.439376e+03  -1.317632e-08  1.398e-07  5.961e+00  
Total Magnetism (uB): 
ATOM 0         0.0000000000e+00    0.0000000000e+00    2.1599341842e+00
ATOM 1         0.0000000000e+00    0.0000000000e+00    2.1599337040e+00
Final optimal lambda (Ry/uB): 
ATOM 0         0.0000000000e+00    0.0000000000e+00   -3.5931898000e-05
ATOM 1         0.0000000000e+00    0.0000000000e+00   -3.5939101250e-05
Magnetic force (Ry/uB): 
ATOM 0        -0.0000000000e+00   -0.0000000000e+00    3.5931898000e-05
ATOM 1        -0.0000000000e+00   -0.0000000000e+00    3.5939101250e-05
```

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by pxlxingliang** [comment]
Metrics "ds_optimal_lambda" and "ds_mag_force" have been added in abacustest, please pull the latest develop branch to use.
https://github.com/pxlxingliang/abacus-test/tree/develop
