### ISSUE TITLE
The energy difference is large even drho is small in SCF

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#4042]
### Describe the bug

In ABACUS daily test, for case 003_12Pt111, the energy difference is still large even drho reach the converge threshold.
https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fsched-abacustest-intel-dav-d1a4c6

```
 START CHARGE      : atomic
 DONE(0.474566   SEC) : INIT SCF
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
 DA1    -3.960664e+04  0.000000e+00   1.868e-01  5.257e+01  
 DA2    -3.960662e+04  2.197685e-02   9.376e-02  8.867e+00  
 DA3    -3.960653e+04  8.641120e-02   4.585e-02  8.975e+00  
 DA4    -3.960656e+04  -3.109478e-02  7.536e-03  9.214e+00  
 DA5    -3.960656e+04  3.752576e-03   4.199e-03  7.715e+00  
 DA6    -3.960655e+04  3.502445e-03   1.127e-03  7.346e+00  
 DA7    -3.960655e+04  6.618376e-04   1.384e-04  8.400e+00  
 DA8    -3.960655e+04  3.445595e-04   1.227e-04  7.712e+00  
 DA9    -3.960655e+04  3.313663e-04   1.089e-05  6.460e+00  
 DA10   -3.960655e+04  1.280307e-04   2.827e-06  8.404e+00  
 DA11   -3.960655e+04  1.932879e-04   9.707e-07  8.863e+00  
 DA12   -3.960655e+04  1.175954e-04   3.369e-07  1.000e+01  
 DA13   -3.960655e+04  7.957665e-05   1.402e-07  8.060e+00  
 DA14   -3.960655e+04  1.075462e-04   2.780e-08  1.187e+01  
----------------------------------------------------------------
```

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@pxlxingliang,
This is originated from the definition of `get_drho()`, which will be divided by the number of total grid point:
```cpp
drho *= GlobalC::ucell.omega / static_cast<double>(this->rhopw->nxyz);
drho /= nelec;
```
Compared with bulk, `omega/nxyz` is much smaller in surface, leading a faster convergence. But it does not mean the surface converges to the ground state as close as the bulk.

I will suggest decreasing `scf_thr` for surface system. You can evaluate it by the ratio of vacuum volume to total cell.

**Comment by QuantumMisaka** [comment]
I've done some test and 
1. by using `nspin=2` can make EDIFF converge better (and the system will have AMAG and TMAG) （to 1e-6)
2. by using `scf_the 1e-9`  can make EDIFF converge better (to 1e-6)
3. LCAO part will have no problem
4. Transfrom vaccum direction to y-axis will make EDIFF converge somehow better (but the SCF time will be more) (which is interesting)
