### ISSUE TITLE
Besides data-HR and data-SR, I need an rR file without scf calculation

### ISSUE THREAD

**Issue by iduygnay** [deepmodeling/abacus-develop#4045]
### Background

rR is the output when I turn on "out_mat_r" tag. 
![b6f443f71a7d3f630f2a2357042d787](https://github.com/deepmodeling/abacus-develop/assets/109792836/8961a221-faf0-48b8-ab27-add1da1e8f2e)

### Describe the solution you'd like

Is it possible to get the rR matrix without scf calculation?

**Comment by iduygnay** [comment]
In detail, now I have the data-HR and data-SR, I need an rR file without scf calculation, and the number of R should be the same as the HR and SR I provided. 
[data-SR-sparse_SPIN0.zip](https://github.com/deepmodeling/abacus-develop/files/15073363/data-SR-sparse_SPIN0.zip)

**Comment by iduygnay** [comment]
[data-HR-sparse_SPIN0.zip](https://github.com/deepmodeling/abacus-develop/files/15073361/data-HR-sparse_SPIN0.zip)

**Comment by dyzheng** [comment]
You can wait for the merging of PR#4084 and try to set "calculation nscf" with "out_mat_r".

Or you can set "calculation scf" with "scf_nmax   1" and "out_mat_r" in current version.

**Comment by iduygnay** [comment]
[rR.zip](https://github.com/deepmodeling/abacus-develop/files/15180123/rR.zip)
This is the rR I got with the calculation you mentioned above. But pyatb reported that the shape is different from the SR or HR. I offered the SR and HR files above. Can you check the shape of them? I think the main issue is the number of R. 
![image](https://github.com/deepmodeling/abacus-develop/assets/109792836/39fecd53-7f90-48ce-b164-cf2f030e0b36)
If you check the shapes for them are the same, I will contact with pyatb developers.

**Comment by iduygnay** [comment]
This could be solved by pyatb developers. Thanks!

**Comment by iduygnay** [comment]
I found that for the large system, it always goes to oom for scf calculation or I have to wait a long time for wfc initialization. But the only thing I want to get is the rR matrix. Is there any suggestion to get this matrix without a large memory? Or can it be quick?

I also tried nscf calculation, but I don't have the charge or wfc files, tho it can not give me the rR matrix.

**Comment by mohanchen** [comment]
We will try to have a better solution to this feature.

**Comment by YuLiu98** [comment]
> I found that for the large system, it always goes to oom for scf calculation or I have to wait a long time for wfc initialization. But the only thing I want to get is the rR matrix. Is there any suggestion to get this matrix without a large memory? Or can it be quick?
> 
> I also tried nscf calculation, but I don't have the charge or wfc files, tho it can not give me the rR matrix.

You can set `calculation` to scf, `scf_nmax` to 0, and `out_mat_r` to 1 to get the rR matrix.
