### ISSUE TITLE
Should negative charge density of spin down electrons be allowed in ABACUS?

### ISSUE THREAD

**Issue by sunliang98** [deepmodeling/abacus-develop#4046]
### Details

In NSPIN=2 case, if we assign a magnetism value that exceeds the total number of electrons (nelec) in the cell - for instance, setting magnetism to 20 when nelec equals 10 - the initialized charge density will comprise 15 spin-up electrons and **-5 spin-down** electrons. Although this situation does not disrupt the calculation and may even yield the correct result, it raises the question of whether such an unphysical case should be permitted.
Corresponding code can be found in `atomic_rho` within the file `/module_elecstate/module_charge/charge.cpp`.
![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/cf17dbac-8278-4aac-8ac5-3e9a966ea79e)

In QE, the `starting_magnetization` is limited between -1 and 1, thereby preventing the occurrence of negative charge densities.
The description of `starting_magnetization` is as follow:
![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/13598f71-847b-4766-bdde-dde234269792)
Corresponding code in QE is:
![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/d32a839f-6663-4fb9-b0fe-eaa55f575d05)

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by WHUweiqingzhou** [comment]
I think we should add a `WarningQuit` to avoid such cases.

**Comment by WHUweiqingzhou** [comment]
I plan:
1. add a `check_mag()` in `charge.h`
2. run `check_mag()` after `this->charge->init_rho` in `ElecState::init_scf`

**Comment by sunliang98** [comment]
I think we should add a `WarningQuit` to avoid such cases.

Perhaps we could issue a warning and adjust the total magnetism to its maximum value in such instances, similar to the approach taken by Quantum ESPRESSO.

**Comment by WHUweiqingzhou** [comment]
> I think we should add a `WarningQuit` to avoid such cases.
> 
> Perhaps we could issue a warning and adjust the total magnetism to its maximum value in such instances, similar to the approach taken by Quantum ESPRESSO.

As far as I know, some users will set initial mag more than 1.0 in some calculation, shou we make some change about it?
