### ISSUE TITLE
DCU cg test error (Device)

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#4050]
### Describe the bug

At 2024-4-23 daily dcu test, the 003_12Pt111 suffered below error:

Test address: https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fsched-abacustest-dcu-cg-4e8282

```
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
 CG1    nan            nan            -nan       2.457e+02  

 notconv = 129
 DiagoCG::diag', too many bands are not converged! 

 notconv = 129
 DiagoCG::diag', too many bands are not converged! 

 notconv = 129
 DiagoCG::diag', too many bands are not converged! 

 notconv = 129
 DiagoCG::diag', too many bands are not converged! 
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 Error when factorizing beta.
 CHECK IN FILE : OUT.ABACUS/warning.log
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by denghuilu** [comment]
Similar to issues #4017, after upgrade the DTK version, no error founded.

**Comment by WHUweiqingzhou** [comment]
This issue is from the machine issue, not related with ABACUS.
