### ISSUE TITLE
Error due to symmetry in a simple test case

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#4056]
### Describe the bug

The error message is:
```
abacus: /root/abacus-develop/source/module_cell/klist.cpp:804: void K_Vectors::ibz_kpoint(const ModuleSymmetry::Symmetry&, bool, std::string&, const UnitCell&, bool&): Assertion `symm.equal(kvec_rot.x, kvec_rot_k.x)' failed.
```
, which occurs at:
```
void K_Vectors::ibz_kpoint

restrict_kpt(kvec_rot);
                if (this->is_mp)
                {
                    kvec_rot_k = kvec_d_k[i] * kkmatrix[j];   //k-lattice rotation
                    kvec_rot_k = kvec_rot_k * gk * ucell.G.Inverse(); //convert to recip lattice
                    restrict_kpt(kvec_rot_k);

804 ====> assert(symm.equal(kvec_rot.x, kvec_rot_k.x));
                    assert(symm.equal(kvec_rot.y, kvec_rot_k.y));
                    assert(symm.equal(kvec_rot.z, kvec_rot_k.z));
```

### Expected behavior

no error

### To Reproduce

[eos0.tar.gz](https://github.com/deepmodeling/abacus-develop/files/15105136/eos0.tar.gz)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@maki49 could you have a look?

**Comment by maki49** [comment]
No such problem in my environment (commit bec5e6468) with `symmetry_prec`=1e-4, 1e-5, 1e-6, 1e-7.
[1e-4.txt](https://github.com/deepmodeling/abacus-develop/files/15105492/1e-4.txt)
[1e-5.txt](https://github.com/deepmodeling/abacus-develop/files/15105494/1e-5.txt)
[1e-6.txt](https://github.com/deepmodeling/abacus-develop/files/15105495/1e-6.txt)
[1e-7.txt](https://github.com/deepmodeling/abacus-develop/files/15105496/1e-7.txt)

**Comment by hongriTianqi** [comment]
The same commit was used in my calculation, as can be seen here:
https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.113-903c30
in a directory like: /outputs/results/Co2/LCAO1/eos0

The image of `registry.dp.tech/deepmodeling/abacus-intel:latest` was used with the command of:
```
OMP_NUM_THREADS=1 mpirun -np 16 abacus | tee out.log
```

**Comment by maki49** [comment]
> The image of `registry.dp.tech/deepmodeling/abacus-intel:latest` was used with the command of:
> 
> ```
> OMP_NUM_THREADS=1 mpirun -np 16 abacus | tee out.log
> ```

I cannot reproduce this problem using docker with the same image and command on my server. Everything goes well with `symmetry`=1, 0 and above values of `symmetry_prec`.

**Comment by hongriTianqi** [comment]
But I can reproduce the error on my local machine with the same commit ...

**Comment by hongriTianqi** [comment]
The debug line:
```
                    restrict_kpt(kvec_rot_k);

                    std::cout << kvec_rot.x << " " << kvec_rot_k.x << std::endl;

                    assert(symm.equal(kvec_rot.x, kvec_rot_k.x));
```
gives result of:
```
-0.499999 -0.499999
0.5 -0.499999
```

**Comment by maki49** [comment]
> -0.499999 -0.499999
> 0.5 -0.499999

"-0.499999" is abnormal after `restrict_kpt` and does not appear in my debug. This function restricts the k-point direct coordinate to (-0.5, 0.5] with a small positive `symmetry_prec`. 
Are you using a zero or negative `symmetry_prec`? It can reproduce this problem. Maybe a range check with `symmetry_prec` should be added to `Input::Check`.

**Comment by hongriTianqi** [comment]
No, the `symmetry_prec` is default value 1e-6. I did not set this key in the INPUT.

**Comment by hongriTianqi** [comment]
Actually, the output value is also 1e-6:
```
UNIFORM GRID DIM        : 30 * 30 * 30
 UNIFORM GRID DIM(BIG)   : 10 * 10 * 10
 DONE(0.165567   SEC) : SETUP UNITCELL
symm.epsilon = 1e-06
-0.499999 -0.499999
0.5 -0.499999
```

**Comment by maki49** [comment]
Does this problem still appear on your machine with symmetry_prec=1e-5 or 1e-4? 
I have no other idea... May this result from a 32-bit system?

**Comment by hongriTianqi** [comment]
Thanks. I making an image on Bohrium for you to reproduce this error. I have added more debug lines according to your information:
```
    auto restrict_kpt = [&symm](ModuleBase::Vector3<double> &kvec){
        // in (-0.5, 0.5]
        std::cout << "initial = " << kvec.x << std::endl;
        kvec.x = fmod(kvec.x + 100.5-0.5*symm.epsilon, 1)-0.5+0.5*symm.epsilon;
        std::cout << "after = " << kvec.x << std::endl;
        kvec.y = fmod(kvec.y + 100.5-0.5*symm.epsilon, 1)-0.5+0.5*symm.epsilon;
        kvec.z = fmod(kvec.z + 100.5-0.5*symm.epsilon, 1)-0.5+0.5*symm.epsilon;
        // in [0, 1)
        // kvec.x = fmod(kvec.x + 100 + symm.epsilon, 1) - symm.epsilon;
        // kvec.y = fmod(kvec.y + 100 + symm.epsilon, 1) - symm.epsilon;
        // kvec.z = fmod(kvec.z + 100 + symm.epsilon, 1) - symm.epsilon;
        if(std::abs(kvec.x) < symm.epsilon) kvec.x = 0.0;
        if(std::abs(kvec.y) < symm.epsilon) kvec.y = 0.0;
        if(std::abs(kvec.z) < symm.epsilon) kvec.z = 0.0;
        return;
    };
```
Gives the results of:
```
symm.epsilon = 1e-06
initial = 2.83324e+179
after = -0.499999
initial = -0.499999
after = -0.499999
initial = 2.83324e+179
after = -0.499999
-0.499999 -0.499999
initial = 0.499999
after = 0.5
initial = -2.83324e+179
after = -0.499999
0.5 -0.499999
```

**Comment by maki49** [comment]
So the problem lies in the initial value. Neither `-2.83324e+179` nor `-0.499999` appears in my debug.
(with kspacing=0.13 or `12 12 7` in KPT file)

**Comment by hongriTianqi** [comment]
The name of image is registry.dp.tech/dptech/prod-585/reproducebug:klist, I need you email. Can you send me on Feishu?

**Comment by hongriTianqi** [comment]
> So the problem lies in the initial value. Neither `-2.83324e+179` nor `-0.499999` appears in my debug. (with kspacing=0.13 or `12 12 7` in KPT file)

OK. My setting of `KPT` is:
```
K_POINTS
0
Gamma
13 13 13 0 0 0
```

If I set kspacing 0.13, the bug disappears.

**Comment by hongriTianqi** [comment]
@maki49 I have found the problem, the KPT file is set as:
```
K_POINTS
0
Gamma
13 13 13
```
This is an wrong `KPT` file. Thanks for your help along the way.
