### ISSUE TITLE
Error when using bohrium B series GPU.

### ISSUE THREAD

**Issue by grysgreat** [deepmodeling/abacus-develop#4062]
### Describe the bug

Compiling abacus using B series Gpus on bohrium will not work properly.

### Expected behavior

![u1Gc7fhOZ4](https://github.com/deepmodeling/abacus-develop/assets/57103981/43363d52-fa55-4fc3-a1ca-39d7a58f42b7)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by caic99** [comment]
Hi @grysgreat ,
What is the exact name of "GPU B"?

**Comment by grysgreat** [comment]
Well. I also don't know the actual name, it just name `NVIDIA GPU B`.

**Comment by caic99** [comment]
> Well. I also don't know the actual name, it just name `NVIDIA GPU B`.

You can check it using `nvidia-smi`

**Comment by grysgreat** [comment]
Oh, i forgot that! it is `NVIDIA GeForce RTX 2080 Ti`
![image](https://github.com/deepmodeling/abacus-develop/assets/57103981/c9b593b5-3b2e-407f-9ce3-7b864443f56e)

**Comment by WHUweiqingzhou** [comment]
@grysgreat have this issue solved already?

**Comment by grysgreat** [comment]
I didn't check it again after using it, perhaps not, because the GPU model is too old and should not be available.

**Comment by caic99** [comment]
@denghuilu The cuda error check does not apply here.
https://github.com/deepmodeling/abacus-develop/blob/a2a6165fca50a1ae0daa8611321576f4d04a7d96/source/module_psi/kernels/device.cpp#L562
Maybe using `print_device_info` would be better.

**Comment by caic99** [comment]
> ### Describe the bug
> Compiling abacus using B series Gpus on bohrium will not work properly.

@grysgreat The error message is: forward compatibility was attempted on non supported HW
Plus, you can attach output as text but not screenshot for better readability.

**Comment by caic99** [comment]
@grysgreat [This post](https://zhuanlan.zhihu.com/p/361545761) explains this issue well. The GPU you are using is not of nvidia datacenter GPU, but a consumer grade one. Hence, the CUDA forward compatibility is disabled.

ABACUS is able to run after executing the following commands:
`ln -sf /usr/lib/x86_64-linux-gnu/libcuda.so.525* /usr/lib/x86_64-linux-gnu/libcuda.so.1`

However, I would suggest using another GPU to avoid any potential problems.

**Comment by denghuilu** [comment]
> @denghuilu The cuda error check does not apply here.
> 
> https://github.com/deepmodeling/abacus-develop/blob/a2a6165fca50a1ae0daa8611321576f4d04a7d96/source/module_psi/kernels/device.cpp#L562
> 
> 
> Maybe using `print_device_info` would be better.

Add the device error checks for this part of codes, check the #4106

**Comment by grysgreat** [comment]
Thanks, this will help us in using different GPU.
