### ISSUE TITLE
No warning given if KPT is ill set

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#4070]
### Describe the bug

When KPT is set as:
```
K_POINTS 
0            
Gamma 
1 1 1
```
no warning is given

### Expected behavior

give warning

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
A correct type should be:
```
K_POINTS 
0            
Gamma 
1 1 1   0 0 0
```

**Comment by WHUweiqingzhou** [comment]
This function related with this issue:
`K_Vectors::read_kpoints(const std::string &fn)` in module_cell/klist.cpp

**Comment by WHUweiqingzhou** [comment]
#4056
