### ISSUE TITLE
CMake encounters a `Maximum recursion depth of 1000 exceeded` error when compiling with Clang and the ROCm environment.

### ISSUE THREAD

**Issue by denghuilu** [deepmodeling/abacus-develop#4074]
### Describe the bug

cmake -DCMAKE_CXX_COMPILER=clang++ -DUSE_ROCM=ON -DENABLE_DEEPKS=OFF -DENABLE_LIBXC=ON -DBUILD_TESTING=ON -DCOMMIT_INFO=OFF -DCMAKE_BUILD_TYPE=Release .. 
-- The CXX compiler identification is Clang 15.0.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rocm-5.3.0/llvm/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Cereal: /usr/include  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Found ELPA: /usr/lib/x86_64-linux-gnu/libelpa.so  
-- Performing Test ELPA_VERSION_SATISFIES
-- Performing Test ELPA_VERSION_SATISFIES - Success
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found OpenMP_CXX: -fopenmp=libomp (found version "5.0") 
-- Found OpenMP: TRUE (found version "5.0")  
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - NOTFOUND
-- Found HIP: /opt/rocm-5.3.0/hip (found version "5.3.22061-e8e78f1a") 
-- Performing Test HIP_CLANG_SUPPORTS_PARALLEL_JOBS
-- Performing Test HIP_CLANG_SUPPORTS_PARALLEL_JOBS - Success
-- hip::amdhip64 is SHARED_LIBRARY
-- hip::amdhip64 is SHARED_LIBRARY
-- hip::amdhip64 is SHARED_LIBRARY
-- Found HIP: 5.3.22061-e8e78f1a
-- Found FFTW3: /usr/lib/x86_64-linux-gnu/libfftw3_omp.so  
CMake Error at cmake/FindBLAS.cmake:1 (if):
  Maximum recursion depth of 1000 exceeded
Call Stack (most recent call first):
 cmake/FindBlas.cmake:8 (find_package)
  ...
  ...
  cmake/FindBlas.cmake:8 (find_package)
  cmake/FindLapack.cmake:9 (find_package)
  CMakeLists.txt:409 (find_package)

-- Configuring incomplete, errors occurred!
See also "/workspaces/abacus-develop/build/CMakeFiles/CMakeOutput.log".
See also "/workspaces/abacus-develop/build/CMakeFiles/CMakeError.log".

### Task list for Issue attackers (only for developers)

- [X] Verify the issue is not a duplicate.
- [X] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by caic99** [comment]
Duplicate: #3958

**Comment by denghuilu** [comment]
Fix by the method mentioned by #3958, still do not understand why this error occurred.
