### ISSUE TITLE
abacus-plot

### ISSUE THREAD

**Issue by Timtansiyu** [deepmodeling/abacus-develop#4075]
### Details

When using abacus-plot to draw band plots, adding "shift" to evaluate the band gap found that the resulting plots were different from those without.
![band](https://github.com/deepmodeling/abacus-develop/assets/164017480/ab24c32b-bdb1-49c6-8775-5956ff5b6905)
![band (1)](https://github.com/deepmodeling/abacus-develop/assets/164017480/9b7e63ee-0d59-4537-8b8e-d7981496eaa0)
[OUT.EEGNRE.zip](https://github.com/deepmodeling/abacus-develop/files/15159432/OUT.EEGNRE.zip)

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by 1041176461** [comment]
Did you provide the correct input and output files? I cannot reproduce your band structure. My results (with `shfit=False`) do not observe spin splitting.
![band-unshift](https://github.com/deepmodeling/abacus-develop/assets/40336950/2125c245-cb88-4f92-b623-9fca0ac9f944)

**Comment by Timtansiyu** [comment]
[scf.zip](https://github.com/deepmodeling/abacus-develop/files/15215917/scf.zip)
[band.zip](https://github.com/deepmodeling/abacus-develop/files/15215920/band.zip)
[config.json](https://github.com/deepmodeling/abacus-develop/files/15215942/config.json)
I re-uploaded the input files for scf, band and json.

**Comment by 1041176461** [comment]
Could you please provide your correct BANDS_1.dat and BANDS_2.dat (which are used to plot band structures), KPT (with high symmetry path) and config.json? I don’t have many resources to run this large system example now, and the drawing script has nothing to do with Abacus itself. I only need band data, high symmetry paths and Fermi energy.

**Comment by Timtansiyu** [comment]
[OUT.EEGNRE.zip](https://github.com/deepmodeling/abacus-develop/files/15229049/OUT.EEGNRE.zip)

**Comment by WHUweiqingzhou** [comment]
@1041176461 has this issue been solved already?

**Comment by Timtansiyu** [comment]
Not yet solved

**Comment by 1041176461** [comment]
I fixed this bug in PR https://github.com/deepmodeling/abacus-develop/pull/4116, and the results (with `shift=True`) are present as below:

![image](https://github.com/deepmodeling/abacus-develop/assets/40336950/8e2abe10-1c6d-4883-8607-92c99837a3c5)

![image](https://github.com/deepmodeling/abacus-develop/assets/40336950/efd57e66-4c04-4784-83b0-19456fc6a7f5)
