### ISSUE TITLE
Convergence Problem

### ISSUE THREAD

**Issue by iduygnay** [deepmodeling/abacus-develop#4078]
### Details

This calculation is really important for me, I tried different ways but still could not converge. Can anyone help me to check my INPUT?
[dft.zip](https://github.com/deepmodeling/abacus-develop/files/15160531/dft.zip)

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by WHUweiqingzhou** [comment]
@iduygnay 
have you tried this [notebook](https://ucoyxk075n.feishu.cn/docx/R0sqdk6T0o2RY4x5IWgcJ3RHnug)?

**Comment by iduygnay** [comment]
I tried to adjust mix_gg0 to 1.5, mix_beta to 0.6 and some other values, degauss to 0.01 and 0.02, smearing method to fixed, but all of them always converge to 1E-3 and can not be smaller.

**Comment by WHUweiqingzhou** [comment]
I notice it is a SOC calculation, I will suggest a quite small `mixing_beta` , like 0.2 or 0.1

**Comment by iduygnay** [comment]
![image](https://github.com/deepmodeling/abacus-develop/assets/109792836/7901591f-a728-4875-9fc6-0538abfae9b7)
It still could not converge.

**Comment by dyzheng** [comment]
I suggest to set "noncolin false" when there is no initial atomic-mag is setting, it usually can improve convergence.

**Comment by iduygnay** [comment]
I set noncolin as default (which is false), still not converge. 
![image](https://github.com/deepmodeling/abacus-develop/assets/109792836/1092dd88-48d6-406a-8b86-51190667b50f)

**Comment by iduygnay** [comment]
I've used QE and solved this, QE can converge quite quickly. But it requires a large memory. 
![image](https://github.com/deepmodeling/abacus-develop/assets/109792836/58b11c28-e0e2-49f1-8582-8268342997e7)

**Comment by iduygnay** [comment]
I tried symmetry = -1, mixing_beta = 0.01, soc lambda = 0.1, still not converge.

**Comment by iduygnay** [comment]
Even 32 atoms cannot converge.
<img width="1173" alt="image" src="https://github.com/user-attachments/assets/67f24990-7903-4240-8d7e-6d15ca557d3c">

**Comment by iduygnay** [comment]
Interesting! I found that abacus3.4.3 can converge, for the 32 atoms case with the same INPUT. 
![image](https://github.com/user-attachments/assets/ec97abbe-cc7d-4542-a144-ea83cf413559)

**Comment by iduygnay** [comment]
240 atoms case can also converge successfully! 
I think my problem is solved, if there is no necessary to keep this issue I can close it. 

![image](https://github.com/user-attachments/assets/c2b81552-d426-4335-a268-c8f4b4f467e4)

**Comment by WHUweiqingzhou** [comment]
@iduygnay  Could you offer your input&output of 32 atoms. I believe this is caused by some numerical problem, and I will try to figure it out.

**Comment by iduygnay** [comment]
I hope to send it via WeChat since the file is too big.

**Comment by mohanchen** [comment]
Will reopen this issue if new connection between the user and the developer can be established in future.
