### ISSUE TITLE
SCF is hard to converge for La series elements

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#4080]
### Details

The SCF of some La elements are hard to converge. 

Such as Ce, 
[Ce-input.zip](https://github.com/deepmodeling/abacus-develop/files/15160848/Ce-input.zip)
[Ce-out.zip](https://github.com/deepmodeling/abacus-develop/files/15160850/Ce-out.zip)

Gd:
[Gd.zip](https://github.com/deepmodeling/abacus-develop/files/15160871/Gd.zip)
[Gd-input.zip](https://github.com/deepmodeling/abacus-develop/files/15160873/Gd-input.zip)

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by WHUweiqingzhou** [comment]
I turn on `symmetry 1`, SCF converges in 27 steps:

```
ELEMENT NATOM       XC          
 Ce      1           
 ---------------------------------------------------------
 Initial plane wave basis and FFT box
 ---------------------------------------------------------
 DONE(0.286024   SEC) : INIT PLANEWAVE
 MEMORY FOR PSI (MB)  : 3.50464
 DONE(0.293817   SEC) : LOCAL POTENTIAL
 DONE(0.40577    SEC) : NON-LOCAL POTENTIAL
 DONE(0.488428   SEC) : INIT BASIS
 -------------------------------------------
 STEP OF RELAXATION : 1
 -------------------------------------------
 START CHARGE      : atomic
 DONE(0.508981   SEC) : INIT SCF
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
 DA1    -1.049091e+03  0.000000e+00   3.198e-01  3.962e+00  
 DA2    -1.048113e+03  9.785316e-01   1.123e+00  3.027e+00  
 DA3    -1.050788e+03  -2.674918e+00  4.137e-02  2.132e+00  
 DA4    -1.051090e+03  -3.023925e-01  1.514e-03  2.828e+00  
 DA5    -1.051167e+03  -7.712577e-02  1.567e-02  2.541e+00  
 DA6    -1.051173e+03  -6.036214e-03  4.817e-02  2.128e+00  
 DA7    -1.050864e+03  3.093945e-01   6.695e-02  2.590e+00  
 DA8    -1.050888e+03  -2.441884e-02  5.125e-04  2.780e+00  
 DA9    -1.050927e+03  -3.919162e-02  1.574e-03  3.261e+00  
 DA10   -1.050980e+03  -5.239460e-02  1.516e-03  2.183e+00  
 DA11   -1.051013e+03  -3.310910e-02  1.093e-03  2.524e+00  
 DA12   -1.050503e+03  5.094215e-01   6.582e-04  2.175e+00  
 DA13   -1.051185e+03  -6.815449e-01  4.273e-04  3.931e+00  
 DA14   -1.051178e+03  7.183921e-03   4.181e-04  2.100e+00  
 DA15   -1.050955e+03  2.223625e-01   5.987e-04  2.202e+00  
 DA16   -1.051132e+03  -1.765134e-01  2.170e-03  3.795e+00  
 DA17   -1.051135e+03  -3.514990e-03  2.362e-04  2.188e+00  
 DA18   -1.051130e+03  5.825220e-03   4.485e-03  3.434e+00  
 DA19   -1.051145e+03  -1.535264e-02  2.748e-03  3.813e+00  
 DA20   -1.051183e+03  -3.806282e-02  2.389e-03  3.827e+00  
 DA21   -1.051188e+03  -5.194344e-03  1.496e-04  3.092e+00  
 DA22   -1.051193e+03  -4.751127e-03  7.030e-06  3.078e+00  
 DA23   -1.051193e+03  -2.085852e-04  7.011e-06  3.082e+00  
 DA24   -1.051193e+03  -1.081092e-04  4.356e-07  3.077e+00  
 DA25   -1.051193e+03  4.396743e-06   2.659e-07  2.011e+00  
 DA26   -1.051193e+03  -8.528502e-06  5.772e-08  3.286e+00  
 DA27   -1.051193e+03  -9.261893e-07  1.150e-10  3.076e+00  
```

Maybe too many k-points results in error?

**Comment by WHUweiqingzhou** [comment]
this converge issue is induced by #3937, merge discussions there.
