### ISSUE TITLE
Timing of the output of H and S matrices

### ISSUE THREAD

**Issue by LiuXiaohui123321** [deepmodeling/abacus-develop#4093]
The output of the H and S matrices in the current program is at this location, and are only output when the charge density converges.
https://github.com/deepmodeling/abacus-develop/blob/48f2b5d59b0dac8882e1bba9946f9d9c308eccbe/source/module_esolver/esolver_ks_lcao.cpp#L822

If the `out_mat_hs` option is used in INPUT file, I think it's better to also output the matrices when the  self-consistent iteration steps  reach `scf_nmax`, even if the charge density doesn't converge.

**Comment by mohanchen** [comment]
Great idea! Could you implement this function? @LiuXiaohui123321

**Comment by LiuXiaohui123321** [comment]
> Great idea! Could you implement this function? @LiuXiaohui123321

OK!
