### ISSUE TITLE
integration test times out

### ISSUE THREAD

**Issue by caic99** [deepmodeling/abacus-develop#4094]
### Describe the bug

The integration test case 904_OF_CO_Potential hangs randomly on CI runs.
https://github.com/deepmodeling/abacus-develop/actions/runs/8951456283/job/24588746454#step:6:2610

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
Maybe we should increase the time limit of CI test?

**Comment by caic99** [comment]
> Maybe we should increase the time limit of CI test?

Ahh you are right, the test now takes [nearly 1600s](https://github.com/deepmodeling/abacus-develop/actions/runs/8963611354/job/24614126928#step:6:2751). The test case itself is correct.
