### ISSUE TITLE
Feature: ABACUS highlighting plugin in VSCode

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#4096]
### Background

In VSCode, there are plugins for highlighting the input (and output) files (and even give hints for input parameters like docs) for VASP, QE, CP2K and LAMMPS. I consider that a highlighting plugin for ABACUS is also needed.

### Describe the solution you'd like

A plugin in VSCode for ABACUS input and output files.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by WHUweiqingzhou** [comment]
@QuantumMisaka do you know how make it?

**Comment by QuantumMisaka** [comment]
Example for VASP plugin:
https://marketplace.visualstudio.com/items?itemName=Mystery.vasp-support
Example for QE plugin:
https://marketplace.visualstudio.com/items?itemName=ritwikdas.QuantumEspresso-VSCode
