### ISSUE TITLE
Bug: possible incorrect calculations (Useful to know how to read charge density from QE and set tight convergence in Davidson)

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#4104]
### Describe the bug

During DeePMD training, some examples show large error, indicating a bad DFT result. Could you double-check them?

[bad.zip](https://github.com/deepmodeling/abacus-develop/files/15219050/bad.zip)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by pxlxingliang** [comment]
I have tested these four examples by ABACUS (on CPU) and QE, and three of them are consistent between ABACUS and QE, and H14C1Te1 has a large difference between QE and ABACUS

![image](https://github.com/deepmodeling/abacus-develop/assets/91927439/c20ca85e-c3c6-4a81-8802-a4324a4aee0c)
 
[out (2).zip](https://github.com/deepmodeling/abacus-develop/files/15219292/out.2.zip)

**Comment by pxlxingliang** [comment]
For H14C1Te1, I try to run abacus with `init_chg file`, and read the charge from QE. This time, the results of abacus is consistent with QE.

![image](https://github.com/deepmodeling/abacus-develop/assets/91927439/cca71bc4-b4ff-48b1-b617-6d35eb872ba7)

**Comment by pxlxingliang** [comment]
We should notice that the energy of ABACUS (init_chg auto) is lower than that in QE
The energy of each SCF step in QE:
```
     total energy              =    -200.65595416 Ry
     total energy              =    -200.76362261 Ry
     total energy              =    -201.08104210 Ry
     total energy              =    -201.15144736 Ry
     total energy              =    -201.24873656 Ry
     total energy              =    -201.19892646 Ry
     total energy              =    -201.04515447 Ry
     total energy              =    -201.15749253 Ry
     total energy              =    -201.15719289 Ry
     total energy              =    -201.15614679 Ry
     total energy              =    -201.15627812 Ry
     total energy              =    -201.15639045 Ry
     total energy              =    -201.15641146 Ry
     total energy              =    -201.15642419 Ry
     total energy              =    -201.15641953 Ry
     total energy              =    -201.15642294 Ry
     total energy              =    -201.15642223 Ry
     total energy              =    -201.15641058 Ry
     total energy              =    -201.15640660 Ry
     total energy              =    -201.15640716 Ry
     total energy              =    -201.15640168 Ry
     total energy              =    -201.15640327 Ry
     total energy              =    -201.15640277 Ry
     total energy              =    -201.15640281 Ry
     total energy              =    -201.15640280 Ry
     total energy              =    -201.15640282 Ry
!    total energy              =    -201.15640283 Ry
```

The energy of each SCF step in ABACUS:
```
E_KohnSham      -200.6377199130     -2729.8162245455
E_KohnSham      -200.8315411184     -2732.4532973322
E_KohnSham      -201.0309680476     -2735.1666399034
E_KohnSham      -200.8600562863     -2732.8412660940
E_KohnSham      -201.1894033523     -2737.3222628115
E_KohnSham      -201.1658521890     -2737.0018327960
E_KohnSham      -201.1683806091     -2737.0362337167
E_KohnSham      -201.1702671779     -2737.0619018018
E_KohnSham      -201.1721679317     -2737.0877628844
E_KohnSham      -201.1721953331     -2737.0881356988
E_KohnSham      -201.1721942980     -2737.0881216164
E_KohnSham      -201.1721898876     -2737.0880616089
E_KohnSham      -201.1721922807     -2737.0880941692
E_KohnSham      -201.1721918110     -2737.0880877783
E_KohnSham      -201.1721921246     -2737.0880920458
E_KohnSham          -201.1721921247     -2737.0880920468
```

**Comment by pxlxingliang** [comment]
I try to set "diago_full_acc = True" in QE calculation, and this time the results are consistence between QE and ABACUS:

![img_v3_02al_fe857264-17e2-4f9a-b89d-fbc8365ee65g](https://github.com/deepmodeling/abacus-develop/assets/91927439/56d030f1-377c-429b-b091-55faf92ce04b)

This parameter is to control if use the same accuracy for empty states in dav diagonalization, the default is false.
https://www.quantum-espresso.org/Doc/INPUT_PW.html#idm878

While in abacus dav, the accuracy is same for all bands.
