### ISSUE TITLE
Question: the second parameter for `out_mat_hs` and the use of `out_ndigits`

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#4108]
### Details

https://github.com/deepmodeling/abacus-develop/blob/develop/tests/integrate/207_NO_KP_OH/INPUT#L28

https://github.com/deepmodeling/abacus-develop/blob/develop/tests/integrate/207_NO_KP_OH/INPUT#L30

```
out_mat_hs  1 5
ks_solver       scalapack_gvx
out_ndigits 5
```

1. I want to know if the second parameter of `out_mat_hs` is different with `out_ndigits`, what will happen?

2. Why only `out_band` and `out_mat_hs` have the second parameters, how about other output variables?

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by kirk0830** [comment]
In the past the `out_ndigits` controls precision of output in a wider range, while `out_mat_hs` only controls precision of output of itself.
I think all the output flags can be re-designed, after re-design of input.
