### ISSUE TITLE
Ultrasoft pseudopotential from GBRV not available

### ISSUE THREAD

**Issue by FurinaWai77** [deepmodeling/abacus-develop#4113]
### Describe the bug

When ABACUS runs cell-relax with an ultrasoft pseudopotential (USPP) from GBRV, it stops and yields "Ultra Soft Pseudopotential not available yet." I'm not sure it's because ABACUS doesn't support USPP, or there's problem in that PP file. ABACUS could complete the calculation using NCPP.

### Expected behavior

ABACUS should complete the cell-relax calculation

### To Reproduce

Simply run any ABACUS program but use USPP from GBRV. I used the element Rh. Here's the USPP file and my inputs:

[rh_pbe_v1.4.uspp.F.zip](https://github.com/deepmodeling/abacus-develop/files/15233793/rh_pbe_v1.4.uspp.F.zip)

### Environment

OS: WSL2 Ubuntu 22.04
Compiler: gcc 11.4.0
ABACUS: v3.6.2

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@YuLiu98 could you have a look?

**Comment by YuLiu98** [comment]
Hello @FurinaWai77, uspp in the GBRV (upf100) format is currently not supported in ABACUS. You can use upf201 format instead. 

We will gradually support uspp in other formats in the future.
