### ISSUE TITLE
Error: "nbands < ncpus"

### ISSUE THREAD

**Issue by smclucky** [deepmodeling/abacus-develop#4125]
### Describe the bug

I have carried out a "cell-relax" calculation for a system containing 2 Li atoms using the LCAO basis set. This calculation was performed using 32 cores. However, an error occurred stating "nbands < ncpus\". Despite this issue, it was not observed in CP2K, and the relevant examples are attached for reference.
[issue-bug.zip](https://github.com/deepmodeling/abacus-develop/files/15249253/issue-bug.zip)

Thank you.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by mohanchen** [comment]
Thanks, it is caused by the fact that the basis number is too small to run on so many cores. We may able to fix it after we reform the MPI communicator, it will take a while
