### ISSUE TITLE
SOC: not converged in some cases

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#4139]
### Describe the bug

In the following test: a noncolin without soc case and a noncoli with soc case were tested. The one without soc converged quickly in 19 steps, another one with soc cannot get converged in 200 steps.

This test is for BiFeO3 (nonsoc 19 steps converged, soc 200 steps unconverged)

https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.113-c78d97

The same happened in FeRh (nonsoc 18 steps converged, soc 200 steps unconverged)

https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.113-a6299e

The same happened in Ni2MnTi (nonsoc 18 steps converged, soc 200 steps unconverged)

https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.113-138236

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by hongriTianqi** [comment]
@dyzheng @WHUweiqingzhou `mixing_angle` has been tried in the following test:
[085c45](https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.113-085c45)

The scf calculations still failed to converge.

**Comment by WHUweiqingzhou** [comment]
I think we should keep this in mind since non-conlinear calculations will be very important in very near future.
