### ISSUE TITLE
Documents about how to use ABACUS to run rt-TDDFT simulations (Useful Information for rt-TDDFT)

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#4144]
### Details

TDDFT method is implemented in ABACUS since X version, I want to get documentation or notebook to learn how to use it.

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by AsTonyshment** [comment]
The latest tutorial has already been released, see https://mcresearch.github.io/abacus-user-guide/abacus-tddft.html. This issue will be closed.

**Comment by mohanchen** [comment]
https://mcresearch.github.io/abacus-user-guide/abacus-tddft.html
