### ISSUE TITLE
Can ABACUS work with VASP-kit or ATOM-kit, I want a documentation to learn how to use

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#4145]
### Details

Such as generating INPUT files, or analyzing the ABACUS output by VASP-kit.

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by QuantumMisaka** [comment]
ATOMKIT is more like Materials Studio or OpenBabel which does the structure construction work like format transformation and structure manipulation. 

VASPKIT is a full toolkit for VASP input and output, and the developers are having some support for ABACUS

I consider that we should have more communication and cooperation with VASPKIT developers

**Comment by WHUweiqingzhou** [comment]
see the link https://mcresearch.github.io/abacus-user-guide/abacus-dos.html
