### ISSUE TITLE
Hard to reach convergence of some magnetic elements & abnormal slow of ABACUS `scf` calculations

### ISSUE THREAD

**Issue by ZLI-afk** [deepmodeling/abacus-develop#4149]
### Details

Please see below attached cases as described by the title:

- Hard to converge within consideration long period (most are magnetic):
[Ni-hcp_uncov.zip](https://github.com/deepmodeling/abacus-develop/files/15274369/Ni-hcp_uncov.zip)
[Mn-bcc_uncov.zip](https://github.com/deepmodeling/abacus-develop/files/15274371/Mn-bcc_uncov.zip)
[Fe-fcc_uncov.zip](https://github.com/deepmodeling/abacus-develop/files/15274375/Fe-fcc_uncov.zip)
[Cr-bcc_uncov.zip](https://github.com/deepmodeling/abacus-develop/files/15274381/Cr-bcc_uncov.zip)
[Co-bcc_uncov.zip](https://github.com/deepmodeling/abacus-develop/files/15274382/Co-bcc_uncov.zip)
[Ce-bcc-uncov.zip](https://github.com/deepmodeling/abacus-develop/files/15274384/Ce-bcc-uncov.zip)

- Reach convergence but takes hours (very slow for single electronic step):
[Sm-rho_very_slow.zip](https://github.com/deepmodeling/abacus-develop/files/15274394/Sm-rho_very_slow.zip)
[V-fcc_very_slow.zip](https://github.com/deepmodeling/abacus-develop/files/15274395/V-fcc_very_slow.zip)

`INPUT`:
```
INPUT_PARAMETERS
calculation scf
basis_type pw
symmetry 0
ecutwfc 100
scf_thr 1e-08
scf_nmax 200
cal_force 1
cal_stress 1
kspacing 0.08
pseudo_rcut 10
pseudo_mesh 1
ks_solver dav
relax_nmax 100
force_thr 0.001
stress_thr 0.5
smearing_method gaussian
smearing_sigma 0.01
```

`machine_type`: 
**c64_m128_cpu_H**

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by WHUweiqingzhou** [comment]
@ZLI-afk,

According to [ABACUS收敛性问题解决手册](https://ucoyxk075n.feishu.cn/docx/R0sqdk6T0o2RY4x5IWgcJ3RHnug). I try to reduce `mixing_beta` from 0.8 to 0.4/0.2, and increase `mixing_ndim` from 8 to 15. You can check the results in [link](https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-metal-abacustest-v0.3.113-202bb5).
Actually, I try 4 combinations, namely:
1. `mixing_beta=0.4` and `mixing_ndim=8`
2. `mixing_beta=0.4` and `mixing_ndim=15`
3. `mixing_beta=0.2` and `mixing_ndim=8`
4. `mixing_beta=0.2` and `mixing_ndim=15`

For Ni-hcp, converges in all 4 combinations:
![image](https://github.com/deepmodeling/abacus-develop/assets/33364058/91cf50b3-7700-485a-9f86-4817dc557f13)

For Mn-bcc, converges in all 4 combinations:
![image](https://github.com/deepmodeling/abacus-develop/assets/33364058/a32f340c-b352-4d96-a470-0f8b194c176e)

For Fe-fcc, converges in 3 combinations, only fails to converge for `mixing_beta=0.4` and `mixing_ndim=8`:
![image](https://github.com/deepmodeling/abacus-develop/assets/33364058/ec466920-46a1-4840-8d69-95c48eb22be8)

For Cr-bcc, converges in all 4 combinations:
![image](https://github.com/deepmodeling/abacus-develop/assets/33364058/12ac3d53-6350-40c7-8701-e6b9d207b4d4)

For Co-bcc, converges in all 4 combinations:
![image](https://github.com/deepmodeling/abacus-develop/assets/33364058/83ac7dac-8d03-4325-ade3-dc432fe6f9b0)

 For Ce-bcc, converges for `mixing_beta=0.2` and `mixing_ndim=8`
![image](https://github.com/deepmodeling/abacus-develop/assets/33364058/e08fa968-80fa-468f-a076-08c28198f799)

Actually, Ce-bcc is not hard converge. Instead, it is very easy to converge, you can see the drho:
![image](https://github.com/deepmodeling/abacus-develop/assets/33364058/adc63c7e-f6ca-4a08-91d1-30b69c905cdd)
You can notice the drho decrease very fast to `1e-7`, while fails to converge to `1e-8`. These results indicate the Ce calculations is unstable numerically. This numerical instability might be caused by the pseudopotential. Furthermore, this instability also can lead to some numerical errors in the iterative solution methods (like Davidson method), but this is not a bug, rather it is a feature of this numerical solution technique. You can see more discussion in Issue #4068.

**Comment by pxlxingliang** [comment]
I have checked some examples calculated previous (ecutwfc is also 100 Ry).

example| natom| nbands| nelec| kpoints| bohrium_machine (parallel core)| cpu| ave scf_time
---|---|---|---|---|---|---|---
041_ZnMnGa| 49|290|481|63| c32_m128_cpu(32)|Intel(R) Xeon(R) Platinum 9242 CPU @ 2.30GHz| 305
043_RuSc|30|223|370|112| c32_m128_cpu(32)|Intel(R) Xeon(R) Platinum 9242 CPU @ 2.30GHz| 530
055_ErAlNi|24|217|360|152| c32_m128_cpu(32)|Intel(R) Xeon(R) Platinum 9242 CPU @ 2.30GHz| 278
V(this issue)|32|250|416|112|c64_m128_cpu_H(64)|AMD EPYC 7452 32-Core Processor|605
Sm(this issue)|24|159|264|172|c64_m128_cpu_H(64)|AMD EPYC 7452 32-Core Processor|1568

**Comment by ZLI-afk** [comment]
Is average `scf_time` too high for V and Sm? Is any way to solve this?

**Comment by ZLI-afk** [comment]
> I have check one example I calculated previous, and the ecutwfc is also 100 Ry.
> 
> example	natom	nbands	nelec	kpoints	bohrium_machine (parallel core)	cpu	ave scf_time
> 041_ZnMnGa	49	290	481	63	c32_m128_cpu(32)	Intel(R) Xeon(R) Platinum 9242 CPU @ 2.30GHz	305
> 043_RuSc	30	223	370	112	c32_m128_cpu(32)	Intel(R) Xeon(R) Platinum 9242 CPU @ 2.30GHz	530
> 055_ErAlNi	24	217	360	152	c32_m128_cpu(32)	Intel(R) Xeon(R) Platinum 9242 CPU @ 2.30GHz	278
> V(this issue)	32	250	416	112	c64_m128_cpu_H(64)	AMD EPYC 7452 32-Core Processor	605
> Sm(this issue)	24	159	264	172	c64_m128_cpu_H(64)	AMD EPYC 7452 32-Core Processor	1568

Is average `scf_time` too high for V and Sm? Is any way to solve this?

**Comment by ZLI-afk** [comment]
> @ZLI-afk,
> 
> According to [ABACUS收敛性问题解决手册](https://ucoyxk075n.feishu.cn/docx/R0sqdk6T0o2RY4x5IWgcJ3RHnug). I try to reduce `mixing_beta` from 0.8 to 0.4/0.2, and increase `mixing_ndim` from 8 to 15. You can check the results in [link](https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-metal-abacustest-v0.3.113-202bb5). Actually, I try 4 combinations, namely:
> 
> 1. `mixing_beta=0.4` and `mixing_ndim=8`
> 2. `mixing_beta=0.4` and `mixing_ndim=15`
> 3. `mixing_beta=0.2` and `mixing_ndim=8`
> 4. `mixing_beta=0.2` and `mixing_ndim=15`
> 
> For Ni-hcp, converges in all 4 combinations: ![image](https://private-user-images.githubusercontent.com/33364058/329748193-91cf50b3-7700-485a-9f86-4817dc557f13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTcwMzksIm5iZiI6MTcxNTM5NjczOSwicGF0aCI6Ii8zMzM2NDA1OC8zMjk3NDgxOTMtOTFjZjUwYjMtNzcwMC00ODVhLTlmODYtNDgxN2RjNTU3ZjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDAzMDUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ODJiOTZmNDA4ODY1ZTQ2NWMwODZhNDdiMTljZGE0NGExZjNiYjU5NTFjMzBjMWRiNjJlN2UxZjk5ZDlkYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z28ngqPzDIfKnelaftuT6P0aUxg-Py_B_kiXCXFpso4)
> 
> For Mn-bcc, converges in all 4 combinations: ![image](https://private-user-images.githubusercontent.com/33364058/329748237-a32f340c-b352-4d96-a470-0f8b194c176e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTcwMzksIm5iZiI6MTcxNTM5NjczOSwicGF0aCI6Ii8zMzM2NDA1OC8zMjk3NDgyMzctYTMyZjM0MGMtYjM1Mi00ZDk2LWE0NzAtMGY4YjE5NGMxNzZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDAzMDUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5MTRiODdjMWYxZjNiMjc1NTRhNDM0NTAxZmEwZDYyNmYwYTg0MTY1ZWE0YzQwNzI0Nzc4NzE1ODQ3OWUxNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kVTmbuE9DeQozpMLC1kzwPTZSd05IOV29C4s3zvwXTU)
> 
> For Fe-fcc, converges in 3 combinations, only fails to converge for `mixing_beta=0.4` and `mixing_ndim=8`: ![image](https://private-user-images.githubusercontent.com/33364058/329748263-ec466920-46a1-4840-8d69-95c48eb22be8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTcwMzksIm5iZiI6MTcxNTM5NjczOSwicGF0aCI6Ii8zMzM2NDA1OC8zMjk3NDgyNjMtZWM0NjY5MjAtNDZhMS00ODQwLThkNjktOTVjNDhlYjIyYmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDAzMDUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzNTNlZjMxMmExZTNjNzA2MGQ3NmE1MWRiMzY2YWZiN2EzNDcyMWNmM2M4MzM4NzFhZGUwNzlkOWY3OTRjNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8yXxWlJYuQukj0RKlL6U2v068cAf6hyTDjyUpkjZs3A)
> 
> For Cr-bcc, converges in all 4 combinations: ![image](https://private-user-images.githubusercontent.com/33364058/329748369-12ac3d53-6350-40c7-8701-e6b9d207b4d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTcwMzksIm5iZiI6MTcxNTM5NjczOSwicGF0aCI6Ii8zMzM2NDA1OC8zMjk3NDgzNjktMTJhYzNkNTMtNjM1MC00MGM3LTg3MDEtZTZiOWQyMDdiNGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDAzMDUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNzMwZTM2ZjZhZGFhYzE5YmU5ODdmYTgzYzhjY2ZhYmUyMGQzYzQ2ZTM5ODA3YTIwMDY4NWM0MDA3ODU2YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d78NIaM-o6Sx6JBhaSay1ChowJq3G0ucj6xIXDpobxM)
> 
> For Co-bcc, converges in all 4 combinations: ![image](https://private-user-images.githubusercontent.com/33364058/329748413-83ac7dac-8d03-4325-ade3-dc432fe6f9b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTcwMzksIm5iZiI6MTcxNTM5NjczOSwicGF0aCI6Ii8zMzM2NDA1OC8zMjk3NDg0MTMtODNhYzdkYWMtOGQwMy00MzI1LWFkZTMtZGM0MzJmZTZmOWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDAzMDUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMTYxNWM1MGE0MWQ1MmE1Yzk3ZjI2MDE3NDk3YjMwMWI0OTk4NzEzN2JhZjY0NmY0M2ZjOGI0MTgyYTQ1ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ssAXK9Y7aJZ7-JuNRqOrGo_2R5xk0S3Of4Z4lV8TJEM)
> 
> For Ce-bcc, converges for `mixing_beta=0.2` and `mixing_ndim=8` ![image](https://private-user-images.githubusercontent.com/33364058/329748445-e08fa968-80fa-468f-a076-08c28198f799.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTcwMzksIm5iZiI6MTcxNTM5NjczOSwicGF0aCI6Ii8zMzM2NDA1OC8zMjk3NDg0NDUtZTA4ZmE5NjgtODBmYS00NjhmLWEwNzYtMDhjMjgxOThmNzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDAzMDUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZWFlNTFhNjZmZWE4ZGZlMmJiYjJlMjQ3YTM3MDJjYmZlNTM2MDliMGFlZDVlYjU1YzgwZTdmODliOGVlYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l0lU5alZlT--0dxMl7FWiIZoSiZ_1f4OT4WGLrh6q3A)
> 
> Actually, Ce-bcc is not hard converge. Instead, it is very easy to converge, you can see the drho: ![image](https://private-user-images.githubusercontent.com/33364058/329748574-adc63c7e-f6ca-4a08-91d1-30b69c905cdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTcwMzksIm5iZiI6MTcxNTM5NjczOSwicGF0aCI6Ii8zMzM2NDA1OC8zMjk3NDg1NzQtYWRjNjNjN2UtZjZjYS00YTA4LTkxZDEtMzBiNjljOTA1Y2RkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDAzMDUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiYWZmNzk3NWYwZWQ2MDQwMjRkMzhmYjc1YjQzZTFmY2NmZGQ5ZmNiYzFjMmEzMWY4ZjFhNTUxNjMxODJhNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y6vNehQY-EuDjCCWvuOd6IXKr_nSxXe24_gPHvjZOHM) You can notice the drho decrease very fast to `1e-7`, while fails to converge to `1e-8`. These results indicate the Ce calculations is unstable numerically. This numerical instability might be caused by the pseudopotential. Furthermore, this instability also can lead to some numerical errors in the iterative solution methods (like Davidson method), but this is not a bug, rather it is a feature of this numerical solution technique. You can see more discussion in Issue #4068.

Just to make sure if this change of setting can affect calculation of other types of element or in respect to `scf_time`, memory cost and convergence ?

**Comment by pxlxingliang** [comment]
> Is average `scf_time` too high for V and Sm? Is any way to solve this?


Yes, it seems abnormal for these two examples. I suspect the performance of c64_m128_cpu_H(64) is not good. I will try to use c32_m128_cpu (paratera) to test them.

**Comment by pxlxingliang** [comment]
I use c32_m128_cpu (paratera) to run example v with 32 cores parallel, the first 3 scf steps are:
```
ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s) 
 DA1    -6.424983e+04  0.000000e+00   2.174e+00  7.761e+02  
 DA2    -6.425507e+04  -5.239252e+00  2.121e+00  4.531e+02  
 DA3    -6.425613e+04  -1.065634e+00  8.683e+00  6.127e+02  
```

While the results in this issue are:
```
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)
 DA1    -6.424983e+04  0.000000e+00   2.174e+00  8.604e+02
 DA2    -6.425507e+04  -5.239372e+00  2.121e+00  5.164e+02
 DA3    -6.425613e+04  -1.063900e+00  8.689e+00  7.088e+02
```

As we can see, the performance of c32_m128_cpu (paratera) is better than c64_m128_cpu_H(64).

**Comment by pxlxingliang** [comment]
Update the first 3 SCF steps of Sm on c32_m128_cpu :
```
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)
 DA1    -2.616618e+04  0.000000e+00   7.877e-02  4.249e+03
 DA2    -2.616630e+04  -1.143728e-01  1.732e-02  1.742e+03
 DA3    -2.616623e+04  6.750572e-02   1.187e-01  1.925e+03
```

The results in this issue are:
```
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)
 DA1    -2.616618e+04  0.000000e+00   7.877e-02  3.811e+03
 DA2    -2.616630e+04  -1.143728e-01  1.732e-02  1.372e+03
 DA3    -2.616623e+04  6.750572e-02   1.187e-01  1.624e+03
```

**Comment by ZLI-afk** [comment]
Please see the latest V case which fails to finished the scf calculation due to `KILLED BY SIGNAL: 6 (Aborted)`. Maybe this imply something
[V_failed_signal_6.zip](https://github.com/deepmodeling/abacus-develop/files/15281892/V_failed_signal_6.zip)

**Comment by ZLI-afk** [comment]
> I use c32_m128_cpu (paratera) to run example v with 32 cores parallel, the first 3 scf steps are:
> 
> ```
> ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s) 
>  DA1    -6.424983e+04  0.000000e+00   2.174e+00  7.761e+02  
>  DA2    -6.425507e+04  -5.239252e+00  2.121e+00  4.531e+02  
>  DA3    -6.425613e+04  -1.065634e+00  8.683e+00  6.127e+02  
> ```
> 
> While the results in this issue are:
> 
> ```
>  ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)
>  DA1    -6.424983e+04  0.000000e+00   2.174e+00  8.604e+02
>  DA2    -6.425507e+04  -5.239372e+00  2.121e+00  5.164e+02
>  DA3    -6.425613e+04  -1.063900e+00  8.689e+00  7.088e+02
> ```
> 
> As we can see, the performance of c32_m128_cpu (paratera) is better than c64_m128_cpu_H(64).

Please see the latest V case which fails to finished the scf calculation due to `KILLED BY SIGNAL: 6 (Aborted)`. Maybe this imply something
[V_failed_signal_6.zip](https://github.com/deepmodeling/abacus-develop/files/15281892/V_failed_signal_6.zip)

**Comment by pxlxingliang** [comment]
> Please see the latest V case which fails to finished the scf calculation due to `KILLED BY SIGNAL: 6 (Aborted)`. Maybe this imply something [V_failed_signal_6.zip](https://github.com/deepmodeling/abacus-develop/files/15281892/V_failed_signal_6.zip)

The error of this test is related to the SchmitOrth in davidson:
```
abacus: /abacus-develop/source/module_hsolver/diago_david.cpp:947: void hsolver::DiagoDavid<>::SchmitOrth(const int &, const int, const int, psi::Psi<T, Device> &, const T *, T *, const int, const int) [T = std::complex<double>, Device = psi::DEVICE_CPU]: Assertion `psi_norm > 0.0' failed.
abacus: /abacus-develop/source/module_hsolver/diago_david.cpp:947: void hsolver::DiagoDavid<>::SchmitOrth(const int &, const int, const int, psi::Psi<T, Device> &, const T *, T *, const int, const int) [T = std::complex<double>, Device = psi::DEVICE_CPU]: Assertion `psi_norm > 0.0' failed.
abacus: /abacus-develop/source/module_hsolver/diago_david.cpp:947: void hsolver::DiagoDavid<>::SchmitOrth(const int &, const int, const int, psi::Psi<T, Device> &, const T *, T *, const int, const int) [T = std::complex<double>, Device = psi::DEVICE_CPU]: Assertion `psi_norm > 0.0' failed.
abacus: /abacus-develop/source/module_hsolver/diago_david.cpp:947: void hsolver::DiagoDavid<>::SchmitOrth(const int &, const int, const int, psi::Psi<T, Device> &, const T *, T *, const int, const int) [T = std::complex<double>, Device = psi::DEVICE_CPU]: Assertion `psi_norm > 0.0' failed.
```

Usually, it is because of the numerical instability.
