### ISSUE TITLE
Downsampling the k points in K_Vectors, required in the planewave hybrid functional calculation

### ISSUE THREAD

**Issue by Flying-dragon-boxing** [deepmodeling/abacus-develop#4155]
### Background

For a k point, get downsampled q points: 
$\mathbf{q_k} = \mathbf{k} + \mathbf{b}_1 \dfrac{m_1 C_1}{N_1} + \mathbf{b}_2 \dfrac{m_2 C_2}{N_2} + \mathbf{b}_3 \dfrac{m_3 C_3}{N_3}, (m_i = 0, \cdots, N_i/C_i - 1)$ 
($\mathbf{b}_i$ are the reciprocal lattice vectors of the primitive cell, and $C_i$ is the integer grid reduction factor along reciprocal lattice direction $\mathbf{b}_i$)

Reference: 
https://www.vasp.at/wiki/index.php/Downsampling_of_the_Hartree-Fock_operator
https://doi.org/10.1063/1.2187006

### Describe the solution you'd like

- Given a (maybe global) k point number `ik`
- Get the downsampled k point number list `std::vector<int> iqs`

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Additional Context

I don't really understand much about the M-P sampling and the Gamma Centered sampling process, and I'm curious if the q points got from this method is an exact subset of the k points set. If so, we can use a index `iq` for one q point, and we can easily get the planewaves on q point `iq`. If Interpolation is required, the downsampling seems to be not efficient. 
I think there is no need to support such downsampling for a manually set k point list. (And this may be hard! )

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by Flying-dragon-boxing** [comment]
Actually, for band structure calculation with hybrid functionals, two sets of kpts are used. This may fit in the K_Vectors well.

**Comment by Flying-dragon-boxing** [comment]
@mohanchen This won't be a quick fix and is not needed in current codes. We may close this issue for now and re-open it when necessary.

**Comment by mohanchen** [comment]
We will have new issues when we decide to finish the pw-based hybrid functional project in the near future.
