### ISSUE TITLE
A same deepks example can converge in the old version, but not in the new version

### ISSUE THREAD

**Issue by xuan112358** [deepmodeling/abacus-develop#4156]
### Describe the bug

I tried to use a deepks model to perform SCF calculation in a periodic system containing 32 water molecules in a unit cell.
When I used the older version of ABACUS, v3.1.2, it can converge normally.
<img width="365" alt="image" src="https://github.com/deepmodeling/abacus-develop/assets/64718735/bfea9d43-ba60-41e2-a0a8-6c0ecda55bda">

But when I tried the newer version, 3.6.1, the DRHO would oscillate, and SCF could not converge.
<img width="414" alt="image" src="https://github.com/deepmodeling/abacus-develop/assets/64718735/5f81456f-0d70-44ec-95d2-c8c536e178a6">

I know the mixing method is different between these two versions. So I changed the method from "pulay" in v3.1.2 to "brodyen" in v3.6.2. Should I change other INPUT parameters to get converged results?
By the way, I have tested to use PBE in v3.6.2, and it can converge normally too. 

### To Reproduce

Inputs and results by v3.1.2 / v3.6.1 are in directory 01_3.1.2 / 02_3.6.2
[github_files.zip](https://github.com/deepmodeling/abacus-develop/files/15286565/github_files.zip)
.

### Environment

I use mpiicpc and icpc to compile.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@xuan112358,
I'd like to ask which version of ABACUS's data was used to train the DEEPKS model here? I suspect it's due to version 3.4.0, where we modified the two-center integrals @jinzx10, causing inconsistencies in the dataset precision and leading to a lack of convergence.
@dyzheng, what is your opinion?

**Comment by xuan112358** [comment]
@WHUweiqingzhou I used the data generated by ABACUS v3.1.2. Would this caused the problem?

**Comment by WHUweiqingzhou** [comment]
@xuan112358 
Yes, I think that's one of the reasons. @dyzheng @wenfei-li @ouqi0711 what is your suggestion?

**Comment by ouqi0711** [comment]
I think the modification to the two-center integrals should be the reason that causing the convergence failure. We have investigated similar problem of the perovskite system. The short answer is that data/model trained via v3.4 or earlier can not be directly applied to the current version.

**Comment by xuan112358** [comment]
OK，I think I understand.
I also tried to compile ABACUS v3.6.2 without the new two-center integral code, by turning off the compilation option USE_NEW_TWO_CENTER. And I found that this time the result was consistent with the older version. I think it does suggest that it's the new two-center integrals that caused the different results.
