### ISSUE TITLE
DCU OOM in INIT BASIS and SCF

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#4158]
### Describe the bug

Below DCU jobs have the OOM error:

060 063 102  103  104  105  107  108  117  118  119  120 raise the OOM error in `INIT BASIS`
```
 Make real space PAO into reciprocal space.
       max mesh points in Pseudopotential = 1001
     dq(describe PAO in reciprocal space) = 0.01
                                    max q = 1204

 number of pseudo atomic orbitals for K is 3

 Warning_Memory_Consuming allocated:  PW_B_K::ig2ixyz 9.77457046509 MB
```

061 062 raise OOM error after `INIT SCF`
```
 Make real space PAO into reciprocal space.
       max mesh points in Pseudopotential = 1001
     dq(describe PAO in reciprocal space) = 0.01
                                    max q = 1204

 number of pseudo atomic orbitals for K is 3

 Warning_Memory_Consuming allocated:  PW_B_K::ig2ixyz 9.42510223389 MB
 DONE : INIT BASIS Time : 33.164693522 (SEC)


 -------------------------------------------
 SELF-CONSISTENT
 -------------------------------------------
                                 init_chg = atomic
 DONE : INIT SCF Time : 124.07 (SEC)
```

[oom (2).zip](https://github.com/deepmodeling/abacus-develop/files/15289014/oom.2.zip)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by pxlxingliang** [comment]
Use commit f5c7cb1, I rerun these examples.
Except for 60-63, other examples can run successfully.
60-63 also raise the OOM after INIT SCF

**Comment by WHUweiqingzhou** [comment]
@dyzheng, could you have a look?
