### ISSUE TITLE
Do not allocate extra memory in function `hamilt::diago_PAO_in_pw_k2`

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#4161]
### Background

This function will initialize the value of Psi for one k point, and extra memory of Psi of this k point is allocated.

### Describe the solution you'd like

We should refactor the calculation of `wfcatom` , reuse the memory of Psi and only allocate the extra `(natomwfc - nbands) * npw` memory.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by dyzheng** [comment]
In function `diagH_subspace_init` , the memory of `hpsi` and `spsi` should be `psi_temp.get_nbasis()` rather than `psi_temp.get_nbands() * psi_temp.get_nbasis()` , and `hPsi()` and `sPsi()` should be calculated band by band in only `GPU_DEVICE`.

**Comment by WHUweiqingzhou** [comment]
closed by #4047
