### ISSUE TITLE
Missing tensorflow_cc when building with DeePMD

### ISSUE THREAD

**Issue by FurinaWai77** [deepmodeling/abacus-develop#4176]
### Details

I'm trying to build DeePMD-kit in my Abacus using
`cmake -B build -DLibxc_DIR=~/libxc-6.2.2 -DENABLE_DEEPKS=1 -DTorch_DIR=~/libtorch/share/cmake/Torch/ -Dlibnpy_INCLUDE_DIR=~/libnpy -DDeePMD_DIR=~/deepmd-kit -DTensorFlow_DIR=~/.local/lib/python3.10/site-packages/tensorflow/ -DENABLE_LIBRI=ON -DUSE_CUDA=1 -DCMAKE_CUDA_COMPILER=/usr/local/cuda-11.8/bin/nvcc`

There is libtensorflow_cc.so inside the Python library, but still cannot be found:

`CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find TensorFlow (missing: tensorflow_cc)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindTensorFlow.cmake:18 (find_package_handle_standard_args)
  CMakeLists.txt:586 (find_package)`

But in installing DeePMD-kit it made sense using Python library. Is there a mistake in finding TensorFlow?

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by caic99** [comment]
Hi @FurinaWai77 ,
Is `libtensorflow_cc.so` presented under your `TensorFlow_DIR`?

**Comment by FurinaWai77** [comment]
> Hi @FurinaWai77 , Is `libtensorflow_cc.so` presented under your `TensorFlow_DIR`?

Yes, both libtensorflow_cc.so.2 and libtensorflow_framework.so.2, is it because of the suffix "2"?

**Comment by FurinaWai77** [comment]
> > Hi @FurinaWai77 , Is `libtensorflow_cc.so` presented under your `TensorFlow_DIR`?
> 
> Yes, both libtensorflow_cc.so.2 and libtensorflow_framework.so.2, is it because of the suffix "2"?

I linked the files to the ones without suffix "2" and it built successfully. Maybe need a fix?

**Comment by caic99** [comment]
Hi @FurinaWai77 ,
I've installed tensorflow within my conda environment, and the path to `libtensorflow_cc.so` is `/opt/conda/envs/deepmd/lib`. Did you install tensorflow with `pip`? The file without suffix should always be available.
