### ISSUE TITLE
An error in ASE-ABACUS when reading atomic positions

### ISSUE THREAD

**Issue by ieiue** [deepmodeling/abacus-develop#4179]
### Describe the bug

![image](https://github.com/deepmodeling/abacus-develop/assets/116336560/bb28f86d-03c4-4eae-a303-cb3c63393422)
When using ASE-ABACUS reading this STRU file, there will be an error. I find that it can be solved by adding information to the three columns of atomic positions, such as "m  1  1  1" to allow atoms to move, so that the number of columns is greater than 3.

### Expected behavior

Only atomic coordinates will work successfully.

### To Reproduce

I'm sorry I can't provide the files because there are some problems with the workstation.

### Environment

ABACUS v.3.6.0

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@1041176461 could you have a look?

**Comment by 1041176461** [comment]
Ok, I suggest that the issue of the ase-abacus interface should be submitted to our GitLab rep (https://gitlab.com/1041176461/ase-abacus) for recording.

**Comment by 1041176461** [comment]
Fixed in the newest commit in ase-abacus gitlab
