### ISSUE TITLE
ABACUS 3.6.3 can not ouput LCAO wave functions when "out_wfc_lcao = 1"

### ISSUE THREAD

**Issue by sgyang345** [deepmodeling/abacus-develop#4184]
### Describe the bug

When runing ABACUS with SCF and NSCF, ABACUS 3.6.3 can not ouput LCAO wave functions when "out_wfc_lcao = 1".

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by kirk0830** [comment]
could you explain more? cuz merely adding `out_wfc_lcao 1` in example/scf/lcao_Si2, I can still see there are LOWF_* files in OUT.ABACUS directory

**Comment by sgyang345** [comment]
It's so weird, I got the same result as you in the example (example/scf/lcao_Si2).
However, the calculations I created myself do not yield the LCAO wave function.
I'm going to do a lot of trying to make sure I find the problem and get back to you after that.

**Comment by QuantumMisaka** [comment]
@sgyang345 Can you share your INPUT file ?

**Comment by sgyang345** [comment]
Of course, this is my INPUT file.

> INPUT_PARAMETERS
>   calculation     nscf
>   suffix          ABACUS
>   ntype           4
>   basis_type      lcao
>   vdw_method      d3_0
>   ecutwfc         100
>   smearing_method gaussian
>   smearing_sigma  0.01
>   mixing_type     pulay
>   mixing_beta     0.2
>   nspin               4
>   lspinorb            1
>   init_chg        file
>   out_wfc_lcao    1

**Comment by mohanchen** [comment]
https://mcresearch.github.io/abacus-user-guide/abacus-chg.html
