### ISSUE TITLE
No warning is given if symmetry=1 in electric field calculation

### ISSUE THREAD

**Issue by Luc1anoo** [deepmodeling/abacus-develop#4193]
### Describe the bug

In ABACUS calculations with an electric field (efield_flag = True), symmetry must be turned off; otherwise, the results will be the same as without the electric field.

### Expected behavior

Throw a warning or autoset the symmetry off directly when if user set symmetry=1 in electric field calculation.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by maki49** [comment]
> otherwise, the results will be the same as without the electric field.

Does this problem also appear at symmetry=0 (or it only appears at symmetry=1)?
- symmetry=0 means only space group symmetry is turned off while time-reversal symmetry still works

**Comment by Luc1anoo** [comment]
> > otherwise, the results will be the same as without the electric field.
> 
> Does this problem also appear at symmetry=0 (or it only appears at symmetry=1)?
> 
> * symmetry=0 means only space group symmetry is turned off while time-reversal symmetry still works

I encounter this problem when performing band structure calculation of bilayer graphene with the eletric filed turned on. When the symmetry is 0 the band gap is open, and when the symmetry is 1 the band structure is the same as without the electric field(i.e. no band gap).
To reproduce:
[bilayer_graphene.zip](https://github.com/deepmodeling/abacus-develop/files/15399961/bilayer_graphene.zip)
Just set `symmetry` = 0/1 in INPUT to compare.

**Comment by maki49** [comment]
I see. I've tested that symmetry=0 and -1 give the same result.
