### ISSUE TITLE
`angle1` and `angle2` is set in xyz axes but NOT in abc axes OR the magmoment is output in abc axes but NOT xyz axes?

### ISSUE THREAD

**Issue by xdzhu** [deepmodeling/abacus-develop#4194]
### Describe the bug

I have used the primitive cell of bcc iron to calculate the magmoment along the 45 degree of z-axis and it lies in zx plane ( in purple).  I carefully read the documentaion to know how to set the angle1 and angle2. I found that the angle between mag and c-axis is 90 degree and between the projection in ab plane and a-axis is 35.26 degree with my lattice vectors as below:

> LATTICE_VECTORS
>  1.4349959999999999    1.4349959999999999    1.4349959999999999
> -1.4349959999999999    1.4349959999999999    1.4349959999999999
> -1.4349959999999999   -1.4349959999999999    1.4349959999999999

**So I set the angle1=90 and angle2=35.26 to describe it. One can easily find out that the mag vector (in purple) is not lies in each of `ab` `bc` or `ac` plane.**
![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/4e999422-6953-4c17-b497-9eae10d5d2ec)

However, when I check for the running_scf.log and the mulliken.txt, the total magnetism line told me that **the magmoment was initialized in xy plane but not in zx plane, i.e. the angle1 of 90 degree rotate the magmoment to xy plane.**

![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/f8b37184-6c70-44c0-91da-03a5f8f40456)

**It can be seen from the log that the angle1 and angle2 is set in xyz axes but not abc axes.**  

I also check another calculation with mag moment along z-aixs which means the so called angle1 should be 54.74 and angle2 should be 19.47. 

![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/3ec6d72b-5082-48f4-b315-3aa05d9828ab)

And I got this:
![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/65fe54ea-29c5-4422-b18a-c2699fb11827)

The description in DOC is as below and I want to figure out **Which axis are they describing indeed?**  OR the magmoment is output in abc axes but NOT xyz axes?

![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/4518c3aa-f2d3-49a8-bbd4-9ef016ddc35c)

### Expected behavior

check the angle1 angle2 target_mag_angle1 target_mag_angle2 parameter

### To Reproduce

[issue-angle.zip](https://github.com/deepmodeling/abacus-develop/files/15386161/issue-angle.zip)
check this zip file.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by pxlxingliang** [comment]
In abacus codes, the parse of angle1 and angle2 in STRU is in https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_cell/read_atoms.cpp#L613-L626.
```
                        else if ( tmpid == "angle1")
                        {
                                ifpos >> atoms[it].angle1[ia];
                                atoms[it].angle1[ia]=atoms[it].angle1[ia]/180 *ModuleBase::PI;
                                input_angle_mag=true;
                                set_element_mag_zero = true;
                        }
                        else if ( tmpid == "angle2")
                        {
                                ifpos >> atoms[it].angle2[ia];
                                atoms[it].angle2[ia]=atoms[it].angle2[ia]/180 *ModuleBase::PI;
                                input_angle_mag=true;
                                set_element_mag_zero = true;
                        } 
```

And the angle1/2 is translated to x/y/z component at https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_cell/read_atoms.cpp#L643-L654.
```
                            if(input_angle_mag)
                            {
                                atoms[it].m_loc_[ia].z = atoms[it].mag[ia] *
                                    cos(atoms[it].angle1[ia]);
                                if(sin(atoms[it].angle1[ia]) > 1e-10 )
                                {
                                    atoms[it].m_loc_[ia].x = atoms[it].mag[ia] *
                                        sin(atoms[it].angle1[ia]) * cos(atoms[it].angle2[ia]);
                                    atoms[it].m_loc_[ia].y = atoms[it].mag[ia] *
                                        sin(atoms[it].angle1[ia]) * sin(atoms[it].angle2[ia]);
                                }
                            }
```
From the code, we can see the angle1 is between Z axis and spin, and angle2 is between X axis and projection of spin on XY plane.

This may be a mistake of DOC.
