### ISSUE TITLE
Convergence issue in regards to Nd

### ISSUE THREAD

**Issue by ZLI-afk** [deepmodeling/abacus-develop#4204]
### Details

Please see following case of a pure Nd structure which fails to converge in the `scf` calculation with a rather strict pro-convergence `INPUT` setting according to [ABACUS收敛性问题解决手册](https://ucoyxk075n.feishu.cn/docx/R0sqdk6T0o2RY4x5IWgcJ3RHnug?from=from_copylink):

- **Task**: [Nd_uncov_case.zip](https://github.com/deepmodeling/abacus-develop/files/15398405/Nd_uncov_case.zip)

- **Image**: registry.dp.tech/dptech/abacus:3.6.3-less-memory

- **machine type**: 4 * DCU_16g

```javascripts
INPUT_PARAMETERS
calculation scf
device gpu
basis_type pw
symmetry 0
ecutwfc 100
scf_thr 1e-08
scf_nmax 200
cal_force 1
cal_stress 1
kspacing 0.08
pseudo_rcut 10
pseudo_mesh 1
ks_solver cg
relax_nmax 100
force_thr 0.001
stress_thr 0.5
mixing_ndim 15
mixing_beta 0.1
mixing_gg0 1.5
smearing_method gaussian
smearing_sigma 0.01
```

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by ZLI-afk** [comment]
This may be closely related to #4080

**Comment by WHUweiqingzhou** [comment]
I also make some [tests](https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-nd-gg0-abacustest-v0.3.113-5375e2), and find all setting fail to converge. I will re-run these calculations in CPU to double-check.

**Comment by WHUweiqingzhou** [comment]
@ZLI-afk  
CPU calculations also fail to converge. I would like to ask if this structure is the ground state configuration or a perturbed configuration?

**Comment by ZLI-afk** [comment]
> @ZLI-afk CPU calculations also fail to converge. I would like to ask if this structure is the ground state configuration or a perturbed configuration?

It's one of Nd 150 perturbed structures, and I think they all failed to converge.

**Comment by WHUweiqingzhou** [comment]
@ZLI-afk,
According to the suggestions from @mohanchen, I make 3 tests for this case:
1. increase `smearing_sigma`
2. try different mixing method, like Pulay/Broyden
3. try different diag method, like CG/dav

1 and 2 all fail to converge, and Davidson method results in OOM due to larger memory cost.

You can see the [Test](https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-nd-abacustest-v0.3.114-a5e6be).

I am inclined to think that the convergence issue stems from an unreasonable structure, and I have no better ideas on how to further improve the convergence of this system. Does anyone else have any thoughts?

**Comment by WHUweiqingzhou** [comment]
I also perform some calculations with extremely small `mixing_beta=0.1, 0.05, 0.01`, and SCF still fails to converge. See [link](https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-nd-nogg0-abacustest-v0.3.114-a11476).

**Comment by WHUweiqingzhou** [comment]
To avoid the convergence problem caused by Gamma point, I perform some calculations by using k-offset. No one converges. See the [link](https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-nd-koffset-abacustest-v0.3.114-11a6b5).

**Comment by WHUweiqingzhou** [comment]
Different pseudo potentials have also been considered, and QE also gives unconverged result. see the [link](https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-nd-qe-abacustest-v0.3.116-b3d71c) .

**Comment by kirk0830** [comment]
I tested QE with:
```
diagonalization = 'rmm-davidson'
mixing_mode = 'TF'
mixing_beta = 0.1
mixing_ndim = 12
```
,
```
diagonalization = 'ppcg'
mixing_mode = 'TF'
mixing_beta = 0.1
mixing_ndim = 12
```
,
```
diagonalization = 'rmm-davidson'
mixing_mode = 'TF'
mixing_beta = 0.05
mixing_ndim = 16
diago_rmm_ndim = 8
```
none of them works, unfortunately.
But I checked the structure and get confused about the rationality of this calculation, it is like:
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/14b3352b-e266-4b53-8828-ee861da2f9c2)
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/6b0cffce-abc0-446c-94cb-66871d2bf2b4)

**Comment by WHUweiqingzhou** [comment]
We think this converge issue of Nd system occurs in off-equilibrium structure.
