### ISSUE TITLE
Compatibility of current GPU code with DCU hardware

### ISSUE THREAD

**Issue by LiuXiaohui123321** [deepmodeling/abacus-develop#4205]
### Describe the Code Quality Issue

When I try to compile ABACUS's GPU/DCU version, it reports an error with the following message, 
<img width="1103" alt="36ed21932395b94da82e151ab2a47a5" src="https://github.com/deepmodeling/abacus-develop/assets/25027983/f6aa0572-3b0f-491a-893f-61ee89292304">

I've checked the related code and the problem may be here: https://github.com/deepmodeling/abacus-develop/blob/0ecc1690bf82e488926dbbbafa9fedd7e9ec67eb/source/module_base/module_device/device.h#L67

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by LiuXiaohui123321** [comment]
When calling the function gint_kernel_vlocal()
https://github.com/deepmodeling/abacus-develop/blob/0ecc1690bf82e488926dbbbafa9fedd7e9ec67eb/source/module_hamilt_lcao/module_gint/gint.h#L79

the following two positions may be problematic because the function's argument list is inconsistent.
https://github.com/deepmodeling/abacus-develop/blob/0ecc1690bf82e488926dbbbafa9fedd7e9ec67eb/source/module_hamilt_lcao/module_gint/gint.cpp#L347

https://github.com/deepmodeling/abacus-develop/blob/0ecc1690bf82e488926dbbbafa9fedd7e9ec67eb/source/module_hamilt_lcao/module_gint/gint.cpp#L351

**Comment by denghuilu** [comment]
What are the compilation commands for CMake ? Did you set the `-DUSE_ROCM=ON` flag ?

**Comment by LiuXiaohui123321** [comment]
Probably since DTK 23.04, it's somewhat compatible with CUDA code. My compilation command is `CC=nvcc CXX=nvcc cmake ... -DUSE_CUDA=1`

**Comment by pxlxingliang** [comment]
@LiuXiaohui123321, you can refer the linked docs to install and use the DCU version's abacus.
https://dptechnology.feishu.cn/docx/MNmNdOevCo2QWWxhxKBctLPdn9e

**Comment by LiuXiaohui123321** [comment]
Thanks! But I need to use LCAO's GPU code, not PW's

**Comment by WHUweiqingzhou** [comment]
@A-006 could you have a look?

**Comment by mohanchen** [comment]
Will close this issue since no further actions are expected from here.
