### ISSUE TITLE
Error when compile abacus with openmp off 

### ISSUE THREAD

**Issue by goodchong** [deepmodeling/abacus-develop#4208]
### Describe the bug

![微信图片_20240522165213](https://github.com/deepmodeling/abacus-develop/assets/3149059/eb2fcf1a-c682-467b-bc6a-6620fd127648)
Encountered errors during compilation abacus with openmp off

### Expected behavior

Compile correctly without OpenMP.

### To Reproduce

cmake -B build -DUSE_OPENMP=OFF
cmake --build build -j`nproc`

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by caic99** [comment]
Hi @goodchong ,
As far as I know, abacus does not support building without OpenMP - it is not tested, and the correctness cannot be assured.

**Comment by goodchong** [comment]
Sure. OPENMP turn off is not an urgent and real requirement. This issue is mainly to record this phenomenon. Maybe we should discuss how we tackle this matter and whether it is necessary in the future to consider removing the OPENMP option in the compilation settings. @caic99

**Comment by goodchong** [comment]
By the way, removing the OPENMP compile option would simplify our code to some content. In a sense, this is quite a tempting idea.
