### ISSUE TITLE
A memory leak is suspected because of the continuous memory increase during cell-relax

### ISSUE THREAD

**Issue by ieiue** [deepmodeling/abacus-develop#4215]
### Describe the bug

 When making a cell-relax calculation of Fe_128H, the memory is keeping increasing. So a memory leak is suspected. 
![e4043da336c2681b9b74d36d2c92b34](https://github.com/deepmodeling/abacus-develop/assets/116336560/a1fde45c-f06c-4994-8e95-3defbe387ea5)
The X axis is time (10s, e.g. the last horizontal value is 4852*10=48520 s ), and the Y axis is memory (GB). This calculation consumes too much memory to finish.

### To Reproduce

[Fe128H_10au_TZDP.zip](https://github.com/deepmodeling/abacus-develop/files/15411071/Fe128H_10au_TZDP.zip)

### Environment

ABACUS v.3.6.3

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by dyzheng** [comment]
I repeat your case with "device cpu" , and no memory leak is detected:
![image](https://github.com/deepmodeling/abacus-develop/assets/49852742/79c49731-c5ce-4a0a-ab70-a5c04647e522)

**Comment by dzzz2001** [comment]
After investigation, it appears that the memory leak is occurring in the cal_gint_force function. We will work on fixing this bug.
![img_v3_02b5_1aaaecae-cdc2-4743-b3be-acdb102ff9dg](https://github.com/deepmodeling/abacus-develop/assets/153698752/a61d7aff-7f54-4e2b-afe4-c4ce44bce28b)

**Comment by dzzz2001** [comment]
PR #4200 has fixed the memory leak in cal_gint_force, you can retry this calculation.

**Comment by WHUweiqingzhou** [comment]
@ieiue has this issue solved after PR #4200?

**Comment by WHUweiqingzhou** [comment]
fixed by #4200
