### ISSUE TITLE
`out_wfc_lcao` not work well since #2085

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#4220]
### Describe the bug

In #2085 , variable `out_wfc_flag` is added , which is not working in nscf calculation.

TODO:
1. Feature of `out_wfc_lcao` should be repaired, and parameters of `out_wfc_lcao` and `out_wfc_flag` should not exist together.
2. add test of `out_wfc_lcao` in CI test.

### Task list for Issue attackers (only for developers)

- [X] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by pxlxingliang** [comment]
#4268
