### ISSUE TITLE
"solve_tridie gj" appear during scf calculation and then the program crash.

### ISSUE THREAD

**Issue by formocho** [deepmodeling/abacus-develop#4230]
### Describe the bug

We use LCAO method to calculate a configuration of diamond with 216-atom, it would appear "solve_tridie gj" in some case. (If there are no errors, it may be necessary to test multiple times). However, both configurations with 8, 64-atom can run calcualtion completely. 

### Expected behavior

The scf calculation would be in convergence under multi-iteration.

### To Reproduce

[example.zip](https://github.com/deepmodeling/abacus-develop/files/15430904/example.zip)
run command: 
`export OMP_NUM_THREADS=1;
mpirun -np 64 abacus`

### Environment

OS: Ubuntu 16.04
Compiler: Intel OneAPI 2021
Dependencies: MKL, ELPA

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
OK, I will make some tests.

**Comment by WHUweiqingzhou** [comment]
@formocho，
I perform the calculation by using your input file, and fail to reproduce the error. I use v3.6.4. Could you try our latest version to double-check it?
[4230.zip](https://github.com/user-attachments/files/15582418/4230.zip)

**Comment by WHUweiqingzhou** [comment]
If you find the bug is still there, reopen this issue.
