### ISSUE TITLE
Questions about the calculation of Hartree energy

### ISSUE THREAD

**Issue by daikemon** [deepmodeling/abacus-develop#4235]
### Details

# Background

I am trying to use abacus v3.5.3 to read the charge density and calculate the corresponding Hartree energy with PBE functional. The charge density comes from a converged calculation of HSE calculation with the same STRU and KPT, and the following is the INPUT of the HSE calculation

```
INPUT_PARAMETERS
suffix                  SiO2
ntype                   2
pseudo_dir              ../abacus/SG15-Version1p0_Pseudopotential/SG15_ONCV_v1.0_upf
orbital_dir             ../abacus/SG15-Version1p0__StandardOrbitals-Version2p0/SG15-Version1p0__StandardOrbitals-Version2p0
ecutwfc                 80
scf_thr                 1e-6
basis_type              lcao
calculation             scf

scf_nmax                100
out_chg                 True
dft_functional          hse
```

and the following is the INPUT of the PBE calculation, where I set the `scf_nmax` , `scf_thr` , `init_chg` , `mixing_beta` , `symmetry` to keep charge density unchanged.

```
INPUT_PARAMETERS
suffix                  SiO2
ntype                   2
pseudo_dir              ../abacus/SG15-Version1p0_Pseudopotential/SG15_ONCV_v1.0_upf
orbital_dir             ../abacus/SG15-Version1p0__StandardOrbitals-Version2p0/SG15-Version1p0__StandardOrbitals-Version2p0
ecutwfc                 80
scf_thr                 1
basis_type              lcao
calculation             scf

scf_nmax                1
out_chg                 True
init_chg                file
mixing_beta             0
symmetry                0
```

# Question

I found `E_Hartree = 1763.4014879563 eV ` in the PBE calculation and `E_Hartree = 1775.7046548165 eV ` in the HSE calculation. I checked the charge density in OUT.SiO2, which was the same except the fermi energy.

How does the choose of functional influence the Hartree energy if the charge density is unchanged ? 

[SiO2_Hartree.zip](https://github.com/deepmodeling/abacus-develop/files/15442483/SiO2_Hartree.zip)

Thanks a lot!

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by WHUweiqingzhou** [comment]
@daikemon,
if you want to keep the input charge density unchanged, you should perform NSCF calculation. As for you case, you choose SCF calculation to find the ground state, and PBE will give a different one compared with HSE.

**Comment by daikemon** [comment]
Thanks for your reply，but I think there is a misunderstanding.

I am trying to get the Hartree energy of a specific charge density in PBE functional, even it is not the ground state. NSCF calculation does not give the values of energies, so I use SCF calculation and set `scf_nmax = 1` to calculate the Hartree energy of the charge density I choose, instead of finding the ground state.  And here I choose the ground state charge density in HSE functional.

if the Hartree energy of a specific charge density is independent of the choice of HSE and PBE functional,
![image](https://github.com/deepmodeling/abacus-develop/assets/46552705/f696d3b9-e8e6-4832-ad3d-652cb574e8c2)
the results should be the same even it is not the ground state. So I am trying to figure out what the difference is in my results.

**Comment by WHUweiqingzhou** [comment]
@daikemon,
I see. Indeed, the Hartree energy only depends on the charge density, while PBE and HSE will give different output charge density. 
Could you try not to mix charge density with output charge by setting `mixing_beta = 0.0`?

**Comment by daikemon** [comment]
Yes, I have set `mixing_beta  =  0` as shown in the Background, and that's why I am confused.

**Comment by WHUweiqingzhou** [comment]
@daikemon,
I notice the `symmetry` is different, try to unify it. If still different, I think the difference originates from the CHG file, which is not a binary file. Or a bug.

**Comment by daikemon** [comment]
I notice that the manual says the `symmetry = 0` If `dft_fuctional=hse`, so I use  `symmetry = 0`  in my following PBE calculation.
When I set `symmetry` as default in PBE calculation, the Hartree energy is still 1763.4014 eV, different from that in the converged HSE result (1775.7046 eV) . 
And I am sorry that I don't know how to output the binary file of the charge density from the web manual, so I cannot check if it is the key of the problem.

**Comment by WHUweiqingzhou** [comment]
@kirk0830 How can one output the charge density as accurately as possible?

**Comment by kirk0830** [comment]
> @kirk0830 How can one output the charge density as accurately as possible?

@WHUweiqingzhou I am not sure about whether ABACUS supports binary output of 3D grid data, but it will be easy to support printing cube file with higher precision. If needed, I will implement that

**Comment by WHUweiqingzhou** [comment]
@daikemon 
Hi, I have figured it out. It is because you set `scf_thr 1`.
`scf_thr 1` means SCF would converge even just after one iteration. For converged result, it will update Hartree energy by using output charge density even though you set `mixing_beta 0.0`.
Please remove `scf_thr 1` in your INPUT.
