### ISSUE TITLE
Need to uniform the file name of the output of wave functions coefficients 

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#4246]
### Describe the Code Quality Issue

Abacus support the output of coefficients of wave functions, but the file names are not consistent in different situations. Such as:
- for pw basis, the file name is "WAVEFUNC${K}.txt", 
- for pw basis, the file name of real space wfc is "wfc_realspace/wfc_realspace_${K}_${B}"
- for lcao basis with gamma-only, the file name is "LOWF_GAMMA_S1.txt", 
- for lcao basis without gamma-only, the filename is "LOWF_K_${k}.dat"

The different formats of the filename will confuse the user.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by pxlxingliang** [comment]
One possible design is: WFC_{basis_type}\_{SPIN index}\_{K index}_{BAND index}. Such as:
- for pw basis with nspin=2, the wfc file name can be like: "WFC_PW_S1_K1.dat", "WFC_PW_S1_K2.dat",...,"WFC_PW_S2_K1.dat",...
- for real space in pw basis, the file name can be like: ""wfc_realspace/WFC_PWRS_S1_K1_B1",... (where PWRS means PW in real space)
- for LCAO basis with gammaonly, the file name can be like: "WFC_LCAO_S1_GAMMA1.dat"
- for LCAO basis without gammaonly, the file name can be like: "WFC_LCAO_S1_K1.dat", "WFC_LCAO_S1_K2.dat",..., "WFC_LCAO_S2_K1.dat"

Or we can remove the sign of SPIN and reflect the SPIN 2 with more K points: WFC_{basis_type}\_{K index}\_{BAND index}. Such as:
-  for LCAO basis with gammaonly and nspin=2, the file name can be like:  "WFC_LCAO_GAMMA1.dat", "WFC_LCAO_GAMMA2.dat"

I prefer the second one, which is more concise.

**Comment by pxlxingliang** [comment]
Another related parameter is "out_app_flag", which control if output with the append model in MD. So the file name should also contain the ION step, and can be like: "WFC_LCAO_GAMMA1_ION1.dat", which add sign "ION{idx}".

**Comment by kirk0830** [comment]
Present structure of file `LOWF_K_*.txt` really nasty, it is desiged neither for human to read nor easy for program to read. I would suggest re-design the structure of wavefunction output file
