### ISSUE TITLE
Non-magnetic atoms are magnetized by nupdown constraint

### ISSUE THREAD

**Issue by Shen-Zhen-Xiong** [deepmodeling/abacus-develop#4255]
### Describe the bug

[nupdown_v20240528.zip](https://github.com/deepmodeling/abacus-develop/files/15465363/nupdown_v20240528.zip)
I  perform a constraint calculation by using "nupdown=6" parameter with ABACUS code, non-magnetic atoms "S" are magnetized, but magnetic atoms "Co" are not magnetized, which doesn't seem quite normal. While I calculate the same system with VASP code, "Co" is magnetized but "S" is not. 

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by dyzheng** [comment]
I want to ask if the band structure of ABACUS is same as VASP?

**Comment by Shen-Zhen-Xiong** [comment]
> I want to ask if the band structure of ABACUS is same as VASP?
Not same.

**Comment by mohanchen** [comment]
It is possible that this is normal, since magnetization calculations are more difficult and the existence of several local minimal is expected
