### ISSUE TITLE
Question: about the default value setting of parameter `ecutwfc`

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#4283]
### Details

Different from softwares which limit users' choice on pseudopotentials to use, for which developers can type in recommended ecutwfc values in their published pseudopotentials. However for community using upf pseudopotentials, this is not possible and reliable. Even as far as I know there are plenty pseudopotentials without such a line like "suggested ecutwfc" and/or "suggested ecutrho".

However sometimes user may forget to set ecutwfc, for cases where "hard" pseudopotentials are used in calculation, the default value 50 Ry may not be enough and result in highly unreliable data. Therefore the default value seems to be case-specific.

How to set the default value of ecutwfc?

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by WHUweiqingzhou** [comment]
I agree to improve the default value of `ecutwfc` to 100 Ry for LCAO basis, and `ecutrho=4*ecutwfc` for sure.
As for PW bases, I think 100 Ry is quite large for some simple cases. Maybe we should keep the default value as 50 Ry.

**Comment by kirk0830** [comment]
But a more reasonable plan would be, greping ecutwfc that used to generate orbitals and get max to set ecutwfc for LCAO calculation, while set element-by-element for PW.
But due to present code structure, both solutions are not plausible.

**Comment by WHUweiqingzhou** [comment]
According to our inner meeting, we decide to change the default setting `ecutwfc` as 100 Ry for LCAO basis, and keep it unchanged as 50 Ry for PW basis. When I try to make the corresponding modifications, and found some obstacles. `ecutwfc` is read in `item_system()` and `basis_type` is read in `itea_elec_stru()` after `ecutwfc`:
```cpp
ReadInput::ReadInput(const int& rank)
{
    this->rank = rank;
    
    // add items
    this->item_system();
    this->item_elec_stru();
```
Because by the time I found out about the `basis_type`, I was no longer able to determine whether the `ecutwfc` had been read. Any suggestion? @Qianruipku, @kirk0830

**Comment by QuantumMisaka** [comment]
Any update? I think this default value is important

**Comment by kirk0830** [comment]
@QuantumMisaka After discussion, we think this feature may require a slight change on param module, so we consult developer of that module.
