### ISSUE TITLE
ABACUS numerical atomic orbitals for Al/Ti/Zr/Nb/Hf-sp.PD04.PBE.UPF pseudopotentials?

### ISSUE THREAD

**Issue by Luc1anoo** [deepmodeling/abacus-develop#4284]
I'm testing the accuracy of `lcao` basis calculating elastic constant of Al. The `pw` basis can give precise result consistent with the experimental result. But using `lcao` basis with `Al_gga_7au_100Ry_4s4p1d.orb` orbital the result is incorrect. So can I get a orbital generated from `Al-sp.PD04.PBE.UPF` for this test?
ABACUS version: 3.6.3

**Comment by kirk0830** [comment]
I will generate a series of orbitals for Al-sp.PD04.PBE.UPF pseudopotential. Please follow this issue, once generation completes, I will post them here.

**Comment by kirk0830** [comment]
[Al-sp.PD04.PBE.zip](https://github.com/user-attachments/files/15510659/Al-sp.PD04.PBE.zip)
@Luc1anoo here are all conventionally used configuration orbitals

**Comment by Luc1anoo** [comment]
Thanks a lot!

**Comment by Luc1anoo** [comment]
Using the `Al-sp.PD04.PBE.UPF` the orbital generated by it, I got the elastic constants as accurate as `pw` basis. Now I want to go further to calculate the elastic constants of multicomponent alloys `NbTiZrHf` in literature [10.1088/1361-651X/ac1bfa](https://iopscience.iop.org/article/10.1088/1361-651X/ac1bfa) . Can I get four more orbitals generated by pseudopotential `Hf-sp.PD04.PBE.UPF`, `Zr-sp.PD04.PBE.UPF`, `Ti-sp.PD04.PBE.UPF` and `Nb-sp.PD04.PBE.UPF` respectively? That will be grately appreciated.

**Comment by kirk0830** [comment]
Hi, here are orbitals.
Please keep in mind these orbitals are generated based on occupied states, therefore only properties based on ground states are expected to reproduced well, for any properties involving those unoccupied need to use with care.

Hope that help.

[Hf-sp.PD04.PBE.UPF.zip](https://github.com/user-attachments/files/15580736/Hf-sp.PD04.PBE.UPF.zip)
[Nb-sp.PD04.PBE.UPF.zip](https://github.com/user-attachments/files/15580742/Nb-sp.PD04.PBE.UPF.zip)
[Ti-sp.PD04.PBE.UPF.zip](https://github.com/user-attachments/files/15580745/Ti-sp.PD04.PBE.UPF.zip)
[Zr-sp.PD04.PBE.UPF.zip](https://github.com/user-attachments/files/15580748/Zr-sp.PD04.PBE.UPF.zip)
