### ISSUE TITLE
Unable to open mca_btl_openib at 3.6.3 GPU version of abacus

### ISSUE THREAD

**Issue by Chentao168** [deepmodeling/abacus-develop#4286]
### Details

I installed the 3.6.3 GPU version of abacus on my workstation using conda. 
When I run abacus, I met the following message but it does not affect the running of abacus: 
`[chentao-Precision-7920-Tower:159376] mca_base_component_repository_open: unable to open mca_btl_openib: librdmacm.so.1: cannot open shared object file: No such file or directory (ignored)`

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by denghuilu** [comment]
@caic99 Have you seen such an error before ?

**Comment by caic99** [comment]
> @caic99 Have you seen such an error before ?

@Chentao168 Maybe you should check your OpenMPI installation is correct.

**Comment by Chentao168** [comment]
I used Conda to install the 3.6.3 GPU version of abacus on my workstation. So how to check whether my OpenMPI installation is correct? @caic99

**Comment by caic99** [comment]
@Chentao168 This seems to be a known issue from OpenMPI: https://github.com/conda-forge/openmpi-feedstock/issues/38
Abacus also offers its MPICH variant.

**Comment by Chentao168** [comment]
By using MPICH, the above issues will no longer occur.
