### ISSUE TITLE
Note: not all member variables need setter functions

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#4288]
### Describe the Code Quality Issue

After reading recently merged code, I want to inform developers please do not add redundant setters to class, unless they are really needed as a part of design of class, NOT FOR THE DESIGN FOR UNIT TEST.
For example in K_Vectors class, it is not appropriate to add setter functions for nks, nkstot etc, because those variables strongly bind with kvec_c, kvec_d. The setter function will bring extra risk of making the K_Vectors class not self-consistent, breaks the state of K_Vectors class.
Still take K_Vectors class as example, it is actually "a thing" can/should only get two kinds of information:
1. the KPT file
2. gamma only flag or kspacing flag with lattice vectors

Then can this class calculate by itself the corresponding set of k points, and nks, nkstot, kvec_c, kvec_d, kc_done, kd_done, ... variables together can define the state of the instance of K_Vectors (although the necessity of a class of K_Vectors is still questionable but it is not the thing I want to discuss here).
However, once there is possibility that can change some variables like nks, nkstot, etc, which means drive the instance to the state in principle not possible, or say the setter function enabling the probability of breaking the encapsulation, self consistency of the class, it is, detrimental rather than beneficial.

Another part would be the design of unit test.
1. once a unit test must need stealing something from the function or class it test on, please refactor or redesign the function or class, because it means the function is not written with enough design on decoupling.
2. DO NOT WRITE SETTER FUNCTION ONLY BECAUSE YOU WANT TO WRITE SOME UNITTESTS.

Thanks.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by WHUweiqingzhou** [comment]
@kirk0830, do you think this information should be added into docs for developers?

**Comment by kirk0830** [comment]
> @kirk0830, do you think this information should be added into docs for developers?

hmmm...I think it would be better that code reviewer directly requires code changes next time if there will be any PR voilating this principle.
