### ISSUE TITLE
Undefine problem in `source\module_cell\parallel_kpoints.h`

### ISSUE THREAD

**Issue by jwsyzy** [deepmodeling/abacus-develop#4290]
### Describe the Code Quality Issue

Two variables are undefined; they are declared as member variables within the `class Parallel_Kpoints` in `source\module_cell\parallel_kpoints.h` : `int* nproc_pool = nullptr;`and `int* startpro_pool = nullptr;` 
The variable `nproc_pool` is neither assigned a value nor used anywhere in the class, so we delete it.
However, for 'startpro_pool', we can't find where it is assigned a value but it actually used in the code. 
But these variables are properly defined and assigned values in another location of the codebase, specifically within `tools\SIAB\SimulatedAnnealing\backup_old_version\1_Source\src_parallel\parallel_kpoints.cpp`.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by WHUweiqingzhou** [comment]
@kirk0830, could you have a look?

**Comment by jwsyzy** [comment]
we have now added `void get_startpro_pool(void)` similar to the backup_old_version and it passed all pr checks, but it's puzzling how it worked before without this change.

**Comment by kirk0830** [comment]
> startpro_pool

@WHUweiqingzhou @jinzx10 and I have done a quick scan. It seems, conventionally kpar will be set to 1 in pw calculation, therefore the undefined behavior is not triggered in function `pool_collection`.

**Comment by Qianruipku** [comment]
> we have now added `void get_startpro_pool(void)` similar to the backup_old_version and it passed all pr checks, but it's puzzling how it worked before without this change.

@jwsyzy 
Because it is only used in output_overlap function (out_spillage > 0). On the one hand,  it is not often used by users. On the other hand, they used it but did not open k parallel.  Maybe you should test out_spillage with kpar > 1 to test if startpro_pool is OK

**Comment by Qianruipku** [comment]
This issue can be closed
