### ISSUE TITLE
Found a Bug during Integration Test and Unit Test / Test when Trying to Do a PR

### ISSUE THREAD

**Issue by HaCTang** [deepmodeling/abacus-develop#4293]
### Describe the bug

TEST 252：esolver_dp_test failed
I added some openMP code to esolver_dp.cpp. It says like this. But when I use examples on Bohrium, it worked very well, no matter how many OMP_NUM_THREADS I set. I think this may be due to the test part?

https://github.com/google/googletest/blob/main/docs/advanced.md#death-tests-and-threads

<img width="892" alt="bug" src="https://github.com/deepmodeling/abacus-develop/assets/141183334/9907c605-bf7d-430d-bcbd-7d45d9f4dc65">

### Expected behavior

Allow me to use openMP to optimize this part 

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by caic99** [comment]
@HaCTang please see #4094
