### ISSUE TITLE
Bug: The search function for online documents is not available.

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#4305]
### Describe the bug

I cannot search something by keyword in online documents.

### Expected behavior

fix it

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@caic99  have you noticed that?

**Comment by caic99** [comment]
@WHUweiqingzhou I'm not able to reproduce that. It works fine for me. Maybe you should check your internet connection?
<img width="794" alt="image" src="https://github.com/deepmodeling/abacus-develop/assets/78061359/319fc876-68a5-421e-b9be-59bf251e79b7">

**Comment by WHUweiqingzhou** [comment]
this issue can be fixed by ctrl+shift+F5.
