### ISSUE TITLE
The doxygen unit test on my branch is not passing

### ISSUE THREAD

**Issue by A-006** [deepmodeling/abacus-develop#4307]
### Details

“After synchronizing the content of my develop branch with the main branch, the doxygen unit test branch did not pass
![img_v3_02bh_3208991f-5a9e-413b-aee8-f0dbe7501d0g](https://github.com/deepmodeling/abacus-develop/assets/74701833/6c9824b0-4c91-42d5-b93b-9774098e8b71)
![img_v3_02bh_5633f393-2fdb-458d-9b20-eeb2d434d2eg](https://github.com/deepmodeling/abacus-develop/assets/74701833/571292af-1243-4042-90f1-89798be719e5)

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by jinzx10** [comment]
Hi @A-006 , sorry that it was my recent PR that causes the error. The doxygen workflow is a github action that deploys doxygen documentation to the github pages of your repo. I notice that your repo has github action activated, but github pages disabled, thereby causing the error.

There are various solutions to this issue. One solution as given by #4306 is to restrict the workflow such that only the deepmodeling repo will trigger the workflow. I believe the "Doxygen Documentation Deployment" entry will disappear once that PR is merged. Another solution, if you would like to have doxygen deployed as a github page of your own repo, is to enable the github pages for your own repo. As such, I believe the "Doxygen Documentation Deployment" will pass on your next push.
