### ISSUE TITLE
Compile too slowly and have a lot of redundant warnings.

### ISSUE THREAD

**Issue by grysgreat** [deepmodeling/abacus-develop#4308]
### Describe the bug

When I compile the GPU version, the file plain_mixing.h causes a lot of warnings and causes the compilation progress to stay stuck (10 minutes in total, the file is stuck for about 5 minutes).

My compile instructions are as follows:
`cmake -B build -DUSE_CUDA=1 -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc`
`cmake --build build -j128`

### Expected behavior

![image](https://github.com/deepmodeling/abacus-develop/assets/57103981/82ce1fdb-9c88-4946-8fd2-7075141c4126)
![image](https://github.com/deepmodeling/abacus-develop/assets/57103981/ee1563a9-9009-48ee-97f7-8fc5a2bd68a4)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by caic99** [comment]
@Qianruipku Would you take a look?

**Comment by yizeyi18** [comment]
ABACUS is big and may take long to compile; usually, warning would not affect the speed of compile. Maybe reducing parallel processes number to number of logical threds could help a little?

If this warning really affects, it worths a try to delete some lines in `mixing.h`:
```patch
diff --git a/abacus-develop/source/module_base/module_mixing/mixing.h b/abacus-develop/source/module_base/module_mixing/mixing_edited.h
index ba0226e..5bc2447 100644
--- a/abacus-develop/source/module_base/module_mixing/mixing.h
+++ b/abacus-develop/source/module_base/module_mixing/mixing_edited.h
@@ -61,27 +61,6 @@ class Mixing
         const bool& need_calcoef)
         = 0;

-    /**
-     * @brief
-     *
-     * @param mdata store information of this iterative step
-     * @param data_in x_in
-     * @param data_out x_out = f(x_in)
-     * @param screen pointer to the screen function for Ker-Ker mixing
-     * @param need_calcoef whether need to calculate the coef
-     *
-     */
-    virtual void push_data(Mixing_Data& mdata,
-                           const double* data_in,
-                           const double* data_out,
-                           std::function<void(double*)> screen,
-                           const bool& need_calcoef);
-    virtual void push_data(Mixing_Data& mdata,
-                           const std::complex<double>* data_in,
-                           const std::complex<double>* data_out,
-                           std::function<void(std::complex<double>*)> screen,
-                           const bool& need_calcoef);
-
     /**
      * @brief calculate coeficients for mixing
      *
```

The function have 4 overrides: residual or no-residual, complex or real; for all 3 derived classes: `Broyden_Mixing`, `Pulay_Mixing` and `Plain_Mixing`, only the 2 residual overrides are implemented. As `plain_mixing.h` is included by `source/module_elecstate/module_charge/charge_mixing.h` which is referred very much(by `dftu.h`, etc.), the warning appears a lot.

**Comment by Qianruipku** [comment]
This would not affect the speed. This is just a reminder for developers, the inherited class partially overrides the push_data, and partially does not. My GCC version is 9.4.0, and I did not encounter this error. You can use "cmake --build build -j1" to see which file the compilation is stuck on.

**Comment by grysgreat** [comment]
Thanks, that solves my mystery.
