### ISSUE TITLE
Numerical atomic orbitals for Ti_ONCV_PBE-1.0.upf including unoccupied bands as reference

### ISSUE THREAD

**Issue by chenjunh** [deepmodeling/abacus-develop#4311]
### Details

I am benchmarking DOS from the calculation of the TiO2 unit cell with one excess electron, using DFT+U and nspin=1. I found that the conduction band structure is quite different from the reference results: my results show that the conduction band overlaps with the fermi level whereas the reference results show that the conduction band is about 0.5 ev away from the fermi level. I was wondering whether I could get a larger numerical orbital basis set (from currently used DZP basis to TZDP basis) to improve the conduction band quality (I hope).

The results I describe above are shown below:
fig. 1: my ABACUS results (TiO2 unit cell, 4x4x4 k points sampling, DFT+U with U=4 ev (different U values were explored based on the same relaxed structure and I found no big difference), nspin=1)
![DOS_ABACUS](https://github.com/deepmodeling/abacus-develop/assets/65362682/83bc4841-86b5-47ca-8a8b-5fad2dfb60cb)

fig. 2:  Reference's VASP results (TiO2 2x2x3 super cell, 4x4x4 k points sampling, DFT+U with  U=4 ev)
![DOS_VASP](https://github.com/deepmodeling/abacus-develop/assets/65362682/eacddadd-5bfd-436f-ae19-36659650a1ce)

Thanks,
Junhan

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by WHUweiqingzhou** [comment]
@kirk0830,
could you have a look?

**Comment by kirk0830** [comment]
Here, these orbitals are generated taking equal number of unoccupied bands as those occupieds as reference states:
[Ti_ONCV_PBE-1.0.upf.fullbands.zip](https://github.com/user-attachments/files/15574559/Ti_ONCV_PBE-1.0.upf.fullbands.zip)
