### ISSUE TITLE
The stress and force programs of SDFT and KSDFT can be unified.

### ISSUE THREAD

**Issue by Qianruipku** [deepmodeling/abacus-develop#4314]
### Describe the Code Quality Issue

Many of the codes in sto_stress_kin, sto_stress_nl, cal_sto_force_nl and stress_kin, sto_stress, cal_force_nl are repetitive and can be merged and simplified.
The differences are: 
|  | sdft         | ksdft     |
|----|--------------|------------|
| 1. | stowf.shchi->| psi_in->   |
| 2. | wk[ik]       | wg(ib,ik)  |

We might control the usage of psi_in or stowf.shchi, and whether to use wg(ib,ik) or wk[ik] for computing KSDFT or SDFT.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by dyzheng** [comment]
@Qianruipku hello, since #4047 has been merged and the new assisted functions: `cal_becp`, `cal_dbecp_f`, `cal_dbecp_s` to calculate force and stress. 

`wk` or `wg` can be passed into these functions to refactor code in SDFT quickly.

@Qianruipku Would you like to try to refactor SDFT code?
