### ISSUE TITLE
Feature: update LibComm to the latest version

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#4315]
### Background

Using latest version of LibComm can fix #4310 and #3674.

### Describe the solution you'd like

update LibComm

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by WHUweiqingzhou** [comment]
@caic99 how to update the link of LibComm?

**Comment by caic99** [comment]
@WHUweiqingzhou Please try `git submodule update --remote --rebase`, since LibComm is a git submodule.

**Comment by caic99** [comment]
@WHUweiqingzhou Any trouble here?

**Comment by WHUweiqingzhou** [comment]
This update has been done.
