### ISSUE TITLE
Test: our CICD auto test workflow does not work fully as expected

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#4335]
### Describe the Testing Issue

see Action: https://github.com/deepmodeling/abacus-develop/actions/runs/9412701654/job/25928061867?pr=4324
The cell_parallel_kpoints_test also failed but in the summary it was like:
```

99% tests passed, 1 tests failed out of 296

Total Test time (real) = 2292.92 sec

The following tests FAILED:
	 78 - cell_klist_test (Subprocess aborted)
Errors while running CTest
Output from these tests are in: /__w/abacus-develop/abacus-develop/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
gmake: *** [Makefile:71: test] Error 8
```

see Action: https://github.com/deepmodeling/abacus-develop/actions/runs/10001403608/job/27644946382?pr=4733
At least two unittests exit with code 0 but actually not work as expected:
```
190/301 Test #190: hontainer_para_test ...............   Passed    2.16 sec
test 191
        Start 191: hcontainer_output_test
191: Test command: /__w/abacus-develop/abacus-develop/build/source/module_hamilt_lcao/module_hcontainer/test/hcontainer_output_test
191: Test timeout computed to be: 1700
191: Running main() from ./googletest/src/gtest_main.cc
191: [==========] Running 1 test from 1 test suite.
191: [----------] Global test environment set-up.
191: [----------] 1 test from OutputHContainerTest
191: [ RUN      ] OutputHContainerTest.Write
191/301 Test #191: hcontainer_output_test ............   Passed    0.67 sec
test 192
        Start 192: hcontainer_readCSR_test
192: Test command: /__w/abacus-develop/abacus-develop/build/source/module_hamilt_lcao/module_hcontainer/test/hcontainer_readCSR_test
192: Test timeout computed to be: 1700
192: Running main() from ./googletest/src/gtest_main.cc
192: [==========] Running 1 test from 1 test suite.
192: [----------] Global test environment set-up.
192: [----------] 1 test from ReadHContainerTest
192: [ RUN      ] ReadHContainerTest.ReadAndOutputHContainer
192:  
192:  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
192:                          NOTICE                           
192:  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
192:  
192:  row or col index out of range
192:  CHECK IN FILE : warning.log
192:  
192:  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
192:                          NOTICE                           
192:  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
192: TIME STATISTICS
192: -----------------------------------------------------
192:  CLASS_NAME    NAME    TIME/s  CALLS   AVG/s  PER/%  
192: -----------------------------------------------------
192:             total      0.00   1        0.00   -nan   
192: -----------------------------------------------------
192: 
192:  See output information in : 
192/301 Test #192: hcontainer_readCSR_test ...........   Passed    0.74 sec
test 193
        Start 193: deltaspin_parse_json_test
193: Test command: /__w/abacus-develop/abacus-develop/build/source/module_hamilt_lcao/module_deltaspin/test/deltaspin_parse_json_test
193: Test timeout computed to be: 1700
```
not any `[   OK        ]` appears.
It may because the `exit(0)` used in WARNING_QUIT function.

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by caic99** [comment]
https://github.com/deepmodeling/abacus-develop/blob/332c875f328f3da8975059d4c79114f2ec5ba737/source/module_cell/test/parallel_kpoints_test.sh#L1-L2
should use `set -e` here, since the script is executed as https://github.com/deepmodeling/abacus-develop/blob/332c875f328f3da8975059d4c79114f2ec5ba737/source/module_cell/test/CMakeLists.txt#L96

**Comment by caic99** [comment]
[The error](https://github.com/deepmodeling/abacus-develop/actions/runs/9366154081/job/25782940730#step:6:6991) you proposed is introduced by #4289 ([previous run](https://github.com/deepmodeling/abacus-develop/actions/runs/9368375648/job/25790249913#step:6:6676) is OK).
@dyzheng @mohanchen Any suggestions?

**Comment by dyzheng** [comment]
@jwsyzy hello, can you look at this Issue?

**Comment by WHUweiqingzhou** [comment]
@mohanchen could you have a look?

**Comment by pxlxingliang** [comment]
After PR #5556 , the CICD will be failed when ABACUS abnormal exit

**Comment by caic99** [comment]
> After PR [#5556](https://github.com/deepmodeling/abacus-develop/pull/5556) , the CICD will be failed when ABACUS abnormal exit

@pxlxingliang Please check if the integrating test could capture the error.
