### ISSUE TITLE
Feature `out_dm` should be deleted, and rename `out_dm1` to `out_dm`. Also feature of `init_dm` is needed.

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#4368]
### Background

In ABACUS, `out_dm` feature only support gamma-only calculation, and only density matrix of gamma_point will be outputted as dense matrix, which is useless now.

I suggest to modify this feature to output real space density matrix (DMR) with non-zero matrix elements as CSR format (the feature of `out_dm1`). 

Feature of `init_dm` for reading DMR file to restart SCF calculation is also needed. 

### Describe the solution you'd like

1. delete code of `out_dm`.
2. refactor code of `out_dm1`, use DensityMatrix::DMR to print CSR format file but not current code.
3. add feature of `init_dm`.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by pxlxingliang** [comment]
I will refactor the interface of out_dm by using DensityMatrix.DMK instead of loc.DM
