### ISSUE TITLE
ERROR! Current core has no plane waves! Please reduce the cores

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#4369]
### Describe the bug

I run this case with `mpirun -np 16` and in running_relax.log I get:
```
 PARALLEL PW FOR WAVE FUNCTIONS
     PROC   COLUMNS(POT)             PW
        1              4             24
        2              4             24
        3              4             24
        4              5             24
        5              4             24
        6              4             24
        7              4             24
        8              5             25
        9              5             25
       10              5             24
       11              5             24
       12              4             23
       13              4             23
       14              4             23
       15              4             23
       16              4             23
 --------------- sum -------------------
       16             69            381
```
but error pops on screen that:
```
 ELEMENT NATOM       XC          
 H       1           
 ---------------------------------------------------------
 Initial plane wave basis and FFT box
 ---------------------------------------------------------
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 ERROR! Current core has no plane waves! Please reduce the cores.
 CHECK IN FILE : OUT.ABACUS/warning.log
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
why?
[caa615af-df28-400c-aec9-b0dc7d772b58.zip](https://github.com/user-attachments/files/15815373/caa615af-df28-400c-aec9-b0dc7d772b58.zip)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by YuLiu98** [comment]
I cannot get your results. On my workstation, I get the following results.
[yuliu_test.tar.gz](https://github.com/user-attachments/files/15839350/yuliu_test.tar.gz)


The error reports from here:
```
void PW_Basis_K::setupIndGk()
{
    //count npwk
    this->npwk_max = 0;
    delete[] this->npwk; this->npwk = new int [this->nks];
    for (int ik = 0; ik < this->nks; ik++)
    {
        int ng = 0;
        for (int ig = 0; ig < this->npw ; ig++)
        {
            const double gk2 = this->cal_GplusK_cartesian(ik, ig).norm2();       
            if (gk2 <= this->gk_ecut)
            {
                ++ng;
            }
        }
        this->npwk[ik] = ng;
        GlobalV::ofs_running << " cpu = " << GlobalV::MY_RANK << "  npw = " << ng << std::endl;
        ModuleBase::CHECK_WARNING_QUIT((ng == 0), "pw_basis_k.cpp", "Current core has no plane waves! Please reduce the cores.");
        if ( this->npwk_max < ng)
        {
            this->npwk_max = ng;
        }
    }
```

I output `npw` on each core, and npw is 0 in the 15th core;
```
 cpu = 14  npw = 2
 cpu = 14  npw = 2
 cpu = 14  npw = 2
 cpu = 14  npw = 2
 cpu = 14  npw = 0
 ERROR! CHECK IN FILE : OUT.ABACUS/warning.log
 ```
 
 Actually, the error info has been printed in the OUT.ABACUS/warning.log:
 ```
 ERROR! pw_basis_k.cpp, core 15: Current core has no plane waves! Please reduce the cores.
 ```

**Comment by kirk0830** [comment]
> I cannot get your results. On my workstation, I get the following results. [yuliu_test.tar.gz](https://github.com/user-attachments/files/15839350/yuliu_test.tar.gz)
> 
> The error reports from here:
> 
> ```
> void PW_Basis_K::setupIndGk()
> {
>     //count npwk
>     this->npwk_max = 0;
>     delete[] this->npwk; this->npwk = new int [this->nks];
>     for (int ik = 0; ik < this->nks; ik++)
>     {
>         int ng = 0;
>         for (int ig = 0; ig < this->npw ; ig++)
>         {
>             const double gk2 = this->cal_GplusK_cartesian(ik, ig).norm2();       
>             if (gk2 <= this->gk_ecut)
>             {
>                 ++ng;
>             }
>         }
>         this->npwk[ik] = ng;
>         GlobalV::ofs_running << " cpu = " << GlobalV::MY_RANK << "  npw = " << ng << std::endl;
>         ModuleBase::CHECK_WARNING_QUIT((ng == 0), "pw_basis_k.cpp", "Current core has no plane waves! Please reduce the cores.");
>         if ( this->npwk_max < ng)
>         {
>             this->npwk_max = ng;
>         }
>     }
> ```
> 
> I output `npw` on each core, and npw is 0 in the 15th core;
> 
> ```
>  cpu = 14  npw = 2
>  cpu = 14  npw = 2
>  cpu = 14  npw = 2
>  cpu = 14  npw = 2
>  cpu = 14  npw = 0
>  ERROR! CHECK IN FILE : OUT.ABACUS/warning.log
> ```
> 
> Actually, the error info has been printed in the OUT.ABACUS/warning.log:
> 
> ```
> ERROR! pw_basis_k.cpp, core 15: Current core has no plane waves! Please reduce the cores.
> ```

Thanks, so seems there are really few planewaves. But I wonder what your suggestion will be, lower the number of processors to use? I am not sure if it should be the obligation of user to ensure all processors to have non-zero number of PWs.

**Comment by YuLiu98** [comment]
> > I cannot get your results. On my workstation, I get the following results. [yuliu_test.tar.gz](https://github.com/user-attachments/files/15839350/yuliu_test.tar.gz)
> > The error reports from here:
> > ```
> > void PW_Basis_K::setupIndGk()
> > {
> >     //count npwk
> >     this->npwk_max = 0;
> >     delete[] this->npwk; this->npwk = new int [this->nks];
> >     for (int ik = 0; ik < this->nks; ik++)
> >     {
> >         int ng = 0;
> >         for (int ig = 0; ig < this->npw ; ig++)
> >         {
> >             const double gk2 = this->cal_GplusK_cartesian(ik, ig).norm2();       
> >             if (gk2 <= this->gk_ecut)
> >             {
> >                 ++ng;
> >             }
> >         }
> >         this->npwk[ik] = ng;
> >         GlobalV::ofs_running << " cpu = " << GlobalV::MY_RANK << "  npw = " << ng << std::endl;
> >         ModuleBase::CHECK_WARNING_QUIT((ng == 0), "pw_basis_k.cpp", "Current core has no plane waves! Please reduce the cores.");
> >         if ( this->npwk_max < ng)
> >         {
> >             this->npwk_max = ng;
> >         }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I output `npw` on each core, and npw is 0 in the 15th core;
> > ```
> >  cpu = 14  npw = 2
> >  cpu = 14  npw = 2
> >  cpu = 14  npw = 2
> >  cpu = 14  npw = 2
> >  cpu = 14  npw = 0
> >  ERROR! CHECK IN FILE : OUT.ABACUS/warning.log
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Actually, the error info has been printed in the OUT.ABACUS/warning.log:
> > ```
> > ERROR! pw_basis_k.cpp, core 15: Current core has no plane waves! Please reduce the cores.
> > ```
> 
> Thanks, so seems there are really few planewaves. But I wonder what your suggestion will be, lower the number of processors to use? I am not sure if it should be the obligation of user to ensure all processors to have non-zero number of PWs.

Yes, users should use fewer cores in this case; since there is only one atom, there is no need to use 16 cores.

The error report here can guide users to reduce cores.
