### ISSUE TITLE
There is a conflict between the `symmetry` and `lspinorb` settings.

### ISSUE THREAD

**Issue by RenguangLiu** [deepmodeling/abacus-develop#4372]
### Describe the bug

If I open the SOC with `lspinorb  1` and open the time symmetry by setting the `symmetry 0`, it should be incorrect and automatically change the symmetry into -1, or refuse to continue the SCF calculation.

Example of a correct INPUT settings:

```
INPUT_PARAMETERS
suffix                          ABACUS
calculation                     scf
ecutwfc                         100
scf_thr                         1.0e-6
scf_nmax                        200
out_chg                         0
smearing_method                 gauss
smearing_sigma                  0.01
mixing_type                     broyden
mixing_ndim                     10
mixing_beta                     0.4
mixing_beta_mag			0.8
mixing_gg0_mag                  0
ks_solver                       genelpa
basis_type                      lcao
symmetry                        -1
noncolin			1
lspinorb			1
nspin                           4
out_mul                         true
kspacing			0.13
```

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
see #4365
