### ISSUE TITLE
Issue with reading LCAO coefficients due to output filename change

### ISSUE THREAD

**Issue by AsTonyshment** [deepmodeling/abacus-develop#4385]
### Describe the Code Quality Issue

When the ABACUS has `out_wfc_lcao` set to `true`, it outputs the LCAO coefficients. However, a recent change in the naming convention of the output files from `LOWF_GAMMA_S1.txt` to `WFC_NAO_GAMMA1.txt` has caused an issue. The software is unable to read the old filenames correctly and does not provide any error messages, which leaves users updating to the new version unable to pinpoint the problem. 

To resolve this, an error message should be implemented to notify users when the expected LCAO coefficients files cannot be read, ensuring they are aware of the filename change and can adjust accordingly.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by kirk0830** [comment]
Hi, are you working on relevant function like "restart wavefunction from file"? I mean if it is from LOWF.
Currently seems there is no user uses this, and... yes I indeed find there is an interesting code piece in function like LOWF::allocate_k:
```c++
        for (int ik = 0; ik < nkstot; ++ik)
        {
            std::complex<double>** ctot;
            this->error = ModuleIO::read_wfc_nao_complex(ctot, ik, GlobalV::NB2D, GlobalV::NBANDS, GlobalV::NLOCAL, 
                                    GlobalV::global_readin_dir, kvec_c[ik], this->ParaV, psi, pelec);
#ifdef __MPI
            Parallel_Common::bcast_int(this->error);
#endif
            switch (this->error)
            {
            case 1:
                std::cout << "Can't find the wave function file: WFC_NAO_K" << ik + 1 << ".txt" << std::endl;
                break;
            case 2:
                std::cout << "In wave function file, band number doesn't match" << std::endl;
                break;
            case 3:
                std::cout << "In wave function file, nlocal doesn't match" << std::endl;
                break;
            case 4:
                std::cout << "In k-dependent wave function file, k point is not correct" << std::endl;
                break;
            default:
                std::cout << " Successfully read in wave functions " << ik + 1 << std::endl;
            }
            if (this->error)
            {
                std::cout << "WARNING: Failed to read in wavefunction, use default initialization instead." << std::endl;
                break;
            }
        }
    }
```
So it means although the code lists like 1, 2, 3, 4, which is really unusual but still will crash without any information?
Or if abacus turns to initial guess rather than crash, it is somehow expected...

**Comment by AsTonyshment** [comment]
@kirk0830 In fact, I discovered this bug while using `get_pchg` to calculate band decomposed charge density. After updating to the latest version yesterday, the original `LOWF` coefficient files became invalid. ABACUS did not generate any error messages and completed the run, defaulting all read-in coefficients to zero. 

I'm not entirely sure if this issue is related to the code you mentioned. It might require a more thorough investigation to determine the connection.

**Comment by AsTonyshment** [comment]
OK, I found an error message in `warning.log` saying

> Can't open file:.//WFC_NAO_GAMMA1.txt

This issue will be closed.
