### ISSUE TITLE
ABACUS relaxation error on HPC platform

### ISSUE THREAD

**Issue by Liu-RX** [deepmodeling/abacus-develop#440]
## Describe the Bug
I bumped into this error when I was testing abacus 2.2.0 beta relax on Beijixing HPC. The bug can be repeatedly performed on cn-large nodes, but on cn_nl nodes everything works fine. I don't know what happens on cn-large nodes. 

## To Reproduce
1. Clone the source code from abacus_2.2.0_beta branch.
2. Build ABACUS with Makefile and Intel 2019 compiler.
4. Run ABACUS.

## Environment
- OS: CentOS Linux release 7.6.1810
- Compiler: Intel 2019
- Optional Dependencies: Intel MKL

## Additional Contex
![屏幕快照 2021-11-07 下午2 36 24](https://user-images.githubusercontent.com/75369672/140636602-24f5eed2-708e-4960-9961-18afd37c018f.png)
Info in out file.
![屏幕快照 2021-11-07 下午2 37 10](https://user-images.githubusercontent.com/75369672/140636611-069dc3be-b38f-4d73-8506-7e00ef16fb4d.png)
Info in warning.log file.

**Comment by caic99** [comment]
How do you run the program? More concisely, under which `mpi` environment?

**Comment by Liu-RX** [comment]
> How do you run the program? More concisely, under which `mpi` environment?

I ran the program with 2019 Intel mpirun, as same as the compilers.

**Comment by caic99** [comment]
Did you compile and run the program on the same platform?

**Comment by Liu-RX** [comment]
> Did you compile and run the program on the same platform?

Yes. The only difference is that I compiled it on login node and ran the program on computation node. But one kind of nodes works while another kind of nodes does not.

**Comment by caic99** [comment]
> > Did you compile and run the program on the same platform?
> 
> Yes. The only difference is that I compiled it on login node and ran the program on computation node. But one kind of nodes works while another kind of nodes does not.

And that's the problem: the targeted platform differs from your compiled verion.
Recompile with a designated [architecture flag](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html) matching that of the computation node, or just compile and run on it.

**Comment by dyzheng** [comment]
Did this problem solved? Can we close this issue?
