### ISSUE TITLE
Update HPSEPS solver

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#441]
## Background
There are three matrix solver in ABACUS lcao code: (parameter: ks_solver)
1. scalapack_gvx, seems good now, no extra installation request.
2. genelpa, most efficient, not robust enough for small systems, not convenience for installing.
3. hpseps, only suitable for gamma_only=0, need to update to the latest version. 

## Describe the solution you'd like
We plan to keep working with Dr. Zhao's group to update our HPSEPS interface.

## Additional context
We need to do:
1. figure out the reason that why gamma_only=1 with HPSEPS solver can't work now;
2. test the latest HPSEPS interface to know which input and output format we need to prepare;
3. unified interface for three solver in ABACUS code.

**Comment by caic99** [comment]
See #679 .
