### ISSUE TITLE
When performing relaxation calculations using single precision, the GPU memory usage keeps increasing

### ISSUE THREAD

**Issue by kogareru1z** [deepmodeling/abacus-develop#4411]
### Describe the bug

When using the RTX 4090 for single precision calculations, the GPU memory usage increases continuously with each iteration, eventually leading to an out-of-memory error. However, this issue does not occur when using double precision.
[test.zip](https://github.com/user-attachments/files/15862165/test.zip)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@denghuilu and @haozhihan, could you have a look?

**Comment by kogareru1z** [comment]
Is there any solution?
