### ISSUE TITLE
Grid integral

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#442]
## Describe Current Status and Possible Solution

Grid integral module in ABACUS need to be optimized for:
1. it cost so much memory for large systems that more than 32G memory used for GaAs_512_system
2. the parallel method for this module now is just along z axis, it is not very smart.
3. we should unify the interface for this module.

**Comment by dyzheng** [comment]
Related issue is #390

**Comment by mohanchen** [comment]
We will start building a new module to perform the grid integrals soon!

**Comment by Liu-RX** [comment]
Roger that!

**Comment by wenfei-li** [comment]
The unification of interface has been achieved; the other two issues still awaits addressing.
