### ISSUE TITLE
Bug: clang-tidy and clang-format do not work

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#4422]
### Describe the bug

Recent PRs do not trigger pre-commit.

### Expected behavior

fix it

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@haozhihan could you have a look?

**Comment by haozhihan** [comment]
> @haozhihan could you have a look?

[OK]

**Comment by WHUweiqingzhou** [comment]
FYI
![image](https://github.com/deepmodeling/abacus-develop/assets/33364058/8aaab8f6-3bd7-4016-b1ae-7e5a6d874510)

**Comment by haozhihan** [comment]
Sorry, I have no idea. 

@caic99 can you have a look?

**Comment by caic99** [comment]
Consequence of #4383
