### ISSUE TITLE
Abnormal Point defect formation energy predicted via ABACUS

### ISSUE THREAD

**Issue by ZLI-afk** [deepmodeling/abacus-develop#4429]
### Describe the bug

I was trying to calculate vacancy formation energy (en_vac - en_ref) with ABACUS, but got **unexpected large** value up to thousands of eV which is abnormal for point defect formation energy.

I reproduce the calculation with `SCF` of `VASP` for the comparasion and reference. All the calculations are `SCF` with same input structure.

May I know what the issue is and how I could fix this.

1. **ABACUS**: 
- ref_state: [relax_abacus.zip](https://github.com/user-attachments/files/15884933/relax_abacus.zip) (Final_en: -1067.66 eV)

- vacancy_stru: [vacancy_abacus.zip](https://github.com/user-attachments/files/15884959/vacancy_abacus.zip) (Final_en: -7499.41 eV)

2. **VASP**:
- ref_state:  [relax_vasp.zip](https://github.com/user-attachments/files/15885165/relax_vasp.zip) (Final_en: -6.45 eV)
- vacancy_stru: [vacancy_vasp.zip](https://github.com/user-attachments/files/15885186/vacancy_vasp.zip) (Final_en: -45.07 eV)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by dyzheng** [comment]
It seems result from ABACUS is same as VASP.
Does this Issue can be closed?

**Comment by ZLI-afk** [comment]
Yes, thanks for your help

**Comment by ZLI-afk** [comment]
> It seems result from ABACUS is same as VASP. Does this Issue can be closed?

Thanks for your help. I have closed this issue
