### ISSUE TITLE
Compiling error with `DEBUG_INFO=ON`

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#4431]
### Describe the bug

![image](https://github.com/deepmodeling/abacus-develop/assets/49852742/b01adc3c-bfcc-4994-b9d0-dfc547e19c07)

from #4331 by @kirk0830 

![image](https://github.com/deepmodeling/abacus-develop/assets/49852742/859a57d0-c76f-475f-8306-fba93a613524)

from #4243  by @DylanWRh

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by kirk0830** [comment]
Oops, sorry I was messed up with nlocal and nbasis...I will fix it ASAP.
but during compilation, I also get this:
```
In file included from /root/abacus-develop/representation/source/module_hamilt_lcao/module_hcontainer/atom_pair.cpp:1:
/root/abacus-develop/representation/source/module_hamilt_lcao/module_hcontainer/atom_pair.h: In instantiation of ‘size_t hamilt::AtomPair<T>::get_R_size() const [with T = double; size_t = long unsigned int]’:
/root/abacus-develop/representation/source/module_hamilt_lcao/module_hcontainer/atom_pair.cpp:866:16:   required from here
/root/abacus-develop/representation/source/module_hamilt_lcao/module_hcontainer/atom_pair.h:279:15: error: ‘assert’ was not declared in this scope
  279 |         assert(this->R_index.size() == this->values.size());
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/abacus-develop/representation/source/module_hamilt_lcao/module_hcontainer/atom_pair.h:11:1: note: ‘assert’ is defined in header ‘<cassert>’; did you forget to ‘#include <cassert>’?
   10 | #include <complex>
  +++ |+#include <cassert>
   11 | #include <tuple>
/root/abacus-develop/representation/source/module_hamilt_lcao/module_hcontainer/atom_pair.h: In instantiation of ‘size_t hamilt::AtomPair<T>::get_R_size() const [with T = std::complex<double>; size_t = long unsigned int]’:
/root/abacus-develop/representation/source/module_hamilt_lcao/module_hcontainer/atom_pair.cpp:867:16:   required from here
/root/abacus-develop/representation/source/module_hamilt_lcao/module_hcontainer/atom_pair.h:279:15: error: ‘assert’ was not declared in this scope
  279 |         assert(this->R_index.size() == this->values.size());
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/abacus-develop/representation/source/module_hamilt_lcao/module_hcontainer/atom_pair.h:279:15: note: ‘assert’ is defined in header ‘<cassert>’; did you forget to ‘#include <cassert>’?
```
Can you also update this to this issue?

**Comment by DylanWRh** [comment]
Simply add `#include <cassert>` in `atom_pair.h` should work. Sry for my oversight regarding the header.
