### ISSUE TITLE
NO STRU_ION_1 file output when i use `out_stru 1` in cell-relax or relax calculation

### ISSUE THREAD

**Issue by xdzhu** [deepmodeling/abacus-develop#4435]
### Describe the bug

NO STRU_ION_1 file output when i use `out_stru 1` in cell-relax or relax calculation. There is only the STRU_ION_D file updated in every relax step. You can easily reproduce it in latest version of abacus.

### Expected behavior

STRU_ION_1 STRU_ION_2 STRU_ION_3 STRU_ION_4 STRU_ION_5 like it was before.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@pxlxingliang and @hongriTianqi could you have a look?
