### ISSUE TITLE
large amount of irrelevant GPU memory allocation was observed when running GPU LCAO.

### ISSUE THREAD

**Issue by goodchong** [deepmodeling/abacus-develop#4442]
### Describe the bug

when I run a case with:
cal_force  1
cal_stress 1
ks_solver cusolver
device gpu
gamma_only 1

I observed some cudamalloc during program init with NO relevant calculations were found.
In my case, about 244 C atoms, max gpu mem usage is about 3.84GB and 1.34 GB doesn't look right.

For example but not limited to:

![微信截图_20240619211715](https://github.com/deepmodeling/abacus-develop/assets/3149059/5aafdf37-0b0b-41bb-a1b7-ee24d040d78d)

![微信截图_20240619211646](https://github.com/deepmodeling/abacus-develop/assets/3149059/53ab31c9-0361-43a2-b3c4-d3b0aa4ab7be)

![微信截图_20240619211618](https://github.com/deepmodeling/abacus-develop/assets/3149059/2b128538-03f4-4106-9738-7d267d54478f)

![微信截图_20240619211548](https://github.com/deepmodeling/abacus-develop/assets/3149059/6a837931-0aec-42eb-a760-34cbf83cfbb1)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@goodchong  any plan?
