### ISSUE TITLE
diffierent output between v3.5.1(gnu) v3.6.5(intel)

### ISSUE THREAD

**Issue by lgjsws** [deepmodeling/abacus-develop#4448]
### Describe the bug

INPUT_PARAMETERS
#Parameters (1.General)
suffix                 ABACUS
calculation            cell-relax
symmetry               1
pseudo_dir             /opt/abacus-develop/pw/SG15_ONCV_v1.0_upf/
orbital_dir            /opt/abacus-develop/orbit/SG15-Version1p0__StandardOrbitals-Version2p0/

#Parameters (2.Iteration)``````
ecutwfc                100
scf_thr                1e-7
scf_nmax               100

#Parameters (3.Basis)
basis_type             lcao
relax_method  cg
ks_solver              genelpa

#Parameters (4.Smearing)
smearing_method        gaussian
smearing_sigma         0.001

#Parameters (5.Mixing)
mixing_type            pulay
mixing_beta            0.2
out_stru 1
cal_stress 1
cal_force 1
md_dumpfreq            1

STRU
ATOMIC_SPECIES
Sn  118.71        Sn_ONCV_PBE-1.0.upf
Te  127.6         Te_ONCV_PBE-1.0.upf

NUMERICAL_ORBITAL
Sn_gga_7au_100Ry_2s2p2d1f.orb
Te_gga_7au_100Ry_2s2p2d1f.orb

LATTICE_CONSTANT
1.889726

LATTICE_VECTORS
9.0108410000      0.0000000000      0.0000000000      
4.5054210000      7.8036160000      0.0000000000      
4.5054200000      2.6012050000      7.3573200000      

ATOMIC_POSITIONS
Direct

Sn
0.0000000000
8
0.0000000000 0.0000000000 0.0000000000 1 1 1 mag 0.0 
0.0000000000 0.0000000000 0.5000000000 1 1 1 mag 0.0 
0.0000000000 0.5000000000 0.0000000000 1 1 1 mag 0.0 
0.0000000000 0.5000000000 0.5000000000 1 1 1 mag 0.0 
0.5000000000 0.0000000000 0.0000000000 1 1 1 mag 0.0 
0.5000000000 0.0000000000 0.5000000000 1 1 1 mag 0.0 
0.5000000000 0.5000000000 0.0000000000 1 1 1 mag 0.0 
0.5000000000 0.5000000000 0.5000000000 1 1 1 mag 0.0 

Te
0.0000000000
8
0.2500000000 0.2500000000 0.2500000000 1 1 1 mag 0.0 
0.2500000000 0.2500000000 0.7500000000 1 1 1 mag 0.0 
0.2500000000 0.7500000000 0.2500000000 1 1 1 mag 0.0 
0.2500000000 0.7500000000 0.7500000000 1 1 1 mag 0.0 
0.7500000000 0.2500000000 0.2500000000 1 1 1 mag 0.0 
0.7500000000 0.2500000000 0.7500000000 1 1 1 mag 0.0 
0.7500000000 0.7500000000 0.2500000000 1 1 1 mag 0.0 
0.7500000000 0.7500000000 0.7500000000 1 1 1 mag 0.0 

the same INPUT and stru work out different output.
"The calculation results of Abacus compiled with GNU version 3.5.1 are normal and converge within a dozen steps. However, Abacus compiled with Intel version 3.6.5 fails to converge and exhibits abnormal energy. The two figures respectively show partial calculation results of Abacus compiled with GNU and Intel versions."

![gnu](https://github.com/deepmodeling/abacus-develop/assets/151837121/600d8634-2364-4ddb-b9e1-6a70c05eef54)
![intel](https://github.com/deepmodeling/abacus-develop/assets/151837121/7954704d-76b3-44c5-a7de-791e509854c6)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by lgjsws** [comment]
![U(D0P4J7V3X~3ACXSSAT$ND](https://github.com/deepmodeling/abacus-develop/assets/151837121/d7fff960-79a8-41d3-9f14-c7c22768c453)
sorry,this is the out put of v3.6.5 abacus

**Comment by WHUweiqingzhou** [comment]
@lgjsws 
Thanks for your feedback. could you upload the input file?

**Comment by lgjsws** [comment]
[INPUT.json](https://github.com/user-attachments/files/15910276/INPUT.json)
@WHUweiqingzhou here is the input file

**Comment by WHUweiqingzhou** [comment]
@lgjsws 
could you upload the input files, including INPUT/KPT/STRU/.upf/.orb, and corresponding output files?

**Comment by lgjsws** [comment]
[OUT.ABACUS(v3.6.5 by intel).zip](https://github.com/user-attachments/files/15910772/OUT.ABACUS.v3.6.5.by.intel.zip)
Due to file size limitations, I deleted OLD_SPIN1_CHG.cube
@WHUweiqingzhou

**Comment by lgjsws** [comment]
After downgrading my version from 3.6.5 to 3.5.1（intel）, the calculation results are still wrong. It seems to be a problem with the Intel compilation?

**Comment by pxlxingliang** [comment]
Hi @lgjsws, the output file "running_cell-relax.log" seems not readable file.
![image](https://github.com/deepmodeling/abacus-develop/assets/91927439/b0cba3bf-bfb8-49a4-ae3c-e40afc061fdf)

I ran this example using the Dockerfile provided in the Abacus code repository to create an image, and the result is normal.
https://github.com/deepmodeling/abacus-develop/blob/develop/Dockerfile.intel
[out.zip](https://github.com/user-attachments/files/16066075/out.zip)

I suspect there may be some issues with the abacus you installed in the Intel environment. Can you provide your installation method?

**Comment by pxlxingliang** [comment]
Long time no update, close it.
