### ISSUE TITLE
ABACUS IO needs keeping updating!

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#445]
## Describe Current Status and Possible Solution

1. Output for LCAO and PW should be unified.
2. All INPUT parameters should output in OUT.suffix/INPUT.
3. Useless output and input should be deleted.
4. Other updates.

Please comment here!

**Comment by pxlxingliang** [comment]
when doing MD, in the screen output, SCF loop has no title.

**Comment by pxlxingliang** [comment]
When doing the relax, the log file will print the STATE ENERGY(eV) AND OCCUPATIONS of all k-points in each ION step, which makes the log file un-readable when k-points are large.
Or we may need an additional file to output the summarization of the key informations like energy, stress, force, time etc.

**Comment by mohanchen** [comment]
@YuLiu98  Could you take a look at this issue and keep me updated?

**Comment by dyzheng** [comment]
When the pseudopotential is LDA, and the orbital file is from PBE pseudopotential file, basis_type = lcao would cause fatal error that "abacus: /root/abacusmodeling/abacus-develop/source/module_orbital/ORB_gen_tables.cpp:142: void ORB_gen_tables::snap_psibeta_half(const LCAO_Orbitals &, const InfoNonlocal &, std::vector<std::vector<double, std::allocator<double>>, std::allocator<std::vector<double, std::allocator<double>>>> &, const ModuleBase::Vector3<double> &, const int &, const int &, const int &, const int &, const ModuleBase::Vector3<double> &, const int &, const bool &) const: Assertion `nproj>0' failed." 

Maybe we should check if information of orbital file is consistant with the pseudopotential file for each element, I think users maybe don't know how to deal with this error.
