### ISSUE TITLE
Failed clang-tidy/clang-format action might break the code

### ISSUE THREAD

**Issue by jinzx10** [deepmodeling/abacus-develop#4454]
### Details

In my recent (draft) PR #4452 , I encountered a weird situation where the integration & unit test failed at its build stage when all build tests are passed:

![image](https://github.com/deepmodeling/abacus-develop/assets/26805483/795bbade-8735-4a93-b449-ea8573920545)
![image](https://github.com/deepmodeling/abacus-develop/assets/26805483/6a01bb39-88a8-4708-90a6-33ab6524ae9e)

After looking into the integration & unit test, I found that the pre-commit action (clang-format & clang-tidy) before the build stage might be the cause, as shown by the error message below:

![image](https://github.com/deepmodeling/abacus-develop/assets/26805483/1e33498d-2715-45e2-8b2d-7e9a8d781f16)
![image](https://github.com/deepmodeling/abacus-develop/assets/26805483/218949f8-39b5-4aff-b106-da6cc3836b4a)
![image](https://github.com/deepmodeling/abacus-develop/assets/26805483/6e1d4c57-a7bd-4222-bd00-5da22d7c32fe)

This is verified on my local PC that, when I pull the latest code (with pre-commit action applied), the same compilation error occurs; but when I checkout out the one just before pre-commit action, the code compiles. The question is, the pre-commit action applies a change of over more than 2000 lines of code, which is difficult to keep track of; and the compilation error seems to be related to the Tensor class in libtorch, which I'm not familiar with. 

While clang-format and clang-tidy work in most situations, I think we still need to apply them carefully, especially when they throw some error message or non-zero exit code.

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by WHUweiqingzhou** [comment]
@haozhihan, @caic99 and @mohanchen,
could you have a look?

**Comment by caic99** [comment]
> @haozhihan, @caic99 and @mohanchen, could you have a look?

Replied under the corresponding PR. I believe this is an existed but hidden bug in ABACUS, and clang-format just unveils it.

**Comment by jinzx10** [comment]
It turns out that including torch's internal headers must obey some order. The code compiles when I change
```cpp
#include "torch/csrc/api/include/torch/linalg.h"
#include "torch/csrc/autograd/autograd.h"
#include "torch/script.h"
```
to
```cpp
#include "torch/script.h"
#include "torch/csrc/api/include/torch/linalg.h"
#include "torch/csrc/autograd/autograd.h"
```
However, as pointed out by @caic99 in the corresponding PR, in order to save the hassel of figuring out the right order, we should probably avoid including any internal headers like torch/csrc/api/include/torch/linalg.h and simply include torch/torch.h instead.

The error code produced by clang-tidy/format seems to be irrelevant to this issue. Nevertheless, I notice that they do appear very frequently, e.g. https://github.com/deepmodeling/abacus-develop/actions/runs/9610410554/job/26506834773

![image](https://github.com/deepmodeling/abacus-develop/assets/26805483/2544d6ca-1ea6-41d9-96d6-954fd1f78fbc)
![image](https://github.com/deepmodeling/abacus-develop/assets/26805483/7d029b30-252c-4091-a7a7-6e7aa4ce7122)

While those non-zero exit codes do not block the workflow, I'm just wondering, are they potentially risky and can we fix them? @caic99

**Comment by jinzx10** [comment]
(The above question is not directly relevant to the present PR and it can be closed if @caic99 has no further comment.

**Comment by caic99** [comment]
> While those non-zero exit codes do not block the workflow, I'm just wondering, are they potentially risky and can we fix them? @caic99

@jinzx10 Installing `libomp` may solve this issue. However, it might have conflict with the GNU toolchain of the environment. I think it is OK to leave it as is.

> are they potentially risky

`clang-format` only format codes which it has confidence to maintain the correctness. So, I don't think it is risky.
