### ISSUE TITLE
Why the charge file .cube still output when i set `out_chg=0`?

### ISSUE THREAD

**Issue by xdzhu** [deepmodeling/abacus-develop#4455]
### Describe the bug

Why the charge file .cube still output when i set `out_chg=0`?  This bug let the relax iteration speed goes slow because it writes charge file after every ION step.
BTW, the `out_stru=1` also failed, NO STRU output in every step, WHY? These params can work well in v3.6.0

INPUT is like:
![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/d734e384-7c84-4942-8124-7d15d78861c3)

I have checked the INPUT has been read:
![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/094ee24b-8c04-42c5-9111-1d51797e8fa6)
![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/3073c560-0c4b-45b0-aba1-05619a6377fb)

However, OUT.ABACUS is like:
![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/e45e5755-778a-4307-bc4f-f67f1d4560e4)

### To Reproduce

[issue-output-flag.zip](https://github.com/user-attachments/files/15916520/issue-output-flag.zip)

VERSION AS BELOW:

                              ABACUS v3.6.5
               Atomic-orbital Based Ab-initio Computation at UStc                    

                     Website: http://abacus.ustc.edu.cn/                             
               Documentation: https://abacus.deepmodeling.com/                       
                  Repository: https://github.com/abacusmodeling/abacus-develop       
                              https://github.com/deepmodeling/abacus-develop         
                      Commit: 854d49c (Mon Jun 10 20:58:55 2024 +0800)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by kirk0830** [comment]
seems these two cube files are for charge extrapolation rather than those dumped from `out_chg` switch. But I remember in the past @YuLiu98 had done something similar to solve this kind problems? 
@YuLiu98 could you have a look if there is any lines of codes left unchanged?

**Comment by YuLiu98** [comment]
> seems these two cube files are for charge extrapolation rather than those dumped from `out_chg` switch. But I remember in the past @YuLiu98 had done something similar to solve this kind problems? @YuLiu98 could you have a look if there is any lines of codes left unchanged?

Indeed, these cube files are utilized for charge extrapolation in molecular dynamics or during relax/cell-relax processes. They are temporary and will be automatically deleted upon the successful completion of the tasks.

**Comment by WHUweiqingzhou** [comment]
@pxlxingliang please double-check it.

**Comment by YuLiu98** [comment]
Now the cube files will not be output and `out_stru` works well in v3.8.0.
