### ISSUE TITLE
support giant basis calculation

### ISSUE THREAD

**Issue by AroundPeking** [deepmodeling/abacus-develop#4458]
### Background

While using jY basis set, ABACUS reported `total_nchi<0 || total_nchi>50`. Please support the giant basis calculation.

### Describe the solution you'd like

Examples are attached here.
[jY.tar.gz](https://github.com/user-attachments/files/15921842/jY.tar.gz)

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by kirk0830** [comment]
@AroundPeking wants to perform calculation on jY basis directly instead using a linearly combined version (say ABACUS conventional numerical atomic orbital). The most difference between these two kinds of calculation is the coefficients of jY in the former case can be fully relaxed during SCF, while for the latter they are bundled together.
I will first support jY basis directly generation on our new orbital generation codes, then remove this restriction.
