### ISSUE TITLE
out_pot does not work for nscf calculations

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#4481]
### Describe the bug

When doing nscf calculations with out_pot set to 1 or 2, no cube containing potential files will be produced in the OUT directory

### Expected behavior

add support of out_pot 2 for nscf calculations

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by hongriTianqi** [comment]
@wenfei-li This issue has been solved.

**Comment by hongriTianqi** [comment]
PR #4517
