### ISSUE TITLE
Had deepks been merged to abacus?

### ISSUE THREAD

**Issue by yufengwhy** [deepmodeling/abacus-develop#449]
## Background
Had deepks been merged to abacus to calculate solid? 
Is there any examples for solid?
what are the labels to train deepks? such as the plane wave for CCSD?

**Comment by dyzheng** [comment]
1. You can use branch deepks to calculate solid.
2. @wenfei-li 
3. Now, only numerical atomic orbitals basis support DeePKS calculation.
