### ISSUE TITLE
Large EDIFF in last scf step suddenly

### ISSUE THREAD

**Issue by Shen-Zhen-Xiong** [deepmodeling/abacus-develop#4505]
### Describe the bug

[large_de.tar.gz](https://github.com/user-attachments/files/16009984/large_de.tar.gz)
In my test case, for last scf step, EDIFF from  6.69311592e-06 jump to 3.53213141e-01 which is unnormal.
GE283    1.6800e+01   2.9235e+01  -4.82564493e+05   7.87996076e-08   2.13498468e-05 364.45
 GE284    1.6800e+01   2.9238e+01  -4.82564493e+05  -3.11050562e-06   2.12412371e-05 364.41
 GE285    1.6800e+01   2.9316e+01  -4.82564493e+05   1.00953583e-05   2.07483494e-05 364.14
 GE286    1.6800e+01   2.9303e+01  -4.82564493e+05  -2.09598047e-05   2.07266596e-05 364.02
 GE287    1.6800e+01   2.9395e+01  -4.82564493e+05  -9.55267053e-06   2.03377062e-05 364.47
 GE288    1.6800e+01   2.9363e+01  -4.82564493e+05  -3.70150267e-06   2.05601797e-05 364.45
 GE289    1.6800e+01   2.9402e+01  -4.82564493e+05  -6.87110800e-06   2.01517282e-05 364.28
 GE290    1.6800e+01   2.9417e+01  -4.82564493e+05  -6.01094494e-07   2.00977701e-05 364.16
 GE291    1.6800e+01   2.9413e+01  -4.82564493e+05  -3.82435483e-06   2.00485653e-05 363.75
 GE292    1.6800e+01   2.9447e+01  -4.82564493e+05   3.19969965e-06   2.02117045e-05 364.06
 GE293    1.6800e+01   2.9424e+01  -4.82564493e+05  -4.66937173e-06   2.02269025e-05 364.26
 GE294    1.6800e+01   2.9480e+01  -4.82564493e+05   1.81912260e-06   2.01544955e-05 364.38
 GE295    1.6800e+01   2.9605e+01  -4.82564493e+05  -2.69545145e-05   1.99719187e-05 364.41
 GE296    1.6800e+01   2.9624e+01  -4.82564493e+05  -1.03393797e-05   2.00034318e-05 364.40
 GE297    1.6800e+01   2.9667e+01  -4.82564493e+05  -4.54493566e-06   2.01031835e-05 364.16
 GE298    1.6800e+01   2.9664e+01  -4.82564493e+05   5.73633425e-06   2.01218804e-05 364.17
 GE299    1.6800e+01   2.9640e+01  -4.82564493e+05   6.69311592e-06   2.01431092e-05 364.44
 GE300    1.6800e+01   2.9608e+01  -4.82564140e+05   3.53213141e-01   2.01885897e-05 364.30
 >> Leave SCF iteration.
 * * * * * *
 !! CONVERGENCE HAS NOT BEEN ACHIEVED !!
TIME STATISTICS

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by pxlxingliang** [comment]
Hi @Shen-Zhen-Xiong, have you ever suffered the similar problem in smaller system? The case you supplied is too large (need about 30 hours to repeat the result) and is hard to debug.

**Comment by WHUweiqingzhou** [comment]
@Shen-Zhen-Xiong,
I would assume that this is because the system does not converge, resulting in the calculation of the energy in the last step using output charge density without mixing, which leads to a significant difference compared to the energy of the previous step based on the mixed charge density.

**Comment by pxlxingliang** [comment]
I have reproduced this problem with gamm_only=1.
I have run two calculations:
run1, set the scf_nmax=2
```
 << Start SCF iteration.
 ITER      TMAG       AMAG        ETOT/eV          EDIFF/eV         DRHO     TIME/s
 GE1      1.68e+01   8.99e+01  -4.82729695e+05   0.00000000e+00   9.0436e-02 155.94
 GE2      1.68e+01   8.99e+01  -4.72450166e+05   1.02795283e+04   8.8833e-02 144.81
 >> Leave SCF iteration.
```

run2, set scf_nmax=3:
```
 * * * * * *
 << Start SCF iteration.
 ITER      TMAG       AMAG        ETOT/eV          EDIFF/eV         DRHO     TIME/s
 GE1      1.68e+01   8.99e+01  -4.82729695e+05   0.00000000e+00   9.0436e-02 160.22
 GE2      1.68e+01   8.99e+01  -4.82625747e+05   1.03948000e+02   8.8833e-02 143.14
 GE3      1.68e+01   2.91e+01  -3.17648329e+06  -2.69385754e+06   3.1059e-01 122.70
 >> Leave SCF iteration.
 * * * * * *
```

As we can see, the energy difference of step 2 in run1 is larger than that in run2, and the energy difference of last step in run2 is also larger than previous steps. This indicate that there may have some bugs in the last SCF step.

**Comment by WHUweiqingzhou** [comment]
@Shen-Zhen-Xiong  
btw, I notice you set `mixing_restart` very low, which is even lower than `scf_thr`. It is wrong usage.

**Comment by pxlxingliang** [comment]
I remove parameter mixing_restart in INPUT, and re-run run1, and this time the energy difference is same as that in run2:
```
 * * * * * *
 << Start SCF iteration.
 ITER      TMAG       AMAG        ETOT/eV          EDIFF/eV         DRHO     TIME/s
 GE1      1.68e+01   8.99e+01  -4.82729695e+05   0.00000000e+00   9.0436e-02 154.95
 GE2      1.68e+01   8.99e+01  -4.82625747e+05   1.03948000e+02   8.8833e-02 146.14
 >> Leave SCF iteration.
 * * * * * *
 * ```

**Comment by Shen-Zhen-Xiong** [comment]
> Hi @Shen-Zhen-Xiong, have you ever suffered the similar problem in smaller system? The case you supplied is too large (need about 30 hours to repeat the result) and is hard to debug.

OK, I have a smaller system. It is a system with Spin Density Wave which need supercell.
[config_9.tar.gz](https://github.com/user-attachments/files/16060645/config_9.tar.gz)

**Comment by Shen-Zhen-Xiong** [comment]
> @Shen-Zhen-Xiong btw, I notice you set `mixing_restart` very low, which is even lower than `scf_thr`. It is wrong usage.

Thank you very much. Actually, I use DFT+U just  want to output local magnetic moment step by step, and only "onsite_radius" is importan for me, and do not want a restart scf, so I set a very small "mixing_restart" value.

**Comment by Shen-Zhen-Xiong** [comment]
> @Shen-Zhen-Xiong, I would assume that this is because the system does not converge, resulting in the calculation of the energy in the last step using output charge density without mixing, which leads to a significant difference compared to the energy of the previous step based on the mixed charge density.

I guess may be some error, especially for last scf step.
