### ISSUE TITLE
GlobalV and INPUT should be refactored.

### ISSUE THREAD

**Issue by Qianruipku** [deepmodeling/abacus-develop#4507]
### Describe the Code Quality Issue

1. GlobalV can be changed as the program is running. It is not good.
2. When add a new input parameter, we need to add some codes at different spaces in ABACUS. It is not good. 
3. Parameter and read_input should be in different classes.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by mohanchen** [comment]
This has been done. Great job!
