### ISSUE TITLE
Cuda building error and warnings

### ISSUE THREAD

**Issue by caic99** [deepmodeling/abacus-develop#4510]
### Describe the bug

Please see [building logs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=964144&view=logs&jobId=517fe804-fa30-5dc2-1413-330699242c05&j=517fe804-fa30-5dc2-1413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412)

```
/home/conda/feedstock_root/build_artifacts/abacus_1719507163903/work/source/module_hamilt_lcao/module_gint/kernels/cuda/gint_force.cu(117): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)
```
This error is generated since cuda arch < 6 does not have `atomicAdd` for double. Maybe should include `device.h`? @haozhihan 

---

```
/home/conda/feedstock_root/build_artifacts/abacus_1719507163903/work/source/module_hamilt_lcao/module_gint/kernels/cuda/interp.cuh(131): warning #607-D: this pragma must immediately precede a statement
/home/conda/feedstock_root/build_artifacts/abacus_1719507163903/work/source/module_hamilt_lcao/module_gint/kernels/cuda/interp.cuh(109): warning #177-D: variable "dist_tmp_stress" was declared but never referenced
```
There are warnings generated for your codes, FYI @A-006 

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by A-006** [comment]
Warnings have been resolved in the latest code, but they haven’t been merged yet. The cuda atomicAdd function does not support double for versions less than 6.0. [CUDA 6 was released in 2014, and nowadays, very few people use versions older than 6.0 for compilation.

**Comment by njzjz** [comment]
There should be a test or a static check for it. I remember this error has appeared several times.
