### ISSUE TITLE
CI: `readability-braces-around-statements` did not work as expected

### ISSUE THREAD

**Issue by haozhihan** [deepmodeling/abacus-develop#4523]
### Describe the Code Quality Issue

https://github.com/deepmodeling/abacus-develop/blob/develop/.clang-tidy#L8

Why didn't `readability-braces-around-statements` work in CI?
 
I verified on my own server that A is working properly.

![image](https://github.com/deepmodeling/abacus-develop/assets/60099470/370ad74d-8025-41f4-bbff-d5dd7136a2a9)

`clang-tidy test.cpp -checks='-*,readability-braces-around-statements' -fix`

![image](https://github.com/deepmodeling/abacus-develop/assets/60099470/dcf48e60-76ba-4075-ab59-ee4e0ba49d8f)

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by caic99** [comment]
@haozhihan Please check the [exact command](https://github.com/deepmodeling/abacus-develop/actions/runs/9692660158/job/26746460002#step:6:57) for clang-tidy.

**Comment by haozhihan** [comment]
https://clang.llvm.org/extra/clang-tidy/checks/readability/braces-around-statements.html

According to [this](https://clang.llvm.org/extra/clang-tidy/checks/list.html), I found that Clang-Tidy Checks does not provide fixes for `readability-braces-around-statements`.

But why can I achieve the effect of fix on my own server, caused by the different versions of clang-tidy?

**Comment by caic99** [comment]
> But why can I achieve the effect of fix on my own server, caused by the different versions of clang-tidy?

@haozhihan Maybe it is a [clang-format feature](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#insertbraces)?

**Comment by haozhihan** [comment]
wow! Great!

Is the clang-format version on our CI machine up to clang-format 15?

@caic99

**Comment by caic99** [comment]
@haozhihan It is installed by `apt`. Please check the commands [here](https://github.com/deepmodeling/abacus-develop/blob/e626c8730d9ae818736d556882925d5f4ccf5054/.github/workflows/test.yml#L26-L29).
The version should be 14 ([ref](https://packages.ubuntu.com/jammy/clang-format)). It is also possible to install it by `pip` for the latest version.

**Comment by haozhihan** [comment]
> @haozhihan It is installed by `apt`. Please check the commands [here](https://github.com/deepmodeling/abacus-develop/blob/e626c8730d9ae818736d556882925d5f4ccf5054/.github/workflows/test.yml#L26-L29). The version should be 14 ([ref](https://packages.ubuntu.com/jammy/clang-format)). It is also possible to install it by `pip` for the latest version.

Should I use `sudo pip install clang-format` instead of the previous download method clang-format? like [this](https://github.com/deepmodeling/abacus-develop/pull/4539/commits/bc8b8771ace6fbfa348d1c8f40a18dd9384e38e9#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R29)

**Comment by caic99** [comment]
> Should I use `sudo pip install clang-format` instead of the previous download method clang-format? like [this](https://github.com/deepmodeling/abacus-develop/pull/4539/commits/bc8b8771ace6fbfa348d1c8f40a18dd9384e38e9#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R29)

It's OK. Don't forget to migrate `clang-tidy`.
