### ISSUE TITLE
Test: test set of 207_NO_KP_OXC in CI is incorrect

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#4531]
### Describe the Testing Issue

In CI test of 207_NO_KP_OXC, the log show the Compare file is error, but the test is passed.

```
1: [ RUN      ] 207_NO_KP_OXC
1: Compare Error: line 1, column 2 
1:  k-1-Vxc.ref: (-1.03906440e+00,-3.28984700e-16)
1:  OUT.autotest/k-1-Vxc: (-1.0392289,-3.6984296e-16)
1: Compare Error: line 4, column 1 
1:  vxc_out.ref: -5.1240042976965061e-01
1:  OUT.autotest/vxc_out: -5.1230909036924088e-01
1: [----------] test for output XC matrix with multipy k-points
1: [      OK  ]  etotref
1: [      OK  ]  etotperatomref
1: [      OK  ]  CompareXC_pass
1: [----------] Time elapsed: 17.365 seconds
```

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by pxlxingliang** [comment]
I have checked the test code:
```
if ! test -z "$has_xc"  && [  $has_xc == 1 ]; then
	if ! test -z "$gamma_only"  && [ $gamma_only == 1 ]; then
			xcref=k-0-Vxc.ref
			xccal=OUT.autotest/k-0-Vxc
	else
			xcref=k-1-Vxc.ref
			xccal=OUT.autotest/k-1-Vxc
	fi
	oeref=vxc_out.ref
	oecal=OUT.autotest/vxc_out
	python3 ../tools/CompareFile.py $xcref $xccal 4
	python3 ../tools/CompareFile.py $oeref $oecal 6
    echo "CompareXC_pass $?" >>$1
fi
```

There are two problems:
1. the codes do two comparation, but only save the test result of final comparation.
2. the output format of k-1-Vxc is different in reference file.

**Comment by pxlxingliang** [comment]
Below tests have the similar problems: 
220_NO_KP_MD_wfc_out
304_NO_GO_AF_atommag,

**Comment by pxlxingliang** [comment]
@WHUweiqingzhou here.

**Comment by WHUweiqingzhou** [comment]
@pxlxingliang and @dyzheng

**Comment by pxlxingliang** [comment]
#4647 and #4700 fix it
