### ISSUE TITLE
Bug: Null appears in `OUT.ABACUS/running.log` induced by #4515

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#4540]
### Describe the bug

At commit 8942b47
I get some null in .log, resulting in some error of CI test 207_NO_KP_OH2.
![image](https://github.com/deepmodeling/abacus-develop/assets/33364058/047059b6-f460-464c-b447-fc671568ccd2)

If I revert f2e4a0d
null disappears.

I have no idea why CI test fails to find it.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by caic99** [comment]
@kirk0830 Looks like there is an excessive trailing '\0' introduced by `format`. Maybe using `table` here could solve the problem?

**Comment by jinzx10** [comment]
After some laborious debugging process with @kirk0830 and @caic99 (and thanks @hongriTianqi for helping set up an environnment where this bug can be persistently reproduced), we found that this bug results from a type mismatch and there's nothing wrong with formatter.h.

Prior to #4515 , ibz2bz was a private member of K_Vectors with type std::vector\<int\>. In #4515 , ibz2bz becomes a local variable initialized on line 776 of klist.cpp with type std::vector\<double\>, which disagrees with its supposed format specifier "%8d" and causes undefined behavior.

**Comment by maki49** [comment]
Sorry, it was my fault. I've fixed it in #4577.
