### ISSUE TITLE
source code compilation on openSUSE leap 15.5 -- config fails with elpa version issue

### ISSUE THREAD

**Issue by tckosvic** [deepmodeling/abacus-develop#4586]
### Describe the bug

openSUSE leap 15.5 has elpa version 2022.11.001 installed.  Configuration of abacus fails saying:

`-- Found ELPA: /usr/lib64/libelpa.so  
-- Performing Test ELPA_VERSION_SATISFIES
-- Performing Test ELPA_VERSION_SATISFIES - Failed
CMake Error at cmake/FindELPA.cmake:96 (message):
  ELPA version is too old.  We support version 2021 or higher.
Call Stack (most recent call first):
  CMakeLists.txt:207 (find_package)

-- Configuring incomplete, errors occurred!
`
Any ideas to help going forward?

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by caic99** [comment]
Hi @tckosvic ,
Would you check the content of `/usr/include/elpa/elpa_version.h`?

**Comment by caic99** [comment]
Closing this issue due to no response. Feel free to re-open it if necessary.
