### ISSUE TITLE
Negative signs in length gague rt-TDDFT

### ISSUE THREAD

**Issue by ESROAMER** [deepmodeling/abacus-develop#4587]
### Describe the bug

There are two sign mistakes in length gague rt-TDDFT:
1.The first one is in the length gague potential：
$V=-qE \cdot r$
For electron, $q=-e$, so it actually should be written as $V=eE \cdot r$ (SI), or $V=E \cdot r$ (au). While in ABACUS code, it was implemented in form $V=-E \cdot r$ (au).

2.The second one is in the output dipole:
$D=\int q\rho (r)rdr$
The problem $q=-e$ also exist here. It actually should be written as $D=-\int e\rho (r)rdr$.

Well , these two negative signs actually do no harm to the result of length gague TDDFT calculation, since the efield oscillates over time and the mistake in dipole calculation was cancelled by the mistake in potential calculation. But if you want to compare the result with velocity gague or other software's tddft, some physical quantities will be completely opposite.
![Figure_1](https://github.com/deepmodeling/abacus-develop/assets/104255052/cdf10e94-4592-4ce5-ba09-afe2bcddfb61)

So I suggest fixing these two negative signs to maintain consistency with other software and velocity gague.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by ESROAMER** [comment]
In addtion, the output electron dipole has large constant term which was supposed to be cancelled by the dipole of ions.
<img width="173" alt="屏幕截图 2024-07-08 105549" src="https://github.com/deepmodeling/abacus-develop/assets/104255052/b4f54a73-8fcc-4709-ab36-c5c3478fb4a3">
I suggest to output dipole_xyz to the output file instead of dipole_elec_xyz. The output file would be much more clear in this way. And be cautious. "dipole_xyz" is not " $dipole_{ion} - dipole_{elec}$ "anymore. Since you have explicitly considered the electron charge, it would be " $dipole_{ion} + dipole_{elec}$ "

**Comment by AsTonyshment** [comment]
Got it, I will fix this very soon.
