### ISSUE TITLE
How to customize the atomic orbitals

### ISSUE THREAD

**Issue by Lonya0** [deepmodeling/abacus-develop#4592]
### Details

I looked through the document of ABACUS and have NOT found a single way to set own atomic orbitals, in 7.2 (of document) it says 'Users may also choose to generate their own atomic obitals.'(a little typeo too) but cannot find how to set own atomic orbitals.

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by kirk0830** [comment]
Noted. 
Later I will provide a hands-on.

**Comment by kirk0830** [comment]
There are, presently three versions of orbital generation code, the v1.0 tutorial can be found here:
https://mcresearch.github.io/abacus-user-guide/abacus-nac2.html
v2.0 can be found here:
https://mcresearch.github.io/abacus-user-guide/abacus-nac3.html
Another, developement v2.1 can be found in my personal repo which is maintained by @jinzx10 and I:
https://github.com/kirk0830/abacus_orbital_generation
, you can follow the readme.md.
