### ISSUE TITLE
Is there pseudo-hydrogen  in ABACUS?

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#4604]
### Background

when dealing with slab model in DFT, we usually need to use pseudo-hydrogen to passivate the bottom side, does abacus support this feature?
Here is an paper showing how to use pseudo-hydrogen in TiO2: https://[arxiv.org/pdf/0902.0854](https://arxiv.org/pdf/0902.0854)

### Describe the solution you'd like

we should have the pseudopotential and orbital files for pseudo-hydrogens, such as H1.33, H0.66 H0.25.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by kirk0830** [comment]
find a bug reported in #4694

**Comment by kirk0830** [comment]
Hi, now I have generated parts of them:
[H_0.50.SG15.PBE.zip](https://github.com/user-attachments/files/16357348/H_0.50.SG15.PBE.zip)
[H_0.58.SG15.PBE.zip](https://github.com/user-attachments/files/16357356/H_0.58.SG15.PBE.zip)
[H_0.66.SG15.PBE.zip](https://github.com/user-attachments/files/16357360/H_0.66.SG15.PBE.zip)
[H_0.75.SG15.PBE.zip](https://github.com/user-attachments/files/16357368/H_0.75.SG15.PBE.zip)
[H_1.25.SG15.PBE.zip](https://github.com/user-attachments/files/16357371/H_1.25.SG15.PBE.zip)
[H_1.33.SG15.PBE.zip](https://github.com/user-attachments/files/16357372/H_1.33.SG15.PBE.zip)
[H_1.50.SG15.PBE.zip](https://github.com/user-attachments/files/16357375/H_1.50.SG15.PBE.zip)
[H_1.66.SG15.PBE.zip](https://github.com/user-attachments/files/16357377/H_1.66.SG15.PBE.zip)
[H_1.75.SG15.PBE.zip](https://github.com/user-attachments/files/16357378/H_1.75.SG15.PBE.zip)

**Comment by Satinelamp** [comment]
Thanks a lot for the help. BTW, H_0.33 is also very often used.

**Comment by kirk0830** [comment]
> Thanks a lot for the help. BTW, H_0.33 is also very often used.

noted. During generating orbitals of H_0.33, I meet another warning_quit that will not meet in common cases:
```
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 Can't find even an electron!
 CHECK IN FILE : OUT.H-dimer-0.60/warning.log
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
 I will release this to generate orbitals.

**Comment by kirk0830** [comment]
@Satinelamp 
Hi, here are rest of pseudo-hydrogen orbitals:
[H_0.17.SG15.PBE.zip](https://github.com/user-attachments/files/16371720/H_0.17.SG15.PBE.zip)
[H_0.25.SG15.PBE.zip](https://github.com/user-attachments/files/16371722/H_0.25.SG15.PBE.zip)
[H_0.33.SG15.PBE.zip](https://github.com/user-attachments/files/16371723/H_0.33.SG15.PBE.zip)
[H_0.42.SG15.PBE.zip](https://github.com/user-attachments/files/16371726/H_0.42.SG15.PBE.zip)

**Comment by kirk0830** [comment]
Please do not use pseudopotentials with fractional charges till the PR#4788 being merged, thanks.
