### ISSUE TITLE
Unconverged relaxation of Selenium

### ISSUE THREAD

**Issue by swome** [deepmodeling/abacus-develop#4611]
### Describe the bug

When I do relaxation of Selenium, using SG15 pp, the electron steps are not converged.

### Expected behavior

It should converge

### To Reproduce

[issue.zip](https://github.com/user-attachments/files/16136103/issue.zip)

### Environment

3.6.3 on Sugon DCU,  AISI

### Additional Context

If this phase is BCC, as expected in experiments. It does not converge either.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@swome 
Thanks for your feedback. I have checked your INPUT and OUTPUT. As you see, the 1-st SCF iteration fails to converge. Such a phenomenon is quite normal for the structure which is not very stable. You can notice that SCF converges rapidly for relaxed structure. And the cell-relaxation was done after 30 steps successfully.
