### ISSUE TITLE
Unable to build the container using the dockerfile, has this node crashed？

### ISSUE THREAD

**Issue by A-006** [deepmodeling/abacus-develop#4614]
### Describe the Testing Issue

![image](https://github.com/deepmodeling/abacus-develop/assets/74701833/b6f91fe9-678f-475f-b73d-b24a6d63cdf2)
![image](https://github.com/deepmodeling/abacus-develop/assets/74701833/2e5d8be3-ff9b-44d2-a2b5-6812cfb815bd)

I'm encountering this issue while building containers with the dockerfile on three different machines. Is this a problem with Ubuntu 22.04?
Without an Intel + CUDA environment, can we build it?

**Comment by caic99** [comment]
Hi @A-006 ,
The problem is apparently network failure.

**Comment by caic99** [comment]
For the users having connection problems, we [recommend](https://abacus.deepmodeling.com/en/latest/quick_start/easy_install.html#container-deployment) using the image at `registry.dp.tech/deepmodeling/abacus-intel`.
