### ISSUE TITLE
Different handling for the multiple setting of same parameter in INPUT

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#4625]
### Describe the bug

If INPUT has multiple settings for one parameter, the handling is different now. LIke:
```
ks_solver cg
ks_solver dav
```

In old abacus, it will actually use the last one, but since #4508, ABACUS actually use the first setting.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by Qianruipku** [comment]
Perhaps this situation shouldn't occur; it should rather throw an error and exit?
