### ISSUE TITLE
Magnetic computational relaxation problems

### ISSUE THREAD

**Issue by cup-matianyou** [deepmodeling/abacus-develop#4626]
### Describe the bug

Turn on the non-collinear, turn off the SOC to do the relaxation, and the second step of the relaxation is non-magnetic all the way to the end

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [X] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by dyzheng** [comment]
I found some unreasonable parameters in your case, I changed `symmetry 0` , `mixing_beta    0.2`, `smearing_sigma    0.01` , `ecutwfc    100` , `#mixing_restart 1e-3 (don't set without DFTU)`,`#mixing_dmr    1 (don't set without DFTU)`.

Total magnetization of each relax steps are : "15.3, 15.6, 15.5, 15.5", which looks reasonable.

**Comment by dyzheng** [comment]
This Issue has been solved, but the relaxation with `noncolin=true` should be tested carefully.
