### ISSUE TITLE
request for usage tutorials of pyabacus module

### ISSUE THREAD

**Issue by moolawooda** [deepmodeling/abacus-develop#4632]
### Details

I'm trying to use the pyabacus module in Python scripts. However, there's no introduction of this module in the [online manual of ABACUS](http://abacus.deepmodeling.com/en/latest/community/faq.html). I would greatly appreciate if you could provide usage tutorials for this module. This would help users like myself better understand and leverage the full potential of the pyabacus module within our ABACUS workflows. Thank you for your consideration.

### Have you read the online manual http://abacus.deepmodeling.com/en/latest/

- [X] Yes, I have read the online manual.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific section of the documentation with the issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Update the documentation to address the issue, following the suggested improvement.
- [ ] Ensure the updated documentation adheres to the project's documentation standards.
- [ ] Test the updated documentation to ensure it is clear and accurate.
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Publish the updated documentation and notify the issue reporter.

**Comment by jieli-matrix** [comment]
Thanks for your interesting in `pyabacus`! `pyabacus` is on trail only supporting the `TwoCenterIntegral` module. We will add online tutorials for `pyabacus` when we release the new version with SCF calls in `pyabacus`.

We also have a simple Borihum Notebook tutorial, see [Notebook](https://bohrium.dp.tech/notebooks/19979733825).

If you have problems when using pyabacus (installations or usage) now, feel free to open a issue on specific topics!
