### ISSUE TITLE
Examples in the integration test reported segmentation fault on my machine

### ISSUE THREAD

**Issue by xuan112358** [deepmodeling/abacus-develop#4635]
### Describe the bug

When running ABACUS with code after commit #4622, I found that I can't run examples in integrate test.
They all reported segmentation fault.
Take “tests/integrate/201_NO_15_pseudopots” for example,  the log.txt was:
<img width="530" alt="image" src="https://github.com/deepmodeling/abacus-develop/assets/64718735/62054ae7-78e1-4609-8c55-97d11859bc18">

### Environment

compiler: -DMPI_CXX_COMPILER=mpiicpc  -DCMAKE_CXX_COMPILER=icpc
build with deepks and libri

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by dyzheng** [comment]
What is your compiling command?

**Comment by xuan112358** [comment]
@dyzheng 
cmake -B build -DCMAKE_INSTALL_PREFIX=./ \
-DELPA_DIR=/home/xuan/03_library/elpa/elpa-2021.05.002 -DELPA_INCLUDE_DIRS=/home/xuan/03_library/elpa/elpa-2021.05.002/include/elpa-2021.05.002  \
-DCEREAL_INCLUDE_DIR=/home/xuan/03_library/cereal/include \
-DMPI_CXX_COMPILER=mpiicpc  -DCMAKE_CXX_COMPILER=icpc \
-DTorch_DIR=/home/xuan/03_library/libtorch/share/cmake/Torch/  \
-Dlibnpy_INCLUDE_DIR=/home/xuan/03_library/libnpy-new/include -DENABLE_DEEPKS=1 -DLibxc_DIR=/home/xuan/03_library/libxc/libxc-5.2.3 -DENABLE_LIBRI=1  \
&& cmake --build build -j30 && cmake --install build

**Comment by Cstandardlib** [comment]
I will check with deepks and libri on my machine right away.

**Comment by dyzheng** [comment]
I have tested both in GNU and Intel environment and cannot rerun your error.

**Comment by dyzheng** [comment]
Intel environment can rerun your error with LibRI and DeePKS

**Comment by dyzheng** [comment]
Error comes from DeePKS with Intel compiler.

**Comment by dyzheng** [comment]
Can you try the newest commit, I test it with no error.

**Comment by dyzheng** [comment]
Can you try the newest commit, I test it with no error.

**Comment by xuan112358** [comment]
@dyzheng 
I can't compile with the command above after commit #4613 
The error is :
<img width="599" alt="image" src="https://github.com/deepmodeling/abacus-develop/assets/64718735/7de98922-787a-48bf-8ed9-08b6d2ad7288">

**Comment by dyzheng** [comment]
@xuan112358 can you rerun the toolchain to rebuild libtorch in your machine?

**Comment by xuan112358** [comment]
@dyzheng It seems like I can just download the LibTorch zip file but not need to build it? I downloaded the new LibTorch v2.3.1 in https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.3.1%2Bcpu.zip and tried again. The error was the same.

**Comment by caic99** [comment]
Duplicated with #4636. Let's track the problem there.

**Comment by Cstandardlib** [comment]
Build #4622 with IntelLLVM 2024.1.0 and encountered a compilation error
![image](https://github.com/deepmodeling/abacus-develop/assets/49788094/f90bf94c-6b7c-4f57-a137-956c79670700)
Build latest with IntelLLVM 2024.1.0 
Warnings are generated by cmake as follows:
![image](https://github.com/deepmodeling/abacus-develop/assets/49788094/3dd4ed6d-8f60-4ad2-89f3-46d7b7a01864)
and build failed with error
![image](https://github.com/deepmodeling/abacus-develop/assets/49788094/3533a1a9-a2eb-4e23-ab6c-a973a121cd83)
Building command:
`CXX=mpiicpx cmake -B build -DBUILD_TESTING=1 -DENABLE_LIBRI=ON -DENABLE_DEEPKS=1 -DTorch_DIR=~/develop/libtorch/share/cmake/Torch/ -Dlibnpy_INCLUDE_DIR=~/develop/libnpy/include`
with https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.3.1%2Bcpu.zip

**Comment by caic99** [comment]
@Cstandardlib Thanks for testing, and would you please apply the modifications in #4644 ?

**Comment by Cstandardlib** [comment]
@caic99 Thanks! I'll update my test results in #4636.

**Comment by caic99** [comment]
Hi @xuan112358 ,
I've updated the building process. Would you try using the latest codes to compile and run it again? Thanks.

**Comment by xuan112358** [comment]
@caic99 I‘ve tried it and all worked well now ! Also , I've tried to comile and run with Intel oneAPI toolkit 2024 and it worked well too. Thanks very much!
