### ISSUE TITLE
unable to use multi-process intel ABAUCS in the container

### ISSUE THREAD

**Issue by A-006** [deepmodeling/abacus-develop#4641]
### Describe the Testing Issue

The Intel compiler I'm using causes a segmentation fault when using multi-process after compiling on the container. This issue has occurred before. The compile command is
`
export I_MPI_CXX=icpx
cmake -B build -DCMAKE_CXX_COMPILER=mpiicpc \
    -DENABLE_DEEPKS=1 -DTorch_DIR=/opt/libtorch/share/cmake/Torch/ \
    -Dlibnpy_INCLUDE_DIR=/opt/libnpy/include \
    -DENABLE_LIBRI=ON
`
`
 cd source make -j50 CXX=mpiicpc ELPA_LIB_DIR=/usr/local/lib ELPA_INCLUDE_DIR=/usr/local/include CEREAL_DIR=/usr/include/cereal OPENMP=ON
`
This issue has occurred：
![20240711-120500](https://github.com/deepmodeling/abacus-develop/assets/74701833/d3ed9a16-45e2-4fba-aada-6483d2f5a168)

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by caic99** [comment]
@A-006 Would you try the command below:
https://github.com/deepmodeling/abacus-develop/blob/dd3718b7003114e2c8afc32db026f1b8a67fa955/Dockerfile.intel#L58

**Comment by A-006** [comment]
![图片](https://github.com/deepmodeling/abacus-develop/assets/74701833/24409502-14fe-4995-95bb-8c78690e450f)
Running according to this compile command still results in a segmentation fault.Could it be a bus error?

**Comment by caic99** [comment]
hi @A-006 ,
Are you using docker on a personal computer or on a cluster? Have you successfully ran ABACUS before?

**Comment by A-006** [comment]
hi,i can correctly use abacus with --shm-size 32g when running Docker.
