### ISSUE TITLE
Test: should we also make CI test by using Intel Env?

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#4643]
### Describe the Testing Issue

Now we only have CI tests under GNU Env.

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by caic99** [comment]
> Now we only have CI tests under GNU Env.

While our production environment is based on Intel oneAPI, which is not tested in CI pipeline.

**Comment by WHUweiqingzhou** [comment]
We decide to add Intel CI tests into daily test.

**Comment by caic99** [comment]
@pxlxingliang Would you verify if the problem in #2844 still exist? Thanks.

**Comment by pxlxingliang** [comment]
The ci test in intel is calculated in: https://bohrium.dp.tech/apps/abacustest/job?type=jobs&jobId=21991

**Comment by caic99** [comment]
> The ci test in intel is calculated in: https://bohrium.dp.tech/apps/abacustest/job?type=jobs&jobId=21991

@pxlxingliang I'm not able to see the result by the link you've provided. I wonder if there is still any warnings?

**Comment by pxlxingliang** [comment]
Two integrate tests are failed:
- 907_OF_LPS
- 140_PW_15_SO
![image](https://github.com/user-attachments/assets/87e9b3b0-3b29-4b45-bdff-9016d02fb17f)

3 unit tests are failed:
- 044_clebsch_gordan_coeff_test
- 203_HSolver_bpcg
- 277_read_wfc_pw_test_parallel

![image](https://github.com/user-attachments/assets/8e1c8b86-ac39-406a-8309-5d5db7a4b030)

**Comment by pxlxingliang** [comment]
In current bohrium app, the schedule jobs are not supported, I can not add this test in the daily test. Close it.

**Comment by mohanchen** [comment]
I don't see any further actions so I close it. If someone needs extra actions, feel free to reopen the issue.
