### ISSUE TITLE
Ionic relaxation error for magnetic system

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#465]
## Describe the Bug
Jin Gan from USTC raised a bug fixed requirement that relaxation calculation is different from version in 2021/08.

## To Reproduce
To test this case, I tested 204_NO_KP_FM case, modified:
1.  calculation from scf to relax
2.  charge_extrap set to "atomic" and "second-order"
3.  nstep set from 1 to 10
4.  move second Si atom for a little.
5.  compare with version in 2021/08/01

**Comment by dyzheng** [comment]
I tested that atomic second-order method has same wrong results. It caused by atomic_rho calculated wrong in step 3.

**Comment by dyzheng** [comment]
The only difference of newly version and 0801 version is startmag_type from 1 --> 2, it is caused by when starting magnet is readed from per element, it is also defaultly pass to atom->mag. It leads to same effect as directly set atomic magnet.

**Comment by dyzheng** [comment]
I still don't know why start from atomic magnet would cause atomic_rho error in step 3. I will modify the default startmag_type to element magnet.

**Comment by mohanchen** [comment]
@dyzheng Who will be responsible for adding new autotests? "why start from atomic magnet would cause atomic_rho error " this should be a new issue.

**Comment by dyzheng** [comment]
#467
