### ISSUE TITLE
The CUDA version of ABACUS takes too long to compile in CI test

### ISSUE THREAD

**Issue by dzzz2001** [deepmodeling/abacus-develop#4654]
### Describe the Testing Issue

It costs about 25 minutes to compile the CUDA version of abacus in CI test.
![image](https://github.com/deepmodeling/abacus-develop/assets/153698752/44f0c962-bc15-48b0-94ce-de27dd1d8f97)
As a contrast, the compilation of non-CUDA version of abacus finishes in three minutes
![image](https://github.com/deepmodeling/abacus-develop/assets/153698752/7499159d-d1e9-49e1-b8a9-73502949d156)
Upon comparing cuda.yml to test.yml, I noticed that the former lacks the procedure for installing ccache, which might be contributing to the problem. Perhaps we should add the installation of ccache into the cuda.yml, although I'm not certain if that will resolve the issue.
 

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by mohanchen** [comment]
@caic99 What's your opinion?

**Comment by caic99** [comment]
> Perhaps we should add the installation of ccache into the cuda.yml, 

Sounds good!

**Comment by mohanchen** [comment]
@caic99 do you know how to install the cache into the cuda.yml?

**Comment by caic99** [comment]
> @caic99 do you know how to install the cache into the cuda.yml?

@mohanchen Sure! @dzzz2001 You may follow the changes in commit https://github.com/deepmodeling/abacus-develop/commit/93c9ce34919f2d99631ca8bf36b5f8347a4be624

**Comment by dzzz2001** [comment]
The compilation time drops significantly after the installation of ccache:
![image](https://github.com/user-attachments/assets/56caa981-89d1-4733-96c0-4118d35bfd43)
Maybe we should add the step of ccache installation into build_test_camke.yml and build_test_makefile.yml too.

**Comment by caic99** [comment]
> Maybe we should add the step of ccache installation into build_test_camke.yml and build_test_makefile.yml too.

@dzzz2001 There's no need to do so, since the compiling time is acceptable. Plus, they runs on GitHub-hosted runners, which means you can not store the cache files locally.
