### ISSUE TITLE
pyabacus example `ex_s_rotate.py` failed 

### ISSUE THREAD

**Issue by maki49** [deepmodeling/abacus-develop#4655]
### Describe the bug

When I run `python ex_s_rotate.py` in `python/pyabacus/examples` after installing pyabacus by pip, the following error occurs:
```
Intel oneMKL ERROR: Parameter 7 was incorrect on entry to DGTSV .
*** stack smashing detected ***: terminated
已放弃 (核心已转储)
```

It seems not really a MKL problem... It may be related to some interface refactor?

**Comment by mohanchen** [comment]
Could you take a look? @jieli-matrix

**Comment by jieli-matrix** [comment]
I tested pyabacus examples on the image `registry.dp.tech/deepmodeling/abacus-intel` and successfully executed `python ex_s_rotate.py` with the results:
`norm(S_e3 - S_numer) =  9.175122689675847e-15`
@caic99 Any idea?
cc: @mohanchen

**Comment by caic99** [comment]
@jieli-matrix  Nope 😿

**Comment by jieli-matrix** [comment]
I checked the error message:
`Intel oneMKL ERROR: Parameter 7 was incorrect on entry to DGTSV .`
`DGTSV` solves a general tridiagonal system. It seems `DGTSV` doesn't occur in the direct usage in `pyabacus`, so it may be some enviroment or link problems in the host.
cc: @mohanchen

**Comment by maki49** [comment]
The error is located at this line: 
https://github.com/deepmodeling/abacus-develop/blob/5a5ff7f70576ea09c91e384981b2c715e2dc730b/python/pyabacus/examples/ex_s_rotate.py#L29

Maybe the problem lies in the linking of FFTW...?

**Comment by maki49** [comment]
I find that adding `set(MKL_INTERFACE lp64)` at the beginning of the inside of `if(MKLROOT)` can solve this problem (but I don't know why).

Copilot's explaination:
> The lp64 model refers to the data model where int and long types are 32 bits in size, and pointers are 64 bits in size. This is contrasted with the ilp64 model, where int is 32 bits, but long and pointers are 64 bits. The choice between lp64 and ilp64 affects how integers and pointers are handled in your code, which can impact compatibility and performance when interfacing with libraries like MKL.
