### ISSUE TITLE
Converged to unexpected electronic structures in DFT+U calculations for LixNiO2 and LixMnO2 cathode materials

### ISSUE THREAD

**Issue by taipinghu** [deepmodeling/abacus-develop#4661]
### Describe the bug

ABACUS generates unexpected electronic structures after finishing DFT+U calculations for Lix(x=6)Mn12O24 and Lix(x=1-11)NiO2. O's spin is decreased in current calculations when a Li ion gradually is removed, which is a incorrect redox property prediction. 

Different U values also generates similar results. 

[1_half_Li_LiMnO2.tar.gz](https://github.com/user-attachments/files/16186645/1_half_Li_LiMnO2.tar.gz)
[5_Scan_U.tar.gz](https://github.com/user-attachments/files/16186652/5_Scan_U.tar.gz)
[3_Various_Li.tar.gz](https://github.com/user-attachments/files/16186720/3_Various_Li.tar.gz)

### Expected behavior

Expected behavior is the decrease of Ni's or Mn's spin, and the number of corresponding spin-decreased Ni or Mn is equal to the number of removed Li. 

### Environment

Bohrium image name: registry.dp.tech/dptech/prod-385/abacus-dspin:0711, proposed by @dyzheng 

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
fixed.
