### ISSUE TITLE
Unexpected results in the EOS calculations of Si with orbitals generated from the GTH-PBE pseudopotential

### ISSUE THREAD

**Issue by JohnYan98** [deepmodeling/abacus-develop#4667]
### Describe the bug

When running EOS calculations for Si using pseudopotentials and orbitals generated from CP2K GTH-PBE pseudopotentials, the PW method exhibits the expected precision, while the LCAO method demonstrates significantly lower precision.

### Expected behavior

The EOS results calculated with the LCAO method showed similar precision to the PW method.

### To Reproduce

/root/abacus_benchmark_demo  in the mirror

### Environment

Bohrium mirror: registry.dp.tech/dptech/prod-36094/abacus-cp2k-elk:v2

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
fixed by  #4705
