### ISSUE TITLE
Refactor: EXX part in `ESolver_KS_LCAO` calls for refactor

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#4670]
### Describe the Code Quality Issue

I am refactoring `LCAO_Matrix` recently, and plan to delete it.
Now, there are only 4 variables in `LCAO_Matrix`, namely:
```cpp
    using TAC = std::pair<int, std::array<int, 3>>;
    std::vector<std::map<int, std::map<TAC, RI::Tensor<double>>>>* Hexxd;
    std::vector<std::map<int, std::map<TAC, RI::Tensor<std::complex<double>>>>>*
        Hexxc;
    /// @brief Hexxk for all k-points, only for the 1st scf loop ofrestart load
    std::vector<std::vector<double>> Hexxd_k_load;
    std::vector<std::vector<std::complex<double>>> Hexxc_k_load;
```
And `Hexxd` and `Hexxc` is defined in `ESolver_KS_LCAO()`:

```cpp
template <typename TK, typename TR>
ESolver_KS_LCAO<TK, TR>::ESolver_KS_LCAO()
{
    this->classname = "ESolver_KS_LCAO";
    this->basisname = "LCAO";

// the following EXX code should be removed to other places, mohan 2024/05/11
#ifdef __EXX
    if (GlobalC::exx_info.info_ri.real_number)
    {
        this->exx_lri_double = std::make_shared<Exx_LRI<double>>(GlobalC::exx_info.info_ri);
        this->exd = std::make_shared<Exx_LRI_Interface<TK, double>>(this->exx_lri_double);
        this->LM.Hexxd = &this->exd->get_Hexxs();
    }
    else
    {
        this->exx_lri_complex = std::make_shared<Exx_LRI<std::complex<double>>>(GlobalC::exx_info.info_ri);
        this->exc = std::make_shared<Exx_LRI_Interface<TK, std::complex<double>>>(this->exx_lri_complex);
        this->LM.Hexxc = &this->exc->get_Hexxs();
    }
#endif
}
```

and also ESolver_KS_LCAO should not manage these variables:
```cpp
#ifdef __EXX
    std::shared_ptr<Exx_LRI_Interface<TK, double>> exd = nullptr;
    std::shared_ptr<Exx_LRI_Interface<TK, std::complex<double>>> exc = nullptr;
    std::shared_ptr<Exx_LRI<double>> exx_lri_double = nullptr;
    std::shared_ptr<Exx_LRI<std::complex<double>>> exx_lri_complex = nullptr;
#endif
```

Could related developers refactor this part, and move them outside `ESolver_KS_LCAO()`.

**Comment by maki49** [comment]
> and also ESolver_KS_LCAO should not manage these variables:
> ```
> #ifdef __EXX
>     std::shared_ptr<Exx_LRI_Interface<TK, double>> exd = nullptr;
>     std::shared_ptr<Exx_LRI_Interface<TK, std::complex<double>>> exc = nullptr;
>     std::shared_ptr<Exx_LRI<double>> exx_lri_double = nullptr;
>     std::shared_ptr<Exx_LRI<std::complex<double>>> exx_lri_complex = nullptr;
> #endif
> ```

These classes contain RI 2-center radial tables and their initialization procedure to be called in `before_all_runners`, so they cannot be moved outside `ESolver_KS_LCAO` ( in the way that previous `LM` or current `hsk` are moved into `HamiltLCAO`).
Luckily, this does not prevent us from removing `LM` completely.
