### ISSUE TITLE
 Refactor Hsolver: unified interfaces for diago_david and diago_dav_subspace needed

### ISSUE THREAD

**Issue by Cstandardlib** [deepmodeling/abacus-develop#4674]
### Description
The HSolver module in our current project includes various diagonalization methods, with the `DiagoDavid` and `DiagoDavSubspace` classes having inconsistent interfaces. To enhance code maintainability and modularity, we need to standardize the interfaces of these classes.
### Design Proposal
- Standardize the interfaces of the `DiagoDavid` and `DiagoDavSubspace` classes.
- Get an independent HSolver module.
- Constructors and destructors should adopt a unified strategy for memory allocation and deallocation to improve memory efficiency and simplify memory management. 
- Large blocks of memory should be uniformly allocated in the constructor to reduce runtime allocation overhead.
- Unified memory deallocation in the destructor to ensure no memory leaks occur.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by WHUweiqingzhou** [comment]
fixed by #4726
