### ISSUE TITLE
somd redundant configuration in examples/tddft/Absoption_spectrum/H2_velocity

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#4685]
### Describe the Code Quality Issue

there are some redundant configuration in examples/tddft/Absoption_spectrum/H2_velocity

![Snipaste_2024-07-13_13-19-17](https://github.com/user-attachments/assets/09f0c73f-e3ed-4632-af4b-b6f2640fc6c3)

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by mohanchen** [comment]
Thanks! Could you propose a PR to fix this? @Satinelamp

**Comment by Satinelamp** [comment]
> Thanks! Could you propose a PR to fix this? @Satinelamp

I will try.
