### ISSUE TITLE
Test: weird CI test fails in PR #4684 show the bug of current workflow

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#4699]
### Describe the Testing Issue

PR #4684 fails in CI tests. And all these errors are proved to be induced by PR #4679 (already fixed by #4686 now). 
It is very weird that PR #4679 can pass the CI test. I double-check it, and find in PR #4679:
![image](https://github.com/user-attachments/assets/173c0c97-28f9-411f-bbbd-991b832715f9)

These HSE tests fails actually, while CI passes. The line `../tools/catch_properties.sh: line 79: [: !=: unary operator expected` is also found in PR #4472, where it make some changes about `catch_properties.sh`.

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by maki49** [comment]
The bug in `catch_properties.sh` induced by #4472 has already been fixed by #4678.
