### ISSUE TITLE
LCAO has memory problems

### ISSUE THREAD

**Issue by Qianruipku** [deepmodeling/abacus-develop#4712]
### Describe the bug

When compiled with ENABLE_ASAN = ON, ABACUS fails in all LCAO integral tests.
For example 
260_NO_DJ_PK_PU_FM    diago_scalapack.cpp
![image](https://github.com/user-attachments/assets/f707a854-e6a7-4704-9f22-260568c182ac)
![image](https://github.com/user-attachments/assets/180a2734-b7a1-4c28-b10b-a02ed88996c1)
201_NO_15_pseudopots  elpa_new_complex.cpp
![image](https://github.com/user-attachments/assets/e430824b-f7c5-4e51-a374-8706a494f703)
![image](https://github.com/user-attachments/assets/36216daa-7928-4be1-88b1-f5ac57e7d14c)

### Environment

CXX=g++, MPICXX=mpicxx
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@pxlxingliang, could you reproduce this?

**Comment by Cstandardlib** [comment]
Could it be an input error? When I was trying AddressSanitizer to run PW first time the same problem was encountered in different examples(i.e. Zero page...), and it turns out that the environment or relative path was not installed properly. If memory leak is detected, something different is reported like xxx bytes leak at xxx
object.

**Comment by Cstandardlib** [comment]
I try to rerun this example on my own machine, and sanitizer reports as follows:
![image](https://github.com/user-attachments/assets/db5e782e-be45-4d55-8051-9d0341862a92)
build with IntelLLVM 2024.2.0, CXX=mpiicpx

**Comment by pxlxingliang** [comment]
I have test with test 204_NO_KP_NC, and there is one memory problem about ABAUCS:
```
Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f2a8de1c337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
    #1 0x562a2e32997e in Pseudopot_upf::read_pseudo_upf201_nonlocal(std::basic_ifstream<char, std::char_traits<char> >&, Atom_pseudo&) /abacus/source/module_cell/read_pp_upf201.cpp:449
    #2 0x562a2e3347db in Pseudopot_upf::read_pseudo_upf201(std::basic_ifstream<char, std::char_traits<char> >&, Atom_pseudo&) /abacus/source/module_cell/read_pp_upf201.cpp:66
    #3 0x562a2e30eef5 in Pseudopot_upf::init_pseudo_reader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, Atom_pseudo&) /abacus/source/module_cell/read_pp.cpp:63
    #4 0x562a2e415331 in UnitCell::read_cell_pseudopots(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_ofstream<char, std::char_traits<char> >&) /abacus/source/module_cell/read_cell_pseudopots.cpp:32
    #5 0x562a2e384aea in UnitCell::read_pseudo(std::basic_ofstream<char, std::char_traits<char> >&) /abacus/source/module_cell/unitcell.cpp:734
    #6 0x562a2eed763a in ModuleESolver::ESolver_FP::before_all_runners(Input_para const&, UnitCell&) /abacus/source/module_esolver/esolver_fp.cpp:49
    #7 0x562a2eec8d6c in ModuleESolver::ESolver_KS<std::complex<double>, base_device::DEVICE_CPU>::before_all_runners(Input_para const&, UnitCell&) /abacus/source/module_esolver/esolver_ks.cpp:100
    #8 0x562a2f23acb5 in ModuleESolver::ESolver_KS_LCAO<std::complex<double>, std::complex<double> >::before_all_runners(Input_para const&, UnitCell&) /abacus/source/module_esolver/esolver_ks_lcao.cpp:141
    #9 0x562a2ea551de in Driver::driver_run() /abacus/source/driver_run.cpp:52
    #10 0x562a2ea4ec7e in Driver::atomic_world() /abacus/source/driver.cpp:188
    #11 0x562a2ea53ef6 in Driver::init() /abacus/source/driver.cpp:41
    #12 0x562a2dfb9e8a in main /abacus/source/main.cpp:42
```

The related codes are:
```
    this->kbeta = new int[pp.nbeta];
```

The last modification is from @sunliang98, could you please help check it?

**Comment by sunliang98** [comment]
> I have test with test 204_NO_KP_NC, and there is one memory problem about ABAUCS:
> 
> ```
> Direct leak of 24 byte(s) in 1 object(s) allocated from:
>     #0 0x7f2a8de1c337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
>     #1 0x562a2e32997e in Pseudopot_upf::read_pseudo_upf201_nonlocal(std::basic_ifstream<char, std::char_traits<char> >&, Atom_pseudo&) /abacus/source/module_cell/read_pp_upf201.cpp:449
>     #2 0x562a2e3347db in Pseudopot_upf::read_pseudo_upf201(std::basic_ifstream<char, std::char_traits<char> >&, Atom_pseudo&) /abacus/source/module_cell/read_pp_upf201.cpp:66
>     #3 0x562a2e30eef5 in Pseudopot_upf::init_pseudo_reader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, Atom_pseudo&) /abacus/source/module_cell/read_pp.cpp:63
>     #4 0x562a2e415331 in UnitCell::read_cell_pseudopots(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_ofstream<char, std::char_traits<char> >&) /abacus/source/module_cell/read_cell_pseudopots.cpp:32
>     #5 0x562a2e384aea in UnitCell::read_pseudo(std::basic_ofstream<char, std::char_traits<char> >&) /abacus/source/module_cell/unitcell.cpp:734
>     #6 0x562a2eed763a in ModuleESolver::ESolver_FP::before_all_runners(Input_para const&, UnitCell&) /abacus/source/module_esolver/esolver_fp.cpp:49
>     #7 0x562a2eec8d6c in ModuleESolver::ESolver_KS<std::complex<double>, base_device::DEVICE_CPU>::before_all_runners(Input_para const&, UnitCell&) /abacus/source/module_esolver/esolver_ks.cpp:100
>     #8 0x562a2f23acb5 in ModuleESolver::ESolver_KS_LCAO<std::complex<double>, std::complex<double> >::before_all_runners(Input_para const&, UnitCell&) /abacus/source/module_esolver/esolver_ks_lcao.cpp:141
>     #9 0x562a2ea551de in Driver::driver_run() /abacus/source/driver_run.cpp:52
>     #10 0x562a2ea4ec7e in Driver::atomic_world() /abacus/source/driver.cpp:188
>     #11 0x562a2ea53ef6 in Driver::init() /abacus/source/driver.cpp:41
>     #12 0x562a2dfb9e8a in main /abacus/source/main.cpp:42
> ```
> 
> The related codes are:
> 
> ```
>     this->kbeta = new int[pp.nbeta];
> ```
> 
> The last modification is from @sunliang98, could you please help check it?

Thanks for your notice, I have fix the memory leak caused by `kbeta` in #4758 .

**Comment by caic99** [comment]
Hi @Qianruipku ,
Does the program finish normally when you turn off the address sanitizer? If so, since no other people is able to reproduce this error, this might be a false positive of the sanitizer.

**Comment by WHUweiqingzhou** [comment]
@Qianruipku 
could you offer the detailed config and Env since we cannot reproduce the memory leak you mentioned here.

**Comment by WHUweiqingzhou** [comment]
plz feel free to reopen it.
