### ISSUE TITLE
output occupation of KS state in TDDFT

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#4714]
### Background

During running TDDFT, the time-dependent occupation of K-S energy state could be informative and usefule

Here is the example in(https://cdmd.cnki.com.cn/Article/CDMD-10358-1023001052.htm     含时密度泛函理论在超快动力学中若干应用的研究
-何傅翔)

![image](https://github.com/user-attachments/assets/ad1e63f8-3562-42b5-87b9-234ba9aaca4f)

### Describe the solution you'd like

output the time-dependent occupation number of K-S energy states. According my knowledge, it seems we should project the on-the-fly electronic states or charge density onto the K-S ground energy states.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by Satinelamp** [comment]
why output l/m/z? seems not related with band?
![Snipaste_2024-08-08_20-31-10](https://github.com/user-attachments/assets/d69b735f-3588-40cd-bc1a-275a4d8701ea)

**Comment by YuLiu98** [comment]
> why output l/m/z? seems not related with band? ![Snipaste_2024-08-08_20-31-10](https://private-user-images.githubusercontent.com/62006565/356222511-d69b735f-3588-40cd-bc1a-275a4d8701ea.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMjI5MTYsIm5iZiI6MTcyMzEyMjYxNiwicGF0aCI6Ii82MjAwNjU2NS8zNTYyMjI1MTEtZDY5YjczNWYtMzU4OC00MGNkLWJjMWEtMjc1YTRkODcwMWVhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDEzMTAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyODExNWY4MTE4ZDdjMzViZGUwMzAwNDBlNGNjYzdhZTM0YWEzYTVhYzdlYWZiYjQyNGI4YzA5N2Y2MTg0NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.waBPb-gRsrhNWFrhdyUXKz2uXbC5btnmGEUdohQcRaQ)

`PBAND_1` contains the contribution of each numerical atomic orbital to the projected band structure. 

As you can see in the figure, this section describes the contribution of the first orbital, which belongs to the first Si atom. And the quantum numbers of the orbital `l` and `m` are 1 and 0. Besides, `z` is the multiplicity.
