### ISSUE TITLE
using DFT+U during TDDFT

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#4728]
### Background

when running TDDFT, it might to useful DFT+U to describe the d electrons. but the current ABACUS doesn't support it.

### Describe the solution you'd like

support DFT+U during TDDFT

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by WHUweiqingzhou** [comment]
@dyzheng could you have a  look?

**Comment by Satinelamp** [comment]
Here is the example and output log.
[tddft_dft_plus_u.tar.gz](https://github.com/user-attachments/files/16479326/tddft_dft_plus_u.tar.gz)

**Comment by mohanchen** [comment]
We will implement and check DFT+U first, and then we will implement this function. Thanks for your patience!
