### ISSUE TITLE
ABACUS abnormal exit with ks_solver dav

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#4729]
### Describe the bug

The daily pw-dav test at 20240718 is failed with commit: be8f40f (the test at 20240717 with commit a7dc5b5 is successful, the commits between them should have some bugs.)
https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fsched-abacustest-intel-dav-a151c1
```
 << Start SCF iteration.
 ITER       ETOT/eV          EDIFF/eV         DRHO     TIME/s
 DA1     -1.85257839e+04   0.00000000e+00   4.3417e-01 168.68
 DA2     -1.85268387e+04  -1.05480877e+00   1.7567e-02  33.60
 DA3     -1.85268419e+04  -3.19533449e-03   1.9583e-03  49.62

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 40 RUNNING AT dp-lbg-471-13864061
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================
```

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by pxlxingliang** [comment]
It seems have memory leak in dav method. 

The memory chart of intel-dav 006_27Fe at 20240717
![image](https://github.com/user-attachments/assets/67f6fe0c-4c1a-409f-8937-53e1f0c765b7)

The memory chart of intel-dav 006_27Fe at 20240718
![image](https://github.com/user-attachments/assets/9f0dc240-6ac3-486b-b63f-0a2901e416da)

**Comment by caic99** [comment]
I've scheduled a dynamic analysis run and here is [the result](https://raw.githubusercontent.com/deepmodeling/abacus-develop/dashboard/README.md). Hope that helps.

**Comment by Cstandardlib** [comment]
I found that no memory release operaion (i.e. `delmem_complex_op()`) is paired with memory allocating operation for basis set used in Davidson method after migration from `Psi` to direct T data fields. That could be the reason for memory leak. I'll fix it right away.

**Comment by Cstandardlib** [comment]
Fix it in #4731.
By the way, is it possible to rerun the daily pw-dav test on my own machine? If possible, what's the proper command? I don't know whether the fix solved the problem effectively.

**Comment by caic99** [comment]
> I don't know whether the fix solved the problem effectively.

@Cstandardlib You can run any test cases using davidson solving method with sanitizer feature. Or you can set an extremely small SCF converge threshold and monitor the memory usage manually. I believe your PR will solve the problem.

**Comment by pxlxingliang** [comment]
> Fix it in #4731. By the way, is it possible to rerun the daily pw-dav test on my own machine? If possible, what's the proper command? I don't know whether the fix solved the problem effectively.


You can download the test results from below link:
https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fsched-abacustest-intel-dav-a151c1

![image](https://github.com/user-attachments/assets/2b60ebe5-6093-4eed-88e8-13b362a02526)

You should firstly repeat the bug in your local machine using the old codes.

**Comment by Cstandardlib** [comment]
@caic99 Thanks! I'll have a shot at it.

**Comment by Cstandardlib** [comment]
@pxlxingliang What command should I use to run examples here? I have tried to repeat bug in 004_3BaTiO3/, but found that testing seems to be a binary executable, `mixbench-intel`.
![image](https://github.com/user-attachments/assets/e75a4bd9-5443-490b-8f5e-87ee55cbb8fa)

**Comment by pxlxingliang** [comment]
> @pxlxingliang What command should I use to run examples here? I have tried to repeat bug in 004_3BaTiO3/, but found that testing seems to be a binary executable, `mixbench-intel`. ![image](https://private-user-images.githubusercontent.com/49788094/349827989-e75a4bd9-5443-490b-8f5e-87ee55cbb8fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyODIwODYsIm5iZiI6MTcyMTI4MTc4NiwicGF0aCI6Ii80OTc4ODA5NC8zNDk4Mjc5ODktZTc1YTRiZDktNTQ0My00OTBiLThmNWUtODdlZTU1Y2JiOGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA1NDk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyYTViNDU2NzM1MTU2YjAwYmVkMDcxMzhlMmU1YTBmMjIwNWFjZmMwNjUzM2MzMmU5NGFiMTE5NGEyNGVkNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lrlUtVkJ_Es3gexhIUzH20G8V6FLbFsxgpq2kHwd_yA)

Please ignore the mixbench, and just use ABACUS inputs to run with command like: `OMP_NUM_THREADS=1 mpirun -np 8 abacus`

**Comment by Cstandardlib** [comment]
> 
> 
> 
> 
> > @pxlxingliang What command should I use to run examples here? I have tried to repeat bug in 004_3BaTiO3/, but found that testing seems to be a binary executable, `mixbench-intel`. ![image](https://private-user-images.githubusercontent.com/49788094/349827989-e75a4bd9-5443-490b-8f5e-87ee55cbb8fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyODIwODYsIm5iZiI6MTcyMTI4MTc4NiwicGF0aCI6Ii80OTc4ODA5NC8zNDk4Mjc5ODktZTc1YTRiZDktNTQ0My00OTBiLThmNWUtODdlZTU1Y2JiOGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA1NDk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyYTViNDU2NzM1MTU2YjAwYmVkMDcxMzhlMmU1YTBmMjIwNWFjZmMwNjUzM2MzMmU5NGFiMTE5NGEyNGVkNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lrlUtVkJ_Es3gexhIUzH20G8V6FLbFsxgpq2kHwd_yA)
> 
> Please ignore the mixbench, and just use ABACUS inputs to run with command like: `OMP_NUM_THREADS=1 mpirun -np 8 abacus`

Got it, thanks!
