### ISSUE TITLE
Test: please avoid using functions and features higher than C++11 even in unittest

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#4735]
### Describe the Code Quality Issue

During the time I was fixing issue #4673 , I find this:
```c++
TEST_F(vdwd2Test, D2Default)
{
    std::unique_ptr<vdw::Vdwd2> vdwd2_test = std::make_unique<vdw::Vdwd2>(ucell);

    vdwd2_test->parameter().initial_parameters(input);
    vdwd2_test->parameter().initset(ucell);
    EXPECT_EQ(vdwd2_test->parameter().scaling(), 0.75);
    EXPECT_EQ(vdwd2_test->parameter().damping(), input.vdw_d);
    EXPECT_EQ(vdwd2_test->parameter().model(), input.vdw_cutoff_type);
    EXPECT_EQ(vdwd2_test->parameter().radius_, 56.6918);
    double Si_C6 = 9.23*1e6 / (ModuleBase::ELECTRONVOLT_SI * ModuleBase::NA) / pow(ModuleBase::BOHR_TO_A, 6)/ ModuleBase::Ry_to_eV;
    EXPECT_NEAR(vdwd2_test->parameter().C6_["Si"], Si_C6,1e-13);
    EXPECT_EQ(vdwd2_test->parameter().R0_["Si"], 1.716/ModuleBase::BOHR_TO_A);
    EXPECT_EQ(vdwd2_test->parameter().period().x, 2 * ceil(56.6918 / ucell.lat0 / sqrt(ucell.a1.norm2())) + 1);
    EXPECT_EQ(vdwd2_test->parameter().period().y, 2 * ceil(56.6918 / ucell.lat0 / sqrt(ucell.a2.norm2())) + 1);
    EXPECT_EQ(vdwd2_test->parameter().period().z, 2 * ceil(56.6918 / ucell.lat0 / sqrt(ucell.a3.norm2())) + 1);
}
```
in file:
/abacus-develop/source/module_hamilt_general/module_vdw/test/vdw_test.cpp

As we decided to use only features, syntax not higher than C++11, this piece of codes obviously spoil this consensus.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by caic99** [comment]
> As we decided to use only features, syntax not higher than C++11, this piece of codes obviously spoil this consensus.

@kirk0830 Since GoogleTest itself [requires C++14](https://github.com/google/googletest?tab=readme-ov-file#release-1150), I think it is OK if those modern features is only used in testing codes.

**Comment by kirk0830** [comment]
> > As we decided to use only features, syntax not higher than C++11, this piece of codes obviously spoil this consensus.
> 
> @kirk0830 Since GoogleTest itself [requires C++14](https://github.com/google/googletest?tab=readme-ov-file#release-1150), I think it is OK if those modern features is only used in testing codes.

@caic99 Thanks I got it. So it indicates if compile with GoogleTest, the C++ standard is implicitly updated to C++14, otherwise it seems to be C++11? A littble bit... strange...
FYI @mohanchen

**Comment by caic99** [comment]
> So it indicates if compile with GoogleTest, the C++ standard is implicitly updated to C++14, otherwise it seems to be C++11?

Yes. The cpp standard used is explicitly set in `CMakeLists.txt`. You can see many extra components requires C++14 or above.

**Comment by mohanchen** [comment]
I would suggest using C++ 11 in both codes and tests, the reason is to lower the barrier for all of the developers of ABACUS.
