### ISSUE TITLE
Compile warnings could be eliminated

### ISSUE THREAD

**Issue by Cstandardlib** [deepmodeling/abacus-develop#4756]
### Describe the Code Quality Issue

Warnings are generated during compile time:

```cpp
abacus-develop/source/module_io/restart.cpp:29:9: warning: add explicit braces to avoid dangling else [-Wdangling-else]
   29 |         else return false;
      |         ^
abacus-develop/source/module_io/restart.cpp:34:9: warning: add explicit braces to avoid dangling else [-Wdangling-else]
   34 |         else return false;
      |         ^

// where there is a risk of dangling else
if (-1 == file)
        if (error_quit)
            throw std::runtime_error("can't open restart save file. \nerrno=" + ModuleBase::GlobalFunc::TO_STRING(errno) + ".\n" + ModuleBase::GlobalFunc::TO_STRING(__FILE__) + " line " + ModuleBase::GlobalFunc::TO_STRING(__LINE__));
        else return false;
```
another warning
```cpp
abacus-develop/source/module_io/test_serial/read_input_test.cpp:28:1: warning: non-void function does not return a value [-Wreturn-type]
   28 | }
      | ^
```

Shall I modify this source file `restart.cpp` to eliminate these warnings?

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by caic99** [comment]
> Shall I modify this source file `restart.cpp` to eliminate these warnings?

@Cstandardlib Sure! If possible, you can also fix all other warnings.

**Comment by Cstandardlib** [comment]
@caic99 I've created 2 PRs to fix part of these warnings, leaving gtest part unchanged. Hope it'll help!
