### ISSUE TITLE
Abosolute path in STRU is conficted with the change of default setting of `pseudo_dir` and `orbital_dir` in version 3.7.1 set to `./`

### ISSUE THREAD

**Issue by xdzhu** [deepmodeling/abacus-develop#4760]
### Describe the bug

In the former versions before 3.7.1, the default setting of `pseudo_dir` and `orbital_dir` is empty.

However, now in the version 3.7.1, the default setting of `pseudo_dir` and `orbital_dir` in version 3.7.1 has been changed to `./` which makes the absolute path in the STRU file unreadable. When you do not set and of  `pseudo_dir` and `orbital_dir`, the ABACUS will read the STRU file like below (now `./` is added at the beginning of the abosolute path): 

![image](https://github.com/user-attachments/assets/351ae994-e929-4b13-99e0-005803a77442)

INPUT of VERSION 3.7.1
![image](https://github.com/user-attachments/assets/fb6ca4ab-ee86-457c-af48-c39a573de78b)

INPUT of VERSION 3.7.0
![image](https://github.com/user-attachments/assets/755be00b-bbb9-4f7a-beec-5f6d23836644)

### Expected behavior

Add some pre-pend rules like if the absolute path in STRU file is detected, the `pseudo_dir` and `orbital_dir` just be dumped directly.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by xdzhu** [comment]
In the latest version of ABACUS 3.7.2, this problem still shows up. You can determine if the path given in the STRU file is an absolute path by checking if it starts with a "/". If it is an absolute path, then directly discard the path settings in the INPUT file. Otherwise, merge the two paths. Can you check if this approach works?

![image](https://github.com/user-attachments/assets/c7b78f0c-bef2-49cc-aead-7dcce3663ae9)

**Comment by pxlxingliang** [comment]
The default value of pseudo_dir and orbital_dir is modified from "" to "./" in #4706.
Hi @Qianruipku, could you check it?
