### ISSUE TITLE
Inquiry: Use of Macros vs. Internal Variables for Controlling Code Versions for GPU Builds

### ISSUE THREAD

**Issue by Cstandardlib** [deepmodeling/abacus-develop#4761]
### Brief
Mixed usage of macro definitions and internal variables for GPU code path control, leading to potential confusion and inconsistency.

### Details

I am working on our codebase and have come across different practices for controlling whether a version of the code is compiled for GPU execution or whether some functionality is turned on/off. I would like to discuss and determine the best approach to standardize this process.

We have sections of code wrapped in preprocessor directives that check for external macro definitions like `__CUDA` or `__ROCM`, as well as our own `this->device` member variable to determine if the code is running on a GPU device. Here's an example of the current approach based on external and internal conditions:

```cpp
    if (this->device == base_device::GpuDevice){
#if defined(__CUDA) || defined(__ROCM)
            Real* e_temp_gpu = nullptr;
            resmem_var_op()(this->ctx, e_temp_gpu, nbase);
            syncmem_var_h2d_op()(this->ctx, this->cpu_ctx, e_temp_gpu, e_temp_cpu.data(), nbase);
            vector_mul_vector_op<T, Device>()(this->ctx,
                                                   nbase,
                                                   vc_ev_vector + m * nbase,
                                                   vc_ev_vector + m * nbase,
                                                   e_temp_gpu);
            delmem_var_op()(this->ctx, e_temp_gpu);
#endif
    }else{
       // CPU-specific code
    }

#if defined(__CUDA) || defined(__ROCM)
    if (this->device == base_device::GpuDevice)
    {
        delmem_var_op()(this->ctx, this->d_precondition);
    }
#endif
```

In this snippet, the GPU-specific code is wrapped in a conditional block that first checks an internal state (`this->device == base_device::GpuDevice`) and then uses preprocessor directives to include CUDA or ROCM-specific code, or vice versa.

Also, some other functionalities use this style:
```cpp
        if(this->use_paw)
        {
#ifdef USE_PAW
            GlobalC::paw_cell.paw_nl_psi(1, reinterpret_cast<const std::complex<double>*> (psi_in + m*ldPsi),
                reinterpret_cast<std::complex<double>*>(&this->spsi[m * dim]));
#endif
        }
```

### Questions:

1. What is the recommended approach for managing GPU code paths within our codebase? Should we rely on macro definitions, internal state checks, or a combination of both?
2.  Which is the determining factor for compilation, MACROS or internal state variables? How can we avoid confusion and inconsistency if we decide to pick one of them as our coding guideline and migrate to the new standard?
3. Is there an approach that aligns with best practices for C++ development, especially in the context of GPU computing?

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by kirk0830** [comment]
I have some comments on practical implementation of PAW codes so I leave some words here. In reality, there are not so many functions that needed to insert macro. What is the real problem of abacus code now (I think) is lack of program abstraction design. The SCF driver (esolver) of ABACUS has too many lines but there are other softwares merely uses 90 lines to do almost the same thing, I mean, there are softwares have esolver with only 90 lines. 
More specifically, I think there should be good and clear seperation between cases where code for illustrating the logic, and code cares actual implementation. Here is an example:
```c++
enum class AnimalType {
    Dog,
    Cat,
    Bird
};

#ifdef __CORGI
void feed_corgi() {
    // feed corgi
}
#endif
#ifdef __HUSKY
void feed_husky() {
    // feed husky
}
#endif

void feed_for_c_zealot(const AnimalType& type) {
    switch (type) {
        case AnimalType::Dog:
            // feed dog
#ifdef __CORGI
            // feed corgi
            feed_corgi();
#endif
#ifdef __HUSKY
            // feed husky
            feed_husky();
#endif
            break;
        case AnimalType::Cat:
            // feed cat
            break;
        case AnimalType::Bird:
            // feed bird
            break;
    }
}
```
There are many macros inserted, but not so many developers need to know what kind of dog to feed but just want to understand how the feed motion proceed. A better choice would be:
```c++
void feed_dogs() {
#ifdef __CORGI
            // feed corgi
            feed_corgi();
#endif
#ifdef __HUSKY
            // feed husky
            feed_husky();
#endif
}
void feed_in_smart_way(const AnimalType& type) {
    switch (type) {
        case AnimalType::Dog:
            // feed dog
            feed_dogs();
            break;
        case AnimalType::Cat:
            // feed cat
            break;
        case AnimalType::Bird:
            // feed bird
            break;
    }
}
```
In my opinion, I will let only `feed_dogs()` care whether those special feed methods are implemented, and let `feed_in_smart_way` function only care about the procedure that if needed to feed, and if so, feed. 
So once you feel confused about the workflow control or cannot decide which to use, my answer would be:
1. first, in principle, either is okay
2. using macro is somewhat like c-style, and not safe in some cases
while there are also cases where without some macros, functions of basic libraries are not visible/callable, it is the case I recommend the way that writing functions like `feed_dogs()`.

@jinzx10 any comments?

**Comment by jinzx10** [comment]
I think this is a complicated issue, as it is a code design problem that relates two flows of control: what the program is capable of, and what an actual calculation chooses to do. Take the GPU code as an example, ABACUS can be built to support or not support GPU, and, if built to support GPU, users may choose to run on CPU or GPU. The former is a compile-time option, while the latter is a run time one. That's basically the reason why we need both macros and if-statements: macros control compile-time behaviors, and if-statements are responsible for the flows in actual calculations (run-time). If one chooses to build ABACUS without GPU, the relevant GPU code must be made invisible to icpx or mpicxx otherwise it's a compilation error, hence it comes the macros; If "device" is an input variable, if-statements seems unavoidable.

Of course, while both macros and if-statements are indispensable, it still remains the problem of how to orgainze the code for better readability and maintainability, and the current situation might not be optimal. However, I believe this is a very big topic that needs comprehensive investigation before we can make a conclusion.

**Comment by Cstandardlib** [comment]
Thank you all for your discussions! I am now impressed with the way GPU code is organized and used during compile time and run time. Maybe further investigation is necessary and I will continue to keep an eye on practices in this area.
