### ISSUE TITLE
Is the formula for Trigonometric type electric field right in the doc?

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#4768]
### Details

I notice the formula for Trigonometric type electric field in the doc contains a square item, is this right?

https://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#td-trigo-freq1

![Snipaste_2024-07-23_14-12-26](https://github.com/user-attachments/assets/7af332a0-7bad-4ac4-bcc2-a1801f4dd506)

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by AsTonyshment** [comment]
Unfortunately, according to the code, the doc indeed contains typos. Thanks for your report! I will fix them now.

![img_v3_02d2_6a4c7a84-c32d-4f0a-9141-2f4d231099eg](https://github.com/user-attachments/assets/d3283342-8bb1-4366-8407-1f8897e71b3a)

**Comment by AsTonyshment** [comment]
Fortunately, according to the code, the documentation is correct, there is this square item:
![img_v3_02d2_6a4c7a84-c32d-4f0a-9141-2f4d231099eg](https://github.com/user-attachments/assets/5f3eb35b-9380-40a4-a2c7-1c876b1fc310)

**Comment by Satinelamp** [comment]
what is the point of using sin^2 instead of sin?

**Comment by AsTonyshment** [comment]
> what is the point of using sin^2 instead of sin?

I did not write this function, so I cannot be sure of the original intention of the code author. However, I suspect it might be related to maintaining the same conventions as other mainstream _ab initio_ software.(?) Perhaps @lyb9812 can provide more insight on this?

**Comment by lyb9812** [comment]
This is inherited from the old code. Actually, it seems not practical. You can change the code yourself on your workstation to perform a certain type of function.
