### ISSUE TITLE
electronic step not convergent when using ELPA-2024.05

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#4772]
### Describe the bug

When I try to compile ABACUS-develop using ELPA-2024.05, the convergence of electronic steps is way much worse than ELPA-2021.05.

Here is the test case and output log:
[TEST.zip](https://github.com/user-attachments/files/16347786/TEST.zip)

### Expected behavior

Is abacus NOT compatible to the ELPA 2024.05 version?

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by QuantumMisaka** [comment]
Any test and update ？
Toolchain update is ongoing, I'll have some test for the newest elpa

**Comment by meishengme** [comment]
I compiled ABACUS-develop using ELPA-2024.05.001 and calculated this expample. I don't see a non-convergence phenomenon.

                              ABACUS v3.7.1

               Atomic-orbital Based Ab-initio Computation at UStc                    

                     Website: http://abacus.ustc.edu.cn/                             
               Documentation: https://abacus.deepmodeling.com/                       
                  Repository: https://github.com/abacusmodeling/abacus-develop       
                              https://github.com/deepmodeling/abacus-develop         
                      Commit: 5b5d151 (Sun Jul 14 21:56:04 2024 +0800)

 Tue Jul 30 14:52:19 2024
 MAKE THE DIR         : OUT.autotest/
 RUNNING WITH DEVICE  : CPU / Intel(R) Xeon(R) Platinum
 UNIFORM GRID DIM        : 90 * 90 * 243
 UNIFORM GRID DIM(BIG)   : 18 * 18 * 81
 DONE(0.327417   SEC) : SETUP UNITCELL
 DONE(0.371693   SEC) : SYMMETRY
 DONE(0.498818   SEC) : INIT K-POINTS
 ---------------------------------------------------------
 Ion relaxation calculations
 ---------------------------------------------------------
 SPIN    KPOINTS         PROCESSORS  NBASE       
 1       1               1           182         
 ---------------------------------------------------------
 Use Systematically Improvable Atomic bases
 ---------------------------------------------------------
 ELEMENT ORBITALS        NBASE       NATOM       XC          
 C       2s2p1d-7au      13          6           
 N       2s2p1d-7au      13          8           
 ---------------------------------------------------------
 Initial plane wave basis and FFT box
 ---------------------------------------------------------
 DONE(0.525902   SEC) : INIT PLANEWAVE
 -------------------------------------------
 STEP OF RELAXATION : 1
 -------------------------------------------
 START CHARGE      : atomic
 DONE(8.07197    SEC) : INIT SCF
 * * * * * *
 << Start SCF iteration.
 ITER       ETOT/eV          EDIFF/eV         DRHO     TIME/s
 GE1     -3.09323615e+03   0.00000000e+00   1.6972e-01   5.71
 GE2     -3.08987902e+03   3.35713707e+00   1.1399e-01   5.52
 GE3     -3.09002436e+03  -1.45348921e-01   5.7369e-02   5.45
 GE4     -3.09020115e+03  -1.76790068e-01   1.5347e-02   5.42
 GE5     -3.09017182e+03   2.93308319e-02   1.3428e-02   5.50
 GE6     -3.09017074e+03   1.08471575e-03   5.0280e-03   5.43
 GE7     -3.09017009e+03   6.46867618e-04   2.2839e-03   5.53
 GE8     -3.09017036e+03  -2.66999538e-04   7.9562e-04   5.33
 GE9     -3.09017067e+03  -3.06637092e-04   5.3088e-04   5.44
 GE10    -3.09017111e+03  -4.42184946e-04   3.2315e-04   5.37
 GE11    -3.09017119e+03  -7.77695627e-05   9.2013e-05   5.42
 GE12    -3.09017122e+03  -3.82875030e-05   5.2732e-05   5.37
 GE13    -3.09017124e+03  -1.29224968e-05   2.4955e-05   5.44
 GE14    -3.09017124e+03  -5.56598486e-06   1.1794e-05   5.48
 GE15    -3.09017124e+03  -3.33473353e-07   3.5221e-06   5.38
 GE16    -3.09017124e+03  -3.22821006e-07   2.6153e-06   5.54
 GE17    -3.09017124e+03  -2.08250361e-07   6.0651e-07   5.17
 >> Leave SCF iteration.
 * * * * * *
 ETOT DIFF (eV)       : 0
 LARGEST GRAD (eV/A)  : 0.00320189
 -------------------------------------------
 STEP OF RELAXATION : 2
 -------------------------------------------
 DONE(119.701    SEC) : INIT SCF
 * * * * * *
 << Start SCF iteration.
 ITER       ETOT/eV          EDIFF/eV         DRHO     TIME/s
 GE1     -3.09017124e+03   0.00000000e+00   5.7523e-05   5.84
 GE2     -3.09017124e+03   6.91747531e-07   3.8307e-05   5.43
 GE3     -3.09017124e+03  -3.04158999e-07   2.0187e-05   5.48
 GE4     -3.09017124e+03  -1.57586841e-08   6.2130e-06   5.40
 GE5     -3.09017124e+03  -5.89674553e-09   2.3967e-06   5.42
 GE6     -3.09017124e+03  -3.34454404e-09   5.5654e-07   5.21
 >> Leave SCF iteration.
 * * * * * *
 ETOT DIFF (eV)       : 3.66115e-06
 LARGEST GRAD (eV/A)  : 0.0120161
 -------------------------------------------
 STEP OF RELAXATION : 3
 -------------------------------------------
 DONE(172.542    SEC) : INIT SCF
 * * * * * *
 << Start SCF iteration.
 ITER       ETOT/eV          EDIFF/eV         DRHO     TIME/s
 GE1     -3.09017124e+03   0.00000000e+00   1.0277e-04   5.78
 GE2     -3.09017124e+03   2.18893930e-06   6.8400e-05   5.41
 GE3     -3.09017124e+03  -9.80841968e-07   3.6061e-05   5.55
 GE4     -3.09017124e+03  -4.97095377e-08   1.1122e-05   5.50
 GE5     -3.09017124e+03  -8.26642594e-09   4.2854e-06   5.43
 GE6     -3.09017124e+03   5.55219833e-09   1.0016e-06   5.46
 GE7     -3.09017124e+03  -1.43348650e-09   6.2782e-07   5.18
 >> Leave SCF iteration.
 * * * * * *
 ETOT DIFF (eV)       : -4.19097e-06
 LARGEST GRAD (eV/A)  : 0.00149252
 -------------------------------------------
 STEP OF RELAXATION : 4
 -------------------------------------------
 DONE(232.075    SEC) : INIT SCF
 * * * * * *
 << Start SCF iteration.
 ITER       ETOT/eV          EDIFF/eV         DRHO     TIME/s
 GE1     -3.09017124e+03   0.00000000e+00   1.8330e-05   5.84
 GE2     -3.09017124e+03   5.01387716e-08   1.3572e-05   5.43
 GE3     -3.09017124e+03  -2.81287407e-08   6.5988e-06   5.48
 GE4     -3.09017124e+03  -1.18677369e-09   1.6977e-06   5.47
 GE5     -3.09017124e+03   1.24207139e-09   7.1294e-07   5.20
 >> Leave SCF iteration.
 * * * * * *
 ETOT DIFF (eV)       : -2.25941e-08
 LARGEST GRAD (eV/A)  : 0.00158626
 -------------------------------------------
 STEP OF RELAXATION : 5
 -------------------------------------------
 DONE(280.377    SEC) : INIT SCF
 * * * * * *
 << Start SCF iteration.
 ITER       ETOT/eV          EDIFF/eV         DRHO     TIME/s
 GE1     -3.09017124e+03   0.00000000e+00   3.4244e-07   5.68
 >> Leave SCF iteration.
 * * * * * *
 ETOT DIFF (eV)       : -4.15021e-08
 LARGEST GRAD (eV/A)  : 0.00158515
 -------------------------------------------
 STEP OF RELAXATION : 6
 -------------------------------------------
 DONE(307.061    SEC) : INIT SCF
 * * * * * *
 << Start SCF iteration.
 ITER       ETOT/eV          EDIFF/eV         DRHO     TIME/s
 GE1     -3.09017124e+03   0.00000000e+00   1.5312e-05   5.82
 GE2     -3.09017124e+03   5.01639069e-08   1.1197e-05   5.49
 GE3     -3.09017124e+03  -9.28498635e-09   4.6403e-06   5.40
 GE4     -3.09017124e+03  -3.36078532e-09   1.6096e-06   5.51
 GE5     -3.09017124e+03  -4.42652279e-09   6.5607e-07   5.29
 >> Leave SCF iteration.
 * * * * * *
 ETOT DIFF (eV)       : -7.3986e-08
 LARGEST GRAD (eV/A)  : 0.00225088
 -------------------------------------------
 STEP OF RELAXATION : 7
 -------------------------------------------
 DONE(355.639    SEC) : INIT SCF
 * * * * * *
 << Start SCF iteration.
 ITER       ETOT/eV          EDIFF/eV         DRHO     TIME/s
 GE1     -3.09017124e+03   0.00000000e+00   5.3954e-07   5.58
 >> Leave SCF iteration.
 * * * * * *
 ETOT DIFF (eV)       : -4.20355e-08
 LARGEST GRAD (eV/A)  : 0.00072593
TIME STATISTICS
----------------------------------------------------------------------------
    CLASS_NAME                NAME            TIME/s  CALLS   AVG/s  PER/%  
----------------------------------------------------------------------------
                   total                      374.61 23       16.29  100.00 
 Driver            reading                    0.01   1        0.01   0.00   
 Input_Conv        Convert                    0.00   1        0.00   0.00   
 Driver            driver_line                374.60 1        374.60 100.00 
 UnitCell          check_tau                  0.00   1        0.00   0.00   
 ESolver_KS_LCAO   before_all_runners         3.54   1        3.54   0.95   
 PW_Basis_Sup      setuptransform             0.02   1        0.02   0.00   
 PW_Basis_Sup      distributeg                0.01   1        0.01   0.00   
 mymath            heapsort                   0.15   105      0.00   0.04   
 Symmetry          analy_sys                  0.04   1        0.04   0.01   
 PW_Basis_K        setuptransform             0.01   1        0.01   0.00   
 PW_Basis_K        distributeg                0.01   1        0.01   0.00   
 PW_Basis          setup_struc_factor         2.01   7        0.29   0.54   
 NOrbital_Lm       extra_uniform              0.06   10       0.01   0.01   
 Mathzone_Add1     SplineD2                   0.00   10       0.00   0.00   
 Mathzone_Add1     Cubic_Spline_Interpolation 0.00   10       0.00   0.00   
 Mathzone_Add1     Uni_Deriv_Phi              0.05   10       0.01   0.01   
 ppcell_vl         init_vloc                  2.41   1        2.41   0.64   
 Ions              opt_ions                   371.04 1        371.04 99.05  
 ESolver_KS_LCAO   runner                     305.14 7        43.59  81.45  
 ESolver_KS_LCAO   before_scf                 47.34  7        6.76   12.64  
 ESolver_KS_LCAO   beforesolver               0.37   7        0.05   0.10   
 ESolver_KS_LCAO   set_matrix_grid            0.33   7        0.05   0.09   
 atom_arrange      search                     0.01   7        0.00   0.00   
 Grid_Technique    init                       0.30   7        0.04   0.08   
 Grid_BigCell      grid_expansion_index       0.08   14       0.01   0.02   
 Record_adj        for_2d                     0.01   7        0.00   0.00   
 Grid_Driver       Find_atom                  0.01   1470     0.00   0.00   
 LCAO_domain       grid_prepare               0.00   7        0.00   0.00   
 Veff              initialize_HR              0.00   7        0.00   0.00   
 OverlapNew        initialize_SR              0.01   7        0.00   0.00   
 EkineticNew       initialize_HR              0.00   7        0.00   0.00   
 NonlocalNew       initialize_HR              0.01   7        0.00   0.00   
 Charge            set_rho_core               0.02   7        0.00   0.00   
 Charge            atomic_rho                 38.42  14       2.74   10.26  
 PW_Basis_Sup      recip2real                 22.76  350      0.07   6.08   
 PW_Basis_Sup      gathers_scatterp           2.72   350      0.01   0.73   
 Potential         init_pot                   9.00   7        1.29   2.40   
 Potential         update_from_charge         58.68  49       1.20   15.66  
 Potential         cal_fixed_v                0.71   7        0.10   0.19   
 PotLocal          cal_fixed_v                0.69   7        0.10   0.18   
 Potential         cal_v_eff                  57.74  49       1.18   15.41  
 H_Hartree_pw      v_hartree                  7.88   49       0.16   2.10   
 PW_Basis_Sup      real2recip                 22.94  392      0.06   6.12   
 PW_Basis_Sup      gatherp_scatters           1.55   392      0.00   0.41   
 PotXC             cal_v_eff                  49.33  49       1.01   13.17  
 XC_Functional     v_xc                       49.14  49       1.00   13.12  
 Potential         interpolate_vrs            0.22   49       0.00   0.06   
 Symmetry          rhog_symmetry              7.64   49       0.16   2.04   
 Symmetry          group fft grids            4.12   49       0.08   1.10   
 H_Ewald_pw        compute_ewald              0.53   7        0.08   0.14   
 Charge_Mixing     init_mixing                0.06   7        0.01   0.02   
 HSolverLCAO       solve                      156.23 42       3.72   41.70  
 HamiltLCAO        updateHk                   77.56  42       1.85   20.71  
 OperatorLCAO      init                       76.48  126      0.61   20.41  
 Veff              contributeHR               74.76  42       1.78   19.96  
 Gint_interface    cal_gint                   186.83 91       2.05   49.87  
 Gint_interface    cal_gint_vlocal            74.70  42       1.78   19.94  
 Gint_Tools        cal_psir_ylm               38.88  407064   0.00   10.38  
 Gint_k            transfer_pvpR              0.05   42       0.00   0.01   
 OverlapNew        calculate_SR               1.07   7        0.15   0.28   
 OverlapNew        contributeHk               0.02   42       0.00   0.01   
 EkineticNew       contributeHR               1.08   42       0.03   0.29   
 EkineticNew       calculate_HR               1.07   7        0.15   0.29   
 NonlocalNew       contributeHR               0.60   42       0.01   0.16   
 NonlocalNew       calculate_HR               0.59   7        0.08   0.16   
 OperatorLCAO      contributeHk               0.02   42       0.00   0.01   
 HSolverLCAO       hamiltSolvePsiK            1.28   42       0.03   0.34   
 DiagoElpa         elpa_solve                 1.26   42       0.03   0.34   
 ElecStateLCAO     psiToRho                   77.38  42       1.84   20.66  
 elecstate         cal_dm                     0.03   49       0.00   0.01   
 psiMulPsiMpi      pdgemm                     0.03   49       0.00   0.01   
 DensityMatrix     cal_DMR                    0.05   49       0.00   0.01   
 Gint              transfer_DMR               0.08   42       0.00   0.02   
 Gint_interface    cal_gint_rho               76.70  42       1.83   20.48  
 Charge_Mixing     get_drho                   0.14   42       0.00   0.04   
 Charge            mix_rho                    8.02   35       0.23   2.14   
 Charge            Pulay_mixing               0.55   35       0.02   0.15   
 ESolver_KS_LCAO   cal_force                  65.87  7        9.41   17.58  
 Force_Stress_LCAO getForceStress             65.87  7        9.41   17.58  
 Forces            cal_force_loc              2.78   7        0.40   0.74   
 Forces            cal_force_ew               1.72   7        0.25   0.46   
 Forces            cal_force_cc               0.00   7        0.00   0.00   
 Forces            cal_force_scc              21.17  7        3.02   5.65   
 Force_LCAO        ftable                     40.20  7        5.74   10.73  
 Force_LCAO        allocate                   148.78 4        37.20  39.72  
 LCAO_domain       build_ST_new               2.30   14       0.16   0.61   
 LCAO_domain       vnl_mu_new                 1.55   7        0.22   0.41   
 Force_LCAO_k      allocate_k                 148.73 4        37.18  39.70  
 Force_LCAO        cal_fedm                   0.03   7        0.00   0.01   
 Force_LCAO_k      cal_edm_2d                 148.73 4        37.18  39.70  
 Force_LCAO        cal_ftvnl_dphi             0.01   7        0.00   0.00   
 Force_LCAO        cal_fvl_dphi               35.42  7        5.06   9.46   
 Gint_interface    cal_gint_force             35.42  7        5.06   9.46   
 Gint_Tools        cal_dpsir_ylm              12.01  33922    0.00   3.21   
 Force_LCAO        cal_fvnl_dbeta             0.88   7        0.13   0.23   
 ESolver_KS_LCAO   after_all_runners          0.00   1        0.00   0.00   
 ModuleIO          write_istate_info          0.00   1        0.00   0.00   
----------------------------------------------------------------------------


 START  Time  : Tue Jul 30 14:52:19 2024
 FINISH Time  : Tue Jul 30 14:58:34 2024
 TOTAL  Time  : 375
 SEE INFORMATION IN : OUT.autotest/

**Comment by meishengme** [comment]
I compile ABACUS-develop using ELPA-2024.05.001 and calculate this example.  The electronic step does not occur that it is difficult to converge.
[Uploading elpa_2024.05.001.txt…]()

**Comment by meishengme** [comment]
I compile ABACUS-develop using ELPA-2024.05.001 and calculate this example. The electronic step does not occur that it is difficult to converge.
[elpa_2024.05.001.txt](https://github.com/user-attachments/files/16423762/elpa_2024.05.001.txt)
