### ISSUE TITLE
Improper indentation of braces added by pre-commit bot

### ISSUE THREAD

**Issue by jinzx10** [deepmodeling/abacus-develop#4789]
### Describe the Code Quality Issue

Currently the pre-commit bot automatically adds braces to one-line control flow (if/for) when the body is not enclosed by braces. However, the closing braces was not properly indented, e.g. 
(code snippets from https://github.com/deepmodeling/abacus-develop/pull/4650/commits/a57a5a7fd0666706b3342bcfb13aeb824d6ccc7b):

![image](https://github.com/user-attachments/assets/cb280e6c-6df0-4cc0-a327-8fd51bb9a14d)
![image](https://github.com/user-attachments/assets/9651b110-33ab-4e1b-8728-b6c2a9f3cc1a)

Such mis-indentation might cause much confusion and harm code readability.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by WHUweiqingzhou** [comment]
@haozhihan,
could you have a look?

**Comment by WHUweiqingzhou** [comment]
@haozhihan,
could you have a look?

**Comment by haozhihan** [comment]
The clang-tidy can add brackets, but it cannot solve the problem of correct indentation. If we want to solve it, we need to add clang-format in CI/CD. However, clang-format is currently disabled. @jinzx10 @WHUweiqingzhou

**Comment by haozhihan** [comment]
I suggest you can use clang-format on own server locally. The current `.clang-format` file works fine.
