### ISSUE TITLE
test: daily pw test failed at 20240725

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#4798]
### Describe the Testing Issue

At 20240725, the daily test of all pw test failed, and it the force of example 003_12Pt111 failed the accuracy test:
![image](https://github.com/user-attachments/assets/4f295e08-8305-4336-9fe2-1a667bbeeac5)
![image](https://github.com/user-attachments/assets/93e2948c-d866-4de2-bcd3-13b98c93c178)

https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fsched-abacustest-intel-dav-b0f9a9

It should be one commit between 2697322 and 636a354 induce the failure.

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by pxlxingliang** [comment]
I have tested the commits between 2697322 and 636a354, and the failure is occurred since 541f6b3d
```
                                                                version  \
11ef76aa/003_12Pt111  v3.7.1(11ef76aab (Wed Jul 24 21:06:31 2024 +08...   
541f6b3d/003_12Pt111  v3.7.1(541f6b3db (Wed Jul 24 11:17:12 2024 +08...   
7d7c0e75/003_12Pt111  v3.7.1(7d7c0e758 (Wed Jul 24 09:38:15 2024 +08...   
815017e3/003_12Pt111  v3.7.1(815017e39 (Wed Jul 24 21:04:30 2024 +08...   
a131482c/003_12Pt111  v3.7.1(a131482c1 (Wed Jul 24 21:01:41 2024 +08...   
e00f13d1/003_12Pt111  v3.7.1(e00f13d16 (Wed Jul 24 09:37:07 2024 +08...   

                      total_time  converge  normal_end ks_solver  \
11ef76aa/003_12Pt111     188.803      True        True       dav   
541f6b3d/003_12Pt111     188.499      True        True       dav   
7d7c0e75/003_12Pt111     197.548      True        True       dav   
815017e3/003_12Pt111     187.773      True        True       dav   
a131482c/003_12Pt111     196.557      True        True       dav   
e00f13d1/003_12Pt111     179.310      True        True       dav   

                      delta_energyPerAtom(eV)  MaxAbsForce(eV/A)  \
11ef76aa/003_12Pt111                      0.0       2.614635e-02   
541f6b3d/003_12Pt111                      0.0       2.614635e-02   
7d7c0e75/003_12Pt111                      0.0       4.070000e-08   
815017e3/003_12Pt111                      0.0       2.614635e-02   
a131482c/003_12Pt111                      0.0       2.614635e-02   
e00f13d1/003_12Pt111                      0.0       4.070000e-08   

                      MaxAbsStress(kbar)  acc_pass  
11ef76aa/003_12Pt111            0.000003     False  
541f6b3d/003_12Pt111            0.000003     False  
7d7c0e75/003_12Pt111            0.000003      True  
815017e3/003_12Pt111            0.000003     False  
a131482c/003_12Pt111            0.000003     False  
e00f13d1/003_12Pt111            0.000003      True  

```

**Comment by WHUweiqingzhou** [comment]
@maki49, could you have a look your PR 541f6b3 ?

**Comment by maki49** [comment]
The previous force suffers from incomplete symmetrization being fixed by #4752. The reference result should be changed.

**Comment by dyzheng** [comment]
![img_v3_02d8_a4b53428-a400-4b1e-b247-63c1ef9d8b8g](https://github.com/user-attachments/assets/9f07c4b9-de35-43d2-8984-3f697ac18ebe)
The new result of force is wrong.

**Comment by pxlxingliang** [comment]
The FORCE with symmetry off is 
```
                       Pt1        -0.5047723932         0.0001578277         0.0001542612
                       Pt2        -0.5048332310        -0.0001649874         0.0000285146
                       Pt3        -0.5047049795         0.0001161483         0.0000014564
                       Pt4        -0.5047922610        -0.0001123333        -0.0001762107
                       Pt5        -0.0011951575        -0.0000173413         0.0000096392
                       Pt6        -0.0012083310         0.0000133942         0.0000223188
                       Pt7        -0.0011978704        -0.0000103542        -0.0000281709
                       Pt8        -0.0012081293         0.0000200021        -0.0000135751
                       Pt9         0.5059622619        -0.0001374455        -0.0001515364
                      Pt10         0.5060351227         0.0001401361        -0.0000401989
                      Pt11         0.5059084701        -0.0000931822         0.0000132020
                      Pt12         0.5060064982         0.0000881355         0.0001802999

```
