### ISSUE TITLE
Automatic Testing on Pull Requests to "develop" Branch

### ISSUE THREAD

**Issue by tuoping** [deepmodeling/abacus-develop#48]
## Summary

Currently, we have some computation examples in directory `ABACUS.develop/examples` and `ABACUS.develop/tests`, they can potentially serves as Integration Tests when someone adds a pull request to the develop branch. We are also planning to add some Unit Tests.

## Details

Currently, only a subset of ABACUS can be built with standardized build system, which is implemented by @tansongchen with Docker, CMake and GitHub Actions, see #47 . We plan to include all ABACUS code in this system in a couple of weeks. Once this is done, we can start to work on automatic testing.

**Comment by tansongchen** [comment]
Solved in #88.
