### ISSUE TITLE
k-point symmetry affects final energy in simple monoclinic lattice in both pw and LCAO base 

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#481]
## Describe the Bug
k-point symmetry affects final energy in simple monoclinic lattice in both pw and LCAO base 

## To Reproduce
diff 812_PW_LT_sm_symmetry_0/result.ref 812_PW_LT_sm_symmetry_1/result.ref
diff 826_NO_LT_sm_symmetry_0/result.ref 826_NO_LT_sm_symmetry_1/result.ref 
[simple_monoclinic_bug.tar.gz](https://github.com/deepmodeling/abacus-develop/files/7608001/simple_monoclinic_bug.tar.gz)

**Comment by dyzheng** [comment]
This error come from function "Symmetry_rho::psymm", if I ignore this function, Symmetry=1 result correspond with Symmetry=0 case. this case is special that k point didn't fold.

**Comment by dyzheng** [comment]
The symmetry average operation for electronic density take place in real space, but not in reciprocal space.
So sometimes k-point symmetry would affects final energy.
But it is not a bug, If k-points for the system is as many as enough, this error would disappear.
@hongriTianqi
