### ISSUE TITLE
Using lambda expressions to make the code logic clearer

### ISSUE THREAD

**Issue by dzzz2001** [deepmodeling/abacus-develop#4823]
### Describe the Code Quality Issue

In PR #4786, I find the logic in the following code snippet a bit convoluted, and there are some checks can be moved outside the loop to reduce unnecessary checking overhead.
![image](https://github.com/user-attachments/assets/419b5260-4f17-4e56-8373-09a0864ce3c1)
the code can be modified as follow using lambda expression:
![image](https://github.com/user-attachments/assets/53729789-8043-469b-a080-8ef447e2da7c)

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by grysgreat** [comment]
That's a good idea. I will take this modification and test the results.
