### ISSUE TITLE
For anyone who uses `icpx` in intel OneAPI to compile ABACUS and encounters an error as "Invalid MKL INTERFACE FULL intel lp64, options are: intel ilp64"

### ISSUE THREAD

**Issue by xdzhu** [deepmodeling/abacus-develop#4845]
### Details

When I used `icpx` to compile in ABACUS version 3.7.0, there were no issues. However, when compiling versions 3.7.1 and 3.7.2, I encountered a problem where the OneAPI suite had issues finding the MKL library with icpx, showing the error "Invalid MKL INTERFACE FULL intel lp64, options are: intel ilp64" as below:
![625e6a05abc453941a0d774600f19f6](https://github.com/user-attachments/assets/bb73ebd2-992e-4b9c-832d-c983abd568e8)

**This issue comes from the MKL library's CMake configuration file used by `icpx`**. I think it comes from the version 2023.x of intel OneAPI. To fix this, you need to modify the line containing "set(MKL_INTERFACE_LIST intel_ilp64" in the file `MKLConfig.cmake` which is located in the path "$MKLROOT/lib/cmake/mkl/".

You should add "${IFACE_TYPE}_lp64)" in the line to let it become "set(MKL_INTERFACE_LIST intel_ilp64 ${IFACE_TYPE}_lp64)". For more details, you can refer to the link: [Re:Using MKL 2023.0.0.20221201 with Eigen](https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/Using-MKL-2023-0-0-20221201-with-Eigen/m-p/1448342#M34189) . After making this change, the compilation can work well as below:
![image](https://github.com/user-attachments/assets/a8cbaefd-65cd-439a-9daf-eab176e3c662)

![image](https://github.com/user-attachments/assets/26d7cc52-96a9-4cbc-b782-206f704f3594)

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [X] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by WHUweiqingzhou** [comment]
@caic99 could you have a look?

**Comment by caic99** [comment]
> @caic99 could you have a look?

@WHUweiqingzhou From the link provided by @xdzhu , this is an external issue introduced by MKL. ABACUS now uses the standard MKL cmake interface, and is compatible with the latest OneAPI version.

> For more details, you can refer to the link: [Re:Using MKL 2023.0.0.20221201 with Eigen](https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/Using-MKL-2023-0-0-20221201-with-Eigen/m-p/1448342#M34189) . After making this change, the compilation can work well as below:
