### ISSUE TITLE
how to accelerate the procedure of init_SCF?

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#4852]
### Details

I try to use ABACUS to run MD, but each step would takes about 20s, while the SCF only takes no more than 1s, I am guessing that ABACUS might take a lot of time to do initialization of each SCF loop. 
Is there any method I could use to accelerate the procedure of init_SCF?
Could this issue be related with https://github.com/deepmodeling/abacus-develop/issues/4851?

![Snipaste_2024-08-01_03-23-13](https://github.com/user-attachments/assets/278c76e6-acf2-4cb2-bd28-7fa7defeb0a4)

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by YuLiu98** [comment]
Hi, could you please attach your test example here?

**Comment by Satinelamp** [comment]
[test-case.zip](https://github.com/user-attachments/files/16548465/test-case.zip)

**Comment by YuLiu98** [comment]
> [test-case.zip](https://github.com/user-attachments/files/16548465/test-case.zip)

Thank you. Maybe you can provide the output files as well.

**Comment by Satinelamp** [comment]
The output log:
[abacus.971308.zip](https://github.com/user-attachments/files/16555335/abacus.971308.zip)

**Comment by Satinelamp** [comment]
Here is my test since the [PR4954](https://github.com/deepmodeling/abacus-develop/pull/4954), works perfect for me.
[abacus.976688.zip](https://github.com/user-attachments/files/16610535/abacus.976688.zip)
