### ISSUE TITLE
It is unable to start magnetization from contributions of each atom

### ISSUE THREAD

**Issue by mohanchen** [deepmodeling/abacus-develop#486]
## Background
Previously, ABACUS (such as version 2.1.0) only supports the starting magnetization from each type of element. In the summer of 2021, Zhou Gengdong had updated this function, after the updates, we thought the magnetization could be starting from the contribution of each atom. However, recently we found this new functionality has some bugs. @dyzheng changed the code back to the original one.

## Describe the solution you'd like
We should check the formulas, maybe do some reconstructions. I believe this issue could be solved. We will come back asap.

## Additional context
@dyzheng should remember the details. Someone will be responsible for adding new tests.

**Comment by dyzheng** [comment]
Correction, #465 this issue remained a new question that if start magnetization from contributions of each atom, it is correct in first step SCF calculation, but would be error when any atom moves.

**Comment by wenfei-li** [comment]
Is the bug still there? I've recently tested the bond breaking process of H2, where I set starting magnetization of the two H atoms. It seems to work fine for me. Is there any test case where things go wrong?

**Comment by dyzheng** [comment]
> Is the bug still there? I've recently tested the bond breaking process of H2, where I set starting magnetization of the two H atoms. It seems to work fine for me. Is there any test case where things go wrong?

There is no new feedback after this answer, I will close this issue.
