### ISSUE TITLE
`KILLED BY SIGNAL: 6 (Aborted)` caused by `Gint_interface::cal_gint_vlocal` in EXX calculation when using ABACUS 3.7.1 and 3.7.2

### ISSUE THREAD

**Issue by xdzhu** [deepmodeling/abacus-develop#4867]
### Describe the bug

When I was using ABACUS versions 3.7.1 and 3.7.2 for HSE calculations, the program crashed after completing the first round of EXX with an error message indicating that xxx had exited.
After enabling debug information, I found that the program stopped at the Gint_interface::cal_gint_vlocal function. Do you have any ideas on how to resolve this issue? To reproduce, you can check the zip file:
[signal6.zip](https://github.com/user-attachments/files/16465157/signal6.zip)

screen output:
![image](https://github.com/user-attachments/assets/1ed0627c-6cac-49a8-95a1-22b2a5bfff65)

running_scf.log:
![image](https://github.com/user-attachments/assets/294fa5dd-53c8-4b37-8bad-82727428b8d5)

### To Reproduce

To reproduce, you can check the zip file:
[signal6.zip](https://github.com/user-attachments/files/16465157/signal6.zip)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by dzzz2001** [comment]
Can you reproduce this error using the latest version of ABACUS (commit: 895c282)? The most recent commit modified the `cal_gint_vlocal` function, which might have fixed the previous issue. This test case consumes too much memory, and I haven't been able to get results on my computer. Perhaps you could provide a smaller test case?

**Comment by xdzhu** [comment]
> Can you reproduce this error using the latest version of ABACUS (commit: [895c282](https://github.com/deepmodeling/abacus-develop/commit/895c282deefa34a459902bbedcc10b1e48a2f2e0))? The most recent commit modified the `cal_gint_vlocal` function, which might have fixed the previous issue. This test case consumes too much memory, and I haven't been able to get results on my computer. Perhaps you could provide a smaller test case?

I pull the latest version of Commit: `d2d5c56` and compile abacus, the signal 6 ERROR also comes up.
[signal6-again.zip](https://github.com/user-attachments/files/16508209/signal6-again.zip)

![image](https://github.com/user-attachments/assets/6b348cb0-c4de-4dc9-bb91-692c7bef3aaf)

**Comment by xdzhu** [comment]
Now the problem is solved.

![image](https://github.com/user-attachments/assets/df5f528d-9bc9-4d86-a666-794b9e4013d5)
