### ISSUE TITLE
We need to have more documents for developers and users.

### ISSUE THREAD

**Issue by mohanchen** [deepmodeling/abacus-develop#487]
## Describe Current Status and Possible Solution

Currently, we need to teach basic knowledge to new ABACUSers face-to-face, this is inefficient. We need to have some detailed documents for these guys.

## Additional Context

Documents/examples/videos/tutorials obtained from a Hands-on workshop for ABACUS (when will it be ready? 2.2 version? maybe with Lebesgue?)

This should be done approximately before 2022-02-28

Mark this and we will do it.

**Comment by dyzheng** [comment]
[1_epsilon.pdf](https://github.com/deepmodeling/abacus-develop/files/7686775/1_epsilon.pdf)
There is linear-responce TDDFT documentation for ABACUS related code, we should add autotest for test it.
