### ISSUE TITLE
noncolliner + SOC calculation is not converged in SnTe

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#4876]
### Describe the Testing Issue

Inputs and results:
[u.zip](https://github.com/user-attachments/files/16489660/u.zip)

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by WHUweiqingzhou** [comment]
By decreasing `mixing_beta`, I notice the SCF can reach `drho`~1e-5 and `dene`~1e-8, which can be treated as convergence.
```bash
INPUT_PARAMETERS
suffix	SnTe
calculation	scf
esolver_type	ksdft
symmetry	-1
init_chg	atomic
ecutwfc	100
basis_type	lcao
ks_solver	genelpa
nspin	4
lspinorb	1
noncolin	1
smearing_method	gauss
smearing_sigma	0.01

mixing_beta	0.01
mixing_ndim     40

scf_nmax	200
scf_thr	1e-6    

```
