### ISSUE TITLE
Scf convergence of HSE hybrid functional is hard for the BBO system.

### ISSUE THREAD

**Issue by YuLiu98** [deepmodeling/abacus-develop#488]
## Describe Current Status and Possible Solution

Scf convergence of HSE hybrid functional is hard for some systems such as the BBO system. 
[BBO_test.zip](https://github.com/deepmodeling/abacus-develop/files/7615070/BBO_test.zip)

It is difficult for users to tune so many parameters, which need to be improved.

## Additional Context

Add any other context or screenshots about the enhancement here.

**Comment by hongriTianqi** [comment]
The STRU file in this example is set by misunderstanding the parameter LATTICE_CONSTANT in STRU file, which is in unit of Bohr in ABACUS.

**Comment by YuLiu98** [comment]
When the lattice constant is corrected, HSE scf is converged with original parameters.
