### ISSUE TITLE
The stress of LCAO SOC seems wrong

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#4884]
### Describe the bug

I have do the stress finite difference test on FeRh and NiMnTi, and the deviation between analytical stress and finite difference stress is larger than 1 kbar.

example | noncollinear + SOC | noncollinear
---|---|---
FeRh| ![2be4c81e41368ee18c13c98e4dd6e712_4uXIwiJ0HsDAAAAAElFTkSuQmCC](https://github.com/user-attachments/assets/86e593cb-ea32-4d02-b4ba-3566fd120462) |  ![image](https://github.com/user-attachments/assets/e145f282-6331-452e-aeb4-33bc2d58df63) 
NiMnTi |  ![b6696eef1d400db478aa7bd14b99381d_aMAAAAASUVORK5CYII=](https://github.com/user-attachments/assets/8ac555c4-fc33-4be4-bc80-ae7c42dbe8ee) |  ![4fa4b14be6bdee6464b6a16fcb275160_zftSQd1jAAAAAElFTkSuQmCC](https://github.com/user-attachments/assets/541e2527-df77-4cd6-83be-fa4ed28981c3)

 

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by pxlxingliang** [comment]
The inputs and outputs of FeRh
[a.zip](https://github.com/user-attachments/files/16509033/a.zip)

**Comment by WHUweiqingzhou** [comment]
this issue has been solved in our private branch, and will be closed until the PR is merged.
