### ISSUE TITLE
Is ABACUS able to run with DPGEN and generate sufficiently accurate DP potentials?

### ISSUE THREAD

**Issue by mohanchen** [deepmodeling/abacus-develop#489]
## Background
In the near future, ABACUS should be able to run on new machines such as GPUs, then it will be possible to provide computationally less costly data to generate DP potentials. However, we would like to ask a question, is it possible to generate sufficiently accurate DP potentials with numerical atomic orbitals?

## Describe the solution you'd like
We have implemented an interface between ABACUS and DPGEN, now we need to have more tests to demonstrate that ABACUS is able to generate usable DP potentials.

Note that it will be better to have the next-generation numerical atomic orbitals.

## Additional context
Any suggestions for the practical systems will be welcome. Metals, alloys, semiconductors?

**Comment by pxlxingliang** [comment]
The interface between ABACUS and DPGEN is already be added in the lasted DPGEN. We have tested the most commonly used functions `init_bulk`, `run` and `autotest`, and all of them are worked well. 
We have trained the DP potential of Al by DPGEN+ABACUS (both PW and LCAO basis), and the results of DP-test are acceptable and the calculated properties (such as lattice parameter, EOS) by this DP potential are comparable with those calculated by ABACUS and VASP.
