### ISSUE TITLE
The stress of PW SOC is wrong

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#4890]
### Describe the bug

I have do the finite difference test on Fe2 with noncollinear and SOC, and the deviation between analytical value and finite difference value is large, and the finite difference value is close to that by QE

![ca49097e360a8f46bd6d269da933e4dc_60d24f50-7564-4bef-961a-58202368c108](https://github.com/user-attachments/assets/4052b25c-8f58-4c5b-89e7-7103dfb71cb3)

The stress by different methods
  | 11 | 22 | 33
-- | -- | -- | --
ABACUS-Ana | 60.302 | 60.302 | 60.312
ABACUS-FD | 53.528 | 53.530 | 53.490
QE | 53.627 | 53.627 | 53.576

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
This issue has been solved in our private branch, and will be closed until that PR merges.
