### ISSUE TITLE
Stress calculation result is incorrect

### ISSUE THREAD

**Issue by dzzz2001** [deepmodeling/abacus-develop#4899]
### Describe the bug

When running ABACUS, I noticed that for the same test case, the stress values from different runs are inconsistent. For example, below are the stress results from running the P101_Si32_lcao example in the tests/performance directory twice:
![image](https://github.com/user-attachments/assets/e5af4979-cd11-4113-9f57-b0d4bfde3c33)
![image](https://github.com/user-attachments/assets/8ba1538b-245f-4af9-bf5c-99e06c432e4b)
the correct result should be:
![image](https://github.com/user-attachments/assets/6095f8e6-77c1-4911-abd4-4037b3d80578)

By tracing back through commits, I found that the bug was introduced in PR #4854. @grysgreat Could you have a look?

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by grysgreat** [comment]
Sure~ I'll try to figure out.

**Comment by dzzz2001** [comment]
**P.S.** The calculation error only occurs when using multiple threads; it does not happen with a single thread.

**Comment by grysgreat** [comment]
The error occurs on CPU, GPU or Both?

**Comment by dzzz2001** [comment]
both

**Comment by grysgreat** [comment]
I pulled the latest code for testing, and the results on the CPU/GPU with single core and multiple cores are correct. 
My test instructions are:

Single MPI:`mpirun --allow-run-as-root -np 1 abacus `
Multi MPI and OMP: `OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 OMPI_MCA_btl_vader_single_copy_mechanism=none OMP_NUM_THREADS=8 mpirun --allow-run-as-root -np 4 abacus`


My test environment is： bohrium docker node 8 Core 31 GB 1 * NVIDIA T4.
Could you please give me more detailed test instructions and how to reproduce this error?

**Comment by grysgreat** [comment]
![image](https://github.com/user-attachments/assets/9e31b713-e3c1-4fc0-8ace-0917568f7b65)

**Comment by dzzz2001** [comment]
My instruction is "OMP_NUM_THREADS=7 mpirun -n 4 abacus", and the device is "CPU: Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz * 2".

**Comment by dzzz2001** [comment]
I'll try reproducing this issue on other machine.

**Comment by dzzz2001** [comment]
I found that the bug only appears when ABACUS is compiled with icpc; there are no issues when compiled with icpx or gcc. My icpc version is 2021.10.0.20230609

**Comment by grysgreat** [comment]
That's weird, I just tested it with your input and the results were correct. My compiler is GNU-GCC.

**Comment by grysgreat** [comment]
> I found that the bug only appears when ABACUS is compiled with icpc; there are no issues when compiled with icpx or gcc. My icpc version is 2021.10.0.20230609

How about the gpu environment when test?

**Comment by dzzz2001** [comment]
> That's weird, I just tested it with your input and the results were correct. My compiler is GNU-GCC.

I have also tested ABACUS compiled by GCC and the result is correct. Error appears only if ABACUS is compiled with ICPC.

**Comment by dzzz2001** [comment]
> > I found that the bug only appears when ABACUS is compiled with icpc; there are no issues when compiled with icpx or gcc. My icpc version is 2021.10.0.20230609
> 
> How about the gpu environment when test?

CUDA version on my computer is 12.4.

**Comment by dzzz2001** [comment]
I tested on different computers, and the issue consistently occurs whenever ABACUS is compiled with icpc.

**Comment by grysgreat** [comment]
> I tested on different computers, and the issue consistently occurs whenever ABACUS is compiled with icpc.

I found a bug that might cause errors in OpenMPI calculations, but this only affects CPU calculations, not Gpus. Can you try this to have a test?

**Comment by dzzz2001** [comment]
> > I tested on different computers, and the issue consistently occurs whenever ABACUS is compiled with icpc.
> 
> I found a bug that might cause errors in OpenMPI calculations, but this only affects CPU calculations, not Gpus. Can you try this to have a test?

I pulled the code from your repository, and both the GPU and CPU computation results are correct.
