### ISSUE TITLE
The bands calculated by HSE  are very strange

### ISSUE THREAD

**Issue by Chentao168** [deepmodeling/abacus-develop#4907]
### Describe the bug

![image](https://github.com/user-attachments/assets/09de13e4-6179-483d-9aa0-4bd04861654c)
The band structure calculated using HSE differs significantly from those obtained with PBE and SCAN functionals in 21 atoms IGZO.

### To Reproduce

[20240808-hse-bug.zip](https://github.com/user-attachments/files/16571965/20240808-hse-bug.zip)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by kirk0830** [comment]
Could you please do this thing:
![img_v3_02d8_ca51a6a9-bbe6-4e26-83b0-b80704cf036g](https://github.com/user-attachments/assets/5d847b94-d88e-43f7-a17b-751eee6c138d)
and check the change of condnum of H during SCF by this following script?
```python
import numpy as np

nbasis = 26 # use the nbasis you use
nbands = 26 # use the nbands you use
h_traj = np.loadtxt('h_mat.txt').view(complex)
s_traj = np.loadtxt('s_mat.txt').view(complex)

h_traj = h_traj.reshape(-1, nbasis, nbasis)
s_traj = s_traj.reshape(-1, nbasis, nbasis)
print(h_traj.shape, s_traj.shape)
eignvals, _ = np.linalg.eigh(s_traj[0])
print(f"The smallest 3 eigenvalues of the first S matrix: {eignvals[:3]}")
num_scf = h_traj.shape[0]
# check
for i in range(num_scf):
    h = h_traj[i]
    s = s_traj[i]
    # check condition number of h and s
    h_condnum = np.linalg.cond(h)
    s_condnum = np.linalg.cond(s)
    # check hermiticity
    assert np.allclose(s, s.conj().T, rtol=1e-14)
    print(f"SCF {i+1:3d} H condnum: {h_condnum:10.2f}, S condnum: {s_condnum:10.2f}")
```
I think there is something unexpected happens.

**Comment by PeizeLin** [comment]
According to the bands, it seems that maybe too few k-points are used when SCF. You can try to increase the k-points.
In addition, maybe you can set `symmetry=-1` and `mixing_type=pulay` in INPUT to avoid potential undefined risks.

**Comment by Chentao168** [comment]
![img_v3_00dl_9580b59d-b28d-4ccb-9f2d-8bf1c4f8f37g](https://github.com/user-attachments/assets/d0c4e2d0-f5bd-4138-bfe7-b18823aab028)
I suspect it's an issue with NSCF. I used k points of 6 * 6 * 1 and 10 * 10 * 1 for SCF and set the output DOS to out_dos without any problem. However, when I tried NSCF, I found that both DOS  were incorrect.

**Comment by maki49** [comment]
Did you forget to upload the STRU file in your archive... ?

**Comment by Chentao168** [comment]
> Did you forget to upload the STRU file in your archive... ?

I have uploaded the STRU file.

**Comment by maki49** [comment]
Running NSCF with 6*6*1 kpoints gives the same dos as SCF. 
Maybe the problem lies in the line of kpoints used in NSCF?
![DOS](https://github.com/user-attachments/assets/d55f65ca-7d04-4aca-87bd-61967e1f57cd)

**Comment by WHUweiqingzhou** [comment]
I close this issue due to no further update from @Chentao168. Please feel free to reopen it.
