### ISSUE TITLE
 NOT recognizes the default XC_Functional.

### ISSUE THREAD

**Issue by meishengme** [deepmodeling/abacus-develop#4909]
### Describe the bug

When using the HGH pseudopotential in the pseudopotential dataset,  Abacus can not recognizes the default XC_Functional.
error: XC_Functional::set_xc_type_libxc  warning : functional name not recognized!

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by kirk0830** [comment]
abacus will check xc_functional key by itself, seems not necessary. The value of this key in HGH pseudopotential is "SLA-PW-PBX-PBC", this is the notation always used by QE. You can find information in QE source code here:
`/q-e/upflib/hgh2qe.f90`

Plus, HGH is a somewhat out-dated pseudopotential family.

**Comment by mohanchen** [comment]
I will close this issue. If you have new questions, welcome to open a new issue.
