### ISSUE TITLE
Scalapack eigenvalue solver would be called twice in one electronic step, this would waste time! 

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#491]
The scalapack eigenvalue solver in ABACUS (hs_solver = scalapack_gvx) need to specify how many degeneracies does hamiltonian matrix have. If the default number 12 is too small, the function would be called twice.

**Comment by mohanchen** [comment]
We can test a lot of systems (for example, semiconductors, metals and alloys) and choose a best value for the degeneracies (for example, 50?) @dyzheng

**Comment by dyzheng** [comment]
> 
Okay, the degeneracies sometimes looks weird. I should find someway to check if the demand number of degeneracies from scalapack is correct.

**Comment by dyzheng** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>



512Si-system | 2step-scf测试 | scalapack实际调用次数 | 平均每次用时
-- | -- | -- | --
  | 8269CY-16c | 2 | 50
  | 8269CY-8c | 3 | 45
  | 8269CY-4c | 3 | 66
  | 8269CY-3c | 3 | 85
  | 8269CY-2c | 3 | 1.20E+02
  | 8269CY-1c | 2 | 2.00E+02



</body>

</html>

**Comment by mohanchen** [comment]
Any progress on this issue? @dyzheng

**Comment by mohanchen** [comment]
@dyzheng could you provide an example for the 'call twice' issue?

**Comment by dyzheng** [comment]
The example in #590 can repeat this error either.
[error.zip](https://github.com/deepmodeling/abacus-develop/files/8040499/error.zip)
In this case, "mpirun -np 7 abacus" can repeat this error, but "mpirun -np 8 abacus" can't.
```
    ITER   ETOT(eV)       EDIFF(eV)      DRHO2      TIME(s) 
    /root/abacusmodeling/abacus-develop/source/src_pdiag/diag_scalapack_gvx.cpp179
    /root/abacusmodeling/abacus-develop/source/src_pdiag/diag_scalapack_gvx.cpp179
     GV1    -5.334226e+04  0.000000e+00   1.056e-01  2.619e+02  
    /root/abacusmodeling/abacus-develop/source/src_pdiag/diag_scalapack_gvx.cpp179
     GV2    -5.780119e+04  -4.458921e+03  1.295e-01  2.104e+02  
    /root/abacusmodeling/abacus-develop/source/src_pdiag/diag_scalapack_gvx.cpp179
     GV3    -5.783546e+04  -3.427327e+01  1.472e-01  2.103e+02 
```

**Comment by wenfei-li** [comment]
This is not a bug. It is necessary when there are too many degeneracies. If we are not satisfied with the treatment, we can increase starting guess of degeneracy from 12 to something larger. But this issue will be closed.
