### ISSUE TITLE
ABACUS KS eigen energies appear much lower with CP2K's pseudopotential & basis

### ISSUE THREAD

**Issue by Fisherd99** [deepmodeling/abacus-develop#4911]
### Describe the Testing Issue

I tried to run ABACUS (ver3.7.2) with CP2K's GTH pseudopotential and cc-pVTZ basis set. For pseudopotential, I used CP2k's ATOM module to generate .upf file. For basis, I generate .orb file with numerical Gaussian function tabulate. I suppose the results will be in accordance roughly, but I found for Na2 molecule something weird happens.

Here provides my test result of Na2, Li2, C2H4 molecule with PBE. It shows that rsults in column 2,3,4 of Na2 molecule are much lower than normal results.

![image](https://github.com/user-attachments/assets/3698cf83-9702-439d-aaa3-26e7a6f15a8c)

Input files for Na2, Li2, CH4 molecules are provided in attachment [ABACUSvsCP2K.zip](https://github.com/user-attachments/files/16537965/ABACUSvsCP2K.zip). NOTICE: in order to use cc-pVTZ basis, one should modify `module_basis/module_nao/numerical_radial.cpp` in line 172 as following, otherwise the absolute value less than 1e-15 in cc-pVTZ will cause error.
```c++
    //orbital_lm.set_orbital_info(symbol_, itype_, l_, izeta_, std::min(nr_, ircut_+1), rab, rgrid_,
    orbital_lm.set_orbital_info(symbol_, itype_, l_, izeta_, nr_, rab, rgrid_,
```

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by Fisherd99** [comment]
It seems that the problem partly may be caused by insufficient RCUT in ccpVTZ orbital file. I enlarge it from 8au to 24au, figures below are Li and Na.

![Li-ccpVTZ](https://github.com/user-attachments/assets/322f3bbd-fc44-4580-9842-79862fdbf6f3)
![Na-ccpVTZ](https://github.com/user-attachments/assets/d5b4e3b5-5717-4eb3-86b8-011e0f1f06e9)
**DOWNLOAD ORB FILE HERE: [cc-pVTZ-24au.zip](https://github.com/user-attachments/files/16593537/cc-pVTZ-24au.zip)**

Also I add ECUTWFC to 300Ry. For now results are much better, but still something weird in Na2.

![image](https://github.com/user-attachments/assets/9f5f14ca-5563-427f-8d8a-5d59b97f2953)

**Comment by kirk0830** [comment]
@AroundPeking used to mention a novel family of pseudopotential called ccECP, may be that will work for Na dimer system
