### ISSUE TITLE
how to postprocess xml file?

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#4912]
### Details

some output file of ABACUS is in the xml format, for example:
If “out_proj_band” set 1, it will also produce the projected band structure in a file called PBAND_1 in xml format.
Is there any provided tools for postprocessing xml file?

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by kirk0830** [comment]
you can simply use the in-built `xml` library of python
