### ISSUE TITLE
101_PW_Coulomb：the energy difference of ABACUS and QE

### ISSUE THREAD

**Issue by meishengme** [deepmodeling/abacus-develop#4913]
### Describe the Testing Issue

Based on abacustest, when calculating 101_PW_Coulomb using ABACUS and QE, there is a big difference in the results of the energy：
abacus：2.5197177275430334  
qe：12.06457655833250

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by mohanchen** [comment]
Could you tell us what's the example? Could you upload the files? @meishengme

**Comment by Qianruipku** [comment]
In fact, the difference comes from the PWLDA XC functional, but not Coulomb. Thanks for this issue @meishengme. The next discussion can be moved to #5591.
