### ISSUE TITLE
Differences of force and stress between ABACUS and QE

### ISSUE THREAD

**Issue by meishengme** [deepmodeling/abacus-develop#4914]
### Describe the Testing Issue

There is a clear difference between forces and stresses when using Abacus and QE to calculate structural optimizations.
                                         abacus/force               qe/force            abacus/stress           abacus/stress
108_PW_RE                         5.171153           0.050307131             801.33330             370.0818556
108_PW_RE_MB                   6.582841            0.154674016   
109_PW_CR_fix_a                 0.058887            0.00147380               348.16950             149.9037047
109_PW_CR_fix_ab               0.083326           0.001473803             352.06580             149.9037047
109_PW_CR_fix_abc             0.000000            0.001473803             350.99000              149.9037047
109_PW_CR_fix_ac               0.083578            0.001473803             352.04620              149.9037047
109_PW_CR_fix_b                0.059004            0.001473803             348.16250              149.9037047
109_PW_CR_fix_bc               0.083429          0.001473803             352.06930               149.9037047
109_PW_CR_fix_c                 0.058676           0.001473803            348.18910               149.9037047
109_PW_CR_moveatoms     0.000000           0.001473803             342.18700               149.9037047

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by mohanchen** [comment]
There examples are from ABACUS, how did you calculate them using QE, could you provide QE files? Thanks.

**Comment by mohanchen** [comment]
We will close this issue, if you have more questions, please propose a new issue. Thank you.
