### ISSUE TITLE
mag of metal Ni seems unreasonable

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#4918]
### Describe the bug

we find a small 0.16 uB mag moment in FCC Ni, the experimental result and VASP result are 0.6 uB.

https://www.vasp.at/wiki/index.php/Fcc_Ni_(revisited)

### Expected behavior

[ni.tar.gz](https://github.com/user-attachments/files/16539153/ni.tar.gz)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by Shen-Zhen-Xiong** [comment]
Ni is a very cruising metal, and it is necessary to be very careful to set the smearing_sigma and higher density of the K-point when it is self-consistent, and the large smearing_sigma get a false result. Let's take a look at the example, I use a smearing_sigma of 0.01 to calculate the magnetic moment is 0.71ub, and at the same time encrypt the K point to 8 8 8, and the calculated magnetic moment is 0.64ub, which is consistent with the experimental results.
[v20240813_Ni4.tar.gz](https://github.com/user-attachments/files/16593544/v20240813_Ni4.tar.gz)
