### ISSUE TITLE
In multi-k calculation, there are too many eigenvalue outputs in OUT.suffix/running_calculation.txt, should we move them to where else?

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#492]
In order to simplify the output file in ABACUS, maybe we can do:
1. only output some bands around fermi energy, such as only output 5 bands above E-fermi and 5 bands below E-fermi;
2. only output occupied bands;
3. output all eigenvalues to a new file, such as named "eigenvalue_display.dat".

**Comment by mohanchen** [comment]
I think maybe we can add a flag, the flag determines whether the eigenvalues are printed only when the self-consistent charge density is obtained. If the users want to print out the eigenvalues for every scf iteration (for example, for debugging), there should also be a choice for the users.

**Comment by mohanchen** [comment]
@dyzheng

**Comment by dyzheng** [comment]
> 

A flag is certainly needed for user to choose, but another case is that user calculated MD or relax and don't need any eigenvalues.
Maybe we should add two flags for them respectively?

**Comment by mohanchen** [comment]
I think it is an interesting idea, maybe we can try that. @dyzheng

**Comment by wenfei-li** [comment]
Seems we are not in urgent need to try this.

**Comment by sunliang98** [comment]
Currently, ABACUS outputs the eigenvalues to both the `running.log` and a separate file `istate.info`. Maybe we can close this Issue. @dyzheng
