### ISSUE TITLE
how to cancel output charge density  in an append manner?

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#4928]
### Details

According to https://github.com/deepmodeling/abacus-develop/pull/4889,  If `iter` is set to 0, the file will be clear and rewritten; otherwise, info is printed into it in an append manner.
My question is: which input parameter is `iter`?

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by YuLiu98** [comment]
There is no input parameter named `iter`. `iter` is the current ionic step.

The charge density file always starts from the first ion step. So, if there is already a charge density file, it will be rewritten when you start a new calculation.

Thus, the charge density file is always rewritten in single-point calculations. In MD calculations, the output frequency is controlled by the input parameter `out_interval`. For example, if `out_interval` is set to 5, then the charge density file contains the charge density of step 0, 5, 10....
