### ISSUE TITLE
Can the output of `out_wfc_r` be changed to standard Gaussian CUBE files?

### ISSUE THREAD

**Issue by AsTonyshment** [deepmodeling/abacus-develop#4938]
### Background

In the current version of ABACUS, when `out_wfc_r = 1` is enabled, a set of `wfc_realspace_*` files is generated in the `wfc_realspace` folder. However, these files are not in the standard Gaussian CUBE format, and I am unsure how to visualize them.

### Describe the solution you'd like

Can the output of `out_wfc_r` be changed to standard Gaussian CUBE files?

**Comment by kirk0830** [comment]
Yes I think so. I checked the implementation of this functionality and find the file organizes information in a casual way. There are also other quantities output in that way.
But as for the cube file, I think there is still a problem that we need to avoid the case like issue #4844
