### ISSUE TITLE
Too many Compilation Warnings generated in esolver module

### ISSUE THREAD

**Issue by Cstandardlib** [deepmodeling/abacus-develop#4943]
### Describe the Code Quality Issue

Many warnings are generated during compilation, disrupting the normal process of locating compilation errors in development.
```cpp
In file included from /abacus-develop/source/module_io/input_conv.cpp:8:
In file included from /abacus-develop/source/module_hamilt_general/module_surchem/surchem.h:11:
In file included from /abacus-develop/source/module_hamilt_pw/hamilt_pwdft/global.h:9:
In file included from /abacus-develop/source/module_relax/relax_driver.h:5:
/abacus-develop/source/module_esolver/esolver_ks.h:73:22: warning: 'after_scf' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
   73 |         virtual void after_scf(const int istep);
      |                      ^
/abacus-develop/source/module_esolver/esolver_ks_lcao.h:25:32: note: in instantiation of template class 'ModuleESolver::ESolver_KS<std::complex<double>>' requested here
   25 | class ESolver_KS_LCAO : public ESolver_KS<TK> {
      |                                ^
/abacus-develop/source/module_esolver/esolver_ks_lcao_tddft.h:12:38: note: in instantiation of template class 'ModuleESolver::ESolver_KS_LCAO<std::complex<double>, double>' requested here
   12 | class ESolver_KS_LCAO_TDDFT : public ESolver_KS_LCAO<std::complex<double>, double>
      |                                      ^
/abacus-develop/source/module_esolver/esolver_fp.h:68:22: note: overridden virtual function is here
   68 |         virtual void after_scf(const int istep);
      |                      ^
```
They are related to 'after_scf' override in esolver.
I kindly request that the development team reviews the compilation warnings and takes necessary action to resolve or reduce them.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by Cstandardlib** [comment]
currently it can be depressed by setting
```cmake
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-inconsistent-missing-override")
```
or
```cmake
add_compile_options(-Wno-inconsistent-missing-override)
```
in CMakeLists.

**Comment by kirk0830** [comment]
I think this kind of warnings are from the lost control of development of ESolver. There are developers make the ESolver deviate the doctrine/design/philosophy of programming this class that "input structure, output energy". The abuse of inheritance, especially the ESolver, has been continuing making the code structure more and more complicated, so a practical plan is needed to sort everything good.

**Comment by WHUweiqingzhou** [comment]
Thanks for your feedback, we will think about it.
