### ISSUE TITLE
lattice symmetry inconsistency between INPUT and output

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#495]
## Describe the Bug
lattice symmetry inconsistency between INPUT and output for bcc, trigonal, bct, fco, bco, bacm in both pw and lcao base

## To Reproduce
One needs to set the "symmetry" tag in INPUT file to 1 to ask abacus do symmetry analysis.
grep BRAVAIS   $EXAMPLE_DIR/OUT.autotest/running_scf.log

In 803 and 817, INPUT-bcc, output-triclinic
In 805 and 819, INPUT-trigonal, output-face centered cubic
In 807 and 821, INPUT-bct, output-triclinic
In 810 and 824, INPUT-fco, output-triclinic
In 811 and 825, INPUT-bco, output-based centered monoclinic (should be body-centered orthorhombic)
In 813 and 827, INPUT-bacm, output-triclinic
[lattice_symmetry_bug.tar.gz](https://github.com/deepmodeling/abacus-develop/files/7618489/lattice_symmetry_bug.tar.gz)

**Comment by mohanchen** [comment]
@hongriTianqi @dyzheng We had an independent module that can do symmetry tests, try to reproduce these errors with that module. For that module, we (actually, Xiaohui Liu) had prepared around 100 tests and he mentioned that all the tests have passed, so this issue is a bit strange...

**Comment by dyzheng** [comment]
> 

I need to check what this problem exactly was. Maybe the autoset lattice vectors is incorrect.

**Comment by dyzheng** [comment]
[symmetry_prec-examples.tar.gz](https://github.com/deepmodeling/abacus-develop/files/7619357/symmetry_prec-examples.tar.gz)
[symmetry_prec-results.xlsx](https://github.com/deepmodeling/abacus-develop/files/7619361/symmetry_prec-results.xlsx)
These 100 tests for symmetry used to be tested, which output symmetry and input symmetry is equally.

**Comment by hongriTianqi** [comment]
> @mohanchen @dyzheng The 100 tests do not cover all 14 Bravais lattices, but only 7 of them. The covered ones are: simple cubic (sc), hexagonal, simple tetrogonal (st), simple monoclinic (sm), triclinic, trigonal, and simple orthorhombic.

**Comment by mohanchen** [comment]
OK, xiaohui is looking into this problem.

**Comment by hongriTianqi** [comment]
> OK, xiaohui is looking into this problem.

Dr Xiaohui give the following instructions to solve this problem, editing module_symmetry/symmetry.cpp:
1) do not comment line 707: brav=temp_brav;
2) do not comment an else ... if block between 774-808;
3) comment line 809: brav = pre_brav;

Now the inconsistency problem can be solved. But these lines are not bug because they are import to get correct force symmetry analysis in current version of ABACUS. This needs more discussions to improve code further.

**Comment by dyzheng** [comment]
Hi @hongriTianqi , the issue caused by the actual structure is what ABACUS symmetry module output. 
It is possible that setting "latname = A", but the actual structure is B with higher symmetry.
The symmetry analysis for these cases is same between ABACUS and QE or VASP.

**Comment by hongriTianqi** [comment]
Now I found consistent results in the following integrated tests by setting "symmetry" to 1 in INPUT:
In 803 and 817, INPUT-bcc, output-bcc
In 807 and 821, INPUT-bct, output-bct
In 810 and 824, INPUT-fco, output-fco
In 811 and 825, INPUT-bco, output-bco
In 813 and 827, INPUT-bacm, output-bacm

Inconsistency still appear in 805 and 819, INPUT-trigonal, output-face centered cubic. However, higher symmetry in output than in INPUT is acceptable.

I also see the following warning info in running_scf.log:
"Warning : If the optimal symmetric configuration is not the input configuration, 
you have to manually change configurations, ABACUS would only calculate the input structure!"

The above updates are acceptable to me, so I will close this issue. Thanks.
