### ISSUE TITLE
unreasonable potential energy surface of NiMnTi by LCAO

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#4957]
### Describe the bug

I try to do the finite difference force test on NiMnTi with nspin=4 noncollinear, and the position of Ni is moved along X axis with 0.01 bohr each step.
As shown in below blue line, the energy of the center point is abnormal high.
![f2ff0fa16e89c7179c8888bf1fcc4019_c8ce21e4-2c5e-4968-8cf7-e788c20e147a](https://github.com/user-attachments/assets/72a25462-1d95-452b-aa11-2f81a48acd45)

The PES of nspin2 is also abnormal:
![e9a3c020201640544fb3efd218795d27_dbd655c9-2c90-42ba-8bde-0bf00829cf25](https://github.com/user-attachments/assets/105697e2-236b-440c-8070-6b3d269ee62f)

While the PES of PW seems reasonable:
nspin2:
![a434e500e22a3cbb6f05a01e3202eec1_bc742519-7aa4-4fa1-b0fa-2d9554fb5caa](https://github.com/user-attachments/assets/03f818eb-71fa-4d9b-b5ed-5cb6268a5f21)

nspin4:
![747d0ac2d4c06dfedecb305ba4cb1f8d_de8f7436-1eb1-4d19-b257-89209ca52493](https://github.com/user-attachments/assets/0ac9e83e-945f-428c-9220-c2a8adb5f675)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
plz try to increase `ecutwfc` @pxlxingliang
