### ISSUE TITLE
wrong result of matrix multiplication using scalapack in tddft module

### ISSUE THREAD

**Issue by lyb9812** [deepmodeling/abacus-develop#496]
## Describe the Bug
When I rewrite the module of tddft , I need to do the matrix multiplication of the wavefunction and U operator, and obtain a wrong result using scalapack. 
The operation to call scalapack is the same as the operations of calculating U operator.
The wavefunction is in 2D format as in pdiag module.

**Comment by mohanchen** [comment]
We need to have unit tests for Scalapack, @dyzheng @pxlxingliang

**Comment by lyb9812** [comment]
The problem is solved. The result of the matrix multiplication of wavefunction and U operator need to be stored in another array, not in the original wavefunction.

**Comment by mohanchen** [comment]
Good.
