### ISSUE TITLE
Inconsistent Handling of Matrix Blocks in `hpsi_func`

### ISSUE THREAD

**Issue by a1henu** [deepmodeling/abacus-develop#4961]
### Describe the Code Quality Issue

**Background**:

In the `module_hsolver`, we are tasked with solving the eigenvalue problem for the Hamiltonian. This typically requires applying the Hamiltonian to a set of wave functions, which can be mathematically represented as a "matrix-matrix block multiplication." The operation involves calculating the action of the Hamiltonian on wave functions within a specific range of energy bands.

Mathematically, this can be expressed as:

$$X_{block}^{out}=\hat{H} \Psi_{block}^{in}$$
 
where:
- $\hat{H}$ is the Hamiltonian matrix .
- $\Psi_{block}^{in}$ is the matrix of wave functions for those bands.
- $X_{block}^{out}$ is the resulting block matrix after applying the Hamiltonian.

**Problem**:

Usually, in [`hsolver::Diago_DavSubspace`](https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_hsolver/diago_dav_subspace.h#L14) and [`hsolver::David`](https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_hsolver/diago_david.h#L11), the function `hpsi_func` is called.

However, the current implementation of `hpsi_func` exhibits [inconsistent handling of input and output matrix blocks](https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_hsolver/diago_dav_subspace.cpp#L363). 
```cpp
hpsi_func(&hphi[nbase * this->dim], psi_iter, this->nbase_x, this->dim, nbase, nbase + notconv - 1);
```
When calling the function, the input matrix (`psi_in`) is passed as a pointer to the first element, with the block operations performed inside the function. However, the output matrix (`hpsi_out`) is passed as a pre-calculated pointer to a specific offset, implying that the block operations are handled externally. This inconsistency complicates the interface, increases the risk of errors, and makes the code harder to maintain.

**Suggested Improvements**:

- Consistent Interface Design: Ensure that `hpsi_func` handles both `psi_in` and `hpsi_out` in a consistent manner, preferably by performing block operations within the function for both input and output matrices.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by haozhihan** [comment]
https://github.com/deepmodeling/abacus-develop/issues/5178
