### ISSUE TITLE
The deviation between finite difference and analysis is large for LCAO stress

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#4965]
### Describe the Testing Issue

I have done the finite difference (FD) test of stress for NiMnTi with LCAO. 
The step of cell deform is 0.0001.

The deviation between FD and analysis is about 2 kbar, while in PW, the deviation is only about 0.15 kbar.

bohrium app job: https://bohrium.dp.tech/apps/abacustest/job?type=jobs&jobId=22571

![bef1cb304ef16c25efa8954b987b1826__preview_type=16](https://github.com/user-attachments/assets/28f2b641-baa2-4edf-b4e2-d92969702abf)

PW:
![f7537462fe11504679421ba83b0953bf_28a03733-b84f-4c79-b5f2-739461e77dd2](https://github.com/user-attachments/assets/b2134e3e-67a3-4a97-875e-79cc48f1f6ed)

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by mohanchen** [comment]
It would be better to describe conditions for the tests. @pxlxingliang

**Comment by pxlxingliang** [comment]
The INPUT for LCAO is:
```
INPUT_PARAMETERS
suffix    ABACUS

calculation   scf
ecutwfc    200
scf_thr    1.0e-6
scf_nmax 100

smearing_method    gaussian
smearing_sigma    0.05


mixing_type    broyden
mixing_beta    0.2

ks_solver    genelpa
basis_type    lcao
gamma_only    0
symmetry    0
noncolin   0
nspin    1

out_bandgap 1
out_chg 0
out_mul 1

kspacing 0.2
cal_stress 1

```
