### ISSUE TITLE
Error when doing MD with freezing partial of atoms

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#497]
## Describe the Bug
when doing MD with freezing partial of atoms, some values (like NVT Conservation/NVT Kinetic energy) are "-nan"

[mderror.zip](https://github.com/deepmodeling/abacus-develop/files/7624047/mderror.zip)

INPUT:
INPUT_PARAMETERS
#Parameters (General)
suffix          autotest
ntype           1
nbands          8
calculation     md
#Parameters (Accuracy)
ecutwfc         20
niter           50
dr2             1.0e-8
basis_type      pw
nstep           4
stress          1
stress_thr      1e-6
force           1
force_thr_ev    1.0e-3
mixing_type     pulay
mixing_beta     0.7
charge_extrap  first-order

STRU:
ATOMIC_POSITIONS
Cartesian       #Cartesian(Unit is LATTICE_CONSTANT)
Si          #Name of element
0.0         #Magnetic for this element.
2           #Number of atoms
0.00 0.00 0.00 0 0 0    #x,y,z, move_x, move_y, move_z
0.25 0.25 0.25 1 1 1

running_md.log
...
 --------------------------------------------------
 Molecular Dynamics (NVT) STEP 1
 --------------------------------------------------
--------------------------------------------------
            SUMMARY OF NVT CALCULATION
 --------------------------------------------------
 NVT Conservation     :       -nan (Rydberg)
 NVT Temperature      :       -nan (K)
 NVT Kinetic energy   :       -nan (Rydberg)
 NVT Potential energy : -15.567031 (Rydberg)
 maxForce             :  +0.000000
 maxStep              :  +0.000000
...

output:
...
 notconv = 8
 Hamilt::diago', too many bands are not converged!

 notconv = 8
 Hamilt::diago', too many bands are not converged!
...

**Comment by mohanchen** [comment]
@YuLiu98 could you please check this problem?

**Comment by YuLiu98** [comment]
Due to the fixed mass center and one fixed atom, the total freedom of the system (2 atoms in total) is **zero**, which is used as denominator in the calculation of temperature, resulting in the presence of the error.

**Comment by YuLiu98** [comment]
There are some alternative solutions:
1) Quit out when the freedom is zero.
2) When no atom is fixed, the mass center is set to be fixed, otherwise the mass center is unfixed.
