### ISSUE TITLE
SCF calculations for the Nd₂Fe₁₄B system run successfully in ABACUS 3.6.4, but an error occurs in ABACUS 3.7.3.

### ISSUE THREAD

**Issue by zhubro321** [deepmodeling/abacus-develop#4970]
### Describe the bug

When using ABACUS for SCF calculation on the Nd₂Fe₁₄B system, the ABACUS 3.7.3 fails to run, with the error details shown in the warning.log file.
[warning.log](https://github.com/user-attachments/files/16643736/warning.log)
last line : **GlobalC::wf.atomic_wfc()  warning : index != GlobalC::ucell.natomwfc**

However, the same input files can run successfully in ABACUS 3.6.4, though the running efficiency is significantly low(The first electronic step took an hour to run). The input files and corresponding output files are located in the OUT folder.
[OUT.zip](https://github.com/user-attachments/files/16644294/OUT.zip)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by kirk0830** [comment]
yes we have noted the Rappe pseudopotential will fail in 3.7.3. @sunliang98 Hi, I guess this may be because of some changes of pseudopot I/O?

**Comment by sunliang98** [comment]
This issue is introduced by #4711 , I will fix it soon.
