### ISSUE TITLE
dcu test failed at 20240819

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#4974]
### Describe the Testing Issue

The daily dcu test is failed since commit ffdc617

https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fsched-abacustest-dcu-cg-7e5f62

example 003_12Pt111 is abnormal stopped at the beginning of SCF
```
-------------------------------------------
 SELF-CONSISTENT : 
 -------------------------------------------
 START CHARGE      : atomic
 DONE(2.99794    SEC) : INIT SCF
 * * * * * *
 << Start SCF iteration.
```

the error message is 
```
[b03r3n11:15326] *** Process received signal ***
[b03r3n11:15326] Signal: Aborted (6)
[b03r3n11:15326] Signal code:  (-6)
[b03r3n11:15326] [ 0] /lib64/libpthread.so.0(+0xf5d0)[0x2b6f1bc575d0]
[b03r3n11:15326] [ 1] /lib64/libc.so.6(gsignal+0x37)[0x2b6f25b8c207]
[b03r3n11:15326] [ 2] /lib64/libc.so.6(abort+0x148)[0x2b6f25b8d8f8]
[b03r3n11:15326] [ 3] /public/software/compiler/rocm/dtk-22.10/lib/libgalaxyhip.so.5(+0x98e7d4)[0x2b6f1d9aa7d4]
[b03r3n11:15326] [ 4] /public/software/compiler/rocm/dtk-22.10/lib/libgalaxyhip.so.5(+0x98d0fe)[0x2b6f1d9a90fe]
[b03r3n11:15326] [ 5] /public/software/compiler/rocm/dtk-22.10/lib/libgalaxyhip.so.5(+0x952086)[0x2b6f1d96e086]
[b03r3n11:15326] [ 6] /lib64/libpthread.so.0(+0x7dd5)[0x2b6f1bc4fdd5]
[b03r3n11:15326] [ 7] /lib64/libc.so.6(clone+0x6d)[0x2b6f25c53ead]
[b03r3n11:15326] *** End of error message ***
```

The test with commit d0b25ea is successful, and after it the only commit is ffdc617

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by pxlxingliang** [comment]
@Qianruipku, the commit https://github.com/deepmodeling/abacus-develop/commit/ffdc61737760872cae27d3acbea035cb1c8d309d is pushed from you, could you please check this issue?

**Comment by Qianruipku** [comment]
In fact, the commit https://github.com/deepmodeling/abacus-develop/commit/ffdc61737760872cae27d3acbea035cb1c8d309d will not affect DCU version. It may be the bug of previous DCU code.

**Comment by WHUweiqingzhou** [comment]
I close this issue since DCU tests pass in recent 2 days.

**Comment by pxlxingliang** [comment]
At 20240823, the dcu test is failed again for example 004_3BaTiO3.
https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fsched-abacustest-dcu-cg-c23711

The node is j20r4n07, and it is found has similar issue in #4063 on this node.
