### ISSUE TITLE
Read pseudopotential error

### ISSUE THREAD

**Issue by AroundPeking** [deepmodeling/abacus-develop#4975]
### Describe the bug

ABACUS can not read some version of upf format. Report: "Assertion `ic<nc' failed."

### To Reproduce

Files are attached here.
[ccecp.tar.gz](https://github.com/user-attachments/files/16658229/ccecp.tar.gz)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@sunliang98 could you have a look?
