### ISSUE TITLE
install abacus error using toolchain with GPU option

### ISSUE THREAD

**Issue by sunlight905** [deepmodeling/abacus-develop#4976]
Dear all,
I want to install abacus 3.7.3 on the system rockylinux 9 using the GPU rtx4090.
I use toolchain for installing. But there are some error:
#############################################################
CMake Warning at CMakeLists.txt:102 (message):
  Failed to get git commit info

-- Found Cereal: /home/sunlight/work/abacus/abacus-develop-3.7.3/toolchain/install/cereal-1.3.2/include/cereal
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.7.3")
-- Found ELPA: /home/sunlight/work/abacus/abacus-develop-3.7.3/toolchain/install/elpa-2024.03.001/cpu/lib/libelpa_openmp.so
-- Performing Test ELPA_VERSION_SATISFIES
-- Performing Test ELPA_VERSION_SATISFIES - Success
-- Found MPI_CXX: /opt/intel/oneapi/mpi/2021.13/lib/libmpicxx.so (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found OpenMP_CXX: -fiopenmp (found version "5.1")
-- Found OpenMP: TRUE (found version "5.1")
-- Found CUDAToolkit: /usr/local/cuda/targets/x86_64-linux/include (found version "12.6.20")
CMake Error at toolchain/install/cmake-3.30.0/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:838 (message):
  Compiling the CUDA compiler identification source file
  "CMakeCUDACompilerId.cu" failed.

  Compiler: /usr/local/cuda/bin/nvcc

  Build flags:

  Id flags:
  --keep;--keep-dir;tmp;-ccbin=/opt/intel/oneapi/compiler/2024.2/bin/icpx -v
#############################################################

The build file is :
#############################################################
`#!/bin/bash
#SBATCH -J build
#SBATCH -N 1
#SBATCH -n 16
#SBATCH -o install.log
#SBATCH -e install.err
#install ABACUS with libxc and deepks
#JamesMisaka in 2023.08.22
#Build ABACUS by intel-toolchain
#module load mkl compiler mpi
#source path/to/vars.sh

ABACUS_DIR=..
TOOL=$(pwd)
INSTALL_DIR=$TOOL/install
source $INSTALL_DIR/setup
cd $ABACUS_DIR
ABACUS_DIR=$(pwd)

BUILD_DIR=build_abacus_intel
rm -rf $BUILD_DIR

PREFIX=$ABACUS_DIR
ELPA=$INSTALL_DIR/elpa-2024.03.001/cpu
CEREAL=$INSTALL_DIR/cereal-1.3.2/include/cereal
LIBXC=$INSTALL_DIR/libxc-6.2.2
#LIBTORCH=$INSTALL_DIR/libtorch-2.1.2/share/cmake/Torch
#LIBNPY=$INSTALL_DIR/libnpy-1.0.1/include
#LIBRI=$INSTALL_DIR/LibRI-0.1.1
#LIBCOMM=$INSTALL_DIR/LibComm-0.1.0
#DEEPMD=$HOME/apps/anaconda3/envs/deepmd

#if use deepks and deepmd
cmake -B $BUILD_DIR -DCMAKE_INSTALL_PREFIX=$PREFIX \
        -DMKLROOT=$MKLROOT \
        -DELPA_DIR=$ELPA \
        -DCEREAL_INCLUDE_DIR=$CEREAL \
        -DLibxc_DIR=$LIBXC \
        -DENABLE_LCAO=ON \
        -DENABLE_LIBXC=ON \
        -DUSE_OPENMP=ON \
        -DUSE_ELPA=ON \
        -DENABLE_RAPIDJSON=ON \
        -DUSE_CUDA=1 \ 
       -DCMAKE_CUDA_COMPILER=nvcc \ 
#-DENABLE_DEEPKS=1 \
#-DTorch_DIR=$LIBTORCH \
#-Dlibnpy_INCLUDE_DIR=$LIBNPY \
#-DENABLE_LIBRI=ON \
#-DLIBRI_DIR=$LIBRI \
#-DLIBCOMM_DIR=$LIBCOMM \
#-DDeePMD_DIR=$DEEPMD \
#-DTensorFlow_DIR=$DEEPMD \
#-DCMAKE_CXX_COMPILER=icpx \
#-DMPI_CXX_COMPILER=mpiicpc \

cmake --build $BUILD_DIR -j `nproc` 
cmake --install $BUILD_DIR 2>/dev/null

#if one want's to include deepmd, your gcc version should be >= 11.3.0

#generate abacus_env.sh
cat << EOF > "${TOOL}/abacus_env.sh"
#!/bin/bash
source $INSTALL_DIR/setup
export PATH="${PREFIX}/bin":\${PATH}
EOF
#############################################################

Could you give me some advices?

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by QuantumMisaka** [comment]
@sunlight905 
Can you try using `icpc` instead of `icpx` in `build_abacus_intel.sh` ? 
In my recollection, `icpx` cannot be used to compile GPU-version ABACUS 
(There should have been an issue about this @caic99 )

**Comment by caic99** [comment]
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#host-compiler-support-policy

**Comment by sunlight905** [comment]
Thanks for your reply @QuantumMisaka  @caic99.
In the toolchain readme file:
 ### GPU version of ABACUS
add following options in build*.sh:
```shell
cmake -B $BUILD_DIR -DCMAKE_INSTALL_PREFIX=$PREFIX \
        -DCMAKE_CXX_COMPILER=icpx \
        -DMPI_CXX_COMPILER=mpiicpc \
        ......
        -DUSE_CUDA=1 \
        -DCMAKE_CUDA_COMPILER=${path to cuda toolkit}/bin/nvcc \
        ......
```
Notice: You CANNOT use `icpx` compiler for GPU version of ABACUS for now 
Notice: `icc` and `icpc` from Intel Classic Compiler of Intel-oneAPI is not supported for 2024.0 and newer version.

1. As you suggested, the build file is changed:
```
        -DCMAKE_CXX_COMPILER=icpc \
        -DMPI_CXX_COMPILER=mpiicpc \
        ......
        -DUSE_CUDA=1 \
        -DCMAKE_CUDA_COMPILER=${path to cuda toolkit}/bin/nvcc \
```
the output:
```
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:7 (project):
  The CMAKE_CXX_COMPILER:

    icpc

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!

```
Because use oneAPI 2024.2 at present, so icpc can't be found.


2. For using GPU, the oneAPI should be downgraded to version 2023?
or maybe suggest ABACUS support icpx?

3. I use the command "dnf install intel-basekit", and the the version of oneAPI 2024.2 is installed. 
If can't use icpx, how to install the oneAPI 2023 or there are other methods to solve the problem?

**Comment by QuantumMisaka** [comment]
@sunlight905 Two ways
- use gcc toolchain
- use offline Intel-OneAPI packages (I have them)

**Comment by caic99** [comment]
> (There should have been an issue about this @caic99 )

#2906

**Comment by sunlight905** [comment]
Could you send the offline Intel-OneAPI packages to me? @QuantumMisaka 
my email is qinglanzi@sina.cn
Thanks!

**Comment by sunlight905** [comment]
@QuantumMisaka I have found the offline OneAPI 2023 from the web:
https://pranabdas.github.io/espresso/setup/hpc/#installing-intel-oneapi-libraries 

Intel oneAPI Base Toolkit:
wget https://registrationcenter-download.intel.com/akdlm/IRC_NAS/992857b9-624c-45de-9701-f6445d845359/l_BaseKit_p_2023.2.0.49397_offline.sh

HPC Toolkit:
wget https://registrationcenter-download.intel.com/akdlm/IRC_NAS/0722521a-34b5-4c41-af3f-d5d14e88248d/l_HPCKit_p_2023.2.0.49440_offline.sh

Thanks!

**Comment by QuantumMisaka** [comment]
> [@QuantumMisaka](https://github.com/QuantumMisaka) I have found the offline OneAPI 2023 from the web: https://pranabdas.github.io/espresso/setup/hpc/#installing-intel-oneapi-libraries
> 
> Intel oneAPI Base Toolkit: wget https://registrationcenter-download.intel.com/akdlm/IRC_NAS/992857b9-624c-45de-9701-f6445d845359/l_BaseKit_p_2023.2.0.49397_offline.sh
> 
> HPC Toolkit: wget https://registrationcenter-download.intel.com/akdlm/IRC_NAS/0722521a-34b5-4c41-af3f-d5d14e88248d/l_HPCKit_p_2023.2.0.49440_offline.sh
> 
> Thanks!

For users：In the newest OneAPI, only HPC toolkit is what you need. But for old version, you need both BaseKit (for MKL) and HPCKit (for IntelMPI and Intel Compilers)
