### ISSUE TITLE
Not providing "FindRapidJSON.cmake"

### ISSUE THREAD

**Issue by MoseyQAQ** [deepmodeling/abacus-develop#4981]
### Details

When building ABACUS 3.7.3, cmake told me that <kbd>By not providing "FindRapidJSON.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "RapidJSON", but CMake did not find one</kbd>

I am unfamiliar with Cmake, maybe a "FindRapidJSON.cmake" file under <kbd>cmake</kbd> folder is missing.

Cmake command:
```Bash
cmake -B $BUILD_DIR -DCMAKE_INSTALL_PREFIX=$PREFIX \
        -DCMAKE_CXX_COMPILER=icpx \
        -DMPI_CXX_COMPILER=mpiicpc \
        -DMKLROOT=$MKLROOT \
        -DELPA_DIR=$ELPA \
        -DCEREAL_INCLUDE_DIR=$CEREAL \
        -DLibxc_DIR=$LIBXC \
        -DENABLE_LCAO=ON \
        -DENABLE_LIBXC=ON \
        -DUSE_OPENMP=ON \
        -DUSE_ELPA=ON \
        -DENABLE_RAPIDJSON=ON \
         -DENABLE_LIBRI=ON \
         -DLIBRI_DIR=$LIBRI \
         -DLIBCOMM_DIR=$LIBCOMM \
```
warning thrown by Cmake:
```Bash
CMake Warning at CMakeLists.txt:45 (find_package):
  By not providing "FindRapidJSON.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "RapidJSON", but CMake did not find one.

  Could not find a package configuration file provided by "RapidJSON" with
  any of the following names:

    RapidJSONConfig.cmake
    rapidjson-config.cmake

  Add the installation prefix of "RapidJSON" to CMAKE_PREFIX_PATH or set
  "RapidJSON_DIR" to a directory containing one of the above files.  If
  "RapidJSON" provides a separate development package or SDK, be sure it has
  been installed.


CMake Warning at CMakeLists.txt:47 (message):
  Rapidjson is not found, trying downloading from github, or you can install
  Rapidjson first and reinstall abacus.
```

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by QuantumMisaka** [comment]
@MoseyQAQ 
You should load environments when build with rapidjson
```
export CPATH="path/to/rapidjson/include":$CPATH
```

this setting is incorporated in toolchain `./install/setup` after running `toolchain_*.sh`

**Comment by MoseyQAQ** [comment]
It works. Thank you!
