### ISSUE TITLE
intel CI test

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#4985]
### Describe the Testing Issue

In this issue, I will update the integrate and unit tests in intel.

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by pxlxingliang** [comment]
20240822:

Link: https://bohrium.dp.tech/jobs/app-detail/24805?type=App
Two integrate test failed and two unit test failed:
140_PW_15_SO	
907_OF_LPS

044_clebsch_gordan_coeff_test
204_HSolver_bpcg 	



![image](https://github.com/user-attachments/assets/9c06e5b0-a4cc-4e91-b7cd-58716df157c1)

![image](https://github.com/user-attachments/assets/647eace6-f719-4a41-bdcc-2566e90c1737)

**Comment by WHUweiqingzhou** [comment]
I suggest we update this comparison for every major version.

**Comment by caic99** [comment]
Related: #4643

**Comment by pxlxingliang** [comment]
20241030:

Link: https://bohrium.dp.tech/jobs/app-detail/39073?type=App
Unit test 044_clebsch_gordan_coeff_test and 166_HSolver_bpcg  are failed
Integrate tests 102_PW_PINT_UKS, 140_PW_15_SO, and 907_OF_LPS are failed

![Image](https://github.com/user-attachments/assets/5f380910-ece3-45fc-94c0-7860c1c482b7)

![Image](https://github.com/user-attachments/assets/055368b5-c23b-482f-be9c-f3065172c9b2)
