### ISSUE TITLE
A Segmentation fault when calculating the vacancy energy of 256 iron atoms

### ISSUE THREAD

**Issue by ieiue** [deepmodeling/abacus-develop#4989]
### Describe the bug

When calculating  the vacancy energy of 256 (actually 255) iron atoms by using 64 cpus and 2 processors with ABACUS(v3.7.3) , there is a  Segmentation fault. 
And I tried 28 cpus and 4 processors, it can run.
(1)64 cpus & 2 processors :
![image](https://github.com/user-attachments/assets/f1411e69-a647-4b92-9781-cd6868b55a66)
(2)28 cpus & 4 processors:
![image](https://github.com/user-attachments/assets/0bce1ea1-4107-4cfe-bc88-f5aacab6c7b1)

### Expected behavior

What's the relationship between calculation success and the number of cpus and the number of processes.

### To Reproduce

[Fe256_vacancy.zip](https://github.com/user-attachments/files/16721028/Fe256_vacancy.zip)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by xdzhu** [comment]
I think there must be something went wrong in `3.7.x` version, recently i also met problems but SIGNAL 9 AND 6.
I suggest you to try version `3.6.5` in https://github.com/deepmodeling/abacus-develop/releases/tag/v3.6.5

Reach me if it works.

**Comment by ieiue** [comment]
I tired v.3.6.4 before. There was the same Segmentation.
![image](https://github.com/user-attachments/assets/87399d79-1838-4af5-8362-5f9c1c31295f)
@xdzhu

**Comment by xdzhu** [comment]
Is it OK for 1 mpi case?

**Comment by ieiue** [comment]
For 1 processor, it still has a Segmentation fault.
![image](https://github.com/user-attachments/assets/db7138e1-e2fc-41b5-bd91-18253b2c8a66)
![image](https://github.com/user-attachments/assets/2073b656-79dd-4268-b7ff-9f6eeb9e0e94)

**Comment by maki49** [comment]
There seems to be some bug with ELPA, could you please try `ks_solver scalapack_gvx`?

**Comment by ieiue** [comment]
Setting ks_solver= scalapack_gvx doesn't help. 
![image](https://github.com/user-attachments/assets/77ff15f4-c567-4b93-a78e-539f2db9ae88)

**Comment by xdzhu** [comment]
Can you try the latest version 3.7.5 to check whether it's solved or not?

**Comment by xdzhu** [comment]
with elpa

**Comment by YuLiu98** [comment]
Now this bug is solved in abacus v3.8.0.
