### ISSUE TITLE
Parameter needed to control whether or not calculating STRESS in ionic relaxation steps during cell-relax procedure

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#499]
## Background
In our method to do cell-relax calculation, we follow steps below:
1: calculate force and check if atomic force is not near zero and any atom can move;
2: if yes, do relax only; goto 1;
3: if no, calculate STRESS and check if STRESS is not near zero and any lattice vector can change;
4: if yes, do cell-relax only and change lattice vector; goto 1;
5: if no,  finish cell-relax procedure.

During steps above, we should only calculate STRESS when relaxation is done; but now, ABACUS calculated STRESS every step if user set stress = 1. We should add a new parameter in INPUT to control that. default setup should be not calculate STRESS. 

Another problem is that ABACUS can't fix all lattice vector and only change lattice constant, do we need this function? @mohanchen

**Comment by dyzheng** [comment]
Our method of cell-relax is not good enough for some structure, maybe we should consider other method to update atomic position and lattice vector at same time.

**Comment by mohanchen** [comment]
1. agree，we should only calculate stress when needed to relax the cell vectors.
2. of course we need this function, also the users should be able to fix any lattice vectors or keep their angles fixed.
3. Yes, we should develop more robust cell-relaxation algorithms.

**Comment by wenfei-li** [comment]
There are some methods which simultaneously relaxes cell and ion, such as https://journals.aps.org/prb/abstract/10.1103/PhysRevB.59.235
However this will be incompatible with our current structure of code, where cell and ions are treated as two separated loops. A refactor of this part might be necessary.

**Comment by wenfei-li** [comment]
This is no longer needed in the new relaxation method.
