### ISSUE TITLE
Cell relax not achieved in 150 steps for bcc Fe with pw basis calculation

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#4990]
### Describe the bug

Cell relax not achieved in 150 steps for bcc Fe with pw basis calculation

### Expected behavior

quick relaxation steps in 100 steps

### To Reproduce
[relax.tar.gz](https://github.com/user-attachments/files/16721513/relax.tar.gz)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by pxlxingliang** [comment]
I have checked the INPUT, the force_thr_ev and stress_thr is too strict, but scf_thr is 1e-6, which is inaccuracy.

```
INPUT_PARAMETERS
suffix    ABACUS

#calculation   scf
ecutwfc    100
scf_thr    1.0e-6
scf_nmax   100

calculation   cell-relax
relax_nmax    150
force_thr_ev  0.001
stress_thr    0.01
relax_method  cg
out_stru      1

#init_chg    file
#out_dos    1
#dos_sigma    0.07
#out_band    1

smearing_method    gaussian
smearing_sigma    0.01

mixing_type    broyden
mixing_beta    0.2
#mixing_gg0    1.5
#mixing_restart 10
#mixing_dmr    1

ks_solver     dav
basis_type    pw
gamma_only    0
symmetry    0
#noncolin   1
nspin    2
#lspinorb   true

kspacing 0.13
onsite_radius 3
```

```
 DA1      4.54e+00   4.84e+00  -6.81999769e+03   0.00000000e+00   1.1106e-04  48.27
 DA2      4.54e+00   4.85e+00  -6.81999777e+03  -7.55903782e-05   2.5204e-05  14.46
 DA3      4.55e+00   4.86e+00  -6.81999782e+03  -5.01560640e-05   3.2952e-05  16.23
 DA4      4.55e+00   4.86e+00  -6.81999784e+03  -2.52556764e-05   7.2469e-07  14.55
```

**Comment by pxlxingliang** [comment]
Suggest to set scf_thr to 1e-8, and loose force_thr_ev to 0.01 and stress_thr to 1.

**Comment by hongriTianqi** [comment]
It is ok with parameters suggested by @pxlxingliang, thx.
