### ISSUE TITLE
Energy is converge to 1e-7, but drho only to 1e-3

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#5011]
### Describe the bug

energy is converge to 1e-7, but drho only to 1e-3. the results seems unreasonable

### To Reproduce

[example.tar.gz](https://github.com/user-attachments/files/16777298/example.tar.gz)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
change `or` to `and`.
