### ISSUE TITLE
Can ABACUS output Energy and Force information EVEN SCF don't converge?

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#5018]
### Details

As https://gitlab.com/1041176461/ase-abacus/-/issues/36
Sometimes we can do relaxation and md in ABACUS itself while SCF do not converge, but it is forbidden in ASE-ABACUS. We need to look at it .

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by WHUweiqingzhou** [comment]
ABACUS will output energy and force though SCF fails to converge. Maybe it is a bug from ASE side?

**Comment by mohanchen** [comment]
Now, even if it doesn't converge, information should still be output. GitLab also has an issue regarding the ASE interface. Yuyang will take a look at it later.
