### ISSUE TITLE
Compile: configure with -DENABLE_MPI=OFF seems not work as expected 

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#5026]
### Describe the bug

As feedback by user, following our online manual https://mcresearch.github.io/abacus-user-guide/abacus-gcc.html, with flag -DENABLE_MPI=OFF, cmake still pops error message as: 
![mmexport1725030635867](https://github.com/user-attachments/assets/dd3f57c4-34e1-4d91-a6b1-3ab56ee55b47)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by brucefan1983** [comment]
Thanks for creating this issue for me; I should have done it myself. 
After commenting out a few lines as shown below,
![6051b9819eb9fb82458238c654b898b](https://github.com/user-attachments/assets/4af2beb9-8ade-491e-8553-fa2d37f5f8fc)
and adding the flag `-DENABLE_LCAO=OFF`, I managed to obtain the desired executable `abacus_pw_serial`.

Is this a reasonable fix?

**Comment by WHUweiqingzhou** [comment]
@caic99, could you have a look?

**Comment by caic99** [comment]
> @caic99, could you have a look?

Hi @WHUweiqingzhou ,
Since the related codes are given, it would be more efficient if you ask the author of [related commits](https://github.com/deepmodeling/abacus-develop/blame/develop/CMakeLists.txt#L242) for help.
