### ISSUE TITLE
Compile without mpi on error when using cuda

### ISSUE THREAD

**Issue by tang070205** [deepmodeling/abacus-develop#5044]
### Describe the bug

Use ：cmake -B build -DENABLE_MPI=OFF -DUSE_CUDA=1
![{F383FC17-372E-4e3a-97B7-3834F0A86D9F}](https://github.com/user-attachments/assets/64c02855-45cd-48ab-bbb3-fcd82fe5486a)
![{15C59CDC-DE07-402c-ACD2-D828E28B4B2A}](https://github.com/user-attachments/assets/bd571c65-f8db-4127-84d0-1706f9cb43e6)
![{F5ED078E-BCC7-4524-AF47-FEEF4D893318}](https://github.com/user-attachments/assets/81b40358-2eb0-4e44-ab24-52f0b1591549)

### Environment

Ubuntu 20.04、gcc 9.4.0、cuda 12.1

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@caic99 could you have a look?

**Comment by caic99** [comment]
> @caic99 could you have a look?

Please see https://github.com/deepmodeling/abacus-develop/blame/develop/source/module_hamilt_lcao/module_gint/grid_technique.cpp#L564
