### ISSUE TITLE
Elpa native solver document needs to be updated

### ISSUE THREAD

**Issue by Critsium-xy** [deepmodeling/abacus-develop#5048]
### Details

See https://github.com/deepmodeling/abacus-develop/pull/4969

This new feature's document is not detailed enough. Maybe the information that elpa should be installed with gpu support should also be updated to the "Easy Installation" part of the document, and place it in where ELPA package is first metioned, or place it in the "USE_ELPA" parameter explanation.

"Advanced Installation Options" -> "Build with CUDA support" may also need to be updated with this info. The document now is a bit difficult to locate this infomation and may cause confusion for users when they find that they fail to build the CUDA version (because of this elpa setting).

Considering quite an amount of users use apt to directly install elpa, and installing elpa from source is exactly not that easy. This may cause difficulty when they are trying to build ABACUS. Maybe adding an option 'USE_GPU_ELPA' is a better way to do this.

### Have you read the online manual http://abacus.deepmodeling.com/en/latest/

- [X] Yes, I have read the online manual.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific section of the documentation with the issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Update the documentation to address the issue, following the suggested improvement.
- [ ] Ensure the updated documentation adheres to the project's documentation standards.
- [ ] Test the updated documentation to ensure it is clear and accurate.
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Publish the updated documentation and notify the issue reporter.

**Comment by caic99** [comment]
This will also affect the behavior for conda builds. I would suggest maintaining the compatibility for the current GPU users, allowing them to use the ELPA distribution already built on CPU.

**Comment by caic99** [comment]
Possible solution:
https://github.com/deepmodeling/abacus-develop/pull/4969/files#r1766539770
