### ISSUE TITLE
Segmentation fault when deepks_out_labels 1

### ISSUE THREAD

**Issue by Chentao168** [deepmodeling/abacus-develop#5052]
### Describe the bug

When running ABACUS with deepks_out_labels = 1, I met segmentation fault.

[cn76863:3201888:0:3201888] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x8)
backtrace (tid:3201888)
 0 0x0000000000012ce0 __funlockfile()  :0
 1 0x0000000000bd74b0 hamilt::BaseMatrix<double>::get_value()  ???:0
 2 0x000000000046012a LCAO_Deepks::cal_projected_DM()  /fs2/home/chenmh/1_chentao/soft/deepks-abacus/abacus-develop/source/module_hamilt_lcao/module_deepks/LCAO_deepks_pdm.cpp:234
 3 0x00000000004744fc LCAO_Deepks_Interface::out_deepks_labels()  /fs2/home/chenmh/1_chentao/soft/deepks-abacus/abacus-develop/source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp:199
 4 0x0000000000953635 ModuleESolver::ESolver_KS_LCAO<double, double>::after_scf()  /fs2/home/chenmh/1_chentao/soft/deepks-abacus/abacus-develop/source/module_esolver/esolver_ks_lcao.cpp:1145
 5 0x00000000008eeade ModuleESolver::ESolver_KS<double, base_device::DEVICE_CPU>::runner()  /fs2/home/chenmh/1_chentao/soft/deepks-abacus/abacus-develop/source/module_esolver/esolver_ks.cpp:642
 6 0x00000000008eeade std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string<std::allocator<char> >()  /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/basic_string.h:519
 7 0x00000000008eeade ModuleESolver::ESolver_KS<double, base_device::DEVICE_CPU>::runner()  /fs2/home/chenmh/1_chentao/soft/deepks-abacus/abacus-develop/source/module_esolver/esolver_ks.cpp:643
 8 0x000000000077d443 Relax_Driver::relax_driver()  /fs2/home/chenmh/1_chentao/soft/deepks-abacus/abacus-develop/source/module_relax/relax_driver.cpp:49
 9 0x0000000000793ef8 Driver::driver_run()  /fs2/home/chenmh/1_chentao/soft/deepks-abacus/abacus-develop/source/driver_run.cpp:68
10 0x0000000000793ef8 Relax_Driver::~Relax_Driver()  /fs2/home/chenmh/1_chentao/soft/deepks-abacus/abacus-develop/source/module_relax/relax_driver.h:14
11 0x0000000000793ef8 Driver::driver_run()  /fs2/home/chenmh/1_chentao/soft/deepks-abacus/abacus-develop/source/driver_run.cpp:69
12 0x0000000000793068 Driver::atomic_world()  /fs2/home/chenmh/1_chentao/soft/deepks-abacus/abacus-develop/source/driver.cpp:186
13 0x00000000007929a1 Driver::init()  /fs2/home/chenmh/1_chentao/soft/deepks-abacus/abacus-develop/source/driver.cpp:40
14 0x0000000000441cf6 main()  ???:0
15 0x000000000003acf3 __libc_start_main()  ???:0
16 0x0000000000441bae _start()  ???:0
/var/spool/slurm/d/job3497124/slurm_script: line 13: 3201888 Segmentation fault      (core dumped) abacus

### To Reproduce

ABACUS v3.7.4 with deepks
[20240905-err-deepks_out_labels.zip](https://github.com/user-attachments/files/16883678/20240905-err-deepks_out_labels.zip)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by xuan112358** [comment]
It seems that the problem comes from a nullptr in function cal_projected_DM.
@dyzheng any suggestion?
