### ISSUE TITLE
Tests: Some results comparison between ABACUS and QE

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#5067]
### Describe the Testing Issue

In principle, ABACUS can use the same pseudo-potential as QE and thus should get the same result if all basic parameters are the same. Is there any test to prove it? @pxlxingliang 

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by pxlxingliang** [comment]
I have compare the results (energy/force/stress) by ABACUS PW and QE on some alloy systems with the same pseudopotential and parameter settings (ecutwfc/smearing/k points/scf_thr/ks_solver). Specially for abacus, pseudo_rcut=10 and pseudo_mesh=1 is set to align the dealing of pseudopotential.

DE means the deviation of energy, and MADF means the maximum absolute deviation of force, and MADS means the maximum absolute deviation of stress.
![PW-benchmark](https://github.com/user-attachments/assets/ebf2f35e-543d-4a07-8046-dcc2fc95c38f)

https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.112-0d4785
