### ISSUE TITLE
Dwarf版本设置问题

### ISSUE THREAD

**Issue by SyntaxSmith** [deepmodeling/abacus-develop#5072]
### Describe the bug

编译正常结束，运行时报错：
BFD: Dwarf Error: found dwarf version '5', this reader only handles version 2, 3 and 4 information.

### To Reproduce

1.从release 3.7.5 source code zip文件解包
2.使用gcc 13.2 openmpi4.1.5，其他选项install
3.编译完成后运行

### Additional Context

查到需要在Cmake文件中添加
`set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -gdwarf-4")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -gdwarf-4")`
但是在根目录CMakeLists.txt中添加这两行设置重新编译无效

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@caic99 could you have a look?

**Comment by caic99** [comment]
@SyntaxSmith Would you try another compiler, or use abacus toolchain.
