### ISSUE TITLE
Unexpected Output When Generating Stress Labels Using DeePKS calculation

### ISSUE THREAD

**Issue by JohnYan98** [deepmodeling/abacus-develop#5075]
### Describe the bug

When running ABACUS 3.7.5 to generate stress labels (deepks_sbase.npy or deepks_stot.npy), the output has a shape of [nframes, 6] instead of the expected [nframes, 9], which is incorrect for DeepKS training.

<br class="Apple-interchange-newline">
[si_1_test.zip](https://github.com/user-attachments/files/16940765/si_1_test.zip)

### Environment

ABACUS 3.7.5

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by JohnYan98** [comment]
[si_1_test.zip](https://github.com/user-attachments/files/16940816/si_1_test.zip)

**Comment by xuan112358** [comment]
@JohnYan98 Since the stress is symmetric, these npy files contain only the upper triangle of stress. 
This is OK for DeePKS training.
