### ISSUE TITLE
The stable lattice constants of Cu fcc are different under old and new two-center-integral

### ISSUE THREAD

**Issue by xuan112358** [deepmodeling/abacus-develop#5076]
### Describe the bug

When using ABACUS with the new two-center-integral to generate NAO and plot energy-lattice curve，I found the most stable lattice constant is quite different from that calculated with old two-center-integral. The old result is closer to the pw result. Should I believe in it?
![image](https://github.com/user-attachments/assets/ee41196e-2d60-4a82-9193-68583ce0036d)
Here is the result. The energy values are translated according to the results at 3.60A of pw.
“New” means that the orbital file and the SCF calculations are performed with ABACUS v3.7.4 when ENABLE_FFT_TWO_CENTER = ON. “Old” means that the orbital file and the SCF calculations are performed with ABACUS v3.7.4 when ENABLE_FFT_TWO_CENTER = OFF. “Old_2000” means that the SCF calculations are performed when ecutwfc=2000.

### To Reproduce

[github_Cu_two_center.zip](https://github.com/user-attachments/files/16942030/github_Cu_two_center.zip)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by jinzx10** [comment]
There might be some misunderstanding about the relationship between "ecutwfc" and two center integration here. In the old two-center integration method, the parameter that actually controls the upper limit of spherical Bessel transform is "lcao_ecut"; its relationship with ecutwfc is that, if lcao_ecut is not set in INPUT, it will use ecutwfc as its default value. However, ecutwfc itself is not intended to be the parameter for spherical Bessel transform; it is intended to be the parameter for plane-wave cutoff, hence related to the grid integration in LCAO calculation. Therefore, setting "ecutwfc = 2200" would not only affect the upper limit for two-center integration, but also have an effect on the grid integration. If only two-center integration is tested, I think setting both "lcao_ecut 2000" and "ecutwfc 100" should be the right thing.

**Comment by jinzx10** [comment]
However, I did tested the right parameters and still found the results abnormal: not only the old & new two-center integration do not agree, but the LCAO energies turn out to be lower than those of PW's, which should definitely not happen. I changed the PP & orb to the SG-15 family and everything looks good. I think the pseudopotential and orbital might need more investigation.

**Comment by jinzx10** [comment]
It turns out that the pseudopotential does have some problem. The first non-local projector (PP_BETA) has a hard cutoff that looks like this:

![image](https://github.com/user-attachments/assets/648877d9-18a8-4611-aa5c-11c2fc3c2a24)

There's no way a normal K-B projector have this kind of shape. Such a hard cutoff can lead to severe numerical stability and I suggest you resort to the publisher of this pseudopotential for help. 

Regarding the difference between old and new two-center integration method, the FFT-based method and Simpson-based method would definitely respond differently to this hard cutoff and lead to different values. However, I don't think this can be attributed to a bug of the two-center integration.

**Comment by xuan112358** [comment]
Get it! Thank you very much for your help！
