### ISSUE TITLE
A new function is requested according to the pw method calculation of the DFT

### ISSUE THREAD

**Issue by 19227sh** [deepmodeling/abacus-develop#5077]
### Background

It is very important to obtain the initial density of the system from the fixed occupation number when calculating DFT of the fixed occupation number

### Describe the solution you'd like

It is suggested to define an INPUT parameter in input on the basis of pw, and the initial density of the system can be obtained according to the fixed occupation number (ocp=1)

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by kirk0830** [comment]
do you mean out_chg 2? https://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#out-chg

**Comment by Qianruipku** [comment]
@19227sh After PR 5802 is merged. You can init charge density from WAVEFUNC.dat and istate.info. Besides, you can change occupations in istate.info
