### ISSUE TITLE
Want some help in accelerating the SCF convergence in Fe-bearing systems using DFT+U.

### ISSUE THREAD

**Issue by Weizhang88** [deepmodeling/abacus-develop#5080]
### Details

I am using Abacus (3.7.4) to perform DFT labeling work with dpgen for an Fe-bearing mineral using DFT+U. However, the system is challenging to converge, with approximately 36-56% of tasks failing in some dpgen iterations. I would appreciate suggestions to accelerate the SCF convergence and any insights on whether the magnetism of Fe in my calculations is accurate.

[scf_Fe.zip](https://github.com/user-attachments/files/16959402/scf_Fe.zip)

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by kirk0830** [comment]
smearing_sigma can be set as 0.015 Ry at most commonly, and you may consider the u_ramping method if you are sure without dft+u the scf can converge:
https://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#uramping

**Comment by QuantumMisaka** [comment]
@Weizhang88 By tackle with systems contain Fe, you can set smearing method to `mp` and smearing sigma to 0.01.

The u_ramping method may help, but for dft-label task, is a fixed U value more physical ?

**Comment by Weizhang88** [comment]
> @Weizhang88 By tackle with systems contain Fe, you can set smearing method to `mp` and smearing sigma to 0.01.
> 
> The u_ramping method may help, but for dft-label task, is a fixed U value more physical ?

Many thanks to @kirk0830 and @QuantumMisaka. The changes to the `smearing method` and `smearing sigma` significantly improved SCF convergence. However, the effect of `u_ramping` is not very noticeable and requires more SCF iterations. Given that my dpgen iterations cover a wide range of temperatures and pressures, the values of U may change. Could I use the `yukawa_potential` to estimate the values of U instead of a fixed U value?

**Comment by dyzheng** [comment]
@Weizhang88 Hello, yukawa_potential feature can be used to estimate U values, it is not recommanded for DPGEN data generation because the U values should not change for one DP model.
