### ISSUE TITLE
ModuleIO::read_rhog does not support kpar > 1

### ISSUE THREAD

**Issue by Qianruipku** [deepmodeling/abacus-develop#5083]
### Describe the bug

ModuleIO::read_rhog does not support kpar > 1

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@YuLiu98, could you have a look?

**Comment by YuLiu98** [comment]
I tested the `read_rhog()` function, which works well.

And I think that this issue arises from `write_rhog()`:
```
ModuleIO::write_rhog(PARAM.globalv.global_out_dir + PARAM.inp.suffix + "-CHARGE-DENSITY.restart",
                                 PARAM.globalv.gamma_only_pw || PARAM.globalv.gamma_only_local,
                                 this->pw_rhod,
                                 PARAM.inp.nspin,
                                 GlobalC::ucell.GT,
                                 rhog_tot,
                                 GlobalV::RANK_IN_POOL,
                                 GlobalV::NPROC_IN_POOL);
```
Note that `kpar > 1` will cause the situation that two or more cores write into the same file in the meantime.

@kirk0830 can you look into this issue?
