### ISSUE TITLE
Daily PW test failed at 20240912

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#5087]
### Describe the Testing Issue

At 20240912, the daily PW test failed for the accuracy.

A link of intel-dav test is: https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fsched-abacustest-intel-dav-14d47e 

![image](https://github.com/user-attachments/assets/bd887157-bc71-4151-93cb-fe479fc31cf9)

Several examples have large different on STRESS.
![image](https://github.com/user-attachments/assets/90316a85-47c0-4d88-8393-3766797be326)

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by maki49** [comment]
This may result from the change of the irreducible k-points in https://github.com/deepmodeling/abacus-develop/pull/5063#issuecomment-2335740877.

**Comment by pxlxingliang** [comment]
I have tested on 000 by latest several commits, it is introduced by commit bd0e6a6.
A large different is in stress which has a deviation of about 0.02 kbar.

```
                     total_time  converge  normal_end  ibzk ks_solver  \
43f32d4a/000_4GaAs      21.4041      True        True    20       dav   
8f86cadb/000_4GaAs      20.1777      True        True    20       dav   
bd0e6a6/000_4GaAs       20.9964      True        True    20       dav   
c7d7c24f5/000_4GaAs     20.9760      True        True    20       dav   

                     delta_energyPerAtom(eV)  MaxAbsForce(eV/A)  \
43f32d4a/000_4GaAs             -2.273737e-13           0.000000   
8f86cadb/000_4GaAs              9.003998e-11           0.000037   
bd0e6a6/000_4GaAs               9.003998e-11           0.000037   
c7d7c24f5/000_4GaAs             9.003998e-11           0.000037   

                     MaxAbsStress(kbar)  acc_pass  
43f32d4a/000_4GaAs         2.000000e-10      True  
8f86cadb/000_4GaAs         1.824293e-02     False  
bd0e6a6/000_4GaAs          1.824293e-02     False  
c7d7c24f5/000_4GaAs        1.824293e-02     False 
```

The time line of recent commits:
<img width="1173" alt="image" src="https://github.com/user-attachments/assets/61ec97d7-0657-4a82-83e2-e4a067dbf178">

**Comment by maki49** [comment]
![image](https://github.com/user-attachments/assets/83824df1-f780-4876-a22e-b9d8018108d5)
Seems that the difference between the two sets of ibz-kpoints can be reduced along with the convergence threshold.

**Comment by pxlxingliang** [comment]
I have tested the latest codes with some alloy examples:
https://deepmodeling-activity.github.io/abacus-test.github.io/index.html?pname=alloy/symmetry

The deviation of energy, force, an stress with symmetry and without symmetry is similar to previous version 
0920 
![image](https://github.com/user-attachments/assets/2e62f0e7-756c-426d-b355-786622904046)


0628
![image](https://github.com/user-attachments/assets/f17ccced-0fec-4a1e-a299-5729773414df)

**Comment by pxlxingliang** [comment]
As the new symmetry has no more abnormal, I will update the reference data of PW daily test.
