### ISSUE TITLE
The manual for Polarization Calculation is misunderstanding easily

### ISSUE THREAD

**Issue by iduygnay** [deepmodeling/abacus-develop#5095]
### Details

![image](https://github.com/user-attachments/assets/bda510c3-25f0-4abd-8898-056fe2f8a443)
This part, says that P is along the c axis in the x, y, z cartesian coordinates. It's not clear and I misunderstood it means R1 represents x, R2 represents y. But actually, R1 R2 R3 correspond to the lattice vectors. I strongly recommend promoting this part. 
https://abacus.deepmodeling.com/en/latest/advanced/elec_properties/Berry_phase.html

### Have you read the online manual http://abacus.deepmodeling.com/en/latest/

- [X] Yes, I have read the online manual.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific section of the documentation with the issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Update the documentation to address the issue, following the suggested improvement.
- [ ] Ensure the updated documentation adheres to the project's documentation standards.
- [ ] Test the updated documentation to ensure it is clear and accurate.
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Publish the updated documentation and notify the issue reporter.

**Comment by WHUweiqingzhou** [comment]
@jingan-181 could you polish the doc?

**Comment by WHUweiqingzhou** [comment]
@jingan-181 could you polish the doc?
