### ISSUE TITLE
The scf of bcc Fe12 (110) surface energy calculation can't converge.

### ISSUE THREAD

**Issue by ieiue** [deepmodeling/abacus-develop#5105]
### Describe the bug

The scf of bcc Fe12 (12 layers) (110) can't converge when making a relax calculation to compute system's surface energy.  With the same parameters, (100) and (111) surface can converge and obtain the results. I tried different setting of "mixing_beta", "mixing_ndim", "mixing_beta_mag", "mixing_gg0", "mixing_gg0_mag".

### To Reproduce

[Fe12_110.zip](https://github.com/user-attachments/files/17002735/Fe12_110.zip)

### Environment

ABACUS v3.6.4

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by YuLiu98** [comment]
You can construct a cubic cell, which can help the convergence.

[Fe_110.tar.gz](https://github.com/user-attachments/files/17372216/Fe_110.tar.gz)
