### ISSUE TITLE
HSE calculation ran into oom_kill problem

### ISSUE THREAD

**Issue by Cheng-JW** [deepmodeling/abacus-develop#5107]
### Describe the bug

When running HSE in a NaTMO2 system, there was OOM error and the calculation stopped.
[hse.zip](https://github.com/user-attachments/files/17005103/hse.zip)

### To Reproduce

In attachment

### Environment

ABACUS version: 7fa03cae0 (Sat Sep 14 19:36:28 2024 +0800)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@PeizeLin 
could you have a look?

**Comment by Cheng-JW** [comment]
I think this problem is solved when I upgrade to the current 3.8.0 version.
