### ISSUE TITLE
Segmentation faults in TDDFT

### ISSUE THREAD

**Issue by Fla4Lu** [deepmodeling/abacus-develop#5108]
### Describe the bug

Using velocity gauge together with the Heaviside function external field (td_stype 1; td_ttype 3) causes a segfault after the first (0th) MD step. Also using any Hubbard correcting causes a segfault right after calculation setup, before the first MD step.

### Expected behavior

Program runs normally or gives an error message about this feature combination not being implemented.

### Environment

OS: Ubuntu 24.04.1 LTS
Abacus Version: 3.7.5 Commit 7fa03cae0

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@AsTonyshment, could you have a look?

**Comment by AsTonyshment** [comment]
I've reviewed the code, and the issue appears to stem from the Simpson Integration in the file `source/module_elecstate/potentials/H_TDDFT_pw.cpp`:
```
// Call the Simpson's rule integration using std::vector data
ModuleBase::Integral::Simpson_Integral(ncut + 1, vext_time.data(), dt_int, out);
```
When using the velocity gauge along with the Heaviside function for the external field (`td_stype 1`; `td_ttype 3`), the `ncut` is set to `1`. However, the Simpson Integration requires the grid mesh to be odd, as indicated by the assertion (`assert(mesh&1)`):
```
void Integral::Simpson_Integral
(
    const int mesh,
    const double * const func,
    const double dr,
    double &asum
)
{
    /*     simpson's rule integration. On input:
    !      mesh = mhe number of grid points (should be odd)
    !      func(i)= function to be integrated
    !      rab(i) = r(i) * dr(i)/di * di
    !      For the logarithmic grid not including r=0 :
    !      r(i) = r_0*exp((i-1)*dx) ==> rab(i)=r(i)*dx
    !      For the logarithmic grid including r=0 :
    !      r(i) = a(exp((i-1)*dx)-1) ==> rab(i)=(r(i)+a)*dx
    !      Output in asum = \sum_i c_i f(i)*rab(i) = \int_0^\infty f(r) dr
    !      where c_i are alternativaly 2/3, 4/3 except c_1 = c_mesh = 1/3
    */
    //  simpson's rule integrator for function stored on the
    //  radial logarithmic mesh
    //	routine assumes that mesh is an odd number so run check
    assert(mesh&1);

    asum = 0.00;
	const size_t end = mesh-2;
    for(size_t i=1; i!=end; i+=2 )
    {
		const double f1 = func[i];
		asum += f1 + f1 + func[i+1];
    }
	const double f1 = func[mesh-2];
	asum += f1+f1;
	asum += asum;
	asum += func[0] + func[mesh-1];
	asum *= dr/3.0;
    return;
}// end subroutine simpson
```
I will work on resolving this issue. Thank you!
