### ISSUE TITLE
Installation v3.7.5 by conda

### ISSUE THREAD

**Issue by BingcanLi** [deepmodeling/abacus-develop#5118]
### Background

I was trying to update abacus to the latest version via conda but failed to update to the lated version (v3.7.5).

### Describe the solution you'd like

I would like to have the conda update channel linked to v3.7.5.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [X] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by QuantumMisaka** [comment]
@BingcanLi You can try to install abacus with toolchain
@caic99 Any comments ?

**Comment by caic99** [comment]
Blocked by #5048, since ELPA does not provide its GPU distribution on conda-forge.
