### ISSUE TITLE
The behavior of "gamma_only" is changed

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#5119]
### Describe the bug

At 20240918, the weekly example test is failed on below tests, and the error message shows the KPOINTS is lacked.
I have check the INPUT of these tests, the INPUT has define gamma_only to 1 and not support KPT file. 
In previous version, ABACUS will generate a KPT file with "1 1 1" K point if "gamma_only 1" has been defined in INPUT regardless of whether Basis is LCAO or PW (in the failed test, the basis is PW). Since commit 03c25826c0c688, ABACUS will not generate KPT file when basis is PW and gamma_only is 1 in INPUT.

![image](https://github.com/user-attachments/assets/c82e0923-1935-45c9-9b79-c3ad64522baa)

https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fsched-abacustest-exampletest-a5fb97

```
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 Something wrong while reading KPOINTS.
 CHECK IN FILE : OUT.ABACUS/warning.log
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by A-006** [comment]
Can you give me the dir you test or the INPUT file.

**Comment by pxlxingliang** [comment]
The test use the example in examples/xxx [The test is in examples/](https://github.com/deepmodeling/abacus-develop/tree/develop/examples/electric_field/Pt-slab)

**Comment by A-006** [comment]
> The test use the example in examples/xxx [The test is in examples/](https://github.com/deepmodeling/abacus-develop/tree/develop/examples/electric_field/Pt-slab)

![图片](https://github.com/user-attachments/assets/762c614f-fa67-4cef-b4fb-859a25f550f4)
the K point can correctly gernerate.
