### ISSUE TITLE
spin-orbit coupling effect case is too slow in computing nonlocal part

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#513]
## Background
Now, nonlocal part in SOC case is calculated very slow, while other case use new method developed by @wenfei-li . 
We need to use new method to optimize nonlocal part in SOC calculation.

## Describe the solution you'd like
There is not too mach work to do for include SOC calculation in new nonlocal part code, because the first step: save half (<phi|beta>) is already calculated and then we only should implement them (<phi|beta>Dij<beta|phi>).

**Comment by wenfei-li** [comment]
seems easy to do, will work on it
