### ISSUE TITLE
`nscf`calculation throw an ERROR `KILLED BY SIGNAL: 6 (Aborted)` in HSE calculation

### ISSUE THREAD

**Issue by xdzhu** [deepmodeling/abacus-develop#5135]
### Describe the bug

Either the latest 3.7.5 or the 3.6.5 version, when I do the nscf calculation after HSE scf, it runs into `KILLED BY SIGNAL: 6 (Aborted)`. After I comment the `dft_functional`, the NSCF calculation can run but the result is WRONG.

You can check the zip file:  [hse-nscf-ERROR.zip](https://github.com/user-attachments/files/17054694/hse-nscf-ERROR.zip)

When I claim that `dft_functional hse`, the running result gives an ERROR `KILLED BY SIGNAL: 6 (Aborted)` like:
![4752586500ef5acf518b696d2c169bb](https://github.com/user-attachments/assets/93545e96-6d3e-44c5-a700-bee82145e76f)

In this case, I check the running log with debug info and it seems broken at this step:
![e2d2bfe5364c97b913faaa032e46a49](https://github.com/user-attachments/assets/d70779b7-54c6-4f6f-8224-bda94aaa0a7e)

When I comment the `dft_functional` line which means set to pbe, the NSCF calculation can run but the result is definitely WRONG:
![image](https://github.com/user-attachments/assets/9776a4e4-d014-43ac-9169-62d34573328c)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by maki49** [comment]
... Is the STRU file missing in your zip package?

**Comment by xdzhu** [comment]
> ... Is the STRU file missing in your zip package?

Here I add the STRU file, you can check this file [hse-nscf-ERROR.zip](https://github.com/user-attachments/files/17054694/hse-nscf-ERROR.zip)
