### ISSUE TITLE
Documentation for features and outputs are needed!

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#514]
## Describe Current Status and Possible Solution

There should be an entire document describing the files and formats output by ABACUS 
* plane waves base (different npool parallel modes)  or local orbit base (Gamma only and multi-k points, ), including 
    * electronic iteration, 
    * ion iteration, 
    * crystal cell optimization, 
    * molecular dynamics, 
    * DeePKS, 
    * TDDFT, 

* We should count which files will output, and then find out what is missing, and whether the format of these files supports some post-processing files. 
The output files includes:
    * wave functions, 
    * electron density, 
    * energy levels, 
    * PDOS, 
    * electrostatic potential

**Comment by wenfei-li** [comment]
will be merged with a latest issue #1191
