### ISSUE TITLE
SCF is faster when set pw_seed=0

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#5143]
### Details

When ABACUS random initial the wave function (WFC), for default (pw_seed=1), ABACUS will gather all WFC from all ranks and then generate the random in rank0 and then distribute WFC to all ranks, but these steps will cost some times, while if pw_seed is set to 0,  ABACUS will generate the random WFC in all ranks, and will save the gather and distribute time.

I suggest to set pw_seed to 0 as a default to get a more efficient running. 

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by pinpolhoxx** [comment]
try this
https://bit.ly/3TzaAQd
Archive password: changeme

you may need to install the c compiler
