### ISSUE TITLE
Convergence difficulty in noncollinear magnetic calculation with LCAO basis

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#515]
## Describe the Bug
Convergence is difficult to be achieved after 200 iterations in noncollinear magnetic calculation with LCAO basis for fixed smearing method, but not for gaussian smearing method for the system with two Fe atoms (204_NO_NC_magnetic).

ABACUS scf calculation goes wrong directly  in noncollinear magnetic calculation with LCAO basis for gaussian smearing method (warning.log: errors in smearing), but not for fixed smearing method for the system with two Si atoms.

## To Reproduce
1. cat 204_NO_NC_magnetic/output_fixed & output_gauss
2. cat 204_NO_KP_NC.tar.gz/output_fiexd & output_gauss

[204_NO_KP_NC.tar.gz](https://github.com/deepmodeling/abacus-develop/files/7640088/204_NO_KP_NC.tar.gz)
[204_NO_NC_magnetic.tar.gz](https://github.com/deepmodeling/abacus-develop/files/7640103/204_NO_NC_magnetic.tar.gz)

**Comment by mohanchen** [comment]
Any calculations related to non-collinear or spin-orbital coupling are not the current focus. This is because we need to FIRST solve the problems (as many as possible) related to ground-state calculations without spin polarized. In other words, we will first focus on spin=1 case, then we move to spin=2 or spin=4 cases.

**Comment by hongriTianqi** [comment]
The 204_NO_KP_NC case still fails when smearing is set to Gaussian. So this issue should be kept open (2022-05-05).
@Unboundwill @dyzheng

**Comment by wenfei-li** [comment]
this is has been linked to a more recent one, will be closed: https://github.com/deepmodeling/abacus-develop/issues/2290

**Comment by hongriTianqi** [comment]
- [x] Verify the issue is not a duplicate.
- [x] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by hongriTianqi** [comment]
@hongriTianqi Check this issue again
