### ISSUE TITLE
Would it be possible to provide the address of the integration daily test cases?

### ISSUE THREAD

**Issue by A-006** [deepmodeling/abacus-develop#5154]
### Details

In the daily tests, the test cases used are different from those in the CI/CD on GitHub. It is difficult to locate the specific test cases, making troubleshooting challenging. Could you please add the daily test cases to the CI/CD, or provide a GitHub address for the test cases so that developers can download, test, and debug them themselves?
![图片](https://github.com/user-attachments/assets/2d45dfad-64c5-4433-a7ae-8b311c43b0f3)

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by QuantumMisaka** [comment]
@pxlxingliang Any comments ?

**Comment by pxlxingliang** [comment]
Hi, @A-006, when you open one report of daily test, you can download the reference INPUTs by path /outputs/results/results.zip, like:

![image](https://github.com/user-attachments/assets/818a5c01-39f4-4fc4-89af-9398ae7e5ae4)

**Comment by A-006** [comment]
fine,i'll have a try! thanks!
