### ISSUE TITLE
Can ABACUS do some constrained DFT calculation

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#516]
## Describe Current Status and Possible Solution

Maybe ABACUS support some interesting option to do calculation for constrained DFT.

Please leave some comments under this Issue.

**Comment by dyzheng** [comment]
For example, when we studying nitrogen-vacancy center, it requires an additional excitation of an electron conduction band to simulate the excited state, so we added two variables:
* ocp    
    * option for choose whether calcualting constrained DFT or not.
* ocp_set
    * The ocp_set is a string to set the number of occupancy, like 1 10 * 1 0 1 representing the 13 band occupancy, 12th band occupancy 0 and the rest 1, the code is parsing this string into an array through a regular expression.

**Comment by dyzheng** [comment]
I found related code about comment above that:

`

    // jiyy add 2020.10.11
    // fix bugs of ocp_set   --  Yuanbo Li 2021/8/17
        if(GlobalV::ocp == 1)
	{
		int count = 0;
		std::string pattern("([0-9]+\\*[0-9.]+|[0-9,.]+)");
		std::vector<std::string> str;
		std::string::size_type pos1, pos2;
		std::string c = " ";
		pos2 = GlobalV::ocp_set.find(c);
		pos1 = 0;
		while(std::string::npos != pos2)
		{
			str.push_back(GlobalV::ocp_set.substr(pos1, pos2-pos1));
			pos1 = pos2 + c.size();
			pos2 = GlobalV::ocp_set.find(c, pos1);
		}
		if(pos1 != GlobalV::ocp_set.length())
		{
			str.push_back(GlobalV::ocp_set.substr(pos1));
		}

		regex_t reg;
		regcomp(&reg, pattern.c_str(), REG_EXTENDED);
		regmatch_t pmatch[1];
		const size_t nmatch=1;
		for(int i=0; i<str.size(); ++i)
		{
			if(str[i] == "")
			{
				continue;
			}
			int status = regexec(&reg, str[i].c_str(), nmatch, pmatch, 0);
			std::string sub_str = "";
			for(int j=pmatch[0].rm_so; j!=pmatch[0].rm_eo; ++j)
			{
				sub_str += str[i][j];
			}
			std::string sub_pattern("\\*");
			regex_t sub_reg;
			regcomp(&sub_reg, sub_pattern.c_str(), REG_EXTENDED);
			regmatch_t sub_pmatch[1];
			const size_t sub_nmatch=1;
			if(regexec(&sub_reg, sub_str.c_str(), sub_nmatch, sub_pmatch, 0) == 0)
			{
				int pos = sub_str.find("*");
				int num = stoi(sub_str.substr(0, pos));
				double occ = stof(sub_str.substr(pos+1, sub_str.size()));
				std::vector<double> ocp_temp(num, occ);
				const std::vector<double>::iterator dest = GlobalV::ocp_kb.begin()+count;
				copy(ocp_temp.begin(), ocp_temp.end(), dest);
				count += num;
			}
			else
			{
				GlobalV::ocp_kb[count] = stof(sub_str);
				count += 1;
			}
		}
	}
`

**Comment by lyb9812** [comment]
It seems that ocp_set is only used in tddft now.
