### ISSUE TITLE
A doc to introduce fixed-potential method

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#5161]
### Details

Call for a doc to introduce the fixed-potential method

### Have you read the online manual http://abacus.deepmodeling.com/en/latest/

- [X] Yes, I have read the online manual.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific section of the documentation with the issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Update the documentation to address the issue, following the suggested improvement.
- [ ] Ensure the updated documentation adheres to the project's documentation standards.
- [ ] Test the updated documentation to ensure it is clear and accurate.
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Publish the updated documentation and notify the issue reporter.

**Comment by mohanchen** [comment]
https://bohrium.dp.tech/notebooks/86445129178
