### ISSUE TITLE
Different running time of MPI processes rised parallization speed collapse

### ISSUE THREAD

**Issue by xdzhu** [deepmodeling/abacus-develop#5170]
### Describe the bug

In the latest 3.7.5 version, when I set `OMP_NUM_THREADS_NUM=2 mpirun -np 20 abacus` it gives normal speed (9 sec) but after 2 steps it goes to extremely slow (60 sec). When I check the processes during running, it shows that every MPI hosts different running time.

When I reduce the MPI to 10 by using `OMP_NUM_THREADS_NUM=4 mpirun -np 10 abacus`, it also comes up.

I test the old 3.6.5 version, it can run well even with the during running time of MPI processes. (showed at the bottom)

Would you give some advices to get a good parallization performance? Thanks.

`20 MPI, 3.7.5`
![image](https://github.com/user-attachments/assets/21a7a604-2be0-4c44-9aa3-dcc27dd0da8b)
![image](https://github.com/user-attachments/assets/6656ad3b-33bd-4eb0-a8e0-a53cfa81519f)

`10 MPI, 3.7.5`
![image](https://github.com/user-attachments/assets/6d463d17-4c5b-4d6a-a34d-ff2db5f0b006)
![image](https://github.com/user-attachments/assets/730dfd58-ac9e-4ff8-b0f8-e3ab16aae6f9)

`10 MPI, 3.6.5`
![image](https://github.com/user-attachments/assets/dfba1b58-4232-418a-8a1f-0e288a84457d)
![image](https://github.com/user-attachments/assets/d6e78666-f393-4329-83bb-c93610374565)

### To Reproduce
the latest 3.7.5
and 3.6.5

### Environment
These are all with the same compilers icpc and mpiicpc in OneAPI 2023.1.0.
The submodules of LibRI and LibComm are also in consistent with the supporting version by using -DGIT_SUBMODULE=ON.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by caic99** [comment]
@xdzhu Should be `OMP_NUM_THREADS`

**Comment by QuantumMisaka** [comment]
@xdzhu Your dependences of 3.6.5 and 3.7.5 ?

**Comment by xdzhu** [comment]
> @xdzhu Should be `OMP_NUM_THREADS`

Yes, it's a typo in my description. I acctually set as the right format `OMP_NUM_THREADS` in my calculation:
![image](https://github.com/user-attachments/assets/f30dbbc0-13e9-41ab-93de-26f3359bb2d1)

**Comment by xdzhu** [comment]
> @xdzhu Your dependences of 3.6.5 and 3.7.5 ?

These are all with the same compilers `icpc` and `mpiicpc` in OneAPI 2023.1.0.

The submodules of `LibRI` and `LibComm` are also in consistent with the supporting version by using `-DGIT_SUBMODULE=ON`.

**Comment by QuantumMisaka** [comment]
@xdzhu I consider that you should check and re-compile your ABACUS 3.7.5

**Comment by WHUweiqingzhou** [comment]
@xdzhu  please upload the input files, then we will check it.

**Comment by WHUweiqingzhou** [comment]
I close this issue due to no updates from @xdzhu for three weeks, one can re-open it if there is any update.
