### ISSUE TITLE
Bug: several tests failed in code converge test

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#5192]
### Describe the bug

please see action https://github.com/deepmodeling/abacus-develop/actions/runs/11089849200/job/30811481597, there are several tests failed:
```
Warning: NG]    2 test cases out of 1499 failed.
1: 102_PW_PINT_UKS
1: 392_NO_GO_LR_HF
1: 
1: [ERROR     ] 21 test cases out of 1499 produced fatal error.
1: 101_PW_15_paw
1: 207_NO_KP_OXC
1: 260_NO_DJ_PK_PU_FM
1: 260_NO_DJ_PK_PU_SO
1: 260_NO_DJ_PK_PU_S1
1: 260_NO_DJ_PK_PU_AFM_URAMPING
1: 281_NO_KP_HSE
1: 281_NO_KP_HSE_symmetry
1: 282_NO_KP_HSE_complex
1: 283_NO_KP_HF
1: 284_NO_KP_PBE0
1: 285_NO_KP_RE_HSE
1: 286_NO_KP_CR_HSE
1: 304_NO_GO_AF_atommag
1: 381_NO_GO_S1_HSE
1: 382_NO_GO_S2_HSE
1: 383_NO_GO_SO_HSE
1: 384_NO_GO_S1_HSE_loop0_PU
1: 385_NO_GO_RE_S1_HSE
1: 386_NO_GO_MD_S1_HSE
1: 392_NO_GO_LR_HF

The following tests FAILED:
	  1 - integrated_test (Failed)
	114 - XCTest_PBE (Failed)
	115 - XCTest_HSE (Failed)
	116 - XCTest_PZ_SPN (Failed)
	157 - HSolver_bpcg (Failed)
```
This may due to 
```
1: -----AUTO TESTS OF ABACUS ------
1: ABACUS path: /__w/abacus-develop/abacus-develop/build/abacus
1: Number of processes: 4
1: Number of threads: 1
1: Test accuracy totenergy: 0.0000001 eV
1: Test accuracy force: 0.0001
1: Test accuracy stress: 0.001
1: Check accuaracy: 8
1: Test cases file: CASES_CPU.txt
1: Test cases regex: ^[^#].*_.*$
1: Generate reference: 
1: --------------------------------
```
that different run mode compared with tests designed to be triggered by PR or commits.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
Up to https://github.com/deepmodeling/abacus-develop/actions/runs/11436455697/job/31813916721, the converge tests still failed.
```
Warning: NG]    1 test cases out of 1547 failed.
1: 102_PW_PINT_UKS
1: 
1: [ERROR     ] 5 test cases out of 1547 produced fatal error.
1: 260_NO_DJ_PK_PU_FM
1: 260_NO_DJ_PK_PU_SO
1: 260_NO_DJ_PK_PU_S1
1: 260_NO_DJ_PK_PU_AFM_URAMPING
1: 304_NO_GO_AF_atommag
```

The following tests FAILED:
	  1 - integrated_test (Failed)
	165 - HSolver_bpcg (Failed)

**Comment by kirk0830** [comment]
@WHUweiqingzhou the 102_PW_PINT_UKS failed is because of the nthreads != 2, after the introduction of omp parallization in psi initializer. So it is an expected behavior

**Comment by WHUweiqingzhou** [comment]
I re-run the converge test with a new branch `converge`, but it also fails. I do not get useful information from log, could you have a look @caic99 ?
https://github.com/deepmodeling/abacus-develop/actions/runs/11771801075/job/32786252540

**Comment by caic99** [comment]
@WHUweiqingzhou The test hits the [timeout limit](https://github.com/deepmodeling/abacus-develop/actions/runs/11771801075/job/32786252540#step:6:2) of 6 hrs.
You can modify [here](https://github.com/deepmodeling/abacus-develop/actions/runs/11771801075/workflow#L29).
