### ISSUE TITLE
abacus-plot Command Not Found After Conda Installation

### ISSUE THREAD

**Issue by MabinogiX** [deepmodeling/abacus-develop#5217]
### Describe the bug

Description: I installed ABACUS using the following command:
```
conda create -n abacus_env abacus "libblas=*=*mkl" mpich -c conda-forge
```
However, after activating the environment, the abacus-plot command is not available.

![Image](https://github.com/user-attachments/assets/19ca1e00-4667-429a-a709-f59c02cdc7f8)

### Expected behavior

The abacus-plot command should be accessible after installation.

### To Reproduce

conda create -n abacus_env abacus "libblas=*=*mkl" mpich -c conda-forge

### Environment

Ubuntu 22.04
Python 3.12.7

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by caic99** [comment]
Hi @Angel-Jia ,
`abacus-plot` offers as a post-processing component, and expected to be a separate package than ABACUS itself. Please follow the [manual](https://github.com/deepmodeling/abacus-develop/blob/develop/tools/plot-tools/README.md) using it.
Feel free to tell us if you've encountered any troubles.

**Comment by MabinogiX** [comment]
@caic99 Thanks
