### ISSUE TITLE
Convergence problem using Methfessel Paxton smearing method in atomic basis calculation of Fe metal

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#522]
## Describe the Bug
Convergence is not achieved after 100 steps of electron iteration using Methfessel Paxton smearing method in atomic basis calculation of Fe metal. However, the corresponding calculation in plane wave calculation is successful.

## To Reproduce
1. cat 105_PW_MP_smearing/OUT.autotest/running.info (plane wave basis, success)
2. cat 205_NO_MP_smearing/OUT.autotest/running.info (atomic orbital basis, failed)
[MP_smearing_in_AO_basis_problem.tar.gz](https://github.com/deepmodeling/abacus-develop/files/7646423/MP_smearing_in_AO_basis_problem.tar.gz)

**Comment by mohanchen** [comment]
@YuLiu98 Could you take a look at this problem and propose your thoughts?

**Comment by YuLiu98** [comment]
I have some points to argue:
1) UNIFORM GRID DIM of PW and LCAO is different in this case, why? What is the difference in the grid division method ? 
2) replacing mp with gauss smearing, LCAO is also not converged with other parameters unchanged as PW does. Thus, the problem may not be mp smearing. 
3) With dense k points grids (12  12  12), larger sigma (0.02), and pulay mixing method (beta=0.3), LCAO is converged in this case. Maybe LCAO is more difficult to converge than PW in some cases.

**Comment by hongriTianqi** [comment]
Spin "flip over and again" happens in this test with LCAO basis.

 @YuLiu98 's method works with the following setting:
in INPUT:
smearing_method mp
smearring_sigma 0.02
mixing_type pulay
mixing_beta 0.3

K_POINTS
0
Gamma
12 12 12 0 0 0 

So I will close this ISSUE.
