### ISSUE TITLE
Toolchain can't download ELPA

### ISSUE THREAD

**Issue by MoseyQAQ** [deepmodeling/abacus-develop#5220]
### Describe the bug

Hi, I am trying to use toolchain to install ELPA. However, `Unsupported scheme ‘fhttps’` error was raised by `wget`:
```bash
==================== Installing ELPA ====================
wget  fhttps://elpa.mpcdf.mpg.de/software/tarball-archive/Releases/2024.05.001/elpa-2024.05.001.tar.gz -O elpa-2024.05.001.tar.gz
fhttps://elpa.mpcdf.mpg.de/software/tarball-archive/Releases/2024.05.001/elpa-2024.05.001.tar.gz: Unsupported scheme ‘fhttps’.
ERROR: (./scripts/stage3/install_elpa.sh) failed to download fhttps://elpa.mpcdf.mpg.de/software/tarball-archive/Releases/2024.05.001/elpa-2024.05.001.tar.gz
```
I guess the problem comes from here:
https://github.com/deepmodeling/abacus-develop/blob/5329628c0ab288ee4deb51471114b69f8f322bd2/toolchain/scripts/stage3/install_elpa.sh#L63

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by MoseyQAQ** [comment]
Another minor comment, In `build_abacus_gnu.sh`, the LAPACK and ELPA versions are `0.3.27` and `2024.03.001`, but the deps installed by toolchain are actually `0.3.28` and `2024.05.001`. So when running `build_abacus_gnu.sh`, cmake will tell me it can't find elpa and lapack. 

https://github.com/deepmodeling/abacus-develop/blob/6b81902d45cfd74ca66ce16ab390772a140470b4/toolchain/build_abacus_gnu.sh#L25-L27

https://github.com/deepmodeling/abacus-develop/blob/6b81902d45cfd74ca66ce16ab390772a140470b4/toolchain/scripts/stage2/install_openblas.sh#L11

https://github.com/deepmodeling/abacus-develop/blob/6b81902d45cfd74ca66ce16ab390772a140470b4/toolchain/scripts/stage3/install_elpa.sh#L12

**Comment by QuantumMisaka** [comment]
Thanks for your issue! These will be fixed
