### ISSUE TITLE
The image of ABACUS on bohrium doesn't  include DeePMD-kit, which is different from the introduction.

### ISSUE THREAD

**Issue by ieiue** [deepmodeling/abacus-develop#5221]
### Describe the bug

The image of ABACUS v3.6.4 in bohrium doesn't  include dp, while the included software is listed in the introduction as having deepmd-kit.![Image](https://github.com/user-attachments/assets/d12dc6a2-7158-49b7-a263-c6dec8c3f7e1)
![Image](https://github.com/user-attachments/assets/11fd2730-9104-4d93-8800-4f8fa5c249cc)

### Expected behavior

I can use deep potential by the ABACUS on bohrium.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by kirk0830** [comment]
![Image](https://github.com/user-attachments/assets/22a7a4fe-9660-4e37-a944-56046c4d3c9e)
Fixed. Thanks for your feedback! :)
