### ISSUE TITLE
Question: TDDFT velocity gauge code - choice for `ncut`

### ISSUE THREAD

**Issue by AsTonyshment** [deepmodeling/abacus-develop#5230]
### Details

I am currently reading through the TDDFT code, specifically the part related to the velocity gauge, and I am having some difficulty understanding the reasoning behind the choice of `ncut`(related to issue #5108). Below is the relevant piece of code from `H_TDDFT_pw.cpp`:

```cpp
int H_TDDFT_pw::check_ncut(int t_type)
{
    int ncut = 0;
    switch (t_type)
    {
    case 0:
        ncut = *(gauss_ncut.begin() + gauss_count);
        break;

    case 1:
        ncut = *(trape_ncut.begin() + trape_count);
        break;

    case 2:
        ncut = *(trigo_ncut.begin() + trigo_count);
        break;

    case 3:
        ncut = 1;
        break;

        // case 4:
        //     vext_time = cal_v_time_HHG();
        //     break;

    default:
        std::cout << "time_domain_type of electric field is wrong" << std::endl;
        break;
    }
    return ncut;
}
```

My question is: what does `ncut` do in function `update_At`, and why is `ncut` set to `1` in other case?

Maybe @ESROAMER is familiar about this?

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [x] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by ESROAMER** [comment]
The vector potential A(t) used in velocity gague rt-tddft, is obtained by integrating E(t). 
$A(t)=-\int E(t)dt$
The simplest way is to use the Euler method, update A(t) at every step: 
$\Delta A(t)=-E(t) \cdot \Delta t$. 
Where $\Delta t$ is normally ``md_dt``. Sometimes ``md_dt``itself might be too large to get a smooth intergral outcome, so I cut it into smaller pieces, calculate more data of $E(t)$ and processed them using Simpson integral to obtain more accurate results.

To describe the details clearly, give a specific example here. 
```
md_dt=0.1
ncut=4
```
Now if you want to get the value of $A(0)$. You need to calculate the value of $E(0),E(0.025),E(0.05),E(0.075),E(0.1)$ first and then processed them with Simpson integral. The large ``md_dt`` is now cut into 4 smaller pieces for a precise integral.

For other cases like length gague rt-tddft, A(t) is not needed. ``ncut=1`` simply means there's no need to cut the time.

**Comment by AsTonyshment** [comment]
@ESROAMER Okay I see, thanks for the clarification. So just to confirm, `ncut` only affects the accuracy of the $A(t)$ integral, is that correct? I'm currently working on fixing the bug in #5108, which seems to stem from splitting Simpson's integration into odd pieces (velocity gauge + Heaviside ext field). Would it be safe to adjust the default `ncut` value for the Heaviside ext field from `1` to something like `2`?

**Comment by ESROAMER** [comment]
> [@ESROAMER](https://github.com/ESROAMER) Okay I see, thanks for the clarification. So just to confirm, `ncut` only affects the accuracy of the A ( t ) integral, is that correct? I'm currently working on fixing the bug in [#5108](https://github.com/deepmodeling/abacus-develop/issues/5108), which seems to stem from splitting Simpson's integration into odd pieces (velocity gauge + Heaviside ext field). Would it be safe to adjust the default `ncut` value for the Heaviside ext field from `1` to something like `2`?

Yes, it would be safe. ``ncut`` should be set to an even number, and for Heaviside ext field, the integral would always be precise enough, so ``2`` would be a perfect choice. Sorry I made a mistake like this.

**Comment by ESROAMER** [comment]
https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_io/input_conv.cpp#L57
@AsTonyshment Please check the function ``read_td_efield``, you may initialize Heaviside ncut here as well.

**Comment by ESROAMER** [comment]
https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_io/input_conv.cpp#L57
@AsTonyshment Please check the function ``read_td_efield``, you may initialize Heaviside ncut here as well.

**Comment by AsTonyshment** [comment]
Actually, after a recent refactoring of the input, we will no longer use `input_conv.cpp` anymore, see [如何在 ABACUS 中新增一个输入参数（v3.7.0 后）](https://mcresearch.github.io/abacus-user-guide/develop-addinp2.html)

**Comment by ESROAMER** [comment]
Okay, I see. So this part would be moved to somewhere else in the future. Thanks for reminding me.
