### ISSUE TITLE
Bug: `ks_solver=cusolver` not working properly reporting CUDA error

### ISSUE THREAD

**Issue by AsTonyshment** [deepmodeling/abacus-develop#5240]
### Describe the bug

When I set `ks_solver=cusolver`, ABACUS quits with CUDA error (for example, a simple SCF task). After my testing, this seems to occur after PR #5225. Maybe @Cstandardlib can have a look?

```
 START CHARGE      : atomic
 DONE(1.21413    SEC) : INIT SCF
 * * * * * *
 << Start SCF iteration.
CUDA error at /home/itztony/Documents/Research/Coding/abacus-develop/source/module_hsolver/kernels/cuda/diag_cusolver.cu:132 code=1(cudaErrorInvalidValue) "cudaMemcpy(d_A2, A, sizeof(cuDoubleComplex) * lda * m, cudaMemcpyHostToDevice)" 
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[48991,1],0]
  Exit code:    1
--------------------------------------------------------------------------

```

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by Cstandardlib** [comment]
I will reproduce it locally.

**Comment by Cstandardlib** [comment]
When ks_solver is set to cusolver,
The error arises from:
line 154 of `hsolver_lcao.cpp` where an object of `DiagoCusolver` is created and `diag` method is called
```cpp
DiagoCusolver<T> cs(this->ParaV);
cs.diag(hm, psi, eigenvalue);
```
line 160 to 168 of `diago_cusolver.cpp` is excuted
```cpp
if (num_procs > 1)
    {
        MPI_Barrier(MPI_COMM_WORLD);
        // global psi for distribute
        int psi_len = myid == root_proc ? h_mat_g.row * h_mat_g.col : 1;
        std::vector<T> psi_g(psi_len);
        if (myid == root_proc)
        {
            this->dc.Dngvd(h_mat_g.col, h_mat_g.row, h_mat_g.p.get(), s_mat_g.p.get(), eigen.data(), psi_g.data());
        }
...
```
Then `dc.Dngvd` in `diago_cusolver.cpp` is invoked
```cpp
// diago_cusolver.cpp
this->dc.Dngvd(h_mat.row, h_mat.col, h_mat.p, s_mat.p, eigen.data(), eigenvectors.data());

// diago_cusolver.cuh
void Dngvd(int N, int M, std::complex<double> *A, std::complex<double> *B, double *W, std::complex<double> *V)
    {
        return Dngvd_complex(N, M, A, B, W, V);
    };

// diago_cusolver.cu
void Diag_Cusolver_gvd::Dngvd_complex(int N, int M, std::complex<double> *A, std::complex<double> *B, double *W, std::complex<double> *V){
    
    // copy A, B to the GPU
        assert(N == M);
        if (M != m) {
            this->finalize();
            this->init_complex(M);
        }
        checkCudaErrors( cudaMemcpy(d_A2, A, sizeof(cuDoubleComplex) * lda * m, cudaMemcpyHostToDevice) );
        checkCudaErrors( cudaMemcpy(d_B2, B, sizeof(cuDoubleComplex) * lda * m, cudaMemcpyHostToDevice) );
    ...
}
```
line 132 of `diago_cusolver.cu` is where the error is thrown.
**checkCudaErrors( cudaMemcpy(d_A2, A, sizeof(cuDoubleComplex) * lda * m, cudaMemcpyHostToDevice) );**

**Comment by Cstandardlib** [comment]
When I removed the 'DiagH' base class that 'DiagoCusolver' inherits from, the scf example using cusolver on the GPU works correctly. How peculiar!
