### ISSUE TITLE
Github PR Integration Test Failed

### ISSUE THREAD

**Issue by Cstandardlib** [deepmodeling/abacus-develop#5243]
### Describe the Testing Issue

ALL PR CI Integration Tests failed when Run pre-commit-ci/lite-action@v1.1.0:
```bash
Run pre-commit-ci/lite-action@v1.1.0
  with:
    msg: [pre-commit.ci lite] apply automatic fixes
/usr/bin/docker exec  15[2](https://github.com/deepmodeling/abacus-develop/actions/runs/11359818896/job/31596522204?pr=5239#step:7:2)d7f568dcd9bc78a19df769db9218007[3](https://github.com/deepmodeling/abacus-develop/actions/runs/11359818896/job/31596522204?pr=5239#step:7:3)e03fea1a0d7e0e7e417e294f5480f sh -c "cat /etc/*release | grep ^ID"
source/module_hsolver/test/diago_lcao_test.cpp: needs update
fetching pr...
saving artifact...
uploading artifact failed with code 127
```

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by Critsium-xy** [comment]
Be quick
