### ISSUE TITLE
Time consuming in OUTPUT is wrong when running with OPENMP

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#527]
When running with OPENMP (larger than 1 thread), the clock() function can not give the real time consuming.
Need  to use another suitable function to time the running.

**Comment by mohanchen** [comment]
Could you reach out to find some solutions? If we only need to change the timer implemented in ABACUS, then this will be a trivial thing to do and may be a good start to read the code structure in ABACUS. @pxlxingliang

**Comment by pxlxingliang** [comment]
The clock() function measures the CPU time used by the process, which means the cumulative CPU time of all threads that have ever existed in the process since it was started.
One solution is calling omp__get_wtime() which returns a value equal to the elapsed wall clock time in seconds since some time-in-the-past.  
I suggest retaining clock() to time the CPU times, and adding omp__get_wtime() to get the wall time.

include <omp.h>
double start; 
double end; 
start = omp_get_wtime(); 
... work to be timed ... 
end = omp_get_wtime(); 
printf("Work took %f seconds\n", end - start);
