### ISSUE TITLE
Memory leak in src_io/write_rho_cube.cpp

### ISSUE THREAD

**Issue by YuLiu98** [deepmodeling/abacus-develop#528]
## Describe the Bug
The variable **num_z** newed in src_io/write_rho_cube.cpp (Line 97) is not deleted.

## To Reproduce
1. [e.g. clone the source code from ...]
2. [e.g. configure CMake with options ...]
3. [e.g. build ABACUS with ...]
4. [e.g. run ABACUS with ...]

## Environment
- OS: [e.g. CentOS 7.6]
- Compiler: [e.g. Intel LLVM 2021.1]
- Optional Dependencies: [e.g. Intel MKL]

**Comment by wenfei-li** [comment]
We will update the code to release the memory properly.

**Comment by dyzheng** [comment]
This function is not indispensable in printing charge density, maybe we can add a option variable for this function?
