### ISSUE TITLE
Output of total threads used in stdout

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#5280]
### Background

There is no output for OpenMP parallel numbers and total threads number in stdout of ABACUS, like
```
 ---------------------------------------------------------
 Self-consistent calculations for electrons
 ---------------------------------------------------------
 SPIN    KPOINTS         PROCESSORS  NBASE
 2       10              4           1182
 ---------------------------------------------------------
 Use Systematically Improvable Atomic bases
 ---------------------------------------------------------
 ELEMENT ORBITALS        NBASE       NATOM       XC
 H       2s1p-6au        5           3
 C       2s2p1d-7au      13          13
 O       2s2p1d-7au      13          2
 Fe      4s2p2d1f-8au    27          36
 ---------------------------------------------------------
 Initial plane wave basis and FFT box
 ---------------------------------------------------------
```

### Describe the solution you'd like

Like this below
```
 ---------------------------------------------------------
 Self-consistent calculations for electrons
 ---------------------------------------------------------
 SPIN    KPOINTS         PROCESSORS  THREADS     NBASE
 2       10              4           16          1182
 ---------------------------------------------------------
 Use Systematically Improvable Atomic bases
 ---------------------------------------------------------
 ELEMENT ORBITALS        NBASE       NATOM       XC
 H       2s1p-6au        5           3
 C       2s2p1d-7au      13          13
 O       2s2p1d-7au      13          2
 Fe      4s2p2d1f-8au    27          36
 ---------------------------------------------------------
 Initial plane wave basis and FFT box
 ---------------------------------------------------------
```

### Task list only for developers

- [x] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by mohanchen** [comment]
Excellent suggestion, we will update it!
