### ISSUE TITLE
Convergence problem with nspin=2

### ISSUE THREAD

**Issue by iduygnay** [deepmodeling/abacus-develop#5300]
### Details

This case does not converge.[pto_dw_fe.tar.gz](https://github.com/user-attachments/files/17428827/pto_dw_fe.tar.gz)

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by mohanchen** [comment]
Could you describe what's the problem? @iduygnay

**Comment by iduygnay** [comment]
Thanks to @QuantumMisaka , he suggested we adjust the mixing_beta to 0.05, and it converges now. 
![Image](https://github.com/user-attachments/assets/e7e8dee5-ae41-4828-8b5f-ca57b3394c89)

**Comment by QuantumMisaka** [comment]
@mohanchen @kirk0830 @WHUweiqingzhou My suggestion is from #3821 
From these hard-converge examples, can we consider a way for more robust SCF iteration algorithm? One idea is to gradually low-down the `mixing_beta` value (like learning rate strategy)

**Comment by mohanchen** [comment]
> [@mohanchen](https://github.com/mohanchen) [@kirk0830](https://github.com/kirk0830) [@WHUweiqingzhou](https://github.com/WHUweiqingzhou) My suggestion is from [#3821](https://github.com/deepmodeling/abacus-develop/issues/3821) From these hard-converge examples, can we consider a way for more robust SCF iteration algorithm? One idea is to gradually low-down the `mixing_beta` value (like learning rate strategy)

Thanks, but this may slow down some typical examples.
