### ISSUE TITLE
MD parallel run error

### ISSUE THREAD

**Issue by 1041176461** [deepmodeling/abacus-develop#5309]
### Describe the bug

When I run MD in parallel with multiple cores, the program breaks when outputting information after the 0th MD step. Single core can run normally.
![Image](https://github.com/user-attachments/assets/ef84642b-f915-4cab-aec3-aaf1329a0870)

![Image](https://github.com/user-attachments/assets/80caf291-3fbe-4a4b-91de-b9c9142478c1)

### To Reproduce

1. ABACUS v3.8.0 works fine
2. develop version fails

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by YuLiu98** [comment]
Note that the update on module_md since v3.8.0 is PR #5215 and #5242 .

However, these two PRs are not related to this bug. 

you can refer to issue #5229 and #5228, which is actually another bug not related to MD.
