### ISSUE TITLE
blas_connector Warning: control reaches end of non-void function

### ISSUE THREAD

**Issue by Cstandardlib** [deepmodeling/abacus-develop#5310]
### Description
There are some functions of code of `blas_connector.cpp` that is not properly terminated:
```cpp
double BlasConnector::dot( const int n, const double *X, const int incX, const double *Y, const int incY, base_device::AbacusDevice_t device_type)
{
	if (device_type == base_device::AbacusDevice_t::CpuDevice) {
		return ddot_(&n, X, &incX, Y, &incY);
}
}
```
I propose adding a default branch (`else` clause or `return` statement) at the end to pair `if`-clause.

### Related PR
#5242 
#5301 
@Critsium-xy 

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by Critsium-xy** [comment]
I will fix this problem in the PR
https://github.com/deepmodeling/abacus-develop/pull/5301

**Comment by mohanchen** [comment]
Good idea.
