### ISSUE TITLE
There are some failed examples and fatal errors When use Autotest.sh

### ISSUE THREAD

**Issue by sunlight905** [deepmodeling/abacus-develop#5317]
### Details

Dear all,
I install abacus 3.8.0 with GNU and CUDA in the ROCKY LINUX 9 with a machine of RTX 4090. I want to test whether the abacus is rightly installed. So I test the abacus by Autotest.sh in the folder of abacus-develop-3.8.0/tests/integrate. But there are some failed examples and fatal errors.
#######################################
[WARNING]^[[0m    2 test cases out of 1543 failed.
102_PW_PINT_UKS
204_NO_KP_NC

^[[0;31m[ERROR     ]^[[0m 4 test cases out of 1543 produced fatal error.
101_PW_15_paw
212_NO_wfc_ienvelope
312_NO_GO_wfc_ienvelope
312_NO_GO_wfc_istate
#######################################
Could you give me some advices?

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [x] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by dzzz2001** [comment]
The test case '204_NO_KP_NC' fails because GPU version of ABACUS can't run normally if nspin is set to 4(issue #5306), this bug will be fixed in a recent PR. 
I guess 101_PW_15_paw failed because your ABACUS is not built with "-DENABLE_PAW=ON".
I have no idea how 102_PW_PINT_UKS fails, there may be some bug in PW basis related code. 
Regarding "212_NO_wfc_ienvelope," "312_NO_GO_wfc_ienvelope," and "312_NO_GO_wfc_istate", I'm still finding out the reasons for these test failures.

**Comment by dzzz2001** [comment]
102_PW_PINT_UKS fails because the setting `init_wfc nao` doesn't support GPU currently.

**Comment by dzzz2001** [comment]
"212_NO_wfc_ienvelope," "312_NO_GO_wfc_ienvelope," and "312_NO_GO_wfc_istate" fail because the setting “calculation get_wf" doesn't support gpu currently.

**Comment by sunlight905** [comment]
@dzzz2001 Thanks for your reply! 
I turn from vasp to abacus. when install vasp, there are command "make test" to verify whether the install is right.
So I want to know if the "./Autotest.sh > check.txt" in the folder tests/integrate is same as vasp for verifing the correctness of installation, or by other methods?

**Comment by kirk0830** [comment]
@sunlight905 approximately equivalent. According to @dzzz2001 , you can realize most of tests failed because the insufficient support of gpu. For numerical calculation, I remember the threshold is quite tight (I am sure on cpu, but for gpu, is it the same? @dzzz2001 ), if so, you can use ABACUS with less concern.

**Comment by dzzz2001** [comment]
> "212_NO_wfc_ienvelope," "312_NO_GO_wfc_ienvelope," and "312_NO_GO_wfc_istate" fail because the setting “calculation get_wf" doesn't support gpu currently.

Make a correction, The real reason those thress test cases did not pass was that your ABACUS was not built with "-DBUILD_TESTING=ON".

**Comment by dzzz2001** [comment]
> [@sunlight905](https://github.com/sunlight905) approximately equivalent. According to [@dzzz2001](https://github.com/dzzz2001) , you can realize most of tests failed because the insufficient support of gpu. For numerical calculation, I remember the threshold is quite tight (I am sure on cpu, but for gpu, is it the same? [@dzzz2001](https://github.com/dzzz2001) ), if so, you can use ABACUS with less concern.

@kirk0830 the threshold for gpu is the same as cpu.

**Comment by mohanchen** [comment]
Good discussion! I will close this one and feel free to propose new ones.
