### ISSUE TITLE
Gamma_only calculation and smearing = fixed (default) results in error

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#534]
## Describe the Bug
I am testing a calculation on the silicon single crystal system. The default smearing method is fixed in gamma_only calculation, which results in convergence difficulty until the smearing is changed from "fixed" to "gauss".

## To Reproduce
1. the attached example shows convergence difficulty after 100 steps.
2. change smearing to "gauss", it goes successfully.

[308_NO_GO_CF_RE.tar.gz](https://github.com/deepmodeling/abacus-develop/files/7665559/308_NO_GO_CF_RE.tar.gz)

**Comment by mohanchen** [comment]
This is not a full report, the convergence problem usually related to whether the system has a large band gap or not, or even a metal. Therefore, at least......., at least you need to specify which system you are testing. Otherwise, one needs to download and open the files attached to see the problem. @hongriTianqi

**Comment by hongriTianqi** [comment]
> This is not a full report, the convergence problem usually related to whether the system has a large band gap or not, or even a metal. Therefore, at least......., at least you need to specify which system you are testing. Otherwise, one needs to download and open the files attached to see the problem. @hongriTianqi

The tested system is Si single crystal.

**Comment by hongriTianqi** [comment]
This issues has not been solved, so it should be kept open. @Unboundwill @mohanchen @dyzheng

**Comment by hongriTianqi** [comment]
The convergence problem disappears in ABACUS v3.2, so I will close this issue now.
