### ISSUE TITLE
Error in offline installation of ABACUS on supercomputing servers using toolchain

### ISSUE THREAD

**Issue by yycx1111** [deepmodeling/abacus-develop#5347]
### Details

I am using toolchain to install abacus-3.7.5 offline on a supercomputing server that is not connected to an extranet. after toolchain_gnu.sh, I encountered errors when executing build_abacus_gnu.sh.
What can be done about these errors？

This is the part where the message starts：

-- The CXX compiler identification is GNU 9.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- RapidJSON found. Headers: @INCLUDE_INSTALL_DIR@
-- Found Git: /usr/bin/git (found version "2.25.1")
-- Found git: attempting to get commit info...
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Warning at CMakeLists.txt:102 (message):
  Failed to get git commit info

-- Found Cereal: /vol8/home/hnu_chn/software/abacus-develop-3.7.5/toolchain/install/cereal-1.3.2/include/cereal
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Found ELPA: /vol8/home/hnu_chn/software/abacus-develop-3.7.5/toolchain/install/elpa-2024.03.001/cpu/lib/libelpa_openmp.so
-- Performing Test ELPA_VERSION_SATISFIES
-- Performing Test ELPA_VERSION_SATISFIES - Success
-- Found MPI_CXX: /vol8/home/hnu_chn/software/abacus-develop-3.7.5/toolchain/install/openmpi-4.1.6/lib/libmpi.so (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - NOTFOUND
-- Found FFTW3: /vol8/home/hnu_chn/software/abacus-develop-3.7.5/toolchain/install/fftw-3.3.10/lib/libfftw3_omp.so
-- Looking for sgemm_
-- Looking for sgemm_ - not found
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Found BLAS: /vol8/home/hnu_chn/software/abacus-develop-3.7.5/toolchain/install/openblas-0.3.27/lib/libopenblas.so
-- Looking for cheev_
-- Looking for cheev_ - found
-- Found LAPACK: /vol8/home/hnu_chn/software/abacus-develop-3.7.5/toolchain/install/openblas-0.3.27/lib/libopenblas.so;-lpthread;-lm;-ldl
CMake Warning (dev) at CMakeLists.txt:418 (find_package):
  Policy CMP0144 is not set: find_package uses upper-case <PACKAGENAME>_ROOT
  variables.  Run "cmake --help-policy CMP0144" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Environment variable SCALAPACK_ROOT is set to:

    /vol8/home/hnu_chn/software/abacus-develop-3.7.5/toolchain/install/scalapack-2.2.1

  For compatibility, find_package is ignoring the variable, but code in a
  .cmake module might still use it.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found ScaLAPACK: /vol8/home/hnu_chn/software/abacus-develop-3.7.5/toolchain/install/scalapack-2.2.1/lib/libscalapack.so
-- Could NOT find MKL (missing: MKL_DIR)
-- Found MKL_SCALAPACK: MKL_SCALAPACK-NOTFOUND
-- Found Torch: /vol8/home/hnu_chn/software/abacus-develop-3.7.5/toolchain/install/libtorch-2.1.2/lib/libtorch.so
-- Checking for one of the modules 'libxc'
-- Found Libxc: /vol8/home/hnu_chn/software/abacus-develop-3.7.5/toolchain/install/libxc-6.2.2/lib/libxc.so
-- Found Libxc: version 6.2.2
-- Configuring done (8.7s)
-- Generating done (3.8s)
-- Build files have been written to: /vol8/home/hnu_chn/software/abacus-develop-3.7.5/build_abacus_gnu
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
chdir: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
chdir: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
chdir: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
chdir: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
chdir: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
chdir: error retrieving current directory: getcwd: cannot access parent directories: Permission denied

This is the end of the error message：
[ 67%] Built target gint
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
[ 67%] Built target cell
make[2]: *** [source/module_hamilt_lcao/hamilt_lcaodft/CMakeFiles/hamilt_lcao.dir/build.make:76: source/module_hamilt_lcao/hamilt_lcaodft/CMakeFiles/hamilt_lcao.dir/hamilt_lcao.cpp.o] Error 1
make[2]: *** [source/module_hamilt_lcao/hamilt_lcaodft/CMakeFiles/hamilt_lcao.dir/build.make:272: source/module_hamilt_lcao/hamilt_lcaodft/CMakeFiles/hamilt_lcao.dir/FORCE_STRESS.cpp.o] Error 1
/vol8/home/hnu_chn/software/abacus-develop-3.7.5/source/module_hamilt_lcao/module_deepks/cal_gedm.cpp: In member function ‘void LCAO_Deepks::cal_gedm_equiv(int)’:
/vol8/home/hnu_chn/software/abacus-develop-3.7.5/source/module_hamilt_lcao/module_deepks/cal_gedm.cpp:99:16: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
   99 |     std::system(cmd.c_str());
      |     ~~~~~~~~~~~^~~~~~~~~~~~~
make[1]: *** [CMakeFiles/Makefile2:1217: source/module_elecstate/CMakeFiles/elecstate.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1451: source/module_hamilt_lcao/hamilt_lcaodft/CMakeFiles/hamilt_lcao.dir/all] Error 2
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
[ 67%] Built target deepks
make: *** [Makefile:136: all] Error 2
-- Install configuration: ""

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [x] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by QuantumMisaka** [comment]
There are lots of `permission denied` error, please check your server
