### ISSUE TITLE
ABACUS met Segmentation fault

### ISSUE THREAD

**Issue by radixwang** [deepmodeling/abacus-develop#5352]
### Describe the bug

运行不了
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions

### To Reproduce

<!-- Uploading "KPT.txt"... --

### Environment

Ubuntu 24.04

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by mohanchen** [comment]
Thanks for your report! I am sorry you met the problem, could you upload the original input files? @radixwang

**Comment by mohanchen** [comment]
I have changed the title to English.

**Comment by radixwang** [comment]
INPUT_PARAMETERS
#Parameters (1.General)
suffix          DO3
calculation     cell-relax
pseudo_dir	/root/PP
orbital_dir	/root/PP

#Parameters (2.Iteration)
ecutwfc	        100
scf_thr		1e-5
relax_nmax      100
force_thr_ev    0.01
stress_thr      0.5

nspin           2
#Parameters (3.Basis)
basis_type		lcao
ntype           3


out_stru


K_POINTS
0
Gamma
4 4 4 0 0 0



ATOMIC_SPECIES
Fe   55.845  Fe_ONCV_PBE-1.0.upf
Si   28.085  Si_ONCV_PBE-1.0.upf
Al   26.982  Al_ONCV_PBE-1.0.upf

NUMERICAL_ORBITAL
Fe_gga_8au_100Ry_4s2p2d1f.orb
Si_gga_7au_100Ry_2s2p1d.orb
Al_gga_7au_100Ry_4s4p1d.orb

LATTICE_CONSTANT
1.889726

LATTICE_VECTORS
5.627256852858  0.000000000000  0.000000000000
0.000000000000  5.636859103882  0.000000000000
0.000000000000  0.000000000000  5.640412951841

ATOMIC_POSITIONS
Direct

Fe
4.0
12
0.004047902185  0.993956888523  0.000388054267  1  1  1  mag  0.0
0.495952097815  0.993956888523  0.000388054267  1  1  1  mag  0.0
0.004047902185  0.506043111477  0.000388054267  1  1  1  mag  0.0
0.250000000000  0.750000000000  0.250000000000  1  1  1  mag  0.0
0.495952097815  0.506043111477  0.000388054267  1  1  1  mag  0.0
0.750000000000  0.750000000000  0.250000000000  1  1  1  mag  0.0
0.004047902185  0.993956888523  0.499611945733  1  1  1  mag  0.0
0.495952097815  0.993956888523  0.499611945733  1  1  1  mag  0.0
0.750000000000  0.250000000000  0.750000000000  1  1  1  mag  0.0
0.004047902185  0.506043111477  0.499611945733  1  1  1  mag  0.0
0.495952097815  0.506043111477  0.499611945733  1  1  1  mag  0.0
0.750000000000  0.750000000000  0.750000000000  1  1  1  mag  0.0

Si
0.000
2
0.250000000000  0.250000000000  0.250000000000  1  1  1  mag  0.0
0.250000000000  0.750000000000  0.750000000000  1  1  1  mag  0.0

Al
0.000
2
0.750000000000  0.250000000000  0.250000000000  1  1  1  mag  0.0
0.250000000000  0.250000000000  0.750000000000  1  1  1  mag  0.0

**Comment by WHUweiqingzhou** [comment]
Hi @radixwang, I fail to reproduce the Segmentation fault you met. I attach my calculation here:
[5352.zip](https://github.com/user-attachments/files/17598390/5352.zip)
Could you upload your output files?

**Comment by WHUweiqingzhou** [comment]
@radixwang 
If you still have the problem, please reopen this issue without hesitation, and output your output files.
