### ISSUE TITLE
Should `ElecState::print_etot` function called only after SCF converge ?

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#5354]
### Describe the bug

As the screenshot, this function will be called not only in SCF convergence but also after number of SCF steps reach 100

![Image](https://github.com/user-attachments/assets/14e02eb5-5862-43be-bdc3-fddcfa699f9a)

print criterion:

![Image](https://github.com/user-attachments/assets/fcb5b30b-ecbe-4aa8-beb6-80499039dd26)

### Expected behavior

This information should only be called after SCF converge

### To Reproduce

perform SCF calculation which can last more than 100 steps

### Environment

ABACUS 3.8.1 (newest now)
intel toolchain

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by QuantumMisaka** [comment]
`ElecState::print_etot` is defined in *source/module_elecstate/elecstate_print.cpp*, and the definition of `printe` is noted as
```
/// @param printe: print energy every 'printe' electron iteration.
```
and this `print_etot` is called by *source/module_esolver/esolver_ks.cpp* by using `PARAM.inp.printe` as `printe` input, and then we can find `printe` in documentation in https://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#printe
```
printe
Type: Integer
Description: Print out energy for each band for every printe step
Default: 100
```

Is this printe needed for any application ?

**Comment by QuantumMisaka** [comment]
@mohanchen @Qianruipku Any comments ?

**Comment by WHUweiqingzhou** [comment]
@QuantumMisaka it is an expected behavior. What is your prefer?

**Comment by QuantumMisaka** [comment]
> @QuantumMisaka it is an expected behavior. What is your prefer?

@WHUweiqingzhou 
I'm curious about where we can use this parameter printe，for commom user this print-out should be only output after SCF convergence. My suggestion is to set default printe equal to scf_nmax
