### ISSUE TITLE
Question: ABACUS throws core dumped error on PC when running examples of official Bohrium Notebook

### ISSUE THREAD

**Issue by 18792462829** [deepmodeling/abacus-develop#5356]
### Details

                              ABACUS v3.8.0

               Atomic-orbital Based Ab-initio Computation at UStc                    

                     Website: http://abacus.ustc.edu.cn/                             
               Documentation: https://abacus.deepmodeling.com/                       
                  Repository: https://github.com/abacusmodeling/abacus-develop       
                              https://github.com/deepmodeling/abacus-develop         
                      Commit: 5486275 (Mon Sep 30 12:16:10 2024 +0800)

 Sun Oct 27 14:01:59 2024
Segmentation fault (core dumped)
                                          

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [x] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by 18792462829** [comment]
我运行的是BOHRIUM上计算材料学的石墨烯能带计算示例

**Comment by QuantumMisaka** [comment]
@18792462829 Plz use English to discussion here
In which way do you install ABACUS?

**Comment by 18792462829** [comment]
> [@18792462829](https://github.com/18792462829) Plz use English to discussion here In which way do you install ABACUS?

I used CONDA for the installation, and when I did the graphene band calculation this error occurred during the scf phase, and the nscf phase worked fine

**Comment by QuantumMisaka** [comment]
@18792462829 Can you try another installation method like toolchain ?

**Comment by 18792462829** [comment]
I didn't succeed using the other methods because of some warnings, but I installed again with conda and succeeded, but now a new problem, sh: 1: abacus-plot: not found

**Comment by 18792462829** [comment]
> [@18792462829](https://github.com/18792462829) Can you try another installation method like toolchain ?

I didn't succeed using the other methods because of some warnings, but I installed again with conda and succeeded, but now a new problem, sh: 1: abacus-plot: not found

**Comment by 18792462829** [comment]
> [@18792462829](https://github.com/18792462829) Can you try another installation method like toolchain ?

I didn't have this problem after installing with toolchain, but after I shut down the virtual machine, I couldn't find abacus

**Comment by 18792462829** [comment]
> [@18792462829](https://github.com/18792462829) Can you try another installation method like toolchain ?

I didn't have this problem after installing with toolchain, but after I closed the terminal and opened one again, I couldn't find abacus

**Comment by WHUweiqingzhou** [comment]
please reopen it if the issue is still here.
