### ISSUE TITLE
PDOS output error

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#536]
The PDOS gives some unreasonable occupation number like 1e-200
[pdos.zip](https://github.com/deepmodeling/abacus-develop/files/7672804/pdos.zip)

This small value should be reasonable, which means an occupation of zero, while the occupation of 10^50 or enven larger is unreasonable in the below example from hongriTianqi.

**Comment by dyzheng** [comment]
I can't download your uploading file, maybe you can uploading it again?

**Comment by dyzheng** [comment]
I recalculated example 207_NO_KP_OD, the output file PDOS seems correct.

**Comment by hongriTianqi** [comment]
> I recalculated example 207_NO_KP_OD, the output file PDOS seems correct.
I repeated this calculation too. The order of magnitudes of PDOS values changes hugely (from 10^50 to 10^100 to 10^200, etc)

**Comment by hongriTianqi** [comment]
> I recalculated example 207_NO_KP_OD, the output file PDOS seems correct.

 I repeated this calculation too. The order of magnitudes of PDOS values change hugely (from 10^50 to 10^100 to 10^200, etc)

**Comment by pxlxingliang** [comment]
I check the 207_NO_KP_OD PDOS again, in my server, the maximum occupition is about 10, and minmum occupation is 3.244e-108, repeated calculations give the smae results. 
So, it is reasonable.
It seems the big changing only occurs in @hongriTianqi 's server?

**Comment by dyzheng** [comment]
I have checked all array in energy_dos.cpp has initial default zero, maybe we should test this problem in @hongriTianqi environment.

**Comment by hongriTianqi** [comment]
> I check the 207_NO_KP_OD PDOS again, in my server, the maximum occupition is about 10, and minmum occupation is 3.244e-108, repeated calculations give the smae results. So, it is reasonable. It seems the big changing only occurs in @hongriTianqi 's server?

I used ABACUS within a Docker container. The compile flag are as follows:

  # compile CXX with /usr/bin/x86_64-linux-gnu-g++-10
  CXX_DEFINES = -DEXX_DM=3 -DEXX_H_COMM=2 -DMETIS -DTEST_EXX_LCAO=0 -DTEST_EXX_RADIAL=1 -DUSE_CEREAL_SERIALIZATION -D__EXX -D__FFTW3 -D__F    P -D__LCAO -D__MPI -D__SELINV
  CXX_INCLUDES = -I/root/abacus-develop/source -isystem /usr/include/x86_64-linux-gnu/mpich
  CXX_FLAGS =  -Wno-write-strings -g -fopenmp

**Comment by mohanchen** [comment]
We should have documents for PDOS using LCAO.

**Comment by mohanchen** [comment]
PW or LCAO? any further progress?

**Comment by pxlxingliang** [comment]
> PW or LCAO? any further progress?

LCAO.
@dyzheng can you repeat the problem occurred at @hongriTianqi 's compile environment?

**Comment by dyzheng** [comment]
Sorry, I can't repeat this problem till now. @pxlxingliang @hongriTianqi

**Comment by pxlxingliang** [comment]
we can not repeat this problem now.
