### ISSUE TITLE
Docs: where to find hands-on manual of compiling ABACUS on Deep-learning Computing Unit (DCU) device?

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#5366]
### Details

there are users requesting on this.

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [x] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by Cstandardlib** [comment]
We have one in the [Chinese docs](https://mcresearch.github.io/abacus-user-guide/).

[ABACUS 在曙光 DCU 集群上的编译与使用](https://mcresearch.github.io/abacus-user-guide/abacus-dcu.html)

A link to this set of docs will be added to main page of Github Readme.
