### ISSUE TITLE
Aborted when running ABACUS with dp(from DPA-2 finetune)

### ISSUE THREAD

**Issue by ieiue** [deepmodeling/abacus-develop#5367]
### Describe the bug

When calculating the vacancy energy of Fe2 and the SIA of Fe256, there are errors.
![Image](https://github.com/user-attachments/assets/5b192230-531d-4639-86cf-a9312be23270)
![Image](https://github.com/user-attachments/assets/a7222d4b-efc5-4bc3-af64-6ebe495b1c98)

### To Reproduce

ABACUS v3.8.0
DPA-2 and DeePMD-kit(Q1) 
[Fe2_vacancy.zip](https://github.com/user-attachments/files/17553914/Fe2_vacancy.zip)
[Fe256_SIA.zip](https://github.com/user-attachments/files/17553913/Fe256_SIA.zip)
![Image](https://github.com/user-attachments/assets/2b27aae9-0309-40ea-be73-b620423b3dc5)
(I failed to upload this potential)

### Environment

gcc 11.3.0

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by caic99** [comment]
Hi @ieiue , 
It seems to be an error running DPA2 inference. I would suggest you creating this issue in deepmd-kit repo.

**Comment by WHUweiqingzhou** [comment]
I am agree with @caic99. Please reopen it if you meet any problem from ABACUS side.
