### ISSUE TITLE
Docs needed for data layout

### ISSUE THREAD

**Issue by Cstandardlib** [deepmodeling/abacus-develop#5370]
### Details

We need developer docs for Data Layout of different containers, such as `Psi`.
- What is the actual organization and arrangement of data in memory?
- leading dimensions
- How to access some columns/rows by indexing, row-major vs column-major?
- Other Notes to keep in mind during code development. Like, some operations are NOT recommended because they are very inefficient, etc.

We also need docs for implementation of algorithms, like whether the array is column major.

### Have you read the online manual http://abacus.deepmodeling.com/en/latest/

- [x] Yes, I have read the online manual.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific section of the documentation with the issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Update the documentation to address the issue, following the suggested improvement.
- [ ] Ensure the updated documentation adheres to the project's documentation standards.
- [ ] Test the updated documentation to ensure it is clear and accurate.
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Publish the updated documentation and notify the issue reporter.

**Comment by mohanchen** [comment]
OK, we will have Psi documents soon.

**Comment by Cstandardlib** [comment]
Need some docs especially on relationship between `ngk_pointer`, `get_current_nbas`, `get_nbasis`.
They are confusing and can vary a lot.

Results of dimension output:
```cpp
const int dim = psi.get_current_nbas();
const int nband = psi.get_nbands();
const int ld_psi = psi.get_nbasis();
```
![Image](https://github.com/user-attachments/assets/fea09461-d881-4397-add8-4964290aa80c)

run abacus in `examples/pw_Al` with 
```bash
 SPIN    KPOINTS         PROCESSORS  THREADS     
 1       8               1           56     
```
![Image](https://github.com/user-attachments/assets/11278fbc-f207-4864-9e26-1b90a8648e6e)


run the same example with `OMP_NUM_THREADS=1 mpirun -np 2 abacus`
```bash
 SPIN    KPOINTS         PROCESSORS  THREADS     
 1       8               2           2           
```
