### ISSUE TITLE
Question: meta-GGA implementation in ABACUS

### ISSUE THREAD

**Issue by AsTonyshment** [deepmodeling/abacus-develop#5372]
### Details

I am reading `module_hamilt_general/module_xc/xc_functional_vxc.cpp`, and I am confused about meta-GGA implementation in ABACUS. 

According to libxc manual https://libxc.gitlab.io/manual/libxc-5.1.x/, `xc_mgga_exc_vxc` is defined as follow:
```cpp
void xc_mgga_exc_vxc(const xc_func_type *p, int np, double *rho, double *sigma, double *lapl, double *tau, 
     double * exc, double *vrho, double *vsigma, double *vlapl, double *vtau)
```
However in the ABACUS code, it seems that `lapl`(i.e. $$\nabla^2\rho$$) is not used:
```cpp
xc_mgga_exc_vxc(&func, nrxx, rho.data(), sigma.data(), sigma.data(),
                kin_r.data(), exc.data(), vrho.data(), vsigma.data(), vlapl.data(), vtau.data());
```
Instead `sigma`(i.e. $$\nabla\rho\cdot \nabla\rho$$) is passed. Is this correct?

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [x] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by WHUweiqingzhou** [comment]
@jinzx10 could you have a look?

**Comment by jinzx10** [comment]
> [@jinzx10](https://github.com/jinzx10) could you have a look?

I think this should be reviewed by a density functional expert.

**Comment by jeanwsr** [comment]
Laplacian is not used by most MGGAs. You can query libxc to know whether lapl is needed for certain functional like
https://github.com/pyscf/pyscf/blob/b519c3dd4935e97dac2d646fc75dc5739911559e/pyscf/lib/dft/libxc_itrf.c#L711

**Comment by AsTonyshment** [comment]
I see. So should we implement checks to ensure that users do not apply mGGA functionals with the Laplacian? Alternatively, we could add a function to compute $\nabla^2\rho$. In either case, we should ensure that this does not lead to **UNDEFINED BEHAVIOUR** in the underlying code.

**Comment by jeanwsr** [comment]
Yeah, in principle there should be a check. (the lapl-needed mGGAs are very rare, though)
