### ISSUE TITLE
Bad termination when setting `out_mat_hs`=`true`/`True`.

### ISSUE THREAD

**Issue by ErjieWu** [deepmodeling/abacus-develop#5389]
### Describe the bug

When running ABACUS with input parameter `out_mat_hs=1`, it works normally. But if I set `out_mat_hs`=`True` or `true`, it will throw a termination as follows:
![Image](https://github.com/user-attachments/assets/2a5dc685-3ab0-4405-b3bf-6e21a88c6ae8)

### To Reproduce

The full INPUT file is:
```
INPUT_PARAMETERS
# Created by Atomic Simulation Enviroment
ntype                                   1
ecutwfc                                 100
scf_nmax                                100
smearing_method                         gaussian
smearing_sigma                          0.002
basis_type                              lcao
ks_solver                               genelpa
mixing_type                             pulay
mixing_beta                             0.7
scf_thr                                 1e-07
symmetry                                0
calculation                             scf
force_thr                               0.001
kspacing                                0.08
lspinorb                                0
dft_functional                          hse
init_chg                                file
out_mat_hs                              true
```

STRU:
```
ATOMIC_SPECIES
Si  28.085        Si_ONCV_PBE-1.0.upf

NUMERICAL_ORBITAL
Si_gga_7au_100Ry_2s2p1d.orb

LATTICE_CONSTANT
1.8897261258369282

LATTICE_VECTORS
5.4437020000      0.0000000000      0.0000000000
0.0000000000      5.4437020000      0.0000000000
0.0000000000      0.0000000000      5.4437020000

ATOMIC_POSITIONS
Direct

Si
0.0000000000
8
0.9998180000 0.9930840000 0.0002490000 1 1 1 v 0.0 0.0 0.0 mag 0.0
0.9988170000 0.5025970000 0.5036740000 1 1 1 v 0.0 0.0 0.0 mag 0.0
0.4969490000 0.5004760000 0.0053650000 1 1 1 v 0.0 0.0 0.0 mag 0.0
0.5033170000 0.9987410000 0.4977020000 1 1 1 v 0.0 0.0 0.0 mag 0.0
0.7471640000 0.2589800000 0.7582050000 1 1 1 v 0.0 0.0 0.0 mag 0.0
0.2489230000 0.2472750000 0.2563730000 1 1 1 v 0.0 0.0 0.0 mag 0.0
0.2531180000 0.7474660000 0.7389000000 1 1 1 v 0.0 0.0 0.0 mag 0.0
0.7518960000 0.7513820000 0.2395340000 1 1 1 v 0.0 0.0 0.0 mag 0.0
```

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by kirk0830** [comment]
you should use 1 instead of true, the throw of stoi means converting from string to integer.

**Comment by mohanchen** [comment]
http://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#out-mat-hs

**Comment by mohanchen** [comment]
A nice question, it seems that you need to put 1 or 0, as described in the online document.

**Comment by kirk0830** [comment]
> A nice question, it seems that you need to put 1 or 0, as described in the online document.

@mohanchen other users used to have suggestions on this, maybe a simple function supporting 1, T, True, .TRUE., etc can solve this more gracefully, and this is what the solution of VASP.

**Comment by ErjieWu** [comment]
![Image](https://github.com/user-attachments/assets/7fa32e14-e1e9-4b6c-b61d-dfcf28afb3bb)


> A nice question, it seems that you need to put 1 or 0, as described in the online document.

The online document may have some issues as it requires users to use Boolean variable.

**Comment by kirk0830** [comment]
@ErjieWu ouch, thanks, now I realize what the real problem is. I will reopen this issue. Thanks for your comments.
