### ISSUE TITLE
Seeking magnetic anisotropic tutorial

### ISSUE THREAD

**Issue by radixwang** [deepmodeling/abacus-develop#5395]
### Details

I would like to ask if there are any tutorials on calculating the magnetic anisotropy constant, thanks.

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [x] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by WHUweiqingzhou** [comment]
@radixwang, 
You can perform two SCF calculations with initial magnetic moments along different directions to get Magnetic Anisotropy Energy (MAE).  MAE is induced by the Spin Orbital Coupling (SOC) effect. So please make sure SOC is on in INPUT:
```
noncolin	1
lspinorb	1
```
Then, you can prepare two STRUs. The initial magnetic moment of one is set as follows, and get $E_{001}$:
```
Fe #label
0.0000   #magnetism
2 #number of atoms
        0.0000000005        0.9999999999        0.9999999996 m 1 1 1 mag 0.0 0.0 1.0
        0.4999999995        0.5000000001        0.5000000004 m 1 1 1 mag 0.0 0.0 1.0
```
 The initial magnetic moment of the other one is set as follows, and get $E_{100}$:
```
Fe #label
0.0000   #magnetism
2 #number of atoms
        0.0000000005        0.9999999999        0.9999999996 m 1 1 1 mag 1.0 0.0 0.0
        0.4999999995        0.5000000001        0.5000000004 m 1 1 1 mag 1.0 0.0 0.0
```
After two full SCF calculations, you can get MAE by $E_{MAE}=E_{001}-E_{100}$. If notice that, MAE is very small, at the order of $\mu eV$. Please make convergence test very carefully to determine the converged `ecutwfc` and `kspacing`.

**Comment by radixwang** [comment]
ok i have to try
