### ISSUE TITLE
Compiling warning with CUDA

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#5409]
### Describe the Code Quality Issue

![Image](https://github.com/user-attachments/assets/1606a27d-6b05-4f63-8653-2fb04a3a5530)
![Image](https://github.com/user-attachments/assets/a5cce51d-3732-44a9-88eb-42d311e46b20)
![Image](https://github.com/user-attachments/assets/27bea932-5bda-4a76-b655-3121e85d0deb)

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by WHUweiqingzhou** [comment]
@Critsium-xy could you have a look?

**Comment by Critsium-xy** [comment]
I partially fixed it here https://github.com/deepmodeling/abacus-develop/pull/5444
Warnings in plain_mixing.h may need someone else's help? I had never reached this part before
