### ISSUE TITLE
Docs: Some parameters' values set in our example might be misleading

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#5420]
### Details

There are users followed the way to set parameters and complained the result was unreliable. More annotations should be added to guide user to know what kind of parameter setting on one specific calculation task can lead to a reliable result.

### Have you read the online manual http://abacus.deepmodeling.com/en/latest/

- [x] Yes, I have read the online manual.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific section of the documentation with the issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Update the documentation to address the issue, following the suggested improvement.
- [ ] Ensure the updated documentation adheres to the project's documentation standards.
- [ ] Test the updated documentation to ensure it is clear and accurate.
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Publish the updated documentation and notify the issue reporter.

**Comment by WHUweiqingzhou** [comment]
@qq270814845 could you have a look?
