### ISSUE TITLE
Fail to read HexxR_* files when doing nscf calculation with hybrid functional

### ISSUE THREAD

**Issue by ErjieWu** [deepmodeling/abacus-develop#5422]
### Describe the bug

The HexxR_* files generated by old version ABACUS can not be read by the newest version (v3.8.1) now, resulting in the failure of nscf calculation with hse functional. A new realization that supports reading old version files in new version ABACUS is in need.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by maki49** [comment]
You can try reading by `read_HexxR_cereal`, but I'm not sure whether it works...
https://github.com/deepmodeling/abacus-develop/issues/2235
