### ISSUE TITLE
Some separate directories are needed to store the corresponding files of each MD steps

### ISSUE THREAD

**Issue by 1041176461** [deepmodeling/abacus-develop#5424]
### Background

When I want to output the information corresponding to each MD step such as Hk, Sk, wfck, 

![Image](https://github.com/user-attachments/assets/42a1fe36-b11d-4577-9d1d-19dabca250ad)

but do not want to append them all to a large file (i.e. set  `out_app_flag 0` for generating separate files), there will be a lot of files in the "OUT*" directory. In particular, when outputting the information of each k-point in each MD step, the "OUT*" directory cannot be opened. 

### Describe the solution you'd like

It is necessary to build separate directories for different information, similar to the "STRU" directory for storing the structure files of each MD step, which may be cleaner.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by mohanchen** [comment]
Another method is to store all information in one file

**Comment by 1041176461** [comment]
Yes, setting `out_app_flag 1` can output to a file, but the file is usually huge, which is not convenient for reading and analyzing. Separate files are more convenient to process. Storing separate files in separate subdirectories will make the OUT directory cleaner. Otherwise, it will be inconvenient to use commands such as `ls` and `cp`.

**Comment by YuLiu98** [comment]
I suggest setting `out_app_flag` to 1 for appending all information into one file as QE does. As you said, the folder cannot be opened if there are too many files, so adding another folder can not solve this problem fundamentally.

**Comment by mohanchen** [comment]
> I suggest setting `out_app_flag` to 1 for appending all information into one file as QE does. As you said, the folder cannot be opened if there are too many files, so adding another folder can not solve this problem fundamentally.

I agree, in QE CPMD, the velocity and position data are accumulated in one corresponding file.
