### ISSUE TITLE
Questions about  the use of DeePKS

### ISSUE THREAD

**Issue by yycx1111** [deepmodeling/abacus-develop#5434]
### Details

I have  installed deepks and abacus on my local machine. I met some problems with package and function versions in the case of running a single water molecule in deepks. Here are a few of my questions, since I didn't get feedback for asking questions in the deepks community. I ask the same questions in abacus.
1. What version of pyscf is compatible with deepks? What can be done about the following problems?
/deepks-kit/examples/water_single/iter/iter.init/00.scf/task.trn.00/err:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 6, in <module>
    from pyscf import gto, lib
ModuleNotFoundError: No module named 'pyscf'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 6, in <module>
    from pyscf import gto, lib
ModuleNotFoundError: No module named 'pyscf'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 6, in <module>
    from pyscf import gto, lib
ModuleNotFoundError: No module named 'pyscf'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 6, in <module>
    from pyscf import gto, lib
ModuleNotFoundError: No module named 'pyscf'
systems/group.00 failed! error: PenaltyMixin.get_fock() got an unexpected keyword argument 'fock_last'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 268, in <module>
    cli()
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/main.py", line 174, in scf_cli
    main(**argdict)
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 236, in main
    meta, result = solve_mol(mol, model, fields, labels,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 52, in solve_mol
    cf.kernel()
  File "<string>", line 2, in kernel
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/pyscf/scf/hf.py", line 2000, in scf
    kernel(self, self.conv_tol, self.conv_tol_grad,
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/pyscf/scf/hf.py", line 175, in kernel
    fock = mf.get_fock(h1e, s1e, vhf, dm, cycle, mf_diis, fock_last=fock_last)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PenaltyMixin.get_fock() got an unexpected keyword argument 'fock_last'
systems/group.00 failed! error: PenaltyMixin.get_fock() got an unexpected keyword argument 'fock_last'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 268, in <module>
    cli()
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/main.py", line 174, in scf_cli
    main(**argdict)
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 236, in main
    meta, result = solve_mol(mol, model, fields, labels,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 52, in solve_mol
    cf.kernel()
  File "<string>", line 2, in kernel
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/pyscf/scf/hf.py", line 2000, in scf
    kernel(self, self.conv_tol, self.conv_tol_grad,
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/pyscf/scf/hf.py", line 175, in kernel
    fock = mf.get_fock(h1e, s1e, vhf, dm, cycle, mf_diis, fock_last=fock_last)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PenaltyMixin.get_fock() got an unexpected keyword argument 'fock_last'
systems/group.00 failed! error: PenaltyMixin.get_fock() got an unexpected keyword argument 'fock_last'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 268, in <module>
    cli()
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/main.py", line 174, in scf_cli
    main(**argdict)
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 236, in main
    meta, result = solve_mol(mol, model, fields, labels,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 52, in solve_mol
    cf.kernel()
  File "<string>", line 2, in kernel
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/pyscf/scf/hf.py", line 2000, in scf
    kernel(self, self.conv_tol, self.conv_tol_grad,
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/pyscf/scf/hf.py", line 175, in kernel
    fock = mf.get_fock(h1e, s1e, vhf, dm, cycle, mf_diis, fock_last=fock_last)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PenaltyMixin.get_fock() got an unexpected keyword argument 'fock_last'

2. Is deepks still being updated? Cause I've encountered some problems that suggest that the function or package used is old and may no longer work.
3. Is there a container image with deepks readily available on the Bohrium platform?

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [x] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by QuantumMisaka** [comment]
@WHUweiqingzhou Any comments? I do think a hands-on tutorial for deepks-abacus installation along with deepks notebook is needed

**Comment by WHUweiqingzhou** [comment]
> [@WHUweiqingzhou](https://github.com/WHUweiqingzhou) Any comments? I do think a hands-on tutorial for deepks-abacus installation along with deepks notebook is needed

Second it. We will consider this.

**Comment by ErjieWu** [comment]
@yycx1111 It seems there are issues with matching deepks-kit with the newest pyscf version. You can use deepks-kit with ABACUS instead.

Here's a way to use ABACUS+deepks in conda environment:

```
conda create -n abacus+deepks python=3.12 numpy=1.26.0 scipy h5py ruamel.yaml=0.17.21 paramiko abacus "libblas=*=*mkl" mpich -c conda-forge

conda activate abacus+deepks

# Install pytorch, the cuda version depends on your machine
conda install pytorch torchvision torchaudio cpuonly -c pytorch # cpu version
conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia # gpu version

# use develop branch
pip install git+https://github.com/deepmodeling/deepks-kit@develop
```

**Comment by yycx1111** [comment]
> [@yycx1111](https://github.com/yycx1111) It seems there are issues with matching deepks-kit with the newest pyscf version. You can use deepks-kit with ABACUS instead.
> 
> Here's a way to use ABACUS+deepks in conda environment:
> 
> ```
> conda create -n abacus+deepks python=3.12 numpy=1.26.0 scipy h5py ruamel.yaml=0.17.21 paramiko abacus "libblas=*=*mkl" mpich -c conda-forge
> 
> conda  activate abacus+deepks
> 
> # Install pytorch, the cuda version depends on your machine
> conda install pytorch cudatoolkit=10.2 -c pytorch # cpu version
> conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia # gpu version
> 
> # use develop branch
> pip install git+https://github.com/deepmodeling/deepks-kit@develop
> ```

Thank you for your reply. But I have been experiencing problems with network connections or failing to connect to the site when creating the environment, and I still have problems with connection errors even after switching to the Tsinghua source. Do you have any suggestions on how to create an environment?
The problems are like this:
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libmagma-2.8.0-hfdb99dd_0.conda>                                                
Elapsed: -                                                                                                                                                                                                                                                                                                                                                                                                           
An HTTP error occurred when trying to retrieve this URL.                                                                                                                                                    
HTTP errors are often intermittent, and a simple retry will get you on your way.                                                                                                                                                                                                                                                                                                                                  
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libmagma-2.8.0-hfdb99dd_0.conda>                                                
Elapsed: -                                                                                                                                                                                                                                                                                                                                                                                                              
An HTTP error occurred when trying to retrieve this URL.                                                                                                                                                    
HTTP errors are often intermittent, and a simple retry will get you on your way.

**Comment by ErjieWu** [comment]
> > [@yycx1111](https://github.com/yycx1111) It seems there are issues with matching deepks-kit with the newest pyscf version. You can use deepks-kit with ABACUS instead.
> > Here's a way to use ABACUS+deepks in conda environment:
> > ```
> > conda create -n abacus+deepks python=3.12 numpy=1.26.0 scipy h5py ruamel.yaml=0.17.21 paramiko abacus "libblas=*=*mkl" mpich -c conda-forge
> > 
> > conda  activate abacus+deepks
> > 
> > # Install pytorch, the cuda version depends on your machine
> > conda install pytorch cudatoolkit=10.2 -c pytorch # cpu version
> > conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia # gpu version
> > 
> > # use develop branch
> > pip install git+https://github.com/deepmodeling/deepks-kit@develop
> > ```
> 
> Thank you for your reply. But I have been experiencing problems with network connections or failing to connect to the site when creating the environment, and I still have problems with connection errors even after switching to the Tsinghua source. Do you have any suggestions on how to create an environment? The problems are like this: CondaHTTPError: HTTP 000 CONNECTION FAILED for url http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libmagma-2.8.0-hfdb99dd_0.conda Elapsed: - An HTTP error occurred when trying to retrieve this URL. HTTP errors are often intermittent, and a simple retry will get you on your way. CondaHTTPError: HTTP 000 CONNECTION FAILED for url http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libmagma-2.8.0-hfdb99dd_0.conda Elapsed: - An HTTP error occurred when trying to retrieve this URL. HTTP errors are often intermittent, and a simple retry will get you on your way.

This looks like a problem with your network setup. Maybe you should check things like your network environment and proxy settings.

**Comment by yycx1111** [comment]
> > > [@yycx1111](https://github.com/yycx1111) It seems there are issues with matching deepks-kit with the newest pyscf version. You can use deepks-kit with ABACUS instead.
> > > Here's a way to use ABACUS+deepks in conda environment:
> > > ```
> > > conda create -n abacus+deepks python=3.12 numpy=1.26.0 scipy h5py ruamel.yaml=0.17.21 paramiko abacus "libblas=*=*mkl" mpich -c conda-forge
> > > 
> > > conda  activate abacus+deepks
> > > 
> > > # Install pytorch, the cuda version depends on your machine
> > > conda install pytorch cudatoolkit=10.2 -c pytorch # cpu version
> > > conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia # gpu version
> > > 
> > > # use develop branch
> > > pip install git+https://github.com/deepmodeling/deepks-kit@develop
> > > ```
> > 
> > 
> > Thank you for your reply. But I have been experiencing problems with network connections or failing to connect to the site when creating the environment, and I still have problems with connection errors even after switching to the Tsinghua source. Do you have any suggestions on how to create an environment? The problems are like this: CondaHTTPError: HTTP 000 CONNECTION FAILED for url http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libmagma-2.8.0-hfdb99dd_0.conda Elapsed: - An HTTP error occurred when trying to retrieve this URL. HTTP errors are often intermittent, and a simple retry will get you on your way. CondaHTTPError: HTTP 000 CONNECTION FAILED for url http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libmagma-2.8.0-hfdb99dd_0.conda Elapsed: - An HTTP error occurred when trying to retrieve this URL. HTTP errors are often intermittent, and a simple retry will get you on your way.
> 
> This looks like a problem with your network setup. Maybe you should check things like your network environment and proxy settings.

After running conda install pytorch cudatoolkit=10.2 -c pytorch # cpu version, I encountered the following problems. Any suggestions for the pytorch install command for CPU version?
Channels:                                                                                                                                                                                                   
 - pytorch                                                                                                                                                                                                  
 - defaults                                                                                                                                                                                                 
Platform: linux-64                                                                                                                                                                                          
Collecting package metadata (repodata.json): done                                                                                                                                                           
Solving environment: failed                                                                                                                                                                                 
                                                                                                                                                                                                            
LibMambaUnsatisfiableError: Encountered problems while solving:                                                                                                                                             
  - nothing provides cudatoolkit >=11.1,<11.2 needed by pytorch-1.10.0-py3.6_cuda11.1_cudnn8.0.5_0                                                                                                          
  - package abacus-3.8.2-cuda_mpi_mpich_h6026299_1 requires libtorch >=2.5.1,<2.6.0a0, but none of the providers can be installed                                                                           
                                                                                                                                                                                                            
Could not solve for environment specs                                                                                                                                                                       
The following packages are incompatible                                                                                                                                                                     
├─ abacus is installable and it requires                                                                                                                                                                    
│  └─ libtorch >=2.5.1,<2.6.0a0 , which requires
│     ├─ nccl >=2.23.4.1,<3.0a0 , which requires
│     │  └─ cuda-version >=11.0,<12.0a0  with the potential options
│     │     ├─ cuda-version 11.8 would require
│     │     │  └─ cudatoolkit 11.8|11.8.* , which can be installed;
│     │     ├─ cuda-version 11.0 would require
│     │     │  └─ cudatoolkit 11.0|11.0.* , which can be installed;
│     │     ├─ cuda-version 11.1 would require
│     │     │  └─ cudatoolkit 11.1|11.1.* , which can be installed;
│     │     ├─ cuda-version 11.2 would require
│     │     │  └─ cudatoolkit 11.2|11.2.* , which can be installed;
│     │     ├─ cuda-version 11.3 would require
│     │     │  └─ cudatoolkit 11.3|11.3.* , which can be installed;
│     │     ├─ cuda-version 11.4 would require
│     │     │  └─ cudatoolkit 11.4|11.4.* , which can be installed;
│     │     ├─ cuda-version 11.5 would require
│     │     │  └─ cudatoolkit 11.5|11.5.* , which can be installed;
│     │     ├─ cuda-version 11.6 would require
│     │     │  └─ cudatoolkit 11.6|11.6.* , which can be installed;
│     │     └─ cuda-version 11.7 would require
│     │        └─ cudatoolkit 11.7|11.7.* , which can be installed;
│     └─ pytorch 2.5.1 cuda118_*_303, which can be installed;
├─ cudatoolkit 10.2**  is not installable because it conflicts with any installable versions previously reported;
└─ pytorch is not installable because there are no viable options
   ├─ pytorch [0.4.0|0.4.1|...|2.5.1] conflicts with any installable versions previously reported;
   ├─ pytorch [1.10.0|1.10.1|...|1.9.1] would require
   │  └─ cudatoolkit >=11.1,<11.2 , which does not exist (perhaps a missing channel);
   ├─ pytorch 1.11.0 would require
   │  └─ cudatoolkit >=11.5,<11.6 , which does not exist (perhaps a missing channel);
   ├─ pytorch [1.12.0|1.12.1] would require
   │  └─ cudatoolkit >=11.6,<11.7 , which does not exist (perhaps a missing channel);
   ├─ pytorch [1.13.0|1.13.1] would require
   │  └─ pytorch-cuda >=11.6,<11.7 , which requires
   │     └─ cuda 11.6.* , which does not exist (perhaps a missing channel);
   ├─ pytorch [1.13.0|1.13.1|2.0.0|2.0.1] would require
   │  └─ pytorch-cuda >=11.7,<11.8  but there are no viable options
   │     ├─ pytorch-cuda 11.7 would require
   │     │  └─ cuda-cudart >=11.7,<11.8 , which does not exist (perhaps a missing channel);
   │     └─ pytorch-cuda 11.7 would require
   │        └─ cuda 11.7.* , which does not exist (perhaps a missing channel);
   ├─ pytorch [1.7.1|1.8.0] would require
   │  └─ python_abi 3.9.* *_cp39, which does not exist (perhaps a missing channel);
   ├─ pytorch [2.0.0|2.0.1|...|2.5.1] would require
   │  └─ pytorch-cuda >=11.8,<11.9  but there are no viable options
   │     ├─ pytorch-cuda 11.8 would require
   │     │  └─ cuda-cudart >=11.8,<12.0 , which does not exist (perhaps a missing channel);
   │     └─ pytorch-cuda 11.8 would require
   │        └─ cuda 11.8.* , which does not exist (perhaps a missing channel);
   ├─ pytorch [2.1.0|2.1.1|...|2.5.1] would require
   │  └─ pytorch-cuda >=12.1,<12.2 , which requires
   │     └─ cuda-cudart >=12.1,<12.2 , which does not exist (perhaps a missing channel);
   ├─ pytorch [0.2.0|0.3.0] would require
   │  └─ cudatoolkit 7.5* , which does not exist (perhaps a missing channel);
   ├─ pytorch [0.2.0|0.3.0|0.3.1] would require
   │  └─ cudatoolkit 8.0* , which does not exist (perhaps a missing channel);
   ├─ pytorch [0.3.1|0.4.0] would require
   │  └─ cudatoolkit 8.0.* , which does not exist (perhaps a missing channel);
   ├─ pytorch 1.0.1 would require
   │  └─ cudatoolkit >=8.0,<8.1.0a0 , which does not exist (perhaps a missing channel);
   └─ pytorch [2.0.1|2.3.0] would require
      └─ __cuda >=11.8 , which is missing on the system.

**Comment by ErjieWu** [comment]
> > > > [@yycx1111](https://github.com/yycx1111) It seems there are issues with matching deepks-kit with the newest pyscf version. You can use deepks-kit with ABACUS instead.
> > > > Here's a way to use ABACUS+deepks in conda environment:
> > > > ```
> > > > conda create -n abacus+deepks python=3.12 numpy=1.26.0 scipy h5py ruamel.yaml=0.17.21 paramiko abacus "libblas=*=*mkl" mpich -c conda-forge
> > > > 
> > > > conda  activate abacus+deepks
> > > > 
> > > > # Install pytorch, the cuda version depends on your machine
> > > > conda install pytorch cudatoolkit=10.2 -c pytorch # cpu version
> > > > conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia # gpu version
> > > > 
> > > > # use develop branch
> > > > pip install git+https://github.com/deepmodeling/deepks-kit@develop
> > > > ```
> > > 
> > > 
> > > Thank you for your reply. But I have been experiencing problems with network connections or failing to connect to the site when creating the environment, and I still have problems with connection errors even after switching to the Tsinghua source. Do you have any suggestions on how to create an environment? The problems are like this: CondaHTTPError: HTTP 000 CONNECTION FAILED for url http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libmagma-2.8.0-hfdb99dd_0.conda Elapsed: - An HTTP error occurred when trying to retrieve this URL. HTTP errors are often intermittent, and a simple retry will get you on your way. CondaHTTPError: HTTP 000 CONNECTION FAILED for url http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libmagma-2.8.0-hfdb99dd_0.conda Elapsed: - An HTTP error occurred when trying to retrieve this URL. HTTP errors are often intermittent, and a simple retry will get you on your way.
> > 
> > 
> > This looks like a problem with your network setup. Maybe you should check things like your network environment and proxy settings.
> 
> After running conda install pytorch cudatoolkit=10.2 -c pytorch # cpu version, I encountered the following problems. Any suggestions for the pytorch install command for CPU version? Channels:
> 
> * pytorch
> * defaults
>   Platform: linux-64
>   Collecting package metadata (repodata.json): done
>   Solving environment: failed
> 
> LibMambaUnsatisfiableError: Encountered problems while solving:
> 
> * nothing provides cudatoolkit >=11.1,<11.2 needed by pytorch-1.10.0-py3.6_cuda11.1_cudnn8.0.5_0
> * package abacus-3.8.2-cuda_mpi_mpich_h6026299_1 requires libtorch >=2.5.1,<2.6.0a0, but none of the providers can be installed
> 
> Could not solve for environment specs The following packages are incompatible ├─ abacus is installable and it requires │ └─ libtorch >=2.5.1,<2.6.0a0 , which requires │ ├─ nccl >=2.23.4.1,<3.0a0 , which requires │ │ └─ cuda-version >=11.0,<12.0a0 with the potential options │ │ ├─ cuda-version 11.8 would require │ │ │ └─ cudatoolkit 11.8|11.8.* , which can be installed; │ │ ├─ cuda-version 11.0 would require │ │ │ └─ cudatoolkit 11.0|11.0.* , which can be installed; │ │ ├─ cuda-version 11.1 would require │ │ │ └─ cudatoolkit 11.1|11.1.* , which can be installed; │ │ ├─ cuda-version 11.2 would require │ │ │ └─ cudatoolkit 11.2|11.2.* , which can be installed; │ │ ├─ cuda-version 11.3 would require │ │ │ └─ cudatoolkit 11.3|11.3.* , which can be installed; │ │ ├─ cuda-version 11.4 would require │ │ │ └─ cudatoolkit 11.4|11.4.* , which can be installed; │ │ ├─ cuda-version 11.5 would require │ │ │ └─ cudatoolkit 11.5|11.5.* , which can be installed; │ │ ├─ cuda-version 11.6 would require │ │ │ └─ cudatoolkit 11.6|11.6.* , which can be installed; │ │ └─ cuda-version 11.7 would require │ │ └─ cudatoolkit 11.7|11.7.* , which can be installed; │ └─ pytorch 2.5.1 cuda118___303, which can be installed; ├─ cudatoolkit 10.2** is not installable because it conflicts with any installable versions previously reported; └─ pytorch is not installable because there are no viable options ├─ pytorch [0.4.0|0.4.1|...|2.5.1] conflicts with any installable versions previously reported; ├─ pytorch [1.10.0|1.10.1|...|1.9.1] would require │ └─ cudatoolkit >=11.1,<11.2 , which does not exist (perhaps a missing channel); ├─ pytorch 1.11.0 would require │ └─ cudatoolkit >=11.5,<11.6 , which does not exist (perhaps a missing channel); ├─ pytorch [1.12.0|1.12.1] would require │ └─ cudatoolkit >=11.6,<11.7 , which does not exist (perhaps a missing channel); ├─ pytorch [1.13.0|1.13.1] would require │ └─ pytorch-cuda >=11.6,<11.7 , which requires │ └─ cuda 11.6._ , which does not exist (perhaps a missing channel); ├─ pytorch [1.13.0|1.13.1|2.0.0|2.0.1] would require │ └─ pytorch-cuda >=11.7,<11.8 but there are no viable options │ ├─ pytorch-cuda 11.7 would require │ │ └─ cuda-cudart >=11.7,<11.8 , which does not exist (perhaps a missing channel); │ └─ pytorch-cuda 11.7 would require │ └─ cuda 11.7.* , which does not exist (perhaps a missing channel); ├─ pytorch [1.7.1|1.8.0] would require │ └─ python_abi 3.9.* __cp39, which does not exist (perhaps a missing channel); ├─ pytorch [2.0.0|2.0.1|...|2.5.1] would require │ └─ pytorch-cuda >=11.8,<11.9 but there are no viable options │ ├─ pytorch-cuda 11.8 would require │ │ └─ cuda-cudart >=11.8,<12.0 , which does not exist (perhaps a missing channel); │ └─ pytorch-cuda 11.8 would require │ └─ cuda 11.8._ , which does not exist (perhaps a missing channel); ├─ pytorch [2.1.0|2.1.1|...|2.5.1] would require │ └─ pytorch-cuda >=12.1,<12.2 , which requires │ └─ cuda-cudart >=12.1,<12.2 , which does not exist (perhaps a missing channel); ├─ pytorch [0.2.0|0.3.0] would require │ └─ cudatoolkit 7.5* , which does not exist (perhaps a missing channel); ├─ pytorch [0.2.0|0.3.0|0.3.1] would require │ └─ cudatoolkit 8.0* , which does not exist (perhaps a missing channel); ├─ pytorch [0.3.1|0.4.0] would require │ └─ cudatoolkit 8.0.* , which does not exist (perhaps a missing channel); ├─ pytorch 1.0.1 would require │ └─ cudatoolkit >=8.0,<8.1.0a0 , which does not exist (perhaps a missing channel); └─ pytorch [2.0.1|2.3.0] would require └─ __cuda >=11.8 , which is missing on the system.

Ahh, I’ve made a mistake. For cpu version, try 

```
conda install pytorch torchvision torchaudio cpuonly -c pytorch
```

**Comment by yycx1111** [comment]
> > > > > [@yycx1111](https://github.com/yycx1111) It seems there are issues with matching deepks-kit with the newest pyscf version. You can use deepks-kit with ABACUS instead.
> > > > > Here's a way to use ABACUS+deepks in conda environment:
> > > > > ```
> > > > > conda create -n abacus+deepks python=3.12 numpy=1.26.0 scipy h5py ruamel.yaml=0.17.21 paramiko abacus "libblas=*=*mkl" mpich -c conda-forge
> > > > > 
> > > > > conda  activate abacus+deepks
> > > > > 
> > > > > # Install pytorch, the cuda version depends on your machine
> > > > > conda install pytorch cudatoolkit=10.2 -c pytorch # cpu version
> > > > > conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia # gpu version
> > > > > 
> > > > > # use develop branch
> > > > > pip install git+https://github.com/deepmodeling/deepks-kit@develop
> > > > > ```
> > > > 
> > > > 
> > > > Thank you for your reply. But I have been experiencing problems with network connections or failing to connect to the site when creating the environment, and I still have problems with connection errors even after switching to the Tsinghua source. Do you have any suggestions on how to create an environment? The problems are like this: CondaHTTPError: HTTP 000 CONNECTION FAILED for url http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libmagma-2.8.0-hfdb99dd_0.conda Elapsed: - An HTTP error occurred when trying to retrieve this URL. HTTP errors are often intermittent, and a simple retry will get you on your way. CondaHTTPError: HTTP 000 CONNECTION FAILED for url http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libmagma-2.8.0-hfdb99dd_0.conda Elapsed: - An HTTP error occurred when trying to retrieve this URL. HTTP errors are often intermittent, and a simple retry will get you on your way.
> > > 
> > > 
> > > This looks like a problem with your network setup. Maybe you should check things like your network environment and proxy settings.
> > 
> > 
> > After running conda install pytorch cudatoolkit=10.2 -c pytorch # cpu version, I encountered the following problems. Any suggestions for the pytorch install command for CPU version? Channels:
> > 
> > * pytorch
> > * defaults
> >   Platform: linux-64
> >   Collecting package metadata (repodata.json): done
> >   Solving environment: failed
> > 
> > LibMambaUnsatisfiableError: Encountered problems while solving:
> > 
> > * nothing provides cudatoolkit >=11.1,<11.2 needed by pytorch-1.10.0-py3.6_cuda11.1_cudnn8.0.5_0
> > * package abacus-3.8.2-cuda_mpi_mpich_h6026299_1 requires libtorch >=2.5.1,<2.6.0a0, but none of the providers can be installed
> > 
> > Could not solve for environment specs The following packages are incompatible ├─ abacus is installable and it requires │ └─ libtorch >=2.5.1,<2.6.0a0 , which requires │ ├─ nccl >=2.23.4.1,<3.0a0 , which requires │ │ └─ cuda-version >=11.0,<12.0a0 with the potential options │ │ ├─ cuda-version 11.8 would require │ │ │ └─ cudatoolkit 11.8|11.8.* , which can be installed; │ │ ├─ cuda-version 11.0 would require │ │ │ └─ cudatoolkit 11.0|11.0.* , which can be installed; │ │ ├─ cuda-version 11.1 would require │ │ │ └─ cudatoolkit 11.1|11.1.* , which can be installed; │ │ ├─ cuda-version 11.2 would require │ │ │ └─ cudatoolkit 11.2|11.2.* , which can be installed; │ │ ├─ cuda-version 11.3 would require │ │ │ └─ cudatoolkit 11.3|11.3.* , which can be installed; │ │ ├─ cuda-version 11.4 would require │ │ │ └─ cudatoolkit 11.4|11.4.* , which can be installed; │ │ ├─ cuda-version 11.5 would require │ │ │ └─ cudatoolkit 11.5|11.5.* , which can be installed; │ │ ├─ cuda-version 11.6 would require │ │ │ └─ cudatoolkit 11.6|11.6.* , which can be installed; │ │ └─ cuda-version 11.7 would require │ │ └─ cudatoolkit 11.7|11.7.* , which can be installed; │ └─ pytorch 2.5.1 cuda118___303, which can be installed; ├─ cudatoolkit 10.2** is not installable because it conflicts with any installable versions previously reported; └─ pytorch is not installable because there are no viable options ├─ pytorch [0.4.0|0.4.1|...|2.5.1] conflicts with any installable versions previously reported; ├─ pytorch [1.10.0|1.10.1|...|1.9.1] would require │ └─ cudatoolkit >=11.1,<11.2 , which does not exist (perhaps a missing channel); ├─ pytorch 1.11.0 would require │ └─ cudatoolkit >=11.5,<11.6 , which does not exist (perhaps a missing channel); ├─ pytorch [1.12.0|1.12.1] would require │ └─ cudatoolkit >=11.6,<11.7 , which does not exist (perhaps a missing channel); ├─ pytorch [1.13.0|1.13.1] would require │ └─ pytorch-cuda >=11.6,<11.7 , which requires │ └─ cuda 11.6._ , which does not exist (perhaps a missing channel); ├─ pytorch [1.13.0|1.13.1|2.0.0|2.0.1] would require │ └─ pytorch-cuda >=11.7,<11.8 but there are no viable options │ ├─ pytorch-cuda 11.7 would require │ │ └─ cuda-cudart >=11.7,<11.8 , which does not exist (perhaps a missing channel); │ └─ pytorch-cuda 11.7 would require │ └─ cuda 11.7.* , which does not exist (perhaps a missing channel); ├─ pytorch [1.7.1|1.8.0] would require │ └─ python_abi 3.9.* __cp39, which does not exist (perhaps a missing channel); ├─ pytorch [2.0.0|2.0.1|...|2.5.1] would require │ └─ pytorch-cuda >=11.8,<11.9 but there are no viable options │ ├─ pytorch-cuda 11.8 would require │ │ └─ cuda-cudart >=11.8,<12.0 , which does not exist (perhaps a missing channel); │ └─ pytorch-cuda 11.8 would require │ └─ cuda 11.8._ , which does not exist (perhaps a missing channel); ├─ pytorch [2.1.0|2.1.1|...|2.5.1] would require │ └─ pytorch-cuda >=12.1,<12.2 , which requires │ └─ cuda-cudart >=12.1,<12.2 , which does not exist (perhaps a missing channel); ├─ pytorch [0.2.0|0.3.0] would require │ └─ cudatoolkit 7.5* , which does not exist (perhaps a missing channel); ├─ pytorch [0.2.0|0.3.0|0.3.1] would require │ └─ cudatoolkit 8.0* , which does not exist (perhaps a missing channel); ├─ pytorch [0.3.1|0.4.0] would require │ └─ cudatoolkit 8.0.* , which does not exist (perhaps a missing channel); ├─ pytorch 1.0.1 would require │ └─ cudatoolkit >=8.0,<8.1.0a0 , which does not exist (perhaps a missing channel); └─ pytorch [2.0.1|2.3.0] would require └─ __cuda >=11.8 , which is missing on the system.
> 
> Ahh, I’ve made a mistake. For cpu version, try
> 
> ```
> conda install pytorch torchvision torchaudio cpuonly -c pytorch
> ```

Thanks, I installed abacus+deepks following the instructions you provided!
