### ISSUE TITLE
Rewrite test for HSolver

### ISSUE THREAD

**Issue by Cstandardlib** [deepmodeling/abacus-develop#5442]
### Describe the Testing Issue

We need clear unit tests for
- HSolver iterative solvers, with a pure matrix and initial guess we can define and change easily.
- Key operators like `gemm`, to ensure they work properly in different devices and libraries.
- Current tests depend on `Psi` and `Hamilt` class and they are difficult to adjust to debug.

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by Cstandardlib** [comment]
Now that `HSolver_PW` solvers take raw data (T *), while tests still depend on `Hamilt` and `Psi` custom types. They are unreadable and difficult to test and debug. We can update the tests to match the modified code interface.

**Comment by mohanchen** [comment]
Reopen it if new PRs come
