### ISSUE TITLE
A possible method to optimize high energy cutoff test case for LCAO base : bx/by/bz

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#550]
## Describe Current Status and Possible Solution

For H64O32 system, I tried "ecutwfc = 100 Ry" with different setup for "bx=by=bz=1 or 2 or 4".

I have found out the time costed for grid_integral part (vlocal, sum_rho, force_vlocal_dphi) decreased drastically, while the accuracy for total energy and force changed tiny. 

<img width="361" alt="image" src="https://user-images.githubusercontent.com/49852742/145504358-e047bcfb-83cb-4e06-9551-fd2779317810.png">

Is that method acceptable?

What is the best choice for bx/by/bz?

**Comment by mohanchen** [comment]
In most cases, 1 may not be a best choice. Typically, 2 or 4 may be a better choice.

**Comment by dyzheng** [comment]
#580 mentioned a bug for that

**Comment by dyzheng** [comment]
There 4 part of code used grid integral method. "vlocal" and "cal_rho" benefitted from bx/by/bz set, while "force_dphi" and "stress_dphi" didn't.

**Comment by caic99** [comment]
Transfer to #580 .
