### ISSUE TITLE
What's the purpose of Testing directory?

### ISSUE THREAD

**Issue by Cstandardlib** [deepmodeling/abacus-develop#5501]
### Details

We have a `Testing` directory that does not have tests.
```bash
Testing
└── Temporary
    ├── CTestCostData.txt
    └── LastTest.log

➜  Temporary git:(develop) ✗ cat CTestCostData.txt 
---
➜  Temporary git:(develop) ✗ cat LastTest.log 
Start testing: Oct 30 23:32 CST
----------------------------------------------------------
End testing: Oct 30 23:32 CST
```
and a `tests` directory which containsreal tests:
```bash
tests
├── CMakeLists.txt
├── deepks
├── integrate
├── libxc
├── performance
└── PP_ORB
```

Why do we need this `Testing` dir?

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [x] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by mohanchen** [comment]
@caic99 do you know the answer?

**Comment by caic99** [comment]
> [@caic99](https://github.com/caic99) do you know the answer?



> We have a `Testing` directory

@Cstandardlib Where is it? I can't find it in the repo.

**Comment by Cstandardlib** [comment]
@caic99 
Thank you. Seems that it is generated by ctest toolchain.
