### ISSUE TITLE
High symmetry k-point path is printed out without real Brillouin zone distance in band structure calculation (BANDS_1.dat)

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#551]
## Background
High symmetry k-point path is printed out without real Brillouin zone distance in band structure calculation (BANDS_1.dat)

## Describe the solution you'd like
One will require real Brillouin zone distance in band structure calculation to show the feature of Brillouin zone.

## Additional context
To see the problem, find BANDS_1.dat under band/OUT.STO directory in the attached example.
[STO-example.tar.gz](https://github.com/deepmodeling/abacus-develop/files/7690057/STO-example.tar.gz)

**Comment by mohanchen** [comment]
In principle, this is a feature related to users' experiences. Could you propose some ideas to improve this feature? @hongriTianqi

**Comment by hongriTianqi** [comment]
> In principle, this is a feature related to users' experiences. Could you propose some ideas to improve this feature? @hongriTianqi

Adding codes to give the real BZ distance is not difficult.
