### ISSUE TITLE
how to set a specific energy convergence (e.g. 1.e10^-5 eV) in scf calculation of ABACUS?

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#552]
## Background
VASP users are used to set EDIFF to point out the energy convergence criterion in their calculation. However, in ABACUS, when you set ethr in the same way, it will cause computational force waste because the key convergence criterion in ABACUS is dr2, not ethr.
ethr, on the contrary, should be set to a large value to faciliate original scf steps in ABACUS.

## Describe the solution you'd like
User will want the VASP way of setting scf energy convergence, or more guideline on how to get energy convergence to a specific small value (e.g. 1.e-5 eV) in ABACUS.

**Comment by mohanchen** [comment]
Ethr is only used in pw calculations and is the convergence threshold for the "first electronic iteration", not the threshold for the final converged ground-state energy, please see the input document. "Description: Only used when you use diago_type = cg or diago_type = david. It indicates the threshold for the first electronic iteration, from the second iteration the ethr will be updated automatically. For nscf calculations with planewave basis set, ethr should be <= 1d-3." If you consider the explanation is not clear enough, you can improve it!

**Comment by hongriTianqi** [comment]
> 

Of course, this is very clear. However, users are more used to require directly an energy threshold than that of rho.

**Comment by hongriTianqi** [comment]
This issue has not been addressed, so should be kept open.
@Unboundwill @mohanchen @dyzheng

**Comment by mohanchen** [comment]
We will redesign the convergence threshold
