### ISSUE TITLE
elastic constant calculation in ABACUS

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#553]
## Background
Elastic constants are important to analyse the mechanical properties of solids. ABACUS can calculate stress in optimization, can elastic constants and Young's modulus be given for an optimized structure in ABACUS?

## Describe the solution you'd like
Add the function of calculating elastic constants in ABACUS.

**Comment by mohanchen** [comment]
I think this is a great idea, but you should clarify how many detailed steps we need to implement this new feature.
