### ISSUE TITLE
running abacus with problem

### ISSUE THREAD

**Issue by kenan12138** [deepmodeling/abacus-develop#5534]
### Details

please check the screen print file in the [abacus_cal.zip](https://github.com/user-attachments/files/17813119/abacus_cal.zip)

some error happened in the progress. 
env:
Ubuntu 22.04.4 LTS (Jammy Jellyfish)
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)
mpiicc for the Intel(R) MPI Library 2021.11 Build 20231005 for Linux* OS

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [x] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by QuantumMisaka** [comment]
@kenan12138 Thanks for your issue!
Your INPUT includes:
```
pseudo_dir              /mnt/SG15-Version1p0_Pseudopotential/SG15_ONCV_v1.0_upf
```
Please edit it to the directory format
```
pseudo_dir              /mnt/SG15-Version1p0_Pseudopotential
```

Also, the error message for wrong pseudopotential is confusing, in the warning.log:
```
In SCAN_END, can't find: </PP_R> block.
 In SCAN_END, can't find: </PP_RAB> block.
 In SCAN_END, can't find: </PP_MESH> block.
 In SCAN_END, can't find: </PP_LOCAL> block.
 In SCAN_END, can't find: </PP_BETA.1> block.
 In SCAN_END, can't find: </PP_BETA.2> block.
 In SCAN_END, can't find: </PP_BETA.3> block.
 In SCAN_END, can't find: </PP_BETA.4> block.
 In SCAN_END, can't find: </PP_RHOATOM> block.
 In SCAN_END, can't find: </PP_R> block.
 In SCAN_END, can't find: </PP_RAB> block.
 In SCAN_END, can't find: </PP_MESH> block.
 In SCAN_END, can't find: </PP_LOCAL> block.
 In SCAN_END, can't find: </PP_BETA.1> block.
 In SCAN_END, can't find: </PP_BETA.2> block.
 In SCAN_END, can't find: </PP_BETA.3> block.
 In SCAN_END, can't find: </PP_BETA.4> block.
 In SCAN_END, can't find: </PP_BETA.5> block.
 In SCAN_END, can't find: </PP_BETA.6> block.
 In SCAN_END, can't find: </PP_RHOATOM> block.
 In SCAN_END, can't find: </PP_R> block.
 In SCAN_END, can't find: </PP_RAB> block.
 In SCAN_END, can't find: </PP_MESH> block.
 In SCAN_END, can't find: </PP_LOCAL> block.
 In SCAN_END, can't find: </PP_BETA.1> block.
 In SCAN_END, can't find: </PP_BETA.2> block.
 In SCAN_END, can't find: </PP_BETA.3> block.
 In SCAN_END, can't find: </PP_BETA.4> block.
 In SCAN_END, can't find: </PP_RHOATOM> block.
 In SCAN_END, can't find: </PP_R> block.
 In SCAN_END, can't find: </PP_RAB> block.
 In SCAN_END, can't find: </PP_MESH> block.
 In SCAN_END, can't find: </PP_LOCAL> block.
 In SCAN_END, can't find: </PP_BETA.1> block.
 In SCAN_END, can't find: </PP_BETA.2> block.
 In SCAN_END, can't find: </PP_BETA.3> block.
 In SCAN_END, can't find: </PP_BETA.4> block.
 In SCAN_END, can't find: </PP_RHOATOM> block.
 In SCAN_END, can't find: </PP_R> block.
 In SCAN_END, can't find: </PP_RAB> block.
 In SCAN_END, can't find: </PP_MESH> block.
 In SCAN_END, can't find: </PP_LOCAL> block.
 In SCAN_END, can't find: </PP_BETA.1> block.
 In SCAN_END, can't find: </PP_BETA.2> block.
 In SCAN_END, can't find: </PP_BETA.3> block.
 In SCAN_END, can't find: </PP_BETA.4> block.
 In SCAN_END, can't find: </PP_RHOATOM> block.
 In SCAN_END, can't find: </PP_R> block.
 In SCAN_END, can't find: </PP_RAB> block.
 In SCAN_END, can't find: </PP_MESH> block.
 In SCAN_END, can't find: </PP_LOCAL> block.
 In SCAN_END, can't find: </PP_BETA.1> block.
 In SCAN_END, can't find: </PP_BETA.2> block.
 In SCAN_END, can't find: </PP_RHOATOM> block.
 AUTO_SET NBANDS to 82
 AUTO_SET NBANDS to 82
```
All the information indicates that there is something wrong with pseudopotential, but not specific.
@kirk0830 @mohanchen Any comments?

Also, Why you choose `ecutwfc 60` and other INPUT setting for you calculation？ @kenan12138

**Comment by kirk0830** [comment]
seems at least the pseudopotential is not correctly read. I will try tomorrow

**Comment by kirk0830** [comment]
@kenan12138 @QuantumMisaka I can run the case smoothly with provided input. But there seems something wrong with the pseudopotential read-in procedure. The `SCAN_END` is quite an out-dated function, considering replace it with something new.

**Comment by kenan12138** [comment]
https://github.com/deepmodeling/abacus-develop/issues/5534#issuecomment-2485767729
I am a beginner in ABACUS. This INPUT file INPUT_PARAMETERS was set up by my supervisor:

suffix                  dipole_job2
pseudo_dir              /mnt/SG15-Version1p0_Pseudopotential/SG15_ONCV_v1.0_upf
orbital_dir             /mnt/SG15-Version1p0__StandardOrbitals-Version2p0_tdzp
#basis
basis_type              lcao
#accuracy
ecutwfc                 60
scf_nmax                100
scf_thr                 1e-8
#Molecular_dynamics
calculation             scf    #md     #scf
#md_type                 nve
#md_nstep                1
#md_dt                   0.0024
#md_tfirst               0
#tddft
#esolver_type            tddft
#output
out_dipole              1
out_stru                1
out_chg                 1
out_bandgap             1
dft_functional          hse
exx_separate_loop       0
exx_pca_threshold       0.0001
exx_c_threshold         0.0001
exx_dm_threshold        0.0001
exx_ccp_rmesh_times     1.0

My goal is to calculate the HOMO-LUMO gap of a molecule. However, when I calculated the gap using the PBE functional, the result differed significantly from the gaps obtained from Gaussian and ORCA. Therefore, I used this parameter set in the INPUT file to perform the calculation.

When using ABACUS 3.8.2, I encountered the error described above. I will now follow your suggestions and try running the calculation again. Thank you very much for your help!

**Comment by kenan12138** [comment]
> [@kenan12138](https://github.com/kenan12138) [@QuantumMisaka](https://github.com/QuantumMisaka) I can run the case smoothly with provided input. But there seems something wrong with the pseudopotential read-in procedure. The `SCAN_END` is quite an out-dated function, considering replace it with something new.

Thank you for your reply. Could you please explain in more detail how to proceed with "considering replace it with something new"? What specific steps should be taken? I greatly appreciate your guidance.

**Comment by kirk0830** [comment]
> > [@kenan12138](https://github.com/kenan12138) [@QuantumMisaka](https://github.com/QuantumMisaka) I can run the case smoothly with provided input. But there seems something wrong with the pseudopotential read-in procedure. The `SCAN_END` is quite an out-dated function, considering replace it with something new.
> 
> Thank you for your reply. Could you please explain in more detail how to proceed with "considering replace it with something new"? What specific steps should be taken? I greatly appreciate your guidance.

@kenan12138 Hi, that is for ABACUS developers. I guess those warning may be printed merely by mistake, so there is something should be updated in ABACUS, but if you have some physical reference data, you can make comparison and check if your calculation with pseudopotential is reliable.

**Comment by kenan12138** [comment]
[abacus_cal2478.zip](https://github.com/user-attachments/files/17826043/abacus_cal2478.zip)
[abacus_cal2478_siingle_C.zip](https://github.com/user-attachments/files/17826042/abacus_cal2478_siingle_C.zip)
Hello, I used ABACUS 3.6.3 for my calculations and found that when calculating a single atom, the calculation can run to completion, although it does not converge. However, when calculating a complete molecule, it runs for a few steps (performing better than version 3.8.2) but still terminates. Could this be a memory issue?

**Comment by QuantumMisaka** [comment]
@kenan12138 For single atom calculation, you need some specific INPUT setting ,refer to #5009

**Comment by sunliang98** [comment]
> > > [@kenan12138](https://github.com/kenan12138) [@QuantumMisaka](https://github.com/QuantumMisaka) I can run the case smoothly with provided input. But there seems something wrong with the pseudopotential read-in procedure. The `SCAN_END` is quite an out-dated function, considering replace it with something new.
> > 
> > 
> > Thank you for your reply. Could you please explain in more detail how to proceed with "considering replace it with something new"? What specific steps should be taken? I greatly appreciate your guidance.
> 
> [@kenan12138](https://github.com/kenan12138) Hi, that is for ABACUS developers. I guess those warning may be printed merely by mistake, so there is something should be updated in ABACUS, but if you have some physical reference data, you can make comparison and check if your calculation with pseudopotential is reliable.

These warnings were triggered in error and do not affect the result. I will fix them.

**Comment by kenan12138** [comment]
> > > > [@kenan12138](https://github.com/kenan12138) [@QuantumMisaka](https://github.com/QuantumMisaka) I can run the case smoothly with provided input. But there seems something wrong with the pseudopotential read-in procedure. The `SCAN_END` is quite an out-dated function, considering replace it with something new.
> > > 
> > > 
> > > Thank you for your reply. Could you please explain in more detail how to proceed with "considering replace it with something new"? What specific steps should be taken? I greatly appreciate your guidance.
> > 
> > 
> > [@kenan12138](https://github.com/kenan12138) Hi, that is for ABACUS developers. I guess those warning may be printed merely by mistake, so there is something should be updated in ABACUS, but if you have some physical reference data, you can make comparison and check if your calculation with pseudopotential is reliable.
> 
> These warnings were triggered in error and do not affect the result. I will fix them.

The issue has been resolved. Previously, I used the command export OMP_NUM_THREADS=2 followed by mpirun -n 4 abacus, which caused an error. Now, I've used export OMP_NUM_THREADS=8 and mpirun -n 1 abacus, and it runs without any issues. Thanks everyone for your replies.
