### ISSUE TITLE
ABACUS tool support CPU with ARM64  and NPU with Huawei 910B?

### ISSUE THREAD

**Issue by somunslotus1** [deepmodeling/abacus-develop#5537]
### Details

I want to use abacus tool on cpu with arm64  and npu with Huawei 910B, Abacus tool suport cpu with arm64  and npu with Huawei 910B?

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [x] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by caic99** [comment]
Hi @somunslotus1 ,
You can build ABACUS on ARM CPUs. ABACUS from the conda-forge channel also provides aarch64 packages for instant use. 
However, the programming interface for Huawei NPU is not aligned with the CUDA(-like) style used in ABACUS, so it is not supported now.

**Comment by QuantumMisaka** [comment]
@somunslotus1 Hi
ABACUS Toolchain support aarch64 machine, but Huawei NPU is not supported now.
Your server environment seems to be very complicated orz
