### ISSUE TITLE
unregular behaviour while using different CPUs combination

### ISSUE THREAD

**Issue by JTaozhang** [deepmodeling/abacus-develop#5548]
### Describe the bug

Hi there,

Currently, I am working on a WTe2 bilayer systems, which contains about 504 atoms. I try to calculate the band structure with kpoint mesh of 11 along the high symmetric path. The software version is v3.8.2. With the same INPUT setting and KPT settings, but adopting different cpus combinations, one works and another runs abnormal. Specifically it reports nothing, no error and no useful information. one is mpirun -np 8 -env OMP_NUM_THREADS=28 and total cpus is 224(8 nodes, 56 cpus per node), another is mpirun -np 20 -env OMP_NUM_THREADS=28 and total cpus is 560 (10 nodes, 56 cpus per node).

for the abnormal job, the whole outoput information shows below,
```                                                                                     
                              ABACUS v3.8.2

               Atomic-orbital Based Ab-initio Computation at UStc                    

                     Website: http://abacus.ustc.edu.cn/                             
               Documentation: https://abacus.deepmodeling.com/                       
                  Repository: https://github.com/abacusmodeling/abacus-develop       
                              https://github.com/deepmodeling/abacus-develop         
                      Commit: unknown

    Start Time is Wed Nov 20 18:43:57 2024
                                                                                     
 ------------------------------------------------------------------------------------

 READING GENERAL INFORMATION

                           global_out_dir = OUT.WTe2/
                           global_in_card = INPUT
                               pseudo_dir = /share/home/zhangtao/work/WTe2/abacus/pseudo/
                              orbital_dir = /share/home/zhangtao/work/WTe2/abacus/orbital/

```

I don't know what causes this abnormal behavior, could you test the code? I think the parallel calculation part may still possess some unstable problem. this problem I also dicussed in the wechat online group, somebody suggest me to propose an issue here. So I do this.

related file is here
[WTe2.zip](https://github.com/user-attachments/files/17838889/WTe2.zip)

### Expected behavior

the second submitting setting should work fast than the first setting.

### To Reproduce

1. calculate the charge density files according to the INPUT_scf, and KPT_scf;
2. after getting the charge density files, do the band calculation according to INPUT and KPT.
3. compare the results and check the code.

### Environment

module load cmake/cmake-3.25  gnu/12.1.0

source /share/apps/intel2022/setvars.sh
source /share/home/zhangtao/software/abacus-develop-3.8.3/toolchain/install/setup

### Additional Context

no more information is needed

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by QuantumMisaka** [comment]
Hi @JTaozhang 
From my experience, this problem is from your job submitting scripts and the server setting. but the provided files do not contain any of information about them, please provide them in detail.
I've done parallel computation with HSE functional by using `OMP_NUM_THREADS=16 mpirun -np 32 abacus` and it works well

**Comment by JTaozhang** [comment]
Hi,
thanks for your reply. I have attached the submitting scripts here, for the combination of "mpirun -np 8 -env OMP_NUM_THREADS=28 and total cpus is 224(8 nodes, 56 cpus per node)", it works. However, for the  "mpirun -np 20 -env OMP_NUM_THREADS=28 and total cpus is 560 (10 nodes, 56 cpus per node)", it fails.

I think ,different machine has different setting, I am not sure you can reproduce my case with your machine. Maybe you can change your combination using my atomic system to check this problem.

one more question, less tasks in a node means that the memory of the node will be less shared by other task, right? The mp_num_thread decides how the cpus are distributed to one task, which governs the parallel computing.

[20-28.zip](https://github.com/user-attachments/files/17866407/20-28.zip)

Best,
Tao

**Comment by YuLiu98** [comment]
Could you supply your STRU and charge density files for nscf?

**Comment by JTaozhang** [comment]
ok. I attached the file here.

Best.

**Comment by YuLiu98** [comment]
> ok. I attached the file here.
> 
> Best.

Thank you, but it seems that you failed to upload the files.

**Comment by JTaozhang** [comment]
I think the uploading failed, due to the large size, I will share it by  baidu cloud. 

链接：https://pan.baidu.com/s/1lphoofZi1MhJh49etZ2weQ 
提取码：1230

Best

**Comment by YuLiu98** [comment]
> I think the uploading failed, due to the large size, I will share it by baidu cloud.
> 
> 链接：https://pan.baidu.com/s/1lphoofZi1MhJh49etZ2weQ 提取码：1230
> 
> Best

The download speed is too low in baidu cloud. Maybe you can temporarily create a GitHub repository and put these files in it

**Comment by mohanchen** [comment]
Low efficient communications...

**Comment by mohanchen** [comment]
Low efficient communications...

**Comment by YuLiu98** [comment]
https://github.com/[JTaozhang/abacus-example](https://github.com/JTaozhang/abacus-example)

This repository is empty.

**Comment by JTaozhang** [comment]
Hi there,

Could you try to open this link  https://github.com/JTaozhang/abacus-example again ? I have uploaded the charge density and structure files here. Apologize to the late uploading. 

As for the unrgular behavior, I have some thoughts. I think, in some cpu combinations, there should be some problem to initialize the charge density when starting to calculate. 

Best,
Tao

**Comment by YuLiu98** [comment]
> Hi there,
> 
> Could you try to open this link https://github.com/JTaozhang/abacus-example again ? I have uploaded the charge density and structure files here. Apologize to the late uploading.
> 
> As for the unrgular behavior, I have some thoughts. I think, in some cpu combinations, there should be some problem to initialize the charge density when starting to calculate.
> 
> Best, Tao

Thank you for your reply, but could you also attach pseudopotentials and orbitals here?

**Comment by JTaozhang** [comment]
Hi @YuLiu98 ,

Here is the pseudopotential and orbital files. if you need more information and files, please let me know.

[potential_orbital.zip](https://github.com/user-attachments/files/18222477/potential_orbital.zip)
Best,
Tao

**Comment by YuLiu98** [comment]
Hi @JTaozhang ,

It seems that you forgot to set the input parameter `read_file_dir` as `./` to specify the location of the charge density files.

And I have completed this calculation: [liuyu_test.tar.gz](https://github.com/user-attachments/files/18226112/liuyu_test.tar.gz)

**Comment by JTaozhang** [comment]
Hi Liu,

Thanks for your test. it looks working well on your cluster. As the input parameter, it doesn't matter, if I create the OUT.ABCUS folder and take charge files into it in advance, it still works. So I have no idea why this happens to me. For my cluster, the memory is 192GB , and 2 Intel Xeon Gold 6330 CPU (2*28) cores per node. Is there any rules for the program reading files or distributing calculation to each task during the initialization? 
I guess maybe there are some  parallel-computing shortcomings for my cluster.  In the future, I plan to change a cluster to do this calculation, If I accounter this problem again, we can talk again. Then, I think we can close this issue now for saving resource and time.  

thanks again for the testing!!

Best,
Tao

**Comment by YuLiu98** [comment]
OK, I will close this issue. If you have any questions in the future, we can reopen it.
