### ISSUE TITLE
The unit of density of states (DOS) and PDOS in ABACUS

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#555]
## Background
One cannot find the unit of density of states (DOS) and PDOS in ABACUS at anywhere in the online documents or mannual.

## Describe the solution you'd like
Give a clear indication of the unit of DOS and PDOS

**Comment by mohanchen** [comment]
I think this is a very good suggestion, we should definitely do it!

**Comment by hongriTianqi** [comment]
This issue has not been solved, so should be kept open. @Unboundwill
