### ISSUE TITLE
How to output momentum/velocity matrix in ABACUS

### ISSUE THREAD

**Issue by DzzZ1** [deepmodeling/abacus-develop#5553]
### Background

I noticed that abacus has implemented the rt-TDDFT function in Velocity-gauge and can output current. My current requirement is to output the momentum p matrix of the system ground state under the LCAO basis set and energy eigenvalue basis set, which is very important to me. But when I was reading the manual, I did not find a label for outputting the p matrix. The p matrix I refer to here is similar to the label out_mat_r in the manual for extracting the position r matrix, but the difference from r is that the r operator now needs to be replaced by the matrix of the p operator (https://abacus.deepmodeling.com/en/latest/advanced/elec_properties/position_matrix.html#extracting-position-matrices). At the same time, I also read the second reference under the rt-TDDFT tutorial (title: Velocity-gauge real-time TDDFT within a numerical atomic orbital basis set). From formulas 7, 8 and 9 in the literature, it can be seen that calculating momentum is a prerequisite for obtaining current. I guess abacus should have calculated this item, but there is no output label.

### Describe the solution you'd like

It is recommended to add labels for output momentum matrix p under the energy eigenvalue basis set.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by ESROAMER** [comment]
Your requirements can be achieved using functions in the `pyatb`. The function `get_velocity_matrix(kpt)` can obtain the velocity matrix in k-space under energy eigenstates, while the function `get_velocity_basis_k(kpt)` provides the velocity matrix in k-space under the atomic orbital basis. You can reach out to the developers of `pyatb` to learn how to use these functions correctly. Hope this helps!

**Comment by DzzZ1** [comment]
Thanks for your reply, I will do it.
