### ISSUE TITLE
PDOS calculation with plane wave basis in ABACUS is not supported yet.

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#556]
## Background
PDOS calculation with plane wave basis in ABACUS is not supported yet.

## Describe the solution you'd like
Add PDOS calculation with plane wave basis calculation.

**Comment by mohanchen** [comment]
In order to compute the PDOS using the plane-wave basis, we need to project the ground-state wave functions onto atomic orbitals. For example, the pseudo atomic orbitals read from pseudopotential files. We should definitely have it ASAP!

**Comment by hongriTianqi** [comment]
This issue has not been addressed, so should be kept open. @Unboundwill

**Comment by mohanchen** [comment]
Will implement it later.
