### ISSUE TITLE
format issues in online manual

### ISSUE THREAD

**Issue by BariumOxide13716** [deepmodeling/abacus-develop#5575]
### Details

I spotted a few format issues in the online manual, for example:

for out_hr_npz/out_dm_npz, there are two trademarks in the description,
for dm_to_rho, there is one trademark after "DM",
and for dft_functional, the description "for example, ‘dft_functional=‘LDA_X_1D_EXPONENTIAL+LDA_C_1D_CSC’." contains some unexpected primes.

Besides, the link to the website of the LIBXC keywords redirects me to an unrelated website. Maybe we can use https://libxc.gitlab.io/functionals/ to replace the link.

### Have you read the online manual http://abacus.deepmodeling.com/en/latest/

- [x] Yes, I have read the online manual.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific section of the documentation with the issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Update the documentation to address the issue, following the suggested improvement.
- [ ] Ensure the updated documentation adheres to the project's documentation standards.
- [ ] Test the updated documentation to ensure it is clear and accurate.
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Publish the updated documentation and notify the issue reporter.

**Comment by mohanchen** [comment]
Thanks for your suggestions, we will try to fix the issues.
