### ISSUE TITLE
SOC energy band is incorrect

### ISSUE THREAD

**Issue by woyolo990422** [deepmodeling/abacus-develop#5585]
### Describe the bug

INPUT1：

INPUT_PARAMETERS
#Parameters	(General)
pseudo_dir              /tests/PP_ORB
orbital_dir            /tests/PP_ORB
nbands			60
#Parameters (Accuracy)
ecutwfc			80
scf_nmax			50
basis_type		lcao
out_chg			1
kspacing 0.15
dft_functional          pbe
symmetry                0
smearing_method         gaussian
smearing_sigma          0.02
mixing_type             broyden
mixing_beta             0.1
exx_hybrid_step 1
lspinorb                True
nspin            4

INPUT2：

INPUT_PARAMETERS
#Parameters (General)
kpoint_file             KLINES
pseudo_dir		/fs09/home/js_wangyl/soft/abacus-develop-3.6.2/tests/PP_ORB
orbital_dir		/fs09/home/js_wangyl/soft/abacus-develop-3.6.2/tests/PP_ORB
calculation             nscf
nbands                  60
#symmetry                0
#Parameters (Methos)
basis_type              lcao

#Parameters (Accuracy)
ecutwfc                 80
#Parameters (File)
init_chg                file
out_band                1
dft_functional          pbe
lspinorb                True
nspin            4

KLINES:

K_POINTS
8
Line
0.0000000000   0.0000000000   0.0000000000 10	//GAMMA 
0.5000000000   0.0000000000   0.5000000000 10	//X
0.6250000000   0.2500000000   0.6250000000 10 	//U      
0.3750000000   0.3750000000   0.7500000000 10 	//K 
0.0000000000   0.0000000000   0.0000000000 10	//GAMMA
0.5000000000   0.5000000000   0.5000000000 10	//L
0.5000000000   0.2500000000   0.7500000000 10	//W
0.5000000000   0.0000000000   0.5000000000 1	//X

STRU:

ATOMIC_SPECIES
Pb 207.2 Pb_ONCV_PBE_FR-1.0.upf upf201

NUMERICAL_ORBITAL
Pb_gga_10au_100Ry_2s2p2d.orb

LATTICE_CONSTANT
1.8897259886

LATTICE_VECTORS
        4.9895095825         0.0000000000         0.0000000000
        0.0000000000         4.9895095825         0.0000000000
        0.0000000000         0.0000000000         4.9895095825
ATOMIC_POSITIONS
Direct
Pb #label
0 #magnetism
4 #number of atoms
	 0.000000000         0.000000000         0.000000000  0  0  0
     0.000000000         0.500000000         0.500000000  0  0  0
     0.500000000         0.000000000         0.500000000  0  0  0
     0.500000000         0.500000000         0.000000000  0  0  0

subjob:

#BSUB -q 5220r
#BSUB -n 48
#BSUB -J R
export OMP_NUM_THREADS=1

cp INPUT1 INPUT
mpirun -np 48 abacus | tee scf.output
cp INPUT2 INPUT
mpirun -np 48 abacus | tee nscf.output

I have chosen here
lspinorb                True
nspin            4
But the result was an increase in energy bands without any SOC effect causing splitting

ABACUS v3.5.1 with conda install

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by dyzheng** [comment]
I retested this case by ABACUS 3.8.3, the band structure has only little split with SOC , where degenerate energy bands without SOC.
There are several suggestions:
1. don't set `nbands`  in INPUT, the value 60 is not enough for this case.
2. try DOJO pseudopotential and related orbitals in https://github.com/abacusmodeling/ABACUS-orbitals/tree/main/Dojo-NC-FR 
3. try ABACUS newest version 3.8.3.
4. try typical case GaAs or Au to check the distinguishable.
5. try `basis_type    pw` .

**Comment by mohanchen** [comment]
If no further discussion, I will close this issue. New discussions are always welcome.
