### ISSUE TITLE
The HSE calculation in v3.8.3 is 64% slower than in v3.8.0

### ISSUE THREAD

**Issue by Chentao168** [deepmodeling/abacus-develop#5587]
### Describe the bug

Within the same system (In4Ga8Zn8O26), using ABACUS v3.8.0 and v3.8.3 for testing with identical parameters, v3.8.3 is 64% (13834 s / 8415 s = 1.64) slower than v3.8.0.

### To Reproduce

[20241124-bug.zip](https://github.com/user-attachments/files/17892462/20241124-bug.zip)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by PeizeLin** [comment]
In your calculation, the INPUT parameter `exx_ccp_rmesh_times` in v3.8.0 is 1, while in v3.8.3 is 1.5.

**Comment by Chentao168** [comment]
It is indeed the impact caused by exx_cp_rmesh_time, and I noticed that the relevant information in the document seems to have not been modified? In the code, hf / pbe0 / scan0 is 5, hse is 1.5, and others are 1.
![Image](https://github.com/user-attachments/assets/37a61bd3-0ca5-461c-9043-71748166291f)
![Image](https://github.com/user-attachments/assets/6ec3a07b-0d36-441a-8790-80483e3f88d6)

**Comment by PeizeLin** [comment]
There seems to be a bug at v3.8.0.
