### ISSUE TITLE
Analysis of DOS calculation output files

### ISSUE THREAD

**Issue by yycx1111** [deepmodeling/abacus-develop#5589]
### Details

There are no TDOS and PDOS files in the output file of the density of states calculation when using abacus3.8.2 and abacus3.8.3. How to get the projected state density information now?

### Have you read the online manual http://abacus.deepmodeling.com/en/latest/

- [x] Yes, I have read the online manual.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific section of the documentation with the issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Update the documentation to address the issue, following the suggested improvement.
- [ ] Ensure the updated documentation adheres to the project's documentation standards.
- [ ] Test the updated documentation to ensure it is clear and accurate.
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Publish the updated documentation and notify the issue reporter.

**Comment by Chentao168** [comment]
Please ref to https://mcresearch.github.io/abacus-user-guide/abacus-pdos.html
