### ISSUE TITLE
The UT of the output and read of hcontainer is break.

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#5606]
### Describe the Testing Issue

The UT of the output and read of hcontainer is not work.

https://github.com/deepmodeling/abacus-develop/actions/runs/12007743357/job/33468965679

![Image](https://github.com/user-attachments/assets/6b8627c6-6bef-49be-ae11-170fc6ecec9b)

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by mohanchen** [comment]
Could you provide some advices? @dyzheng
