### ISSUE TITLE
Why is ABACUS automatically set symmetry to 0 in MD calculation?

### ISSUE THREAD

**Issue by ESROAMER** [deepmodeling/abacus-develop#5607]
### Details

Why is ABACUS automatically set symmetry to 0 in MD calculation? What if I need `symmetry -1`? 

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [x] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by ESROAMER** [comment]
In fact, for the velocity operator, the values at +k and -k are not identical. Therefore, if we need to calculate the time-dependent current in RT-TDDFT for a periodic system, the symmetry parameter must be set to -1. The constant current observed in our calculations with multiple k-points arises because it is not possible to use `symmetry -1`.

**Comment by dyzheng** [comment]
https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_io/read_input_item_system.cpp#L155 @ESROAMER you can modify this  by yourself.
