### ISSUE TITLE
Using my own code for calculating dipole

### ISSUE THREAD

**Issue by kenan12138** [deepmodeling/abacus-develop#5612]
### Details

Hello, I used my own code and the SPIN1_CHG.cube file generated by ABACUS to calculate the dipole moment of the corresponding molecule, but the result is not entirely consistent with the one calculated by ABACUS. The values of dipole_ion_x, dipole_ion_y, and dipole_ion_z are very consistent, but there are significant discrepancies in dipole_elec_x, dipole_elec_y, and dipole_elec_z. Could you please take a look at my code and identify where the problem might be and how to correct it? I would greatly appreciate your help! Sorry I can't upload my SPIN1_CHG.cube file, it is too big.[cal_dipole.zip](https://github.com/user-attachments/files/17916683/cal_dipole.zip)
 

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [x] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by kenan12138** [comment]
Can someone please help me with my problem?I would be very grateful！

**Comment by WHUweiqingzhou** [comment]
@ESROAMER, could you provide any suggestion?

**Comment by ESROAMER** [comment]
Have you tried improving the precision of the output cube?

**Comment by kenan12138** [comment]
> Have you tried improving the precision of the output cube?
Yes i tried.You can take a look at this PPT[dipole_comparison.pptx](https://github.com/user-attachments/files/17953437/dipole_comparison.pptx)

**Comment by ESROAMER** [comment]
If it's not the accuracy of the charge density, then it's the precision of the integration grid causing the issue. Here is your cube file
![Image](https://github.com/user-attachments/assets/f49036b3-3388-45aa-bb35-04fab4f1dfaa)
Using your STRU, I calculated a more precise grid spacing. Here, replace your spacing with these values, and you'll get what you're looking for.
```
288 0.19578348745833335 0.000000 0.000000
300 0.000000 0.19825745374666667 0.000000
240 0.000000 0.000000 0.1915394778166667
```

**Comment by kenan12138** [comment]
> If it's not the accuracy of the charge density, then it's the precision of the integration grid causing the issue. Here is your cube file ![Image](https://github.com/user-attachments/assets/f49036b3-3388-45aa-bb35-04fab4f1dfaa) Using your STRU, I calculated a more precise grid spacing. Here, replace your spacing with these values, and you'll get what you're looking for.
> 
> ```
> 288 0.19578348745833335 0.000000 0.000000
> 300 0.000000 0.19825745374666667 0.000000
> 240 0.000000 0.000000 0.1915394778166667
> ```
Thank you very much for your insightful response. I used the values you provided and recalculated, and indeed the result is much closer to the output from abacus. Could you please let me know where I can set the parameters to achieve a more precise grid spacing?I greatly appreciate your help.

**Comment by ESROAMER** [comment]
ABACUS currently does not support adjusting the output precision for this part. You can modify the code at this location (https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_io/write_cube.cpp#L171) and recompile the program to obtain the precision you need.

**Comment by kenan12138** [comment]
> ABACUS currently does not support adjusting the output precision for this part. You can modify the code at this location (https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_io/write_cube.cpp#L171) and recompile the program to obtain the precision you need.

I now know how to solve the issue. Thank you once again for your help, I really appreciate it!
