### ISSUE TITLE
request the function of output dipol matrix while using get_S command

### ISSUE THREAD

**Issue by JTaozhang** [deepmodeling/abacus-develop#5616]
### Background

as we know, get_S can produce overlaps matrix only, and it is not time-consuming. the same process also works for dipole matrix, if we can produce the dipole matrix in the same time, which will be helpful to interact with deeph, especially will be helpful to connect withpyatb as well.

Best

### Describe the solution you'd like

setting calculation to get_S, it can produce the overlap and dipole matrix in the same time.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by dyzheng** [comment]
Setting `out_mat_r` can output this transition dipole matrix $$<\phi_{\mu}|r|\phi_{\nu}>$$ with `calculation get_S` after #5611 .
Refer to https://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#out-mat-r
