### ISSUE TITLE
Should nscf support cal_stress or cal_force?

### ISSUE THREAD

**Issue by Qianruipku** [deepmodeling/abacus-develop#5619]
### Describe the bug

Now ABACUS do not calculate stress or force in nscf.
![Image](https://github.com/user-attachments/assets/22ba1b77-110e-48b3-90c2-470e2775e603)

But anyway, there is a bug now. When using nscf, and json will try outputting stress, although no stress are calculated.
It will cause segmental fault.
![Image](https://github.com/user-attachments/assets/a10c82a6-8ecb-47c8-9df3-7012f76d977f)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by mohanchen** [comment]
@pxlxingliang could you provide some advices?

**Comment by pxlxingliang** [comment]
If no user need force/stress in nscf, it seems this function is unnecessary.

The bug @Qianruipku mentioned is actually the mismatch of ABACUS INPUT and ABACUS actions, that is user set `cal_force` or `cal_stress` to True, but ABACUS do not do the calculation. 

I suggest that in the INPUT reading function, when the `calculation` is set to `nscf` and `cal_force` or `cal_stress` is set to True at the same time, ABACUS throw a warning (to tell user  that ABACUS do not support the calculation of force and stress in nscf), and modify cal_force and cal_stress to False.

In function `add_output_cell_coo_stress_force()`, only when cal_force or cal_stress is set to True, it will try to output the value, which I think is reasonable and not a bug.
