### ISSUE TITLE
The efficiency of DCU CG decreased significantly

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#5620]
### Describe the Testing Issue

The performance score of DCU CG at 20241127 with commit v3.8.3(664f996 (Tue Nov 26 22:16:00 2024 +0800)) is much lower than previous test at 20241101 with commit v3.8.1(3984296 (Thu Oct 31 14:49:09 2024 +0800)). Tests between these two commits are failed because of the compile problem.

![Image](https://github.com/user-attachments/assets/eaa808ec-a482-4e2d-8908-e3af0c25fdcd)

Link of test at 20241101: https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fsched-abacustest-dcu-cg-ba967b

Link of test at 20241127: https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fsched-abacustest-dcu-cg-1cc5b6

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by pxlxingliang** [comment]
I have checked the log, and the calculation of force and stress contribute lots of time. 

![Image](https://github.com/user-attachments/assets/2ca0830a-e213-4f9e-b654-87d4c51b623d)

**Comment by dyzheng** [comment]
The function `FS_Kin_tools<FPTYPE, Device>::cal_stress_kin` caused a serious performance mismatch between the running time of the modified function on GPU and DCU.
4 * DCU:
![Image](https://github.com/user-attachments/assets/51cbf133-9186-4540-992c-34055f66a7bc)
1* GPU:
![Image](https://github.com/user-attachments/assets/770a1e89-03b0-43ed-9ab1-472202bfb412)

This function was included since #5487 . @Qianruipku Hello, do you have any suggestion for this difference?

**Comment by mohanchen** [comment]
We can discuss through this issue. @Qianruipku @A-006

**Comment by Qianruipku** [comment]
It is strange. I'll look at stress_kin.
