### ISSUE TITLE
doing SCF error with setting ks_solver to "dav"  

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#563]
In the attached case, the job is error during doing SCF by dav method.
[davError.zip](https://github.com/deepmodeling/abacus-develop/files/7702902/davError.zip)

![image](https://user-images.githubusercontent.com/91927439/145792920-df129bcd-bc30-4c8d-9c52-9807ad1e66bb.png)

I have run this system by cg method, and it is normal finished.

**Comment by Qianruipku** [comment]
I ran this case with 1/2/4 processors and did not see the error. Would you provide more details?
Mistake "psi_norm > 0" occurs when the program cannot get a new eigen wavefunction that is orthogonal to other wavefunctions.
Possible reason: nband is big while wfcecut is small

**Comment by pxlxingliang** [comment]
The NBANDS is 58 and wfcecut is 60 Ry. 
I re-run this case by lasted abacus, it can be normal finished, I don't know what changed between the version at 13 Dec 2021 and now, but the result is good.

**Comment by mohanchen** [comment]
Sounds no problems right now.
