### ISSUE TITLE
Cannot find optimized structure file after cell relax calculation

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#564]
## Background
Although the out_stru has been set to 1, no optimized structure (like STRU_NOW.cif) has been found in output directory OUT.MgO

Please see attached example.
[trigonal_MgO.tar.gz](https://github.com/deepmodeling/abacus-develop/files/7708138/trigonal_MgO.tar.gz)

## Describe the solution you'd like
Give more instructions on how to output optimized structure file.

**Comment by hongriTianqi** [comment]
The current example sets atom not to move in STRU file (wrongly). But we think an opt file should be output as well.

**Comment by mohanchen** [comment]
When you prepare the refactor plan for the input/output files, please make sure to have a section describing the current input/output format problems we met in the ’Github issues' section. @hongriTianqi @dyzheng @pxlxingliang

**Comment by hongriTianqi** [comment]
This issues is caused by a mistake (see above comments). So will be closed.
