### ISSUE TITLE
The scf step number of density-matrix pulay mixing is much larger than before

### ISSUE THREAD

**Issue by PeizeLin** [deepmodeling/abacus-develop#5640]
### Describe the bug

The scf step number of density-matrix pulay mixing significantly increased after the commit [2024.02.05-a25fd3](https://github.com/deepmodeling/abacus-develop/commit/a25fd34e6c2d81a80d2545cfef9d5c343fad62b8) .

[DM_mixing_bug.zip](https://github.com/user-attachments/files/17944785/DM_mixing_bug.zip)

Thanks @1041176461 @maki49

### Environment

- CentOS Linux release 7.9.2009 (Core)
- icpc version 2021.5.0 (gcc version 10.2.0 compatibility)
- mpiicpc for the Intel(R) MPI Library 2021.5 for Linux*

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
I am working on it.
