### ISSUE TITLE
What's the underlying data behind psi type？

### ISSUE THREAD

**Issue by Cstandardlib** [deepmodeling/abacus-develop#5647]
### Details

What's the relationship between `ngk_pointer`, `get_current_nbas`, `get_nbasis`?
They are confusing and can vary a lot.

Results of dimension output:
```cpp
const int dim = psi.get_current_nbas();
const int nband = psi.get_nbands();
const int ld_psi = psi.get_nbasis();
```
![Image](https://github.com/user-attachments/assets/fea09461-d881-4397-add8-4964290aa80c)

run abacus in `examples/pw_Al` with 
```bash
 SPIN    KPOINTS         PROCESSORS  THREADS     
 1       8               1           56     
```
![Image](https://github.com/user-attachments/assets/11278fbc-f207-4864-9e26-1b90a8648e6e)

run the same example with `OMP_NUM_THREADS=1 mpirun -np 2 abacus`
```bash
 SPIN    KPOINTS         PROCESSORS  THREADS     
 1       8               2           2           
```

I would be grateful if someone could provide relevant information or documents. ❤ 

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [x] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by haozhihan** [comment]
Under the plane wave basis set, the `nbasis` corresponding to different k points may be different.

* `get_nbasis` returns the largest `nbasis` among all `k` points of the current psi.
* `get_current_nbas` refers to the `nbasis` at the current `k` point in psi (the current pointer in psi can be adjusted to the specified k point).
* `ngk_pointer` stores the specific value of `nbasis` for each k point in psi.

**Comment by haozhihan** [comment]
I have written a specific psi document, and we can discuss it together during the group meeting tomorrow. @Cstandardlib
