### ISSUE TITLE
Same func in two class

### ISSUE THREAD

**Issue by A-006** [deepmodeling/abacus-develop#5667]
### Describe the Code Quality Issue

![Image](https://github.com/user-attachments/assets/5a5c9ccd-32f8-4387-9495-769d12348932)
there are two function have same code and parameter,Should they be set to the same external function with parameter ORB and ucell?

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by jingan-181** [comment]
You can make this change. The ultimate goal of the code in these two places is to use the atomic orbital basis set from the system to create the Center2_Orb::Orb11 and Orb21 objects, and then perform the two-center integral calculation. If your modifications ensure the correct operation of Center2_Orb, such changes are acceptable.
