### ISSUE TITLE
Doc says relax_nmax's default is 1 for SCF, 50 for relax and cell-relax calcualtions, but not

### ISSUE THREAD

**Issue by saltball** [deepmodeling/abacus-develop#5675]
### Details

Doc https://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#relax-nmax says `Default: 1 for SCF, 50 for relax and cell-relax calcualtions`.
I'm not sure whether it is a doc problem or a bug.

but when running relax without explicitly define `relax_nmax` in `INPUT`, the calculation still run with `relax_nmax 1` in OUT.xxx/INPUT

byw there is a typo `calcualtions`

### Have you read the online manual http://abacus.deepmodeling.com/en/latest/

- [x] Yes, I have read the online manual.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific section of the documentation with the issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Update the documentation to address the issue, following the suggested improvement.
- [ ] Ensure the updated documentation adheres to the project's documentation standards.
- [ ] Test the updated documentation to ensure it is clear and accurate.
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Publish the updated documentation and notify the issue reporter.

**Comment by WHUweiqingzhou** [comment]
@saltball  
this issue has been solved by #5506, please use the latest code.
