### ISSUE TITLE
Mac Metel Support

### ISSUE THREAD

**Issue by OutisLi** [deepmodeling/abacus-develop#5678]
### Background

Will this project support Mac gpu? Or can someone give me some hints about how to realize this?

### Describe the solution you'd like

enable gpu acceleration for Mac with apple silicon

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by dzzz2001** [comment]
abacus's GPU programs are currently written for ROCm and CUDA, and there is no implementation targeting Metal yet.![Image](https://github.com/user-attachments/assets/82535c64-c753-4d66-864d-10f2fa790317)

**Comment by Flying-dragon-boxing** [comment]
I think few developers here really knows about Metal API, so feel free to contribute if you want!
(BTW, the name of the API is Metal rather than "Metel")

**Comment by mohanchen** [comment]
If needed, please feel free to raise a new issue.
