### ISSUE TITLE
compile for Mac

### ISSUE THREAD

**Issue by OutisLi** [deepmodeling/abacus-develop#5680]
### Describe the bug

尝试使用mac编译的时候报错如下：
Undefined symbols for architecture arm64:
  "ModulePW::FFT_BASE<double>::initfft(int, int, int)", referenced from:
      vtable for ModulePW::FFT_BASE<double> in sltk_atom_arrange_test.cpp.o
  "ModulePW::FFT_BASE<double>::initfft(int, int, int, int, int, int, int, int, bool, bool)", referenced from:
      vtable for ModulePW::FFT_BASE<double> in sltk_atom_arrange_test.cpp.o
  "ModulePW::FFT_BASE<float>::initfft(int, int, int)", referenced from:
      vtable for ModulePW::FFT_BASE<float> in sltk_atom_arrange_test.cpp.o
  "ModulePW::FFT_BASE<float>::initfft(int, int, int, int, int, int, int, int, bool, bool)", referenced from:
      vtable for ModulePW::FFT_BASE<float> in sltk_atom_arrange_test.cpp.o
  "ModulePW::FFT_BASE<double>::fft3D_forward(std::__1::complex<double>*, std::__1::complex<double>*) const", referenced from:
      vtable for ModulePW::FFT_BASE<double> in sltk_atom_arrange_test.cpp.o
  "ModulePW::FFT_BASE<double>::get_auxg_data() const", referenced from:
      vtable for ModulePW::FFT_BASE<double> in sltk_atom_arrange_test.cpp.o

使用的cmake选项：
option(ENABLE_LCAO "Enable LCAO calculation." ON)
option(ENABLE_DEEPKS "Enable DeePKS functionality" OFF)
option(ENABLE_LIBXC "Enable LibXC functionality" ON)
option(USE_CUDA "Enable support to CUDA for ABACUS." OFF)
option(ENABLE_FLOAT_FFTW "Enable support to single precision FFTW library." OFF)
option(USE_ROCM "Enable support to ROCm." OFF)
option(USE_OPENMP "Enable OpenMP in ABACUS." OFF)
option(ENABLE_ASAN "Enable AddressSanitizer" OFF)
option(BUILD_TESTING "Build ABACUS unit tests" OFF)
option(INFO "Enable gathering of math library information" OFF)
option(ENABLE_COVERAGE "Enable coverage build." OFF)
option(ENABLE_LIBRI "Enable EXX with LibRI." OFF)
option(ENABLE_LIBCOMM "Enable communicate with LibComm." ON)
option(ENABLE_PAW "Enable PAW calculation" OFF)
option(ENABLE_MPI "Enable compilation with or without MPI." ON)
option(USE_ELPA "Enable ELPA" OFF)
option(USE_ABACUS_LIBM "Build libmath from source to speed up." OFF)
option(GIT_SUBMODULE "Check submodules during build" ON)
option(DEBUG_INFO "Print message for developers to debug." OFF)
# Do not enable it if generated code will run on different CPUs
option(ENABLE_NATIVE_OPTIMIZATION
       "Enable compilation optimization for the native machine's CPU type" ON)
option(COMMIT_INFO "Print commit information in log" ON)
option(ENABLE_FFT_TWO_CENTER "Enable FFT-based two-center integral method." ON)
option(ENABLE_GOOGLEBENCH "Enable GOOGLE-benchmark usage." ON)
option(ENABLE_RAPIDJSON "Enable rapid-json usage." OFF)
option(ENABLE_CNPY "Enable cnpy usage." OFF)
option(ENABLE_PEXSI "Enable support for PEXSI." OFF)
option(ENABLE_CUSOLVERMP "Enable cusolvermp." OFF)
option(USE_DSP "Enable DSP usage." OFF)

已经使用brew 安装了fftw等相关库，在cmake中也指定了fftw库的位置，但还是不对

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by A-006** [comment]
Can you tell me which MAC version to use?

**Comment by OutisLi** [comment]
> Can you tell me which MAC version to use?

OS: macOS Sequoia 15.1.1 arm64
Host: Mac mini (2024)
Kernel: Darwin 24.1.0

**Comment by A-006** [comment]
> > Can you tell me which MAC version to use?
> 
> OS: macOS Sequoia 15.1.1 arm64 Host: Mac mini (2024) Kernel: Darwin 24.1.0

Currently, abacus does not have a testing environment for Apple Clang. Can You  set the compiler to gcc14 or gcc11 or mpic++, and use DBUILD_TESTING=OFF.

**Comment by A-006** [comment]
> > Can you tell me which MAC version to use?
> 
> OS: macOS Sequoia 15.1.1 arm64 Host: Mac mini (2024) Kernel: Darwin 24.1.0

Could tell me your compile  instrucions.It seems that you set the DBUILD_TESTING=ON,Now there is not an environment for Mac OS.so you can just set the  DBUILD_TESTING=OFF.

**Comment by OutisLi** [comment]
> DBUILD_TESTING

我把ENABLE_GOOGLEBENCH关闭了，但是还是fftw报错。我检查了#include "fftw3.h"这个文件是存在在/opt/homebrew/include中的，我对cmakelists进行了修改[CMakeLists.txt](https://github.com/user-attachments/files/18037369/CMakeLists.txt)
我查找相关的动态库也能找到如图
![Image](https://github.com/user-attachments/assets/7d95feab-20a5-4707-9fb0-d7d5a208ed6f)

最后还是报错如下；
Undefined symbols for architecture arm64:
  "ModulePW::FFT_BASE<double>::initfft(int, int, int)", referenced from:
      vtable for ModulePW::FFT_BASE<double> in main.cpp.o
      vtable for ModulePW::FFT_CPU<double> in fft_bundle.cpp.o
  "ModulePW::FFT_BASE<double>::initfft(int, int, int, int, int, int, int, int, bool, bool)", referenced from:
      vtable for ModulePW::FFT_BASE<double> in main.cpp.o
  "ModulePW::FFT_BASE<float>::initfft(int, int, int)", referenced from:
      vtable for ModulePW::FFT_BASE<float> in main.cpp.o
      vtable for ModulePW::FFT_CPU<float> in fft_bundle.cpp.o
  "ModulePW::FFT_BASE<float>::initfft(int, int, int, int, int, int, int, int, bool, bool)", referenced from:
      vtable for ModulePW::FFT_BASE<float> in main.cpp.o
  "ModulePW::FFT_BASE<double>::fft3D_forward(std::__1::complex<double>*, std::__1::complex<double>*) const", referenced from:
      vtable for ModulePW::FFT_BASE<double> in main.cpp.o
      vtable for ModulePW::FFT_CPU<double> in fft_bundle.cpp.o
  "ModulePW::FFT_BASE<double>::get_auxg_data() const", referenced from:
      vtable for ModulePW::FFT_BASE<double> in main.cpp.o
  "ModulePW::FFT_BASE<double>::get_auxr_data() const", referenced from:
      vtable for ModulePW::FFT_BASE<double> in main.cpp.o
  "ModulePW::FFT_BASE<double>::fft3D_backward(std::__1::complex<double>*, std::__1::complex<double>*) const", referenced from:
      vtable for ModulePW::FFT_BASE<double> in main.cpp.o
      vtable for ModulePW::FFT_CPU<double> in fft_bundle.cpp.o
  "ModulePW::FFT_BASE<double>::get_rspace_data() const", referenced from:
      vtable for ModulePW::FFT_BASE<double> in main.cpp.o
  "ModulePW::FFT_BASE<double>::get_auxr_3d_data() const", referenced from:
      vtable for ModulePW::FFT_BASE<double> in main.cpp.o
      vtable for ModulePW::FFT_CPU<double> in fft_bundle.cpp.o
  "ModulePW::FFT_BASE<double>::fftzbac(std::__1::complex<double>*, std::__1::complex<double>*) const", referenced from:
      vtable for ModulePW::FFT_BASE<double> in main.cpp.o
  "ModulePW::FFT_BASE<double>::fftzfor(std::__1::complex<double>*, std::__1::complex<double>*) const", referenced from:
      vtable for ModulePW::FFT_BASE<double> in main.cpp.o
  "ModulePW::FFT_BASE<double>::fftxybac(std::__1::complex<double>*, std::__1::complex<double>*) const", referenced from:
      vtable for ModulePW::FFT_BASE<double> in main.cpp.o
  "ModulePW::FFT_BASE<double>::fftxyc2r(std::__1::complex<double>*, double*) const", referenced from:
      vtable for ModulePW::FFT_BASE<double> in main.cpp.o
  "ModulePW::FFT_BASE<double>::fftxyfor(std::__1::complex<double>*, std::__1::complex<double>*) const", referenced from:
      vtable for ModulePW::FFT_BASE<double> in main.cpp.o
  "ModulePW::FFT_BASE<double>::fftxyr2c(double*, std::__1::complex<double>*) const", referenced from:
      vtable for ModulePW::FFT_BASE<double> in main.cpp.o
  "ModulePW::FFT_BASE<float>::fft3D_forward(std::__1::complex<float>*, std::__1::complex<float>*) const", referenced from:
      vtable for ModulePW::FFT_BASE<float> in main.cpp.o
      vtable for ModulePW::FFT_CPU<float> in fft_bundle.cpp.o
  "ModulePW::FFT_BASE<float>::get_auxg_data() const", referenced from:
      vtable for ModulePW::FFT_BASE<float> in main.cpp.o
  "ModulePW::FFT_BASE<float>::get_auxr_data() const", referenced from:
      vtable for ModulePW::FFT_BASE<float> in main.cpp.o
  "ModulePW::FFT_BASE<float>::fft3D_backward(std::__1::complex<float>*, std::__1::complex<float>*) const", referenced from:
      vtable for ModulePW::FFT_BASE<float> in main.cpp.o
      vtable for ModulePW::FFT_CPU<float> in fft_bundle.cpp.o
  "ModulePW::FFT_BASE<float>::get_rspace_data() const", referenced from:
      vtable for ModulePW::FFT_BASE<float> in main.cpp.o
  "ModulePW::FFT_BASE<float>::get_auxr_3d_data() const", referenced from:
      vtable for ModulePW::FFT_BASE<float> in main.cpp.o
      vtable for ModulePW::FFT_CPU<float> in fft_bundle.cpp.o
  "ModulePW::FFT_BASE<float>::fftzbac(std::__1::complex<float>*, std::__1::complex<float>*) const", referenced from:
      vtable for ModulePW::FFT_BASE<float> in main.cpp.o
  "ModulePW::FFT_BASE<float>::fftzfor(std::__1::complex<float>*, std::__1::complex<float>*) const", referenced from:
      vtable for ModulePW::FFT_BASE<float> in main.cpp.o
  "ModulePW::FFT_BASE<float>::fftxybac(std::__1::complex<float>*, std::__1::complex<float>*) const", referenced from:
      vtable for ModulePW::FFT_BASE<float> in main.cpp.o
  "ModulePW::FFT_BASE<float>::fftxyc2r(std::__1::complex<float>*, float*) const", referenced from:
      vtable for ModulePW::FFT_BASE<float> in main.cpp.o
  "ModulePW::FFT_BASE<float>::fftxyfor(std::__1::complex<float>*, std::__1::complex<float>*) const", referenced from:
      vtable for ModulePW::FFT_BASE<float> in main.cpp.o
  "ModulePW::FFT_BASE<float>::fftxyr2c(float*, std::__1::complex<float>*) const", referenced from:
      vtable for ModulePW::FFT_BASE<float> in main.cpp.o
ld: symbol(s) not found for architecture arm64
c++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [abacus] Error 1
make[1]: *** [CMakeFiles/abacus.dir/all] Error 2
make: *** [all] Error 2

出现在最后链接的部分

**Comment by A-006** [comment]
Since I lack a MAC environment, you can try my modifications by using 
git clone -b fft8 https://github.com/A-006/abacus-develop.git. 
Thank you. There might still be other errors, please point them out, and I will do my best to address them.

**Comment by mohanchen** [comment]
Currently we don't support MAC, if you have further questions, please reopen the issue or raise a new issue.
