### ISSUE TITLE
First CG step of every MD step except the first MD step is much slower than other CG steps

### ISSUE THREAD

**Issue by Liu-RX** [deepmodeling/abacus-develop#570]
## Describe Current Status and Possible Solution

I was testing a 6-water cluster (prism) in a 10-Angstrom box with plane-wave MD when I encountered this issue. The first CG step of each MD step after the first MD step (which means 2, 3, 4, ... MD steps) is slower than other CG iterations. 
The tested geometry is as follows in a 10-Angstrom box:
18
prism (Angstrom)
O 1.48177134 -0.38076297 1.41635148
H 0.54980015 -0.71156814 1.53229732
H 1.98817476 -0.68311212 2.17396904
O 0.79080509 2.00892143 -0.06382021
H 1.11722198 1.46540185 0.67093808
H 1.15245966 1.55820226 -0.83911778
O 1.67906423 -0.50648504 -1.35763923
H 2.40812997 -0.93324027 -1.81457409
H 1.81915992 -0.64714738 -0.40117327
O -1.86394951 1.26508891 -0.07019175
H -0.96601505 1.66494403 -0.08043747
H -2.49003750 1.98807965 -0.15585021
O -1.15027391 -1.29159516 -1.37171807 
H -0.21826757 -1.10964569 -1.56988648
H -1.55550097 -0.41679332 -1.27664261
O -1.07806450 -1.13929446 1.43000657
H -1.13819160 -1.47458503 0.51189678
H -1.56304826 -0.30353340 1.36806551

The following screenshot shows the first and second MD steps, from which one can see the clear time difference.

![屏幕快照 2021-12-15 下午5 18 39](https://user-images.githubusercontent.com/75369672/146159483-5ceef935-5033-4820-97c1-f72c281b9b12.png)

**Comment by dyzheng** [comment]
I have a related test result that too much time for first scf step using convergence charge density.

ITER    ETOT(eV)            EDIFF(eV)          DRHO2      CG_ITER      TIME(S) 
CG1    -9.304415e+03  0.000000e+00   1.555e-09  2.432e+01  1.488e+02
CG2    -9.304409e+03  5.723870e-03    1.801e-09  8.489e+00  2.855e+01

By the way, h_psi time is 0.009s, and NBANDS = 56, nks = 10, times of hpsi per k point for first scf step is 1640 for 56 bands. It seems too many?

**Comment by mohanchen** [comment]
Is it because the initial wave functions are random?

**Comment by dyzheng** [comment]
> Is it because the initial wave functions are random?

Yes， I tested DOJO pseudopotential which has pseudo atomic wavefunction in pseudopotential files. First cg step is only slightly slower than others.

**Comment by mohanchen** [comment]
On one hand, I think the problem @Liu-RX met is because the initial guess of wave functions or atomic charge density is not properly extrapolated because the MD steps change the coordinates of atoms. On the other hand, the problem @dyzheng met is not properly described, we don't know it is an scf calculation or a MD calculation. More details should be added.

**Comment by dyzheng** [comment]
> On one hand, I think the problem @Liu-RX met is because the initial guess of wave functions or atomic charge density is not properly extrapolated because the MD steps change the coordinates of atoms. On the other hand, the problem @dyzheng met is not properly described, we don't know it is an scf calculation or a MD calculation. More details should be added.

Sorry, the problem I met is only about scf, it should be another issue.

**Comment by dyzheng** [comment]
Xiaohui Liu reported a "nan" output for MD calculation in plane wave base, I have turned this Issue to tag "Bug". 
I will test related case and fix this bug later.

**Comment by dyzheng** [comment]
[pw_md_error-nan.tar.gz](https://github.com/deepmodeling/abacus-develop/files/8496448/pw_md_error-nan.tar.gz)

**Comment by caic99** [comment]
Kindly reminder: `i` is not initialized here.
https://github.com/deepmodeling/abacus-develop/blob/0081653be8332fc440caad90280be9b50760f638/source/module_md/MSST.cpp#L95
https://github.com/deepmodeling/abacus-develop/blob/0081653be8332fc440caad90280be9b50760f638/source/module_md/MSST.cpp#L106

**Comment by dyzheng** [comment]
@YuLiu98

**Comment by YuLiu98** [comment]
The issue that the first CG step of every MD step is much slower than other CG steps existed **a long time ago**!

I tested the test `120_PW_KP_MD_NVTrestart` with the version of commit `76807828fcbabc4aecf333f512e477a82d5f43fe`, which is **before** the MD reconstruction.

![image](https://user-images.githubusercontent.com/77716030/163743217-774877f6-542c-4607-947b-b75e3f294d6f.png)

[run.log](https://github.com/deepmodeling/abacus-develop/files/8502993/run.log)

I note that the total time is 4 s, but the first step of every MD step is about 5 s, so I think the timer went wrong here.

**Comment by YuLiu98** [comment]
> Kindly reminder: `i` is not initialized here.

Thank you for your fix!

**Comment by YuLiu98** [comment]
> Xiaohui Liu reported a "nan" output for MD calculation in plane wave base, I have turned this Issue to tag "Bug".
> I will test related case and fix this bug later.

The issue may arise from the improper selection of the **thermostat mass**, which is controlled by the parameter `md_tfreq` instead of `msst_qmass`. And the determination of the **thermostat mass** is the same as **LAMMPS**.

In example-02, if parameter `md_tfreq` is set to **0.1**, MD will not output `nan`.
![image](https://user-images.githubusercontent.com/77716030/163746808-af483335-1c8f-4e80-a005-912b250305e5.png)


In fact, this is not a BUG, which also exists in LAMMPS, if the parameter related to **thermostat mass** is improper.

**Comment by dyzheng** [comment]
> The issue that the first CG step of every MD step is much slower than other CG steps existed **a long time ago**!
> 
> I tested the test `120_PW_KP_MD_NVTrestart` with the version of commit `76807828fcbabc4aecf333f512e477a82d5f43fe`, which is **before** the MD reconstruction.
> 
> ![image](https://user-images.githubusercontent.com/77716030/163743217-774877f6-542c-4607-947b-b75e3f294d6f.png)
> 
> [run.log](https://github.com/deepmodeling/abacus-develop/files/8502993/run.log)
> 
> I note that the total time is 4 s, but the first step of every MD step is about 5 s, so I think the timer went wrong here.

I have noticed two possible problems of MD with pw base:
1. there is no call of "GlobalC::pw.setup_structure_factor()" in run_md_pw.cpp, which should be update when position of atoms changed. maybe it is called but I missed.
2. When diagonalization is CG method, a preprocessing of diagH_subspace() is needed once, but in MD with PW base, it would be called twice when md_step>1 .

**Comment by YuLiu98** [comment]
> 1. there is no call of "GlobalC::pw.setup_structure_factor()" in run_md_pw.cpp, which should be update when position of atoms changed. maybe it is called but I missed.

"GlobalC::pw.setup_structure_factor()" is called once per MD step in the line 93 of run_md_pw.cpp.

**Comment by dyzheng** [comment]
There is a simple test for no initialization of wavefunction for md_step>1:
Test case: water H64O32

1. Init wavefunction every md_step:
" 
 CG1    -1.494886e+04  0.000000e+00   1.187e+01  9.575e+00  5.804e+01
 CG1    -1.495732e+04  0.000000e+00   1.608e-02  7.724e+01  4.151e+02
 CG1    -1.495735e+04  0.000000e+00   1.614e-02  7.482e+01  3.996e+02
 CG1    -1.495738e+04  0.000000e+00   1.619e-02  7.358e+01  3.919e+02
 CG1    -1.495743e+04  0.000000e+00   1.624e-02  7.310e+01  3.820e+02
 CG1    -1.495747e+04  0.000000e+00   1.624e-02  7.340e+01  3.905e+02
 CG1    -1.495751e+04  0.000000e+00   1.623e-02  8.334e+01  4.398e+02
 CG1    -1.495755e+04  0.000000e+00   1.611e-02  8.061e+01  4.214e+02
 CG1    -1.495759e+04  0.000000e+00   1.591e-02  8.150e+01  4.253e+02
 CG1    -1.495761e+04  0.000000e+00   1.559e-02  8.203e+01  4.313e+02
 CG1    -1.495762e+04  0.000000e+00   1.511e-02  8.122e+01  4.270e+02
 CG1    -1.495763e+04  0.000000e+00   1.442e-02  8.079e+01  4.226e+02
 CG1    -1.495762e+04  0.000000e+00   1.339e-02  7.872e+01  4.167e+02
 CG1    -1.495761e+04  0.000000e+00   1.197e-02  8.019e+01  4.226e+02
"

2. init wavefunction only in md_step<=1 
"
 CG1    -1.494886e+04  0.000000e+00   1.187e+01  9.575e+00  5.647e+01
 CG1    -1.495732e+04  0.000000e+00   1.608e-02  7.724e+01  4.062e+02
 CG1    -1.495735e+04  0.000000e+00   1.614e-02  3.339e+01  1.782e+02
 CG1    -1.495738e+04  0.000000e+00   1.619e-02  3.305e+01  1.790e+02
 CG1    -1.495743e+04  0.000000e+00   1.624e-02  3.299e+01  1.768e+02
 CG1    -1.495747e+04  0.000000e+00   1.624e-02  3.312e+01  1.737e+02
 CG1    -1.495751e+04  0.000000e+00   1.623e-02  4.130e+01  2.187e+02
"

**Comment by dyzheng** [comment]
> > 1. there is no call of "GlobalC::pw.setup_structure_factor()" in run_md_pw.cpp, which should be update when position of atoms changed. maybe it is called but I missed.
> 
> "GlobalC::pw.setup_structure_factor()" is called once per MD step in the line 93 of run_md_pw.cpp.

https://github.com/deepmodeling/abacus-develop/blob/develop/source/src_pw/run_md_pw.cpp 
I didn't find that, but I agree to add this function call in line 93.

**Comment by dyzheng** [comment]
> > 1. there is no call of "GlobalC::pw.setup_structure_factor()" in run_md_pw.cpp, which should be update when position of atoms changed. maybe it is called but I missed.
> 
> "GlobalC::pw.setup_structure_factor()" is called once per MD step in the line 93 of run_md_pw.cpp.

Ok, I find that, thanks!

**Comment by dyzheng** [comment]
> > Xiaohui Liu reported a "nan" output for MD calculation in plane wave base, I have turned this Issue to tag "Bug".
> > I will test related case and fix this bug later.
> 
> The issue may arise from the improper selection of the **thermostat mass**, which is controlled by the parameter `md_tfreq` instead of `msst_qmass`. And the determination of the **thermostat mass** is the same as **LAMMPS**.
> 
> In example-02, if parameter `md_tfreq` is set to **0.1**, MD will not output `nan`. ![image](https://user-images.githubusercontent.com/77716030/163746808-af483335-1c8f-4e80-a005-912b250305e5.png)
> 
> In fact, this is not a BUG, which also exists in LAMMPS, if the parameter related to **thermostat mass** is improper.

In documentation, I find "md_tfreq" has default value "1.0", does this default value caused Xiaohui Liu's problem? How can one user decide which md_tfreq should be set?

**Comment by YuLiu98** [comment]
> In documentation, I find "md_tfreq" has default value "1.0", does this default value caused Xiaohui Liu's problem? How can one user decide which md_tfreq should be set?

If `md_tfreq` is too large, the temperature can fluctuate wildly; if it is too small, the temperature will take a very long time to equilibrate. A good choice for many models is `1/md_tfreq` of around 100 timesteps.
