### ISSUE TITLE
The wannier90 interface tests are failed at 20241211

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#5715]
### Describe the Testing Issue

The tests with lcao and lcao_in_pw basis are failed.

![Image](https://github.com/user-attachments/assets/c87bb9af-c0d2-4580-ac28-f88ffbb3ea55)

https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fsched-abacustest-interface-test-9b0f5a

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by jingan-181** [comment]
In line 1227 of `source\module_esolver\esolver_ks_lcao.cpp`, `ucell.tpiba` and `ucell.omega` of `toWannier90_LCAO_IN_PW` are not initialized.
