### ISSUE TITLE
The program is stucked while calculating scf using HSE

### ISSUE THREAD

**Issue by JTaozhang** [deepmodeling/abacus-develop#5724]
### Describe the bug

Hi there,

Currently, I am using abacus 3.8.3 to calculate band structure of HfO2. I has successfully compiled the Libri and abacus. the program also has been successfully tested  on example of Si. However, when the program transfers to my system. it is stucked at SETUP EXTENDED REAL SPACE GRID FOR GRID INTEGRATION. meanwhile it is reported with  Warning_Memory_Consuming allocated:  HamiltLCAO::hR 327 MB.  I thoght it is due to out of memory, I try to adopt large memory node, the program was stucked at the place. Could you help me to reveal the problem and find the solution? 

I has done a lot testd too, the result is shown in the attached figures, although I have achieved the band structure by a special combination of thread and mpi, but the result is not right. it looks there indeed some problem with the cpus combination.

Best,
Tao[HfO2-hse-scf.zip](https://github.com/user-attachments/files/18108057/HfO2-hse-scf.zip)

### Expected behavior

running successfully

### Environment

module load cmake/cmake-3.25  gnu/12.1.0

source /share/apps/intel2022/setvars.sh
source *****/software/abacus-develop/toolchain/install/setup

#export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
ABACUS=*****/software/abacus-develop/bin

srun hostname -s |sort -n > slurm.hosts
mpirun -np 1 -env OMP_NUM_THREADS=48 $ABACUS/abacus

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by kirk0830** [comment]
@JTaozhang Hi, could you try with `ks_solver scalapack_gvx` and tell me what information you obtain then?

Regards.

**Comment by JTaozhang** [comment]
Hi @kirk0830 , I have tried it. it still failed. The Program is stucked at the same place.

regards,
Tao

**Comment by JTaozhang** [comment]
Hi there,
I am trying the supercell of mentioned HfO2 by 4x5x1. it also performs abnormal. one type of error is similar with that I mentioned earlier, another error is stucking at initializing the MPI step. I has done some test of different cpus combinations, and their results are shown in the attached files. could help me to check what happens to the program? The related files are also included in the attached files.

[Hf160O320.zip](https://github.com/user-attachments/files/18174149/Hf160O320.zip)

Best,
Tao

**Comment by Chentao168** [comment]
Using larger memory nodes (500 GB) and OMP parallelism, the task can be executed. It is recommended to use only OMP parallelism and large memory nodes when performing HSE calculations.
