### ISSUE TITLE
start_wfc = file interface has no corresponding implementation

### ISSUE THREAD

**Issue by Liu-RX** [deepmodeling/abacus-develop#577]
## Describe Current Status and Possible Solution

wavefunc.cpp has an interface corresponding to `start_wfc file` in `INPUT` file. But there is no implementation for this interface. I wonder what it's for.

**Comment by mohanchen** [comment]
@dyzheng @hongriTianqi Could you answer the question and provide possible solutions/plan here?

**Comment by dyzheng** [comment]
Reading wavefunction of plane wave is important, we can only print wavefunction now by setting out_wf as 1 or 2, but the reading function has not been implemented now.
I recommend you can set start_charge as 1 for reading charge density for non-self-consistent calculation.
We will add this function when we start to develop hybrid functional in ABACUS pw code.
