### ISSUE TITLE
Incorrect energy when bx/by/bz cannot be divided by the dimensions of FFT grid

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#580]
In my case, when i do not set bx in INPUT, the UNIFORM GRID DIM is 96 * 96 * 96
while when I set bx to be 5, the UNIFORM GRID DIM will be changed to 100 * 100 * 100, and the energy has a change of about 100 eV, that is from -1807.5069600630899913 eV to -1713.6079872077116306 eV .

If the change of UNIFORM GRID DIM will arouse the big change of energy, ABACUS should stop and give the ERROR when the setting of bx is not reasonable.
[bxyzerror.zip](https://github.com/deepmodeling/abacus-develop/files/7761698/bxyzerror.zip)

**Comment by mohanchen** [comment]
the use of bx=5 should be prohibited in this case. We need refactor not bug-fixed.

**Comment by wenfei-li** [comment]
This is because the size of FFT grid will be expanded to be a multiple of bx/by/bz. With different FFT grid, the calculated energy is naturally different. (I'm assuming here the FFT grid size is not converged.)

**Comment by wenfei-li** [comment]
One question : what's the result using 100*100*100 FFT grid but bx=by=bz=1?

**Comment by pxlxingliang** [comment]
I manually set nx=ny=nz=100, and bx/by/bz=1, and the calculated energy  is -1713.608086113457 eV, this result is not same with the energy (-1807.5069600630899913 eV) when using default nx and bx. It means that, if the nx/ny/nz is not the default value (same with the dimension of FFT), the calculation is wrong. May be, the FFT is not correct when nx/ny/nz is not default value?

**Comment by pxlxingliang** [comment]
I ran this structure by PW basis and set the ecutwfc to be 90/100/110 Ry. The energy of 100 Ry ecutwfc by ABACUS is abnormal smaller than those of 90/110 Ry ecutwfc, and also different to the results by QE. There may have some weird bug when setting ecutwfc to be 100 Ry in ABAUS.

Total Energy(Ry)
|ecutwfc|ABACUS|QE|
|:----:|:----:|:----:|
|90|-126.104899129|-126.10489912
|100|-133.30730175|-126.10489931|
|110|-126.104902259|-126.10490231|

the INPUT and OUTPUT files
[example.zip](https://github.com/deepmodeling/abacus-develop/files/9051012/example.zip)

ABACUS input
[abacus.zip](https://github.com/deepmodeling/abacus-develop/files/9052119/abacus.zip)

**Comment by pxlxingliang** [comment]
This may be the bug of symmetry, I re-run the job of ecutwfc=100 with setting symm = false by ABACUS, and this time the energy is -126.10489929 Ry, which is close to that by QE.

**Comment by pxlxingliang** [comment]
This structure has 48 space group operations, and the first 24 operations are the pure point group operations, and last 24 space group operations have the translation operation, which is [0.375, 0.375, 0.375]. 

The grid number of ecutwfc=90/100/110 is 90X90X90, 96X96X96, and 100X100X100, respectively. So only when ecutwfc=100, the grid number can just satisfy the translation operation (96*0.375 equals to an integer number), and when do the `rho_symmetry` it will contains the latter 24 space operations. 

Coincidently, the lattice vector of this structure do not satisfy the right-hand rule, and ABACUS will reverse the lattice vector and atom coordinate. So when doing the  `rho_symmetry` the translation operation should also be reversed, but ABACUS not do (this is a bug), which leads to the wrong density. 

After I fix this bug, the energy seems much more reasonable. But energy difference to the result of no symmetry has still about 0.0002 Ry. 

I try to remove the space group that has the translation operation when doing the `rho_symmetry`, and this time the total energy is nearly equal to that of symmetry=false.

Total energy (Ry)
|ecutwfc|symmetry=False|symmetry=True|symmetry=True <br />(fix the translation operation bug)|symmetry=True <br />(no translation operation)|
|:----:|:----:|:----:|:----:|:----:|
|90|-126.104899129|-126.104899129|-126.104899129|-126.104899129|
|100|-126.10489929|-133.30730175|-126.104690094|-126.104899301|

**Comment by pxlxingliang** [comment]
In some k points cases, there still has a little difference in energy between calculation with symmetry and without symmetry. This difference is exist in both QE abd ABACUS.

For example in KPT = 2 1 1 ecutwfc=100
The total energy(Ry)
|job type|QE|ABACUS|
|:----:|:----:|:----:|
|symmetry=off|-125.29614632|-125.296146339|
|symmetry=on|-125.29682130|-125.296821323(no translation)<br/>-125.296725464(has translation)|

Because the sampling of K points do not satisfy the symmetry, so the difference is  expected.
