### ISSUE TITLE
valgrind debug： 304_NO_GO_AF choked with valgrind while mpirun is alright

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#584]
## Describe the Bug
"test/integrate/304_NO_GO_AF" is running well using mpirun, 
but would be choked using valgrind.

**Comment by caic99** [comment]
Please provide more detailed information. @dyzheng

**Comment by dyzheng** [comment]
This error seems caused by my misuse of valgrind, I will close this Issue.
