### ISSUE TITLE
Stress error with symmetry on, only in LCAO code.

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#585]
## Describe the Bug
In case: 201_NO_KP_DJ_CF_CS_GaAs
Stress in LCAO base for symmetry on is :
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

-828.171936 | 7166.310456 | 7166.310456
-- | -- | --
7166.310456 | -828.171936 | 7166.310456
7166.310456 | 7166.310456 | -828.171936

</body>

</html>

When we test ABACUS with symmetry off, the analytical stress result is as below: 
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

-828.171937 | 7140.279641 | 7140.279641
-- | -- | --
7140.279641 | -828.171937 | 7140.279641
7140.279641 | 7140.279641 | -828.171937

</body>

</html>

After considering the lattice symmetry, the off-diagonal matricist results of the stress matrix are wrong.
But in PW base, analytical stress matrix is correct whether the symmetry option is on or off.

**Comment by mohanchen** [comment]
Try to clearly describe the issues, there are several typos in the sentences.

**Comment by dyzheng** [comment]
Okay, In ABACUS, user can set "symmetry" option in INPUT file to decide whether or not the lattice symmetry should be considered. 
We expect to be able to see whether considering the symmetry has no effect on the correctness of some outcomes: energy, ionic forces, stress matrix.
