### ISSUE TITLE
nbspline=1 would cause "nan" error.

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#589]
## Describe the Bug
In case /abacus-develop/test/integrate/133_PW_DJ_PK/ ,
Replace file INPUT with 
[INPUT.zip](https://github.com/deepmodeling/abacus-develop/files/7789076/INPUT.zip)

or just set "nbspline 1" or "nbspline 0"
you will see "nan" error:
`notconv = 8
 Hamilt::diago', too many bands are not converged! 
 CG1    nan            nan            -nan       3.110e+02  1.835e+00`

In my experience, this error often come from some variable divided by "zero".

**Comment by Qianruipku** [comment]
![图片](https://user-images.githubusercontent.com/76200646/148768364-55feacf6-245f-4223-a88d-dbe96dd8c740.png)
n must be larger than 1, or it will have (0)^-1 which causes "nan"
Besides, nbspline must be even.
