### ISSUE TITLE
"BAD TERMINATION" using LCAO in large system 

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#590]
In this example，where the SCF,FORCE,STRESS are calculated on the Si512 system and the ks_solver is scalapack_gvx, all calculations are normal finished, but in the end abacus throw the message as shown in below: 
![image](https://user-images.githubusercontent.com/91927439/147717238-f7252d92-b464-441d-b39a-a5c18c654ed3.png)

the running command is : mpirun -np 8 -env OMP_NUM_THREADS=1 abacus > result.log
[error.zip](https://github.com/deepmodeling/abacus-develop/files/8551828/error.zip)

**Comment by mohanchen** [comment]
@dyzheng Could you repeat the test and provide some clues?

**Comment by mohanchen** [comment]
@dyzheng same question: Could you repeat the test and provide some clues?

**Comment by dyzheng** [comment]
Sorry, I can't repeat the same error in my machine.
During My test, 7 cores lead to error in third scf loop, the error occured on calculating vlocal part for hamiltonian.
8 cores lead to error in forth scf loop, the error occured on calculating charge density.
It maybe caused by out of memory.
My suggestion for error from pxlxingliang is focus on memory leak problems, we would better solve reports from valgrind and sanitizer in some small cases first.

**Comment by mohanchen** [comment]
This may be due to memory leak problem, which is hard to find in the current stage. We will come back to this issue later (after we do some refactors)

**Comment by caic99** [comment]
Hi @pxlxingliang ,
I'm trying to reproduce this error. It shows:
```
 Something wrong during read_atom_positions.
 CHECK IN FILE : OUT.autotest/warning.log
```

**Comment by pxlxingliang** [comment]
> Hi @pxlxingliang , I'm trying to reproduce this error. It shows:
> 
> ```
>  Something wrong during read_atom_positions.
>  CHECK IN FILE : OUT.autotest/warning.log
> ```

I have update the attached file, and run it again, it can be run now, but the previous error is still occurred.

**Comment by caic99** [comment]
> > Hi @pxlxingliang , I'm trying to reproduce this error. It shows:
> > ```
> >  Something wrong during read_atom_positions.
> >  CHECK IN FILE : OUT.autotest/warning.log
> > ```
> 
> I have update the attached file, and run it again, it can be run now, but the previous error is still occurred.

OK, I reproduced with Intel OneAPI kit. Could you compiling it with `ENABLE_ASAN` flag and runnning it again to locate memory problems?

**Comment by pxlxingliang** [comment]
The dimension of ekb (which is used to accept the eigenvalue) is NBANDS, while the request dimension by SCALAPACK is NLOCAL, even though we use scalapck to solver only  NBANDS's eigenvalues. I try to increase the dimension of ekb to be NLOCAL, and run the example again, and this time there has no any error.

**Comment by caic99** [comment]
> The dimension of ekb (which is used to accept the eigenvalue) is NBANDS, while the request dimension by SCALAPACK is NLOCAL, even though we use scalapck to solver only NBANDS's eigenvalues. I try to increase the dimension of ekb to be NLOCAL, and run the example again, and this time there has no any error.

Hi @pxlxingliang ,
That's great! Could you submitting a patch for this?
