### ISSUE TITLE
ABACUS pw efficiency is significantly lower than QE

### ISSUE THREAD

**Issue by ouqi0711** [deepmodeling/abacus-develop#594]
## Describe Current Status and Possible Solution

A SCF+force test has been carried out on single water molecule gamma only calculation with pw basis in both ABACUS and QE. Same functional (PBE) and ECut (100Ry) are applied in both calculation. Running with 4 cpus, QE takes around 0.12s while ABACUS takes more than 1sec (see attached output). The number of calls on HPsi and FFT in ABACUS is significantly larger than that in QE. Corresponding codes (possible CG in SCF) might need to be optimized.  

## Additional Context
[test-pw.zip](https://github.com/deepmodeling/abacus-develop/files/7795328/test-pw.zip)

**Comment by Qianruipku** [comment]
There are 3 reasons:
1. ABACUS uses 14 nbands while QE uses 6 nbands
2. QE has gamma only while ABACUS does not have for pw basis
3. QE uses "david" diagonalization method which is faster than "cg" while ABACUS has not optimize "david" method yet and it uses "cg" method by default.
Besides, it seems ABACUS need a little more cg steps to get wavefunctions than that of QE. Maybe the cg method in ABACUS has some hidden problems.
All these problems need to be solved.

**Comment by mohanchen** [comment]
Has the issue been solved? @ouqi0711

**Comment by ouqi0711** [comment]
Thanks Qianrui. That makes sense!
