### ISSUE TITLE
LCAO MD stopping at 9-th step

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#595]
## Describe the Bug
When running MD with LCAO and PBE on a condensed phase water system containing 32 water molecules, the jobs always stops at 9-th ionic step, when carrying out diagonalization.
When setting ks_solver = genelpla, the job gets stucked.
When setting ks_solver = scalapack_gvx, the job quits with error message related to matrix not being positive definite.

## To Reproduce
Get the latest version of the code, compile and run with 16 cores.

## Environment
- Compiler: Intel oneapi
- Optional Dependencies: Intel MKL

## Additional Context
Rewinding the code to before merging update_MD solves the problem.Test case is attached.
[32water_test.zip](https://github.com/deepmodeling/abacus-develop/files/7795759/32water_test.zip)

**Comment by dyzheng** [comment]
@YuLiu98 I found mdtype==1 means ADS thermostat for NVT, and mdtype==2 means NHC thermostat for NVT. 
In the old version, mdtype==1 and set NVT_control as default 1 means NHC thermostat for NVT. 
Why did you do this modification?

The other problem is ADS thermostat is wrong for parallel version. 
Please take care of the random number used in ADS functional!!!

**Comment by YuLiu98** [comment]
Parameter NVT_control is useless in the new version, and mdtype is used to choose specific thermostat, which is more convenient.
> I found mdtype==1 means ADS thermostat for NVT, and mdtype==2 means NHC thermostat for NVT.
In the old version, mdtype==1 and set NVT_control as default 1 means NHC thermostat for NVT.
Why did you do this modification?

This issue results from the random number used in ADS thermostat, and I will fix it.

> The other problem is ADS thermostat is wrong for parallel version.
Please take care of the random number used in ADS functional!!!

>
