### ISSUE TITLE
Too many OPENBLAS warning printed for GNU compiler!

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#606]
## Describe the Bug
In test case: tests/integrate/301_NO_GO_15_CF_CS
There are too many warning message printed as :
"OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option."

When using "cmake -B bulid -DUSE_OPENMP=1" for compiling, and gamma_only = 1 this error would happen, but the error would disappear when gamma_only=0 or basis_type=pw.

**Comment by dyzheng** [comment]
I found that the warning message come from function : UHM.GG.cal_rho(GlobalC::LOC.DM);

**Comment by dyzheng** [comment]
It is come from "dsymm_()" function.

**Comment by dyzheng** [comment]
but the function dgemm_() is ok.

**Comment by caic99** [comment]
> ## Describe the Bug
> In test case: tests/integrate/301_NO_GO_15_CF_CS There are too many warning message printed as : "OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option."
> 
> When using "cmake -B bulid -DUSE_OPENMP=1" for compiling, and gamma_only = 1 this error would happen, but the error would disappear when gamma_only=0 or basis_type=pw.

Hi @dyzheng ,
The warning comes from the OpenBLAS library. You should try rebuild OpenBLAS but not ABACUS with that flag.

**Comment by mohanchen** [comment]
Has the problem been solved? @dyzheng @caic99

**Comment by caic99** [comment]
> Has the problem been solved? @dyzheng @caic99

Hi @mohanchen ,
I didn't encounter such problems, and I'm still waiting for response from @dyzheng .

**Comment by dyzheng** [comment]
I did not solve this problem now, because I havn't rebuild my OpenBLAS on my GNU docker image till now.
Maybe my image for ABACUS with GNU compiler is too old, how can I get same image as CI test using now?@caic99

**Comment by caic99** [comment]
> I did not solve this problem now, because I havn't rebuild my OpenBLAS on my GNU docker image till now. Maybe my image for ABACUS with GNU compiler is too old, how can I get same image as CI test using now?@caic99

Hi @dyzheng ,
You can get the docker image with tag `gnu` from our repo's package. https://github.com/deepmodeling/abacus-develop/pkgs/container/abacus-development-kit/14013813?tag=gnu
