### ISSUE TITLE
Bugs in unittests with cmake

### ISSUE THREAD

**Issue by YuLiu98** [deepmodeling/abacus-develop#611]
## Describe the Bug
When ABACUS is complied with the option **BUILD_TESTING** ON, if the compile command `cmake --install build` is used in the last, 
the executable file `base_matrix3` will be moved to `/build/tests/`.
Run it will report an error:
`error while loading shared libraries: libelpa.so.15: cannot open shared object file: No such file or directory`

## To Reproduce
1. [e.g. clone the source code from ...]
2. [e.g. configure CMake with options ...]
3. [e.g. build ABACUS with ...]
4. [e.g. run ABACUS with ...]

## Environment
- OS: Ubuntu 18.04
- Compiler: Intel oneAPI 2021
- Optional Dependencies: Intel MKL, elpa2021.05.002

**Comment by caic99** [comment]
Hi @YuLiu98 ,
Could you please check if the `abacus` main program is able to execute normally? If not so, the program may related to the path to your `libelpa.so`. What is the path, and have you added it to `LIBRARY_PATH` environment variable?

**Comment by YuLiu98** [comment]
> Hi @YuLiu98 , Could you please check if the `abacus` main program is able to execute normally? If not so, the program may related to the path to your `libelpa.so`. What is the path, and have you added it to `LIBRARY_PATH` environment variable?

Yes, the `abacus` main program is able to execute normally.

Without the command `cmake --install build`, the `abacus` main program and executable files such as `base_matrix3` can also run normally.

**Comment by caic99** [comment]
> > Hi @YuLiu98 , Could you please check if the `abacus` main program is able to execute normally? If not so, the program may related to the path to your `libelpa.so`. What is the path, and have you added it to `LIBRARY_PATH` environment variable?
> 
> Yes, the `abacus` main program is able to execute normally.
> 
> Without the command `cmake --install build`, the `abacus` main program and executable files such as `base_matrix3` can also run normally.

OK, where did you install your elpa library?

**Comment by caic99** [comment]
Hi @YuLiu98 ,
Could you run `ldd ./base_matrix3` for me to see if the `libelpa.so` is properly linked?

**Comment by YuLiu98** [comment]
> Hi @YuLiu98 , Could you run `ldd ./base_matrix3` for me to see if the `libelpa.so` is properly linked?

1) `ldd ./base_matrix3`:  
`libelpa.so.15 => not found`

2) `ldd ../abacus`:  
`libelpa.so.15 => /home/liuyu/soft/newelpa/lib/libelpa.so.15 (0x00007eff069ea000)`

The main problem is ok, but the unittest executable files can not link the `libelpa.so`.

Without the command `cmake --install build`, everything is ok.

**Comment by caic99** [comment]
@YuLiu98 Hmmm, it seems that your elpa library is not installed in a standard place. Have you ever tried extending `/home/liuyu/soft/newelpa/lib` to environment variable `LIBRARY_PATH` and `LD_LIBRARY_PATH`?

**Comment by YuLiu98** [comment]
> @YuLiu98 Hmmm, it seems that your elpa library is not installed in a standard place. Have you ever tried extending `/home/liuyu/soft/newelpa/lib` to environment variable `LIBRARY_PATH` and `LD_LIBRARY_PATH`?

OK, thank you! Now the unittest executable files can link the `libelpa.so` properly.
