### ISSUE TITLE
Incorrect using of "inline" function in module_base/complexarray.h

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#616]
In module_base/complexarray.h, it has declared an "inline" function "inline void operator=(std::complex <double> c);", but the definition is in "complexarray.cpp", this will cause error when this function is called in other codes.

I suggest modify this function to be a normal function by removing "inline".

**Comment by caic99** [comment]
> In module_base/complexarray.h, it has declared an "inline" function "inline void operator=(std::complex c);", but the definition is in "complexarray.cpp", this will cause error when this function is called in other codes.
> 
> I suggest modify this function to be a normal function by removing "inline".

@pxlxingliang Thank you for your issue! Could you provide detailed information on how the 'inline' attribute causes error?

**Comment by pxlxingliang** [comment]
In my "complexarray_test.cpp" (attached file 
[complexarray_test.cpp.txt](https://github.com/deepmodeling/abacus-develop/files/7838086/complexarray_test.cpp.txt)
), the compilation is failed (command is: g++ complexarray_test.cpp ../complexarray.cpp -lgtest -lpthread -lgtest_main), and the message is as below: 
```bash
In file included from complexarray_test.cpp:1:
../complexarray.h:35:13: warning: inline function ‘void ModuleBase::ComplexArray::operator=(std::complex<double>)’ used but never defined
   35 | inline void operator=(std::complex <double> c);
      |             ^~~~~~~~
/usr/bin/ld: /tmp/ccJLqIxR.o: in function `ComplexArray_test::SetUp()':
complexarray_test.cpp:(.text._ZN17ComplexArray_test5SetUpEv[_ZN17ComplexArray_test5SetUpEv]+0x342): undefined reference to `ModuleBase::ComplexArray::operator=(std::complex<double>)'
/usr/bin/ld: complexarray_test.cpp:(.text._ZN17ComplexArray_test5SetUpEv[_ZN17ComplexArray_test5SetUpEv]+0x36a): undefined reference to `ModuleBase::ComplexArray::operator=(std::complex<double>)'
/usr/bin/ld: complexarray_test.cpp:(.text._ZN17ComplexArray_test5SetUpEv[_ZN17ComplexArray_test5SetUpEv]+0x392): undefined reference to `ModuleBase::ComplexArray::operator=(std::complex<double>)'
/usr/bin/ld: complexarray_test.cpp:(.text._ZN17ComplexArray_test5SetUpEv[_ZN17ComplexArray_test5SetUpEv]+0x3ba): undefined reference to `ModuleBase::ComplexArray::operator=(std::complex<double>)'
/usr/bin/ld: complexarray_test.cpp:(.text._ZN17ComplexArray_test5SetUpEv[_ZN17ComplexArray_test5SetUpEv]+0x3e5): undefined reference to `ModuleBase::ComplexArray::operator=(std::complex<double>)'
/usr/bin/ld: /tmp/ccJLqIxR.o:complexarray_test.cpp:(.text._ZN17ComplexArray_test5SetUpEv[_ZN17ComplexArray_test5SetUpEv]+0x42b): more undefined references to `ModuleBase::ComplexArray::operator=(std::complex<double>)' follow
collect2: error: ld returned 1 exit status
```

> > In module_base/complexarray.h, it has declared an "inline" function "inline void operator=(std::complex c);", but the definition is in "complexarray.cpp", this will cause error when this function is called in other codes.
> > I suggest modify this function to be a normal function by removing "inline".
> 
> @pxlxingliang Thank you for your issue! Could you provide detailed information on how the 'inline' attribute causes error?

**Comment by caic99** [comment]
It seems that the declaration of operator = does not match its definition(the `const` decorator of argument).
https://github.com/deepmodeling/abacus-develop/blob/9aa165087b1049eb668165a9c6e354336374e903/source/module_base/complexarray.h#L35
https://github.com/deepmodeling/abacus-develop/blob/9aa165087b1049eb668165a9c6e354336374e903/source/module_base/complexarray.cpp#L129

**Comment by caic99** [comment]
The inlined functions should not be declared and defined in separated files, you can just remove the 'inline' attribute of function. @pxlxingliang Would you fix the bug for us?

**Comment by pxlxingliang** [comment]
> The inlined functions should not be declared and defined in separated files, you can just remove the 'inline' attribute of function. @pxlxingliang Would you fix the bug for us?

ok, I will submit a PR to fix it.
