### ISSUE TITLE
init_meshball problem

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#627]
## Describe the Bug
When running an example with water molecule using develop branch, I encounter the following error message:

ABACUS.mpi: ./src_lcao/grid_meshball.cpp:124: void Grid_MeshBall::init_meshball(): Assertion `count == this->meshball_ncells' failed.

The error occurs for serial as well as parallel running. The example is attached:
[meshball_bug.zip](https://github.com/deepmodeling/abacus-develop/files/7846728/meshball_bug.zip)

**Comment by mohanchen** [comment]
@YuLiu98 Could you reproduce this error? This error is related to the grid integral used in LCAO.

**Comment by YuLiu98** [comment]
> @YuLiu98 Could you reproduce this error? This error is related to the grid integral used in LCAO.

Everything is OK with the latest develop branch on my workstation.

**Comment by mohanchen** [comment]
@caic99 We need a solution to quickly repeat this kind of bug in different environments, could you reach out and provide a solution? If you have more questions, please reply here.

**Comment by caic99** [comment]
> @caic99 We need a solution to quickly repeat this kind of bug in different environments, could you reach out and provide a solution? If you have more questions, please reply here.

Hi @mohanchen ,
@wenfei-li did not provide her/his environment detail. From the executable name, I guess this error happens with an executable compiled by Makefile. Since there's no guaranteed support for Makefile compilation, it's hard to reproduce the case.
In addition to compilation, the running status also matters, say the number of MPI processes. The bug reporter and @YuLiu98 didn't provide enough information for developers to triage.

And @wenfei-li , would you provide the environment and compilation detail? Thanks.

**Comment by wenfei-li** [comment]
> > @caic99 We need a solution to quickly repeat this kind of bug in different environments, could you reach out and provide a solution? If you have more questions, please reply here.
> 
> Hi @mohanchen , @wenfei-li did not provide her/his environment detail. From the executable name, I guess this error happens with an executable compiled by Makefile. Since there's no guaranteed support for Makefile compilation, it's hard to reproduce the case. In addition to compilation, the running status also matters, say the number of MPI processes. The bug reporter and @YuLiu98 didn't provide enough information for developers to triage.
> 
> And @wenfei-li , would you provide the environment and compilation detail? Thanks.

I cannot reproduce the bug myself ... I'll close the issue.
