### ISSUE TITLE
Bug report for CI test of 311_NO_GO_S2_elec_minus case

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#637]
## Describe the Bug
In CI test, we found some errors randomly occured and we don't know why.
This case should be tested by valgrind.
311_NO_GO_S2_elec_minus for PR #636

**Comment by dyzheng** [comment]
Another error occurs on case 831_NO_GO_LT_bcc in CI test. #636

**Comment by dyzheng** [comment]
Another error occurs on case 830_NO_GO_LT_fcc in CI test for PR #634

**Comment by dyzheng** [comment]
Another error occurs on case 345_NO_GO_BS in CI test for PR #634

**Comment by pxlxingliang** [comment]
Another case is 260_NO_15_PK_PU_AF in CI test for PR 612

**Comment by mohanchen** [comment]
some errors? What kind of errors? Could you provide further details?

**Comment by mohanchen** [comment]
@caic99 could you collect more data and feedbacks on this issue?

**Comment by caic99** [comment]
> @caic99 could you collect more data and feedbacks on this issue?

Hi @mohanchen ,
I've collected some potential memory leakage problems using Address Sanitizer. We'll look into these special cases after the common problems are fixed.

**Comment by caic99** [comment]
`207_NO_KP_OD` also fails sometime, provided by @maki49 at https://github.com/deepmodeling/abacus-develop/pull/699/checks .
@hongriTianqi Does this case also failed once in your PR test?

**Comment by caic99** [comment]
> > @caic99 could you collect more data and feedbacks on this issue?
> 
> Hi @mohanchen , I've collected some potential memory leakage problems using Address Sanitizer. We'll look into these special cases after the common problems are fixed.

I'm attaching result file here.
[asan.md](https://github.com/deepmodeling/abacus-develop/files/8085079/asan.md)

Also at https://github.com/deepmodeling/abacus-develop/tree/dashboard .

**Comment by dyzheng** [comment]
311_NO_GO_S2_elec_minus, 831_NO_GO_LT_bcc, 830_NO_GO_LT_fcc, 345_NO_GO_BS cases still have problems recently.

**Comment by caic99** [comment]
Fixed by #1065.
