### ISSUE TITLE
Job "Aborted (core dumped)" when using Al.pz-vbc.UPF Pseudopotential

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#643]
In this case, ABACUS can not running when the pseudopotential is by using "Al.pz-vbc.UPF", and the error is:
abacus: /home/pxl/abacus-develop/source/src_pw/charge.cpp:253: lambda []()->std::vector<double, std::allocator<double>>::operator()()->std::vector<double, std::allocator<double>>: Assertion `charge!=0.0 || charge==atom->zv' failed.
Aborted (core dumped)

pseudopotential "Al.pz-vbc.UPF" is from QE, when I running the examples in QEPATH/PW/examples/example01, QE auto download it from internet.
[al-scf-cg.zip](https://github.com/deepmodeling/abacus-develop/files/7882561/al-scf-cg.zip)

**Comment by sunliang98** [comment]
In read_pp_upf201.cpp, we locate the position of the initial charge (Pseudopot_upf::rho_at) in pseudopotential by finding the key word "<PP_RHOATOM", for example, in "Al_ONCV_PBE-1.0.upf", the header of initial charge is "<PP_RHOATOM type="real"  size=" 602" columns="4">". However, in "Al.pz-vbc.UPF", the header is "<PP_RHOATOM>", so that ABACUS can't find initial charge, and corresponding warning is written in "warning.log": "In SCAN_BEGIN, can't find: <PP_RHOATOM block."
"<PP_RAB>", "<PP_DIJ>", and "<PP_R>" in "Al.pz-vbc.UPF" all cause similar problems, add a space in front of ">" can solve the problem.

**Comment by pxlxingliang** [comment]
May be, we should make ABACUS be compatible with the format like "<PP_RHOATOM>".

**Comment by YuLiu98** [comment]
> May be, we should make ABACUS be compatible with the format like "<PP_RHOATOM>".

Yes, maybe another method to extract keywords in pseudopotentials is needed. 
For example, if the first 11 characters of lines is `<PP_RHOATOM`, the part is judged to have been found, no matter the next character is `>` or space character.

**Comment by sunliang98** [comment]
> Yes, maybe another method to extract keywords in pseudopotentials is needed.
For example, if the first 11 characters of lines is <PP_RHOATOM, the part is judged to have been found, no matter the next character is > or space character.

This may cause new problem, for example, this is a key word `<PP_R`, it will be confused with `PP_RAB` and `PP_RHOATOM` if we just judge the first 5 characters.
Let ABACUS look for both `<PP_RHOATOM>` and `<PP_RHOATOM` may avoid this problem.

**Comment by YuLiu98** [comment]
> This may cause new problem, for example, this is a key word `<PP_R`, it will be confused with `PP_RAB` and `PP_RHOATOM` if we just judge the first 5 characters.
> Let ABACUS look for both `<PP_RHOATOM>` and `<PP_RHOATOM` may avoid this problem.

OK, you are right, I ignored the problem.

**Comment by mohanchen** [comment]
Has the problem been solved?

**Comment by sunliang98** [comment]
I have submitted the modified code according to the suggestion of @dyzheng and @caic99 .

**Comment by caic99** [comment]
> I have submitted the modified code according to the suggestion of @dyzheng and @caic99 .

Hi @sunliang98 ,
Are you ready with your PR? If all done, resolve conversations and request a review from @dyzheng .
