### ISSUE TITLE
diagonalization of Hamiltoian using lapack

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#661]
I noticed that ABACUS provided some interfaces to using LAPACK subroutines for solving the Hamiltonian matrix, but most of these interfaces are not used and/or not working:
1. In Pdiag_Double::diago_double_begin, there is an option KS_SOLVER=="lapack_gv", which calls the dsygv_ subroutine from LAPACK to solve the generalized eigenproblem HC=eSC;
2. In Pdiag_Double::diago_double_begin, there is an option KS_SOLVER=="lapack_gvx", which calls the dsygvx_ subroutine from LAPACK to solve the generalized eigenproblem HC=eSC;
3. Diago_LCAO_Matrix::using_LAPACK, which uses dsygv to solve the generalized eigenproblem, was called from Diago_LCAO_Matrix::solve_double_matrix when KS_SOLVER=="lapack", but has been commented out;
4. Hamilt_PW::diag_zheev, which supposedly solves the eigenproblem HC=eC, is not called at all in the program.
Also, it seems that the KS_Solver="lapack" option is only available for gamma point LCAO calculations.

I think it would be better to:
either remove those interfaces from the code;
or fix the interfaces and provide them as working options, especially for a serial version of ABACUS.

**Comment by mohanchen** [comment]
The LAPACK interface is used in two situations. (1) In the parallel version of the PW line, each processor calls LAPACK to diagonalize a small H matrix formed by the Bloch wave functions, resulting in a good initial guess of Bloch wave functions for the subsequent iterative diagonalization method, such as CG or Davidson. (2) In the serial version of the LCAO line. I think it would be better to fix the interface. However, those 'lapack_gv‘ and 'lapack_gvx' were added by Peize Lin (I guess), I am not sure the differences between 'lapack_gv' and 'lapack_gvx'.

**Comment by wenfei-li** [comment]
lapack_gv differs from lapack_gvx in the lapack subroutine called for solving matrix diagonalization. In lapack_gv, dsygv_ is called which returns all the eigenvalues of a Hermitian matrix; while in lapack_gvx, dsygvx_ is called which returns selected eigenvalues.

**Comment by caic99** [comment]
> lapack_gv differs from lapack_gvx in the lapack subroutine called for solving matrix diagonalization. In lapack_gv, dsygv_ is called which returns all the eigenvalues of a Hermitian matrix; while in lapack_gvx, dsygvx_ is called which returns selected eigenvalues.

Hi @wenfei-li ,
I didn't see the difference in your first issue message (dsygv vs. dsygvx). It may be a typo.

**Comment by wenfei-li** [comment]
> > lapack_gv differs from lapack_gvx in the lapack subroutine called for solving matrix diagonalization. In lapack_gv, dsygv_ is called which returns all the eigenvalues of a Hermitian matrix; while in lapack_gvx, dsygvx_ is called which returns selected eigenvalues.
> 
> Hi @wenfei-li , I didn't see the difference in your first issue message (dsygv vs. dsygvx). It may be a typo.

thanks! i've edited it

**Comment by wenfei-li** [comment]
This issue is merged into #771
