### ISSUE TITLE
Memory leak in Parallel: any of examples fails when running with `valgrind --trace-children=yes` 

### ISSUE THREAD

**Issue by maki49** [deepmodeling/abacus-develop#664]
## Describe the Bug
When running ABACUS with `valgrind --trace-children=yes` for any cases, it will report errors and stop before any calculation. 
- uninitialised bytes
- uninitialised value
- definately lost

That may indicate that there exists memory leak in parallel program. 
If these are fixed, it would be much more convenient to debug in parallel programming. 
![image](https://user-images.githubusercontent.com/33978601/151098427-eea11b7a-3020-41cd-a3cb-fefe93e982cf.png)

## To Reproduce
1. compile ABACUS (current develop branch)
2. cd examples/01a_Si_diamond_pw_scf/
3. run: `valgrind --trace-children=yes mpirun -n 4 ../../bin/ABACUS.mpi`

## Environment
- OS: Ubuntu 16.04
- Compiler: oneAPI 2021.3.0
- Optional Dependencies: Intel MKL; Valgrind

**Comment by caic99** [comment]
Hi @maki49 ,
Would you follow the guideline of valgrind to add flags to trace detailed message? In your image, "Rerun with --leak-check-full to see details of leaked memory".
Also, try to use address sanitizer for a more accurate result. Compile abacus with `-DENABLE_ASAN=ON` and run the program.

**Comment by caic99** [comment]
@maki49 Besides, It's better to quote the output data in text format, rather than attach a screenshot.

**Comment by maki49** [comment]
I've compiled with `-DENABLE_ASAN=ON` and rerun `examples/01a_Si_diamond_pw_scf` with `valgrind --leak-check=full --trace-children=yes mpirun -n 4 ../../build/abacus`.
Here is the full output-log.
[valgrind_full_children.log](https://github.com/deepmodeling/abacus-develop/files/7940744/valgrind_full_children.log)

**Comment by caic99** [comment]
> I've compiled with `-DENABLE_ASAN=ON` and rerun `examples/01a_Si_diamond_pw_scf` with `valgrind --leak-check=full --trace-children=yes mpirun -n 4 ../../build/abacus`. Here is the full output-log. [valgrind_full_children.log](https://github.com/deepmodeling/abacus-develop/files/7940744/valgrind_full_children.log)

Hi @maki49 ,
Thank you for your report. However, Sanitizer and Valgrind are two tools of same purpose. Please don't use them together, just running without valgrind is OK.

**Comment by mohanchen** [comment]
Memory leak is a problem that will be solved later.

**Comment by caic99** [comment]
Hi @maki49 ,
There should be no other user codes(not third-party codes, e.g. MPI) memory leak after my patches, see [dashboard](https://github.com/deepmodeling/abacus-develop/tree/dashboard) for more details.
