### ISSUE TITLE
Refactor "ddot"s (too many interfaces)

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#667]
There are many realizations of the method "ddot" in the program which supposedly calculates the inner product between two complex arrays:
1. Diago_CG::ddot, which is defined as:
```
std::complex<double> Diago_CG::ddot
(
    const int & dim,
    const ModuleBase::ComplexMatrix &psi,
    const int & m,
    std::complex<double> *psik
)
{
    std::complex<double> result(0, 0);
    assert(dim > 0) ;

    for (int i = 0; i < dim ; i++)
    {
        result += conj(psi(m, i)) *  psik[i] ;
    }

    Parallel_Reduce::reduce_complex_double_pool( result );

    return result;
}  // end of ddot
```

2. DiagoCG::ddot_real and Hamilt_PW::ddot_real, both uses:
```
    int dim2=2*dim;
    double *pL,*pR;
    pL=(double *)psi_L;
    pR=(double *)psi_R;
    double result=BlasConnector::dot(dim2,pL,1,pR,1);
    if(reduce)  Parallel_Reduce::reduce_double_pool( result );
    return result;
```

3. Hamilt_PW::ddot, which uses:
```
	std::complex<double> result = ModuleBase::ZERO;
	const int incx = 1;
	const int incy = 1;
	// mohan add 2010-10-11
	zdotc_(&result, &dim, psi_L, &incx, psi_R, &incy);

	if(GlobalV::NPROC_IN_POOL>1)
	{
		Parallel_Reduce::reduce_complex_double_pool( result );
	}
        return result;
```

4. Hamilt_PW::just_ddot, which uses:
```
	static int warn_about_zdotc=true;
	if(warn_about_zdotc)
	{
		GlobalV::ofs_warning << " in Hamilt_PW::just_ddot, sometimes zdotc is not available due to GNU compiler!!!" << std::endl;
		GlobalV::ofs_warning << " So here I use simple for cicle to replace zdotc, but it will affect the speed." << std::endl;
		warn_about_zdotc=false;
	}
	for(int i=0; i<dim; ++i)
	{
		result += conj(psi_L[i])*psi_R[i];
	}
```

5. ddot in xc_3.cpp, which uses:
```
    std::complex < double> prod;

    if (n < 1 || incx <= 0 || incy <= 0)
    {
        std::cerr << "\n error in ddot, n < 1 or incx <= 0 or incy <= 0, ";
        return 0;
    }

    prod = std::complex < double>(0.0, 0.0);

    for (int ix = 0, iy = 0;ix < n && iy < n;ix += incx, iy += incy)
    {
        prod += conj(x[ix]) * y[iy];
    }
```

Of all those different realizations, only DiagoCG::ddot_real is actually used in the code.
Besides, I noticed there were some places where DiagoCG::ddot was used but has been replaced by a direct loop, such as this part in Diago_David::SchmitOrth:
```
    for (int j = 0; j < m; j++)
    {
        for (int ig = 0; ig < npw; ig++)
        {
            lagrange[j] += conj( psi(j,ig) ) * spsi[ig] ;
        }
        //	lagrange[j] = Diago_CG::ddot( npw, psi, j, spsi );
    }

    Parallel_Reduce::reduce_complex_double_pool( hc.c+offset_h, notconv*hc.nr );
    Parallel_Reduce::reduce_complex_double_pool( sc.c+offset_s, notconv*sc.nr );
```

I tried switch back to using Diago_CG::ddot, and commenting out the Parallel_Reduce::reduce_complex_double_pool( result ) from Diago_CG::ddot, and the program gives the same results as using the loop.
I think it would be better to have a unified interface to the inner product operation, instead of many different ones scattered around the program.

**Comment by mohanchen** [comment]
Yes, it is better to have just one ddot, the same logic applied to dcopy, etc. However, please keep in mind that in the GPU version, the ddot may have different implementations

**Comment by wenfei-li** [comment]
> Yes, it is better to have just one ddot, the same logic applied to dcopy, etc. However, please keep in mind that in the GPU version, the ddot may have different implementations

I see .. I think I can first try sort out the CPU-related methods.

**Comment by mohanchen** [comment]
Any progress on this issue? @dyzheng

**Comment by dyzheng** [comment]
The function ddot looks like a operator overloading. 
Maybe a good solution is that a uniform operator overloading and using unique overloading for some special class.

**Comment by dyzheng** [comment]
It is not a urgent problem, we will keep optimizing these common functions.
