### ISSUE TITLE
Davidson diagonalization gives wrong results

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#668]
## Describe the Bug
ks_solver == 'dav' does not produce the correct result

## To Reproduce
For any of the PW examples in the intergrate test, add "ks_solver dav", the resulting energy will be different from running with default diagonalization (which uses CG method)

**Comment by mohanchen** [comment]
@Qianruipku Could you take a look and write down your suggestions here?

**Comment by Qianruipku** [comment]
I have test 101_PW_15_pseudopots, 103_PW_15_CS_CF, 104_PW_AF_magnetic, 105_PW_FD_smearing,106_PW_BD_chargemixing, 140_PW_15_SO. (in develop branch)
Only results of 101_PW_15_pseudopots are different?
In 101_PW_15_pseudopots, if I change the STRUCTURE a little, the results can be the same.
So it is rare for two methods getting different results.

**Comment by Qianruipku** [comment]
In 101_PW_15_pseudopots, two methods get different results.
I also run it with QE, two methods in QE get the same result, which is equal to the CG method in ABACUS.
Maybe the DAV program in ABACUS have a little problems or it right and QE may get different results in some case.

**Comment by mohanchen** [comment]
> In 101_PW_15_pseudopots, two methods get different results. I also run it with QE, two methods in QE get the same result, which is equal to the CG method in ABACUS. Maybe the DAV program in ABACUS have a little problems or it right and QE may get different results in some case.

How different?

**Comment by pxlxingliang** [comment]
I have calculated the below two examples, the difference in 101_PW_15_pseudopots is a little bigger than that in 103_PW_15_CS_CF, but I don't think the difference is unacceptable. 
101_PW_15_pseudopots cg=-197.1405644352774971, dav=-197.1405644327929281, cg-dav=-2.4845689949870575e-09
103_PW_15_CS_CF cg=-4206.8778432386461645, dav=-4206.8778432383041945, cg-dav=-3.41970007866621e-10
@Qianruipku
