### ISSUE TITLE
GlobalC makes UT executable large

### ISSUE THREAD

**Issue by caic99** [deepmodeling/abacus-develop#670]
# Current status
When writing UTs, the "spaghetti code" leads to the requirement of nearly every abacus model.
Take `tool_check_test` under module_base as an example. The requirement chain is:
tool_check_test.cpp tool_check_test.cpp  ../tool_check.cpp ../tool_quit.cpp ../global_variable.cpp ../timer.cpp ../global_file.cpp ../memory.cpp 
Thus, we have to link `base` into unit test, and it requires `parallel`. The `GlobalV` namespace in global_variable.cpp then depends largely on other codes, eventually linking the whole library into a single unit test.
# Possible solution
The ideal situation is: each unit test only needs to compile the main program and the tested code, while other related methods should be minimized and mocked. However, we need a top-down design of code structure on the refactoring of abacus.
@mohanchen @dyzheng

**Comment by dyzheng** [comment]
If any source code rely on GlobalV to parameter transfer, now there is no time to discuss the top-level design of GlobalV, but we need to write the unit test first and modify the source code to reduce the dependency.

**Comment by dyzheng** [comment]
I have tested this file tool_check_test, maybe the solution for this dependency problem is mock for "tool_quit.cpp"

**Comment by mohanchen** [comment]
I would suggest that we don't need to test for "tool_quit.cpp" at this moment. What do you guys think?

**Comment by dyzheng** [comment]
> I would suggest that we don't need to test for "tool_quit.cpp" at this moment. What do you guys think?

Yes, I have tried this method, and added mock for WARNING_QUIT() for file tool_check_test.cpp:
`
#include "../tool_quit.h"
void ModuleBase::WARNING_QUIT(const std::string &file,const std::string &description)
{
	std::cout<<"NOTICE"<<std::endl;
}
`
The compiling is correct for dependents: tool_check_test.cpp ../tool_check.cpp .
And the executable file is very small.

**Comment by dyzheng** [comment]
Maybe the settlement is not the best for our unittest code. But we definitly not dependent whole ABACUS files.

**Comment by caic99** [comment]
> I would suggest that we don't need to test for "tool_quit.cpp" at this moment. What do you guys think?

@mohanchen  Agreed.

> If any source code rely on GlobalV to parameter transfer, now there is no time to discuss the top-level design of GlobalV, but we need to write the unit test first and modify the source code to reduce the dependency.

@dyzheng It's a waste of time "modify the source code to reduce the dependency" at this time. The refactoring project should take this  into consideration. For UTs, I'll find a solution.

**Comment by hongriTianqi** [comment]
> The GlobalV namespace in global_variable.cpp then depends largely on other codes, eventually linking the whole library into a single unit test.

@caic99 @dyzheng @mohanchen 

This is wrong. GlobalV only includes declaration of some 100 parameters, and no other dependence.

**Comment by hongriTianqi** [comment]
> I would suggest that we don't need to test for "tool_quit.cpp" at this moment. What do you guys think?

@mohanchen @dyzheng @caic99 

disagree. To postpone is not to solve.

**Comment by mohanchen** [comment]
> > The GlobalV namespace in global_variable.cpp then depends largely on other codes, eventually linking the whole library into a single unit test.
> 
> @caic99 @dyzheng @mohanchen
> 
> This is wrong. GlobalV only includes declaration of some 100 parameters, and no other dependence.

Agree, the GlobalV does not depend on others.

**Comment by mohanchen** [comment]
> # Current status
> When writing UTs, the "spaghetti code" leads to the requirement of nearly every abacus model. Take `tool_check_test` under module_base as an example. The requirement chain is: tool_check_test.cpp tool_check_test.cpp ../tool_check.cpp ../tool_quit.cpp ../global_variable.cpp ../timer.cpp ../global_file.cpp ../memory.cpp Thus, we have to link `base` into unit test, and it requires `parallel`. The `GlobalV` namespace in global_variable.cpp then depends largely on other codes, eventually linking the whole library into a single unit test.
> 
> # Possible solution
> The ideal situation is: each unit test only needs to compile the main program and the tested code, while other related methods should be minimized and mocked. However, we need a top-down design of code structure on the refactoring of abacus. @mohanchen @dyzheng

If we delete #include "../src_parallel/parallel_common.h in tool_quit.cpp, what will happen?

**Comment by caic99** [comment]
> > # Current status
> > When writing UTs, the "spaghetti code" leads to the requirement of nearly every abacus model. Take `tool_check_test` under module_base as an example. The requirement chain is: tool_check_test.cpp tool_check_test.cpp ../tool_check.cpp ../tool_quit.cpp ../global_variable.cpp ../timer.cpp ../global_file.cpp ../memory.cpp Thus, we have to link `base` into unit test, and it requires `parallel`. The `GlobalV` namespace in global_variable.cpp then depends largely on other codes, eventually linking the whole library into a single unit test.
> > # Possible solution
> > The ideal situation is: each unit test only needs to compile the main program and the tested code, while other related methods should be minimized and mocked. However, we need a top-down design of code structure on the refactoring of abacus. @mohanchen @dyzheng
> 
> If we delete #include "../src_parallel/parallel_common.h in tool_quit.cpp, what will happen?

Nothing happenes. I'll remove it.

**Comment by caic99** [comment]
> > > The GlobalV namespace in global_variable.cpp then depends largely on other codes, eventually linking the whole library into a single unit test.
> > 
> > 
> > @caic99 @dyzheng @mohanchen
> > This is wrong. GlobalV only includes declaration of some 100 parameters, and no other dependence.
> 
> Agree, the GlobalV does not depend on others.

My bad, I mixed up GlobalV with GlobalC. @hongriTianqi @mohanchen

**Comment by caic99** [comment]
> # Current status
> When writing UTs, the "spaghetti code" leads to the requirement of nearly every abacus model. Take `tool_check_test` under module_base as an example. The requirement chain is: tool_check_test.cpp tool_check_test.cpp ../tool_check.cpp ../tool_quit.cpp ../global_variable.cpp ../timer.cpp ../global_file.cpp ../memory.cpp Thus, we have to link `base` into unit test, and it requires `parallel`. The `GlobalV` namespace in global_variable.cpp then depends largely on other codes, eventually linking the whole library into a single unit test.
> 
> # Possible solution
> The ideal situation is: each unit test only needs to compile the main program and the tested code, while other related methods should be minimized and mocked. However, we need a top-down design of code structure on the refactoring of abacus. @mohanchen @dyzheng


Hi all,
In my PR #676 , I realized the proposed "possible solution" part.
