### ISSUE TITLE
Should we remove all globalV:: from module_base?

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#671]
For example, the GlobalV::ofs_running in tool_title.cpp. I noticed that someone actually tried to overload the TITLE function, such that ofstream is passed as an input variable. But the new TITLE function is only used in a limited number of places in the code.
Eliminating GlobalV from module_base would make it easier to build unit tests  since it removes dependence on the file global_variable.cpp which in turn depend on parallel_common.h and then the rest of the program. This is relevant to the previous issue:  [https://github.com/deepmodeling/abacus-develop/issues/670](url)

**Comment by mohanchen** [comment]
I think it is a good idea to pass ofs_running into TITLE function. 

Speaking of removing all "GlobalV::" variables from module_base, I think it is a good idea. However, I suggest the refactor plan be reviewed before anyone would like to do it.

**Comment by mohanchen** [comment]
In the refactor plan, one can list all of the GlobalV:: variables used in the module_base module.

**Comment by wenfei-li** [comment]
Sure.

**Comment by mohanchen** [comment]
Any progress on this issue? @dyzheng

**Comment by dyzheng** [comment]
There are 115 variables in GlobalV namespace in ABACUS now. 
In detail: 
a. 34 variables for testing, which are read from INPUT file and then saved as global variables in GlobalV. 
    plan: we will refactor them in our input refactor progress.
b. 13 variables for parallelization.
    plan: 11 of them will be refactored in our input refactor progress, and 2 of them will be cancelled.
c. NLOCAL variable is for saving number of LCAO bases, it only belongs to basis for LCAO, but the change for this variable would not be quick.
d. 50 variables for storing parameters from INPUT file for controlling the program.
    plan: we will refactor them in our input refactor progress.
e. other 17 variables would be changed firstly. 
    plan: all of them will be deleted.

**Comment by dyzheng** [comment]
We will not dealing with global variables in the short term,  it is not matter for keeping these variables in module_base now.
