### ISSUE TITLE
Should we put matrix inversion and diagonalization as methods of the two matrix class?

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#672]
Instead of passing the matrix class as an argument to matrix inversion and diagonalization subroutines, such as the following:
```
    // wrap function of fortran lapack routine zhegv
    // which solves the generalized eigenproblem Ax=eBx, where A is Hermitian and complex couble
    static inline
    void zhegv(	const int itype,const char jobz,const char uplo,const int n,ModuleBase::ComplexMatrix& a,
                const int lda,ModuleBase::ComplexMatrix& b,const int ldb,double* w,std::complex<double>* work,
                int lwork,double* rwork,int info)
    {	// Transpose the std::complex matrix to the fortran-form real-std::complex array.
        std::complex<double>* aux = LapackConnector::transpose(a, n, lda);
        std::complex<double>* bux = LapackConnector::transpose(b, n, ldb);

        // call the fortran routine
        zhegv_(&itype, &jobz, &uplo, &n, aux, &lda, bux, &ldb, w, work, &lwork, rwork, &info);
        // Transpose the fortran-form real-std::complex array to the std::complex matrix.
        LapackConnector::transpose(aux, a, n, lda);
        LapackConnector::transpose(bux, b, n, ldb);
        // free the memory.
        delete[] aux;
        delete[] bux;
    }
```
Would it be more natural to make it a method of the matrix class?

**Comment by mohanchen** [comment]
The subroutine shown above is a temporary solution for calling LAPACK subroutine, and the solution is not a perfect one. It origins from a fact that the data stored in ComplexMatrix owns a different format (row first or column first) as required by the input subroutine of LAPACK. Therefore, we have to transpose the input/output matrices a and b, which is a waste of computational time. In principle, we need to change the data format stored in ComplexMatrix.

**Comment by wenfei-li** [comment]
> The subroutine shown above is a temporary solution for calling LAPACK subroutine, and the solution is not a perfect one. It origins from a fact that the data stored in ComplexMatrix owns a different format (row first or column first) as required by the input subroutine of LAPACK. Therefore, we have to transpose the input/output matrices a and b, which is a waste of computational time. In principle, we need to change the data format stored in ComplexMatrix.

I see ... this information would be quite helpful in the future refactoring of module_base.

**Comment by caic99** [comment]
> std

Hi @wenfei-li ,
Would you help me finding out similar situations (transposition before & after lapack routine)? It would be very helpful determining matrix layout.

**Comment by wenfei-li** [comment]
> > std
> 
> Hi @wenfei-li , Would you help me finding out similar situations (transposition before & after lapack routine)? It would be very helpful determining matrix layout.

Basically all the wrappers in class LapackConnector uses the transpose function.

**Comment by mohanchen** [comment]
Any progress on this issue? @wenfei-li @caic99 @dyzheng

**Comment by caic99** [comment]
> Any progress on this issue? @wenfei-li @caic99 @dyzheng

Hi @mohanchen ,
This problem should be take into consideration in the process of refactoring ABACUS project, especially `module_base`. An appropriate data structure improves the efficiency.

@Unboundwill Do you have any suggestions?

**Comment by wenfei-li** [comment]
According to our reconstruction plan, we do not want to put matrix diagonalization method as part of matrix class.
