### ISSUE TITLE
An unified interface to "dcopy" needed

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#673]
what dcopy does is simple : copies content from an array A into another array B. In ABACUS, this is realized in 3 places:
1. the dcopy_ interface to the BLAS subroutine dcopy_, in blas_connector.h;
2. the dcopy function defined in myfunc.h;
3. the ModuleBase::GlobalFunc:DCOPY function defined in global_function.h
Would it be better if we have a unified interface to do this job?

**Comment by mohanchen** [comment]
Yes, definitely. The 'dcopy' is a specific subroutine defined in BLAS, so I think it would be better to have another interface defined in module_base. For example, DCOPY in global_functional.h. In this regard, we can either use BLAS or other dcopy subroutines in DCOPY.

**Comment by wenfei-li** [comment]
> Yes, definitely. The 'dcopy' is a specific subroutine defined in BLAS, so I think it would be better to have another interface defined in module_base. For example, DCOPY in global_functional.h. In this regard, we can either use BLAS or other dcopy subroutines in DCOPY.

Sounds good!

**Comment by mohanchen** [comment]
Any plans or progress on this? @dyzheng

**Comment by dyzheng** [comment]
First, the current way for DCOPY are programmed with simple loops. 
During my testing, it is problematic.
If there is a array a[10], DCOPY(&a[0], &a[2], 5); would cause error that a[4] == a[2] == a[0].
In ABACUS code now, repeat from one array to another is correct, but this function is still not save enough.
In the refactor plan, we only need one function for this operation, and this function should pass all unittest.
If any coder want to add this operation for member function of his/her own class, he/she can use our DCOPY safely.

**Comment by wenfei-li** [comment]
It seems this issue is no longer relevant.
