### ISSUE TITLE
Rename the function `Diago_LCAO_Matrix::using_HPSEPS_complex` needed in LCAO line

### ISSUE THREAD

**Issue by maki49** [deepmodeling/abacus-develop#679]
The function `Diago_LCAO_Matrix::using_HPSEPS_complex` calls the subfunction`diago_complex_begin`, which
contains routines with both 2 solvers (ELPA and HPSEPS).
So, the name `using_HPSEPS_complex` is not conform with what it's doing, which makes it misleading.
Maybe it can be renamed such as "solve_eig_complex".

**Comment by mohanchen** [comment]
Agree, unless someone comes up with a better name.

**Comment by caic99** [comment]
The support of HPSEPS will be considered after our refactor finishes; hence, it's not necessary to change it in current codes.
