### ISSUE TITLE
excessive dimension for 2d format wave function in wfc_dm_2d

### ISSUE THREAD

**Issue by lyb9812** [deepmodeling/abacus-develop#692]
The dimensions of wfc_k and wfc_gamma in wfc_dm_2d are both (nks) x NLOCAL x NLOCAL. Actually, we only need (nks) x Nbands x NLOCAL.
We need to make some corresponding changes ( like redividing the new 2D format wave functions ) to reduce the size of the 2D format wave  functions.

**Comment by maki49** [comment]
#735 have optimizedw wfc_k into nks*NBANDS*NLOCAL. but wfc_gamma is still NLOCAL*NLOCAL because of elpa output. 
I suggest closing this and remaining #693 to ask for more details about elpa.
