### ISSUE TITLE
Dimensions of wave function coefficients in LCAO basis should be updated

### ISSUE THREAD

**Issue by lyb9812** [deepmodeling/abacus-develop#693]
The elpa function elpa_generalized_eigenvectors_d is used in pdiag_double to solve eigen wave functions. 
Is the dimension of the output Nbands x NLOCAL or NLOCAL x NLOCAL ?
Can the dimension of the wave function wfc_2d to store the output change from NLOCAL x NLOCAL to Nbands x NLOCAL ?

**Comment by mohanchen** [comment]
I think it is possible.

**Comment by maki49** [comment]
#735 have optimizedw wfc_k into nks\*NBANDS\*NLOCAL. but wfc_gamma is still NLOCAL*NLOCAL because of elpa output.

**Comment by caic99** [comment]
> #735 have optimizedw wfc_k into nks*NBANDS*NLOCAL. but wfc_gamma is still NLOCAL*NLOCAL because of elpa output.

Hi @maki49 , please be aware that the contents within two asterisk '*' will be interpreted as italic text in markdown grammar. I've fixed your comment(originally nks*NBANDS*NLOCAL).

**Comment by pxlxingliang** [comment]
we should keep the dimension of wfc_2d to be nlocal * nlocal, even though we solver only some bands, and this is the request of ELPA.
line72 https://gitlab.mpcdf.mpg.de/elpa/elpa/-/blob/master/src/elpa_impl_math_generalized_template.F90#L72

**Comment by caic99** [comment]
> we should keep the dimension of wfc_2d to be nlocal * nlocal, even though we solver only some bands, and this is the request of ELPA. line72 https://gitlab.mpcdf.mpg.de/elpa/elpa/-/blob/master/src/elpa_impl_math_generalized_template.F90#L72

This is similar to the requirements of scalapack routine.
