### ISSUE TITLE
Makefile-compiled ABACUS fails in some test cases

### ISSUE THREAD

**Issue by maki49** [deepmodeling/abacus-develop#707]
## Describe the Bug
branch: develop

On my workstation, Makefile-compiled ABACUS fails following tests, while cmake-compiled ABACUS passes all tests:
- `107_PW_OD_outputdos` : wrong result (occationally)
- `817_NO_LT_bcc` and `831_NO_GO_LT_bcc`:  segment fault at `Grid_MeshBall::init_meshball`

(Detailed report: [bug-report-3-Makefile.zip](https://github.com/deepmodeling/abacus-develop/files/8049602/bug-report-3-Makefile.zip))

## To Reproduce
```
cd source && make clean && make
cd ../tests/integrate/
vim Autotest.sh
(abacus_path=~/abacus-develop/bin/ABACUS.mpi)
(np=3)
./Autotest.sh
```
## Environment
- OS: ubuntu 16.04
- Compiler: OneAPI 2021.3.0

**Comment by maki49** [comment]
Another error occurd in #699 :
`207_NO_KP_OD` occationally fails on CI, while it never failed on my workstation.

**Comment by caic99** [comment]
Hi @maki49 ,

Currently we lack support of Makefile, while compiling by CMake is actively updated and covered by CI test. We are still not sure if we should keep both compiling method.



> Another error occurd in #699 : `207_NO_KP_OD` occationally fails on CI, while it never failed on my workstation.

For this issue, I've reported in #637 .
