### ISSUE TITLE
threshold for rho and grho in xc functionals

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#719]
I've noticed in potential_libxc.cpp that the threshold for rho and grho is only applied when nspin=2, and for GGA correlation:
```cpp
		// jiyy add for threshold
		const double rho_threshold = 1E-6;
		const double grho_threshold = 1E-10;
		// sgn for threshold mask
		std::vector<double> sgn( nrxx * nspin0(), 1.0);

		if(nspin0()==2 && func.info->family != XC_FAMILY_LDA && func.info->kind==XC_CORRELATION)
		{
			for( size_t ir=0; ir!=GlobalC::pw.nrxx; ++ir )
			{
					if ( rho[ir*2]<rho_threshold || sqrt(abs(sigma[ir*3]))<grho_threshold )
							sgn[ir*2] = 0.0;
					if ( rho[ir*2+1]<rho_threshold || sqrt(abs(sigma[ir*3+2]))<grho_threshold )
							sgn[ir*2+1] = 0.0;
			}
		}
```

Is there a specific reason for not applying the same threshold for other cases? (nspin = 1, GGA exchange, etc.)
Furthermore, this is not consistent with that in xc_gga_pw.cpp:
```cpp
	const double epsr = 1.0e-6;
	const double epsg = 1.0e-10;

	if(nspin0==1)
	{
		double segno;
		for(int ir=0; ir<GlobalC::pw.nrxx; ir++)
		{
			const double arho = std::abs( rhotmp1[ir] );
			h1[ir].x = h1[ir].y = h1[ir].z = 0.0;
			if(arho > epsr)
			{
				grho2a = gdr1[ir].norm2();
				if( grho2a > epsg )
				{
```
This is probably the reason why our results do not agree when using and not using LIBXC.

**Comment by mohanchen** [comment]
Thanks Wenfei! This is an important message! jiyy is short for ji yuyang, so probably this change was made by him without notifying others, @dyzheng could you ask him the reason for adding these parameters? In my opinion, we should fix this issue by using the same parameters.

**Comment by dyzheng** [comment]
Jiyy answered that "There was a problem with the magnetic material calculation at that time. He used a long time to find out that this truncation was needed after comparing it with the LIBXC interface in QE. If this truncation is not done, there will be strange values like energy or gradient coming out of the libxc function, resulting in incorrect results.  "
