### ISSUE TITLE
 there still exist some Chinese comments, which become messy code on linux 

### ISSUE THREAD

**Issue by maki49** [deepmodeling/abacus-develop#732]
at least following files have Chinese comments:
- berryphase.cpp
- unk_overlap_lcao.cpp, .h
- unk_overlap_lcao_pw.cpp
- abfs.cpp
- cal_r_overlap_R.cpp
- to_wannier90.h

**Comment by caic99** [comment]
Use regex `\p{sc=Han}` (in VS Code) to find all Chinese characters.
