### ISSUE TITLE
CUDA API failed with error

### ISSUE THREAD

**Issue by haxushu** [deepmodeling/abacus-develop#736]
## Describe the Bug

When running abacus-gpu version in abacus-develop/examples/01a_Si_diamond_pw_scf, the following message appears.
```bash
In File /root/abacus-develop/source/src_pw/hamilt_pw.cu : CUDA API failed at line 1558 with error: invalid argument (1)
```

It may be fixed like this:
```c++

	if(m == 1)
	{
		CHECK_CUDA(cudaFree(ps));
	}
```
    === To ==>
```c++
    if(m != 1)
	{
		CHECK_CUDA(cudaFree(ps));
	}
```

**Comment by caic99** [comment]
@haxushu Thank you for your report!
@Asuna981002 Would you look into it? In my opinion this patch is correct.
https://github.com/deepmodeling/abacus-develop/blob/bdd72564f80f3b3886786d41227f2776ba618478/source/src_pw/hamilt_pw.cu#L1556-L1559
