### ISSUE TITLE
PW CUDA version may be incompatible with LCAO 

### ISSUE THREAD

**Issue by haxushu** [deepmodeling/abacus-develop#737]
## Describe the Bug
When running abacus-gpu version in abacus-develop/examples/02a_Si_diamond_lcao_scf, the following message appears.
```bash
-------------------------------------------
 SELF-CONSISTENT : 
 -------------------------------------------
 nbx = 18
 nby = 18
 nbz = 18
 nbxx = 0
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 nbxx is <=0 !
 CHECK IN FILE : OUT.ABACUS/warning.log
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

PW CUDA version shows to be incompatible with LCAO, which may attribute to that divide_fft_grid() fails to be called.

**Comment by dyzheng** [comment]
ABACUS with LCAO base has not been optimized by CUDA, so please don't open USE_CUDA option for LCAO base calculation.
We will solve this problem in the future.

**Comment by mohanchen** [comment]
we have new GPU codes, the issue can be closed
