### ISSUE TITLE
How to build abacus-gpu version with make?

### ISSUE THREAD

**Issue by abacus-ustc** [deepmodeling/abacus-develop#739]

**Comment by caic99** [comment]
Hi @abacus-ustc ,
GPU supported version of abacus can only be built by CMake. Please refer to https://github.com/deepmodeling/abacus-develop/blob/develop/doc/install.md#configure . You can build abacus with `-DUSE_CUDA=1` flag.

Currently we are using CMake to solve dependencies in configuring step, and the support to Makefile is limited. CMake is our recommended method.

**Comment by dyzheng** [comment]
Can you try cmake on your machine and display the output when any error is reported? 
Maybe we can offer more constructive suggestions.

**Comment by abacus-ustc** [comment]
> Hi @abacus-ustc , GPU supported version of abacus can only be built by CMake. Please refer to https://github.com/deepmodeling/abacus-develop/blob/develop/doc/install.md#configure . You can build abacus with `-DUSE_CUDA=1` flag.
> 
> Currently we are using CMake to solve dependencies in configuring step, and the support to Makefile is limited. CMake is our recommended method.

As I know, the GPU version of abacus just works for PW basis. So I try to build abacus-gpu in src_pw/ directory.
The code is cloned from https://github.com/deepmodeling/abacus-develop.git
Environment is intel/2018.update3, intelmpi/2018.update3, mkl/2018.update3, cuda/11.6

In src_pw/, after running command
`cmake -B build -DUSE_CUDA=1  && cmake --build build` 
The following error message is reported，
[  1%] Building CXX object CMakeFiles/pw.dir/H_Ewald_pw.o
In file included from /home/nic/liuxiaoh/code/github/deepmodeling/v-fork/abacus-develop/source/src_pw/../module_base/global_function.h:12:0,
                 from /home/nic/liuxiaoh/code/github/deepmodeling/v-fork/abacus-develop/source/src_pw/H_Ewald_pw.h:4,
                 from /home/nic/liuxiaoh/code/github/deepmodeling/v-fork/abacus-develop/source/src_pw/H_Ewald_pw.cpp:1:
/opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/include/complex:53:3: error: #error "This Intel <complex> is for use only with the Intel C++ compilers!"
 # error "This Intel <complex> is for use only with the Intel C++ compilers!"
   ^~~~~
In file included from /home/nic/liuxiaoh/code/github/deepmodeling/v-fork/abacus-develop/source/src_pw/../src_parallel/ft.h:13:0,
                 from /home/nic/liuxiaoh/code/github/deepmodeling/v-fork/abacus-develop/source/src_pw/pw_basis.h:8,
                 from /home/nic/liuxiaoh/code/github/deepmodeling/v-fork/abacus-develop/source/src_pw/H_Ewald_pw.h:7,
                 from /home/nic/liuxiaoh/code/github/deepmodeling/v-fork/abacus-develop/source/src_pw/H_Ewald_pw.cpp:1:
/opt/fftw/3.3.8/intel/2018.update3/include/fftw3-mpi.h:51:10: fatal error: mpi.h: No such file or directory
 #include <mpi.h>
          ^~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/pw.dir/H_Ewald_pw.o] Error 1
gmake[1]: *** [CMakeFiles/pw.dir/all] Error 2
gmake: *** [all] Error 2

**Comment by caic99** [comment]
Hi @abacus-ustc ,
- You should execute `cmake` in the root path of project, i.e. `abacus-develop/`. Currently CMake does not support building single component of `abacus`.
- After that, please ensure your compilers used for CMake. You may assign compilers by environment variables, like `CXX=mpiicpc cmake ...`.
We will update our doc to explain the building procedure more precisely. Should you need further support, feel free to contact us.

**Comment by abacus-ustc** [comment]
> Hi @abacus-ustc ,
> 
> * You should execute `cmake` in the root path of project, i.e. `abacus-develop/`. Currently CMake does not support building single component of `abacus`.
> * After that, please ensure your compilers used for CMake. You may assign compilers by environment variables, like `CXX=mpiicpc cmake ...`.
>   We will update our doc to explain the building procedure more precisely. Should you need further support, feel free to contact us.

Thank you for your suggestion.
I change to build the program in the root path  i.e. `abacus-develop/`. And specify the path of each dependent package by 
`cmake -B build -DCereal_INCLUDE_DIR=$MyPathOfCereal -DELPA_LIBRARY=$MyPathOfElpaLib -DELPA_INCLUDE_DIR=$MyPathOfElpaInclude -DMPI_CXX_COMPILER=mpicc -DUSE_CUDA=1`
And assign compilers by environment variables,
`export CC=icc CXX=icpc`
Finally it works! Thanks!
