### ISSUE TITLE
k-point parallelism-related error in GPU version

### ISSUE THREAD

**Issue by LiuXiaohui123321** [deepmodeling/abacus-develop#741]
## Describe the Bug
When using multiple CPU cores (+ 1 GPU) to run the GPU version of abacus with 1x1x1 kpoint, it reports an error

>   nks == 0, some processor have no k point!

If I change to use 1 CPU core  (+ 1 GPU), it's ok.
I also try to use the same CPU cores to run CPU version of abacus, it's also ok.

**Comment by ddhhss** [comment]
The program only supports multi-k points parallelism, and you need to set MPI parameter np equal to 'npool'.

**Comment by LiuXiaohui123321** [comment]
> The program only supports multi-k points parallelism, and you need to set MPI parameter np equal to 'npool'.

And `npool` should be not larger than the number of k points?

**Comment by LiuXiaohui123321** [comment]
> The program only supports multi-k points parallelism, and you need to set MPI parameter np equal to 'npool'.

@Asuna981002 In GPU supported version of abacus, does `npool` must equal MPI parameter np?
In a calculation example, I use 8 CPU + 1 GPU cores to run a system with 2x2x2 k-points. `npool` is set as default value, i.e. 1.
After calculation, there is just one k-point diagonalization message in the output file running_scf.log.
![image](https://user-images.githubusercontent.com/25027983/155276681-6f4056bf-1fea-42a8-af1a-6bd8c879f64d.png)

Normally I think there should be 8 k-point diagonalization message, which is like the output of CPU version
![image](https://user-images.githubusercontent.com/25027983/155276743-d3faaa9b-fa66-4eba-a85a-c7cd4e4f278f.png)

**Comment by ddhhss** [comment]
You should set npool = 8 in INPUT file.
