### ISSUE TITLE
Update the executable file by Cmake after some modification

### ISSUE THREAD

**Issue by LiuXiaohui123321** [deepmodeling/abacus-develop#742]
How to update the executable file by Cmake after some modification on source code file?
Is there a more convenient way or I have to run `cmake -B ...` from the beginning?

**Comment by caic99** [comment]
> How to update the executable file by Cmake after some modification on source code file? Is there a more convenient way or I have to run `cmake -B ...` from the beginning?

Hi @LiuXiaohui123321 ,
You only need to run `cmake --build build` (the same as `cd build && make` if you are using Makefile). Please refer to [CMake tutorial](https://cmake.org/cmake/help/latest/manual/cmake.1.html#build-a-project). 
CMake uses GNU make for its backend by default: it generates Makefile for the project. Think of Makefile cases - just re-run
`make`.

**Comment by LiuXiaohui123321** [comment]
> > How to update the executable file by Cmake after some modification on source code file? Is there a more convenient way or I have to run `cmake -B ...` from the beginning?
> 
> Hi @LiuXiaohui123321 , You only need to run `cmake --build build` (the same as `cd build && make` if you are using Makefile). Please refer to [CMake tutorial](https://cmake.org/cmake/help/latest/manual/cmake.1.html#build-a-project). CMake uses GNU make for its backend by default: it generates Makefile for the project. Think of Makefile cases - just re-run `make`.

Got it! Thanks.
