### ISSUE TITLE
We lack a unit test for class Bspline in Module_base

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#748]
## Describe Current Status and Possible Solution

We lack a unit test for class Bspline in Module_base.

## Additional Context

Currently, this class is the application of methods in "J. Chem. Phys. 103, 8577 (1955)" to calculate structure factor. It is not used for B-spline interpolation.

**Comment by mohanchen** [comment]
What's the difficulty to add a unit test for class Bspline?
