### ISSUE TITLE
CMake compiler  Error

### ISSUE THREAD

**Issue by 13015339981** [deepmodeling/abacus-develop#750]
load env : intel-oneapi-compilers/2021.4.0     intel-oneapi-mpi/2021.4.0         intel-oneapi-mkl/2021.4.0
gnu compile is true , but intel-oneapi compile false. Is there a problem with the version?

CC=icc CXX=icpc FC=ifort COMMON_FLAGS="-std=c++11" cmake   ..

`/usr/include/c++/4.8.5/bits/stl_algobase.h(739): error: function "std::atomic<_Tp>::operator=(const std::atomic<_Tp> &) [with _Tp=Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Send]" (declared at line 170 of "/usr/include/c++/4.8.5/atomic") cannot be referenced -- it is a deleted function
  	*__first = __value;
  	         ^
          detected during:
            instantiation of "__gnu_cxx::__enable_if<<expression>, _OutputIterator>::__type std::__fill_n_a(_OutputIterator, _Size, const _Tp &) [with _OutputIterator=std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Send> *, _Size=std::size_t={unsigned long}, _Tp=std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Send>]" at line 786
            instantiation of "_OI std::fill_n(_OI, _Size, const _Tp &) [with _OI=std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Send> *, _Size=std::size_t={unsigned long}, _Tp=std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Send>]" at line 515 of "/usr/include/c++/4.8.5/bits/stl_uninitialized.h"
            instantiation of "void std::__uninitialized_default_n_1<true>::__uninit_default_n(_ForwardIterator, _Size) [with _ForwardIterator=std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Send> *, _Size=std::size_t={unsigned long}]" at line 544 of "/usr/include/c++/4.8.5/bits/stl_uninitialized.h"
            instantiation of "void std::__uninitialized_default_n(_ForwardIterator, _Size) [with _ForwardIterator=std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Send> *, _Size=std::size_t={unsigned long}]" at line 605 of "/usr/include/c++/4.8.5/bits/stl_uninitialized.h"
            instantiation of "void std::__uninitialized_default_n_a(_ForwardIterator, _Size, std::allocator<_Tp> &) [with _ForwardIterator=std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Send> *, _Size=std::size_t={unsigned long}, _Tp=std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Send>]" at line 1225 of "/usr/include/c++/4.8.5/bits/stl_vector.h"
            instantiation of "void std::vector<_Tp, _Alloc>::_M_default_initialize(std::vector<_Tp, _Alloc>::size_type={std::size_t={unsigned long}}) [with _Tp=std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Send>, _Alloc=std::allocator<std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Send>>]" at line 271 of "/usr/include/c++/4.8.5/bits/stl_vector.h"
            instantiation of "std::vector<_Tp, _Alloc>::vector(std::vector<_Tp, _Alloc>::size_type={std::size_t={unsigned long}}, const std::vector<_Tp, _Alloc>::allocator_type &) [with _Tp=std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Send>, _Alloc=std::allocator<std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Send>>]" at line 58 of "/lustre/home/acct-hpc/hpcsjw/abacus/abacus-develop/source/src_ri/exx_abfs-parallel-communicate-dm3-allreduce.cpp"

/usr/include/c++/4.8.5/bits/stl_algobase.h(739): error: function "std::atomic<_Tp>::operator=(const std::atomic<_Tp> &) [with _Tp=Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Recv]" (declared at line 170 of "/usr/include/c++/4.8.5/atomic") cannot be referenced -- it is a deleted function
  	*__first = __value;
  	         ^
          detected during:
            instantiation of "__gnu_cxx::__enable_if<<expression>, _OutputIterator>::__type std::__fill_n_a(_OutputIterator, _Size, const _Tp &) [with _OutputIterator=std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Recv> *, _Size=std::size_t={unsigned long}, _Tp=std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Recv>]" at line 786
            instantiation of "_OI std::fill_n(_OI, _Size, const _Tp &) [with _OI=std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Recv> *, _Size=std::size_t={unsigned long}, _Tp=std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Recv>]" at line 515 of "/usr/include/c++/4.8.5/bits/stl_uninitialized.h"
            instantiation of "void std::__uninitialized_default_n_1<true>::__uninit_default_n(_ForwardIterator, _Size) [with _ForwardIterator=std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Recv> *, _Size=std::size_t={unsigned long}]" at line 544 of "/usr/include/c++/4.8.5/bits/stl_uninitialized.h"
            instantiation of "void std::__uninitialized_default_n(_ForwardIterator, _Size) [with _ForwardIterator=std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Recv> *, _Size=std::size_t={unsigned long}]" at line 605 of "/usr/include/c++/4.8.5/bits/stl_uninitialized.h"
            instantiation of "void std::__uninitialized_default_n_a(_ForwardIterator, _Size, std::allocator<_Tp> &) [with _ForwardIterator=std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Recv> *, _Size=std::size_t={unsigned long}, _Tp=std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Recv>]" at line 1225 of "/usr/include/c++/4.8.5/bits/stl_vector.h"
            instantiation of "void std::vector<_Tp, _Alloc>::_M_default_initialize(std::vector<_Tp, _Alloc>::size_type={std::size_t={unsigned long}}) [with _Tp=std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Recv>, _Alloc=std::allocator<std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Recv>>]" at line 271 of "/usr/include/c++/4.8.5/bits/stl_vector.h"
            instantiation of "std::vector<_Tp, _Alloc>::vector(std::vector<_Tp, _Alloc>::size_type={std::size_t={unsigned long}}, const std::vector<_Tp, _Alloc>::allocator_type &) [with _Tp=std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Recv>, _Alloc=std::allocator<std::atomic<Exx_Abfs::Parallel::Communicate::DM3::Allreduce::Flag_Recv>>]" at line 59 of "/lustre/home/acct-hpc/hpcsjw/abacus/abacus-develop/source/src_ri/exx_abfs-parallel-communicate-dm3-allreduce.cpp"

compilation aborted for /lustre/home/acct-hpc/hpcsjw/abacus/abacus-develop/source/src_ri/exx_abfs-parallel-communicate-dm3-allreduce.cpp (code 2)
gmake[2]: *** [source/src_ri/CMakeFiles/ri.dir/exx_abfs-parallel-communicate-dm3-allreduce.cpp.o] Error 2
gmake[2]: *** Waiting for unfinished jobs....
[ 36%] Building CXX object source/src_ions/CMakeFiles/ions.dir/variable_cell.cpp.o
[ 36%] Building CXX object source/src_lcao/CMakeFiles/lcao.dir/DM_gamma.cpp.o
[ 36%] Building CXX object source/src_lcao/CMakeFiles/lcao.dir/DM_k.cpp.o
[ 37%] Building CXX object source/src_lcao/CMakeFiles/lcao.dir/ELEC_cbands_gamma.cpp.o
[ 37%] Building CXX object source/src_io/CMakeFiles/io.dir/read_dm.cpp.o
[ 37%] Building CXX object source/src_io/CMakeFiles/io.dir/read_rho.cpp.o
[ 37%] Building CXX object source/src_io/CMakeFiles/io.dir/read_txt_tools.cpp.o
gmake[1]: *** [source/src_ri/CMakeFiles/ri.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
`

**Comment by caic99** [comment]
Hi @13015339981 ,
You may update your `gcc` version. See [GCC* Compatibility and Interoperability](https://www.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compatibility-and-portability/gcc-compatibility-and-interoperability.html) for more details.

**Comment by 13015339981** [comment]
hello, i use gcc to compile normally, i want to try intel compiler, do you have any good suggestions
I try:
' CC=icc CXX=icpc FC=ifort COMMON_FLAGS="-std=c++11" cmake .. ' is Error

**Comment by caic99** [comment]
> hello, i use gcc to compile normally, i want to try intel compiler, do you have any good suggestions I try: ' CC=icc CXX=icpc FC=ifort COMMON_FLAGS="-std=c++11" cmake .. ' is Error

Hi @13015339981 ,
intel compilers rely on `gcc` components. You may read my reply before for further details.

**Comment by 13015339981** [comment]
thanks, I listened to your suggestion and increased the gcc version to 8.3, and the operation was successful
