### ISSUE TITLE
`set_matrix_grid()` function should be placed in ion-step rather than elec-step

### ISSUE THREAD

**Issue by maki49** [deepmodeling/abacus-develop#754]
https://github.com/deepmodeling/abacus-develop/blob/eeb8cc7c7e1739a582efd79441ee3afec55a96f8/source/src_lcao/LOOP_elec.h#L20

This function do such things: 
- search adjacent atoms 
- set periodic condition
- prepare grid division (2d-divsion has been moved out to ORB_control)
- allocate H(R), S(R)

All it need is cell and atom information, but not electronic state. So I think it should be moved into class `LOOP_ions` and called before `LOE.solve_elec_stru()`.

**Comment by wenfei-li** [comment]
it seems this issue is now resolved; set_matrix_grid is now called in function 'beforescf', which is called once per ion step
