### ISSUE TITLE
The rounding error in Gram-Schmidt orthogonalization

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#757]
I found there has the rounding error in Gram-Schmidt orthogonalization.
I designed a series of basis functions $$f_n(x)=x^{n+1}$$ (n >= 0), and do Gram-Schmidt orthogonalization by using class Gram_Schmidt_Orth<Func_Type,R_Type>::Gram_Schmidt_Orth, and got the new  orthogonalization  basis. I then calculated the inner product of each two new basis to verify the orthogonality. The bad result is that there has inner product is much larger than 0, even the basis number is just only 10. This means the orthogonalization  is unsuccessful.
The improved methods are CGS2/CGS3 algorithm (Rounding error analysis of the classical Gram-Schmidt orthogonalization process), or multiple using the Gram-Schmidt orthogonalization. 
![image](https://user-images.githubusercontent.com/91927439/155918156-eb9b8992-b246-403c-8307-0d82b79d98ee.png)
The FeiShu link:  https://dptechnology.feishu.cn/docs/doccnENWCIWeqMYB8zu9OjaKg0e#

**Comment by mohanchen** [comment]
@pxlxingliang has new results?

**Comment by pxlxingliang** [comment]
After communicate with Peize Lin, we think we should use the CGS2 algorithm, which can orthogonalize 50 nbasis successfully. In ABACUS, we apply the  orthogonalization on the basis of one orbital of one element, and the basis number is  not too big, a CGS2 algorithm is enough. Such as for Pt, the maximum basis number is just only 23.
