### ISSUE TITLE
Dipole correction for energy and potential

### ISSUE THREAD

**Issue by sunml99** [deepmodeling/abacus-develop#760]
## Background
In the simulation of the slab model, a vacuum layer needs to be added to isolate the interaction between the two repetitions. A dipole moment is created because of the slab’s asymmetry, and the electrostatic potentials of the slab’s upper and lower sides are different.
The periodic boundary condition imposed on the electrostatic potential then gives rise to an artificial electric field across the slab. This has an impact on the total energy and potential of the system.
It is desirable to offset the effect of the artificial electric field by using a dipole correction.

## Additional context
In addition to the system energy, the work-function for asymmetric slabs can also be evaluated by dipole correction.
Ideally, the work function in the vacuum layer should be a constant value. But if the two sides of the surface are not symmetrical, the work function in the vacuum will be a diagonal line. After the dipole correction, there will be a step in the work function. Then we can get the vacuum energy level of the lower and upper sides.

**Comment by mohanchen** [comment]
We will plan this.
