### ISSUE TITLE
refactor md input parameters

### ISSUE THREAD

**Issue by YuLiu98** [deepmodeling/abacus-develop#763]
The MD input parameters need to be refactored, the details are reported as follows:

1) `md_mdtype`  ->  `md_type` : control the ensemble to run md;
2) `md_potential`  ->  `md_ensolver` : choose the energy solver for MD;
3) `md_rstmd`  ->  `md_restart` : control whether restart md;
4) `md_dt`  ->  `md_dt` : time step(fs) used in md simulation;
5) `md_tfirst`  ->  `md_tfirst` : initial MD temperature;
6) `md_tlast`  ->  `md_tlast` : final MD temperature;
7) `md_dumpfred`  ->  `md_dumpfreq` : the frequence to dump md information;
8) `md_rstfred`  ->  `md_restartfreq` : the frequence to output restart information;
9) `md_tfreq`  ->  `md_tfreq` : Oscillation frequency, used to determine Qmass of NHC, or 1/(md_tfreq*md_dt) is collision probability in Anderson method;
10) `mnhc`  ->  `md_mnhc` : Number of Nose-Hoover chains;
11) `rcut_lj`  ->  `lj_rcut` : Cut-off radius for Leonard Jones potential (angstrom);
12) `epsilon_lj`  ->  `lj_epsilon` : The value of epsilon for Leonard Jones potential (eV);
13) `sigma_lj`  ->  `lj_sigma` : The value of sigma for Leonard Jones potential (angstrom);
14) `md_qmass`  ->  `msst_qmass` : Inertia of extended system variable for MSST;
15) `direction`  ->  `msst_direction` : the direction of shock wave for MSST;
16) `velocity`  ->  `msst_vel` : the velocity of shock wave (\AA/fs);
17) `viscosity`  ->  `msst_vis` : artificial viscosity (mass/length/time) for MSST;
18) `tscale`  ->  `msst_tscale` : reduction in initial temperature (0~1) used to compress volume in MSST;
19) `damp`  ->  `md_damp` : damping parameter (fs) used to add force in Langevin method.

**Comment by caic99** [comment]
Hi @YuLiu98 ,
I'm wondering if it's a change on input variable's name, or also its type, algorithm, and so on?

**Comment by YuLiu98** [comment]
> I'm wondering if it's a change on input variable's name, or also its type, algorithm, and so on?

Just a change on input variable's name.
