### ISSUE TITLE
Finding unused, repeated codes in module_base, should we delete them now?

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#765]
## Describe Current Status and Possible Solution

We find many unused, repeated codes in module_base during unit testing.

The following files are not called at all:
random.h
sph_bessel.h & .cpp
polint.h & .cpp
integral.h & .cpp

The following files contain functions not called:
mymath.h: simpson, my_erf, my_erfc, gauss_freq

**Comment by caic99** [comment]
I suggest removing all unused codes, and renaming functions with a ill-defined name, for example some functions starting with `my`.

**Comment by mohanchen** [comment]
ok

**Comment by hongriTianqi** [comment]
These files are still available:
random.h
sph_bessel.h & .cpp
polint.h & .cpp
integral.h & .cpp

**Comment by wenfei-li** [comment]
@hongriTianqi Is this issue be considered resolved? If so please close it.

**Comment by mohanchen** [comment]
I will close it.
