### ISSUE TITLE
A little Numerical differences branch develop now with ABACUS 2.1.0 version

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#766]
## Describe the Bug
I received feedback from users Yuyang Ji and Xiaohui Liu that result from the current version of the program do not exactly agree with result from ABACUS version 2.1.0.
They want to know if there have been some bugs fixed in recent codes.

## To Reproduce
I have not tested these two cases, but I also want to know which parts lead to the discrepancy mentioned by users.

Xiaohui Liu's Inputs are:
[checkElpa.tar.gz](https://github.com/deepmodeling/abacus-develop/files/8167232/checkElpa.tar.gz)
Yuyang Ji's Inputs are:
[LiF.zip](https://github.com/deepmodeling/abacus-develop/files/8167234/LiF.zip)

**Comment by mohanchen** [comment]
1) I suggest using those tagged versions for the test. 2) You should encourage them to submit the issues by themselves, again submitting the issue for them is a waste of your time and do no good for Ji Yuyang and Xiaohui Liu. 3) We should always consider whether the bug report examples should be included in the integrate tests.

**Comment by wenfei-li** [comment]
Does this have something to do with the update in XC functional parameters?

**Comment by dyzheng** [comment]
This issue can be close now.
The reason for numerical differences comes from two changes:
1. nonlocal pseudopotential in Hamiltonian for gamma_only=1 case has bug before, now it is fixed to same as gamma_only=0 case.
2. XC functional parameters has updated for higher precision.
