### ISSUE TITLE
Ewald code need to be tested independently.

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#767]
## Describe the Bug
Xiaohui Liu has reported that a MoS2 system would cause error energy for ewald term. 
Inputs of his case is :
[Ewald_MoS2.zip](https://github.com/deepmodeling/abacus-develop/files/8167395/Ewald_MoS2.zip)
The problem for me to test this case is the case is too large to test.
Maybe we should refactor the ewald part code first to test this problem.

**Comment by mohanchen** [comment]
refactor the ewald is possible but the priority is not high

**Comment by wenfei-li** [comment]
Has this issue been resolved? Is there another smaller case where Ewald fails? @dyzheng

**Comment by wenfei-li** [comment]
Has this case been tested against quantum espresso? What was the reference value?

**Comment by mohanchen** [comment]
Xiaohui report this has been fixed.
