### ISSUE TITLE
Serial version not work in some scenes

### ISSUE THREAD

**Issue by lyb9812** [deepmodeling/abacus-develop#771]
The serial version now doesn't work for gamma_only and may not work for Nspin=4.
The results for pw tests are not exactly the reference values.

TDDFT branch 
Ubuntu 18.04.   OneAPI 2021.3.0

compile : 
1. change HONG in Makefile to serial version
2. delete exx related files in Makefile.Objects
3. make fp

test:
PW cases can work, but give different results compared with reference.
LCAO cases need to change the default ks_solver from "genelpa" to "lapack". I only test a few cases now. 201，220 can give the same result as the reference. Gamma-only case 320 cannot work. I haven't change NSPIN=4 related codes yet so it may don't work as well .

**Comment by caic99** [comment]
Hi @lyb9812 ,
Thank you for your feedback. Will you provide further information for us, like the environment, compiling args, and the case?

**Comment by wenfei-li** [comment]
One reason is that the diagonalization subroutine is not working, as mentioned in #661 .

**Comment by mohanchen** [comment]
see also https://github.com/deepmodeling/abacus-develop/issues/709#issuecomment-1517764399
