### ISSUE TITLE
I will add the UTs for global_functions in module_base

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#777]
## Background
ABACUS lack UT for global_functions in module_base.

## Describe the solution you'd like
We should add UT for global_functions in module_base

**Comment by mohanchen** [comment]
Adding UTs seem to be the right thing to do. If you can do it, just do it. If you cannot do it, I don't see an issue here.

**Comment by mohanchen** [comment]
OK, I see a pull request. Next time, you can mention who will do this job and I will not comment.

**Comment by hongriTianqi** [comment]
sorry, this is just the routine thing to link a PR with an issue.发自我的手机-------- 原始邮件 --------发件人： Mohan Chen ***@***.***>日期： 2022年3月6日周日 上午9:24收件人： deepmodeling/abacus-develop ***@***.***>抄送： hongriTianqi ***@***.***>, Author ***@***.***>主    题： Re: [deepmodeling/abacus-develop] ABACUS lacks UT for global_functions in module_base (Issue #777)
Adding UTs seem to be the right thing to do. If you can do it, just do it. If you cannot do it, I don't see an issue here.

**Comment by mohanchen** [comment]
> sorry, this is just the routine thing to link a PR with an issue.

I see, next time you may add "I will add the UTs."
