### ISSUE TITLE
grid_base seems no longer used

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#790]
Grid_base is not used and it seems it has already been replaced by grid_base_beta. Are we considering removing grid_base.cpp and grid_base.h

**Comment by wenfei-li** [comment]
actually grid_base_beta is not used either, since the old method for calculating ylm has been replaced

**Comment by wenfei-li** [comment]
actually the only part used in grid_base_beta is vfactor, which is used for calculating vldr3 by Gint_Gamma. I think we might as well move vfactor into Gint_Gamma and remove grid_base_beta too.

**Comment by caic99** [comment]
Hi @wenfei-li ,
I think it would be an improvement removing redundant code if you think it is OK to do so. And don't forget to assign a proper file name.

**Comment by mohanchen** [comment]
I don't know the current state of Grid_base...

**Comment by wenfei-li** [comment]
> I don't know the current state of Grid_base...

I have been producing a short note on the Grid_Technique class, I think I'll be able to finish it within this week.

**Comment by wenfei-li** [comment]
> Hi @wenfei-li , I think it would be an improvement removing redundant code if you think it is OK to do so. And don't forget to assign a proper file name.

Sure I'll have a look at the code.
