### ISSUE TITLE
Can `gamma_only` algorithm deal with soc ?

### ISSUE THREAD

**Issue by maki49** [deepmodeling/abacus-develop#795]
Now if we run an `nspin =4` case with `gamma_only=1`, ABACUS will report error like this:
![image](https://user-images.githubusercontent.com/33978601/158750422-2fb2ad3b-8dba-4859-b7c1-1ad25d5d9056.png)

I want to know whether it's impossible for gamma_only to deal with soc in term of algorithm, or just because ABACUS haven't implemented it yet.

@dyzheng

**Comment by jinxin68** [comment]
Accurate charge density is required when considering SOC . So abacus does not support using gamma_only when considering SOC .

**Comment by dyzheng** [comment]
It is no problem in theory for SOC or nonlinear spin in gamma_only, but in general , user will not use only gamma point for system which need to evaluate SOC effect. 
If @maki49  have this demand, please set gamma_only as 0 and use gamma point in KPT file.

**Comment by wenfei-li** [comment]
It seems this issue has been resolved.
