### ISSUE TITLE
ELPA takes more computational time than before

### ISSUE THREAD

**Issue by sgyang345** [deepmodeling/abacus-develop#798]
## Describe the Bug
The latest development version seems to have taken nearly 1.5 times more computational time.

## To Reproduce
1. clone the source code from “https://github.com/abacusmodeling/abacus-develop”
2. run ABACUS with intel 2020 mpirun

## Environment
- OS: CentOS Linux release 7.9.2009 (Core)
- Compiler Intel 2020

## Additional Context
1. The latest development version seems to have taken nearly 1.5 times more computational time.
2. Something wrong with the BAND.dat： After the energy band is calculated, the first energy band seems to become linear data. (Similar to K-point but not K-point, this data seems superfluous.)
[nscf_wrong_with_BAND.zip](https://github.com/deepmodeling/abacus-develop/files/8310482/nscf_wrong_with_BAND.zip)

**Comment by dyzheng** [comment]
This problem comes from the interface of ELPA, before 2021/09/26, ABACUS only use ELPA_2016_version. 
Now, ABACUS use ELPA_2021_version but the code of new interface has not been fully optimized.
As far as I know, Dr. Yu Shen and Dr. Xiaohui Liu are working for solve that. 
Please wait for the progress~

**Comment by hongriTianqi** [comment]
> Something wrong with the BAND.dat： After the energy band is calculated, the first energy band seems to become linear data. (Similar to K-point but not K-point, this data seems superfluous.)

@sgyang345 
For the file BAND.dat, the firt column is just the order of k-points from 1, 2, to nkpt; the second column is the absolute k line distance; the third column is the first energy band. I think the first line is useful in finding the positions of high symmetry points, so left them as is. If you want, please check PR 571 [https://github.com/deepmodeling/abacus-develop/pull/571](url) and Issue 551 [https://github.com/deepmodeling/abacus-develop/issues/551](url)
