### ISSUE TITLE
Makefile-Compile problem for new modules

### ISSUE THREAD

**Issue by maki49** [deepmodeling/abacus-develop#869]
Shell we maintain Makefiles for new modules such as HSolver？
Some files in `module_hsolver/` now have the same name as files in `src_pw/` , such as `diago_cg.cpp`, so I failed to add `diago_cg.o` in `Makefile.Objects` because of redefination.

**Comment by dyzheng** [comment]
HSolver module is not working in ABACUS now, only UT for this new module for verifying the behavier of this new module.
In the future, the HSolver module will replace the old files, such as diago_cg.cpp.
So makefile.Object should not support files in HSolver module now.
