### ISSUE TITLE
some details about 2D-block data structure in LCAO are needed

### ISSUE THREAD

**Issue by maki49** [deepmodeling/abacus-develop#870]
I see 2 structures of 2D-block matrix `LocalMatrix<T>` and `MatrixBlock` in the new `module_hamilt`. 
Maybe more details are needed to tell developers about how to use the two data structure, what they're doing, and what's the relation of the two (maybe the former contains the latter)? 
And shell we use `MatrixBlock` for 2D-block wavefunction in `module_psi` too ?

**Comment by mohanchen** [comment]
@dyzheng could you answer the question?

**Comment by dyzheng** [comment]
HamiltLCAO class is unfinished.
The MatrixBlock<T> is designed for packing matrix data with its rows and columns and descriptors for parallel.
The LocalMatrix<T> is designed for :
1. union Hamiltonian matrix and overlap matrix.
2. union gamma_only and multi-k code.
I recognize first aim for LocalMatrix is not necessary , and I also plan to use one class to replace both MatrixBlock and LocalMatrix. 
If anyone has good idea for that, please tell me what you think.
Thank you for your attention of these ongoing code, I will continue to evolve them to achieve our design goals and eventually replace the old code.

**Comment by wenfei-li** [comment]
It seems this issue has been resolved.
