### ISSUE TITLE
Modification of grid integration code

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#882]
## Describe Current Status and Possible Solution

The current grid integration code has a few problems, making the code structure messy and not quite efficient:
1. the conversion of density matrix from 2D-block to grid format requires lots of additional memory and can cause program failure for large systems. Possible solution is to break the alltoallv operation to a series of send/recv with mpi user-defined datatype.
2. the current realization of force and stress multiplies density matrix in the end, which is not the most efficient way. #880 provides an alternative solution.
3. there are lots of repetitive codes, they will be put together into unified interfaces.

Furthermore, there is one thing that we could do, but is not in urgent need:
To realize the computation of kinetic energy density, this way we can implement mGGA functional for LCAO.

**Comment by mohanchen** [comment]
Excellent findings!
