### ISSUE TITLE
abacus reads orbital files during reading STRU file

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#883]
## Describe Current Status and Possible Solution

This mainly hampers the codes' readability. Separating codes reading STRU file with that reading orbital files may be better.

## Additional Context

This happens in the file module_cell/read_atoms.cpp and the function UnitCell_pseudo::read_atom_positions(), specifically line 434-520.

**Comment by wenfei-li** [comment]
we will consider this during the refactor of ucell class
