### ISSUE TITLE
No non-MPI support when reading wavefunctions in LCAO gamma only calculation

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#885]
## Background
This will result in failure of non-MPI code when users want to read wavefunctions in LCAO gamma only calculation.

## Describe the solution you'd like
This is so because the function WF_Local::distri_lowf_new () at line 313 in src_io/wf_local.cpp has no non-MPI codes. The above function is called by WF_local::read_lowf() at line 316 when reading LOWF files. The non-MPI codes should be added to support non-MPI abacus.

**Comment by mohanchen** [comment]
Hi Tianqi, thanks for the report! Do you think you will be able to provide these non-MPI codes? @hongriTianqi

**Comment by hongriTianqi** [comment]
Dear Chen, this issue has just been addressed along with my above PR. Thanks. @mohanchen
