### ISSUE TITLE
Openmp result differs in LCAO cases

### ISSUE THREAD

**Issue by Qianruipku** [deepmodeling/abacus-develop#886]
## Describe the Bug
When we use openmp (OMP_NUM_THREADS not equal to 1), the LCAO results are different.
For example of 830_NO_GO_LT_fcc:
![ASjZztm928](https://user-images.githubusercontent.com/76200646/166099397-74b758c6-138b-4e66-8c80-36d86955b135.png)
![eZUMtncmvd](https://user-images.githubusercontent.com/76200646/166099398-a7aa88aa-b146-4eee-9bdd-34d108f8a052.png)
![97w2lbBQ7A](https://user-images.githubusercontent.com/76200646/166099405-f09a46eb-7818-4383-8c83-e5590c137527.png)
Worse still,  sometimes segmental fault may occur in 830_NO_GO_LT_fcc!

## To Reproduce
1. [e.g. clone the source code from ...]
2. [e.g. configure CMake with options ...]
3. [e.g. build ABACUS with ...]
4. [e.g. run ABACUS with ...]
It is recommended to attach your calculation case here for the developers to reproduce the bug.

## Environment
- OS: [e.g. Ubuntu 20.04]
- Compiler: [e.g. gcc 5.1.0]
- Dependencies: [e.g. Intel MKL, OpenBLAS]

**Comment by Qianruipku** [comment]
For test 211_NO_S2_elec_add，if we use "export OMP_NUM_THREADS=1" or "export OMP_NUM_THREADS=2".
The test cannot be passed. 
![image](https://user-images.githubusercontent.com/76200646/166104740-5c31064e-0a1a-462e-8760-69926b5e85fe.png)
 OMP_NUM_THREADS = 4 can pass the test.
![image](https://user-images.githubusercontent.com/76200646/166104922-6d659955-742d-4719-8dc4-a380ed623ad6.png)
It means the results of different OMP_NUM_THREADS are different.

**Comment by dyzheng** [comment]
Test the Gamma_only cases:
    modify: tests/integrate/Autotest.sh: line12 ' case="^[^#].\*\_GO\_ .\*$" ' and set correct abacus path in line4,
    run Autotest.sh dozens of times and check if any case failed.

**Comment by dyzheng** [comment]
Can you give more information about your top three graphs? @Qianruipku

**Comment by Qianruipku** [comment]
cd 830_NO_GO_LT_fcc
export OMP_NUM_THREADS=4
../../../build/abacus
(get figure 1)
../../../build/abacus
(get figure 2)
../../../build/abacus
(get figure 3)

**Comment by caic99** [comment]
Using `OMP_NUM_THREADS=4 mpirun -n 4 abacus`, I got the following result:
```
 ITER   TMAG      AMAG      ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
 GE1    -4.77e-14 4.78e-14  -2.037124e+02  0.000000e+00   1.247e-01  2.164e-01  
 GE2    -2.19e-13 2.20e-13  -2.037347e+02  -2.231557e-02  3.101e-02  2.096e-01  
 GE3    -1.15e-12 1.15e-12  -2.037348e+02  -3.447545e-05  8.795e-03  2.082e-01  
 GE4    -5.22e-12 5.22e-12  -2.037348e+02  1.445857e-05   2.591e-03  2.071e-01  
···
 GE25   -2.50e-01 2.55e-01  -2.037509e+02  -3.757284e-06  3.298e-04  2.144e-01  
···(TMAG & AMAG converged)
 GE42   -2.50e-01 2.55e-01  -2.037509e+02  1.691800e-13   6.333e-10  2.079e-01  
```

For `OMP_NUM_THREADS=1 mpirun -n 4 abacus`, TMAG & AMAG output is always 0.
@dyzheng Could you take a look at this?

**Comment by dyzheng** [comment]
In collinear spin calculation for LCAO base, initial magnetization should not be 0, which would cause Hamiltonian of spin-up and spin-down always be same. The convergent state is not the real fundamental state.
In this issue, OMP_NUM_THREADS>1 would introduce a little digital error in "Gint" procedure, which lead to real fundamental state.
I will fix this test case and add warnings in ABACUS.

**Comment by pxlxingliang** [comment]
I have run 830_NO_GO_LT_fcc with OMP_NUM_THREADS=1 and 4 by using the lastest develop codes. The energy of later case is different in multiple repeat runnings, while the former one is always same.

The enegies of 4 repeat runnings with command: OMP_NUM_THREADS=1 mpirun -np 2 abacus are same:
!FINAL_ETOT_IS -32.8385790451128017 eV

The energies of 4 repeat runnings with command: OMP_NUM_THREADS=4 mpirun -np 2 abacus:
!FINAL_ETOT_IS -32.8385790451128514 eV
!FINAL_ETOT_IS -32.8385790451128727 eV
!FINAL_ETOT_IS -32.8385790451128798 eV
!FINAL_ETOT_IS -32.8385790451127946 eV
There has the difference of 1e-14 eV.
