### ISSUE TITLE
Calculate the H2 molecule with the LDA functional and the corresponding pseudopotential: error feedback

### ISSUE THREAD

**Issue by HeFuxiang94** [deepmodeling/abacus-develop#895]
## Describe the Bug
The bug may results in:
- abnormal interruption of the program,

## Expected behavior
- able to operate normally
[H2_lda.zip](https://github.com/deepmodeling/abacus-develop/files/8638502/H2_lda.zip)
.

## To Reproduce
1. clone the source code from develop branch, and compile,
2. Download from abacus website [Traditional_PP_Orb.zip](http://abacus.ustc.edu.cn/uploadfile/Traditional_PP_Orb.zip),
3. run ABACUS scf calcualtion with H_lda_8.0au_50Ry_2s1p and H.pz-vbc.UPF
It is recommended to attach your calculation case here for the developers to reproduce the bug.

## Error message
./module_orbital/ORB_gen_tables.cpp:143: void ORB_gen_tables::snap_psibeta_half(const LCAO_Orbitals &, const InfoNonlocal &, std::vector<std::vector<double, std::allocator<double>>, std::allocator<std::vector<double, std::allocator<double>>>> &, const ModuleBase::Vector3<double> &, const int &, const int &, const int &, const int &, const ModuleBase::Vector3<double> &, const int &, const bool &) const: Assertion `nproj>0' failed.

**Comment by maki49** [comment]
I reproduced this error. No problem when using `H_ONCV_PBE-1.0.upf` .
I don't know how to deal with pseudopotential without projectors.... Maybe @wenfei-li can help?

**Comment by dyzheng** [comment]
H only system is sometimes special that it has not projectors. In this case, non-local part should be ignored.
