### ISSUE TITLE
calculate force error for Si512 system

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#901]
## Describe the Bug
I want to calculate the force of the si512 system by using current develop version, but it  is abnormal end. It seems a memory problem. 

the commit number: 0d2bbd1fad7bcbaf3dd72f85c0e394801265f611

[si512-force.zip](https://github.com/deepmodeling/abacus-develop/files/8644673/si512-force.zip)

**Comment by caic99** [comment]
Hi @pxlxingliang ,
Thank you for your report!
Would you provide more information(like the terminating position, the environment you used) to help us locate the problem?
If possible, you can compile ABACUS with `ENABLE_ASAN` flag, and run the program to locate possible memory errors.
Thanks again!

**Comment by pxlxingliang** [comment]
@caic99 
This time, I load the docker image of ABACUS, which can compile ABACUS with GNU, and run this example, it exits before doing SCF.
The error information is like below:

![image](https://user-images.githubusercontent.com/91927439/167537229-0ab48176-39b0-48c0-a7b1-24d284ecd768.png)

![image](https://user-images.githubusercontent.com/91927439/167537187-085922f5-431b-413a-8d85-c487ea4d3add.png)

**Comment by pxlxingliang** [comment]
I have recomfirmed the problem, it is an "out of memory" issue. After the abnormal exist, run command `dmesg|grep oom` can get the message:
![image](https://user-images.githubusercontent.com/91927439/171526615-642d65ea-38c7-4e9d-9210-b44e2b9861d7.png)

It should be the problem of my mathine which do not has enough memory, and it run the previous versions (e.g. 2022-3) have the same error.
