### ISSUE TITLE
Non-zero off-diagonal elements of `PP_DIJ` in pseudopotential should be supported.

### ISSUE THREAD

**Issue by sunliang98** [deepmodeling/abacus-develop#916]
## Describe the Bug
The restriction that the off-diagonal elements of `DIJ` (`Pseudopot_upf::dion`) must be zero has been released in [pr910](https://github.com/deepmodeling/abacus-develop/pull/910). However, ABACUS currently only uses diagonal elements for computation, so further updates are needed.

## Expected behavior
Add the support to the non-zero off-diagonal elements of `PP_DIJ` in pseudopotential.

## To Reproduce
The pseudopotential in [test.zip](https://github.com/deepmodeling/abacus-develop/files/8684440/test.zip) has non-zero off-diagonal elements in `PP_DIJ`.

**Comment by wenfei-li** [comment]
@dyzheng Is this issue resolved? If so please close it.

**Comment by wenfei-li** [comment]
the new nonlocal part now supports such calculations. we should find a time to implement this

**Comment by mohanchen** [comment]
LCAO case has not been supported yet, need pseudopotentials and the corresponding LCAO orbitals.

**Comment by hongriTianqi** [comment]
- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team and stakeholders on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by hongriTianqi** [comment]
@dyzheng Is this issue resolved? If so please close it.

**Comment by hongriTianqi** [comment]
@dyzheng Will need tests.

**Comment by dyzheng** [comment]
This bug occurred again with GTH LCAO calculation, I will fix it.
