### ISSUE TITLE
MD was stuck at the 65th step

### ISSUE THREAD

**Issue by Chentao168** [deepmodeling/abacus-develop#932]
## Describe the Bug
MD was stuck at the 65th step. 
![image](https://user-images.githubusercontent.com/76426373/169641901-c67dd2ed-e59a-4198-95db-0b328d26140e.png)
![origin_img_v2_bfcceffc-9c20-47ee-b087-1c16bbbc036g](https://user-images.githubusercontent.com/76426373/169641526-50d2210c-4a60-4ba3-ab1a-672ae31d9d92.png)
@YuLiu98 thinks it was stuck at the function cal_force_nl(forcenl)

## To Reproduce
The source code: https://github.com/deepmodeling/abacus-develop/tree/SDFT
My calculation case: [chentao_bug.zip](https://github.com/deepmodeling/abacus-develop/files/8747204/chentao_bug.zip)

## Environment
- OS: Beijing Super Cloud Computing Center
- Compiler: Intel 2022.1

**Comment by caic99** [comment]
Hi @Chentao168 ,
You can try using `gdb` to attach to the stuck process and pause it to locate this issue.
