### ISSUE TITLE
E2E case 211_NO_S2_elec_add failed without OpenMP

### ISSUE THREAD

**Issue by caic99** [deepmodeling/abacus-develop#945]
## Describe the Bug
Compile the abacus program with cmake option use_openmp=off, and run the integrate test. The test result deviates on case 211_NO_S2_elec_add: etotref cal=-203.73475113 ref=-203.75086921 deviation=-0.01611808

## To Reproduce
1. build abacus with `-DUSE_OPENMP=0` and install. Note: this will fail due to a trivial compilation error; I'll submit a patch for it ASAP.
2. run test on this case with `./Autotest.sh -r 211_NO_S2_elec_add`.

**Comment by caic99** [comment]
Related issue: #886
The difference is the program is compiled with openmp support in #886, but totally without openmp(without `-fopenmp` flag, `_OPENMP` definition) here.

**Comment by LiuXiaohui123321** [comment]
> ## Describe the Bug
> Compile the abacus program with cmake option use_openmp=off, and run the integrate test. The test result deviates on case 211_NO_S2_elec_add: etotref cal=-203.73475113 ref=-203.75086921 deviation=-0.01611808
> 
> ## To Reproduce
> 1. build abacus with `-DUSE_OPENMP=0` and install. Note: this will fail due to a trivial compilation error; I'll submit a patch for it ASAP.
> 2. run test on this case with `./Autotest.sh -r 211_NO_S2_elec_add`.

@dyzheng I've calculated the total energy of this example using abacus v2.1.0, and the result is -203.734751128.
Please check the ref result.

**Comment by caic99** [comment]
> @dyzheng I've calculated the total energy of this example using abacus v2.1.0, and the result is -203.734751128. Please check the ref result.

Hi @LiuXiaohui123321 ,
Thank you for your test result! The reference value is calculated with default option(openmp on), thus this problem may lies in openmp-related region.

**Comment by dyzheng** [comment]
Fixed in #1549
