### ISSUE TITLE
Why ABACUS initialize plane wave basis when choosing the basis type as LCAO?

### ISSUE THREAD

**Issue by gawcista** [deepmodeling/abacus-develop#978]
I noticed that even if the `basis_type` is chosen to be `lcao`, ABACUS would also run INIT PLANEWAVE. 
For mpi calculations, if too many cores is used, the calculation would be aborted and return "some processor has no plane waves!" 
Why could that happen? Besides, where can I get the numbers of plane waves/orbitals?

**Comment by Qianruipku** [comment]
LCAO calculation also need plane waves, like calculations of Hartree potential and local potential.
Plane waves are related to FFT. We can see FFT grids output on the screen:
![image](https://user-images.githubusercontent.com/76200646/171618930-a87ac2f7-8629-450a-a47c-4b88ed477f47.png)
ABACUS executes FFT  in parallel. We will divide the FFT grids in the z-directions. The number of cores should be larger than the number of z-direction grids.  In the future we will optimize it and make the number of cores able to be larger than z-direction grids.

**Comment by Qianruipku** [comment]
LCAO calculation also need plane waves, like calculations of Hartree potential and local potential.
Plane waves are related to FFT. We can see FFT grids output on the screen:
![image](https://user-images.githubusercontent.com/76200646/171618930-a87ac2f7-8629-450a-a47c-4b88ed477f47.png)
ABACUS executes FFT  in parallel. We will divide the FFT grids in the z-directions. The number of cores should be no larger than the number of z-direction grids.  In the future we will optimize it and make the number of cores able to be larger than z-direction grids.

**Comment by Qianruipku** [comment]
The numbers of plane waves/orbitals can be found in the running.log file.

**Comment by gawcista** [comment]
> 

Thanks for your reply! It helps a lot to me.
I noticed that there's an additional line below that begins with "UNIFORM GRID DIM(BIG)" . Is this equivalent to the "fine" FFT grid in PAW method?

**Comment by Qianruipku** [comment]
It will be used by grid integration in LCAO and we do not use it in pw basis yet. I do not know clearly what the "fine" FFT is. Maybe it is different.
