### ISSUE TITLE
ABACUS to Wannier90 error

### ISSUE THREAD

**Issue by sgyang345** [deepmodeling/abacus-develop#981]
I have some problems when I using the ABACUS interface to Wannier90 calculations.

When I repeated the wannier example calculation provided by ABACUS, I tried to use the LCAO calculation to docking with Wannier90. However, there is always an error when reading seedname.nnkp file for ABACUS NSCF calculation, as shown in the following figure.

Description:
Reading seedname.nnkp file, setting towannier90=1, calculation error.

Software Version used:
ABACUS: 2.2.2
Wannier90: 3.1.0

![1](https://user-images.githubusercontent.com/68679106/171551576-df2961a0-e82e-4a72-a3fa-2dffcc282459.png)

[ABACUS_towannier90-test.zip](https://github.com/deepmodeling/abacus-develop/files/8820640/ABACUS_towannier90-test.zip)

**Comment by dyzheng** [comment]
I have tested case: examples/wannier90-example/ABACUS_towannier90 with v2.2.3, and didn't find error that you mentioned? 
Can you repeat your error using v2.2.3?

**Comment by sgyang345** [comment]
Thanks a lot for your test!

I have used v2.2.3 for LCAO test calculation, and found that the error still occurs.

Note: PW calculations work fine, but LCAO nscf calculations errors.

[LCAO_test.zip](https://github.com/deepmodeling/abacus-develop/files/8868017/LCAO_test.zip)

**Comment by dyzheng** [comment]
Thanks for your report!
I have repeated this error and fixed it in #1010 , v2.2.4 which will be published today would be ok for this issue.
