### ISSUE TITLE
Convergence difficulty in calculation with VDW DFT-D2 correction

### ISSUE THREAD

**Issue by gawcista** [deepmodeling/abacus-develop#987]
As described in the title, by setting `vdw_method  d2`, the geometry relaxation can not converge. The `LARGEST GRAD`  would just diverge:
```
>grep "LARGEST GRAD" out.m
 LARGEST GRAD (eV/A)  : 4.451e-01
 LARGEST GRAD (eV/A)  : 5.810e-01
 LARGEST GRAD (eV/A)  : 5.597e-01
 LARGEST GRAD (eV/A)  : 8.053e-01
 LARGEST GRAD (eV/A)  : 1.157e+00
 LARGEST GRAD (eV/A)  : 3.025e+00
...
```

Structural description:
Twisted bilayer SnS (728 atoms)
The initial structure has been well relaxed (EDIFFG = -0.01 eV/Å) with the same input parameters with vasp.6.3.1 (PBE)
The input files for ABACUS can be found here: [pack.zip](https://github.com/deepmodeling/abacus-develop/files/8837741/pack.zip)
I guess this could result from a bug of dft-d2 method. 

P.S. I noticed that someone has submitted similar issues before: https://github.com/abacusmodeling/abacus-develop/issues/134

**Comment by caic99** [comment]
Fixed by https://github.com/abacusmodeling/abacus-develop/pull/151.
