### ISSUE TITLE
Bug: vdwd2 error in relax calculation

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#988]
## Describe the Bug
In case tests/integral/250_NO_KP_CR_VDW2 , change the parameters in INPUT file:
"relax_nmax  10
 ecutwfc         50"

The result of energy is wrong that:
"
final etot is -4134.78204688 eV
 final etot is -4135.299817967871 eV
 final etot is -4137.768840162431 eV
 final etot is -4149.499539458167 eV
 final etot is -4146.149897072450 eV
 final etot is -4134.997086282970 eV
 final etot is -4141.315269405296 eV
 final etot is -4326.818759075427 eV
 final etot is -10150.855605772877 eV
 final etot is -201909.573880494543 eV
"

**Comment by dyzheng** [comment]
It is ok for same case with vdwd3:
"
 final etot is -4134.54391714 eV
 final etot is -4134.569664437586 eV
 final etot is -4134.618813727812 eV
 final etot is -4134.619072748452 eV
 final etot is -4134.621710423961 eV
 final etot is -4134.562716235854 eV
 final etot is -4134.621075682121 eV
 final etot is -4134.621684534608 eV
 final etot is -4134.621739221550 eV
 final etot is -4134.621806331660 eV
"

**Comment by caic99** [comment]
Duplicate issue: https://github.com/deepmodeling/abacus-develop/issues/987
