### ISSUE TITLE
Multi-core lcao calculations get stuck when USE_OPENMP is ON

### ISSUE THREAD

**Issue by YuLiu98** [deepmodeling/abacus-develop#992]
## Describe the Bug
If abacus is complied with USE_OPENMP setting ON, multi-core lcao calculations get stuck in the first electronic step.
![f15hyjBFyR](https://user-images.githubusercontent.com/77716030/172112664-d7a4a911-69f3-4fe3-9e02-683da891401c.jpg)

If USE_OPENMP is OFF, everything is OK.

## Expected behavior
USE_OPENMP should be set to OFF by default if openmp does not work.

**Comment by caic99** [comment]
Hi @YuLiu98 ,
Is this a common problem on every LCAO case? How many threads and processes are you using?

**Comment by YuLiu98** [comment]
> Hi @YuLiu98 , Is this a common problem on every LCAO case? How many threads and processes are you using?

At least it is a common problem for all lcao cases I tested.

I used 4 processes and set `export MKL_NUM_THREADS=1`.

**Comment by caic99** [comment]
> I used 4 processes and set `export MKL_NUM_THREADS=1`.

@YuLiu98 Would you set `OMP_NUM_THREADS=1` and try again? This issue might be related to #972 .

**Comment by YuLiu98** [comment]
> > I used 4 processes and set `export MKL_NUM_THREADS=1`.
> 
> @YuLiu98 Would you set `OMP_NUM_THREADS=1` and try again? This issue might be related to #972 .

Thank you! Now it works with `OMP_NUM_THREADS=1`. Maybe this issue can be closed?

**Comment by caic99** [comment]
Duplicate issue: #972 .
