### ISSUE TITLE
Memory leak in MD calculation

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#994]
## Describe the Bug
In case: tests/integral/220_NO_KP_MD_NVE 
Version v2.2.3
Change parameter "md_nstep 20" and run "/usr/bin/time -v mpirun -np 4 abacus 2>time.log |tee log" and check file time.log for number after word "Maximum resident set size". 
The maximum memory number continuously increase when md steps increase.

**Comment by caic99** [comment]
Address Sanitizer result shows the memory leak happened here:

https://github.com/deepmodeling/abacus-develop/blob/999bdee1e4e5af702ea2d9f0ecabcacb82409dbf/source/src_lcao/gint_tools.cpp#L99-L100

https://github.com/deepmodeling/abacus-develop/blob/999bdee1e4e5af702ea2d9f0ecabcacb82409dbf/source/src_lcao/gint_tools.cpp#L19

**Comment by caic99** [comment]
This failure can not be reproduced on latest develop version. @dyzheng Would you try on the latest branch?
